.cypress/cypress/integration/highwaysengland.js, web/cobrands/fixmystreet/fixmystreet.js
On mobile, the message controller code moves an asset not found message to within the map box (given that takes up the whole page) and displays it based upon a map-page class. This class was added to subsequent map pages (e.g. asset selection), but not the first map page, which meant if the asset selection failure happened then (e.g. you have to click on a road to continue), the Continue button was hidden but no message was shown, which was confusing.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2325
=> Handle first map page asset not found better.

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Develop.pm, t/app/controller/alert_new.t, templates/email/default/_email_comment_list.html
When showing a list of comments in HTML emails we previously didn't show anything for updates that were left anonymously. This led to some confusion about which text related to which update.
This change means that anonymous comments will show the text "Posted anonymously" next to them, which should make things a bit clearer.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2236
=> Make anonymous comments clearer in alert emails

templates/web/base/noise/confirmation.html, web/cobrands/hackney/base.scss, web/cobrands/hackney/layout.scss, web/cobrands/sass/_noise.scss
Adds a banner to the top of the Hackney noise reporting form’s final page, prompting people to sign up to help us with our noise case management research in June:
@dracos could you test this out, and check it appears on the right page and looks like this? ⬆️ I had to hack around a bit to test this out (submitting a noise report in my setup fails) so designed this on a different page and then moved it into the `confirmation.html` template after the fact. Should all work, but just need someone to check 🙂 
=> [Hackney] Noise research banner on final noise reporting screen

bin/fixmystreet.com/bromley-reconcile-dd, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/Integrations/Pay360.pm, t/app/controller/waste.t, t/cobrand/bromley.t, t/integrations/pay360.t
Fetch a list of recent Direct Debit payments and match them to up to the
relevant report in FixMyStreet and then process accordingly.
For new and ad-hoc payments (the latter is for adding a bin half way
through) find the matching report and confirm it.
For renewals and cancellations we need to find the original subscription
report and then use that to create a new report that then cancels or
renews the subscription.
Issues warnings for reports not handled.
=> [Bromley] waste direct debit payment processing

bin/fixmystreet.com/buckinghamshire-flytipping, bin/fixmystreet.com/hackney-noise, perllib/FixMyStreet/App/Controller/Noise.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Script/UK/AutoClose.pm, t/Mock/Hackney.pm, t/Mock/MapIt.pm, t/app/controller/noise.t, t/script/autoclose.t
Refactors the Bucks script to be shared (and removes Bucks district code). Also stores all MapIt areas in noise like normal reports. [skip changelog]
=> [Hackney] Noise closing script

perllib/FixMyStreet/App/Controller/Noise.pm, perllib/FixMyStreet/App/Form/Noise.pm, perllib/FixMyStreet/App/Form/Waste.pm, perllib/FixMyStreet/App/Form/Wizard.pm, t/app/controller/noise.t, templates/web/base/noise/existing.html
Store a random value in both session and form, and mandate that they
always match; on successful submission, delete the value from the
session so that any resubmission of the same form will error.
=> [Noise] Prevent duplicate form submission.

templates/web/buckinghamshire/report/new/inline-tips.html
Bucks have requested that we add an extra bullet point to the new report form, under the report description checkbox.
Fixes https://github.com/mysociety/societyworks/issues/2381
=> [Buckinghamshire] Add bullet point under report description field

web/cobrands/bromley/assets.js
Add parks layer to Bromley as a non-interactive layer that's displayed for the **Parks and Greenspace** category.
The relevant config was added to the fixmystreet.com repo in https://github.com/mysociety/fixmystreet.com/pull/22.
Part of https://github.com/mysociety/societyworks/issues/2282
=> [Bromley] Add parks asset layer

perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm, t/app/script/archive_old_enquiries.t
This prevents a huge backlog of unsent updates building up that don’t actually need to be sent anywhere.
=> [Oxfordshire] Archive script marks comments sent for Open311 reports

perllib/FixMyStreet/Cobrand/Peterborough.pm
Peterborough have a number of Open311 categories marked as ‘inactive’ on the site
pending the launch of a new integration. For some reason these categories were
omitted from the service list from Open311 adapter for a short period, which
resulted in the inactive categories being deleted. When they subsequently
reappeared in the service list, they were reinstated as ‘confirmed’ categories
instead of going back into the ‘inactive’ state. This meant users could unexpectedly
raise reports in these new categories.
For https://github.com/mysociety/societyworks/issues/2391
=> [Peterborough] Don’t delete inactive Open311 categories

perllib/FixMyStreet/Cobrand/Bromley.pm
Default to an empty array if the event has no data to avoid errors.
=> [Bromley] handle waste events with no data

bin/bromley/make-parks-database, perllib/BromleyParks.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
Bromley have provided us with a spreadsheet of park names/aliases and the corresponding easting and northing. This change integrates that dataset into the location search on the homepage.
The code for this is largely inspired by/based on the Highways England junction lookup code that was added in #2918.
Fixes https://github.com/mysociety/societyworks/issues/2280
=> [Bromley] Park name lookup

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Contact.pm, t/app/controller/contact.t
Previously we were sending emails from the recipient's address if we detected dmarc on the email entered into the contact form. This caused issues if the other end also had dmarc, since it would detect the incoming emails as spoofing attempts and reject them.
To avoid these issues change the contact form to send from the do-not-reply email address if the sending email address domain uses dmarc.
Fixes https://github.com/mysociety/societyworks/issues/2344
=> Send contact form email from fixmystreet.com email if dmarc

web/cobrands/centralbedfordshire/assets.js
Fixes https://github.com/mysociety/societyworks/issues/2403 [skip changelog]
=> [Central Beds] Assign street light ID to correct field.

CHANGELOG.md, web/cobrands/fixmystreet/fixmystreet.js
If going back from a report page to a list page, a marker refresh would
be triggered twice, once by the popstate, once by display_around. As
only one of those had use_page set, it would at best make two identical
requests, at worst return to page 1 of results whatever page it should
have been showing.
If we're already on a list page, trigger the refresh in popstate as
currently; if not, skip that trigger and rely on the refresh that will
be called in display_around.
An alternative solution would have been to change the refresh in
dispaly_around to use the same debounce as the popstate trigger, which
would fix the issue in that it would only be called once, but introduce
a delay waiting for the end of the debounce time.
Also set use_page when going back to initial state in case that wasn't …
=> Only trigger one refresh going Back to list view.

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/SendReport/Email/Highways.pm, t/cobrand/highwaysengland.t, t/sendreport/email/highways.t
Turns out #3474 worked for HE cobrand but not .com (see comment at https://github.com/mysociety/fixmystreet/blob/0f4f1b48e471f6827be1e1928c5c9f6f60c4054a/perllib/FixMyStreet/Cobrand/UK.pm#L377 ). So here's a new way of doing the same thing.
Due to not setting cobrand handler for HE (for correct email templates) the munge function was not being called if the report was made on .com. As HE has its own SendReport handler, we can put the same code in there instead for both sites.
=> [Highways England] Move fallback lookup to sender.

templates/web/base/noise/confirmation.html
We’ve closed the old (alpha testing) signup form, and now want to redirect people to a new (beta testing) form that’ll stay up throughout the Summer.
=> [Hackney] Update URL for citizen beta testing signup form

templates/email/fixmystreet.com/_submit_footer.html, templates/web/fixmystreet.com/reports/summary.html
I've updated the copy to remove the webinar link and changed it to a request a demo link. 
=> Remove webinar link from council report emails

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste.t
Because expired services can show up do this differently by checking for
services that show up on the bin list. If it's not there then it's not
active. Previously we were listing expired services that weren't on the
bin list as active which meant the garden waste subscribe link wasn't
displayed
=> [Bromley] fix available services call for waste

templates/web/borsetshire/front/footer-marketing.html, templates/web/fixmystreet.com/front/footer-marketing.html
Updated the link to go directly to the FixMyStreet Pro page instead of SocietyWorks homepage
=> Update Pro footer link on FixMyStreet homepage

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
DA5 2BD is split over Bexley and Dartford but the centroid is in
Dartford so using it results in a "not in bexley" error. So catch this
and return a hardcoded just inside Bexley result.
Fixes mysociety/fixmystreet-commercial#2418
=> [Bexley] override split postcode so it's inside Bexley

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, t/cobrand/highwaysengland.t
The update name is generally always the body name for staff, they want to see the real user name. [skip changelog]
=> [Highways England] Show staff user name in CSV export.

perllib/FixMyStreet/Cobrand/Greenwich.pm
Re-opening reports is turned off so we should also turn off
questionnaires.
Fixes mysociety/societyworks#2425
=> [Greenwich] turn off questionnaires

bin/fixmystreet.com/process_update_file, perllib/FixMyStreet/Script/ProcessUpdateFile.pm, perllib/Open311/GetServiceRequestUpdates.pm, perllib/Open311/UpdatesBase.pm, t/script/process_updates_file.t
Adds the option to suppress alerts, dry run by default and also print out summary statistics
=> add more options to process update file script

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
If a staff user can view private reports then let them see the Waste
categories in the all reports filter.
Fixes mysociety/societyworks#2430
=> [Bromley] let staff with enough permission filter on waste reports

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
Avoid problems if someone has tried to create a direct debit payment and
failed, and then succeeded by hiding any matching records that were not
confirmed and not matched.
=> [Bromley] only process one row for a dd record

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste.t
This allows us to hide failed direct debit subs and not have them effect
renewal by other means, or by trying again.
Fixes mysociety/societyworks#2441
=> [Bromley] hidden direct debit subs should not prevent renewal

perllib/FixMyStreet/App/Controller/Waste.pm
Occasionally these are too long and we end up sending scientific
notation to mapit and hence getting errors.
=> [Bromley] truncate co-ords fetched from Echo

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Users.pm, t/app/controller/admin/users.t
Fixes #3295 
PROBLEM: Admin can create a user and put in a landline phone number and verify it if reporting on behalf of a user. But phone numbers are expected to be mobile numbers (for confirming number by SMS). Editing a user created by an admin in this way leads to the phone number being revalidated and the edit is rejected, whatever it is, if the number is a landline.
SOLUTION: When submitting an 'edit user' form, we will no longer revalidate the phone number if the phone number is the same as the original. If the phone number is changed, revalidation will take place.
TESTS: Test if changing the user name on a user with a verified landline succeeds. Test if changing the phone number from one landline to another fails.
=> Remove revalidation of verified landline number

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste.t, templates/web/bromley/waste/services.html
At his point the user should renew and change the number of bins while
renewing. This avoids complications with modifications and then
renewals.
[skpi changelog]
=> [Bromley] prevent garden sub modification during renewal window

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
Highways England have requested that reports made before 9th November
aren't visible on their cobrand.
Fixes https://github.com/mysociety/societyworks/issues/2445
=> [Highways England] Add cut off date for problems

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
It's possible for a user to create a direct debit that starts as a
renewal if the first time they use the system they renew an existing
subscription using direct debit. Previously we'd assumed that there had
to be a New subscription as the first direct debit interaction so this
resolves that.
=> [Bromley] cope with direct debit renewals that started as a renewal

t/cobrand/tfl.t, templates/email/default/_email_bottom.html, templates/email/hackney/_email_bottom.html
Check for defined-ness so empty footer can be used.
=> [TfL] [Hounslow] Stop default text in submit email

perllib/FixMyStreet/Cobrand/Rutland.pm, t/cobrand/rutland.t, templates/web/base/report/new/category.html, templates/web/base/report/new/subcategories.html
Rutland have started including some HTML hint text in their Salesforce instance that they want to display on FixMyStreet.
I've added the Salesforce bits to open311-adapter in https://github.com/mysociety/open311-adapter/pull/188, so this pull request follows on/is linked to that pull request.
Part of https://github.com/mysociety/societyworks/issues/2206
=> [Rutland] Show group and category hint text from Salesforce

perllib/FixMyStreet/Cobrand/Bromley.pm
It's possible for the user for a subscription not to have a name so fall
pack to the one on the report to avoid DB errors.
=> [Bromley] make sure duplicated report has a name

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
Bromley have requested that we add the role into the open311 report_title field so that they can use it to update the point of contact field in their Confirm instance.
Fixes https://github.com/mysociety/societyworks/issues/2450
=> [Bromley] Add contributing user's role to open311 report_title

t/cobrand/bexley.t, templates/web/bexley/report/_council_sent_info.html
Bexley have requested that the FixMyStreet ID be visible on report pages. This adds the **Council ref** text along with the FMS ID for the report.
Fixes https://github.com/mysociety/societyworks/issues/2464
=> [Bexley] Show FixMyStreet report ID as Council ref

CHANGELOG.md, bin/export-import-data
Enables transferring of response templates between two installs.
=> script to transfer response templates

perllib/FixMyStreet/Cobrand/TfL.pm, web/cobrands/tfl/assets.js
[TFL] Add an extra category of "Drain Cover - Missing or Damaged" to tfl red route only list.
https://github.com/mysociety/societyworks/issues/2503
=> [TfL] Add drain cover missing category to tfl red route list

.cypress/cypress/integration/bathnes.js, bin/fixmystreet.com/fixture, web/cobrands/fixmystreet/fixmystreet.js
An uncaught exception was being thrown by extra data which
included a space in the code (name), e.g. 'public safety',
when the user chose a report category.
+ **fixmystreet.js**: fix applied (single quotes around code name)
+ **fixture**: BathNES has new categories and extra data for testing
+ **bathnes.js**: additional Cypress test to trigger uncaught exception by clicking between road responsibility categories
+ **cypress.json**: fix to ensure Cypress tests run (is this appropriate?)
Fixes mysociety/fixmystreet#3308
=> Handle spaces in code names of extra data.

CHANGELOG.md, docs/sites.md
Outdated information on https://fixmystreet.org/sites/ (Ticket: https://github.com/mysociety/societyworks/issues/2481)
A number of sites listed on the fixmystreet.org/sites page as running fixmystreet are no longer connecting, so move them into the honourable mentions part of the page.
I'm not aware of how to test this, but as mainly text edits, hopefully safe.
=> Move non connecting sites to honourable mentions

perllib/FixMyStreet/Cobrand/Bromley.pm
Also default to returning 0 not undef
=> [Bromley] catch missing ChildData when getting sub quantity

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin.pm, t/app/controller/admin/reportextrafields.t
Ordering of dropdown list options is now sorted numerically on the index position. This means the order will be that expected by the user when creating the options.
https://github.com/mysociety/societyworks/issues/2511
=> Fixes issue with not being able to order dropdowns in extra questions

cpanfile, cpanfile.snapshot
HTML::Selector::Element makes tests less
brittle, easier to write and more idiomatic
by allowing content and values to be searched
for and specified via the Selectors API.
This allows us to avoid having to use whole
strings of HTML for comparison, which could
break if minor changes are made.
It also makes it much easier to find and check
values in specific areas of the page e.g. to
verify that a particular problem in a list is
showing the right value, when the wrong value
could also be present in another problem listing
also showing which would be caught by
$mech->content_contains().
POD: https://metacpan.org/pod/HTML::Selector::Element
relates to mysociety/societyworks#2455
Screenshots or …
=> Add HTML::Selector::Element to test modules

perllib/FixMyStreet/Cobrand/Zurich.pm, t/cobrand/zurich.t
The lastupdate column wasn't being populated in the CSV. After some investigation Matthew noticed that there was an errant space in the field name, which meant that column wasn't being populated.
This change removes that space and adds a test to check that this column is correctly populated.
Fixes https://github.com/mysociety/societyworks/issues/2550
=> [Zurich] Fix bug with lastupdate not appearing in CSV

t/app/controller/waste.t, templates/web/base/waste/bin_days.html
The code was only showing the garden waste subscribe link if its own terms were met, plus if any request or reporting was allowed. It was not always showing when needed, e.g. if no reporting was allowed and you had requested new containers for every service.
Fixes https://github.com/mysociety/societyworks/issues/2517 [skip changelog]
=> [Waste] Show garden sub link even if no reporting.

templates/email/default/waste/direct_debit_in_progress.html, templates/email/default/waste/direct_debit_in_progress.txt
Updated text in direct_debit_in_progress email templates to match true lead times. 
For https://mysocietysupport.freshdesk.com/a/tickets/1401
=> [Bromley] Update DD lead time text after garden waste subscription

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/cobrand/peterborough.t
If a category change means the backend system has changed, resend.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2154
=> [Peterborough] Resend if backend changes.

perllib/FixMyStreet/App/Controller/Admin/Reports.pm, t/app/controller/admin/search.t
There is an issue with Number::Phone that means it is matching e.g. 402609 as a Jersey phone number. Reported and behaviour improved at https://github.com/DrHyde/perl-modules-Number-Phone/issues/101, but until a new release, move the searches around so a ref search takes precedence. [skip changelog] For FD#1398
=> Fix issue searching for numeric IDs.

perllib/FixMyStreet/App/Controller/Contact.pm, perllib/FixMyStreet/SendReport/Email.pm, t/app/controller/contact.t, t/app/model/problem.t
This means we can choose in configuration to set a cobrand or cobrands to always use Reply-To for the user's details and our own email (matching the SMTP envelope) in the From, regardless of DMARC settings.
[skip changelog] For Freshdesk https://mysocietysupport.freshdesk.com/a/tickets/1472 (whereby a recipient is performing a DMARC check regardless of actual DMARC settings)
=> Add feature for always using Reply-To in emails.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t, templates/web/base/report/new/form_report.html, templates/web/bromley/report/new/after_detail.html
Adds private comments field to the report form for people with the `can_contribute_as_body` permission. This is then sent over open311 in the description field.
Bromley also want this field adding to updates, but I'm going to do that as a separate change.
Part of https://github.com/mysociety/societyworks/issues/2293
=> [Bromley] Private comments for reports

perllib/FixMyStreet/App/Controller/Report/Update.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/Open311/PostServiceRequestUpdates.pm, t/cobrand/bromley.t, templates/web/base/report/update/form_update.html, templates/web/bromley/report/update/after_update.html
Adds a private comments box for updates and sends those comments over open311 to Bromley's backend.
Fixes https://github.com/mysociety/societyworks/issues/2293
=> [Bromley] Private comments for updates

perllib/Utils/Email.pm, t/utils/email.t
To cope with the case where the subdomain does not have its own DMARC configuration. 
Fixes https://github.com/mysociety/societyworks/issues/2594
=> Look up organizational domain in DMARC checking.

perllib/FixMyStreet/Cobrand/Shropshire.pm
* Categories with disabled forms should be usable by staff
=> [Shropshire] Set blocked categories to be staff usable

CHANGELOG.md, docs/_includes/admin-tasks-content.md, perllib/FixMyStreet/App/Controller/My.pm, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/DB/Result/Body.pm, t/app/controller/admin/users.t, t/app/controller/my_assigned.t, t/app/controller/report_inspect.t, templates/web/base/admin/_report-assignment.html, templates/web/base/admin/problem_row.html, templates/web/base/admin/reports/edit.html, templates/web/base/report/_inspect.html, templates/web/base/report/_item.html, templates/web/base/report/_item_small.html, templates/web/base/report/inspect/_assignment-options.html, templates/web/base/report/inspect/assignment.html, templates/web/base/reports/_bulk-assign.html, templates/web/base/reports/_problem-list.html, templates/web/base/reports/body.html, web/cobrands/fixmystreet/staff.js, web/cobrands/sass/_base.scss, web/cobrands/sass/_report_list.scss
Depends on https://github.com/mysociety/fixmystreet/pull/3562
Fixes https://github.com/mysociety/societyworks/issues/2455
_Please check the following:_
=> Cheshire east inspector tool upgrade

templates/web/highwaysengland/around/_report_banner.html, templates/web/highwaysengland/around/intro.html, templates/web/highwaysengland/report/new/councils_text_all.html, templates/web/highwaysengland/report/new/form_heading.html, templates/web/highwaysengland/report/new/inline-tips.html, templates/web/highwaysengland/report/new/top_message.html, web/cobrands/highwaysengland/base.scss, web/cobrands/highwaysengland/layout.scss, web/cobrands/sass/_layout.scss
Freshdesk ticket https://mysocietysupport.freshdesk.com/a/tickets/1534
- Homepage – replace "problem" with "maintenance issue" in main heading
- Homepage – add yellow warning box about emergencies and incidents
- New report page – replace "problem" with "maintenance issue" in main heading
- New report page – "maintenance issue" in blue box, not just "issue"
- Reporting form – new wording about public details
- Reporting form – new "do and don’t" tips below descripton
- Reporting form – "How did you hear about this reporting tool" not "about us"
I’m really not a fan of how messy this has made the homepage hero element, but it’ll do as a temporary fix, until we implement the rest of the requested changes.
=> [National Highways] High priority text changes

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
This is a manually-added extra field in a limited number of categories.
=> [Peterborough] Don’t send extra_detail over Open311

web/cobrands/merton/base.scss, web/cobrands/merton/layout.scss
Additional style changes for Merton for accessibility and branding compliance. 
- 'click map to report a problem' -> bold
- 'skip this step' -> black
- 'here are some other nearby reports' -> color: #666666
- 'Fixed/Closed' (problem state) labels -> bg : #666666
- report title text -> black
- another type of big green button (.btn-primary) added
to Merton's preferred big jade green button styles
=> [Merton] Additional CSS changes for accessibility

perllib/FixMyStreet/DB/Result/Problem.pm, t/cobrand/shropshire.t, templates/web/shropshire/tokens/_confirm_problem_council_id.html
Shows the Confirm ID publicly on the report page:
(Also removes the FMS ID from the problem confirmation page where it's shown by default.)
For https://github.com/mysociety/societyworks/issues/2641
=> [Shropshire] External ID display

web/cobrands/buckinghamshire/base.scss
Oh look, here’s [another one](https://github.com/mysociety/fixmystreet/pull/3650)!
Fixes mysociety/societyworks#2709
@lizettal / @ClareA it might be worth scheduling a ticket for the next design sprint, to check through these buttons on every cobrand. I bet there’ll be one or two more that exhibit the same issue.
=> [Buckinghamshire] Fix illegible text colour for pagination links

web/cobrands/shropshire/base.scss
Looks like this now:
Makes me wonder whether this bug might also be present on other recent cobrands, where the primary button colour has been changed to somethign dark…
=> [Shropshire] Fix illegible grey text colour for pagination links

perllib/FixMyStreet/Cobrand/Shropshire.pm, t/cobrand/shropshire.t
Fix so 'Abandoned since' field will be a date type field to stop text entry
=> [Shropshire] Override field type to date for Abandoned since field

web/cobrands/shropshire/assets.js
'central_asset_id' to populate from correct field in wfs layer
Change asset item from 'grit bin' to 'salt bin' to reflect category name
Removes unused 'feature_id' fields
Removes unused 'central_asset_id' fields
'central_asset_id' on traffic signal asset to populate from correct field in wfs layer.
=> [Shropshire] Fix defaults for central_asset_id field and prune fields

web/cobrands/sass/_base.scss
Super quick fix, in core, for everyone, but spotted by the team at Shropshire. More noticeable `:focus` style for the `#key-tools` links at the bottom of the map page and report page sidebars.
=> Focus style for #key-tools links/buttons

perllib/FixMyStreet/Cobrand/Shropshire.pm, t/cobrand/shropshire.t
The 'Abandoned since' field requires input or is rejected by confirm.
Request to make 'Registration Mark' mandatory too.
=> [Shropshire] Set 'Abandoned since field to mandatory

perllib/FixMyStreet/Cobrand/Hounslow.pm
When a category with a send_method of undef is edited in the admin
panel, the send_method is updated to an empty string. Adding this
to the query in categories_restriction() prevents the categories
disappearing after any update.
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1604
=> [Hounslow] fix admin-panel-edited categories disappearing

perllib/Open311/UpdatesBase.pm, t/open311/getservicerequestupdates.t
Do not look for state change templates if only the external status code has changed.
=> [Open311] Improve template lookup behaviour.

conf/general.yml-example, perllib/Open311.pm, t/open311.t
=> Add delay before FMS's Open311 `GET service_request_id for a token` call 

perllib/FixMyStreet/Cobrand/Merton.pm, templates/web/merton/before_wrapper.html, templates/web/merton/header_extra.html, templates/web/merton/tracking_code.html
A group of key configurations and code updates towards ensuring the Merton cobrand fits the agreed technical specification. 
for mysociety/societyworks/issues/2629 
for mysociety/societyworks/issues/2628
=> [Merton] Milestone 63: some configuration for Merton cobrand

CHANGELOG.md, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Reporting.pm, t/app/controller/dashboard.t, t/cobrand/bromley.t
Removes slashes from category names used in file name for csv download.
Backward slash makes the file not retrievable.
Forward slash makes the file not saveable.
https://github.com/mysociety/societyworks/issues/2679
=> Stop slashes breaking csv report downloads

templates/web/shropshire/footer_extra.html, web/cobrands/shropshire/base.scss, web/cobrands/shropshire/layout.scss
Adds a new footer to the Shropshire cobrand, with the required links:
=> [Shropshire] Privacy and accessibility links in footer

web/cobrands/fixmystreet-uk-councils/roadworks.js
If the roadworks message had already been shown, but you e.g. change category to something for which the filter returns false, the message would not be removed. Spotted in https://mysocietysupport.freshdesk.com/a/tickets/1558 but nothing to actually do for that ticket.
=> [UK] Fix removal of roadworks message.

perllib/FixMyStreet/DB/Result/Problem.pm, t/cobrand/merton.t, templates/web/merton/tokens/_confirm_problem_council_id.html
Replaces mention of the numeric FMS problem ID with Merton's 'SRQ' code from their MS Dynamics CRM as the case reference number. 
to fix mysociety/societyworks/issues/2621
=> Replace FMS problem ID with Merton SRQ case reference 

CHANGELOG.md, web/cobrands/sass/_base.scss
I am totally at a loss as to when this bug was introduced, or what caused it. The stacking clearly worked fine when the new JavaScript-powered pop-over menu was added 12 months ago (in a01e927), so something must have changed, in core, since then.
I think the absolute positions of everything on the map page have always been relative to the viewport (rather than there being any `position: relative` parents). If so, it can’t be that a positioned parent has been removed, causing the `z-indexes` to no longer be in the right stacking context.
The `z-index: 1` for `.map-fullscreen #map_box` was [set 5 years ago](https://github.com/mysociety/fixmystreet/blame/master/web/cobrands/sass/_base.scss#L2171) in a5ef113, with a comment: `// stack above positioned elements later on the page (eg: …
=> Explicit z-indexes to stack mobile menu above map

perllib/FixMyStreet/Cobrand/Merton.pm, t/cobrand/merton.t
Enable anonymous reporting for the Merton cobrand and a test to ensure it's working as expected.
The test is copied from TfL's one, which seemed to be testing the right things.
Fixes https://github.com/mysociety/societyworks/issues/2615
=> [Merton] Allow anonymous reports

templates/web/shropshire/footer_extra.html
Turns out #3683 linked to the wrong Privacy page.
=> [Shropshire] Footer link to FMS privacy page, not Shropshire one

web/cobrands/fixmystreet/admin.js
The upgrade to jQuery 3 broke the fetching of val() on the roles
multiple select input, as the code assumed this returned null if
no role was selected, whereas now it returns an empty array.
I've checked all the other uses of val() and can't see any others on a select multiple.
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1634
[skip changelog] (as upgrade was before last release)
=> Fix permissions setting in admin.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
Client has requested that the default map filters are changed to "Open" and "Fixed".
Fixes https://github.com/mysociety/societyworks/issues/2766
=> [Buckinghamshire] Change default map filters

templates/email/buckinghamshire/other-reported.html, templates/email/buckinghamshire/other-reported.txt
Removes the Covid-19 text that appears when a report is made that was warning that the time taken to fix reports could be longer due to Covid-19
https://mysocietysupport.freshdesk.com/a/tickets/1657
=> [Buckinghamshire] Removes Covid-19 text from report confirmation

perllib/FixMyStreet/Cobrand/Merton.pm, t/cobrand/merton.t
Hide 'service' input in inspector toolbar which is an artefact of sending service field via Open311 plus endpoint settings. 
To do this, simply save the service field as an additional, albeit redundant extra data field. 
=> [Merton] save service to extra data to hide spurious service field

perllib/FixMyStreet/Cobrand/Merton.pm, templates/web/fixmystreet-uk-councils/about/_sidebar.html
- Removed FMS contact form _link_ from privacy policy page.
- Set Merton cobrand to only allow contact form for abuse reports.
fixes mysociety/societyworks/issues/2629
=> [Merton] drop FMS contact form from privacy page

templates/web/merton/tracking_code.html
Getting an error on the Merton cobrand:
> Refused to execute inline script because it violates the following Content Security Policy directive: “script-src ‘self’ ‘unsafe-inline’ ‘nonce-ef5d8d05655b1d495b666235f0d57b80’ https://www.googletagmanager.com”. Note that ‘unsafe-inline’ is ignored if either a hash or nonce value is present in the source list.
I believe adding this nonce attribute should fix that.
=> [Merton] Add nonce attribute to Google Tag Manager script

perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/Merton.pm
This ensures that reports have a service and that the service is persisted to extra data.
=> [Merton] Run before_insert hook on .com

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste.t
If we're not taking a payment or updating a direct debit amount then
don't store the payment field as it appears in the admin which can be
confusing. This only applies for reducing bins on non direct debit
subscriptions.
Fixes mysociety/societyworks#2448
=> [Bromley] only store payment field when required

perllib/FixMyStreet/DB/Result/Body.pm, perllib/FixMyStreet/Script/UpdateAllReports.pm, t/app/controller/reports.t, t/cobrand/fixmystreet.t
Ignore waste/noise/claims reports from summary dashboard and body averages [skip changelog]
Fixes https://github.com/mysociety/societyworks/issues/2440
=> [UK] Exclude waste/noise/claims from statistics.

.cypress/cypress/integration/buckinghamshire.js
For some reason clicking the pan/zoom button in these tests was sometimes causing the categories to switch to Borsetshire catgories. Taking that line out appears to make the tests pass consistently.
Not sure how to verify that the tests are passing because they're fixed, rather than just random chance 🤷 but it appears to pass consistently for me locally, and I was definitely getting failures before, so hopefully this will fix it for good.
Fixes https://github.com/mysociety/societyworks/issues/2761
=> [Buckinghamshire] Fix browser tests

CHANGELOG.md, bin/make_css
This would fix an issue where if you have, say, a multi-gigabyte photo cache at web/photos, it won't get searched for SCSS files.
=> Default make_css to web/cobrands rather than web.

perllib/FixMyStreet/Cobrand/TfL.pm
Merton want all of their current categories (which they consider to be street cleaning categories) to be available for reporting on Red Routes.
Fixes https://github.com/mysociety/societyworks/issues/2779
=> [Merton] Add Merton categories to TfL cleaning categories list

.gitignore, CHANGELOG.md, docker/docker-compose-dev.yml, docs/install/docker-develop.md, docs/install/manual-install.md
The content of the `SERVER_ARGUMENTS` environment variable (read from `docker/.env`) will be passed as an argument string to `script/server` when run by `docker/compose-dev up`.
If you have generated a self-signed SSL certificate and key, this change means you can pass those filepaths to `script/server`, to serve and access your development version of FixMyStreet over HTTPS.
This is all now documented at Installing > Docker (development).
=> Allow custom arguments to script/server in Docker config

bin/archive-old-enquiries, perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm, templates/email/default/archive-old-enquiries.html, templates/email/default/archive-old-enquiries.txt
This adds the necessary templates for Shropshire to have files closed using automated script
Moves script 'archive-old-enquiries' out of oxfordshire directory as it's a generic script that will run on all cobrands
=> [Shropshire] Make Oxfordhshire report archiving script generic to use for Shropshire integration report archiving

bin/archive-old-enquiries, perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm, t/app/script/archive_old_enquiries.t, templates/email/default/archive-old-enquiries.html, templates/email/default/archive-old-enquiries.txt
Fix missing slash in emails, and improve templates add testing to archiving old reports script
Adds slash that was missing between base url and 'report' which broke urls in emails
Changes templates to use cobrand variables throughout and remove passing in council name
Adds tests to check urls and templating
=> [Shropshire] Fix missing slash in emails, and improve templates, testing

CHANGELOG.md, templates/web/base/pagination.html, web/cobrands/buckinghamshire/base.scss, web/cobrands/greenwich/layout.scss, web/cobrands/sass/_base.scss, web/cobrands/shropshire/base.scss, web/cobrands/tfl/base.scss
Seminatically, these are links not buttons, so they should look like links, not buttons.
This also avoids the colour contrast issues that we previously had to work around in commits like 5ef5710e06042b4d81207b5d69905096f8a9d89f and 8c595e720763dbcd19228db9921deafb73dc8042.
While I was at it, I also changed the `<p>` to a `<nav>`, to give assistive devices a hint that the links relate to navigation, and an `aria-label` that explains "Next" and "Previous" relate to pagination.
Here’s an example of how it looks, on Merton cobrand:
=> Remove custom styling for /around pagination links

templates/web/stevenage/header_extra.html
Oddly, despite @dracos removing lots of files from `/templates/web/stevenage` in c21f766dee71bdce2e1823fc8af2840ef34c5250, I seemed to still have this one hanging around. We’re not keeping it for a reason, are we?
=> [Stevenage] Remove left-over Stevenage header_extra template

web/cobrands/westminster/base.scss, web/cobrands/westminster/layout.scss
Somehow a recent commit applied the same massive `font-size: 3.3em` to the map page headings, as to the front page heading. This was particularly unfortunate on the "Click the map…" banner, which is actually a `h1`.
This commit resets `.mappage` headings (including the "Click the map…" banner, and the "Report your problem" heading at the top of the reporting form) to their default font-sizes.
Fixes mysociety/societyworks#2557.
=> [Westminster] Correct "Click map" font size on /around page

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Dashboard.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/fixmystreet.t, t/script/inactive.t, templates/email/default/inactive-account.html, templates/email/default/inactive-account.txt
This brings the ability for logged-in non-staff users with specific email addresses/domains to view `/dashboard/heatmap` in the same way they can view `/reports/<body>/summary`. If a cobrand has the `heatmap_dashboard_body` feature enabled, then the same user-checking code will run when the heatmap is viewed on that cobrand. For example, if enabled for the Bromley cobrand, anyone with a bromley.gov.uk email address will be able to see the heatmap page as well as the summary page they currently can as well.
This PR adds the functionality but doesn't e.g. link to this anywhere, to be determined if given manually, linked, or other.
Fixes https://github.com/mysociety/societyworks/issues/2590 [skip changelog]
=> [UK] Add ability to allow domain access to heatmap

CHANGELOG.md, t/script/inactive.t, templates/email/default/inactive-account.html, templates/email/default/inactive-account.txt
This has come up in user support (someone had two accounts, one forwarded to the other, they didn't realise) and I see client support (domain name change causing the same issue), so including the email (or phone number) in the body of the inactive email seems like a sensible thing to do at the least.
=> Include username in inactive email.

perllib/FixMyStreet/DB/Result/Comment.pm, perllib/Open311/PostServiceRequestUpdates.pm, t/open311/post-service-request-updates.t
This should prevent the daemon from constantly retrying these updates. [skip changelog]
=> Mark a wait-skipped update as a failure.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
This fixes an issue where a report is duplicated once per day if the
original GGW report had a problem with payment.
See https://mysocietysupport.freshdesk.com/a/tickets/1704 for an example
Fixes https://github.com/mysociety/societyworks/issues/2845
=> [Bromley] Set payment method to DD for GGW renewals

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/Integrations/Pay360.pm, t/app/controller/waste.t
Fixed amendments to garden waste subscriptions paid for by Direct Debit by adding missing DD due date to hash in call to Integrations::Pay360->one_off_payment.
for https://mysocietysupport.freshdesk.com/a/tickets/1742
=> [Bromley] Fix GGW DD subscription amendment.

perllib/FixMyStreet/Cobrand/Bromley.pm
For https://mysocietysupport.freshdesk.com/a/tickets/1752
=> [Bromley] Fix split postcode BR1 4EY to point to Bromley.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
Pushes one particular geocoder result north a few thousandths of a degree so it's within Buckinghamshire's boundary.
For https://github.com/mysociety/societyworks/issues/2873
=> [Buckinghamshire] Tweak geocoder result for road on county boundary

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, t/app/controller/admin/bodies.t, t/app/controller/report_new.t, templates/web/base/admin/bodies/contact-form.html
This is for the situation where multiple bodies covering the same area have a contact with the same name. Checking this box indicates that if multiple contacts are found with the same name then the one(s) with this box checked should be preferred.
If no contacts are found with this flag then fall back to the default behaviour of sending to all matching contacts.
If multiple contacts are found with this flag then it will send to all of them.
This is related to the Buckinghamshire parish changes (see #3750), the idea being the parish contacts have this flag on them and therefore only get sent to the parish, rather than to Bucks as well.
=> Add prefer_if_multiple setting to contacts

CHANGELOG.md, templates/web/base/maps/noscript_map.html, templates/web/base/maps/noscript_map_base_wmx.html, templates/web/base/maps/openlayers.html, templates/web/zurich/maps/noscript_map.html, web/js/map-OpenLayers.js, web/js/map-OpenStreetMap.js, web/js/map-bing-ol.js, web/js/map-cheshireeast.js
Since the `#fms_pan_zoom` map controls are keyboard-navigable (and could conceivably be used by even non-sighted users, wanting to move the map view to reveal new markers in the `#map_sidebar` list) we need to make sure the controls aren’t hidden inside an `aria-hidden` parent.
Removing `aria-hidden` from `#map_box`, however, now exposes a whole load of new elements to assistive devices, including (in order):
1. each of the image tiles
2. each of the pin shadows
3. each of the pins
4. map data attribution at the bottom
5. each of the pan/zoom/other controls
In this commit, I’ve at least hidden the image tiles and pins in the non-JavaScript version(s) of the map. But doing the same thing in the OpenLayers JavaScript is beyond my current understanding!
Perhaps a developer can take a look? …
=> Remove aria-hidden from parents of #fms_pan_zoom

CHANGELOG.md, web/cobrands/sass/_layout.scss
Moved to the top of the page, below main title. I got rid of the yellow background so it doesn't pop up much on the page,
encouraging users that can see the map to actually keep using it, instead of skipping it.
Fixes part of #1360
=> "Can't see the map?" message now is always visible

perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/Integrations/Bartec.pm, t/app/controller/waste_peterborough.t
Prevents requests for new food caddies if there are already open service requests.
For https://github.com/mysociety/societyworks/issues/2878
=> [Peterborough] Don't allow duplicate food caddy requests

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_more_services_sidebar.html
No all bins option if a bin request; hide sidebar report links pre 5pm; alwas show (to staff at the mo) request bin link.
Fixes rest of https://mysocietysupport.freshdesk.com/a/tickets/1827
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1812
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1818
Hopefully last of the dupe issues.
=> [Peterborough] Some bin fixes

CHANGELOG.md, templates/web/base/around/_report_banner.html, templates/web/bromley/around/_report_banner.html, templates/web/greenwich/around/_report_banner.html, templates/web/highwaysengland/around/_report_banner.html, templates/web/oxfordshire/around/_report_banner.html, templates/web/shropshire/around/_report_banner.html, web/cobrands/bexley/base.scss, web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/merton/layout.scss, web/cobrands/oxfordshire/_colours.scss, web/cobrands/oxfordshire/base.scss, web/cobrands/oxfordshire/layout.scss, web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss, web/cobrands/sass/_report_list.scss
=> Fix colour contrast issues in map page sidebar

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_peterborough.t
Purely numerical check was not working for Peterborough as its
property IDs are of the form 'postcode:id_no'. So a string
equality check must be used instead.
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1821.
=> [Peterborough] Replace '==' with 'eq' for memcached property check

CHANGELOG.md, t/app/controller/dashboard.t, templates/web/base/dashboard/index.html
A hash lookup in a template is escaping the key used, meaning the lookup is failing anywhere we are using a category containing an ampersand as a key. Fixes https://mysocietysupport.freshdesk.com/a/tickets/1840
=> Fix dashboard rows for categories with &s.

bin/buckinghamshire/add-parish-categories, bin/buckinghamshire/create-parish-bodies, perllib/FixMyStreet/DB/ResultSet/Contact.pm
Adds two scripts for setting up Buckinghamshire parishes as bodies:
1. `bin/buckinghamshire/create-parish-bodies` to pull in all known Buckinghamshire parishes from Mapit and create bodies for them.
2. `bin/buckinghamshire/add-parish-categories` which takes a CSV file with `name` and `email` columns where `name` is the parish body name and creates categories for those parishes which send to the provided email address.
The second script is necessary as Buckinghamshire aren't going to setup categories for all parishes immediately, so we need to be able to control which parishes have the necessary categories.
Fixes https://github.com/mysociety/societyworks/issues/2808
=> [Buckinghamshire] Scripts to setup parish councils

CHANGELOG.md, perllib/FixMyStreet/Geocode/Bexley.pm, perllib/FixMyStreet/Geocode/Bing.pm
Makes Geocoder links be https rather than http - http causing an issue after an upgrade to server and http only to be problematic going forwards.
Ticket: **Calls from Geocoder files should be https to prevent unexpected failues** mysociety/societyworks#2898
=> Switch geocoder files from http to https

CHANGELOG.md, bin/update-schema, db/downgrade_0076---0075.sql, db/schema.sql, db/schema_0076-add-index-problem-external_id.sql
This should substantially speed up the bin/fetch --updates script.
=> Add problem(external_id) database index.

.cypress/cypress/integration/lincolnshire.js, bin/browser-tests, bin/fixmystreet.com/fixture, perllib/FixMyStreet/App/Controller/Report/New.pm, templates/web/base/report/new/top_message.html, web/cobrands/lincolnshire/assets.js
Was previously 'null', which was throwing an error in
fixmystreet/assets.js->get_asset_pick_message().
Fixes https://github.com/mysociety/societyworks/issues/2855.
=> [Lincs] Make asset_item_message for road assets an empty string

CHANGELOG.md, bin/install_perl_modules, cpanfile, cpanfile.snapshot
Tricky as the old one has to be uninstalled first... Take a copy of your `local` before testing in case it messes anything up.
Also upgrade Getopt::Long for it to work in Perl 5.18 (trusty in ESM, but should we drop it?).
=> Upgrade Net::DNS.

perllib/Integrations/Bartec.pm, t/app/controller/waste_peterborough.t
Rather than take the first found per container, loop through and make sure we find the closest previous/next dates in all schedules to use. Old/new schedules may lack information. [skip changelog]
=> [Peterborough] Work if multiple schedules present.

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, t/cobrand/oxfordshire.t
If one street lighting subcategory is picked, check all of them for duplicates to display, at a reduced distance. [skip changelog]
=> [Oxfordshire] Search all street lighting for dupes

perllib/FixMyStreet/Template.pm, t/app/controller/alert_new.t
Some officers are using chevrons around links so removing chevrons from around fully qualified urls before sanitization, otherwise they are purged from the displayed update.
https://github.com/mysociety/societyworks/issues/2716
=> [Oxfordshire] Remove chevrons from links in updates

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/app/controller/contact.t, t/cobrand/bucks.t
Because parishes are setup as separate bodies the default behaviour is to direct people to fixmystreet.com to follow the progress of their report.
Instead we want parish problems to be displayed on the cobrand and treated as cobrand problems. This is achieved by adding some new methods to UKCouncils.pm to make it easier to overrride the bodies/areas that are relevant to a particular cobrand, which will hopefully be useful if/when we add parishes elsewhere in the future.
=> [Buckinghamshire] Treat parish problems as belonging to the Bucks cobrand

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
Adds alphabetical sort to the list of mixed NH and council categories, otherwise council categories are at the end of list
=> [National Highways] Sort NH categories mixed with council categories

perllib/FixMyStreet/App/Controller/Dashboard.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t, templates/web/base/dashboard/index.html
This adds an extra "Body" dropdown to the Buckinghamshire dashboard which in addition to Buckinghamshire Council also lists all of the active parishes associated with the Buckinghamshire cobrand. When selected allows viewing the parish bodies stats in the same way as you can with the primary cobrand body.
Fixes https://github.com/mysociety/societyworks/issues/2810
=> [Buckinghamshire] Dashboard dropdown for parishes

bin/archive-old-enquiries, perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm, t/script/archive_old_enquiries.t, templates/email/default/archive-old-enquiries.html, templates/email/default/archive-old-enquiries.txt
Added test email output option to old reports closure script.
- New '--show_emails' option outputs emails instead
of sending them and does not close reports.
- Updated templates to use council name to refer to
council instead of council area.
Also: added signoff to HTML template to match plain text template.
For mysociety/societyworks#2616.
=> Add test 'show emails' option to report closure script

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/header.html
[skip changelog] My previous fix now breaks if there is a schedule without a next date (e.g. some brown bins at present). And the waste message wasn't displaying because they have their own header (I thought about factoring it out in some way but it's tiny and whatever).
=> [Peterborough] More waste fixes

templates/web/base/header.html, templates/web/base/header_site.html, templates/web/borsetshire/secondary_navbar.html, web/cobrands/borsetshire/base.scss
Added a secondary bar to showcase website. This change should change the user to easily contact the team if they are interested getting in touch.
Related to Issue [2537](https://github.com/mysociety/societyworks/issues/2537)
=> Secondary bar showcase

web/cobrands/borsetshire/layout.scss
The current navigation bar is a bit confusing, it doesn't show easily whereabout on the site the user currently is. This fix adds an active state to the current page.
=> Added active state to navigation bar

web/cobrands/buckinghamshire/layout.scss
This fix was included on layout.scss because it should only affect wider screen. 
Checked current state on mobile I didn't consider it needed any intervention.
This fix also prevents the changes in the position of the menu when selecting more than one option.
Tested on Edge, IE11, Firefox, Chrome, Opera, Safari.
Fixes: mysociety/societyworks#2905
=> [Buckinghamshire] Added fix to wider selection panel

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/bucks.t, templates/web/buckinghamshire/about/parishes.html, templates/web/buckinghamshire/reports/cobrand_stats.html, web/cobrands/buckinghamshire/base.scss
This adds a new button to the Buckinghamshire "All reports" page which links to a static page listing all of the parishes with links to the individual parish pages.
Fixes https://github.com/mysociety/societyworks/issues/2939
https://user-images.githubusercontent.com/22996/157831159-5e8b1ec0-f4dc-4168-93a4-df011091115c.mov
=> [Buckinghamshire] Allow viewing all reports for parishes

web/cobrands/shropshire/_colours.scss, web/cobrands/shropshire/base.scss
Fixes https://github.com/mysociety/societyworks/issues/2789 (hopefully!)
Hides the browser’s default focus outline on form inputs in the Shropshire cobrand, so that Shropshire’s custom focus (created with a border and box-shadow) shows through, uninterrupted – as requested by their branding guidelines document.
This also means that the multiselect dropdown toggles and the _native_ dropdowns on the `/around` page now match:
Before:
After:
=> [Shropshire] Remove form input focus outline to match branding guidelines

.cypress/cypress/fixtures/shropshire.xml, .cypress/cypress/integration/shropshire.js, bin/browser-tests, bin/fixmystreet.com/fixture, t/Mock/MapIt.pm, templates/web/base/js/translation_strings.html, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js, web/cobrands/fixmystreet-uk-councils/js.js, web/cobrands/fixmystreet.com/js.js
Restrict phone numbers to non-text characters (0-9, +, space).
Shropshire have asked to be able to match:
+44 1234 567890
and similar phone numbers but not e.g. similar to the following which caused a stuck report:
`Customer - Mrs XXXX - 01746 222 222`
(Where the reporter was reporting on behalf of a resident.)
for https://mysocietysupport.freshdesk.com/a/tickets/1741
=> [Shropshire] restrict phone numbers to non-alphabetic characters (0-9, +, space only)

t/cobrand/bromley.t, templates/email/bromley/_council_reference_alert_update.html, templates/email/bromley/_council_reference_alert_update.txt
Adds bin days link with optional personalisation to new garden waste subscription email
for https://mysocietysupport.freshdesk.com/a/tickets/1410
=> [Bromley] email amendments

templates/web/buckinghamshire/report/new/_form_labels.html
Changes the label on the title field:
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1933
=> [Bucks] Update report title field label

.cypress/cypress/integration/bromley.js, .cypress/cypress/integration/buckinghamshire.js, .cypress/cypress/integration/highways.js, .cypress/cypress/integration/regressions.js, .cypress/cypress/integration/westminster.js, .cypress/cypress/support/commands.js
This was originally part of https://github.com/mysociety/fixmystreet/pull/3832, and the code has already been reviewed, but I'm pulling it into a separate PR because I want to use the new pickSubcategory method in https://github.com/mysociety/fixmystreet/pull/3843.
There was already a `cy.pickSubcategory` method, but the name was misleading because it was actually picking a subcategory from within extra data, which isn't how most cobrands work.
This change renames the previous method to pickSubcatExtraInfo to more accurately reflect what it's doing, then the pickSubcategory method has been updated to actually pick a regular subcategory given a category ID and a subcategory label. I've also gone through and updated the obvious places where this pattern was being used to use the new method. …
=> Add Cypress method for picking subcategories

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
Bucks has some special code to ensure grass cutting reports are routed either to Bucks or to the parish. This code needs to be run on .com as well to ensure reports made on there are routed in the same way.
=> [Buckinghamshire] Grass cutting routing for .com reports

bin/buckinghamshire/create-parish-bodies
Previously this was looking up the list of children for the Unitary authority, but this meant that the parishes created were slightly different to the list of parishes in the "Areas covered" dropdown because the dropdown uses the hard-coded list of parishes in the cobrand.
The impact of this is that "Bierton Parish Council" wasn't associated with an area, because the area ID for the new "Bierton" is different to the one in the `_parish_ids` list in Buckinghamshire.pm.
This changes the create-parish-bodies script to use the same list of parish IDs that's used elsewhere, rather than deriving a list from the area children.
Part of https://github.com/mysociety/societyworks/issues/2938
=> [Buckinghamshire] Use hard-coded IDs when creating parishes

.cypress/cypress/integration/buckinghamshire.js, bin/fixmystreet.com/fixture, t/Mock/MapIt.pm, web/cobrands/buckinghamshire/assets.js, web/cobrands/fixmystreet/assets.js
This ensures that grass cutting reports are always made on a road.
Initially I tried simply adding the "Grass, hedges and weeds" category to the `asset_group` array, but that wasn't showing the stopper message because the `road_not_found` function checks for `is_single_body`, but there are actually two bodies in this case, Bucks and the parish, but we still want to show the stopper message. So I've added a `criterion` argument to `road_not_found` which the Bucks road layer then uses to always show the stopper message for the grass cutting categories.
=> [Buckinghamshire] Show the roads layer for grass cutting categories

web/cobrands/fixmystreet/staff.js
This was causing issues because setting `disabled` seemed to stop UAs submitting any value for the title field, which is required for Bromley reports.
`readonly` can’t be used with <select> elements, so just drop these lines entirely.
=> [Bromley] Don’t protect title dropdown field for staff

templates/web/peterborough/front/pre-steps.html
* Remove Covid message so emergency message feature works again
This are requested for staging for the time being.
https://mysocietysupport.freshdesk.com/a/tickets/1865
=> [Peterborough] Remove Covid message

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/cobrand/peterborough.t, templates/web/base/report/new/fill_in_details_form.html, templates/web/peterborough/front/pre-steps.html, web/cobrands/peterborough/assets.js, web/cobrands/sass/_base.scss
This PR fixes the issue where users that are on /around page then click on "Report a problem here" on the navigation bar, and there wasn't a "Can’t use the map? Skip this step." button (same that we have implemented on /report/new) causing accessibility issues.
This has been implemented across all cobrands.
This fixes part of: mysociety/societyworks#2787
Do I need to updated the changelog?
=> Added "Can’t use the map? Skip this step." to report problem here

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/cobrand/peterborough.t, templates/web/peterborough/front/pre-steps.html, web/cobrands/peterborough/assets.js
They've added this to their ArcGIS so we can use it instead, it's more up to date. [skip changelog]
Should fix https://mysocietysupport.freshdesk.com/a/tickets/1918
=> [Peterborough] Switch to their highways layer.

CHANGELOG.md, bin/update-schema, db/downgrade_0077---0076.sql, db/schema.sql, db/schema_0077-add-comment-send-state.sql, perllib/FixMyStreet/App/Controller/Admin/Triage.pm, perllib/FixMyStreet/DB/Result/Comment.pm, perllib/Open311/PostServiceRequestUpdates.pm, t/cobrand/bromley.t, t/cobrand/northamptonshire.t, t/cobrand/peterborough.t, t/open311/post-service-request-updates.t
This adds a sending state column to the comment table that the daemon can use for finding what updates still need processing. The schema change sets the default to 'processed' then changes it to 'unprocessed' so that all existing entries are set as processed.
This also means we no longer need workaround such as sticking -1 in the external_id column to stop an unsendable comment being processed, we can set the send_state to `processed` or `skipped` instead.
The daemon will fetch all `unprocessed` confirmed updates on sent reports. Any that lack an external_id or weren't sent via the Open311 send method will be marked as `processed`. Any that the cobrand says should be skipped will be marked as `skipped`. Any remainder will be sent, marked as `sent` if successful, left as `unprocessed` if …
=> Add send_state column to updates.

templates/web/base/admin/triage/_list-filters.html, templates/web/base/js/translation_strings.html, templates/web/base/reports/_list-filters.html, web/cobrands/fixmystreet/fixmystreet.js
In this fix the <label> elements with no "for" attribute, haven been replaced for <span> elements. 
I have also added aria-labels for all the .multi-select-button elements on the report page. The aria-label should be clear enough to help the users using screen readers.
To implement this solution, I have used approach number 2 of this
guideline: https://www.w3.org/WAI/tutorials/forms/labels/
For the commit I haven't added the name of the council on the commits [Shropshire], I think this would benefit all cobrands.
I tested this using the screen reader(VoiceOver).
Fixes: mysociety/societyworks#2785
Let me know if you have any feedback
=>  Added aria-label attribute to 'multi-select-button' elements

t/cobrand/hackney.t
As test is not about what the time is, make the time a pattern match to confirm the time is in the email.
Previous test was failing as the timezone on my local server was changing the time by an hour after British Summertime clock changes.
Fixes: Test failing due to timezone issues #3868 
=> Make test for time in email a pattern match for confirming time is in email

CHANGELOG.md, perllib/FixMyStreet/DB/Result/Body.pm, t/app/controller/report_inspect.t
staff_with_permission has been collating user names if permissions repeated through assignment to multiple roles.
This filters the list to return unique users.
https://github.com/mysociety/fixmystreet/issues/3870
=> staff_with_permission list returns list of users unique by id

t/cobrand/bexley.t, templates/web/bexley/report/new/councils_extra_text.html, templates/web/bexley/report/updates-sidebar-notes.html
Adds anti-phishing warning to top of report form, as well as above the update form.
For FD-1036.
Fixes https://github.com/mysociety/societyworks/issues/2776.
=> [Bexley] Add warning about personal information to new report/update forms

CHANGELOG.md, perllib/FixMyStreet/DB/Result/User.pm, t/app/controller/report_inspect.t
An anonymised user loses their name, phone, verified status and now their affiliation with a body.
This will stop the user being picked up by 'id' in body permission code.
For issue: https://github.com/mysociety/fixmystreet/issues/3873
=> undef body if user is anonymised

perllib/FixMyStreet/App/Controller/Around.pm, perllib/FixMyStreet/App/Controller/Auth.pm, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Root.pm
[Recent changes](https://github.com/mysociety/fixmystreet-mobile/pull/298) to the iOS app mean that requests to FMS now include an `Origin: app://localhost` header, so we need to return the corresponding header in the response.
=> Add CORS header for requests from iOS app

web/cobrands/greenwich/base.scss
Primary button is having contrast issues between the colour and background colour, also the hover effect on the background is too subtle to be noticed, especially for someone with visual impairment.
This PR fixes both issues, by adding white colour to the buttons, and also make the background colour lighter on hover.
=> [Greenwich] Improve accesibility for button element

web/cobrands/sass/_base.scss
This will prevent the ".fancybox-bg-s" element from taking over the clickable area from the button.
This fixes: mysociety/societyworks#2935
=> Added fix that enables buttons from having a full clickable area.

web/cobrands/buckinghamshire/base.scss, web/cobrands/sass/_claims.scss
Added minor UI fix that prevents inconsistency in the claims forms.
The current fix uses "Helvetica" just like the rest of the website.
Fixes: mysociety/societyworks#2930
=> [Buckinghamshire] Fixed font inconsistency in claim form

templates/web/base/admin/triage/_list-filters.html, templates/web/base/reports/_list-filters.html, web/cobrands/fixmystreet/fixmystreet.js
#3863 had a couple of bugs, I'm afraid - 'untriaged' disappeared from the triage filter, it was acting on multi-selects on other pages besides report lists (e.g. admin user form has one that was getting an incorrect aria-label), there was still English in the JS ("Show" and "about") which wouldn't be translated and display in English in other languages. Hopefully what I've done makes sense, let me know if you have any questions.
=> Improve adding aria-label to multi-select-button.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, t/app/controller/waste.t
If the original payment was made by CSC, this payment method was being copied across to modifications made by normal users. It is already re-set to CSC if CSC is used for the modification so default to credit card in the usual case. Also fix button text for such a payment. Fixes https://github.com/mysociety/societyworks/issues/2865 [skip changelog]
=> [Waste] Do not reuse CSC payment method on modify.

perllib/FixMyStreet/Cobrand/Oxfordshire.pm, t/cobrand/oxfordshire.t, templates/email/oxfordshire/_council_reference.html, templates/email/oxfordshire/_council_reference.txt, templates/web/oxfordshire/tokens/_confirm_problem_council_id.html
Add FMS ID to confirmation emails asking users to use it if they get in touch with the council. 
fixes https://github.com/mysociety/societyworks/issues/2548
=> [Oxfordshire] Send FMS ID to reporter in confirmation email.

perllib/FixMyStreet/Cobrand/Thamesmead.pm, perllib/FixMyStreet/Cobrand/UK.pm, templates/web/thamesmead/around/intro.html, templates/web/thamesmead/report/form/private_details.html, templates/web/thamesmead/report/new/councils_text_private.html
1) Confirmation of report refers to it going to a council rather than Peabody
https://3.basecamp.com/4020879/buckets/26382066/todos/4906247418
https://3.basecamp.com/4020879/buckets/26382066/todos/4910559283
2) Content text for page when entering your details, refers to 'Council' and should refer to Peabody
https://3.basecamp.com/4020879/buckets/26382066/todos/4915678385
3) Update home page text to reflect Thamesmead locations
https://3.basecamp.com/4020879/buckets/26382066/todos/4911842219
4) Site going through to FMS.com after confirming a report rather than back to Peabody cobrand
https://3.basecamp.com/4020879/buckets/26382066/todos/4902033447
=> [Thamesmead] Changes after testing part 1

perllib/FixMyStreet/Cobrand/Thamesmead.pm, t/cobrand/thamesmead.t
1) Southmere drive not in Crayford - OSM doesn't show it as such so changing to OSM removes Crayford
https://3.basecamp.com/4020879/buckets/26382066/todos/4906047321
2) Claridge Way not coming up in search - OSM shows Claridge Way
https://3.basecamp.com/4020879/buckets/26382066/todos/4906653404
3) Holstein and Lensbury way don't show on map and have Crayford in title - OSM removes Crayford. Lensbury way seems to show up but Holstein too small for the map? 
https://3.basecamp.com/4020879/buckets/26382066/todos/4906718571
4) Some locations not found and taken to an area outside of Thamesmead - remove not area search results.
https://3.basecamp.com/4020879/buckets/26382066/todos/4898005285
=> [Thamesmead] Change geocoder to OSM and use OSM mapping methods

templates/web/base/js/translation_strings.html, templates/web/base/report/form/photo_upload.html, web/cobrands/fixmystreet/fixmystreet.js
This function will allow replacing unnecessary labels with a span element that won't get read on a screen reader.
This fix will also prevent orphaned labels.
To improve accessibility, this function also allows to includes an aria-label.
I think we should try not to overwhelm the screen reader and visually impaired user, by not repeating information that has
already been provided.
For example:
Label("Photos(optiona)")-> Div("Browse or drag photos"),
instead -> Div(Aria-label("You can add optional photos"))
I tested this solution using VoiceOver.
Fixes: mysociety/societyworks#3024
And is related to mysociety/societyworks#2785
=> Added function that prevents orphaned labels and includes aria-label

web/cobrands/kingston/base.scss, web/cobrands/kingston/layout.scss
Updated fonts styles to the ones https://www.kingston.gov.uk/.
I have also fixed some spacing issues I found on mobile. These changes should make it look similar to Kingston website.
It fixes: https://3.basecamp.com/4020879/buckets/26876928/todos/4935216341
=> [Kingston] Changed font size and colour for h1, h2, p

CHANGELOG.md, conf/general.yml-example, docs/customising/config.md, perllib/FixMyStreet.pm
This adds a new configuration variable, `FMS_DB_SSLMODE`, can be used to override the default `sslmode` setting FMS uses when connecting to its PostgreSQL database and changes the default from `allow` to `prefer`.
The previous value for `sslmode` used was hardcoded to `allow` which will at first try an unencrypted connection before trying an encrypted one if the database server enforces SSL. This is an insecure default behaviour and also results in large numbers of FATAL connection errors on database servers that enforce SSL connections.
This nows default to `prefer` if the variable isn't present in the configuration file. This is backwards-compatible with the previous default in that it will allow unsecure connections, but only after first trying an encrypted connection, reversing the …
=> Permit control over database connection SSL mode

CHANGELOG.md, docs/_includes/admin-tasks-content.md, perllib/FixMyStreet/App/Controller/My.pm, perllib/FixMyStreet/App/Controller/Report.pm, t/app/controller/my_assigned.t, t/app/controller/report_inspect.t, templates/web/base/admin/_report-assignment.html, templates/web/base/admin/problem_row.html, templates/web/base/report/inspect/_assignment-options.html, templates/web/base/report/inspect/assignment.html, templates/web/base/reports/_bulk-assign.html
This PR hides 'assigned to' text if there is no assignee for a report.
It also fixes buggy behaviour around unassigning reports.
Fixes https://github.com/mysociety/fixmystreet/issues/3646.
Fixes https://github.com/mysociety/fixmystreet/issues/3903.
=> Tidy up behaviour around unassigned reports

perllib/FixMyStreet/Cobrand/Peterborough.pm
For https://mysocietysupport.freshdesk.com/a/tickets/1911
=> [Peterborough] Display help message when ‘new build’ bin request reason selected

t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/services.html
- On the day of collection a more specific message is shown to prevent user confusion. For FD-2046
- The email link displayed in the "There was a problem with the collection, please email" message now prepopulates the user's address in the subject line. For FD-2040.
=> [Peterborough] Small improvements to bin day & missed collection messages

.cypress/cypress/integration/hackney.js, perllib/FixMyStreet/Cobrand/Hackney.pm, t/app/controller/report_new_errors.t, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js
Technically the limit doesn't need to be applied to email categories, but it seemed simplest/quickest to do it this way.
Fixes https://github.com/mysociety/societyworks/issues/3056
=> [Hackney] Only allow 256 chars in report description

web/cobrands/lincolnshire/assets.js
Lincolnshire have recently had a category reshuffle. As part of that they've introduced a new group for bus stops and shelters and want the bus stop assets to appear for all subcategories in that group.
Fixes https://github.com/mysociety/societyworks/issues/3052
=> [Lincolnshire] Change asset_group for bus stops

templates/email/default/_email_settings.html, templates/email/default/_email_top.html
I'll give a little bit of context, a few weeks ago, we implemented dark mode styling for emails, preventing the contrast issue found in #3643. This solution worked well, but while working on the Peabody cobrand. I noticed that the buttons had contrast issues on the emails.
The ideal solution would have been to keep the dark mode on. But unfortunately, all windows products were causing issues when reversing the colours and, of course, not respecting the CSS rules. In addition, some elements in certain templates were having issues with some Apple products. 
-Contrast colour on buttons (windows products)
-Black font color against black background color on apple email app
So fixing, testing and maintaining a solution keeping Dark mode enabled will probably take more than we expected during …
=> Enable Light version only for emails

web/cobrands/kingston/_colours.scss, web/cobrands/kingston/base.scss, web/cobrands/kingston/layout.scss
This PR contains some changes that fixes the focus state on the navigation bar and other interactive links making them accessible.
=> [Kingston] Improved focus state links and navbar

perllib/FixMyStreet/DB/Result/Comment.pm, t/cobrand/thamesmead.t, templates/web/thamesmead/footer_extra_js.html, web/cobrands/thamesmead/js.js
When staff user comments, body should report as Peabody.
https://github.com/mysociety/societyworks/issues/3063
Ticket created from
https://3.basecamp.com/4020879/buckets/26382066/todos/4948834882
=> [Thamesmead] Replaces Thamesmead in staff comments with Peabody

templates/web/thamesmead/footer_extra_js.html, web/cobrands/thamesmead/js.js
When filling in the form to make a report, a user is asked for their full name if they only enter one name.
This text usually says that councils require this text. We want it to say that Peabody requires this.
https://github.com/mysociety/societyworks/issues/3064
(created from https://3.basecamp.com/4020879/buckets/26382066/todos/4952095715)
=> [Thamesmead] Text requesting full user name should be from Peabody

web/cobrands/bristol/assets.js
Final requested changes for testing:
* Includes childplay areas in parks restriction
* Adds parks/playgrounds to Graffiti and Flyposting
* Changes 'Vegetation Clearance' to 'Brambles'
* Makes wfs url ready for go-live
https://mysocietysupport.freshdesk.com/a/tickets/2073
=> [Bristol] Change more category names

templates/web/oxfordshire/report/inspect/_extra_details_field.html, templates/web/oxfordshire/report/inspect/_raise_defect.html, templates/web/oxfordshire/report/inspect/extra_details.html
* Pothole (permanent) should be the default above Sweep and Fill
* Removes Pothole Cluster from defect type dropdown
* Changes the pothole detail when Sweep and Fill is selected
* Replaces '-' with a space in dropdown selection
* Once issue raised, disables priority and extra_priority fields so they can't be changed
https://github.com/mysociety/societyworks/issues/3067
https://mysocietysupport.freshdesk.com/a/tickets/2113
=> [Oxfordshire] Minor inspector tool changes

templates/web/bromley/main_nav_items.html
Bromley council has requested to remove the coronavirus update from the navigation bar.
=> [Bromley] Erased 'Coronavirus update' navitem from navbar

.cypress/cypress/integration/oxfordshire.js, templates/web/oxfordshire/report/inspect/_raise_defect.html
* Removes residual not seen dropdown elements for pothole cluster
* Removes pothole cluster elements from tests
* Changes test to target correct element more precisely
Related to https://mysocietysupport.freshdesk.com/a/tickets/2113
=> [Oxfordshire] Fix broken cypress test on inspector tool

web/cobrands/buckinghamshire/assets.js
This disables the body check for the sign assets so that it shows for
all of the (100+) parishes in Buckinghamshire to allow asset selection
for the "Dirty signs" category.
=> [Buckinghamshire] Show sign assets for parish Dirty signs category

perllib/Integrations/SCP.pm, t/integrations/scp.t
name and address fields are limited to 50 characters in the SCP api so
truncate these before sending.
=> [Waste] truncate some SCP fields which have limits

templates/web/bathnes/around/_postcode_form_post.html, web/cobrands/bathnes/_colours.scss, web/cobrands/bathnes/base.scss, web/cobrands/bathnes/layout.scss, web/cobrands/bathnes/pattern-lib/_colours.scss
This PR fixes issues found by the design team[ here on this Trello ticket](https://trello.com/c/HLfN7G5Q)
There were a couple of accessibility issues:
- Focus state for links too subtle. I made them match the focus state on Bathnes website.
- The contrast of the white text against the light blue of the #front-main element wasn't high enough.
- The #front-main element felt cluttered, so I added some space.
- Reduced the size of the report other issues message on the #front-main element, so the page is easier to scan and clearer which elements are more important than others.
- The colour of the stats on the homepage was changed to navy, so they passed the contrast test.
https://user-images.githubusercontent.com/13790153/175244106-fbb2ad7f-1edc-4e18-ad34-528b7764798a.mov …
=> [Bathnes] Accessibility colour improvement

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/cobrand/bucks.t
Adds a `post_report_sent` hook to Bucks which checks if any of the receiving bodies are a know Bucks parish and if so marks the report as internal referral.
Fixes https://github.com/mysociety/societyworks/issues/3075
=> [Buckinghamshire] Mark parish reports as internal referral after sending

CHANGELOG.md, perllib/FixMyStreet/Cobrand/Merton.pm, perllib/Open311/UpdatesBase.pm, t/open311/getservicerequestupdates.t
This already existed for Merton, but it seemed like a good thing to have in general - could help with e.g. Bucks duplicate updates on occasion (though we've hidden some status codes there as a different solution).
=> [Open311] Check for identical latest update.

perllib/FixMyStreet/Cobrand/Lincolnshire.pm
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1798.
=> [Lincs] Change pin colours.

.cypress/cypress/integration/oxfordshire.js, templates/web/base/report/new/fill_in_details_form.html, templates/web/bathnes/report/new/roads_message.html, templates/web/buckinghamshire/report/new/roads_message.html, templates/web/centralbedfordshire/report/new/roads_message.html, templates/web/cheshireeast/report/new/roads_message.html, templates/web/fixmystreet-uk-councils/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html, templates/web/highwaysengland/report/new/roads_message.html, templates/web/northamptonshire/report/new/roads_message.html, templates/web/oxfordshire/report/new/roads_message.html, templates/web/peterborough/report/new/roads_message.html, templates/web/shropshire/report/new/roads_message.html, templates/web/tfl/report/new/roads_message.html, templates/web/thamesmead/report/new/roads_message.html, templates/web/westminster/report/new/roads_message.html, web/cobrands/fixmystreet/assets.js
If the pin was moved and the message shown, it was being scrolled into view by update_pin, but this was not happening if the message was shown after category selection. [skip changelog]
=> Scroll responsibility message into view.

t/app/controller/contact.t, t/app/controller/report_new_staff.t
Restores the correct functionality for Parishes after the MapIt generation update (#3933).
NB when you come to rebase the Bucks parishes work over `master`, you'll need to replace the `2217` area IDs with `163793`.
=> [Bucks] Fixes after MapIt generation update

perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Queue/Item/Report.pm, t/cobrand/bucks.t, templates/email/fixmystreet.com/_council_reference.html, templates/email/fixmystreet.com/_council_reference.txt
This means a parish report made on .com will get a report logged email,
plus no need for a special post_report_sent function in FixMyStreet.pm.
Should fix FD-2186.
=> [Buckinghamshire] Have cobrand own parish bodies.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
Our open311-adapter doesn’t need these params munging in the same way
as the Bromley endpoint.
=> [Bromley] Don’t munge Open311 update params for waste reports

.cypress/cypress/fixtures/bucks_speed_limits_30.xml, .cypress/cypress/fixtures/bucks_speed_limits_60.xml, .cypress/cypress/fixtures/bucks_speed_limits_none.xml, .cypress/cypress/integration/buckinghamshire.js, bin/buckinghamshire/add-parish-categories, bin/fixmystreet.com/fixture, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/cobrand/bucks.t, web/cobrands/buckinghamshire/assets.js
This uses the same code that was already in place for this, but the
question is now a hidden field which gets auto-populated by the values
in the asset layer.
Fixes https://github.com/mysociety/societyworks/issues/2812
=> [Buckinghamshire] Use speed limit asset layer to route Grass cutting reports

web/cobrands/fixmystreet/assets.js
Fixes https://github.com/mysociety/societyworks/issues/3076.
The bug is on the `bucks-parishes-reviewed` branch.
The 'Grass, hedges and weeds' category was showing 'The location you have selected doesn't appear to be on a road' msg when a (private) road was selected. This PR fixes that so that the correct 'The selected road is not maintained by Buckinghamshire Council' msg is shown.
=> [Bucks] Fix stopper message for 'Grass. hedges...' category for private roads

perllib/Open311.pm, t/cobrand/bromley.t
Missed this in previous fix (765bfb0146b09132b653494c2da063ea1ae304c1)
=> [Bromley] Skip email_alerts_requested param for waste report updates

perllib/FixMyStreet/Cobrand/Thamesmead.pm
* Thamesmead uses own stats for front page stat reporting like a council
* Thamesmead /reports goes to its own reports page like a council
Two parts out of three on this ticket https://github.com/mysociety/societyworks/issues/3074
=> [Thamesmead] Goes to own report page and reports own stats

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
=> [Bexley] Send report P1 emails even if Symology is down

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
Area 62431 (Bierton with Broughton) has split into 3 separate areas (Bierton, Broughton Hamlet, Kingsbrook).
Now that FixMyStreet is on a newer mapit generation we can include these newer parishes in the list that's hardcoded in the cobrand module.
Fixes https://github.com/mysociety/societyworks/issues/2955
=> [Buckinghamshire] Update hardcoded list of parish IDs

.cypress/cypress/integration/buckinghamshire.js, bin/fixmystreet.com/fixture, perllib/FixMyStreet/App/Controller/Report/New.pm, t/cobrand/bucks.t
Rather than the text during the reporting process saying "These will be sent to Adstock Parish Council or Buckinghamshire Council and also published online" we instead want it to just say the parish name. This is because parish categories have the `prefer_if_multiple` flag, so the reports will only go to those contacts.
=> [Buckinghamshire] Make it clear when reports are sent to the parish

perllib/FixMyStreet/App/Controller/Reports.pm, t/cobrand/bucks.t
On the staging site the Buckinghamshire parish councils were originally
loaded in by simply appending "Parish Council" to the area name in
mapit.
However as part of the Buckinghamshire parish project we got a
more accurate list of parish and town council names to use. [1]
This means we have database entries for e.g. "Aylesbury Parish Council"
(from the original import) and "Aylesbury Town Council" (from the more
recent import). There are many other examples like this.
The unused entries from the original import should all be marked as
deleted, however the code that maps URLs like /reports/Aylesbury
to a body wasn't filtering for active bodies, so the deleted bodies were
being returned.
There was also a separate bug where if there's a third body, in this
case "Aylesbury Vale District …
=> [Buckinghamshire] Match parish/town councils for all reports page

bin/browser-tests
On more than one occasion I have edited the fixture script and left a
syntax error in there by accident, and then been confused about why the
browser tests are all failing.
To avoid this problem check the exit status of the fixture script before
running the browser test interface.
=> Abort browser-test script if fixture script fails

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t
Allow the category to be shown in dropdowns on admin pages so e.g.
triaged reports can be recategorised. [skip changelog]
Fixes FD-2280
=> [Buckinghamshire] Off-road flytipping in admin.

perllib/FixMyStreet/App/Controller/Admin/Reports.pm, perllib/FixMyStreet/App/Controller/Admin/Triage.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/DB/Result/User.pm, t/app/controller/admin/triage.t, t/cobrand/bucks.t, t/cobrand/isleofwight.t, templates/web/base/admin/triage/_inspect.html
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/3138
This turned out to need multiple steps - firstly fixing the triage list page to show all cobranded reports rather than just the cobrand body's. Next to allow Bucks staff as if they had their staff permissions on all parish bodies (so that viewing a parish report page would show the triage form). Then instead of using the unique-name dropdown, show all contacts, and update the triage server form to deal with contact IDs rather than category name. Don't think this should affect any usage (and may well need extending at some point if same thing applies to e.g. normal admin report edit page).
=> [Bucks] Triage parish fixes

perllib/FixMyStreet/Cobrand/TfL.pm, t/cobrand/tfl.t
Borough emails in the configuration automatically pass validation
This will allow client to self-manage updates
https://mysocietysupport.freshdesk.com/a/tickets/2287
=> [TfL] Validate borough email addresses

web/cobrands/northamptonshire/assets.js
Northamptonshire would like it so users can make a report against a tree, hedge, etc. that does not appear as an asset on the map. So this PR disables pin snapping for trees; a user can select a tree asset if they wish but can also select e.g. the side of a road.
Fixes https://github.com/mysociety/societyworks/issues/2900.
=> [Northants] Disable pin snapping for tree layer

perllib/FixMyStreet/Cobrand/Thamesmead.pm
Disambiguation has value quoted now to be read correctly
https://github.com/mysociety/societyworks/issues/3152#event-7169341342
=> [Thamesmead] Fixes broken disambiguate_location

templates/web/base/waste/bin_days.html, templates/web/sutton/header_logo.html, templates/web/sutton/header_site.html, web/cobrands/sutton/base.scss, web/cobrands/sutton/layout.scss
- Colours
- Form components
- Footer
- Header
- Emails
I'd like to give a proper cross browser testing once the developer have started/finish working on this cobrand.
=> [Sutton] WW front-end

perllib/FixMyStreet/Cobrand/Northamptonshire.pm, t/cobrand/northamptonshire.t
This adds an extra "External ID" column to the dashboard CSV export which Northamptonshire have requested so they can map updates to reports in their new system.
Part of https://github.com/mysociety/societyworks/issues/3131
=> [Northamptonshire] Include report's external ID in CSV export

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Users.pm, perllib/FixMyStreet/DB/Result/User.pm, t/script/inactive.t, templates/web/base/my/my.html
Fixes https://github.com/mysociety/societyworks/issues/2991. Fixes https://github.com/mysociety/societyworks/issues/3027 - carries on from https://github.com/mysociety/fixmystreet/pull/3874, makes sure permissions are removed along with the from_body. Existing entries in db will need updating to match, I think.
=> Make sure staff permissions removed when anonymized

t/cobrand/public_asset_ids.t
Possibly was failing due to original external ID strings (0123,
0234, etc.) also sometimes matching the randomly generated CSRF
token or CSP nonce in the HTML. So external IDs are now prefixed
with the non-base64 char €.
Fixes https://github.com/mysociety/societyworks/issues/3153.
=> Fix intermittently failing public_asset_ids.t

perllib/FixMyStreet/Cobrand/UK.pm, t/app/controller/alert.t
When creating the alert feed url, remove Highways England from the bodies that are selected for covering that area
=> [Bromley] Remove Highways England from alert search

bin/handlemail, cpanfile, perllib/FixMyStreet/App/Controller/Admin/Templates.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Email/Incoming.pm, perllib/FixMyStreet/Queue/Item/Report.pm, perllib/FixMyStreet/SendReport/Email.pm, perllib/Open311/UpdatesBase.pm, t/app/controller/admin/templates.t, t/cobrand/bucks.t, t/email/incoming.t, t/open311/getservicerequestupdates.t, templates/email/buckinghamshire/submit.html, templates/email/buckinghamshire/submit.txt
This PR first refactors handlemail so that the various aspects of it can be tested. And then adds some new functionality to look for a code in the subject and mark report fixed/use a response template like it was an Open311-fetched update.
Fixes https://github.com/mysociety/societyworks/issues/2820. [skip changelog]
=> Parse incoming email for subject code

CHANGELOG.md, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/DB/Result/Body.pm, perllib/FixMyStreet/Reporting.pm, t/Mock/MapIt.pm, t/app/controller/dashboard.t
Fixes https://github.com/mysociety/societyworks/issues/3156
Area IDs are stored on a report at creation; if the areas in MapIt change, due to boundary changes, those IDs no longer match against the data in the current MapIt generation. So fetch all generations of children so old ward information is included.
=> For CSV export, fetch children of all generations.

.cypress/cypress/integration/highwaysengland.js, web/cobrands/fixmystreet/assets.js
Previously always_visible layers were set to visible at setup, but then when the layer was initialized update_layer_visibility was called which would set the visibility to false if the body did not match. However by then a layer data request would already have been made.
=> Check asset layer body visibility at creation.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/cobrand/peterborough.t
As requested in https://mysocietysupport.freshdesk.com/a/tickets/1332, this PR:
- stops emails being sent for graffiti reported on public land
- stops emails being sent for fly-tipping, on both public and private land, for incident sizes of
- 'Single Black Bag'
- 'Single Item'
- stops emails being sent for graffiti and fly-tipping reports raised by Peterborough staff
Fixes https://github.com/mysociety/societyworks/issues/2529.
Should be deployed before https://github.com/mysociety/fixmystreet/pull/3985.
=> [Peterborough] Suppress certain emails for graffiti and fly-tipping

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Queue/Item/Report.pm, perllib/FixMyStreet/Roles/Bottomline.pm, perllib/FixMyStreet/Roles/DDProcessor.pm, t/app/controller/waste.t, t/app/controller/waste_kingston.t, t/cobrand/bromley.t
Fixes https://github.com/mysociety/societyworks/issues/3169 - This makes the Kingston DD reference code the general code, so replaces Bromley's existing. Leave the old GGW handling for any DDs that come in overlap.
Fixes https://github.com/mysociety/societyworks/issues/3114 - make sure the renewals set the correct cobrand_data
Fixes https://github.com/mysociety/societyworks/issues/3149 - deal with the cron output
Fixes https://github.com/mysociety/societyworks/issues/3171 - fix the update order issue (I think)
=> [Waste] DD uniqueness, renewal cobrand_data, New dd_date, auto-internal created time

perllib/FixMyStreet/Email/Incoming.pm, t/email/incoming.t
If an incoming email concerns a report for a body other than the one we are using to look up a response template, do not match on categories, as they should only apply to reports for that body. This is so e.g. if a category exists for both Bucks and a parish, a reply to a parish report will not use a matching Bucks template. [skip changelog]
=> Check report body for category on incoming email.

perllib/FixMyStreet/Email/Incoming.pm, t/email/incoming.t
If there is not a code present, we should check if it looks like an out-of-office before sending the 'no code' bounce, and if it looks like one, forward it on to the reporter as before. [skip changelog] For https://mysocietysupport.freshdesk.com/a/tickets/2065
=> [Bucks] Ignore OoO in email status code handling.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/services.html
The rules on missed collections have changed. Missed collections can now only be reported until noon the next working day.
Fixes https://github.com/mysociety/societyworks/issues/3183
=> [Peterborough] Change missed collection timeframe from 2.5 days to 1.5 days

bin/csv-export
Until recently, nothing tried to use the class as an instance, only call simple functions, but the Buckinghamshire parish_bodies call caches the fetched bodies on the cobrand. [skip changelog]
Fixes https://mysocietysupport.freshdesk.com/a/tickets/2342
=> CSV export, instantantiate cobrand class.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste.t
Just a bit of tidying to make it easier for non-GGW modules to use payments code.
=> [Waste] Remove hardcoded ‘GGW’ references

perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/IsleOfWight.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/isleofwight.t, t/cobrand/northamptonshire.t, templates/web/base/report/display.html, templates/web/base/report/update-form-wrapper.html, templates/web/fixmystreet-uk-councils/report/_updates_disallowed_message.html, templates/web/fixmystreet.com/report/_updates_disallowed_message.html
If a report is closed to updates, directly or because of its category, a
closed-to-updates message should be shown, even if the cobrand eg allows
updates for reporters. Also take out a couple of cobrand functions where
the same behaviour is achieved through config. [skip changelog]
Fixes https://github.com/mysociety/societyworks/issues/3081
=> [UK] Tidy up closed-to-update messaging.

perllib/FixMyStreet/Cobrand/TfL.pm
Bromley have recently switched to using proper groups. As a result they
have a new "Street Cleansing" group that should be displayed on red
routes, but wasn't being handled by the code.
Fixes https://github.com/mysociety/societyworks/issues/3193
=> [Bromley] Add "Street Cleansing" to red route groups

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm
=> [UK] Fix crash on /admin/config for cobrands that don’t define report_sent_confirmation_email

web/cobrands/northamptonshire/base.scss, web/cobrands/northamptonshire/layout.scss
The client has requested that we remove the logos while they think further about a potential rebrand.
Fixes https://github.com/mysociety/societyworks/issues/3222
=> [Northamptonshire] Remove North and West Northamptonshire logos

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Page/Simple.pm, perllib/FixMyStreet/App/Form/Page/Wizard.pm, perllib/FixMyStreet/App/Form/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/base/admin/waste/edit.html, templates/web/base/admin/waste/index.html, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/summary.html, templates/web/base/waste/index.html, templates/web/peterborough/waste/_more_services_sidebar.html, templates/web/peterborough/waste/index.html, web/cobrands/sass/_admin.scss
This implements the basic wizard for booking a bulky collection, albeit with lots of hardcoded values and behaviour that is not yet correct according to the tech spec.
It's behind a feature flag that must be enabled:
```
waste_features:
peterborough:
bulky_enabled: 1
```
There is also an config editor for admins that will allow certain aspects of the bulky goods system to be controlled. This was reviewed in https://github.com/mysociety/fixmystreet/pull/4090 (though I've moved the new permission from `Default::available_permissions` to `Peterborough::available_permissions` and put it behind the feature flag). This also needs a feature flag to be active:
```
waste_features:
peterborough:
admin_config_enabled: 1
```
Per recent discussion I thought having …
=> [Peterborough Bulky Goods] Basic implementation of booking wizard & admin config editor

bin/fixmystreet.com/call-wasteworks-backend, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Roles/ParallelAPI.pm, perllib/Integrations/Bartec.pm, perllib/Integrations/Echo.pm
WasteWorks was making 6 sequential calls to the Bartec API on every page load which made the process feel quite sluggish - often taking up to 3 or 4 seconds for each page.
This PR factors out the existing Echo parallel API code into a `Role` which the Bartec module then uses. The Peterborough cobrand takes advantage of this which also has the side effect of caching results in the user's session, making page loads effectively instant.
=> [Peterborough] Speed up WasteWorks by calling Bartec API in parallel

CHANGELOG.md, bin/export-import-data
Adds email_text field from templates to import-export-data script so it is included in imports and exports
https://github.com/mysociety/fixmystreet/issues/4084
=> import-export-data script includes email_text from templates

.cypress/cypress/fixtures/highways_a_road.xml, .cypress/cypress/fixtures/highways_litter.xml, .cypress/cypress/integration/highwaysengland.js, bin/fixmystreet.com/fixture, templates/web/highwaysengland/report/new/form_heading.html, templates/web/highwaysengland/report/new/roads_message.html, web/cobrands/highwaysengland/assets.js
* Changes the headline where HE not responsible for litter
* Changes the text where HE not responsible for litter
* Adds tests
https://github.com/mysociety/societyworks/issues/3158
Below part of the comment from WIP - left so comment below makes some sense:
@davea  Could you give me a hand in understanding how to create the cypress test for this. I'm a bit confused as nationalhighways seems to be the only one that actually uses a route of 'PUSH' to the WFS - for example, tfl uses a route that lets you put in the map layer that's being targeted.
So I can't work out how I can get both asset layers to get called separately - or how to combine them into one file. Not sure that using two `<featureCollections>` is legitimate.
=> [Highways England] Update text for roads where HE not responsible for litter

web/cobrands/peterborough/base.scss, web/cobrands/peterborough/images/chevron-back-green.svg, web/cobrands/peterborough/images/chevron-back-white.svg, web/cobrands/peterborough/images/chevron-next-green.svg, web/cobrands/peterborough/images/chevron-next-white.svg
This PR includes elements that improves the user journey:
- Added secondary button, which has less emphasis than the primary one. It's good to use it next to the primary one so it 
- Added a secondary button with less emphasis than the primary one. It's good to use it next to the primary one so it doesn't draw as much attention, but it's still fairly obvious is there. You can also use it on its own; when you want to show there is an action available but is not the most important part of the page.
- Added "Next" and "Back" buttons, which help with the page's scannability.
- Added an info message based on the GOVUK warning message. It can be used to provide non-vital information to the user, so if they decide to omit it, there won't be a big consequence. For example: "If you are a landlord, …
=> [PCC] Added reusable UI elements for Bulky waste request form

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, templates/web/base/govuk/fields.html, templates/web/base/reports/index.html, web/cobrands/fixmystreet/fixmystreet.js
Enables situations where the autocomplete element is optional.
=> Make js-autocomplete respect presence/absence of `required` property

CHANGELOG.md, bin/update-schema, db/downgrade_0080---0079.sql, db/schema.sql, db/schema_0080-roles-add-extra.sql, docs/_includes/admin-tasks-content.md, perllib/FixMyStreet/App/Controller/Admin.pm, perllib/FixMyStreet/App/Controller/Admin/Roles.pm, perllib/FixMyStreet/App/Controller/Admin/Users.pm, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/App/Form/Role.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/DB/Result/Role.pm, perllib/FixMyStreet/DB/Result/User.pm, t/app/controller/admin/roles.t, t/app/controller/report_inspect.t, t/app/model/user.t, t/cobrand/bromley.t, templates/web/base/admin/roles/form.html
Adds category restrictions to roles, which should work in the same way as category restrictions for users.
This includes adding an admin interface for assigning categories to roles, as well as a couple of tweaks to the logic that checks user's categories to take a role's categories into account.
Fixes https://github.com/mysociety/societyworks/issues/2382
=> Add category restrictions to roles

perllib/FixMyStreet/App/Controller/Form.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Wizard.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/Integrations/Bartec.pm, t/app/controller/waste_peterborough.t, t/cobrand/peterborough/bulky-goods/available-slots.t, templates/web/base/waste/bulky/choose_date.html
Core behaviour for fetching & displaying viable bulky good collection slots to a user.
Closes https://github.com/mysociety/societyworks/issues/3215.
=> Peterborough bulky goods: check availability of collection slots (core behaviour)

perllib/FixMyStreet/Cobrand/Lincolnshire.pm
This code was originally written back in March but was accidentally overlooked when it came to putting the changes live. Opening this pull request so we don't forget to complete this task.
Part of https://github.com/mysociety/societyworks/issues/3057
=> [Lincolnshire] Update district categories list

perllib/FixMyStreet/App/Controller/Admin.pm, perllib/FixMyStreet/App/Controller/Dashboard.pm, perllib/FixMyStreet/App/Controller/Reports.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/DB/Result/Body.pm, perllib/FixMyStreet/Reporting.pm, perllib/FixMyStreet/Script/UpdateAllReports.pm, t/Mock/MapIt.pm, t/cobrand/northamptonshire.t
Updates the code that fetches children for a body to look at all associated areas.
This fixes the issue that Northamptonshire reported where they could only see North Northamptonshire wards in the dashboard dropdown.
Fixes https://github.com/mysociety/societyworks/issues/3262
=> Retrieve children for all body areas

.cypress/cypress/integration/highwaysengland.js, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, t/cobrand/fixmystreet.t, templates/web/highwaysengland/report/new/roads_message.html, web/cobrands/fixmystreet/assets.js, web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/highways/assets.js
* Adds a parameter 'he_referral' when directing to cooridinates on FMS
* When 'he_referral' is present:
- filters highways category to only contain council litter categories
- triggers automatic selection of highways category
- adds message to say to choose one of the councils litter categories
- adds cypress test
https://github.com/mysociety/societyworks/issues/3159
=> [National Highways] Forward council litter responsibilities to FMS

perllib/FixMyStreet/Cobrand/UK.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/highwaysengland.t
The HighwaysEngland cobrand module doesn't inherit from UKCouncils, so was falling back to the updates_disallowed method from Default.pm. This means that despite there being configuration designed to prevent updates they were still being permitted.
This change moves the updates_disallowed method from UKCouncils to UK.pm.
I think this should be ok, as the two places where it might matter, FixMyStreet.pm and Thamesmead.pm have their own version of the method.
Thamesmead might be a cause for concern because it calls SUPER, which will now be the new method in UK.pm, rather than Default.pm.
The other two cobrands that might be affected are EastSussex and WestBerkshire, but I can't see that it would make a difference to those.
Fixes https://github.com/mysociety/societyworks/issues/3272
[skip …
=> [National Highways] Ensure reports don't have an update form

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
- Persists the bulky collection in the database
- Allows report to be sent via Open311
- Initial implementation skips past payment screen
- Doesn't store photos yet
=> [Bulky] Store bookings in DB

web/js/waste.js
On Safari, at least, it seems that the code on L2 doesn't get called when the back button is used.
=> [Waste] Re-enable submit button when browser back button is used

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/Integrations/Bartec.pm, t/app/controller/waste_peterborough.t, templates/web/base/admin/report_blocks.html, templates/web/base/admin/waste/bulky_items.html, templates/web/base/admin/waste/edit.html, web/cobrands/fixmystreet/admin.js, web/cobrands/sass/_admin.scss
Adds a new page to the admin that displays items in a table:
This is linked at the bottom of the `/admin/waste/2566` page:
You can edit items, add new ones, or delete existing items, and it all gets stored in the config JSON:
https://user-images.githubusercontent.com/4776/193123593-a75ae9ed-35d7-4393-b59d-e67e40597f28.mov
I reused the existing JS that dynamically adds/removes rows, and figured out how to get the header to stick in place when scrolling a really long table :)
@nephila-nacrea let me know if the fields/data structure isn't what you expected for the part you're working on.
For https://github.com/mysociety/societyworks/issues/2914
=> [Bulky] Admin page for editing bulky items list

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/DB/Result/User.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/admin/emergencymessage.t, t/app/controller/admin/templates.t, t/app/controller/index.t, t/app/controller/report_new_errors.t, t/app/controller/waste.t, t/app/controller/waste_kingston.t, t/app/controller/waste_peterborough.t, t/app/controller/waste_sutton_garden.t, t/app/controller/waste_sutton_r.t, t/cobrand/bromley.t, t/cobrand/merton.t, t/cobrand/peterborough.t, t/cobrand/tfl.t, t/cobrand/westminster.t, t/open311/getservicerequestupdates.t, t/sendreport/open311_send.t, templates/web/base/waste/garden/subscribe_summary.html
@struan First commit for you to check on the DD contact/mandate stuff discussed, and in second commit there's the fix for direct_debit_error not having the property details (already fixed for CC).
@davea In the second commit, there's one bulky goods change for you to just check - to make sure the fileid for location_photo is included in the right page, so it's not included on all pages (and thereby cause undef warnings).
Think all the rest is just to prevent warnings.
=> Fix all warnings and offline running

web/cobrands/buckinghamshire/assets.js
Request from Bucks for sign layer not to be activated on Sign Problem or Dirty Sign
https://mysocietysupport.freshdesk.com/a/tickets/2486
=> [Bucks] Remove layer activation for two categories

perllib/FixMyStreet/Cobrand/Greenwich.pm, t/cobrand/greenwich.t
The server associated with these old reports is gone, so they have nowhere to be sent. [skip changelog]
=> [Greenwich] Do not send updates on old reports.

perllib/FixMyStreet/App/Form/Field/FileIdPhoto.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/forms/waste/bulky.t, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, web/cobrands/fixmystreet/fixmystreet.js
Closes https://github.com/mysociety/societyworks/issues/3245.
Items for selection are fetched from the database (admin can provide item list via `/admin/waste/<pbro_body_id>`); user can  select up to 5 items (one item per dropdown), as well as optionally upload one image per item.
This PR does not handle saving booking details to the database - see https://github.com/mysociety/fixmystreet/pull/4127.
=> Peterborough bulky goods: implement form for item selection

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Users.pm, t/app/controller/admin/users.t, templates/web/base/admin/list_updates.html, templates/web/base/admin/reports/index.html, templates/web/base/admin/users/alerts.html, templates/web/zurich/admin/index-dm.html, templates/web/zurich/admin/index-sdm.html, templates/web/zurich/admin/reports/index.html
Some shared/service user accounts have thousands of alerts and this page was timing out when attempting to render them all.
Prompted by FD-2538
=> Paginate alerts on user admin page

perllib/FixMyStreet/Cobrand/Default.pm
It is possible you might want to provide a default fallback to a cobrand feature, so this provides a way for you to do so.
This is for https://github.com/mysociety/societyworks/issues/3259 so I can provide a default to be used there for any cobrand not with a specific entry. Think it's an okay way of doing that.
=> Add cobrand feature fallback lookup.

perllib/FixMyStreet/Cobrand/Peterborough.pm, templates/web/base/waste/bulky/choose_date.html
As per feedback from Peterborough, the page for date selection now just shows the first four earliest dates, with no option to see later dates.
The time window for collection dates now starts from tomorrow's date, not today's.
=> [Bulky Goods] Post-testing fixes for collection date selection

perllib/FixMyStreet/Cobrand/Camden.pm
The JS asset changed are in the config file under the `asset_layers` key.
Part of https://github.com/mysociety/societyworks/issues/3305
=> [Camden] Add NSGRef to reports in JS and on server

perllib/FixMyStreet/App/Controller/Questionnaire.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Script/Questionnaires.pm, t/cobrand/brent.t
* Add cobrand hook 'prevent_questionnaire_updating_status'
* Add mechanism for stopping status of report updating when cobrand hook present
* Add tests
=> [Brent] Add cobrand hook to stop questionnaire changing status

templates/web/bromley/header_extra.html, templates/web/bromley/tracking_code.html
For FD-2536.
(It seems impossible to run this outside of production as the Cookie Control code checks that the domain matches `bromley.gov.uk`)
=> [Bromley] Add cookie banner & analytics to WasteWorks pages

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/items.html, web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/peterborough/base.scss, web/cobrands/sass/_waste.scss
This PR adds the following functionality:
- The "Delete Item" will delete item + reset the item value in case there was something selected.
- "Add item" button will become enabled when all the visible items have a selected item, but will become disabled when the max number of items has been reached or there is a visible item with nothing selected.
- Both buttons will become invisible if JS is not enabled.
- I used @nephila-nacrea[ commit](https://github.com/mysociety/fixmystreet/pull/4142/commits/62a9f9ee0a083145dc9898c73668832da31af870) for to display message. However I tweak her JS + the markup to make it more accessible and noticeable.
Preview:
https://user-images.githubusercontent.com/13790153/197184457-03e2923d-f278-48f0-90af-08550e2f0745.mov
There is one thing tat it would be nice: …
=> [Bulky] Added Jquery for item screen

perllib/FixMyStreet/Cobrand/Camden.pm, t/Mock/MapIt.pm, t/cobrand/camden.t
Camden don't want this displayed on their cobrand as it's not relevant to their area.
Fixes https://github.com/mysociety/societyworks/issues/3351
=> [Camden] Hide TfL's River Piers category

web/cobrands/camden/base.scss
Hey @chrismytton I have added a fix some of the from FMS base don't get apply to checkboxes with `.bulk-assign class`
Fixes: https://github.com/mysociety/societyworks/issues/3354
Note for self: To visit this page the body needs to be added to the url.
https://camden.localhost:3000/dashboard/heatmap?body=8
Let me know if there any that need a fix =)
=> [Camden] Fixed checkbox on heatmap page

web/cobrands/sass/_waste.scss
Small fixes that overrides the media breakpoint for `.govuk-grid-column-two-thirds` class only when the body has the `.bulky` class.
Fixes: https://mysociety.slack.com/archives/C02QNSSP2QK/p1669384971151229
Let me know if there is any feedback.
=> [Bulky] Added fix that improves layout on bin days page

bin/fixmystreet.com/waste-bulky-reminders, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/peterborough/_bulky_data.html, templates/email/peterborough/other-reported-bulky.html, templates/email/peterborough/other-reported-bulky.txt, templates/email/peterborough/other-reported.html, templates/email/peterborough/other-reported.txt
For https://github.com/mysociety/societyworks/issues/2901 (apart from querying if something has been cancelled, awaiting details on that) 
For https://github.com/mysociety/societyworks/issues/2913 (bar text changes and cancellation link - which I think should be the "view bookings" page, most straightforwardly)
=> [Peterborough] Bulky logged and reminder emails

perllib/FixMyStreet/Cobrand/Camden.pm, perllib/FixMyStreet/DB/Result/Comment.pm, perllib/FixMyStreet/DB/Result/Problem.pm, t/cobrand/camden.t, templates/web/camden/report/_show_name_label.html
Camden don't want users to have the option to be able to display their name publicly on the cobrand.
Fixes https://github.com/mysociety/societyworks/issues/3300
=> [Camden] Hide user's name on cobrand

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Roles/SCP.pm, t/app/controller/waste_peterborough.t, templates/web/base/waste/bulky/summary.html
Fixes https://github.com/mysociety/societyworks/issues/3370 [skip changelog] The other approach would have been to save `saved_data` in the session or somewhere just before redirecting to payment page, and then picking it up if they come back, but assuming most uses aren't going to be going back, that seemed like extra data storage that wasn't needed. I think it's okay reconstructing from the created report, the data should all be there - ~~it needs moving into Peterborough.pm to be the reverse of the waste_munge_bulky_data there, ideally, but wanted to get it up for review first.~~
=> [Bulky Goods] Handle coming back from payment page

perllib/FixMyStreet/Cobrand/Camden.pm
This is needed for the Symology code in open311-adapter.
=> [Camden] Add service_code to update params

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
Change to make all light codes add feature_id to the category
https://mysocietysupport.freshdesk.com/a/tickets/2569
=> [Bromley] Adjust codes for adding feature_id

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/app/controller/waste_peterborough.t, templates/web/base/admin/waste/bulky_items.html, templates/web/base/waste/bulky/items.html
For https://github.com/mysociety/societyworks/issues/3374 [skip changelog]
This adds the admin interface, some text to the items page describing any maximums if present, and prevents submission if items selected are over these maximums. It does not do any client side updating to e.g. disallow an item from being selected once the maximum number have been selected because that seemed like it would be a non-trivial amount of work for not really that much gain, given if someone does do it they get the error immediately and quickly and can resolve it, it'd only be a small improvement and I'm not entirely sure how to have it work with the autocompletes etc.
=> [Bulky Goods] Add per-item maximums.

templates/web/camden/main_nav_items.html, web/cobrands/camden/_mixins.scss, web/cobrands/camden/base.scss, web/cobrands/camden/layout.scss, web/cobrands/fixmystreet/images/check-white.svg
Hi @chrismytton =)
I have implemented the latest feedback from Camden. Let me know if you need me to change anything.
Before submitting this pull request. @bekkileaver after our chat here
https://github.com/mysociety/societyworks/issues/3355
I think they client hasn't seen the admin page(@jacquelinebylau  could you confirm this?), so I could revert the special input styles for the admin pages so they look like our default FMS. After your research it seems unnecessary to override our current styles. However in the likely scenario the client ask to keep the consistency between the citizen user and the admin side, can we share your research with them to persuade them not to move forward with it?
Fixes part of:
https://3.basecamp.com/4020879/buckets/27695641/todos/5470577758#__recording_559264 …
=> Camden fron end v5

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm
Did think about adding an expiry to the cached slots but that seemed like overkill; similarly I thought clearing the slots every time you visit the "available slots" page might be a bit irritating. This seemed like an OK way to (hopefully) catch the majority of cases.
For https://github.com/mysociety/societyworks/issues/3372.
=> [Peterborough] Clear cached bulky slots at start of wizard

perllib/FixMyStreet/App/Controller/Moderate.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/fixmystreet.t, t/cobrand/highwaysengland.t, templates/web/highwaysengland/header_extra.html, templates/web/highwaysengland/report/new/councils_text_all.html, templates/web/highwaysengland/report/new/inline-tips.html, web/cobrands/fixmystreet/fixmystreet.js
This is part 1 of a series of requirements for HE to highlight to users that personal information should not be put into the text field.
* Highlights existing wording warning about personal details
https://github.com/mysociety/societyworks/issues/3098
=> [Highways England] NHW035 Personal Details in Free Text 'Detail' Field

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t, templates/web/brent/report/new/_form_labels.html
Report prompt should ask for a location based summary of the issue and then send the title as an attribute so symology endpoint can transfer the attribute into the report location field
https://github.com/mysociety/societyworks/issues/3407229
=> [Brent] Change report prompt and send title as attribute to open311

perllib/FixMyStreet/App/Controller/Auth.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, t/app/controller/auth.t
Works around iOS bug where users login info is forgotten each time they launch the app.
For https://github.com/mysociety/fixmystreet-mobile/issues/300
=> Allow cookie-less API calls from iOS app

perllib/FixMyStreet/App/Controller/Auth/Social.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Hackney.pm, perllib/FixMyStreet/Cobrand/Westminster.pm, t/Mock/MapIt.pm, t/Mock/OpenIDConnect.pm, t/app/controller/auth_social.t
Azure oidc payload is client specific for details like name and email.
Change to make parameter fetching cobrand specific
and adapts Westminster and Hackney to use this.
https://github.com/mysociety/societyworks/issues/3411
=> [Brent] Look for Azure name in correct parameters

web/cobrands/fixmystreet/assets.js
Adds a class to the mobile alert message that an asset has not been found based on the id of the alert message. That way a cobrand will only remove its own messages when triggered through 'not_found'.
Adds a check when enabling the report form too if there are any mobile asset not found messages.
https://github.com/mysociety/societyworks/issues/3269
=> [FMS] Stop cobrand removing stopper of another on mobile

CHANGELOG.md, perllib/FixMyStreet/Cobrand/UK.pm, t/app/controller/contact.t, templates/web/base/contact/form.html, templates/web/bathnes/contact/index.html
Closes https://github.com/mysociety/fixmystreet/issues/2303.
Adds a CAPTCHA to the contact form on FMS and cobrand sites; this only shows up for non-UK IP addresses.
=> Add CAPTCHA to contact form

perllib/FixMyStreet/App/Controller/Auth/Social.pm
If the single-sign on returns a blank name, don't overwrite any current name from FMS.
If it's not blank then the single-sign on should be the name used.
=> [FMS] Stop blank OIDC name overwriting name

perllib/FixMyStreet/App/Controller/Auth/Social.pm, perllib/FixMyStreet/Cobrand/Hackney.pm, perllib/FixMyStreet/Cobrand/Westminster.pm, t/Mock/OpenIDConnect.pm, t/app/controller/auth_social.t
Different single sign on instances send different parameter names containing user name and email details.
This moves the field identification to the Cobrand.
Refactored out of https://github.com/mysociety/fixmystreet/pull/4224 as core functionality as will affect Camden implementation.
=> [FMS] Move single sign on detail params to cobrand

perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/Northamptonshire.pm, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, perllib/FixMyStreet/Cobrand/Thamesmead.pm, perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/councils.t, t/cobrand/northamptonshire.t, t/cobrand/thamesmead.t, templates/web/fixmystreet-uk-councils/about/faq-en-gb.html, templates/web/fixmystreet-uk-councils/admin/bodies/_updates_disallowed_hint.html
Adds new options to updates_disallowed for reporter/staff to both leave updates (sure this has come up before, but never implemented as far as I can see). Fixes FD-2619 [skip changelog]
=> Add reporter/staff update_disallowed options

templates/web/camden/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html, web/cobrands/fixmystreet-uk-councils/assets.js
This prevents reports from being made on housing estate land and shows a not maintained message.
The asset config changes in `/data/servers` are in commit `7b54f1179fe6d9c43b17c3ad0f429f04090b9abf` on the `camden-housing-estates-asset-layer` branch.
Fixes https://github.com/mysociety/societyworks/issues/3416
=> [Camden] Add Housing Estate custom JS and templates

perllib/FixMyStreet/App/Controller/Auth/Social.pm
I recently had a situation where the id_token was missing so I was getting the "Sorry, we could not log you in" error but there were no details in the logs about _why_ it failed.
This change adds an extra bit of logging to show the response that comes back from the OIDC provider in the event that the id_token is determined to be invalid for whatever reason.
=> Log response when id_token is missing

.github/pull_request_template.md, .github/workflows/docs.yml, CHANGELOG.md, perllib/FixMyStreet/Cobrand/Greenwich.pm, perllib/FixMyStreet/Cobrand/Lincolnshire.pm, perllib/FixMyStreet/Cobrand/Shropshire.pm
Include documentation for three cobrands.
Documentation is put up at http://pages.mysociety.org/fixmystreet-pod/
=> Add documentation GitHub action.

perllib/FixMyStreet/DB/Result/Comment.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Script/Alerts.pm, t/cobrand/oxfordshire.t
This also fixes an issue where alert emails were not renaming the state on the cobrand.
=> [Oxfordshire] Use renamed state also on .com.

templates/web/brent/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html, web/cobrands/fixmystreet-uk-councils/assets.js
Add messages for Brent and FixMyStreet.com for
categories that must be made in a park or on a highway.
Add in a function for the criterion argument for `road_not_found` to fix issue with housing stopper not being triggered when multiple bodies covering area.
=> [Brent] Add roads messages for parks and highways

perllib/FixMyStreet/App/Controller/My.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/my.t, t/app/controller/waste_peterborough.t, templates/email/default/waste/bulky-reminder.html, templates/email/peterborough/other-reported-bulky.html, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/cannot_book.html, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/summary.html, templates/web/base/waste/garden/csc_code.html, templates/web/peterborough/waste/bin_days_bulky.html
Fixes issues that have been raised by the client themselves or spotted by devs.
These include:
=> Peterborough bulky goods: post-staging fixes

bin/update-schema, db/downgrade_0081---0080.sql, db/schema.sql, db/schema_0081-alert-sent-cascade.sql, perllib/FixMyStreet/DB/Result/AlertSent.pm, perllib/FixMyStreet/DB/Result/UserPlannedReport.pm, perllib/FixMyStreet/TestMech.pm
If an alert is deleted, automatically drop its alert_sent rows; if a report or a user are deleted, drop any relevant user_planned_reports rows. [skip changelog]
=> Cascade delete alert_sent and user_planned_reports.

web/cobrands/brent/base.scss
Hey @dracos 
The original PR was replaced by a later [PR](https://github.com/mysociety/fixmystreet/pull/4191) on [client's request here](https://3.basecamp.com/4020879/buckets/28996137/todos/5548702394#__recording_5577093487):
So the first screenshot on this [issue]( https://github.com/mysociety/societyworks/issues/3419) is not longer the version we are using.
- Fixes the white colour on h1 headings for WW
- Transparent bg colour for summary-list element
- Styling of .govuk-button element
Let me know if you want to apply this one, it basically follows the style of the primary button. But if you prefer to use the default styling govuk-button I'll drop this commit.
Fixes: https://github.com/mysociety/societyworks/issues/3419
Let me know if there is any feedback.
=> [Brent] WW front end

perllib/FixMyStreet/Cobrand/Brent.pm, templates/web/brent/header_extra.html, templates/web/brent/waste/services.html, web/cobrands/brent/base.scss
Adds the framework for a working bin page with reporting a missed collection.
Will need services, events and correct bin images adding.
'Request a new container' and 'Subscribe to' are not implemented.
https://github.com/mysociety/societyworks/issues/3403
=> [Brent] Add a working bin page with report missed collection

perllib/FixMyStreet/App/Controller/Admin.pm, perllib/FixMyStreet/Map.pm, t/app/controller/admin/templates.t, t/app/controller/report_import.t, templates/web/base/admin/config_page.html, templates/web/base/admin/config_page_cobrand.html, templates/web/base/admin/config_page_cobrand_one.html, templates/web/base/admin/config_page_value.html
This adds a superuser-only page to the site listing the `COBRAND_FEATURES` configuration indexed by feature, plus a page per cobrand showing that cobrand's entries in that configuration.
=> Add admin page to view COBRAND_FEATURES config.

CHANGELOG.md, perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm, templates/web/base/report/update/moderation_diff.html, templates/web/base/report/update/moderation_photo_diff.html
closes https://github.com/mysociety/societyworks/issues/2585
=> Display photo changes in report moderation updates.

web/cobrands/fixmystreet-uk-councils/assets.js, web/cobrands/fixmystreet/assets.js
This adds a new `filter:` option for the asset_layers which allows you to pass an instance of `OpenLayers.Filter.Comparison` or similar, for times when `filter_key`/`filter_value` don't do what you need.
I've used this new option to filter out streetlights (aka columns) that have a `symlink` property of `0`.
See also commit `b4cd0ce6d4f16113b5f4182b4f319877ae426bc4` in the `/data/servers` repo, which has the change to the asset YAML.
Fixes https://github.com/mysociety/societyworks/issues/3418
=> [Camden] Ignore street light assets with symlink = 0

perllib/FixMyStreet/Cobrand/Camden.pm
Enable social auth for the Camden cobrand.
At this stage we don't know which fields the name/email are actually in, so I've put in some placeholders and some logging to help us figure out where they are.
Credentials for this are in the config files on the servers.
Part of https://github.com/mysociety/societyworks/issues/3307
=> [Camden] Enable social auth for Microsoft Azure login

templates/web/base/admin/config_page_cobrand.html, templates/web/base/admin/config_page_cobrand_one.html, web/cobrands/sass/_admin.scss
Just a couple of little things that make it easier to navigate the pages that I've found useful.
- Link to individual cobrand pages from each feature
- Link back to main page from each feature key on cobrand page
- Use sticky headers for table on main page
=> Small tweaks to admin COBRAND_FEATURES page

web/cobrands/camden/base.scss
Fixes: https://github.com/mysociety/societyworks/issues/3462
I reverted the input Camden styling when a user is moderating a report.
Let me know if there is any feedback.
=> [Camden] Added fix for input when moderating reports

CHANGELOG.md, perllib/FixMyStreet/App/View/Web.pm
If the site is present on multiple application servers, the last modified times will be different on each server. This means that multiple copies can be fetched/cached by a browser, and that the service worker can repeatedly fetch the files to go in the cache as it thinks they have changed when they have not.
=> Use digest rather than mtime for static versioning.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, templates/web/buckinghamshire/report/new/roads_message.html
Requests to update the postcode text to say that you can enter a report number.
Not to prompt the citizens to nudge the report pin over the border when on a borderline road and to direct to FMS instead.
https://mysocietysupport.freshdesk.com/a/tickets/2683
https://mysocietysupport.freshdesk.com/a/tickets/2692
=> [Bucks] Text changes for Bucks

perllib/FixMyStreet/Cobrand/Camden.pm, t/cobrand/camden.t
On the staging site there's just one "River Piers" category, but on the live site there are quite a few. Luckily they all start with "River Piers", so switching to using `NOT LIKE` is enough to ignore the live categories.
Fixes https://github.com/mysociety/societyworks/issues/3500
=> [Camden] Ignore live TfL River Piers categories

perllib/FixMyStreet/Cobrand/Camden.pm
Azure has been configured so that the users email address appears in the "preferred_username" field, so look for it there.
Fixes https://github.com/mysociety/societyworks/issues/3307
=> [Camden] Get email from preferred_username field

perllib/FixMyStreet/App/Controller/Photo.pm, perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_peterborough.t
For https://github.com/mysociety/societyworks/issues/3410.
Adds code that gathers together the various photos that may be uploaded during a bulky collection,  so that `process_photo_upload_or_cache` in App/Controller/Photo.pm can handle them (put them in an 'upload_fileid' stash field). This is because `save_user_and_report` in App/Controller/Report/New.pm expects 'upload_fileid' in the stash, in order to set 'photo' on the report (the 'photo' field is what is ultimately used to send data through Open311 to Bartec).
=> [Bulky Goods] Munge photo data so it can be picked up by Bartec

web/cobrands/northumberland/base.scss
This PR prevents the staging sit banner to get hidden by the navbar:
=> [Northumberland] Increse z-index staging warning site banner

bin/fixmystreet.com/waste-bulky-reminders, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/peterborough/_bulky_data.html, templates/email/peterborough/other-reported-bulky.html, templates/email/peterborough/other-reported-bulky.txt, templates/web/base/waste/bin_days_sidebar.html, templates/web/peterborough/waste/_more_services_sidebar.html, templates/web/peterborough/waste/header.html, templates/web/peterborough/waste/services.html
- Adds a `staff` value to `bulky_enabled` setting that prevents non-staff users accessing bulky goods feature
- Replaces cancellation link with phone number in confirmation & reminder emails
=> [Bulky Goods] Soft launch for staff-only

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/app/controller/waste_peterborough.t, templates/email/peterborough/_bulky_data.html, templates/email/peterborough/other-reported-bulky.html, templates/email/peterborough/other-reported-bulky.txt, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/booking_cancellation.html, templates/web/base/waste/bulky/cancel_intro.html, templates/web/base/waste/bulky/intro.html
For https://github.com/mysociety/societyworks/issues/3410.
Fixes https://3.basecamp.com/4020879/buckets/26662378/todos/5745542885, https://3.basecamp.com/4020879/buckets/26662378/todos/5449035154 and https://3.basecamp.com/4020879/buckets/26662378/todos/5851755632.
=> Peterborough Bulky Goods: text & link updates

templates/web/base/waste/bulky/summary.html, web/cobrands/peterborough/base.scss, web/cobrands/sass/_waste.scss
Fixes part of https://github.com/mysociety/societyworks/issues/3425
In the "Location details" page I think we should wrap the instructions using the `govuk-warning-text` with the icon so it doesn't get lost, specially for visually impaired users. It seems like and important message that needs some special attention. I tried changing it, but I realise it's part the `bulky.pm` file.
Let me know if there is any feedback
=> [Bulky] Added front-end fixes for Bulky waste

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/forms/waste/bulky.t, templates/web/base/govuk/fields.html
For https://3.basecamp.com/4020879/buckets/26662378/todos/5821380701.
Removed the optgroup logic because this prevents the list of items being alphabetical under JS (JS users do not see option grouping; option grouping was there for the benefit of non-JS users, but the non-JS experience is already less than ideal so option grouping arguably doesn't add much).
=> [Bulky Goods] Sort item list on booking form alphabetically

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/cobrand/peterborough/bulky-goods/unit.t, templates/web/base/waste/bulky/choose_date.html
Should hopefully speed up display of the available dates page a bit...?
Shows first two available dates on "Choose date for collection" page, and reinstates "Show later dates"/"Show earlier dates" buttons.
=> [Bulky Goods] Only show two dates per page

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Bodies.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, t/cobrand/highwaysengland.t
Partially fixes https://github.com/mysociety/societyworks/issues/3469.
=> Add cobrand hook for validating category name and implement suffix test for National Highways.

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
Adds a town to disambiguate_location to what results to return so out of area places not returned.
Tidies up results to not include the full Brent address - just street and postcode.
To fix: https://3.basecamp.com/4020879/buckets/28996137/todos/5880896603
=> [Brent] Accurate/tidy search of Brent areas to make report

docs/pro-manual/deep-linking.md
Updates documentation for clients on `filter_category`/`filter_group` behaviour. Fixes https://github.com/mysociety/fixmystreet/issues/4282.
=> [FMS] Update documentation for filter_category behaviour

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/cobrand/brent.t, templates/web/brent/admin/templates/_external.html
Auto responses for non-waste categories for Echo
need to be stripped down to just the resolution code and not to have commas in.
https://github.com/mysociety/societyworks/issues/3531
(linking to https://3.basecamp.com/4020879/buckets/28996137/todos/5870961914#__subscriptions)
=> [Brent] Add auto template triggering to Echo for Brent

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
Request from client support to make this category only usable by staff and to advise users to phone
https://mysocietysupport.freshdesk.com/a/tickets/2706
=> [Peterborough] Make bin not returned to collection point staff only

web/cobrands/brent/base.scss
This PR fixes:
https://github.com/mysociety/societyworks/issues/3516
I couldn't check if "Subscribe to Garden waste collection service" was solved, not if I need to add something to the cobrand in order to be able to access that content. But I think it used the same `.govuk-button--secondary` class than the "Submit a container request". 
Let me know if there is anything I need to amend =)
=> [Brent] Added styling for .govuk-button--secondary button

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kingston.t, t/app/controller/waste_sutton_garden.t, templates/web/kingston/waste/garden/subscribe_intro.html, templates/web/sutton/waste/garden/subscribe_intro.html
This means you can add new costs that will come into effect in the future in the config and it will automatically start using them at the appropriate time.
Fixes https://github.com/mysociety/societyworks/issues/3451
- ~~At the moment this is just for the SLWP cobrands, I haven't made this change affect e.g. Bromley.~~ See below, have updated this so it works with all cobrands.
- All of the costs need a `start_date`, so need to make up a start date in the past for the current cost. See example configuration below.
- If the cost in the config is a numerical value rather than an array of values then this will be used as the cost (so will work without updating the config, if needed)
Will need to update the server config when deploying this to reflect the new prices.
```yaml …
```
=> [SLWP] Add support for dynamic costs based on date

web/cobrands/tfl/layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/3132
They issue of the odd scroll bar appearing on the navbar was a problem only in Chrome, when I tried to replicate the problem on Safari and Firefox I couldn't see it. 
I added a fix that prevents the scroll bar to be displayed.
=> [TFL] Added fix that prevents scroll bar to appear on navbar

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/Bottomline.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/Integrations/Bottomline.pm, t/app/controller/waste.t, t/app/controller/waste_kingston.t, t/app/controller/waste_sutton_garden.t, t/cobrand/kingston.t, templates/web/base/waste/garden/wrong_user.html
The contact ID seems to be available in the mandate, and given this it seemed safer to only proceed if we know we have got a mandate to amend/cancel. [skip changelog]
=> [SLWP] Use fetched DD rather than storing info.

templates/web/hart/footer_extra.html
Links for data and contact weren't correct in the footer of Hart Cobrand
=> [Hart] Amended links in the footer for data and contact

templates/web/peterborough/waste/_more_services_sidebar.html, templates/web/peterborough/waste/confirmation.html
This reverts commit d4d5cd612893f9958e6170b52f0b27c7f1761a10 (https://github.com/mysociety/fixmystreet/pull/4277).
As per FD ticket https://mysocietysupport.freshdesk.com/a/tickets/2839,
which asks for food bags to be re-enabled.
Confirmation messaging has also been changed.
=> Revert "[Peterborough] Request to suspend food bags"

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Offline.pm, templates/web/base/around/postcode_form.html, templates/web/base/common_scripts.html, templates/web/base/main_nav_items.html, templates/web/base/offline/fallback.html, templates/web/base/offline/service_worker.html, templates/web/fixmystreet.com/footer_extra.html, web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/fixmystreet/offline.js, web/cobrands/fixmystreet/offline_report.js, web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss, web/js/front.js, web/js/offline_draft.js
- Adds report form to offline fallback page
- Automatically saves data from that form as a draft report in IndexedDB
- Button on front page to continue draft report on normal /report/new flow when back online
- Edits made to report when continuing draft are saved
- Uses Dropzone for photo handling, stores images in IndexedDB
Bugs yet to be fixed:
Outstanding features required for parity with existing app:
Future improvements:
- Automatically start draft when going through /report/new flow in usual online manner
- ???
For https://github.com/mysociety/fixmystreet/issues/2221
**NB** This would all probably benefit from some design love :)
The offline page now has a form for storing a draft report:
Users can store their current location, attach photos with the usual Dropzone UI, and enter a …
=> Offline reporting functionality

docs/_layouts/pro.html, docs/_layouts/wasteworks.html, perllib/FixMyStreet/Cobrand/Lincolnshire.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Queue/Item/Report.pm, perllib/Open311/GetServiceRequests.pm, t/cobrand/lincolnshire.t
Lincolnshire have requested that reports pulled in via Open311's
GetServiceRequests are created using the user information stored in
their backend system.
This is so that the reports created in FixMyStreet are associated with
the email address of the original reporter so they can receive updates
on reports.
Open311 adapter change to add the user data is here: https://github.com/mysociety/open311-adapter/pull/228
Part of https://github.com/mysociety/societyworks/issues/3079
=> [Lincolnshire] Pull in user information via Open311 so customers can receive updates

perllib/FixMyStreet/Cobrand/Camden.pm, t/cobrand/camden.t
Request to add user name and email to csv export
https://mysocietysupport.freshdesk.com/a/tickets/2812
=> [Camden] Add Name and email fields to data export

CHANGELOG.md, templates/web/base/header.html, templates/web/oxfordshire/header.html, templates/web/zurich/header.html
This improves the responsiveness of UI elements on mobile by telling the browser not to wait 350ms before acting upon the event.
More details on the WebKit blog:
https://webkit.org/blog/5610/more-responsive-tapping-on-ios/
and the Chrome blog:
https://developer.chrome.com/blog/300ms-tap-delay-gone-away/
=> Set ‘width=device-width’ in viewport meta tag

perllib/FixMyStreet/Cobrand/Brent.pm
Set cut off date to Brent go-live date so reports in all reports shown from then
https://github.com/mysociety/societyworks/issues/3421
=> [Brent] Add report cut off date

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
On reports pages (and heatmap), we know all reports involved are owned by the body, so do not need to perform this check. [skip changelog]
=> [Bucks] Bypass ownership check on on reports pages

templates/web/bathnes/around/intro.html, templates/web/bathnes/header_site.html, web/cobrands/bathnes/_colours.scss, web/cobrands/bathnes/base.scss, web/cobrands/bathnes/layout.scss
Bathnes council asked for a new style for their homepage and also to use "Arial" instead of the current one.
Fixes: https://github.com/mysociety/societyworks/issues/3581
Preview:
[skip changelog ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog
Let me know if there is any feedback
=> [Bathnes] New style for homepage

t/cobrand/bucks.t, templates/email/buckinghamshire/submit.html, templates/email/buckinghamshire/submit.txt
Request by Bucks not to show staff details when user is anonymous
https://mysocietysupport.freshdesk.com/a/tickets/2725
=> [Bucks] Dont give staff name/email when contributing for anon user

templates/web/base/header.html, web/cobrands/sass/_base.scss, web/cobrands/sass/_report_list.scss
Prevent over-scrolling of the page, user selection on the map, and leave enough gap at the bottom on the full screen map.
I have tested the first two on my phone, but the last one I'm not sure how to emulate properly (as it's only in the native app wrapper that it's fullscreen enough for it to matter, IYSWIM).
=> Tweak app-like display CSS.

templates/web/northumberland/header_extra.html, templates/web/northumberland/tracking_code.html
closes https://github.com/mysociety/societyworks/issues/3477
Tested with locally spoofed domain - no gtag analytics cookies when rejected.
Configuration based off of https://www.northumberland.gov.uk
=> [Northumberland] Add cookie banner and analytics.

templates/web/northumberland/about/faq-en-gb.html
Add a section to the FAQ page about contacting the council by phone.
Fixes https://github.com/mysociety/societyworks/issues/3629
To see the actual changes you can run:
```
git diff --no-index templates/web/fixmystreet-uk-councils/about/faq-en-gb.html templates/web/northumberland/about/faq-en-gb.html
```
=> [Northumberland] Add contact-by-phone information to FAQ

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report/New.pm, templates/web/base/report/form/photo_upload.html, templates/web/zurich/report/new/fill_in_details_form.html, web/cobrands/fixmystreet/fixmystreet.js
fixes https://github.com/mysociety/societyworks/issues/3072
Additionally:
* Move category selection before photo upload for Zurich so the label is changed before the reporter is prompted.
* Make the photo field label visually appear as a label. Currently this appears as normal text which looks especially weird for Zürich after the above change. This applies to all cobrands.
I have skipped setting up a cypress test as it was taking me too long.
Setup: category 'Graffiti' requires a photo, the others don't.
https://user-images.githubusercontent.com/9289297/235450684-cf0452c6-bb82-47aa-a3f0-1ea3bd0ca46b.mov
=> [Zürich] Stop showing optional label on photo field when not optional.

docs/_posts/2023-05-10-v5.0.md, perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm, t/app/controller/moderate.t
[skip changelog] Spotted by Tracy on a Bucks report with a Confirm reference (which should be ignored anyway, so added).
=> Fix display of moderated extra.

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
This is required so that these categories don't appear when National Highways is responsible for the litter on a section of road.
=> [Northumberland] Add litter categories to NH _cleaning_categories

CHANGELOG.md, perllib/Open311.pm
Send 'closed' rather than 'open' when a report is closed and extended statuses are being used.
=> Fix status in open311 service request update when report closed.

web/cobrands/sass/_dashboard.scss
Fixes: https://github.com/mysociety/societyworks/issues/3663
This PR includes two commits:
The first one should* fix the non-wrapping behaviour that the dashboard currently has. I think due to the number of fields in the form it makes sense that they wrap up instead of just cutting each other.
_*I couldn't find the original screen that was shown in the issue listed above, so I used one screen that seemed similar(/dashboard?group_by=month), but I might need to enable something in order to see the original screen and properly test it. In this case I only added extra fields in the browser to test what happens with extra fields, like the ones shown in the original issue._
The second one is just for aesthetics purpose and happy to drop it if it only adds more complexity to the code. I noticed …
=> FMS Admin Dashboard form

CHANGELOG.md, templates/web/base/auth/create.html, templates/web/base/auth/general.html, templates/web/camden/auth/general.html, templates/web/hackney/auth/general.html, templates/web/kingston/auth/general.html, templates/web/sutton/auth/general.html, templates/web/westminster/auth/general.html
This makes logging in easier on mobiles as the email-specific soft keyboard is presented.
=> Use email field type when SMS authentication not in use

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/app/controller/around.t, templates/web/base/admin/config_page_cobrand.html, templates/web/base/admin/config_page_value.html, web/js/duplicates.js
For UK councils this is picked up from cobrand feature config.
For FD-2997.
=> Allow cobrands to customise nearby lookup distances for duplicates

perllib/FixMyStreet/Cobrand/Gloucestershire.pm, t/cobrand/gloucestershire.t
Fixes https://github.com/mysociety/societyworks/issues/3650.
There is also a change in commit 553a30878, `glos-confirm-integration`, in mysociety-servers.
=> Glos. confirm integration: Homepage placeholder text

templates/web/fixmystreet.com/about/_sidebar.html, templates/web/fixmystreet.com/about/faq-en-gb.html, templates/web/fixmystreet.com/about/house-rules.html, templates/web/fixmystreet.com/contact/unsuitable-text.html, templates/web/fixmystreet.com/contact/who.html, templates/web/fixmystreet.com/report/new/inline-tips.html
Changes references from House Rules to Conditions of Use.
Adds text to be clear about abusive messages to FMS. This is being updated in terms of good practice - not in relation to any abuse.
https://github.com/mysociety/societyworks/issues/3713
=> [FMS] Update House Rules with name change and staff well-being text

perllib/FixMyStreet/Cobrand/Gloucestershire.pm, templates/web/gloucestershire/about/faq-en-gb.html, templates/web/gloucestershire/contact/_footer.html, templates/web/gloucestershire/contact/submit.html
Closes https://github.com/mysociety/societyworks/issues/3653.
- We hide the fixmystreet.support@gloucestershire.gov.uk email from
public view (this includes the error message shown when contact form
submission fails)
- We direct users to GCC's external privacy page
There is also a commit (4e02a79d9) in mysociety-servers -> `glos-confirm-integration` branch to add `contact_email` to the staging config.
=> [Glos] Contact and privacy information

perllib/FixMyStreet/Cobrand/Brent.pm
Essentially reverts https://github.com/mysociety/fixmystreet/commit/4e1db0039cb4cbb5cfae87ea3468b9cf26092c70.
For FD-3057.
=> [Brent] Allow missed reports before 10pm

templates/web/camden/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html
For some reason this template got missed, which was part of the reason the layer preventing reports made off-road wasn't working.
The other part of this fix is commit `265b941e8d5ddd6d131426ddae9ec8b3cb6a357e` in the servers repo.
For FD-3055
=> [Camden] Add missing "not on a road" message

web/cobrands/brent/base.scss
Removes excess padding on an empty update in Brent
From:
To:
=> [Brent] Remove extra padding above blank update

.cypress/cypress/fixtures/brent-tfl.xml, .cypress/cypress/integration/brent.js, bin/fixmystreet.com/fixture, data/test-asset-layers.yml, perllib/FixMyStreet/Cobrand/TfL.pm, t/Mock/MapIt.pm, web/cobrands/fixmystreet-uk-councils/assets.js
[skip changelog] Fixes FD-3072.
Adds the relevant Brent group to the cleaning list, and allows through reports if they're made on a red route.
=> [Brent] Street cleaning on red routes

bin/repl, cpanfile, cpanfile.snapshot, script/console
This is a very simple REPL for making quick database queries via the perl interface, without having to go via bin/cron-wrapper.
It defines top-level convenience methods for all `FixMyStreet::DB::Result` subclasses, so you can do `Problem->search` instead of `FixMyStreet::DB->resultset('Problem')->search`.
Adding a semi-colon to the end of a line suppresses the output, which is useful when you get back a big database result object that you don't want dumped to the terminal.
$ bin/repl
FMS> $p = Problem->find(id => 42);
FMS> $p->get_extra_metadata
{}
FMS> $p->set_extra_metadata(foo => 'bar')
{'foo' => 'bar'}
FMS> $p->update;
FMS> Comment->search({ state => 'confirmed' });
FMS> User->search({ email => 'user@example.com' });
=> Add bin/repl script

conf/packages
This package is needed for the Term::ReadLine dependency, which is used by the `bin/repl` script.
Follows on from #4479
=> Add libreadline-dev to conf/packages

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Templates.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/DB/Result/Contact.pm, t/app/controller/admin/bodies.t, t/cobrand/bucks.t, templates/web/base/admin/bodies/body.html
As Bucks can set both state and external status code (for email updates), need to check differently. Use a cobrand variable. [skip changelog] Fixes FD-3138.
Plus a fix for apostrophe in category name noticed in FD-3141.
=> [Buckinghamshire] Allow templates in same category, different code.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/App/View/Web.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, templates/web/peterborough/waste/_announcement.html, templates/web/peterborough/waste/_more_services_sidebar.html, templates/web/peterborough/waste/_service_navigation_bar.html, templates/web/peterborough/waste/bin_days_bulky.html
And make location page staff only. And only allow bulky on properties with black bin service.
[skip changelog] Fixes FD-3148 and FD-3150
=> [Peterborough] Small bulky text changes

perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/app/controller/waste.t, t/app/controller/waste_sutton_r.t, templates/email/kingston/other-reported.html, templates/email/kingston/other-reported.txt, templates/email/sutton/other-reported.html, templates/email/sutton/other-reported.txt, templates/web/base/waste/confirmation.html, templates/web/kingston/waste/_confirmation_after.html
[skip changelog] Fixes FD-3154.
This turns on wasteworks_config for bromley/sutton/Kingston and then you'd create a `request_timeframe` key which would contain "20 working days" for Kingston, "30 working days" for Sutton, and "two weeks" for Bromley.
=> [Waste] Move request timeframe to configuration.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/app/controller/claims.t
Bucks no longer need claims going to email now we're sending claims to EvoClaim (#4357).
This change separates the claim auto-response template code from the claims email sending code and then removes the claim email sending code entirely.
Also updated a couple of comments while I was in the file.
Fixes https://github.com/mysociety/societyworks/issues/3768
=> [Buckinghamshire] Turn off claims emails

web/js/waste.js
If only some items have a price set it's possible for the total price of the booking to be displayed as `£NaN`.
=> Fix £NaN display on bulky items page when per-item pricing active

web/cobrands/sass/_base.scss
Having the report thumbnails butted up against the right hand edge of the page looked a little odd, so this commit mirrors the padding from the left hand side for symmetry.
Raised in FD-3161
=> Increase front page thumbnail right padding on mobile

.cypress/cypress/integration/duplicates.js, perllib/FixMyStreet/App/Controller/Around.pm, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/app/controller/report_new_open311.t, web/js/duplicates.js
Showing reports that might be duplicates of the report the user is making is a cobrand feature, and only works on branded sites.
This makes it work on cobrand areas on FixMyStreet where the duplication_suggestion is turned on for the cobrand on the selected category.
https://github.com/mysociety/societyworks/issues/3646
=> [FMS] Adds duplicate_suggestion functionality to FMS

CHANGELOG.md, bin/update-schema, db/downgrade_0085---0084.sql, db/schema.sql, db/schema_0085-add-problem-send-state.sql, perllib/FixMyStreet/App/Controller/Admin.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Zurich.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Queue/Item/Report.pm, perllib/FixMyStreet/Script/Reports.pm, t/app/controller/report_new_unresponsive.t, t/app/controller/report_new_update.t, t/app/controller/waste_brent_garden.t, t/app/controller/waste_kingston.t, t/app/controller/waste_peterborough.t, t/app/controller/waste_sutton_garden.t, t/app/model/problem.t, t/cobrand/bromley.t, t/cobrand/bucks.t, t/cobrand/hackney.t, t/cobrand/highwaysengland.t, t/cobrand/peterborough.t, t/cobrand/zurich.t, t/sendreport/open311_send.t, t/sendreport/two-tier/open311-both.t, templates/web/base/admin/problem_row.html
Similar to comments which already have them, adds a send_state column to both make finding things still to process easier and also being able to manually mark things as not being sent without losing their associated body.
Fixes https://github.com/mysociety/fixmystreet/issues/4048.
=> Add send_state column to problems

CHANGELOG.md, templates/web/base/admin/bodies/contact-form.html, templates/web/base/report/new/_form_labels.html, templates/web/base/report/new/form_report.html, templates/web/base/report/new/form_title.html
Also fixes a bug introduced in #4471 where the detail hint default text would stop displaying for cobrands without a bespoke value set.
=> Move form override defaults into cobrand code from templates.

CHANGELOG.md, bin/update-schema, db/downgrade_0085---0084.sql, db/schema.sql, db/schema_0085-add-problem-send-state.sql, perllib/FixMyStreet/App/Controller/Admin.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Zurich.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Queue/Item/Report.pm, perllib/FixMyStreet/Script/Reports.pm, t/app/controller/report_new_unresponsive.t, t/app/controller/report_new_update.t, t/app/controller/waste_brent_garden.t, t/app/controller/waste_kingston.t, t/app/controller/waste_peterborough.t, t/app/controller/waste_sutton_garden.t, t/app/model/problem.t, t/cobrand/bromley.t, t/cobrand/bucks.t, t/cobrand/hackney.t, t/cobrand/highwaysengland.t, t/cobrand/peterborough.t, t/cobrand/zurich.t, t/script/send-daemon.t, t/sendreport/open311_send.t, t/sendreport/two-tier/open311-both.t, templates/web/base/admin/problem_row.html
The first two commits were reviewed in #4505. The two fixups in here deal with issues found before putting live:
* There was an issue with the marking of rows as processed not being saved; and if that had been working, then it would have marked unconfirmed reports as processed
* The DB migration marked all rows as processed, when we need to update any currently unsent rows as unprocessed.
=> Add send state to problems (fixes)

templates/web/gloucestershire/report/new/roads_message.html, web/cobrands/fixmystreet-uk-councils/assets.js
In conjunction with assets .yml file in `mysociety-servers` -> `glos-confirm-integration-assets` -> 72fa38c9d.
Closes https://github.com/mysociety/societyworks/issues/3696.
=> [Glos] Add stylemap and not-found messages for assets

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
These will have been left by the inspector form.
=> [Bromley] Skip updates lacking a title.

web/cobrands/fixmystreet-uk-councils/assets.js
[skip changelog] Fixes FD-3144. Configuration change:
```
-  actions:
-    found: fixmystreet.message_controller.road_found
-    not_found: fixmystreet.assets.banes.road_not_found
+  nearest_radius: 0.1
+  actions: fixmystreet.assets.banes.road_actions
```
BANES roads have widths, so nearest radius I think is okay, and needed so that it doesn't allow on curo land next to a road.
=> [BANES] Allow Curo reports on highways.

web/cobrands/bromley/layout.scss, web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/3810
The rule padding: flip(0 0 0 1em, 0 1em 0 0) has been replaced so there is always some horizontal padding.
This commit also fixes the left padding for cobrands using a pin icon in the "Recently reported problems" section in the front page.
=> Fixed padding for 'item-list--reports__item a'

CHANGELOG.md, perllib/FixMyStreet/Script/SendDaemon.pm, templates/email/buckinghamshire/submit.html, templates/email/buckinghamshire/submit.txt, templates/email/default/cy/submit.html, templates/email/default/cy/submit.txt, templates/email/default/submit.html, templates/email/default/submit.txt, templates/email/fixmystreet.com/cy/submit.html, templates/email/fixmystreet.com/cy/submit.txt, templates/email/fixmystreet.com/submit.html, templates/email/fixmystreet.com/submit.txt, templates/web/base/admin/triage/_inspect.html
If there are a number of reports failing to send, leaving it to database order could cause the same reports to be returned over and over, never looking at other waiting reports.
And fix fallback code thing.
=> Return random unprocessed row to daemon.

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_garden.t, templates/web/brent/waste/services.html
The BRT - Paid Collection Container Quantity has code 1 matching 1 bin and continues with 2:2, 3:3 etc so the number code corresponds to the number of bins.
We have relied on the code for the number of bins.
However, when we reach 9, that corresponds to sacks rather than a number so if we have 9 bins - it is, in fact, a sack subscription and the template adapts accordingly.
https://mysocietysupport.freshdesk.com/a/tickets/3211
=> [Brent] Amend template so '9' represents sacks rather than 9 bins

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/integrations/evo_claim.t
When looking up the nearest road we're only checking a 200m radius, which means that sometimes there are claim reports that don't get a road because they're further than 200m from a road (e.g. claims for accidents on a footpath). Handle this by returning "Unknown location" if no roads are returned.
Fixes https://github.com/mysociety/societyworks/issues/3803
=> [Buckinghamshire] Evo: Handle locations with no nearby roads

CHANGELOG.md, perllib/FixMyStreet/App/Controller/My.pm, perllib/FixMyStreet/DB/ResultSet/Body.pm, perllib/FixMyStreet/DB/ResultSet/Contact.pm, templates/web/base/report/_item_small.html
Worst thing was shortlist report sorting was doing a DB query each call of the sort function (eek).
=> Reduce some DB queries

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
As discussed in https://mysocietysupport.freshdesk.com/a/tickets/3047.
Brent are switching to the OSPlaces API as a reverse geocoder, and along with this change, want a street name column in their reports CSVs.
Also handles OSPlaces data for open311_extra_data_include() method.
=> [Brent] Use OSPlaces API as reverse geocoder

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/FixMyStreet/Roles/ParallelAPI.pm, templates/web/base/header.html, templates/web/base/waste/bin_days.html, templates/web/fixmystreet-uk-councils/footer_extra_js_base.html, templates/web/peterborough/footer_extra_js.html, templates/web/peterborough/waste/bin_days_bulky.html
Extends the use of the HTMX partial page refresh to Echo WasteWorks API calls. Turned out to be fairly straightforward in the end, the only real change was to ensure the results of the property lookup aren’t cleared if the request is made by HTMX/page refresh while waiting for second batch of API calls to return.
(That makes me wonder if I’ve missed something somewhere though… But everything seems to work as expected.)
=> [Waste] Async Echo API calls for bin days page

web/cobrands/gloucestershire/_variables.scss, web/cobrands/gloucestershire/base.scss
Fixes: https://github.com/mysociety/societyworks/issues/3811
Fixes part of: https://github.com/mysociety/societyworks/issues/3812 
This PR fixes:
Button styling on "Your account" page
Date contrast ratio
@nephila-nacrea and @jacquelinebylau 
Two of the problems listed[ here](https://github.com/mysociety/societyworks/issues/3812 ), weren't just Glos problems. So I fixed it across all cobrands on these PRs:
- [Here are some nearby reports marginal - ration required = 4.5 - actual = 4.48](https://github.com/mysociety/fixmystreet/pull/4554)
- [ 'Closed' marker well below - actual = 3.54](https://github.com/mysociety/fixmystreet/pull/4553)
=> [Glos] Accessibility Issues

templates/web/thamesmead/about/web-app.html
Similar to https://github.com/mysociety/fixmystreet/pull/4485 the Peabody/Thamesmead cobrand was missing PWA instructions because it doesn't inherit from the UKCouncil cobrand. Fixed by symlinking the appropriate file.
=> [Thamesmead] Add PWA instructions

CHANGELOG.md, perllib/FixMyStreet/DB/ResultSet/Problem.pm, perllib/Integrations/Bartec.pm, perllib/Memcached.pm
This PR changes the front page number calculations to do two things:
* Change the cache time from a fixed number (default 1hr) to a spread (45-75 minutes)
* Adds a 'lock' so that only one call to the backend calculation should be made - so 3 memcached calls rather than 1, but much better than having to do the calc.
@sagepe asked you as of interest in terms of stopping the hourly issue, and doesn't really involve any FMS code, only generic Perl, but can ask someone else/as well if preferred
=> Front page cache herding

web/cobrands/sass/_layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/3873
Another alternative to accomplish the same result was to use `width: fit-content`, but it's not supported by IE11. Not that it matter according to [GOVUK](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices). Let me know if you prefer me to use that property instead.
=> Added fix to .form-error width

templates/web/base/contact/form.html, templates/web/fixmystreet.com/contact/who.html
Fixes: https://github.com/mysociety/societyworks/issues/3826
Part of this milestone: https://github.com/mysociety/societyworks/milestone/99
This PR should improve accessibility and make the input looks more noticeable.
I have also include the `input[type="text"] and  input[type="textarea"]` in this PR.
[Skip Change log]
=> GOVUK Styling for inputs in contact page

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm
Functionality for 'show_later_dates' for K&S is a) currently broken and b) is not needed, so we simply deactivate that field.
=> [SLWP] Hide 'show_later_dates' option for bulky slot selection

perllib/FixMyStreet/Cobrand/Brent.pm
Similarly to 22fd8ee6f0b9d for Central Beds Jadu, we don't want to send updates to ATAK.
=> [Brent] Skip sending updates for ATAK backend.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/Integrations/Echo.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_kingston.t, t/app/controller/waste_kingston_r.t, t/app/controller/waste_sutton_garden.t, t/app/controller/waste_sutton_r.t
Contributes to https://github.com/mysociety/fixmystreet/pull/4547.
- Checks if a reserved collection slot has expired when user submits summary page
- If it has, we
- cancel the reserved slot
- attempt to automatically reserve a new slot with the same date before continuing to payment
- if this fails, we return the user to the slot selection page
=> [SLWP] bulky slot expiry

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_small_items.t
For https://github.com/mysociety/societyworks/issues/3883
I wondered if it'd be better to have the checkbox flags at the open311-adapter end, but that also seemed fragile in that it would have to e.g. parse the Notes field being passed through (given no individual data is). This is probably okay?
=> [Brent] Correct fields for Echo

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_small_items.t, t/cobrand/brent.t, templates/web/brent/waste/_more_services_sidebar.html
Allows any Brent resident with a domestic refuse collection to make a small items collection request.
In process fixes small error in Brent test mock data that is confusing but wasn't causing an issue.
=> [Brent][WW] Small items eligibility

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, perllib/FixMyStreet/Roles/SCP.pm, t/app/controller/waste_peterborough_bulky.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/default/waste/other-reported-bulky.html, templates/email/default/waste/other-reported-bulky.txt, templates/web/base/waste/bulky/_bin_days_list.html, templates/web/base/waste/bulky/booking_cancellation.html, templates/web/base/waste/bulky/cancel_intro.html, templates/web/base/waste/bulky/summary.html, templates/web/peterborough/waste/_bulky_not_signed_user.html
Various aspects brought together to make future merging easier:
* Add a report ID to cancel URLs, and list all bookings (no change/point at present, but as/when multiple bookings are allowed, these will be used)
* Add days_before, for times when cancellation might eg be two days before (though don't think is at present).
* Add a way for cancellation to be done by adding an update rather than a new report - most non-Peterborough will work this way, it looks like.
=> [Bulky waste] Framework for multiple bookings, different way of cancelling

perllib/FixMyStreet/App/Form/Waste/SmallItems.pm, t/app/controller/waste_brent_small_items.t, t/cobrand/brent.t, templates/web/base/waste/bin_days.html, templates/web/base/waste/bulky/_bin_days_list.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, templates/web/brent/waste/_more_services_sidebar.html
Changes the Brent bulky goods flow to say "small items" where relevant. Also hides anything relating to payments and pricing.
Fixes https://github.com/mysociety/societyworks/issues/3894 and https://github.com/mysociety/societyworks/issues/3893
=> [Brent] Rename bulky goods -> small items and hide pricing

perllib/FixMyStreet/Cobrand/Brent.pm
So that it can be included in the issue text in open311-adapter.
See also https://github.com/mysociety/open311-adapter/pull/304, which handles the open311-adapter side of things.
Part of https://github.com/mysociety/societyworks/issues/3836
=> [Brent] Send the report group over Open311

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, t/app/controller/waste_peterborough_bulky.t, templates/web/base/waste/bulky/_bin_days_list.html, templates/web/base/waste/bulky/summary.html
Fixes https://github.com/mysociety/societyworks/issues/3780 [skip changelog]
First adds ID to cancel URLs (so that you'll be able to choose which to cancel), then lists all bookings on bin day page (even though there's only one at this point), and then allow multiple bookings.
=> [Bulky] Allow multiple bookings

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_peterborough_bulky.t, templates/email/default/waste/csc_payment_failed.html, templates/email/default/waste/csc_payment_failed.txt, templates/web/base/waste/bulky/_bin_days_list.html, templates/web/base/waste/bulky/summary.html, templates/web/base/waste/garden/csc_payment_failed.html, templates/web/peterborough/waste/index.html
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/3781
The form is shown to staff at /waste, as requested by Peterborough.
=> [Bulky] Allow retrying of failed CSC payments.

bin/email-bulky-payment-echo-update-failed, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/app/controller/waste_kands_bulky.t, templates/email/default/waste/bulky_payment_echo_update_failed.txt
If Echo fails to send us an update after payment has been taken for a bulky collection, we send an email to Kingston or Sutton as appropriate, so the collection can be booked manually their end.
Closes https://github.com/mysociety/societyworks/issues/3842.
=> K&S Bulky: Send email if Echo update fails

t/app/controller/waste_kands_bulky.t, templates/web/base/waste/bulky/confirmation.html, templates/web/peterborough/waste/bulky/confirmation.html
Move from bespoke Peterborough design for Kingston and Sutton and any other cobrands to more consistent waste layout for confirmation.
https://3.basecamp.com/4020879/buckets/33314444/todos/6536119405
=> [SLWP] Make confirmation page more like other waste confirmations

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t
Kingston confirmation emails for bulky waste collection only send when payment is received so stop the email sending on report completion and add it into the payment callback.
=> Kands bulky send confirmation email after payment

web/js/waste.js
On page load after clicking back, the form values can be filled in with their previous values by the browser, but this happens later, so switch to the pageshow event to update the autocomplete/messages and check the hidden select - as the autocomplete will have picked up an empty select at the time it was created. [skip changelog]
=> [Waste] Improve page loading display.

t/app/controller/waste_kands_bulky.t, templates/web/base/waste/bulky/items.html, web/js/waste.js
Adds js for updating the amount of selected items and if price change is imminent.
Changes text for introduction box.
Fixes bug where total not being updated on page load.
Fixes final part of https://github.com/mysociety/societyworks/issues/3937
=> [SLWP] Kands collection page changes

templates/web/base/report/inspect/information.html
Adds name to inspector area by one council but seems like information pertinent for all.
https://mysocietysupport.freshdesk.com/a/tickets/3398
=> [FMS] Add name to inspector area

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
No longer allow request for replacement bin with cracked bin option.
https://mysocietysupport.freshdesk.com/a/tickets/3401
=> [Peterborough] Remove cracked bin option from waste services

t/cobrand/gloucestershire.t, templates/web/fixmystreet.com/report/_updates_disallowed_message.html
If a logged-in user can only leave updates on their reports if they’re closed, don’t incorrectly invite them to log in on open reports.
=> [fms.com][Gloucestershire] Show correct message for logged-out users trying to leave an update

perllib/FixMyStreet/Geocode/OSM.pm
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.
(Is: https://github.com/openstreetmap/operations/issues/951)
cc: @dracos
=> Switch to api.openstreetmap.org API host

perllib/FixMyStreet/Cobrand/TfL.pm
Config would then currently be `['TfL', 'National Highways', 'Dott', 'Tier', 'Lime', 'HumanForest']`
=> [TfL] Add config for including extra bodies on the site.

perllib/FixMyStreet/Cobrand/Gloucestershire.pm
As requested in https://3.basecamp.com/4020879/buckets/32187059/todos/6590902908#__recording_6645587896:
- Show green tick pin for closed or fixed enquiries
- Show 'blue man' pin for all defect jobs
=> [Glos] Show green tick pin for closed or fixed enquiries

perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/bristol.t
Bristol categories were being filtered out in the dropdown on a report's admin page for changing category.
Broaden the check on munge_overlapping_bodies to check for more that the first area as report admin uses a larger pool of areas taken from the mapit areas for the report location
https://github.com/mysociety/societyworks/issues/3942
=> [Bristol] Show Bristol categories on admin

perllib/FixMyStreet/App/Controller/Report/New.pm, t/app/controller/report_new_open311.t
The old app has a === "1" comparison in it to check for a question answer disabling, so make sure we output a string.
=> Make sure disable flag for old app is string "1".

perllib/FixMyStreet/Cobrand/TfL.pm, t/cobrand/tfl.t
TfL would like to be able to see the extra data for a category on the 'All report' on the dashboard as well as on the specifically selected category.
https://mysocietysupport.freshdesk.com/a/tickets/2556
=> [TfL] Add extra data to all report on dashboard

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_kands_bulky.t
So staff making a paye payment on behalf of a user will still initiate a confirmation of booking
https://github.com/mysociety/societyworks/issues/3957
=> [SLWP] Send confirmation email after confirmation

templates/web/base/report/banner.html, templates/web/fixmystreet.com/report/banner.html
Been pointed out that it is not clear what is unknown on a report with an unknown status - so add clarity by putting 'Status unknown'
https://github.com/mysociety/societyworks/issues/3950
=> [FMS] Change banner on report to 'Status unknown' instead of 'Unknown'

web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss
.form-hint element wasn't been displayed when non-nested inside` #front-main`, this because of the colour` $form-hint-color `variable. This variable will now take effect only when nested inside #front-main element. Any other` .form-hint` will have #666 colours.
=> Fixed invisible .form-hint element

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
Adds link for checking parish email addresses to documentation.
Prompted by https://mysocietysupport.freshdesk.com/a/tickets/3498
=> [Bucks] Add moderngov link to pod doc for parish emails

web/cobrands/fixmystreet.com/base.scss
Currently the new CTA in the contact page looks like this on desktop:
This PR includes a fix that gets rid of the styling for the CTA section that inherits some behaviour from the homepage and also the `.twothirdswidthpage` class.
This is how it looks with this PR
=> Added fix for CTA footer erasing homepage styling

perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t
Request that bulky not be offered if the service hasn't been initialised which may be the case on new builds
https://3.basecamp.com/4020879/buckets/33314444/todos/6713679040
=> [SLWP] Bulky can only be offered if service initiated

web/cobrands/bathnes/_colours.scss, web/cobrands/bristol/_colours.scss, web/cobrands/centralbedfordshire/_colours.scss, web/cobrands/isleofwight/_colours.scss, web/cobrands/lincolnshire/_colours.scss, web/cobrands/rutland/_colours.scss, web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/3827
This should fix the accessibility issue with the white text against green background for the `.green-btn` class . A list of variables has been included, so the button can be customised according to a cobrand's branding guide.
NOTE: I went for a neutral default colour for the background, because some cobrands will use these colours as well, and the FMS yellow would look odd with their branding colour. Which brings the question, with this PR, the primary button has variables now, therefore we could update all cobrands so they use their own colours, instead of the default ones.  Let me know what you think so I can create the relevant ticket.
=> Added variables for btn-primary, green-btn and btn--primary

web/cobrands/highways/assets.js
Fixes https://github.com/mysociety/societyworks/issues/3936.
The `regenerate_category()` function in web/cobrands/highways/assets.js was indiscriminately (re-)enabling the report form after category selection. So if user selected an NH road, selected the 'Somewhere else' option from the popup, then selected a category that should disable the form, the form would not be disabled.
=> Do not re-enable report form for non-NH categories

perllib/FixMyStreet/Cobrand/Bromley.pm, templates/email/bromley/waste/bulky-confirm-cancellation.txt
=> [Bromley] [Waste] No refund text for bulky cancel confirmations with no payment.

perllib/FixMyStreet/Cobrand/Thamesmead.pm, t/cobrand/thamesmead.t, templates/web/base/tokens/confirm_problem.html
If a report is made on the Thamesmead cobrand but not on a Thamesmead asset the contacts for the appropriate council will be displayed and a report can be made for that council.
https://github.com/mysociety/societyworks/issues/3571
=> [Thamesmead][Bexley][Greenwich] Allow council reporting on Thamesmead cobrand

perllib/FixMyStreet/App/Controller/Auth/Social.pm, perllib/FixMyStreet/Cobrand/Brent.pm, t/Mock/OpenIDConnect.pm, t/app/controller/auth_social.t, templates/web/base/auth/general.html
Allows Brent's `oidc_login` `COBRAND_FEATURE` to have a different set of values for whatever hostname is used for the request.
For example, to use a different config for `brent.wasteworks.example.org`:
```yaml
oidc_login:
brent:
client_id: 'fms_client_id'
secret: 'fms_secret'
display_name: 'Brent FMS Login'
auth_uri: 'https://oidc.example.org/oauth2/v2.0/authorize'
token_uri: 'https://oidc.example.org/oauth2/v2.0/token'
hosts:
brent.wasteworks.example.org:
client_id: 'ww_client_id'
secret: 'ww_secret'
display_name: 'Brent WasteWorks Login'
auth_uri: 'https://oidc.example.org/oauth2/v2.0/authorize'
token_uri: 'https://oidc.example.org/oauth2/v2.0/token'
```
For FD-3395
=> [Brent] Allow different OIDC config for WasteWorks host

.cypress/cypress/integration/brent.js, .cypress/cypress/integration/duplicates.js, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/oxfordshire.t
This is needed for the front-end role filtering to work.
=> Always fetch staff role info in pre-made CSVs.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste_bromley_bulky.t, templates/email/bromley/waste/bulky-confirm-cancellation.txt
[skip changelog] Stops a refund email being sent when a user cancels a booking that hasn't actually been paid for.
=> [Bromley] [Waste] No refunds for unpaid bulky bookings.

t/app/controller/waste_sutton_r.t, templates/web/sutton/waste/_more_services_sidebar.html, templates/web/sutton/waste/services.html
Request for Sutton only change to remove the link for ordering a new bin from each bin and have reworded link in the sidebar
https://mysocietysupport.freshdesk.com/a/tickets/3540
=> [Sutton] Remove link to order new bins from each bin

templates/web/brent/errors/generic.html
Very occasionally the user will run into an "invalid id_token" error when logging in via Brent Azure B2C OIDC, either because the redirects from B2C aren't working correctly, or the user's browser doesn't have a cookie set, or their session doesn't have the relevant oauth values stored. The exact cause is currently unknown and hard to pin down due to the transient nature of the bug.
Because the login invariably works the next time the user tries, this workaround just presents the OIDC login button again (labelled as a 'continue' button...) and will thus allow them to login successfully. In theory.
(Brent have tested this on the staging site and it seems to solve the problem for them.)
For FD-3395.
=> [Brent] Workaround OIDC login not working on first attempt

perllib/FixMyStreet/Cobrand/Thamesmead.pm
Code not being executed due to a bug and demonstrates not required
Noted from here: https://github.com/mysociety/fixmystreet/pull/4704/files#r1398946778
=> [Thamesmead] Remove unecessary code block

CHANGELOG.md, perllib/FixMyStreet/Script/SendDaemon.pm, perllib/Open311/PostServiceRequestUpdates.pm, t/script/send-daemon.t
Currently the update daemon query looks for 1) unprocessed, 2) confirmed, updates on reports that 3) have been sent to 4) bodies-with-Open311+send_comments-on. This query is quite slow, due to e.g. the number of updates (1+2) it's considering each time that are never going to be processed because they're not on relevant bodies.
This PR changes the query to fetch all unprocessed confirmed updates, regardless of sent state or body. If the body isn't an Open311+send_comments one, it now marks as processed and moves on. If it's not been sent and it's a non-open state, it marks as processed (only open state reports are sent) and moves on. If it's not been sent, it skips processing this one (is an update on a report still awaiting being sent to a backend which needs to happen first). Otherwise …
=> Mark non-Open311 updates as processed by daemon.

CHANGELOG.md, bin/update-schema, db/downgrade_0087---0086.sql, db/schema.sql, db/schema_0087-add-wasteworks-name-to-manifest-theme.sql, perllib/FixMyStreet/App/Controller/Offline.pm, perllib/FixMyStreet/App/Form/ManifestTheme.pm, perllib/FixMyStreet/DB/Result/ManifestTheme.pm, t/app/controller/admin/manifesttheme.t, t/app/controller/offline.t, templates/web/base/admin/manifesttheme/form.html, templates/web/base/admin/manifesttheme/index.html
This adds `wasteworks_name` and `wasteworks_short_name` fields to the manifest theme admin area, then uses those values when the PWA is installed for a WasteWorks site.
Fixes https://github.com/mysociety/societyworks/issues/3864
https://github.com/mysociety/fixmystreet/assets/22996/93f2cf0f-2ef8-4f6a-967f-3c8e98e9121d
=> Make WasteWorks PWA name configurable in the admin

bin/csv-export, perllib/FixMyStreet/App/Controller/Dashboard.pm, perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Reporting.pm, t/app/controller/admin/report_edit.t, t/app/controller/dashboard.t, templates/web/base/dashboard/index.html, templates/web/base/report/new/_category_select.html
Add a parent categories column to show if a category is a subcategory.
Arbitrary decision to choose the first parent category from the groups method of a contact.
https://github.com/mysociety/societyworks/issues/1458
=> [FMS] Add parent categories to dashboard categories view

web/cobrands/fixmystreet-uk-councils/assets.js
As locking the page from progressing is done using the standard no asset process, update the no_asset_message attribute to contain the same informative messaging as at the continue button.
Also solves issues of informative messaging not appearing on the subcategory screen if you get to subcategory and then choose a parish light which would mean there was no explanation on the page as to why you were blocked from going forward.
Calling "fixmystreet.assets.shropshire.streetlight_asset_message" for the text did not always update so repeated the logic of creating the message. 
https://github.com/mysociety/societyworks/issues/3996
https://github.com/mysociety/societyworks/issues/4014
=> [Shropshire] Add relevant messaging to the no_asset_message

CHANGELOG.md, perllib/FixMyStreet/App/Controller/My.pm, perllib/FixMyStreet/DB/Result/User.pm, perllib/FixMyStreet/Script/Questionnaires.pm, t/app/controller/my.t, t/app/controller/questionnaire.t, templates/web/base/admin/reports/_edit_main.html, templates/web/base/my/my.html, templates/web/fixmystreet-uk-councils/about/privacy.html, templates/web/fixmystreet.com/about/privacy.html
Closes https://github.com/mysociety/fixmystreet/issues/1265.
=> [FMS] Allow users to opt out of questionnaires

bin/fetch, perllib/Open311/UpdatesBase.pm, t/app/model/problem.t
Strictly speaking this code is cobrand-agnostic; the Northumberland-specific code is handled in open311-adapter.
For https://github.com/mysociety/societyworks/issues/3978.
=> [Northumberland] Assign user to report based on updates from Alloy

web/cobrands/cyclinguk/layout.scss
This PR only affects map page
- Hides the Cycle SOS(Second logo) when screens are below 1350px
- Reduced size of Fill that Hole logo when screens are below 1350px.
This minimises the overlap  between elements when Admin is enabled.
=> [Cyclinguk] Map page navigation bar

perllib/FixMyStreet/Roles/Open311Alloy.pm, perllib/Open311.pm, t/open311.t
If an image is on a comment which was made on a private report Open311 can not download the image as it will not be visible.
In this case, for Alloy, send the photos directly to open311
Open311 end still to do
https://github.com/mysociety/societyworks/issues/3709
=> [FMS][Open311] Send images when comment on private report

perllib/FixMyStreet/Cobrand/Brent.pm
Reduce time for reports to be shown on map from default 6 months down to 3 months
https://mysocietysupport.freshdesk.com/a/tickets/3554
=> [Brent] Reports should only show on map for 3 months

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
https://github.com/mysociety/societyworks/issues/4054
Make the 'in progress' state available when editing a response template for Oxfordshire, to allow setting up an auto-response for 'Job raised' alloy updates.
The 'in progress' state was initially dropped to simplify the states list: https://github.com/mysociety/fixmystreetforcouncils/issues/129. 
This approach also makes the state available in:
* Dashboard filtering.
* Reports filtering.
* Staff report state editing.
* Updating a report.
Which seems like a good idea with the state now in use for reports via Alloy.
=> [Oxfordshire] Include 'in progress' in available states.

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
We check ScheduleDescription before making the link to the ggw calendar.
In the winter the format of this changes to give a more accurate representation of the collection for customer view, but looks like the rest of the details remain the same and so the logic still works for picking the calendar
https://mysocietysupport.freshdesk.com/a/tickets/3692
=> [Brent] Green Garden Waste calendar to show in winter

CHANGELOG.md, bin/fixmystreet.com/waste-echo-reservation-update, perllib/FixMyStreet/App/Model/PhotoSet.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_bromley_bulky.t
Hopefully resolving two reasons we get stuck/problem reports:
1. Some backends have a maximum filesize for images. This has only ever been hit by PNGs people occasionally upload. Rather than limit this to those backends or PNGs, easier to convert all uploaded images to JPEGs.
2. If a report to Echo fails due to expired slots for some reason (we do check at report creation but if there's another issue sending (e.g. issue 1 above) this could happen), try and fetch new ones immediately for next retry rather than await manual interaction.
=> [Echo] Try and fetch new expired slots on sending; Convert all images to JPEGs

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_garden.t
Change Brent's ggw renewal from 28 days to 90 days so users can renew from the beginning of the year.
https://mysocietysupport.freshdesk.com/a/tickets/3693
=> [Brent] Increase Green Garden Waste renewal window

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Around.pm, perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/DB/ResultSet/Nearby.pm, perllib/FixMyStreet/DB/ResultSet/Problem.pm, t/app/model/problem.t, t/cobrand/restriction.t
Closes https://github.com/mysociety/societyworks/issues/3965.
Cobrands may now have a report_age() that is a hashref of upper-level states (open, closed, fixed) mapped to time intervals.
If a state is not specified, it will default to 6 months (as specified in FixMyStreet/Cobrand/Default.pm).
=> Support different /around map display times for open/closed/fixed reports

perllib/FixMyStreet/App/Controller/Admin/Reports.pm, perllib/FixMyStreet/Cobrand/CyclingUK.pm, t/cobrand/cyclinguk.t
For changing existing entries:
```
my $problems = FixMyStreet::DB->resultset("Problem")->search({ cobrand => 'cyclinguk' });
while (my $p = $problems->next) {
my @keys = ('CyclingUK_injury_suffered', 'CyclingUK_property_damage', 'CyclingUK_transport_mode', 'CyclingUK_transport_other', 'CyclingUK_marketing_opt_in');
my %keys = map { $_ => 1 } @keys;
my @fields;
foreach (@{$report->get_extra_fields}) {
if ($keys{$_->{name}}) {
$report->set_extra_metadata($_->{name} => $_->{value});
} else {
push @fields, $_;
}
}
$report->set_extra_fields(@fields);
$report->update;
}
```
=> [Cycling UK] Store extra data in metadata, not fields.

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, t/app/controller/waste_kands_bulky.t
The report might be immediately sent at this point (eg if bulky_send_before_payment is set), so needs to be set correctly.
=> [Waste] Record staff PAYE payment immediately.

perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/tfl.t
TfL use the whensent field in their reporting and so truncate it to not include nanoseconds
https://mysocietysupport.freshdesk.com/a/tickets/3722
=> [TfL] Truncate whensent field in CSVExport

cpanfile, cpanfile.snapshot, perllib/FixMyStreet/App/Controller/Contact/Enquiry.pm, perllib/FixMyStreet/App/Controller/Form.pm, perllib/FixMyStreet/App/Controller/Photo.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Claims.pm, perllib/FixMyStreet/App/Form/ManifestTheme.pm, perllib/FixMyStreet/App/Form/Wizard.pm, perllib/FixMyStreet/App/Model/PhotoSet.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Geocode.pm, perllib/FixMyStreet/Geocode/Zurich.pm, perllib/FixMyStreet/PhotoStorage/FileSystem.pm, perllib/FixMyStreet/Reporting.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/FixMyStreet/Roles/ParallelAPI.pm, perllib/FixMyStreet/TestMech.pm, t/app/controller/waste.t, t/app/controller/waste_brent_garden.t, t/app/controller/waste_kingston.t, t/app/controller/waste_peterborough_bulky.t, templates/web/base/about/_cookies.html, templates/web/base/about/privacy.html, templates/web/fixmystreet-uk-councils/about/privacy.html, templates/web/fixmystreet.com/about/privacy.html, templates/web/highwaysengland/about/privacy.html
Currently the code stores a number of waste things in the session for caching/performance reasons. We already store most of these on disk, so instead of deleting those, use them as the cache instead. Also start storing Peterborough postcode lookup on disk to match, and move the form unique ID to its own cookie rather than create sessions purely for them as well.
=> Don't cache waste things in session

perllib/FixMyStreet/Cobrand/TfL.pm, t/Mock/OpenIDConnect.pm
Force consistency in log-in by keeping password to one case.
=> [TfL] Azure single sign-on force email lowercase

perllib/FixMyStreet/Cobrand/TfL.pm, t/cobrand/tfl.t
TfL Staff will be logging in by OIDC only so shouldn't be forced to update their FMS password
https://github.com/mysociety/societyworks/issues/4105
=> [TfL] Users with TfL email not to be prompted to change password

perllib/FixMyStreet/Cobrand/Gloucestershire.pm, perllib/FixMyStreet/DB/ResultSet/Problem.pm, t/app/model/problem.t
Done as part of https://github.com/mysociety/societyworks/issues/4029.
Following on from [Support different /around map display times for open/closed/fixed reports](https://github.com/mysociety/fixmystreet/pull/4790), Gloucestershire require custom report_age settings for jobs versus enquiries (standard reports). This entails fun with nested hashrefs and even more nested SQL::Abstract queries :-)
=> [Glos] Handle custom report_age for Confirm jobs

perllib/Open311/GetServiceRequests.pm
Part of https://github.com/mysociety/societyworks/issues/4029.
If e.g. backfilling jobs into our system by calling the fetch
script with explicit start and end offsets, we do not want a
bunch of jobs to fail just because the *updated* date is outside
that range; the created date is what matters.
=> Fetching Confirm jobs: bypass date check

templates/web/sutton/waste/_more_services_sidebar.html
=> [Sutton] Remove ‘Request a larger/smaller refuse container’ from sidebar for staff

perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/index.html
Change postcode finder code so can receive a single hash rather than an array of hashes if only one result.
Remove bullet points from front page that don't apply to Bexley.
Add testing file and testing for the above.
=> [Bexley][Ww] Adds tests and minor changes for postcode finder

.github/workflows/coverage.yml, .github/workflows/cypress.yml
Code coverage should drop in this PR because I hope it's fixing the fact the JS code coverage hasn't been working for a while.
=> [GitHub] Use Codecov action in Cypress tests.

templates/web/northamptonshire/about/faq-en-gb.html
This is an interim measure until the split happens.
For FD-3779
=> [Northamptonshire] Update phone numbers on FAQ page

web/cobrands/bathnes/_colours.scss, web/cobrands/brent/_variables.scss, web/cobrands/bristol/_colours.scss, web/cobrands/bromley/_colours.scss, web/cobrands/buckinghamshire/_colours.scss, web/cobrands/fixmystreet.com/base.scss, web/cobrands/gloucestershire/_variables.scss, web/cobrands/greenwich/_colours.scss, web/cobrands/greenwich/base.scss, web/cobrands/highwaysengland/_colours.scss, web/cobrands/highwaysengland/base.scss, web/cobrands/hounslow/_colours.scss, web/cobrands/hounslow/base.scss, web/cobrands/merton/_colours.scss, web/cobrands/northamptonshire/_colours.scss, web/cobrands/northamptonshire/base.scss, web/cobrands/northumberland/_variables.scss, web/cobrands/oxfordshire/_colours.scss, web/cobrands/peterborough/_colours.scss, web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss, web/cobrands/southwark/_variables.scss, web/cobrands/southwark/layout.scss, web/cobrands/thamesmead/_colours.scss, web/cobrands/zurich/_colours.scss
Fixes: https://github.com/mysociety/societyworks/issues/4006
This variables will allow to avoid custom override for some cobrands for the label and .form-hint colors. In this commit the `$form-hint` variable will depend by default of the `$postcodeform-color`, usually they both share the same background colour, so it seemed like a good move in order to have both variables passing a contrast test, of course `$postcodeform-color` will need to satisfy the criteria otherwise both label and .form-hint will fail. It's imporant to note that $form-hint-color and `$form-hint-color-desktop` are being transparentize by 20%, therefore if `$postcodeform-color` and `$postcodeform-color-desktop` are passing the contrast test, by a small margin, then the label will most likely fail the test. …
=> Added variables to control #postcodeForm color

CHANGELOG.md, cpanfile, cpanfile.snapshot
Upgraded to perl 5.38, got a warning in the tests, upgraded that, and thought I'd also try and tidy up the snapshot a little bit.
=> Perl 5.38 upgrade tweaks

perllib/FixMyStreet/App/Controller/Auth.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Report/Update.pm, perllib/FixMyStreet/Cobrand/TfL.pm, t/Mock/OpenIDConnect.pm, t/app/controller/admin/templates.t, t/app/controller/auth_social.t, t/cobrand/tfl.t
TfL has requested staff can only log in via single sign on.
Create a call hook and add the call to TfL to
disallow logging in on an email address not supplied for single sign on.
https://github.com/mysociety/societyworks/issues/4100
=> [TfL] Remove FMS log in options for TfL

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t
The categories currently being sent to Abavus, they also want to go by email. This adds a number of categories to the email sending (plus the future ones, commented out). ~~The configuration would be updated to have e.g.~~
```
district_default: default@district
dead_animal: rubbish@district
flytipping_off_road: flytipping@district
car_park_flytipping: flytipping@district [plus other]
```
Edit after fixup - config would now be more like this:
```
'Dead animal (off the road)': [ 'rubbish@district' ]
'Flytipping (off-road)': [ 'flytipping@district' ]
```
Fixes https://github.com/mysociety/societyworks/issues/4123
=> [Buckinghamshire] Send Abavus categories also by email.

web/cobrands/highwaysengland/base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4103
I added a preview of desktop as well, because I changed the nesting for `#front-main-container`, otherwise the new rules get overridden by the default behaviour of FMS, this could have affected some rules in `layout.scss`, but it wasn't the case.
https://github.com/mysociety/fixmystreet/assets/13790153/c74ad177-4a38-480c-a614-0d03ef6b4ef0
=> [Highways] Added fix to prevent overflowing in homepage

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
GL-660 'Glass 660 ltr bin' was missing an image; have added one according to https://3.basecamp.com/4020879/buckets/35109031/todos/6816011725#__recording_7058530525.
Closes https://github.com/mysociety/societyworks/issues/4067 .
=> [Bexley] [WW] Add image for Glass 660

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
Order Bexley waste services by earliest upcoming collection (i.e. next collection date).
Closes https://github.com/mysociety/societyworks/issues/4096.
=> Bexley WW: Order waste services by earliest upcoming collection

web/cobrands/fixmystreet/map.js
On first page load the green pin would be draggable out from under the crosshairs, but it shouldn’t have been. The change stops that from happening.
For https://github.com/mysociety/societyworks/issues/3638 (specifically [the bug described in this comment](https://github.com/mysociety/societyworks/issues/3638#issuecomment-1632197164))
=> Prevent ‘new report’ pin being dragged on mobile

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/app/controller/waste_peterborough_bulky.t, t/cobrand/peterborough.t
To stop waste reports being stuck if the site code lookup isn't operational.
Refers to https://mysocietysupport.freshdesk.com/a/tickets/3859
=> [Peterborough] Skip site code lookup for waste.

t/cobrand/brent.t, templates/web/base/waste/bin_days_sidebar.html
Configuration can either still be a single link, or a list of href/text objects (as in test example).
Fixes https://github.com/mysociety/societyworks/issues/4134
=> [Brent] Enable multiple waste calendar links.

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Stats.pm, perllib/FixMyStreet/App/Controller/Dashboard.pm, t/app/controller/dashboard.t, templates/web/base/dashboard/index.html, templates/web/base/report/new/_category_select.html
As the templates auto-escape & to &amp; this will not match when used as a key lookup for a hash. We can use mark_safe when fetching a variable directly, but cannot combine with another string without the escaping kicking in again, so need to construct the string in the code first. Fixes FD-3905.
=> Fix dashboard selected for group/category with &.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Renew.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/cobrand/bromley_waste.t, templates/web/base/waste/garden/_bin_quantities.html, templates/web/base/waste/garden/renew.html, templates/web/base/waste/garden/sacks/renew.html, templates/web/kingston/waste/garden/_bin_quantities.html
Adds functionality to charge renewals based on the price for subscriptions at or beyond the renewal date.
Adds functionality to check for the price of additional bins based on the price of bins by date to allow for adding changes to the configuration in advance which will take effect on the day the date set.
Adds tests.
https://github.com/mysociety/societyworks/issues/4135
=> [Bromley] Waste different renewal cost

perllib/FixMyStreet/App/Controller/Dashboard.pm, t/app/controller/dashboard.t, templates/web/base/dashboard/index.html
Dashboard should collect categories under groups if they are in a group.
Currently, as we aren't distinguishing between which group a category is in, filters out categories in multiple groups into a multiple category.
Tests added and confirmed can go ahead before https://github.com/mysociety/societyworks/issues/4039 is implemented
https://github.com/mysociety/societyworks/issues/1458
=> [FMS] Add grouping to dashboard output

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days_sidebar.html
If the service is the waste bin use that to work out whether the household is on rotation week one or rotation week two for PDF calendars and present the correct link.
Also assume that if a calendar_link or ggw_calendar_link is stashed then a PDF download link should be shown.
https://github.com/mysociety/societyworks/issues/4099
=> 4099 bexley add bin calendar links

perllib/FixMyStreet/App/Controller/Auth.pm, perllib/FixMyStreet/App/Controller/Auth/Social.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Report/Update.pm, perllib/FixMyStreet/Cobrand/TfL.pm, t/Mock/OpenIDConnect.pm, t/app/controller/admin/templates.t, t/app/controller/auth_social.t, t/cobrand/tfl.t
Staff users sign on by oidc and be given their role from the role designated in the oidc payload
As it's staff users, make them from the body so a new user is automatically set to the body. 
Although it's unlikely multiple roles are sent, the roles sent is an array so makes that possible.
Remove current roles as only roles to be used are the ones from the single sign on 
https://github.com/mysociety/societyworks/issues/4046
https://github.com/mysociety/societyworks/issues/4047
=> [TfL] Single sign on for staff

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t, templates/email/bexley/site-name.txt, templates/web/bexley/waste/_announcement.html, templates/web/bexley/waste/_service_missed.html, templates/web/bexley/waste/services.html, templates/web/bexley/waste/services_extra.html
Adds the necessary checks, templates and hooks to allow reporting missed collections to Whitespace.
Handles the gate checks that need to be done before the report can be submitted:
- Check for existing open reports
- Check that the collection happened in the past 3 working days
- Check the in-cab logs for red tags and service updates
I've also added a superuser-only section at the bottom of the services screen to allow superusers to view the "raw" in-cab logs (red tags and service exceptions), as I think that might be useful in the future.
Closes https://github.com/mysociety/societyworks/issues/4094.
=> [Bexley][WW] Allow reporting missed collections

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm, t/cobrand/centralbedfordshire.t
=> [Central Beds] Include housing fly-tipping types in CSV.

perllib/FixMyStreet/Cobrand/Camden.pm
This prevents an issue where we're unable to send an update to Symology as it's closed.
[skip changelog] For FD-3926
=> [Camden] Only try sending updates two times.

perllib/FixMyStreet/Reporting.pm, t/cobrand/tfl.t
If the CSV export was acting on a pre-made CSV, and a category with brackets was explicitly specified in the query, it would not match. [skip changelog] For FD-3976.
=> Fix CSV export with category with brackets.

t/app/controller/auth_social.t, templates/web/tfl/errors/generic.html
Add continue button to continue OIDC login when it stalls.
Give all 500 errors a custom header to override default error message.
Conversation from: https://mysociety.slack.com/archives/C01TK8P1K8T/p1710262493550249?thread_ts=1710258039.797529&cid=C01TK8P1K8T
=> [TfL] Azure OIDC error handling

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t
Since newer GetCollectionByUprnAndDatePlus method is not currently supported on Bexley's live system.
Closes https://github.com/mysociety/societyworks/issues/4156.
=> [Bexley][WW] Refactor iCal code to use GetCollectionByUprnAndDate

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
Whitespace returns a standard bin service along with the assisted collection, where one exists.
If there is a current assisted collection for a service, remove the standard service so duplicates aren't presented.
https://github.com/mysociety/societyworks/issues/4182
=> [Bexley][WW] Remove duplicate bin services when assissted collection

web/cobrands/buckinghamshire/_colours.scss, web/cobrands/buckinghamshire/base.scss
Requested by client: https://mysocietysupport.freshdesk.com/a/tickets/3973
Client requested to change the `background-colour `of the `.site-message` from orange to light blue.
Preview here:
https://buckinghamshire.staging.fixmystreet.com/
=> [Bucks] Change .site-message background-colour

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/bexley/waste/_service_missed.html
Adds some extra fields that are used when creating missed collection reports in Whitespace.
See also the related Open311 adapter changes: https://github.com/mysociety/open311-adapter/pull/331
Part of https://github.com/mysociety/societyworks/issues/4051
Also related to https://github.com/mysociety/societyworks/issues/4098
=> [Bexley][Whitespace] Add extra fields for missed reports

templates/web/base/maps/openlayers.html, web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4211
This has been added after header elements and before any focusable map elements, that way the user doesn't need to go through the map links and compass to be able to go to skip the map.
IMPORTANT: https://github.com/mysociety/fixmystreet/pull/4879 should be merged so the styling of the button is contrast accessible.
=> Added skip map button

templates/web/base/around/postcode_form.html, templates/web/base/waste/index.html
Fixes: https://github.com/mysociety/societyworks/issues/4207
As part of the TFL audit, this PR improves the markup for the homepage of FMS and WW, by adding the `main` element. This should improve how users using screenreader navigate this page.
=> Added main element to homepage FMS and WW

perllib/BexleyAddresses.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days.html, templates/web/bexley/waste/_rotation_schedule.html
Done as part of https://github.com/mysociety/societyworks/issues/4206 .
- Do not mark child address as 'communal' if it has its own services - for https://3.basecamp.com/4020879/buckets/35109031/todos/7182351792
- Use LLPG data for address on collection page - https://3.basecamp.com/4020879/buckets/35109031/todos/7182204348
- Handle biweekly collections - https://3.basecamp.com/4020879/buckets/35109031/todos/7182331622
- Display collection frequency - https://3.basecamp.com/4020879/buckets/35109031/todos/7182127728
- Display rotation schedule for property - https://3.basecamp.com/4020879/buckets/35109031/todos/7183494892
=> Bexley ww misc fixes

templates/web/base/maps/openlayers.html, web/cobrands/hackney/base.scss
Introduced by https://github.com/mysociety/fixmystreet/pull/4880
I don't think any other cobrands change .btn like this
Alternatively - can the position relative be removed from the .btn above, or some other simplification?
=> [Hackney] Fix display of skip map link.

web/cobrands/bexley/_colours.scss, web/cobrands/brent/_variables.scss, web/cobrands/brent/base.scss, web/cobrands/camden/_variables.scss, web/cobrands/camden/base.scss, web/cobrands/lincolnshire/_colours.scss, web/cobrands/lincolnshire/base.scss, web/cobrands/merton/_colours.scss, web/cobrands/merton/base.scss, web/cobrands/northnorthants/_variables.scss, web/cobrands/northnorthants/base.scss, web/cobrands/sass/_base.scss, web/cobrands/southwark/_variables.scss, web/cobrands/southwark/base.scss, web/cobrands/tfl/_colours.scss, web/cobrands/tfl/base.scss, web/cobrands/westnorthants/_variables.scss, web/cobrands/westnorthants/base.scss
Fixes part of:  https://github.com/mysociety/societyworks/issues/4268
Red color `(#FF0000)` wasn't passing contrast test against white text so now it's a bit darker(with this PR the contrast test is 5.45). I have also made it a variable `error_color`, that should help the styling process for cobrands reducing the need for overrides.
The second commit is a tidy up, so now instead of having the overrides for the cobrands that were using their own red, now use the variable instead.
=> Added error_color variable and decreased lightness of default error color.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/EmailRenewalReminders.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_brent_garden.t, t/cobrand/brent.t, templates/web/base/waste/garden/renew.html, templates/web/base/waste/garden/subscribe_details.html, templates/web/base/waste/summary.html
closes https://github.com/mysociety/societyworks/issues/4202
=> [Brent] [Waste] Add upcoming renewal email opt-in control for garden sub and renew.

perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_sutton_r.t
For https://mysocietysupport.freshdesk.com/a/tickets/4118
=> [SLWP] Use service unit ID when checking events.

templates/web/base/main_nav.html, web/js/front.js
Fixes: https://github.com/mysociety/societyworks/issues/4257
Let me know if you'd rather me to create a PR to put the "Current page" bit, considering it is not directly related with the issue.
=> Added role button to span.report-a-problem-btn and "Current page" indicator to navbar

templates/web/base/maps/_compass.html, web/cobrands/fixmystreet/fixmystreet.js, web/js/map-OpenLayers.js
Fixes: https://github.com/mysociety/societyworks/issues/4218
This PR improves UX for users using assistive devices.
=> Added role button to .dropzone and elements inside .fms_pan_zoom

templates/web/base/admin/bodies/contact-form.html, templates/web/base/admin/users/_form_details.html, templates/web/base/alert/_list.html, templates/web/base/alert/_updates.html, templates/web/base/auth/change_email.html, templates/web/base/contact/enquiry/index.html, templates/web/base/contact/form.html, templates/web/base/report/form/user_loggedout_by_email.html, templates/web/base/report/form/user_loggedout_email.html, templates/web/base/report/form/user_name.html, templates/web/base/report/new/form_user_loggedin.html, templates/web/base/report/new/report_import.html, templates/web/bromley/report/form/user_name.html, templates/web/cyclinguk/report/form/user_name.html, templates/web/fixmystreet-uk-councils/report/form/user_name.html, templates/web/hart/footer_extra.html, templates/web/zurich/admin/bodies/contact-form.html, templates/web/zurich/report/new/fill_in_details_form.html
Fixes: https://github.com/mysociety/societyworks/issues/4208
NOTES:
CyclingUK and Bromley have first and last names in their forms, so they were tackled in this commit:
[Added autocomplete attribute to first and last name](https://github.com/mysociety/fixmystreet/commit/2665a014b61c03b152421139b9db0dcc34c31255)
=> Added autocomplete attribute to inputs

templates/web/westminster/footer_extra_js.html, web/cobrands/westminster/base.scss, web/cobrands/westminster/vendor/banner.js
For https://mysocietysupport.freshdesk.com/a/tickets/3058
=> [Westminster] Add cookie banner.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
As per https://3.basecamp.com/4020879/buckets/35109031/todos/7334096549, we don't want to display clinical waste collections.
Supersedes / closes https://github.com/mysociety/societyworks/issues/4235 .
=> [Bexley][WW] Remove Clinical Waste

templates/email/bexley/waste/_council_reference.html, templates/email/bexley/waste/_sidebar_content.html, templates/email/default/alert-update.html, templates/email/default/waste/other-reported.html, templates/email/default/waste/other-reported.txt
Update the wording on the confirmation email for missed collection reports, as per this thread: https://3.basecamp.com/4020879/buckets/35109031/todos/7259735553.
Email sidebar changes also made for update alert email.
=> [Bexley WW] Email template for missed collections

perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, t/app/controller/waste_merton_bulky.t, templates/web/base/waste/bulky/_bin_days_list.html
Allows report missed collection on the day
https://github.com/mysociety/societyworks/issues/4270
=> [Merton][WW] Adds configurations for bulky waste

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, t/app/controller/waste_merton_bulky.t, t/integrations/adelante.t, templates/web/base/waste/bulky/_bin_days_list.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/location.html
Starts off by renaming the various payment Roles, moving those with no relevance to FixMyStreet under Integrations/Roles directly, and moving the cobrand-based payment roles under FixMyStreet/Roles/Cobrand/. Then adds a new payment integration provider (operates very similarly to the existing SCP one). Then adds the basic bulky waste code for Merton.
For https://github.com/mysociety/societyworks/issues/4270 [skip changelog]
=> [Merton] Initial bulky waste functionality

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/bexley/waste/_announcement.html
Shows a notice to users warning them of an upcoming bank holiday for a two weeks prior to and a week after bank holidays.
Can also be triggered manually by including `?show_bank_holiday_message=1` in the query string.
Part of https://github.com/mysociety/societyworks/issues/4206
[Basecamp todo item](https://3.basecamp.com/4020879/buckets/35109031/todos/7168045358)
=> [Bexley] [WasteWorks] Add bank holiday notice

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
=> [Brent] Add nsg mapping config.

perllib/FixMyStreet/App/Form/Waste/Request/Merton.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, t/app/controller/waste_merton.t, templates/web/base/waste/services.html
Staff can select any available domestic container when doing a request 
They are not restricted to ordering only one container (they can order 3).
They can leave an optional note when ordering a container.
https://github.com/mysociety/societyworks/issues/4273
=> [Merton][WW] Add staff features for requesting new containers

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
Turns out 'Hidden' formhandler fields take 'default', not 'value'.
=> [Bexley][WW] Make sure default value is passed for hidden container location field

CHANGELOG.md, perllib/FixMyStreet/Script/Alerts.pm, t/app/controller/alert_new.t
Except for waste categories.
closes https://github.com/mysociety/fixmystreet/issues/4901
=> Include status change line in update emails using auto response templates.

web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4213
This should improve the accessibility contrast of the `.skip-link` element against the navigation bar.
Part of TFL audit. This should improve the following criteria:
https://www.w3.org/WAI/WCAG21/Understanding/focus-visible
=> Added Dual box-shadow colour for .skiplink

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days.html
For https://3.basecamp.com/4020879/buckets/35109031/todos/7411178677.
Logs with a reason of 'N/A' were being ignored, but we need them to check whether a collection has already been made today for a given service.
=> [Bexley][WW] Fetch successful collections alongside other in-cab logs

perllib/FixMyStreet/Cobrand/Bromley.pm
If a waste pickup is delayed, set to in progress and don't allow reporting of missed collection
https://mysocietysupport.freshdesk.com/a/tickets/4185
=> [Bromley] Add Delayed check on state

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days.html
We are pretty certain that UPRN logs are always a subset of USRN logs, so I have simplified the code so we only fetch USRN logs.
=> [Bexley WW] Simplify in-cab logs code to use USRN logs only

perllib/FixMyStreet/App/Controller/Report/New.pm, t/cobrand/brent.t
contributed_by is now set if a user logs in during report making process.
Results in dashboard report now showing roles filter correctly when staff user logs in as part of report making process.
https://github.com/mysociety/societyworks/issues/4234
=> [FMS] Make sure contributed_by recorded if not logged in

templates/web/base/admin/bodies/body.html, templates/web/base/admin/bodies/category.html
Placed at top of category list, above add category form and in category edit form.
Could maybe restrict to showing in category edit form for ones that are already red route (something like `body.cobrand._tlrn_categories.grep(contact.category).size`) but thought it better to just include for all.
=> [TfL] Add admin heads for changing red route categories.

perllib/FixMyStreet/Cobrand/Northamptonshire.pm, perllib/FixMyStreet/Cobrand/Northumberland.pm
And remove the code that accidentally set this up on the Northamptonshire cobrand.
=> [Northumberland] Skip sending updates on reports fetched from Alloy.

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_bexley.t, templates/web/bexley/waste/_service_missed.html
Fixes https://github.com/mysociety/societyworks/issues/4342 .
Touches code shared between all cobrands, so presumably fixes the issue across all cobrands. (At the very least, doesn't break existing behaviour - see screengrab below).
https://github.com/mysociety/fixmystreet/assets/11098355/2fc562a9-944f-44d9-b48b-99045c86a7e3
=> Prevent hidden missed collection selection if given service is no longer eligible

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
Splits out the services with a GL- prefix into a separate "Glass" prefix for red tags. Also adds a missing GL-240 container type.
For https://3.basecamp.com/4020879/buckets/35109031/todos/7465218614#__recording_7468587102
=> [Bexley] Add a "Glass" red tag prefix for GL- services

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/bexley/waste/services_extra.html
In-cab logs only have a RoundCode, but that can't be matched directly to a collection's RoundSchedule because both weekly and fortnightly collections share a RoundCode in the logs. So we need to do this extra check to ensure we were actually expecting a collection in the past three days.
For https://3.basecamp.com/4020879/buckets/35109031/todos/7468948862
=> [Bexley] Collected today check should check scheduled collections

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/enquiry.html, templates/web/base/waste/summary_enquiry.html, templates/web/bexley/waste/_bin_days_no_collections.html, templates/web/bexley/waste/enquiry-no-collections.html
Makes some changes to the enquiry form to allow properties with no collections to report a missed collection via email to one of two categories.
- Removes the check for a valid service in the `enquiry` sub in the Waste controller, think this is ok, as nothing breaks if there isn't a service, it just isn't recorded if it's missing.
- Adds support for checkboxes in extra data on enquiry categories
- Changes to support enquiry checkboxes
- Changes to support service no longer being required
For https://3.basecamp.com/4020879/buckets/35109031/todos/7182401179
=> [Bexley] Add form for properties with no collections

templates/web/base/alert/_index_text.html, templates/web/base/alert/index.html, templates/web/base/around/postcode_form.html, templates/web/fixmystreet.com/around/location_error.html, web/cobrands/sass/_base.scss, web/cobrands/sass/_search-help.scss
Fixes: https://github.com/mysociety/societyworks/issues/4217
In Firefox, the error message remains in the same place when the page is scrolled, so you lose the visual relationship between it and the form field that is in error. Use a text error message, as has been done on other pages.
For this one I added an extra commit:
https://github.com/mysociety/fixmystreet/pull/5000/commits/6c34076c32de98c8018808aaddba2508d17ed9c6
making the  search-help component having the same colour as an error, It's a bit confusing that both of them are related, but they have different colours. Also some cobrands are already using the same colour for errors and "search-help" so I thought standardised wouldn't be a bad idea.
If the input is left empty, no error message is provided.
This has two commits:
[One …
=> Form error identification improvements

web/cobrands/tfl/_colours.scss
Fixes: https://github.com/mysociety/societyworks/issues/4188
This allows that the outline has enough contrast with the background color.
=> [TFL] Added 2px outline off-set for focus state for TFL button

.cypress/cypress/integration/simple_spec.js, templates/web/base/alert/list.html, templates/web/base/report/update/form_user.html, templates/web/bromley/report/update/form_user.html, web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4212
Both of these fixes should improve how users using assistive devices travel across inputs by modifying which focus element we are focusing, making it easier to rectify errors or previous steps.
[Added fix to email input focus behaviour when there is an error](https://github.com/mysociety/fixmystreet/commit/23a43e2081971a375207bc490e7b7a680d4512bb) 
First commit fixes:
SW ref 30: Local RSS feeds and email alerts - part 2
An error message is provided in text, but it is not programmatically associated with the email address input element.
[Added fix for focus behaviour in pages with a .form-section-preview](https://github.com/mysociety/fixmystreet/commit/28c761324c203c0506657cef8be38c5c89b9041d)
SW ref 29: Reported issue - provide …
=> Improvements to focus order 

perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm, perllib/FixMyStreet/Test.pm, perllib/FixMyStreet/TestMech.pm, script/server
This means you can use `::Dwarn $var` in both code and tests without needing to add any other import or code.
=> Load Devel::Dwarn in dev server and tests.

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/NottinghamshirePolice.pm, perllib/Utils.pm, t/Mock/MapIt.pm, t/cobrand/nottinghamshirepolice.t
Checks report for email address and returns error requesting removal if found in title or detail.
Fixes https://github.com/mysociety/societyworks/issues/4338
Also moves Highways England code regex match into Utils for general use.
=> [Notts Police] Prevent reports being made if they contain email

templates/web/base/around/_on_map_empty.html, templates/web/base/around/tabbed_lists.html
Fixes: https://github.com/mysociety/societyworks/issues/4219
This commit helps screen reader to notify the user once the number of results in the map have been updated.
The reason to not add `aria-live="polite"` on the `js-reports-list` that contains messages like 'No reports to show on map, here are some nearby:' is because after testing I realised it also starts reading all the reports found, one by one. So this commit cover cases where:
- There are reports in the map
- No reports in the map
However it doesn't cover the scenario where: "No reports to show on map, here are some nearby:", because that one is nested inside `.js-reports-list` and the text is not dynamic, is basically hidden if the condition is not met, therefore `aria-live` doesn't have an effect. As an idea we could add a …
=> Added aria-live search results in around page

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Queue/Item/Report.pm, t/app/controller/report_new_update.t
Don't use the Open311 update generating code, so the update is created
unconfirmed rather than confirmed (with timestamp) then changed, and
create the alert first, in the unlikely case the comment somehow gets
confirmed in the time between the alert and the comment. FD-4237
=> Create report alert before first auto-update.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, t/app/controller/waste.t, t/app/model/questionnaire.t, t/cobrand/bexley.t
Bexley have requested that we turn off questionnaires for FMS. (See [this doc](https://docs.google.com/document/d/13xu4LLEDuZKt216aIloTNaSZZeFOvUu5IrEM9eHrICo/edit#heading=h.93j3fbds4ycb) point 5 under general notes.)
See also commit 837d357448d7da0fa5ce56f1dff0ffaa38e7b453 in mysociety-servers.
Also stops questionnaires for being sent for all waste report, as they don't make sense in the context of WasteWorks.
Fixes https://github.com/mysociety/societyworks/issues/4388
=> [Bexley] Disable questionnaires

bin/expire-sessions, perllib/Catalyst/Plugin/FixMyStreet/Session/WasteCache.pm, perllib/FixMyStreet/App.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, perllib/FixMyStreet/DB/Result/Session.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, perllib/Integrations/Roles/ParallelAPI.pm, t/cobrand/peterborough/bulky-goods/unit.t
We're not expiring property lookups in the session cache (they get replaced if the same property is looked up again, but otherwise will just stick around) which was causing issues as people built up thousands of cached unneeded properties in the session. Factor out the cache stuff to a plugin that can store the time of setting, then add to the expire script something to remove things older than a day.
=> [Waste] Add ability to expire session cache entries.

web/cobrands/merton/_colours.scss, web/cobrands/merton/base.scss, web/cobrands/merton/layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/4381
For reviewing and in case of feedback I have added a commit for each point, but once the PR is ready I'll rebase and squash everything into one commit.
Here is the list of changes:
```
/* B1 - Top banner and logo sizing */
/* Mobile layout:   */
.merton-header {
border-top-width: 3px;
padding: 0;
}
.merton-header__logo {
width: 150px;
background-position-y: 11px;
}
/* Top banner and logo sizing – desktop layout: */
@media screen and (min-width: 48em) {
.merton-header {
border-top-width: 5px;
padding: 11px 0;
}
.merton-header__logo {
width: 186px;
background-position-y: 6px;
}
/* Verticaly position other elements below the banner */
body.mappage #site-header, body.mappage .nav-wrapper {
top: 87px;
}
body.mappage #map_box, …
```
=> [Merton] Styling amendments 

docs/_layouts/wasteworks.html
Adding in new sidebar navigation options and editing copy in others
=> Update WasteWorks manual sidebar.html

.cypress/cypress/integration/category_tests.js, web/cobrands/fixmystreet/fixmystreet.js
If there are no categories after filtering has taken place then prevent continuing with the report and add a message to tell the user to search again.
https://github.com/mysociety/societyworks/issues/4314
=> [FMS] Adds stop to reporting if all categories filtered out

CHANGELOG.md, perllib/FixMyStreet/Cobrand/Surrey.pm, perllib/FixMyStreet/DB/Result/Problem.pm, templates/email/surrey/_council_reference.html, templates/email/surrey/_council_reference.txt, templates/email/surrey/_council_reference_alert_update.html, templates/email/surrey/_council_reference_alert_update.txt, templates/web/base/report/new/category_extras_fields.html, templates/web/surrey/admin/bodies/_category_field.html
Fixes https://github.com/mysociety/societyworks/issues/4370 - don't think I've missed anything, but would be good to check. We should probably have a simpler generic way to do a "use external_id over id" option.
Fixes https://github.com/mysociety/societyworks/issues/4409 - this seemed a very simple "fix" so not sure if this will have broken anything!
Fixes https://github.com/mysociety/societyworks/issues/4408 - have added the option, not sure I fully understood Dave's point here but hopefully this is enough for whatever he wanted (could also probably have a generic way of doing this as in use in a few places now)
Fixes https://github.com/mysociety/societyworks/issues/4391 - hopefully this is just the config from the new feature you added.
=> [Surrey] Various tweaks

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report/New.pm, t/app/controller/report_new_staff.t
We have had a few cases where staff forget they are not logged in, report on behalf of someone else when logged out, and have their own account name updated when clicking the confirmation link.
=> Staff cannot update name reporting when logged out

templates/web/base/around/postcode_form.html, templates/web/base/front/site-message.html, templates/web/base/index.html, templates/web/base/report/new/form_after_heading.html, templates/web/lincolnshire/around/intro.html, web/cobrands/lincolnshire/base.scss
Lincolnshire have asked for the site message on the homepage to be moved above the postcode form, and for it to have a red background with white text.
Fixes FD-4059
=> [Lincolnshire] Move and restyle site messages on home page

perllib/FixMyStreet/Cobrand/Lincolnshire.pm
We are getting results from Bing which show the same 3 locations when an address is not recognised.
OSM returns no addresses for the same not recognised addresses. 
https://mysocietysupport.freshdesk.com/a/tickets/4288
=> [Lincs] Switch to OSM for Geocoding

perllib/FixMyStreet/Cobrand/NottinghamshirePolice.pm, templates/email/nottinghamshirepolice/signature.txt, templates/web/nottinghamshirepolice/report/new/form_public_councils_text.html, web/cobrands/nottinghamshirepolice/js.js
And update the relevant templates to match.
I've overridden the whole `report/new/form_public_councils_text.html` template, which means the same message is now shown for reports in public and private categories.
Fixes https://github.com/mysociety/societyworks/issues/4405
=> [Notts Police] Change body name to Immediate Justice Team

templates/web/base/reports/index.html, web/cobrands/fixmystreet.com/images/healthcheck-bad.svg, web/cobrands/fixmystreet.com/images/healthcheck-good.svg, web/js/dashboard.js
Fixes: #3900 
With this PR we comply with WCAG Level Headlines AA (3:1)
Changes:
- Orange from `#F4A140` to `#D97B0C`
- Blue from `#4FADED` to `#269AE9`
- Green from `#62B356` to `#56A54A`
=> Updated Stats colours in Dashboard Panel

templates/web/base/reports/_problem-list.html
Fixes: https://github.com/mysociety/societyworks/issues/4239
This is a title we have added to improve accessibility and avoid the jumping from `h1` straight to `h3`
=> Added H2 title for list reports in 'All reports' page

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/_address_display.html, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/_rotation_schedule.html, templates/web/bexley/waste/_service_missed.html, web/cobrands/bexley/base.scss
Fixes the following Basecamp todos, which are all text changes or similar.
- [Review bin type labels on the 'select your missed bin' page](https://3.basecamp.com/4020879/buckets/35109031/todos/7465372000)
- [Rotation text](https://3.basecamp.com/4020879/buckets/35109031/todos/7349248069)
- [Change 'already reported' text](https://3.basecamp.com/4020879/buckets/35109031/todos/7514472576)
- [Include more links in the 'more services' section](https://3.basecamp.com/4020879/buckets/35109031/todos/7514438414)
- [Add Change address link](https://3.basecamp.com/4020879/buckets/35109031/todos/7512718726)
=> [Bexley] Various post go-live text changes

perllib/Integrations/Whitespace.pm
Fixes these errors that are appearing in the logs:
```
Caught exception in FixMyStreet::App::Controller::Waste->process_report_data "Not an ARRAY reference at /data/vhost/www.fixmystreet.com/fixmystreet-2024-07-10T10-44-33/perllib/FixMyStreet/Cobrand/Bexley/Waste.pm line 1015.", referer: /waste/10011843743/report
```
[Basecamp todo](https://3.basecamp.com/4020879/buckets/35109031/todos/7591740937)
=> [Bexley] Use force_arrayref on Whitespace site contracts

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste.pm
It is possible you might be sent a bad service/container parameter (perhaps it has expired). Ignore it if so to prevent it being kept until the final processing. FD-4334. [skip changelog]
@nephila-nacrea For info, I think this is a slightly better way of achieving your aim with https://github.com/mysociety/fixmystreet/pull/4986
=> [Waste] Only allow through valid first page fields.

templates/web/base/reports/_bulk-assign.html, web/cobrands/sass/_report_list.scss
Fixes: https://github.com/mysociety/societyworks/issues/4434
This PR gives the GOVUK layout to the `#bulk-assign-form`
=> Added fix for select element in bulk assign report section

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t, templates/web/base/report/new/after_photo.html, templates/web/buckinghamshire/footer_extra_js.html, templates/web/fixmystreet-uk-councils/footer_extra_js_base.html, templates/web/fixmystreet-uk-councils/report/new/after_photo.html, templates/web/fixmystreet.com/footer_extra_js.html, web/cobrands/fixmystreet-uk-councils/council_category_element_display_rules.js, web/cobrands/fixmystreet-uk-councils/council_category_hide_element_rules.js, web/cobrands/fixmystreet/fixmystreet.js
For https://github.com/mysociety/societyworks/issues/4366.
=> [Bucks] Changes for 'Littering From Vehicles' category

templates/web/bexley/main_nav_items.html
closes https://github.com/mysociety/societyworks/issues/4406
=> [Bexley] Add link to address lookup page to waste navbar.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
closes https://github.com/mysociety/societyworks/issues/4346
This also includes a small change that removes the word 'rotation' before 'schedule'.
=> [Bexley] Surface only one waste service if multiple share a name.

.github/ISSUE_TEMPLATE/Bug_report.md, README.md
The fixmystreet-mobile app has been replaced by the PWA app.
=> Remove fixmystreet-mobile references

web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4415
UI Improvement: Currently, FMS and cobrands use the system default. Depending on the font the cobrand and system use, this can feel quite disjointed.
=> Added $body-font variable to input, select and textarea elements

perllib/FixMyStreet/Cobrand/Surrey.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/Mock/MapIt.pm, t/cobrand/surrey.t
Adds a column, "Subscribers" which uses the problem alert method to populate the number for subscribers.
The original reporter is not automatically subscribed to their own report for Surrey so the figure is those that have subscribed after the report has been created.
Also adds initial test file
https://github.com/mysociety/societyworks/issues/4369
=> [Surrey] CSV export includes subscribers to the report

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
Currently only applies to Clear Sack(s) but could apply to others in future.
For https://3.basecamp.com/4020879/buckets/35109031/todos/7648636722.
=> [Bexley][WW] Preserve HTML in specific container description(s)

web/cobrands/fixmystreet/fixmystreet.js
"Everything" ideally would change to a checkbox (or even three-state to show when some selected), but this will be a workaround for the present.
Legend moves to option instead of checkboxes to improve history behaviour.
=> Allow click on Everything to unselect everything, and improve legend toggle

perllib/FixMyStreet/Cobrand/Surrey.pm, perllib/Open311/GetServiceRequests.pm
Stop receiving category/subcategory as no longer sent
https://3.basecamp.com/4020879/buckets/36546415/todos/7648793252#__recording_7674131654 https://mysociety.slack.com/archives/C06SKSH5KQT/p1722624461300599?thread_ts=1722616474.424329&cid=C06SKSH5KQT
=> [Surrey] Remove category and subcategory on received reports

perllib/FixMyStreet/Roles/EnforcePhotoSizeOpen311PreSend.pm
By the time the open311_pre_send hook is reached, the report has had Open311-only extra fields set on it and we are not in a transaction, so we don't want to update the database at this point. The open311_update_missing_data hook is run within a transaction, so is the best place to make any necessary database updates, before the report is sent.
Only concern I can think of is if the photo shrinking is very slow and it's stuck in a transaction for a while, but hopefully that isn't the case?
=> [Echo] Move photo shrinking to update hook.

perllib/FixMyStreet/DB/Result/Problem.pm, templates/email/surrey/_council_reference.html, templates/email/surrey/_council_reference.txt, templates/email/surrey/_council_reference_alert_update.html, templates/email/surrey/_council_reference_alert_update.txt, templates/web/base/report/_council_sent_info.html
Surrey don't want to show their backend ids to anybody so remove those from the email and site
https://3.basecamp.com/4020879/buckets/36546415/todos/7611442254#__recording_7688243427
=> [Surrey] Remove council id from site and emails

bin/merton/send-waste, perllib/FixMyStreet/App/Controller/Claims.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/Cobrand/Adelante.pm, perllib/FixMyStreet/Script/Merton/SendWaste.pm, t/app/controller/waste_merton_garden.t
Needed to move a few things into the model, but worked through them all in the end, I think [skip changelog]
Means you can call payment confirmation (for garden or bulky) outside the controller flow, should that be needed elsewhere in future.
=> [Merton] Add fallback check

web/cobrands/sass/_dashboard.scss, web/cobrands/sass/_govuk.scss, web/cobrands/sass/_report_list.scss
**Fixes:**
The multi-select has lost its maximum width at some point so e.g. if you’re on the dashboard for a council and pick a number of different wards, see how it gets bigger and bigger (or on a body admin page if you pick a number of areas to cover, etc)
**Preview**
This PR adds `max-width` to  the class `.govuk-select` 
https://github.com/user-attachments/assets/58239b8c-2fa9-4834-8e90-71f2bbf8c5b8
=> Added max-width to govuk-select class

templates/web/base/common_header_tags.html, web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/fixmystreet/header.js, web/cobrands/sass/_base.scss, web/cobrands/sass/_report_list.scss, web/js/map-OpenLayers.js
Fixes: https://github.com/mysociety/societyworks/issues/4209
Currently when users zooming over 175% in a screen that is 1280px by 720px, the mobile version is trigger in the around page. This behaviour doesn't allow them to see the list of reports made in the area. This fix prevent classes(map-fullscreen only-map map-reporting) to be added, resulting in a mobile view with a non-full page map with a scrollable page so users can see the list of reports.
https://github.com/user-attachments/assets/5a03ebaa-2cc2-45d7-be2d-aa5d446a17cb
`.alerts__nearby-activity__photos` is now horizontally scrollable, so when zooming users can see all the images.
https://github.com/user-attachments/assets/9171dbb0-9ed3-4a9c-a4e1-bff2e3862432
=> WCAG page reflow

web/cobrands/fixmystreet/fixmystreet.js
There are two open PRs in the dropzone repo which fix this (see [the original issue](https://github.com/mysociety/societyworks/issues/4493#issuecomment-2288259642) for details), but at the time of writing neither had been merged.
Could have forked dropzone and applied the fix to our fork, but seemed easier to just apply it in our custom init method for now.
Fixes https://github.com/mysociety/societyworks/issues/4493
=> Add aria-label to dropzone's hidden file input

templates/web/base/alert/_list.html
Fixes: https://github.com/mysociety/societyworks/issues/4489
Included `aria-label` that tells users which measurement unit they should use to specify the distance radius of their alert.
=> Added aria-label to distance radius in Get Updates component

templates/web/base/navigation/_report.html, web/cobrands/bexley/layout.scss, web/cobrands/borsetshire/layout.scss, web/cobrands/bromley/layout.scss, web/cobrands/cyclinguk/base.scss, web/cobrands/eastherts/layout.scss, web/cobrands/fixamingata/layout.scss, web/cobrands/gloucestershire/layout.scss, web/cobrands/hart/base.scss, web/cobrands/hart/layout.scss, web/cobrands/highwaysengland/layout.scss, web/cobrands/kingston/layout.scss, web/cobrands/northamptonshire/layout.scss, web/cobrands/nottinghamshirepolice/layout.scss, web/cobrands/peterborough/layout.scss, web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss, web/cobrands/shropshire/layout.scss, web/cobrands/sutton/layout.scss, web/cobrands/thamesmead/layout.scss, web/cobrands/westminster/layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/4490
Hiding this element, because users can't interact with it. It is also not very clear that is an active state to reflect that is the current page(homepage), but also the page where a user can start the process to report a problem.
The second commit is removing all the styling for `span.report-a-problem` from all cobrands.
=> Hide span.report-a-problem button

web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss
Minor bug, but currently on mobile the not found page has some overflow if the url is longer than the screen.
https://github.com/user-attachments/assets/d3be1c4e-c5fe-4b97-ad56-864636af3577
Added `word-break` attribute to `p` elements nested inside `.confirmation-header`
=> Added word-break attribute to confirmation-header paragraph

web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4481
Added outline and box-shadow. This change should make more obvious that the element `.alerts-rss-link` is being focused.
=> Improved focus state for img nested inside alerts-rss-link

web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4482
This includes the following buttons:
-Up, down, left, right
-Zoom in and Zoom out
-aerial
-re-centre
This PR tackles any cobrand where rules changing the colour of `a:focus` were generating a contrast issue, for example Chesire East and Surrey.
Important: When this PR is approved we should add it in `commercial-staging` and `Surrey-cobrand`
=> Improved focus state for map buttons

web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4487
This PR prevents the odd extra rectangles when focusing one of the `pan_zoom` buttons
https://github.com/user-attachments/assets/caf46fcd-75cb-4655-8752-9d18e8b23b1c
=> Added text-indent property to pan_zoom map buttons

perllib/FixMyStreet/Cobrand/Surrey.pm
Use exact service name as title without having 'problem' appended.
https://github.com/mysociety/societyworks/issues/4505
=> [Surrey] Add call hook to use service_name as title

templates/web/base/maps/openlayers.html
Fixes: https://github.com/mysociety/societyworks/issues/4488
Currently `.js-recentre-map` is the only control element in the map that can't be focused. By adding a `tabindex="0"` we allow keyboard users to be able to use that element.
Preview here:
https://github.com/user-attachments/assets/4efb1a2b-d266-4915-bf83-fcc6c77bf82a
=> Added tabindex to .js-recentre-map element

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Bodies.pm, t/app/controller/admin/bodies.t, t/app/controller/admin/reportextrafields.t, t/app/controller/admin/translations.t, t/cobrand/highwaysengland.t, t/cobrand/tfl.t, t/cobrand/zurich.t, templates/web/base/admin/bodies/add.html, templates/web/base/admin/bodies/body.html, templates/web/base/admin/bodies/category.html, templates/web/base/admin/bodies/contact-form.html, templates/web/base/admin/bodies/form.html, templates/web/base/admin/bodies/index.html, templates/web/zurich/admin/bodies/body.html, templates/web/zurich/admin/bodies/contact-form.html, templates/web/zurich/admin/bodies/form.html
One very old 'bug', in that we can now view those pages (and then separately deal with whatever is creating 1000s of log entries), and then I was fed up of being confused by two forms on one page.
=> [Admin] Move add body/category forms to own pages, limit history

CHANGELOG.md, t/app/controller/admin.t, t/app/controller/admin/stats.t, templates/web/base/about/_sidebar.html, templates/web/base/admin/header.html, templates/web/base/admin/navigation.html, templates/web/base/admin/reports/edit.html, templates/web/buckinghamshire/about/_sidebar.html, templates/web/cyclinguk/about/_sidebar.html, templates/web/fixamingata/about/council.html, templates/web/fixamingata/about/faq-sv.html, templates/web/fixamingata/about/privacy.html, templates/web/fixmystreet-uk-councils/about/_sidebar.html, templates/web/fixmystreet.com/about/_sidebar.html, templates/web/fixmystreet.com/about/posters.html, templates/web/gloucestershire/about/_sidebar.html, templates/web/highwaysengland/about/_sidebar.html, templates/web/oxfordshire/about/_sidebar.html, templates/web/rutland/about/_sidebar.html, templates/web/shropshire/about/_sidebar.html, templates/web/thamesmead/about/_sidebar.html, web/cobrands/sass/_page-with-sticky-content-bar.scss
Moves the navigation to a sidebar, and makes it prettier
=> Move admin nav to sidebar

perllib/FixMyStreet/App/Controller/Dashboard.pm, perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Reporting.pm, t/cobrand/tfl.t
If a request for a CSV export includes the current day, stop the pre-generated export at midnight and switch to a live export for the current day. [skip changelog]
Fixes https://github.com/mysociety/societyworks/issues/4170
=> Include same-day data in pre-generated CSV exports

templates/web/base/common_scripts.html, web/cobrands/fixmystreet/img_gallery_keyboard_view.js
Fixes: https://github.com/mysociety/societyworks/issues/4518
Currently the browser doesn't scroll into view on images that are partially visible, which is causing a bit of a confusing navigation. This fix makes automatically scroll to the focused image.
https://github.com/user-attachments/assets/e275984d-2724-4d72-b582-223f88826fdb
At the beginning I was adding this fix to `FixMyStreet.js` but then I noticed that `/alert` page doesn't use it, so I ended up creating a file exclusively for it. Let me know if you think there is a more appropriate place to put it. 
=> Improved image keyboard focus view on Alert Page

web/cobrands/eastherts/base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4524
There wasn't any top property, therefore the hamburger was seating at the bottom, clashing with searhbar
=> [eastherts] Added fix to vertical position of eh-header__nav-link

templates/email/bexley/_council_reference_alert_update.html, templates/email/bexley/_council_reference_alert_update.txt, templates/email/centralbedfordshire/_council_reference_alert_update.html, templates/email/centralbedfordshire/_council_reference_alert_update.txt, templates/email/cheshireeast/_council_reference_alert_update.html, templates/email/cheshireeast/_council_reference_alert_update.txt, templates/email/hounslow/_council_reference_alert_update.html, templates/email/hounslow/_council_reference_alert_update.txt, templates/email/isleofwight/_council_reference_alert_update.html, templates/email/isleofwight/_council_reference_alert_update.txt, templates/email/northamptonshire/_council_reference_alert_update.html, templates/email/northamptonshire/_council_reference_alert_update.txt, templates/email/peterborough/_council_reference_alert_update.html, templates/email/peterborough/_council_reference_alert_update.txt, templates/email/tfl/_council_reference_alert_update.html, templates/email/tfl/_council_reference_alert_update.txt
For FD-4535. And making consistent use of symlinks in this bit. [skip changelog]
Guess there's a question as to whether we should do this consistently everywhere automatically rather than needing a template, something to discuss perhaps.
=> [Central Beds] Adds council ref to alert update

perllib/FixMyStreet/App/Controller/Waste/Whitespace.pm
For now I've just added some logging to allow us to see what information Whitespace is sending to us when there's a new event.
For https://github.com/mysociety/societyworks/issues/4095
=> [Bexley][Whitespace] Add endpoint for incoming notifications

perllib/FixMyStreet/Cobrand/UK.pm
North Northants already had notopen311-open, but asked to also have the reporter/staff-open option, which didn't exist.
This change combines the notopen311-open and reporter/staff-open options into one.
For FD-4419
=> Add reporter/staff/notopen311-open option for updates_allowed

bin/export-import-data
This allows you to update existing contacts when importing a JSON file.
Handy to e.g. batch update emails, or add parent categories, etc.
=> Add --update-contacts flag to export-import-data

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Default.pm, t/app/controller/around.t
Setting a `suggestions` value to 0 within the `nearby_distances` cobrand feature disables the dupe suggestion feature for that group/category, eg:
```
nearby_distances:
my_cobrand:
suggestions:
_fallback: 100
Potholes: 0
```
=> Dupe suggestions can be disabled on a per-category basis in config

perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Reporting.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/bexley.t
It is possible to have a questionnaire response, which marks a report as fixed, without a corresponding update. To ensure we have all the correct fixed timestamps, fetch answered questionnaires as well to check for any fixed responses. [skip changelog]
=> Process answered questionnaires in CSV export.

templates/web/base/report/form/user_loggedout_email.html, templates/web/bromley/report/form/user_loggedout_email.html, web/cobrands/fixmystreet/fixmystreet.js
Adds aria-required attributes to the name and email fields, as well as any other fields marked as required in `web/js/validation_rules.js`.
Fixes https://github.com/mysociety/societyworks/issues/4492
=> Add aria-required attributes to new report form

web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4308
Added some spacing and sizing fixes for elements inside `.js-post-category-messages`.
https://github.com/mysociety/fixmystreet/assets/13790153/136a6c8f-6ad4-46ad-b7c9-abd64a786f06
=> Added varius stying fixes to .js-post-category-messages element

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Camden.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/Westminster.pm, t/cobrand/brent.t, t/cobrand/camden.t
Camden have provided a responsibility layer around boundary areas - we check against this to see who is responsible for a location that may be outside their defined boundary area and set the body responsible accordingly. Alternatively, it may be inside their boundary area but not be their responsibility.
They do not divide up responsibilities by category type
Camden needs to be set to be covered by, and to cover, all of its boundary areas.
https://github.com/mysociety/societyworks/issues/4399
=> [Camden] Adds boundary check against neighbours

templates/web/surrey/footer_extra.html, templates/web/surrey/footer_extra_js.html
I noticed that the <script> tags for Surrey's HappyOrNot feedback script were appearing [in service-worker.js](https://tellus.surreycc.gov.uk/service-worker.js) on their cobrand.
This fixes it by moving those scripts out of footer_extra_js and into footer_extra.
=> [Surrey] Move feedback script to different template

web/cobrands/sass/_admin.scss
For bodies covering a lot of areas, like National Highways, this resulted in an extremely wide body edit page.
=> [Admin] Restrict width of multi-select

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/email/bexley/waste/_sidebar_content.html
Adds the service description to the template email so the service and container are shown.
https://mysocietysupport.freshdesk.com/a/tickets/4449
=> [Bexley] Look up service description

templates/web/base/waste/bin_days.html
[skip changelog]. [FD-4559](https://mysocietysupport.freshdesk.com/a/tickets/4559).
=> [Brent] [Waste] Include collection window in bin days page.

templates/web/base/admin/reports/_edit_main.html
Not submitting the name field would cause a DB error because it would try to set `name` to NULL.
And including the other two seemed like a good idea too.
=> Fix admin editing of anonymous reports

CHANGELOG.md, bin/open311-populate-service-list
Allows bodies to be excluded from Open311 service list fetching.
This seemed like the simplest approach and matches what we do for `bin/fetch`. Other options I considered were adding a "skip service list fetch" checkbox to the body admin edit page, and adding a cobrand hook to allow cobrand to opt-out of service list fetching.
=> [Open311] Add --exclude to bin/open311-populate-service-list

web/cobrands/greenwich/_colours.scss, web/cobrands/greenwich/base.scss
Update to match their site. The front page colour didn't seem to do anything, and the visited seemed pointless. [skip changelog] Fixes https://github.com/mysociety/societyworks/issues/3435
=> [Greenwich] Update link colour.

perllib/FixMyStreet/App/Controller/Auth.pm, t/app/controller/auth_social.t, templates/web/base/auth/general.html, templates/web/brent/errors/generic.html, templates/web/camden/auth/general.html, templates/web/hackney/auth/general.html, templates/web/tfl/errors/generic.html
This reduces confusion if a browser auto-fills the email form but someone still clicks the SSO button, or similar. [skip changelog]
=> Make SSO button use separate form.

templates/web/base/report/form/user_name.html, templates/web/fixmystreet-uk-councils/report/form/user_name.html
Ensure the full name field is marked as required for screen readers.
Fixes https://github.com/mysociety/societyworks/issues/4492
=> Full name is aria-required in report creation

.cypress/cypress/integration/category_tests.js, perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/App/Controller/Report/New.pm, t/app/controller/auth_social.t, t/app/controller/report_new.t, t/cobrand/brent.t, t/cobrand/northumberland.t, templates/web/base/report/new/category.html, web/cobrands/fixmystreet/fixmystreet.js
If a category is in a group on its own, the reporting form hoists it up to the top level, to save a pointless extra step. In doing so, it was no longer getting the associated group to store for submission. Rewrite the input so it is clearer as to what we are receiving. For FD-4534 [skip changelog]
=> Capture group from hoisted categories.

perllib/FixMyStreet/App/Controller/Status.pm, t/app/controller/status.t
Trying to narrow down if the slow responses are due to DB contention or some other cause.
=> Add logging of slow/failed DB queries to healthcheck page

perllib/FixMyStreet/Roles/Cobrand/Echo.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_merton_bulky.t
Once we have sent an email concerning a payment confirmation update failure, we should stop trying to send that payment confirmation update. [skip changelog]
=> [Echo] Mark update as skipped after fallback email

t/cobrand/sutton.t, templates/web/base/report/photo.html
When viewing a link from an alert confirming a bulky waste order has been picked up, make the images available if the user is not logged in to their WasteWorks account.
https://github.com/mysociety/societyworks/issues/4525
=> [WW][Bulky][Sutton] Bulky update images available logged out

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_peterborough.t, templates/web/fixmystreet-uk-councils/about/waste-calendar.html
- Adds `Cache-Control` header to `calendar.ics` responses
- No longer hits backend APIs for calendar help page
=> [Waste] Calendar performance improvements

templates/web/base/admin/extra-metadata-item.html, templates/web/base/admin/extra-metadata-option.html
This wasn't being output when creating a new category. It needs to always be present, and shown/hidden depending on the type picked. [skip changelog]
Fixes https://github.com/mysociety/societyworks/issues/4554
=> Fix display of option disable form checkbox.

perllib/FixMyStreet/Cobrand/FixaMinGata.pm, t/cobrand/fixamingata.t, templates/email/fixamingata/submit.html, templates/web/fixamingata/about/faq-sv.html, templates/web/fixamingata/about/privacy.html, templates/web/fixamingata/contact/address.html, templates/web/fixamingata/contact/blurb.html, templates/web/fixamingata/footer_extra_js.html, templates/web/fixamingata/report/new/inline-tips.html, web/cobrands/fixamingata/base.scss, web/cobrands/fixamingata/js.js, web/cobrands/fixamingata/layout.scss, web/cobrands/hylte/base.scss, web/cobrands/surrey/base.scss
Some minor FixaMinGata-related changes. The empty `public_update.html` file is intentional (we are currently not using this section of the inspect form).
Related to #4235.
=> [FixaMinGata] Add various updates

CHANGELOG.md, web/cobrands/fixmystreet/offline.js
For extremely long lists of planned reports this was causing load issues.
=> [offline] Cache inspector reports sequentially, not in parallel

.cypress/cypress/integration/borsetshire.js, CHANGELOG.md, templates/web/base/my/planned.html, web/cobrands/fixmystreet/images/cloud-download.svg, web/cobrands/fixmystreet/offline.js, web/cobrands/sass/_base.scss
Desktop users are presumably less likely to find themselves offline, so it doesn't make sense to cache all reports in the shortlist automatically. This commit adds a link to the bottom of the report list on the desktop version of the /my/planned page that allows users to kick off the caching process manually.
Behaviour on mobile is unchanged.
=> [offline] On desktop /my/planned don’t cache reports automatically

perllib/FixMyStreet/Test.pm, perllib/Open311/PopulateServiceList.pm, t/cobrand/bristol.t, t/cobrand/bromley.t, t/cobrand/greenwich.t, t/cobrand/rutland.t, t/cobrand/shropshire.t, t/cobrand/warwickshire.t, t/open311/populate-service-list.t
The main point of this PR is to add the ability for an Open311 endpoint to use a 'staff' keyword which will then automatically mark the category as staff only when it's created/updated. That's the last commit.
However, while implementing it it seemed good to tidy up the populate script so that it only updated the contact table once for a category (it was possible for a new Open311 category to update the DB once to create the category, once to add extra fields (with no note), once to set the group, once to set as non public or inactive or waste; updating a category would only do it for changes, but could still leave more than one). And then also I thought it good to make a difference between undeleting a category and having its name/destination change (in the former I think we can drop any …
=> [Open311] Add 'staff' keyword handling

perllib/FixMyStreet/Cobrand/Surrey.pm, t/cobrand/surrey.t
For https://github.com/mysociety/societyworks/issues/4512
=> [Surrey] Exclude Open311-fetched reports from cut_off_date

perllib/FixMyStreet/Cobrand/Camden.pm, t/cobrand/camden.t
Adds necessary Confirm roles https://github.com/mysociety/societyworks/issues/4298
Fixes https://github.com/mysociety/societyworks/issues/4504
=> [Camden] Setup Confirm integration

perllib/FixMyStreet/App/Controller/Waste/Echo.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/FixMyStreet/SendReport/Open311.pm, perllib/FixMyStreet/TestMech.pm, perllib/Open311/PostServiceRequestUpdates.pm, perllib/Open311/UpdatesBase.pm, t/cobrand/brent.t, t/cobrand/bromley.t, t/cobrand/bromley_waste.t, t/cobrand/sutton.t
closes https://github.com/mysociety/societyworks/issues/3267
Example on staging: https://staging.fixmystreet.com/admin/report_edit/23736
=> [Bromley] Create 'Investigation Required' events for comments on closed Echo-backed reports.

perllib/FixMyStreet/App/Controller/Develop.pm, perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste.t, t/app/controller/waste_bexley.t, t/app/controller/waste_brent_small_items.t, t/app/controller/waste_kingston_r.t, t/app/controller/waste_merton.t, t/app/controller/waste_sutton_r.t, t/cobrand/brent.t, templates/web/base/develop/index.html, templates/web/base/waste/confirmation.html, templates/web/bexley/waste/_confirmation_after.html
Similar to what we display in the emails.
For https://mysocietysupport.freshdesk.com/a/tickets/4606.
=> [Bexley][WW] Display additional missed report details on confirmation page

perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough_bulky.t
Bartec has a 250 char limit on the CREW_NOTES field (the 'location' field our end); reports fail to send if this limit is exceeded.
For https://3.basecamp.com/4020879/buckets/32749602/todos/7873595742 /  fixes https://github.com/mysociety/societyworks/issues/4568 .
=> [P'bro][WW] Limit bulky location details to 250 characters

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Alert.pm, perllib/FixMyStreet/App/Controller/Rss.pm, perllib/FixMyStreet/Script/Alerts.pm, t/app/controller/alert_new.t, templates/web/base/alert/_list.html, web/cobrands/fixmystreet/fixmystreet.js
Fixes https://github.com/mysociety/societyworks/issues/3278
=> Allow decimals in the local alert radius.

bin/bexley/make-bexley-ww-postcode-db, perllib/BexleyAddresses.pm, t/app/controller/waste_bexley.t
We were skipping over all parent addresses on the assumption that all were 'shell' addresses that shouldn't be displayed. But the 'shell' status only applies to some parents.
For https://mysocietysupport.freshdesk.com/a/tickets/4432.
Closes https://github.com/mysociety/societyworks/issues/4498.
=> [Bexley][WW] Only skip parent addresses if they are marked as 'shell' properties

templates/web/base/alert/index.html, templates/web/base/around/postcode_form.html
Fixes: https://github.com/mysociety/societyworks/issues/4561
Replaces: https://github.com/mysociety/fixmystreet/pull/5207
Because the Geolocate button comes after the submit button, assistive device users might not realise it even exists. So, we have added an aria-label to input#pc in the front and alert page that provides more context about the input postcode and a geolocate button at the end of the form.
=> Added aria-label to input#pc

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/IsleOfWight.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Cobrand/Thamesmead.pm, perllib/FixMyStreet/Cobrand/UK.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, perllib/FixMyStreet/Cobrand/Westminster.pm, perllib/FixMyStreet/DB/ResultSet/Contact.pm
I did some in f241299b1 but seemed to have missed quite a few! We don't need to check translations for all the overlapping asset stuff etc, we want to check against the actual db name.
This should cut down on the number of translation DB lookups when e.g. fetching /report/new/ajax pages.
I also try and fetch the translations first off, so that no more DB queries are needed anyway. (That's probably a better way of doing it I thought of after, but might as well leave the others, clearer for the comparison.)
=> Reduce body name translation db lookups

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm, perllib/FixMyStreet/App/Controller/Council.pm, perllib/FixMyStreet/App/Controller/Reports.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/UK.pm, t/Mock/MapIt.pm, t/cobrand/bucks.t, t/cobrand/fixmystreet.t
Fixes https://github.com/mysociety/fixmystreet/issues/160 [skip changelog]
This adds the ability to add parish council bodies to .com (with a manual allow list rather than having them all appear in the area dropdown on the body page), and also allows parish council alert updates everywhere, regardless of if bodies exist for them or not.
~~It updates the alert sign up page to have it one column, ordered by area rather than destination, and fixes a bug where you signed up for a different body than it said in Brent/Camden type areas.~~ This part has been merged.
=> Add parish councils

web/cobrands/highways/assets.js
Fixes: https://github.com/mysociety/societyworks/issues/4549
Currently we use the segmented-control(pill) component, unfortunately it does not cover cases where the address of the report is quite long. This causes horizontal overflow and UI wise both buttons look quite uneven, because one is quite long while the other one says "Somewhere else".
With this change I think is also more obvious that they are options and not buttons. For example I tried stacking both "buttons" vertically so the first button being too long is not a problem anymore, unfortunately I think in terms of UX is a bit confusing because they look just like `.btn` and `btn--primary` so it just look like styled links, where one has more emphasis than the other one, instead of what they really are: option A which is active, …
=> Added GOVUK radio buttons on National Highways report message

templates/web/base/report/_main.html, web/cobrands/fixmystreet/fixmystreet.js
Bug found while working on this PR: https://github.com/mysociety/fixmystreet/pull/5208
This PR changes the markup of `label.btn--shortlist` and swaps it for `button.btn--shortlist`, that way the element is focusable and can also be interacted via keyboard.
=> Shortlist button focusable

templates/web/base/report/new/form_report.html, web/cobrands/bexley/_colours.scss, web/cobrands/bexley/base.scss, web/cobrands/bromley/_colours.scss, web/cobrands/bromley/base.scss, web/cobrands/camden/_mixins.scss, web/cobrands/cheshireeast/_colours.scss, web/cobrands/cheshireeast/base.scss, web/cobrands/gloucestershire/_variables.scss, web/cobrands/gloucestershire/base.scss, web/cobrands/highwaysengland/_colours.scss, web/cobrands/highwaysengland/base.scss, web/cobrands/hounslow/_colours.scss, web/cobrands/hounslow/base.scss, web/cobrands/lincolnshire/_colours.scss, web/cobrands/lincolnshire/base.scss, web/cobrands/nottinghamshirepolice/base.scss, web/cobrands/peterborough/_colours.scss, web/cobrands/peterborough/base.scss, web/cobrands/sass/_mixins.scss, web/cobrands/shropshire/_colours.scss, web/cobrands/westminster/_buttons.scss, web/cobrands/westminster/_colours.scss, web/cobrands/westnorthants/base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4246
With this PR "Continue" button will have  same styling as `btn--primary`, to match the branding of each cobrand, the disabled state has also been updated so it has a more evident "disabled" state.
NOTE: To fix the original issue, including `btn-primary` is more of a bonus, but we could also get away with keeping what we currently have and add transparentize effect that passes the contrast colour to the disabled state. However this could be an opportunity to make a standard across all cobrands the use of the mixin `button-variant` for `btn--primary`.  As an extra I think we could also include an extra variable in the mixin to control the `border-radius` property. We would be covering more topics, so happy to open a new issue to …
=> Added btn--primary class to "Continue" button in New report page

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Request/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_container_requests.t, templates/web/base/waste/confirmation.html, templates/web/bexley/waste/summary_request.html
For https://github.com/mysociety/societyworks/issues/4576 and some of https://github.com/mysociety/societyworks/issues/4575.
The normal 'request new' journey also includes options for removal, if property has containers that can be removed.
There is also a separate journey that handles removals only.
=> [Bexley][WW] Handle container removal requests

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/4572
This would involve adding the below to the server configuration (I guessed the mapped states, I don't think we've been given them?). (Note that I would be in favour of adding admin templates with these texts in, and then not having them in the server configuration at all, that would have the same outcome with less configuration needed.)
The alert update email already includes a "Contact us" link to https://mybexley.bexley.gov.uk/service/rubbish_and_recycling_enquiries so I'm going to take that as already covered by that.
```
container_deliver_state_mapping:
Container Delivered:
fms_state: fixed - council
text: Our waste contractor has confirmed that your new bin has been delivered.
Duplicate Request
fms_state: …
```
=> [Bexley] Spot updates on container requests.

perllib/FixMyStreet/App/Controller/Auth/Social.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Cobrand/UK.pm, perllib/FixMyStreet/DB/Result/Comment.pm, perllib/OIDC/Lite/Client/IDTokenResponseParser.pm, t/Mock/MicrosoftGraph.pm, t/Mock/OpenIDConnect.pm, t/cobrand/highwaysengland.t, t/cobrand/tfl.t, templates/web/base/admin/index.html, templates/web/highwaysengland/errors/generic.html
Initial setup for single sign on
Include debugging info to show payload for seeing what fields are used for this and going forward.
https://3.basecamp.com/4020879/buckets/37793327/todos/7702417410#__recording_7705494216
=> [National Highways] Initialise single-sign on

perllib/FixMyStreet/SendReport/Open311.pm, t/cobrand/bromley.t
Otherwise, a later resending will still use the override category.
=> [Bromley] Reset category override once sent.

templates/web/surrey/header_logo.html
Surrey have requested that their logo link back to their main website, rather than to FMS.
FD-4742
=> [Surrey] Add custom header logo template

perllib/Open311/UpdatesBase.pm, t/app/model/problem.t
If we're told the update is only the latest data, so we can't trust the timestamp, compare it against the last system user comment, and skip if it matches the same text and problem state. Move the assigned user code earlier so that it will be run.
[FMS end corresponding with https://github.com/mysociety/open311-adapter/pull/371 ]
I did wonder about changing the update_id at the open311 end to be a hash of state+text (which it looks like we do do in another backend or two), so it would match once and then not again, but I thought comparing against the last system update received was better if something moved into the same state twice (and perhaps those other backends could be switched to do this as well - unless I've missed something about checking the last update!)
For …
=> [Open311] Skip latest data identical updates.

docker-compose.yml, docker/docker-compose-dev.yml
See https://github.com/jgoerzen/docker-debian-base-standard?tab=readme-ov-file#container-invocation-systemd-containers-busterbullseyesid (with options changed to be in the docker compose file).
Without these lines you get lots of failures about operation not permitted, or read only file system, or process manager cannot be allocated, etc etc
=> [Docker] Changes needed for systemd to work.

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Zurich.pm, t/cobrand/zurich.t, templates/web/base/around/display_location.html, templates/web/base/around/postcode_form.html, templates/web/zurich/report/new/fill_in_details_form.html, web/cobrands/sass/_layout.scss
For Zurich, can add a prefill_description to the url arguments which will fill the description of a report.
Can also add a prefill_category, and it will remove the category choice, so category can not be changed - also provides a call hook used by Zurich to allow reports to be made in not active categories.
https://github.com/mysociety/societyworks/issues/4517
=> [Zurich][FMS] Adds a filter_description url argument

cpanfile
`mirror =>` is failing (for `carton install`, not sure about `carton install --deployment`) with recent `carton`/`cpanm` and I doubt it works with old vendored carton neither.
I propose to replace per `url =>` which is [documented](https://metacpan.org/pod/Carton#Specifying-a-CPAN-distribution) (`mirror` is documented but only with usage of `dist` along).  
What do you think?
=> cpanfile: Use url instead mirror for Geography::NationalGrid

perllib/FixMyStreet/App/Form/Waste/Request.pm, perllib/FixMyStreet/App/Form/Waste/Request/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/FixMyStreet/Script/Alerts.pm, t/app/controller/waste_bexley.t, t/app/controller/waste_bexley_container_requests.t, templates/web/base/govuk/fields.html, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/_services_request.html, templates/web/bexley/waste/container_delivery_intro.html, templates/web/bexley/waste/container_removal_intro.html, templates/web/bexley/waste/services.html
For https://3.basecamp.com/4020879/buckets/35109031/todolists/7983073165.
=> [Bexley][WW] Container requests fixes part 2

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/brent.t
If a report is by a member of staff then check if they have a role and set that in the exported data.
https://mysocietysupport.freshdesk.com/a/tickets/4306
=> [Brent] Add Staff Role column to csv export

docker-compose.yml
Is switching to an inlne dockerfile like this okay, do you think? Saves us having to maintain/update a postgres container separately, but I didn't know if there was a downside.
Fixes https://github.com/mysociety/fixmystreet/issues/5271
=> [Docker] Update third party containers.

t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_more_services_sidebar.html
Link should only be under individual containers and not in the more_services block
https://mysocietysupport.freshdesk.com/a/tickets/4774
=> [Peterborough] Link to report waste service only in on place

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Auth.pm, perllib/FixMyStreet/App/Controller/Auth/Social.pm, perllib/FixMyStreet/App/Controller/Form.pm, perllib/FixMyStreet/App/Controller/My.pm, perllib/FixMyStreet/App/Controller/Questionnaire.pm, perllib/FixMyStreet/App/Controller/Root.pm, t/app/controller/admin.t, t/app/controller/admin/triage.t, t/app/controller/auth_profile.t, t/app/controller/index.t, t/app/controller/my.t, t/app/controller/my_planned.t, t/app/controller/questionnaire.t, t/app/controller/report_updates.t, t/app/controller/waste_echo.t, templates/web/base/errors/generic.html, templates/web/brent/errors/generic.html, templates/web/highwaysengland/errors/generic.html, templates/web/tfl/errors/generic.html, web/cobrands/sass/_base.scss
This adds more logging to page_error, including the HTTP status code, the request IP address, an internal message to show the reason for the error, and a random string to help identify the error in the logs. This string is also shown on the error page to the user, to improve the chance of it being included in any screenshots from users.
For https://github.com/mysociety/societyworks/issues/4628
=> Better logging of page_error

.cypress/cypress/integration/surrey.js, web/cobrands/fixmystreet/assets.js
Reported that users think the button is broken and don't read the message above for an explanation of why they can't proceed
https://mysocietysupport.freshdesk.com/a/tickets/4768
https://mysocietysupport.freshdesk.com/a/tickets/4818
=> [Surrey] [Hart] Continue button should not be visible when disabled

templates/web/surrey/footer_extra.html, web/cobrands/surrey/base.scss
=> [Surrey] Add text under happy-or-not section

perllib/FixMyStreet/Cobrand/NottinghamshirePolice.pm, t/cobrand/nottinghamshirepolice.t
For FD-4703.
For https://github.com/mysociety/societyworks/issues/4608
=> [Notts Police] Allow staff to manage available states

perllib/FixMyStreet/App/Controller/Report/New.pm, t/cobrand/zurich.t
The check for a private category needed to be done in contacts_to_bodies as well as process_report.
[skip changelog] Fixes FD-4869
=> [Zurich] Fix setting of body in inactive category.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
This was being set incorrectly as Whitespace returns inaccurate information from its GetSiteContracts endpoint. So instead set it from $property->{has_assisted} as we do elsewhere.
For FD-4777
=> [Bexley] Fix for assisted collections flag

t/app/controller/waste_bexley.t, templates/email/bexley/waste/_email_data.html, templates/email/bexley/waste/_report_details.txt, templates/email/bexley/waste/_sidebar_content.html, templates/email/bexley/waste/other-reported.html, templates/email/bexley/waste/other-reported.txt, templates/web/bexley/waste/_more_services_sidebar.html
For https://github.com/mysociety/societyworks/issues/4520.
- https://3.basecamp.com/4020879/buckets/35109031/todos/8072413022 - add clinical waste link
- https://3.basecamp.com/4020879/buckets/35109031/todos/8057915745 - text changes for enquiry form (I also made some additional fixes because otherwise Bexley are likely to raise those separately later on)
=> Bexley WW container requests: post go-live amendments

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Transfer.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, t/app/controller/waste_merton_garden.t, templates/web/base/waste/garden/transfer_confirm_addresses.html, templates/web/base/waste/garden/transferred.html, templates/web/merton/waste/_more_services_sidebar.html
When a Green Garden Waste subscriber in Merton moves to another address in Merton, they can transfer the remainder of their ggw subscription to the new address
1) As long as the new address does not already have a sub 
2) As long as there is a ggw on their previous property, and it is not in the renewal period
3) They have brought their bin(s) with them
This is a staff only feature.
https://github.com/mysociety/societyworks/issues/4551
=> [Merton][WW] Allow transfer of ggw subscription

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, t/app/controller/waste_merton_bulky.t, t/cobrand/merton.t
Rather than a cancellation update on the original and no logged on the new (if no payment), send the reverse - a logged email on the new, and no cancellation update.
Fixes FD-4484
=> [Merton] Send different email on bulky amending.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
Manual exceptions have round codes like "(Mon) GDN-R1" rather than just GDN-R1.
Should fix FD-4764.
=> [Bexley] Spot logs with more text in their round.

perllib/FixMyStreet/Cobrand/Merton.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/Cobrand/BulkyWaste.pm, perllib/FixMyStreet/Script/Merton/SendWaste.pm, t/app/controller/waste_merton_bulky.t, templates/web/base/waste/bulky/summary.html
If we're confirming payment by an update (SLWP), store the payment as extra data on the update, so that it'll be sent through to the backend. Also store *all* payments, so for amendments the full history is sent through with the amended new booking.
=> [Merton] Send through all payment details

perllib/FixMyStreet/App/Form/Waste/Request.pm, perllib/FixMyStreet/App/Form/Waste/Request/Merton/Larger.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, t/app/controller/waste_merton.t, templates/web/base/waste/summary_request.html, templates/web/merton/waste/_confirmation_after.html, templates/web/merton/waste/_more_services_sidebar.html, templates/web/merton/waste/request/intro.html, templates/web/merton/waste/request/static.html, templates/web/peterborough/waste/summary_request.html
Fixes https://github.com/mysociety/societyworks/issues/4594
=> [Merton] Add larger bin process flow.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, t/app/controller/waste_merton.t, templates/email/default/waste/other-reported.html, templates/email/default/waste/other-reported.txt, templates/web/base/waste/services.html, templates/web/merton/waste/enquiry-problem.html
Part 1 of MRT167 Set up remaining processes in WW
Allow residents to select specified bin types to report a problem that bins haven't been returned correctly to the correct  location or have been left open.
These reports allow a request for the bin collectors to return and rectify the issue along with a notes field
Waste spillage can be reported just with a notes field.
To make live: Check category details on servers with same branch name are live and merge this
https://github.com/mysociety/societyworks/issues/4593
=> [Merton] Bin not being returned correctly and waste spillage

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/Cobrand/DDProcessor.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, templates/email/bromley/_council_reference_alert_update.html, templates/email/bromley/_council_reference_alert_update.txt, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/default/waste/other-reported-bulky.html, templates/email/default/waste/other-reported-bulky.txt, templates/email/kingston/_council_reference_alert_update.html, templates/email/kingston/_council_reference_alert_update.txt, templates/email/kingston/waste/bulky-reminder.html, templates/email/kingston/waste/bulky-reminder.txt, templates/email/merton/_council_reference_alert_update.html, templates/email/merton/_council_reference_alert_update.txt, templates/email/sutton/_council_reference_alert_update.html, templates/email/sutton/_council_reference_alert_update.txt, templates/web/base/admin/reports/_edit_waste.html, templates/web/base/waste/_button_show_upcoming.html, templates/web/fixmystreet-uk-councils/report/_updates_disallowed_message.html, templates/web/peterborough/waste/bulky/confirmation.html, templates/web/peterborough/waste/confirmation.html
Bexley uses the UPRN, not the property ID, so use this so that some things that add links to bin day pages can work more automatically. [skip changelog]
There's one use left of property_id directly, I think, which is in the get_original_sub call, so that will need looking at as part of Bexley GGW.
=> Add waste_property_id function.

.cypress/cypress/integration/bromley.js, bin/fixmystreet.com/fixture, data/test-asset-layers.yml, perllib/FixMyStreet/Cobrand/Bromley.pm, t/Mock/MapIt.pm, t/cobrand/bromley.t, web/cobrands/fixmystreet-uk-councils/assets.js
Set a hidden field when the asset is selected and the report is made so that we can recognise it was on an streetlight belonging to Bromley regardless of the id
https://mysocietysupport.freshdesk.com/a/tickets/4815
=> [Bromley] Any streetlight on a Bromley asset should be 'in Bromley'

perllib/FixMyStreet/Cobrand/UK.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm
Rather than directing back to the dashboard page.
We already had checks for Bexley & Greenwich, whose full names start with 'London|Royal Borough of'; we needed a check for Kingston upon Thames as well.
This is a minimal fix; I feel there's improvements to be made elsewhere or other bugs that may crop up (e.g. should perllib/FixMyStreet/Cobrand/Kingston.pm have its council_name updated to be 'Royal Borough of...'?) But I do not know how much behaviour that would affect down the line.
Fixes https://github.com/mysociety/societyworks/issues/4609.
=> [FMS] Make sure /reports link for Kingston work

perllib/Open311/PostServiceRequestUpdates.pm, t/script/send-daemon.t
Updates are selected in random order but some cobrands/APIs (e.g. Northumberland/Alloy) do not know how to handle updates in order their end, so an earlier update may overwrite a later one.
This change checks that an update is not sent until earlier updates for that problem are sent.
Fixes https://github.com/mysociety/societyworks/issues/4640.
=> Prevent Open311 updates from being sent out of order

web/cobrands/fixmystreet-uk-councils/assets.js
The "Rights of way" category is now called "Public Rights of way", so update the asset code to match.
See also commit `74b3a1473` in the servers repo.
For FD-4937
=> [Central Beds] Rename rights of way asset layer

perllib/FixMyStreet/Cobrand/Sutton.pm, t/app/controller/waste_sutton_garden.t
Adds a cream-coloured Garden Waste Sack Image, requested by the client in FD-4929.
=> [Sutton] Add garden waste sack image

templates/web/surrey/around/intro.html
For https://mysocietysupport.freshdesk.com/a/tickets/4918.
Before:
After:
=> [surrey] Update intro text.

perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/Integrations/Echo.pm
This simplifies the code by avoiding the need to pass the config around.
It also means that calling FindPoints via `call-wasteworks-backend` will only return address_types from the config file without the need to manually pass in the config.
Came up while investigating FD-4972
=> [Echo] Add address_types to the Echo integration class

perllib/FixMyStreet/Cobrand/Oxfordshire.pm, t/cobrand/oxfordshire.t
Oxfordshire would like the category 'Trees obscuring street lights' to send an additional email as well as being sent over open311.
https://mysocietysupport.freshdesk.com/a/tickets/4741
=> [Oxfordshire] Send additional email on category

web/cobrands/fixmystreet-uk-councils/roadworks.js, web/js/map-OpenLayers.js
Previously all map pans on /around were hitting the Street Manager API unnecessarily.
WIP - /report/new is broken at the very least, probably others.
For https://github.com/mysociety/societyworks/issues/4728
=> [Street Manager] Only activate asset layer when starting report

templates/web/brent/waste/request/intro.html
[skip changelog] https://mysocietysupport.freshdesk.com/a/tickets/5031
=> [Brent] [Waste] Add notice for food caddy delays.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
Communal/flat above shop properties should always show their location lists, for staff as well as public.
Fixes https://mysocietysupport.freshdesk.com/a/tickets/5046
=> [Bexley] Communal/FAS take precedence for staff.

templates/web/fixamingata/footer_extra.html, web/cobrands/fixamingata/js.js
The `app-platform` cookie comes from the PWABuilder code:
```
$ grep -Inr app-platform
./src/FixaMinGata/Settings.swift:22:let platformCookie = Cookie(name: "app-platform", value: "iOS App Store")
```
It has worked okay for us. The app icons are visible outside of the iOS app but hidden inside the iOS app.
Apple rejected the app until we made that change.
Related to #4153.
=> [FixaMinGata] Hide app badges when using PWABuilder

web/cobrands/fixamingata/js.js
We disabled the installation banner two years ago and no one has complained.
Related to #4153.
=> [FixaMinGata] Avoid displaying the installation banner

perllib/FixMyStreet/Cobrand/Southwark.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/southwark.t
For https://mysocietysupport.freshdesk.com/a/tickets/5051
=> [Southwark] Include user email in CSV report export.

perllib/Open311/UpdatesBase.pm, t/cobrand/brent.t, t/cobrand/bromley_waste.t, t/cobrand/sutton.t
https://github.com/mysociety/societyworks/issues/4748
=> Only update 'lastupdate' when the update is new.

templates/web/bristol/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html, web/cobrands/fixmystreet-uk-councils/assets.js
Setup for two asset layers to have either selected to allow reports in Bristol on relevant categories.
https://github.com/mysociety/societyworks/issues/4692
Configuration in same branch on the servers
=> [Bristol] Add layers for allowed reports

perllib/FixMyStreet/Script/Alerts.pm, t/cobrand/highwaysengland.t
Fixes https://github.com/mysociety/societyworks/issues/4747
=> [National Highways] Only include NH reports in alerts

perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/bristol.t
Where an Alloy report is sending to Bristol over Open311 it must have a usrn present to identify the street it is on so the report can be parented to the correct road and given the correct locality.
https://github.com/mysociety/societyworks/issues/4743
=> [Bristol][Alloy] Adds putting usrn into Alloy reports

perllib/FixMyStreet/App/Form/Waste/Request/Brent.pm, perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/4589
(changes from WIP. -I moved the set up of payment into the about_you next because in the replacement next we don’t yet have the answer to the “how_long_lived” question, and I don’t think we need a special page about payment, they can stick whatever text they want in the intro)
=> [Brent] Add payment for some containers.

.cypress/cypress/integration/hounslow.js, bin/fixmystreet.com/fixture, perllib/FixMyStreet/Cobrand/Hounslow.pm, perllib/FixMyStreet/DB/Result/Comment.pm, t/Mock/MapIt.pm, t/app/controller/contact_enquiry.t, t/app/controller/report_new.t, t/cobrand/hounslow.t, t/sendreport/open311_send.t, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js, web/cobrands/hounslow/js.js
Rename the **Hounslow Borough Council** body to **Hounslow Highways**, seeing as that's what it's publicly called.
This should also fix an issue where a report could go to multiple bodies but it wasn't previously listing all those bodies to the user.
For FD-5117
The following need to be done when deploying this change
=> [Hounslow] Rename body to "Hounslow Highways"

perllib/FixMyStreet/Template.pm, t/app/controller/admin/sitemessage.t, templates/web/base/front/site-message.html, templates/web/base/report/new/form_after_heading.html, templates/web/base/waste/header.html, templates/web/bathnes/around/_postcode_form_post.html, templates/web/peterborough/waste/header.html
If we detect that a site message contains HTML then don't use the html_para filter to avoid adding extra <br> elements which mess up spacing.
For FD-5103
=> Fix HTML in site messages

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
If a category has a `FLYT_NOT` extra field then include that in the report description.
For FD-5053
=> [Bromley] Include flytip information in report description

perllib/FixMyStreet/Cobrand/Lincolnshire.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/lincolnshire.t
Extends the dashboard CSV export to include additional columns for staff users and their roles when a report is contributed by a staff member.
For FD-5038
=> [Lincolnshire] Add staff user and role to dashboard CSV export

t/cobrand/peterborough.t, templates/web/fixmystreet.com/report/new/flytipping_text.html, templates/web/fixmystreet.com/report/new/roads_message.html, templates/web/peterborough/report/new/flytipping_text.html, templates/web/peterborough/report/new/roads_message.html
Remove `<br>`s that were appearing in the update.
Fixes https://github.com/mysociety/societyworks/issues/4730
For FD-4998
=> [Peterborough] Fix closed flytipping message.

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/DB/Result/User.pm, perllib/Open311/UpdatesBase.pm, t/app/model/problem.t, t/cobrand/northumberland.t, templates/web/base/report/_update_state.html, templates/web/base/report/updates.html
For https://mysocietysupport.freshdesk.com/a/tickets/3082 / https://github.com/mysociety/societyworks/issues/4507.
=> [Northumberland] Fetch 'detailed_information' (extra details) to/from Alloy & assigned user to Alloy

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/Integrations/SCP.pm, t/app/controller/waste_bexley_garden.t, templates/web/bexley/waste/garden/subscribe_intro.html, templates/web/bexley/waste/services_extra.html
Builds on #5324 - with that and the #5322 refactor, basic garden subscription itself is hopefully not too much as you can see, is mostly a test!
With the configuration given in https://github.com/mysociety/societyworks/issues/4613, and a "Garden Subscription" category with payment/payment_method/uprn/property_id extra fields, and not with garden_disabled, with this PR you should be able to get through a subscription sign up from bin day page link in right sidebar to the details page, and with SCP (public) or Paye (staff) payment. It should then confirm and create a report for then sending to Agile (not storing any extra data as yet, see TODOs in the test).
=> [Bexley] Garden subscription flow, front to payment.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Cancel.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Cancel/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Agile.pm, t/app/controller/waste_bexley.t, t/app/controller/waste_bexley_container_requests.t, t/app/controller/waste_bexley_garden.t
For https://github.com/mysociety/societyworks/issues/4679.
=> [Bexley][WW] Cancel GGW subscription

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t
As follow-up to https://github.com/mysociety/fixmystreet/pull/5371.
=> [Bexley][WW] Populate direct debit fields to pass to Agile

perllib/FixMyStreet/App/Form/Waste/Garden/Cancel/Bexley.pm, t/app/controller/waste_bexley_garden.t
For https://3.basecamp.com/4020879/buckets/40373795/todos/8328047893.
'Further details' text box should only be required when reason is 'Other'.
=> [Bexley][WW] Garden cancellation textbox fix

bin/bexley/make-bexley-ww-postcode-db, perllib/BexleyAddresses.pm
closes https://github.com/mysociety/societyworks/issues/4463
Matthew:
* I rearranged the script to put flow top / business logic middle / setup data last.
* For use in production, it creates a new full file in a tempfile then moves into place. For updates it updates in place.
* It works out the type of file (full or update) from its contents.
* As we don't know what rows a COU file will contain, I thought it easiest to store the BLPU rows as well (then they can be updated if changes come in) and change the queries to check property shell then, rather than try and work out dependencies between the types.
* As we don't use full text search, I changed the tables to be normal ones with a primary key, making updating much easier. If FTS is needed in future, that can be joined …
=> [Bexley] Adapt postcode DB script to take URL for fetching CSV.

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm
This allows staff to setup a Direct Debit on behalf of a customer.
For https://3.basecamp.com/4020879/buckets/40373795/todos/8365691536
=> [Bexley][WW] Allow staff to choose payment method

perllib/FixMyStreet/App/Form/Waste/AccessPaySuiteBankDetails.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Bexley.pm, t/Mock/AccessPaySuiteBankChecker.pm, t/app/controller/waste_bexley_garden.t
The Access PaySuite DD API does not validate bank details when creating new contracts, so we first pass them to a totally separate Access PaySuite 'bankchecker' API to make sure they're good.
For https://github.com/mysociety/societyworks/issues/4823
=> [Bexley][WW] Validate DD bank details before submitting them

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_garden.t, templates/web/bexley/waste/garden/renew_bin_desc.html
For https://github.com/mysociety/societyworks/issues/4678.
=> [Bexley][WW] Renew GGW subscription

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_bexley_garden.t, templates/email/default/waste/_garden_data.html
=> [Bexley][WW] GGW misc todos

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_bexley_garden.t
For https://3.basecamp.com/4020879/buckets/40373795/todos/8374072726#__recording_8397227572 - cancellations for DD subscriptions were not auto-confirming.
=> [Bexley][WW] Automatically mark cancellation report as confirmed for DD sub

perllib/FixMyStreet/App/Controller/Waste.pm
Just had this thought this morning; DD reports are confirmed immediately, so we don't need to check for unconfirmed reports, which might confuse with unpaid credit card reports. [skip changelog]
Wasn't entirely sure if should only do this for cancelled, the known issue, not new/renew, but I thought this was slightly better in case there's a problem sending to Agile so we don't have the RENEWALDUE from there.
=> [Bexley] For pending reports, look for confirmed.

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t
=> [Bexley] Don’t pass NOACTIVE as ACTIVE.

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Roles/Cobrand/Paye.pm, perllib/Integrations/Paye.pm, t/app/controller/waste_bexley_garden.t
- Add support for custom narratives in the Paye integration
- Add method to Bexley garden module to generate a custom narrative
- Update Paye role to use the custom narrative method if available
For https://3.basecamp.com/4020879/buckets/40373795/todos/8407638567
=> [Bexley][WW] Customize paye.net narrative field for GGW

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/Open311/UpdatesBase.pm
As perlsyn says, "NOTE: The behaviour of a `my`, `state`, or `our` modified with a statement modifier conditional or loop construct (for example, `my $x if ...`) is undefined. The value of the `my` variable may be `undef`, any previously assigned value, or possibly anything else."
Repeat of #2377 [skip changelog]
=> Remove any use of my $x if $foo.

perllib/Integrations/AccessPaySuite.pm, t/app/controller/waste_bexley_garden.t
This ensures that HTTP requests made to the Access PaySuite API have the correct Content-Length header set, which it seems to require, for POST requests at least.
Spotted this when trying to archive contracts manually from the CLI.
=> [Bexley] Add Content-Length header to DD requests

perllib/FixMyStreet/App/Controller/Report/New.pm, t/app/controller/report_new_open311.t, t/open311/populate-service-list.t
Check that stopper categories in the metadata are added to options.
https://github.com/mysociety/societyworks/issues/4757
=> [FMS] Test receiving stopper categories from open311

perllib/FixMyStreet/App/Controller/Form.pm, perllib/FixMyStreet/App/Form/Wizard.pm, t/app/controller/waste_bexley_garden.t, templates/web/base/waste/already_submitted.html
If a user refreshes the page after submitting the form we detect this and show them an error.
I also tried adding a check for an existing sub in Agile before creating the Direct Debit, but this doesn't work in the case of a renewal where a user is switching from Credit/Debit Card to Direct Debit, in which case there will already be a sub in Agile. Might be possible to do something there, but was a bit fiddly, and we're already checking for an existing sub in the main flow, so this is a bit of an edge case.
[Related Slack thread](https://mysociety.slack.com/archives/C07H1MFDNRG/p1742908679431989)
=> [Bexley] Don't show form on double submission

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t
Staff aren't required to enter an email address, so set a default in that case as the email is required by Access PaySuite for setting up the Direct Debit.
For [this Basecamp todo](https://3.basecamp.com/4020879/buckets/40373795/todos/8471147856).
=> [Bexley] Default email address for Direct Debit when not provided

web/cobrands/fixmystreet-uk-councils/refresh.js
Chrome sometimes caches the ajax response (without header or footer) and can show that when clicking Back/Forward. [skip changelog] FD-5311
=> [Waste] When checking update, add parameter to URL

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, t/cobrand/highwaysengland.t
Fixes https://github.com/mysociety/societyworks/issues/4477 [skip changelog]
=> [National Highways] Per-area destination handling.

perllib/BexleyAddresses.pm
Bexley have a unique record in their systems where the property is in Bexley, but the street isn't. This means we need to relax the requirement for a matching street record when doing postcode and uprn lookups.
For FD-5333
---
The only slight issue with this is that because there's no associated street record it's displayed as just the property number, but I think that's ok for this unique situation.
=> [Bexley] Handle Bexley addresses that are not on Bexley streets

.cypress/cypress/fixtures/lincs_grass_LCDC_contactLCC.xml, .cypress/cypress/fixtures/lincs_grass_LCDC_contactLCDC.xml, .cypress/cypress/fixtures/lincs_grass_contact_cp.xml, .cypress/cypress/fixtures/lincs_grass_contact_parish.xml, .cypress/cypress/fixtures/lincs_grass_f0_withDates.xml, .cypress/cypress/fixtures/lincs_grass_f1_withDates.xml, .cypress/cypress/fixtures/lincs_grass_lcc_noDate.xml, .cypress/cypress/fixtures/lincs_grass_lcc_withDates.xml, .cypress/cypress/integration/lincolnshire.js, bin/fixmystreet.com/fixture, data/test-asset-layers.yml, t/Mock/MapIt.pm, templates/web/fixmystreet.com/report/new/roads_message.html, templates/web/lincolnshire/report/new/roads_message.html, web/cobrands/fixmystreet-uk-councils/assets.js
Adds layer which provides information about repsponsibility of grass areas in Lincolnshire which is triggered on selecting 'Grass cutting'
New action - if grass is Lincolnshire County Council responsibility (including those that are 'cut by' F1, F0, STR, Flail) and has cutting dates, show the dates to the user and invite them to carry on with the report or abandon it depending if that answers their query
Keep action - if grass is Lincolnshire County Council and no cutting dates, report continues to make report to Lincolnshire County Council
New action - if grass is District Council South Keveston or Lincoln City council and responsibility is with Lincolnshire County Council, send report to Lincolnshire County Council. Otherwise send to the District Council
New action - if grass is a …
=> [Lincs] Adds grass cutting layer and actions

perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/cobrand/bristol.t
For FD-4905
To test locally you will need:
```yaml
dott_email:
bristol: foo@bar.example.org
```
=> [Bristol] Send Dott reports to a different email address

perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP2.pm, t/app/controller/waste_sutton_r.t, templates/web/sutton/waste/_announcement.html
Following on the from the recent change to a new Echo system this RoundGroupName that's used to check whether the time-banded info box should be shown has been renamed, so this updates the code to use the new name.
For FD-5402
=> [Sutton] Update Time-banded info-box group name check

perllib/FixMyStreet/Cobrand/BathNES.pm
All passthrough contacts are manually added as the passthrough does not return a service list.
We extend protection from open311 changes to stop the removal of categories that don't have a corresponding service.
https://github.com/mysociety/societyworks/issues/4746
=> [BANES][FMS] Allows protection of open311 passthrough contacts

bin/fixmystreet.com/waste-check-payments, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/Cobrand/Adelante.pm, perllib/FixMyStreet/Roles/Cobrand/Paye.pm, perllib/FixMyStreet/Roles/Cobrand/SCP.pm, perllib/FixMyStreet/Script/Merton/SendWaste.pm, perllib/FixMyStreet/Script/Waste/CheckPayments.pm, t/app/controller/waste_bromley_bulky.t
For https://github.com/mysociety/societyworks/issues/4681 [skip changelog]
Doesn't actually include any Bexley specific tests/stuff, that should be added when payments are added in some other work. This is being used by Merton (and can be used by any SCP usage, which Bexley is).
=> [Bexley] Add payment fallback script

bin/banes/send_confirm_to_passthrough, perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Script/BANES/PassthroughConfirm.pm, perllib/Open311.pm, t/cobrand/bathnes.t, t/script/banes/sendtopassthrough.t
All reports are being sent to open311, but we still want reports with an email contact to be sent to the email contact after being sent to open311.
https://github.com/mysociety/societyworks/issues/4831
=> [BANES][FMS] Contacts with an email as the contact should be emailed

bin/banes/send_confirm_to_passthrough, perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Script/BANES/PassthroughConfirm.pm, perllib/Open311.pm, t/script/banes/sendtopassthrough.t
After reports or comments have been sent to Confirm through the standard send-reports script, we want to then send them on to the Passthrough endpoint.
Reports and comments should keep their Confirm identifications as they will continue to receive updates from Confirm.
https://github.com/mysociety/societyworks/issues/4831
=> [FMS][BANES] Create Script to send all Confirm reports to Passthrough endpoint

t/app/controller/waste_sutton_r.t, templates/web/sutton/waste/_bin_days_no_collections.html
[skip changelog] Config for this would be `no_service_residential_address_types: [ 102, 279, 105, 281, 284, 285, 288, 290, 352, 351, 350, 296, 289 ]` from https://3.basecamp.com/4020879/buckets/40355775/todos/8526030249#__recording_8541184649
=> [Sutton] Different no-service message for some address types.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_garden.t
Correctly handle addresses with a parent shell record. Previously, the panel was hidden for all addresses with a parent, under the assumption that services are tied to the parent record (as is the case with communal collections).
However, some properties have a parent record that is unused, with all services (including kerbside collections) linked to the child record. In these cases, the panel should be visible.
For FD-5332
=> [Bexley] Fix child properies with services

perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/councils.t
The permutation requested in https://github.com/mysociety/societyworks/issues/4792 didn't exist, but now it does.
=> [UK] Add reporter-open/staff updates_allowed option

bin/fixmystreet.com/send-stuck-reports-summary, perllib/FixMyStreet/Script/SendStuckReportsSummary.pm, t/script/send-stuck-reports-summary.t, templates/email/default/stuck-reports-summary.txt
Similar to the send-failure-summary one used internally but can be filtered to reports for a specific body and specific categories, and uses the cobrand URL, so better suited for flagging stuck reports externally.
Also supports sending details of unconfirmed reports.
For https://github.com/mysociety/societyworks/issues/4879.
`bexley-ggw-stuck-reports-cron` branch in servers repo has the changes to set-up the cron for Bexley. Verified with test script runs on staging site.
=> Add script to send stuck report summary emails.

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t
To speed up the loading of a bin days page this changes some of the Whitespace API calls to be made in parallel, and then cached.
Closes https://github.com/mysociety/societyworks/issues/4384
=> [Bexley] Make Whitespace API calls in parallel

web/cobrands/fixmystreet.com/base.scss, web/cobrands/sass/_base.scss
Fixes: https://github.com/mysociety/societyworks/issues/4538
- Increased colour contrast for link's default state(AA -> AAA)
- Increased colour contrast for link's hover state(Failed -> AA)
- Added text-decoration underline, so it's more noticeable for users with visual impairments that there is a link.
- Improved focus state by adding box-shadow and outline.
**Note:** We could have used the existing variables to change the underline `$link-text-decoration` and `$link-hover-text-decoration` behaviour. The problem with this alternative is that by adding an underline to the default state, we are also adding an underline to the links in the footer, navbar, sticky sidebar and links nested inside `item-list__item`. But it looks a bit jarring. It's probably why we got rid of the underline by …
=> Improved accessibility for links

perllib/Open311/UpdatesBase.pm, t/open311/getservicerequestupdates.t
We can be in the situation where we get multiple fixed updates from a backend, each with the same photo and no text or state change, and we don’t want to show this update just because it has a photo.
Fixes https://github.com/mysociety/societyworks/issues/4810
=> [Open311] Check photo has changed in new update.

perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/cobrand/fixmystreet.t
As NH is exempted from get_body_handler_for_problem in Cobrand::UK, its code for handling special emails is not automatically called. [skip changelog] Fixes failure to send #7545071.
=> [National Highways] Fix issue with special email handling on .com.

perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/councils.t, templates/web/fixmystreet-uk-councils/about/faq-en-gb.html, templates/web/fixmystreet-uk-councils/admin/bodies/_updates_disallowed_hint.html
This allows anyone to update an open report, but only staff can update a closed report.
Part of https://github.com/mysociety/societyworks/issues/4668 for Gloucester City.
=> Add open/staff config to updates_disallowed_check

perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Cobrand/Bristol.pm
Normally, these would be removed, but Bristol want to maintain them. We can't use the normal devolved send method workaround, because those do not appear on the Bristol cobrand. Fixes FD-5462 [skip changelog]
=> [Bristol] Protect manually added categories.

templates/web/gloucester/footer_extra_js.html
These are standard functionality for a UK council cobrand, that were accidentally missed when doing the initial frontend changes in #5295 
Fixes https://github.com/mysociety/societyworks/issues/4953
=> [Gloucester] Enable Street Manager, National Highways and validations

perllib/FixMyStreet/Cobrand/Gloucester.pm
Gloucester have a category with the same name under two different parents with two different destinations, so we'll need to use the display name so we can have them display correctly.
Fixes https://github.com/mysociety/societyworks/issues/4957
=> [Gloucester] Add display_name to admin contact

web/cobrands/fixmystreet-uk-councils/assets.js
Similar to Gloucester layer recently discussed with Nik. We have road and property layers, with messaging only to show if not in either, so only want the message attached to one of the layers. Currently, it would sometimes briefly show two messages, and not work depending on the order layers were returned.
Server diff would be:
```diff
diff --git a/vhosts/fixmystreet/assets/bristol.yml.include b/vhosts/fixmystreet/assets/bristol.yml.include
index 402afdd915..d18f796168 100644
--- a/vhosts/fixmystreet/assets/bristol.yml.include
+++ b/vhosts/fixmystreet/assets/bristol.yml.include
@@ -53,7 +53,8 @@ my $tilma_host = "https://" . ($staging ? "tilma.staging.mysociety.org" : "tilma
http_options:
params:
layer: designs_wasteContainers
-- filter_key: ''
+- name: 'bristol_property'
+  filter_key: …
```
=> [Bristol] Only use message controller on one layer.

perllib/FixMyStreet/Cobrand/Gloucester.pm, t/cobrand/gloucester.t
Removing anonymous reporting from code so this can be managed via admin on a category by category basis.
=> [Gloucester] Remove global anonymous reporting option

web/cobrands/fixmystreet-uk-councils/assets.js
Adds generic function for dealing with two layers that are combined to work as one in terms of selecting an asset
https://3.basecamp.com/4020879/buckets/38208405/todos/8726635870#__recording_8730302024
https://github.com/mysociety/societyworks/issues/4992
Please check same branch on the servers too
=> [Gloucester][FMS] Add combined layer function

perllib/FixMyStreet/Cobrand/Gloucester.pm
Gloucester have asked for some of the county categories to be hidden on their cobrand.
This hides any category that starts with "Ash Tree located on" (as there are two county categories on the live site like that), as well as all of the "Noxious weeds" categories.
I couldn't see an easy way to hide based on the parent, so if more Noxious weeds categories are added in the future, they'll need to be added to this list.
For [this Basecamp todo](https://3.basecamp.com/4020879/buckets/38208405/todos/8663336750).
=> [Gloucester] Hide some county categories

perllib/FixMyStreet/Cobrand/Merton/Waste.pm, t/app/controller/waste_merton.t
Textiles service being removed at request of Council though batteries service will continue.
https://mysocietysupport.freshdesk.com/a/tickets/5433
=> [Merton] Remove textiles as a service

web/cobrands/fixmystreet-uk-councils/assets.js
Server config is updated for the two layers (streets with plots, and plots with streets) to use fixmystreet.assets.gloucester.street_or_plot_found and not found instead of the `combined`  functions, and the `usrn` configuration removed. [skip changelog]
=> [Gloucester] Update itemId attribute from either street/plot layer.

t/app/controller/waste_merton.t, t/app/controller/waste_merton_bulky.t, templates/web/merton/waste/_service_missed.html
"Report a missed food waste collection" instead of "Report a food waste collection as missed" etc.
Fixes FD-5637
=> [Merton] Update missed collection link test

perllib/FixMyStreet/Cobrand/Gloucester.pm, t/cobrand/gloucester.t
Use the lookup site code functionality to get the relevant Alloy ID for the nearest feature if it wasn't selected during report creation.
For https://3.basecamp.com/4020879/buckets/38208405/todos/8726231700
=> [Gloucester] Lookup Alloy code before sending over Open311

web/cobrands/sass/_report_list.scss
Fixes: https://github.com/mysociety/societyworks/issues/5077
Because the z-index number was quite low, the element didn't have the right order compared with the other elements on the page. This was causing the drawer to be opened, but its contents were behind the map.
=> Increased z-index of .mobile-filters-active

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Roles/Cobrand/AccessPaySuite.pm, perllib/Integrations/AccessPaySuite.pm, t/app/controller/waste_bexley_garden.t, templates/web/base/waste/garden/modify.html, web/cobrands/bexley/waste.js, web/js/waste.js
Adds code for taking a one-off payment to cover any in-year difference in cost, as well as code for changing the amount of the original contract for future payments.
For https://github.com/mysociety/societyworks/issues/4796
Part of https://github.com/mysociety/fixmystreet/pull/5374
The live API doesn't have the "No Frequency - AD-HOC Payments" schedule, it's only in test, which you can see with the following calls:
```
$ curl -L -g -X GET 'https://playpen.accesspaysuite.com/api/v3/client/APIRTM/schedules' -H "apiKey: $APS_TEST_API_KEY"
$ curl -L -g -X GET 'https://ddcms.accesspaysuite.com/api/v3/client/LBBEX/schedules' -H "apiKey: $APS_LIVE_API_KEY"
```
You can also get the schedule ID you need for the `dd_adhoc_schedule_id` config setting from that playpen call.
(Added 08/07/25:)
=> [Bexley] GGW amend DD amount

.cypress/cypress/integration/northumberland.js, .cypress/cypress/integration/simple_spec.js, bin/browser-tests, perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/Cobrand/Zurich.pm, perllib/FixMyStreet/Map/Base.pm, perllib/FixMyStreet/Map/OSM.pm, t/cobrand/northumberland.t, t/map/fms.t, templates/web/base/maps/fms.html, templates/web/base/maps/google-ol.html, templates/web/base/maps/openlayers.html, templates/web/base/maps/osm.html, templates/web/zurich/maps/zurich.html, web/cobrands/fixmystreet/map.js, web/js/map-os-bng.js
Tidying up a little now Bing aerial has gone, but hopefully then only changing Northumberland and nothing else.
The tilma set up is already there, added to the mapcache config in servers (this relies on two files existing in /data/vhost/tilma.../layers/northumberland/ called watermark.png and aerial.xml which contains the actual endpoint and metadata etc).
The aerial.xml file was generated following the instructions at https://mapserver.org/de/mapcache/sources.html#wmts-sources
The watermark was generated by me personally.
=> [Northumberland] Add aerial mapping layer.

templates/web/base/waste/bulky/items.html, web/cobrands/sass/_waste.scss
Fixes: https://github.com/mysociety/societyworks/issues/5079
This PR adds:
- `govuk-button--secondary` to "add item" button
- `govuk-button--warning` to "Delete item"
- Deleted `margin-top` for "Delete item". `govuk-form-group` which is the previous element already has `margin-bottom`
- Added extra vertical margin to `hr` elements to improve distance between the items to collect. 
https://github.com/user-attachments/assets/33f7cb57-7653-4ab5-a0dc-5304a7852aea
https://github.com/user-attachments/assets/237da0bf-cbfa-4969-b184-781c3d13e8cf
=> "Add items for collection": layout and styling improvements

perllib/FixMyStreet/App/Controller/Offline.pm, templates/web/base/common_header_tags.html, templates/web/base/waste/bin_days_sidebar.html, templates/web/fixmystreet-uk-councils/about/waste-web-app.html, templates/web/fixmystreet-uk-councils/about/web-app.html
- Adds new `/about/waste-web-app` page with WW-tailored instructions
- Updates web manifest used on property pages to set `start_url` to the property page
- Adds link to new help page from property page and allows PWA installation for that property from there
For https://github.com/mysociety/societyworks/issues/4962
For https://github.com/mysociety/societyworks/issues/3993
=> [Waste] PWA installation improvements

t/app/controller/waste_merton.t, templates/web/merton/waste/_more_services_sidebar.html
Due to the new Echo setup we need to have a separate form for updating the crew notes after an assisted collection has been added or updated on a property.
See `b968f7e04741d16328565e6841c0eae025099957` in the servers repo for the related changes there.
Fixes https://github.com/mysociety/societyworks/issues/5152
=> [Merton] Add separate form for changing assisted collection Crew Notes

CHANGELOG.md, perllib/FixMyStreet/Queue/Item/Report.pm, t/sendreport/two-tier/email-and-open311.t
Some senders call `discard_changes()` within their `send()` method, which results in the `send_method_used` change being overwritten rather than appended to. The end result of this is that in some cases updates aren't being sent via Open311 because the `send_method_used` ends up as `Email`.
This change ensures that `send_method_used` is persisted between sender calls, so in cases with multiple senders it correctly ends up as `Email,Open311` or similar.
Fixes https://github.com/mysociety/societyworks/issues/5146
Relates to FD-5945
=> Persist send_method_used immediately during report sending

templates/web/base/admin/bodies/_category_field.html
When a cobrand is setup to use a display name its sometimes still useful to have a way to change the category name.
This change adds a form field for superusers to allow them to update the category name as well as the display name on these cobrands.
Should make tickets like FD-5943 possible to fix from the admin rather than having to use the DB console.
=> Add superuser category editing for display name cobrands

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/App/Controller/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Billing.pm, perllib/FixMyStreet/Roles/Cobrand/Waste.pm, templates/web/base/waste/garden/_payment_method.html
This adds a 'cash' payment option for Merton at their request (fixes https://github.com/mysociety/societyworks/issues/5099), and takes the opportunity to fix some historical cruft to do with payment references (fixes https://github.com/mysociety/societyworks/issues/4023 - see comment there for details as to what's changed).
It also stops payment options being shown during a bulky amendment if there's no payment to be taken, and removes a duplicate payment method display in the admin. [skip changelog]
=> [Merton] Adding a cash option (and tidying up payment references)
