mysociety/fixmystreet

CHANGELOG.md, web/js/duplicates.js, web/js/map-OpenLayers.js
Fixes https://github.com/mysociety/societyworks/issues/2786
=> Highlight pin on sidebar focus as well as hover.

templates/web/fixamingata/about/accessibility.html, templates/web/fixamingata/about/council.html, templates/web/fixamingata/about/faq-sv.html
A few changes done in our cobrand that hadn't been delivered to upstream yet.
=> [FixaMinGata] latest updates to the FixaMinGata cobrand

web/cobrands/oxfordshire/layout.scss
=> [Oxfordshire] Fix vertical scroll bar being shown.

templates/web/base/maps/_compass.html, templates/web/base/report/form/user.html, templates/web/hackney/report/form/user.html, templates/web/westminster/report/form/user.html, web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss, web/cobrands/zurich/base.scss, web/cobrands/zurich/layout.scss
Fixes https://github.com/mysociety/societyworks/issues/2802
=> Give noscript compass different IDs.

.github/pull_request_template.md
Added a question to the text that appears in this space. [skip changelog]
=> Memo in new PR text to look out for extra work for fixmystreet.com implied by cobrand changes

bin/send-daemon, perllib/FixMyStreet/Script/SendDaemon.pm, t/script/send-daemon.t
Fixes https://github.com/mysociety/fixmystreet/issues/3228
=> Fix stuck report after mapit nearest call fails

.cypress/cypress/integration/buckinghamshire.js, bin/fixmystreet.com/fixture, web/cobrands/buckinghamshire/assets.js, web/cobrands/cheshireeast/assets.js, web/cobrands/fixmystreet/assets.js
Fixes https://github.com/mysociety/societyworks/issues/2662.
Fixes https://github.com/mysociety/societyworks/issues/2680.
=> [Cheshire East] [Bucks] Fix non-road reporting

bin/open311-populate-service-list, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Roles/Open311Multi.pm, perllib/Open311.pm, t/cobrand/oxfordshire.t, t/open311/post-service-request-updates.t, templates/web/fixmystreet-uk-councils/footer_extra_js_base.html, templates/web/hackney/footer_extra_js.html, templates/web/northamptonshire/footer_extra_js.html, templates/web/oxfordshire/footer_extra_js.html, templates/web/oxfordshire/report/_main_sent_info.html, web/cobrands/fixmystreet-uk-councils/alloy.js, web/cobrands/hackney/assets.js, web/cobrands/northamptonshire/assets.js, web/cobrands/oxfordshire/assets.js
For sending street lighting reports to Alloy, and displaying existing defects on the map.
=> [Oxfordshire] Alloy integration

templates/email/buckinghamshire/other-reported.html, templates/email/buckinghamshire/other-reported.txt
For https://mysocietysupport.freshdesk.com/a/tickets/1721
=> [Bucks] Remove COVID message from logged emails

t/cobrand/oxfordshire.t, templates/web/fixmystreet.com/report/_oxfordshire_ref.html, templates/web/oxfordshire/report/_council_sent_info.html
=> [Oxfordshire] Show Alloy asset ID as well as WDM.

templates/web/fixmystreet-uk-councils/about/privacy.html, templates/web/merton/about/googlecookies.html, web/cobrands/merton/base.scss
=> [Merton] add Google cookies info table to privacy page

perllib/FixMyStreet/Map/Northamptonshire.pm
Northampton to check a new default zoom of 9
https://mysocietysupport.freshdesk.com/a/tickets/1507
=> [Northampton] Increase default zoom

docker/compose-dev, docker/docker-compose-dev.yml
FIxes Linux compatibility and tests.
=> Docker compose fixes

t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_bin_day_sidebar_extra.html, templates/web/peterborough/waste/_more_services_sidebar.html
For https://3.basecamp.com/4020879/buckets/19439943/todos/4540156988
=> [Peterborough] Always show ‘Request more food bags’ link

templates/web/buckinghamshire/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html, web/cobrands/buckinghamshire/assets.js
Fixes https://github.com/mysociety/societyworks/issues/2804
https://user-images.githubusercontent.com/22996/146956989-db8ae639-cdbe-4dad-be8b-9edebabce404.mov
=> Bucks add car park layer

templates/web/shropshire/report/update/after_update.html
https://mysocietysupport.freshdesk.com/a/tickets/1773
=> [Shropshire] Include report tips after update form

perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/Integrations/Echo.pm, t/cobrand/bromley.t
Fixes https://github.com/mysociety/societyworks/issues/2462 [skip changelog]
=> [Bromley] Only one report per collection

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
=> [Buckinghamshire] On native app, put car parks group at end.

perllib/FixMyStreet/Cobrand/Merton.pm, t/cobrand/merton.t, web/cobrands/merton/assets.js
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1758
=> [Merton] Exclude type 3 USRN streets.

templates/web/merton/tracking_code.html
cf. https://developers.google.com/tag-platform/tag-manager/web/csp
fixes https://mysocietysupport.freshdesk.com/a/tickets/1718
fixes mysociety/societyworks#2628
(hopefully!)
=> [Merton] Updated Google Tag Manager container code to nonce-aware version

perllib/FixMyStreet/Cobrand/Hackney.pm, t/cobrand/hackney.t
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1601
=> [Hackney] Include time in update emails.

web/cobrands/fixmystreet/fixmystreet.js
=> Hide side form error if we now have good data.

perllib/FixMyStreet/Cobrand/Oxfordshire.pm, perllib/FixMyStreet/DB/Result/Problem.pm, t/cobrand/oxfordshire.t
Fixes https://github.com/mysociety/societyworks/issues/2856 [skip changelog]
=> [Oxfordshire] Use Open311 contact for update send.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
Not removals. Fixes https://mysocietysupport.freshdesk.com/a/tickets/1809 [skip changelog]
=> [Peterborough] Check for open missed collections.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/services.html
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1814
=> [Peterborough] Prevent problem/request on black bin when large bin request open

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1825
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1819 
Fixes https://mysocietysupport.freshdesk.com/a/tickets/1827
=> [Peterborough] more dupe prevention

perllib/FixMyStreet/Cobrand/Merton.pm, t/cobrand/merton.t
=> [Merton] Spot duplicate endpoint messages.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t
We added a new car parks asset layer in https://github.com/mysociety/fixmystreet/pull/3726 which prevented car park reports from being created outside car parks. However that change relied on JavaScript to work, which means people using the native app and people without JavaScript enabled were able to create car park reports anywhere.
This change adds a server-side lookup to ensure the report is in a car park, returning an error if it's not.
- I put the radius at 50m, does this seem about right?
- I had to manually escape the `$filter` parameter, explanation in a code comment. Is there a cleaner way to do that?
Fixes https://github.com/mysociety/societyworks/issues/2804
=> [Buckinghamshire] Server-side checks for car park reports

docs/install/manual-install.md
=> Update manual install docs with Mac-specific issues

.cypress/cypress/integration/buckinghamshire.js, bin/buckinghamshire/add-parish-categories, bin/fixmystreet.com/fixture, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/DB/Result/Contact.pm, t/Mock/MapIt.pm, t/app/model/contact.t, t/cobrand/bucks.t, templates/web/base/report/new/category_extras.html, templates/web/buckinghamshire/footer_extra_js.html, templates/web/buckinghamshire/report/new/_category_extras_header.html, web/cobrands/buckinghamshire/js.js
Route grass cutting reports to the parish if the speed limit is 30mph or less, otherwise to the council. This is based on the answer to an extra question set on the parishes grass cutting contact which asks the user what the speed limit of the road is.
I've also made a couple of tweaks to the parish categories script to allow updating existing contacts as I've made some change to the extra question on the grass cutting category and want that to propagate to the existing staging categories.
Fixes https://github.com/mysociety/societyworks/issues/2812
=> [Buckinghamshire] Routing for parish grass cutting categories

web/js/map-OpenLayers.js
With Ctrl held down, move five times less. And reduce the overall movement. [skip changelog]
=> Enable more precise keyboard pin movement.

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/Mock/MapIt.pm, t/cobrand/fixmystreet.t, web/cobrands/highways/assets.js, web/cobrands/highwaysengland/assets.js
https://github.com/mysociety/societyworks/issues/1268
* Use new layer to see if Highway England responsible for litter on A-road
* If they are responsible make sure HE Litter category available
* If they are not responsible make sure council litter category available
* Also Switch to EPSG:4326 for site code lookup in report sending as
these changes break test otherwise
=> [Highways England] Fix litter responsibilties for HE

CHANGELOG.md, cpanfile, cpanfile.snapshot
=> Upgrade libwww.

perllib/FixMyStreet/Cobrand/Merton.pm
Cut-off: 2021-12-31
Report age: 3 months
for mysociety/societyworks#2616
=> [Merton] Set cut_off_date and report_age.

web/cobrands/buckinghamshire/assets.js, web/cobrands/oxfordshire/assets.js
And include channels too. 
Also fixes https://github.com/mysociety/societyworks/issues/2698 I think
=> [Oxfordshire] Show drainage last clean dates

CHANGELOG.md, templates/web/base/js/translation_strings.html, web/cobrands/fixmystreet/fixmystreet.js
Fixes https://github.com/mysociety/societyworks/issues/2941
=> Update document title on page transition.

.cypress/cypress/integration/merton.js, bin/browser-tests, bin/fixmystreet.com/fixture, perllib/FixMyStreet/Cobrand/Merton.pm, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js
fixes mysociety/societyworks#2823
=> [Merton] character limit on extra question fields

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
For https://mysocietysupport.freshdesk.com/a/tickets/1904
Example address in PE6 9AJ
=> [Peterborough] Only include in service.

t/cobrand/zurich.t, templates/web/zurich/admin/reports/edit.html
For https://mysocietysupport.freshdesk.com/a/tickets/1931
=> [Zürich] Don’t allow DMs to provide public update on internal reports

web/cobrands/peterborough/waste.js
For https://mysocietysupport.freshdesk.com/a/tickets/1913
=> [Peterborough] Don’t enable service checkboxes that start disabled

perllib/FixMyStreet/Cobrand/Thamesmead.pm, t/cobrand/thamesmead.t
Add cobrand file for Peabody/Thamesmead cobrand
https://github.com/mysociety/societyworks/issues/2923
=> [Thamesmead] Add Thamesmead cobrand file

bin/fixmystreet.com/fixture, templates/web/lincolnshire/report/new/_form_labels.html
Helpdesk request [#1864 ](https://mysocietysupport.freshdesk.com/a/tickets/1864) to change default report title text
=> [Lincs] Change 'title' field of reports

templates/web/fixmystreet-uk-councils/about/privacy.html
Closes https://mysocietysupport.freshdesk.com/a/tickets/2018.
- [ x] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ x] Will cobrand-specific changes require additional work to ensure consistent behaviour on www.fixmystreet.com?
=> [Shropshire] Update privacy statement

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Billing.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/Integrations/SCP.pm, t/app/controller/waste.t, templates/web/base/waste/bin_days.html, templates/web/base/waste/garden/modify_summary.html, templates/web/base/waste/garden/renew.html, templates/web/base/waste/garden/renew_summary.html, templates/web/base/waste/garden/subscribe_details.html, templates/web/base/waste/garden/subscribe_summary.html
Mostly the changes needed for working CC flow, with couple other small changes. [skip changelog]
Needs a fix for missing payment_method when staff-CNP flow is used (think just needs a default, don't think that has any other effect).
For https://github.com/mysociety/societyworks/issues/3006 (bar finding out if name needed) and https://github.com/mysociety/societyworks/issues/3001
=> [Kingston] Credit card flow changes

perllib/FixMyStreet/Cobrand/Oxfordshire.pm, t/cobrand/oxfordshire.t
For https://github.com/mysociety/societyworks/issues/2940 [skip changelog]
Links with https://github.com/mysociety/open311-adapter/pull/216
=> [Oxfordshire] Include role in sent extra data.

perllib/FixMyStreet/Cobrand/Thamesmead.pm
* Adds cobrand method to return link to Thamesmead's own privacy policy
https://github.com/mysociety/societyworks/issues/2928
=> [Thamesmead] Adds link to Thamesmead's own privacy policy

perllib/FixMyStreet/Cobrand/Thamesmead.pm
Adds admin permission based on UK Councils
Adds body based on Highways England
Adds users_restrictions imported from UK Councils
=> [Thamesmead] Add admin permissions

templates/web/thamesmead/before_wrapper.html
Replaces gtag from another cobrand with the correct one from Thamesmead
=> [Thamesmead] Change gtag to Thamesmead gtag

web/cobrands/bristol/assets.js
Fix issue breaking tests with stylemap
=> [Bristol] Fix broken stylemap options

perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston.t
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/3008
=> [Kingston] Allow editing of renewal bin count.

bin/oxfordshire/update_district_category_notices
For https://github.com/mysociety/societyworks/issues/2877
(There's an example data file at `~davea/district_categories.json` on the staging server.)
=> [Oxfordshire] Add script for one-off updating of district categories

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Page/Simple.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Renew.pm, perllib/FixMyStreet/App/Form/Wizard.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/CobrandPay360.pm, t/app/controller/waste_kingston.t, templates/web/base/waste/garden/sacks/renew.html, templates/web/base/waste/garden/sacks/renew_summary.html, templates/web/base/waste/garden/sacks/subscribe_details.html, templates/web/base/waste/garden/sacks/subscribe_summary.html, templates/web/base/waste/garden/subscribe_details.html, templates/web/kingston/waste/garden/sacks/subscribe_intro.html, templates/web/kingston/waste/services.html
Fixes https://github.com/mysociety/societyworks/issues/3016 - first commit to enable a way to do this, not sure if there's a nicer way I haven't thought of!
Then lookup for https://github.com/mysociety/societyworks/issues/3018 and then code to hopefully fix https://github.com/mysociety/societyworks/issues/3019 and https://github.com/mysociety/societyworks/issues/3022 and https://github.com/mysociety/societyworks/issues/3020 
=> [Kingston] waste sacks

templates/web/base/tokens/confirm_problem.html, templates/web/thamesmead/tokens/_confirm_problem.html, templates/web/thamesmead/tokens/_confirm_problem_council_id.html
* Adds functionality for using fragment _confirmed_problem.html
* Adds _confirmed_problem.html with Thamesmead customisation
=> [Thamesmead] Add template for confirmed report message

templates/web/cheshireeast/about/faq-en-gb.html
For https://mysocietysupport.freshdesk.com/a/tickets/2036
=> [Cheshire East] Update FAQ content

web/cobrands/bromley/assets.js
https://mysocietysupport.freshdesk.com/a/tickets/1945
=> [Bromley] Add drains layer.

perllib/FixMyStreet/Cobrand/Thamesmead.pm, templates/web/thamesmead/about/faq-en-gb.html, templates/web/thamesmead/alert/_index_text.html, templates/web/thamesmead/around/intro.html, templates/web/thamesmead/contact/blurb.html, templates/web/thamesmead/index-steps.html
Make text changes based on feedback from client
https://3.basecamp.com/4020879/buckets/26382066/todos/4916971998
=> [Thamesmead] Further editorial changes

perllib/FixMyStreet/Cobrand/Hackney.pm, t/cobrand/hackney.t, t/open311/post-service-request-updates.t, t/sendreport/open311.t, web/cobrands/hackney/assets.js
Some changes/improvements to support the Alloy environmental services integration launch.
=> [Hackney] Alloy environmental services integration

cpanfile, cpanfile.snapshot, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/Bottomline.pm, perllib/FixMyStreet/Roles/CobrandPay360.pm, perllib/FixMyStreet/Roles/DDProcessor.pm, perllib/Integrations/Bottomline.pm, t/cobrand/bromley.t, t/cobrand/kingston.t
This adds a Bottomline integration and code to process new, renewed and cancelled direct debit transactions.
=> Kingston waste dd confirm 3011

web/cobrands/thamesmead/cookies.js
Wrong code in gtag config replaced
=> [Thamesmead] Correct gtag code

templates/web/centralbedfordshire/report/new/roads_message.html, web/cobrands/centralbedfordshire/assets.js
For https://mysocietysupport.freshdesk.com/a/tickets/2038
=> [Central Beds] Allow trees reports to be made off roads

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Purchase.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Renew.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston.t, templates/web/base/waste/garden/sacks/modify.html, templates/web/base/waste/garden/sacks/modify_confirmed.html, templates/web/base/waste/garden/sacks/modify_summary.html, templates/web/base/waste/garden/sacks/renew.html, templates/web/base/waste/garden/sacks/subscribe_details.html, templates/web/kingston/waste/garden/renew_sacks_desc.html, templates/web/kingston/waste/garden/subscribe_details_sacks_desc.html, templates/web/kingston/waste/services.html
Fixes https://github.com/mysociety/societyworks/issues/3021 [skip changelog]
I did it as part of the garden 'modify' flow, which mostly worked, if statement a bit big in the controller maybe but couldn't think of anything much better.
=> [Kingston] Purchase of more sacks

perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/thamesmead.t
Categories were only filtered out on FMS site
Now filters Thamesmead categories out of all UK Council sites
=> [Thamesmead] Remove Thamesmead categories from UK Council sites

templates/web/bristol/around/intro.html, web/cobrands/bristol/assets.js
- Adds park layer
- Changes category for gullies
- Adds Trees layer
- Adds bins layer
- Adds noticeboard/signs layer
- Edits for category triggers for above layers
https://mysocietysupport.freshdesk.com/a/tickets/865
[Fix My Street Categories.xlsx](https://github.com/mysociety/fixmystreet/files/7985167/Fix.My.Street.Categories.xlsx)
=> [Bristol] Adds parks and other layers

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_kingston.t, templates/web/base/waste/dd.html, templates/web/kingston/waste/dd_form.html
=> [Kingston] include admin fee in direct debit first payment

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/Bottomline.pm, perllib/FixMyStreet/Roles/CobrandPay360.pm, perllib/FixMyStreet/Roles/DDProcessor.pm, perllib/Integrations/Bottomline.pm, t/app/controller/waste.t, t/app/controller/waste_kingston.t, t/cobrand/kingston.t
=> Kingston waste dd one off payments

templates/web/thamesmead/about/faq-en-gb.html, templates/web/thamesmead/index-steps.html
Part of https://github.com/mysociety/societyworks/issues/3055
=> [Thamesmead] Update copy on homepage and FAQ page

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Billing.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Kingston/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Kingston/Subscribe.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston.t, templates/web/base/waste/garden/renew.html, templates/web/base/waste/garden/sacks/renew.html, templates/web/base/waste/garden/sacks/subscribe_details.html, templates/web/base/waste/garden/subscribe_details.html, templates/web/kingston/waste/garden/renew_bin_desc.html, templates/web/kingston/waste/garden/renew_sacks_desc.html, templates/web/kingston/waste/garden/subscribe_confirm.html, templates/web/kingston/waste/garden/subscribe_details_sacks_desc.html, templates/web/kingston/waste/garden/subscribe_existing_bin_desc.html, templates/web/kingston/waste/garden/subscribe_intro.html, templates/web/kingston/waste/services.html
Various text changes (though more changes to them have been made since), cheque payment option, payment method for staff to show that field, end date 2023-03 thing, check for service unit existing to allow garden waste [skip changelog]
=> [Kingston] Text changes &c

perllib/FixMyStreet/App/Form/Waste/Billing.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/cobrand/kingston.t, templates/web/base/govuk/fields.html, templates/web/base/waste/garden/_payment_method.html, templates/web/base/waste/garden/renew_summary.html, templates/web/base/waste/garden/sacks/renew_summary.html, templates/web/base/waste/garden/sacks/subscribe_summary.html, templates/web/base/waste/garden/subscribe_summary.html
=> [Kingston] Add option to hide DD and prevent action scheduled updates

perllib/FixMyStreet/Cobrand/Greenwich.pm, t/cobrand/greenwich.t
For https://mysocietysupport.freshdesk.com/a/tickets/1951
=> [Greenwich] Use more concise value for closest_address Open311 param

perllib/FixMyStreet/Cobrand/Bristol.pm
Remove stripping of groups from Bristol open311
=> [Bristol] Re-enable Open311 category groups

perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston.t, templates/web/kingston/waste/dd_form.html
=> [Kingston] use different DD form for staff users

templates/web/buckinghamshire/report/new/roads_message.html, web/cobrands/buckinghamshire/assets.js
Request through helpdesk to make lampost selection required
https://mysocietysupport.freshdesk.com/a/tickets/2133
=> [Bucks] Force selection of lamp from asset layer

templates/web/bromley/header_logo.html
Helpdesk request to update link for the logo
https://mysocietysupport.freshdesk.com/a/tickets/2136
=> [Bromley] Update logo link

bin/buckinghamshire/add-parish-categories
Add an extra question to the fly posting category.
=> [Buckinghamshire] Add extra question to parish Fly posting category

templates/email/kingston/other-reported.html, templates/web/kingston/waste/garden/subscribe_intro.html
=> Kingston waste text changes

perllib/Integrations/Bottomline.pm, t/app/controller/waste_kingston.t
Various small fixes to the bottomline API, plus an extra method to get a mandate by reference.
=> Kingston bottomline api fixes

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston.t, templates/web/base/waste/dd_error.html
If not show an error page with a retry option.
=> [Kingston] check if direct debit verification was applied and passed

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
=> [Bexley] Update Christmas concessionary day.

t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_more_services_sidebar.html
Remove link to food bags as currently out of stock
=> [Peterborough] suspend food bags temporarily

perllib/FixMyStreet/Cobrand/Hampshire.pm, web/cobrands/tfl/assets.js
* Fixes two issues where calling staging mapserver instead of live
=> [Hampshire][TfL] Update tilma links to point to live

perllib/FixMyStreet/App.pm, perllib/FixMyStreet/App/Controller/Open311.pm, perllib/FixMyStreet/App/Controller/Reports.pm, perllib/FixMyStreet/Cobrand/Zurich.pm, t/cobrand/zurich.t, web/js/map-OpenLayers.js
Fixes FD-2194. Fixes FD-2203. Fixes a couple of other bugs in that area that I spotted whilst I was there. [skip changelog]
=> [Zurich] Missing body error and other bugs

perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/cobrand/bromley.t, templates/web/base/waste/bin_days.html, templates/web/bromley/waste/services.html, templates/web/kingston/waste/services.html
=> [Bromley] task type and renewal messages

perllib/FixMyStreet/Cobrand/Lincolnshire.pm
=> [Lincolnshire] Open reports on map by default.

.cypress/cypress/integration/staff.js, CHANGELOG.md, t/app/controller/report_as_other.t, templates/web/base/report/new/form_user_loggedin.html, templates/web/base/report/update/form_user_loggedin.html, web/cobrands/fixmystreet/staff.js
=> Use the default_to_body permission also when creating updates.

perllib/Integrations/SCP.pm
=> [Waste] Add syslogging of SCP calls.

perllib/Open311/UpdatesBase.pm
Combine the two checks so that the incoming comment is hidden unless there’s a text change, a photo, or a state change. This should fix a warning when either comment may lack a problem_state. [skip changelog]
=> [Open311] Tweak to latest update check.

templates/email/zurich/problem-confirm.txt
For https://github.com/mysociety/societyworks/issues/3103
For FD-2232
=> [Zürich] Update problem-confirm template with new wording

perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston.t, templates/web/kingston/waste/services.html
Struan already reviewed this not in PR.
=> [Kingston] Remove overdue notice display.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, templates/web/base/admin/triage/_inspect.html, templates/web/base/report/inspect/public_update.html, templates/web/buckinghamshire/report/inspect.html, web/cobrands/fixmystreet/staff.js
Fixes https://github.com/mysociety/societyworks/issues/2819. Fixes https://github.com/mysociety/societyworks/issues/2821 (except possibly notification but that can be returned to, they say they're happy as-is)
=> [Bucks] Add triage reports page

perllib/FixMyStreet/Cobrand/Kingston.pm
As [requested](https://3.basecamp.com/4020879/buckets/26876928/todos/5153912332) by client.
=> [Kingston] End early August 2022 renewals in March 2023

t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_more_services_sidebar.html
This reverts commit 6e8a1382a9a1b90c25050c75f7ef14a8ad95dbf0.
Client request to reinstate food bag link
https://mysocietysupport.freshdesk.com/a/tickets/2281
=> [Peterborough] Revert "[Peterborough] suspend food bags temporarily"

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
=> [Bexley] Send P1 emails for offensive graffiti reports

t/cobrand/tfl.t, templates/email/tfl/submit.html, templates/email/tfl/submit.txt
=> [TfL] Include bike number in Abandoned Santander Cycle report emails

.cypress/cypress/integration/merton.js, perllib/FixMyStreet/Cobrand/Merton.pm, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js
=> [Merton] Adjust extra question max lengths.

perllib/FixMyStreet/App/Controller/Moderate.pm, t/app/controller/moderate.t
Fixes https://github.com/mysociety/fixmystreet/issues/3330. [skip changelog]
=> Do not send moderation emails to anon accounts.

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Queue/Item/Report.pm, t/app/controller/report_new_update.t
=> Add initial update on report sending, not creation

web/cobrands/lincolnshire/assets.js
This was on staging for ages, I forgot to open PR for it. [skip changelog]
=> [Lincolnshire] Use staging tilma on staging site.

perllib/FixMyStreet/App/Controller/Admin/Reports.pm, t/app/controller/waste.t, templates/web/base/admin/reports/_edit_waste.html
Fixes https://github.com/mysociety/societyworks/issues/3168 [skip changelog]
=> [Waste] Include contributed by in report admin.

perllib/FixMyStreet/Cobrand/Lincolnshire.pm
Lincolnshire have requested that the map be more zoomed in by default.
Fixes https://github.com/mysociety/societyworks/issues/3173
=> [Lincolnshire] Change default_map_zoom

CHANGELOG.md, templates/web/base/questionnaire/index.html
=> Add label to questionnaire textarea.

perllib/FixMyStreet/App/Controller/Waste.pm
Fixes https://github.com/mysociety/societyworks/issues/2897 [skip changelog]
=> [Waste] Tweak wording of property limit message.

CHANGELOG.md, bin/csv-export, perllib/FixMyStreet/App/Controller/Admin/Users.pm, perllib/FixMyStreet/App/Controller/Dashboard.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Reporting.pm, t/app/controller/dashboard.t, templates/web/base/dashboard/index.html
Fixes https://github.com/mysociety/societyworks/issues/2446
=> Add role filter to dashboard interface.

t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_more_services_sidebar.html
Fixes https://github.com/mysociety/societyworks/issues/3026 [skip changelog]
=> [Peterborough] No food bags link if open request.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/cobrand/bucks.t
For https://mysocietysupport.freshdesk.com/a/tickets/2353 - agreed doesn't work well.
=> [Buckinghamshire] Do not change parish report state after sending.

perllib/FixMyStreet/Script/UpdateAllReports.pm, t/cobrand/thamesmead.t
* Removes Thamesmead from best performing council table as not a council
* Removes Thamesmead categories from top five stats
=> [Thamesmead] Stats on landing page to reflect Thamesmead only reports

web/cobrands/thamesmead/assets.js
Using Thamesmead wfs feed for grass, hardsurfaces, planting and water
https://github.com/mysociety/societyworks/issues/3068
=> [Thamesmead] Replace asset shapefiles with WFS feed

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/Cobrand/Default.pm, t/app/controller/waste_peterborough.t, templates/web/base/admin/waste/edit.html, templates/web/base/admin/waste/index.html, web/cobrands/sass/_admin.scss
This is a very basic JSON-in-a-text-area form (there is some validation at least) and will be turned into a fully-featured and more user friendly editor later on.
For https://github.com/mysociety/societyworks/issues/2916
=> [Bulky Goods] Add JSON editor in admin for configuring WasteWorks parameters

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Request.pm, perllib/FixMyStreet/App/Form/Waste/Request/Bromley.pm, perllib/FixMyStreet/App/Form/Waste/Request/Peterborough.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
=> [Waste] Treat request flows more similarly.

web/cobrands/isleofwight/assets.js
Switched to OS Maps in 361957c68, but the resolutions weren't updated at that time. [skip changelog]
=> [Isle of Wight] Fix max resolutions.

t/app/controller/admin/manifesttheme.t, t/cobrand/tfl.t, t/email/incoming.t, templates/email/tfl/reply-autoresponse, templates/email/tfl/signature.txt, templates/email/tfl/site-name.txt, templates/web/tfl/about/faq-en-gb.html, templates/web/tfl/contact/_heading.html, templates/web/tfl/site-name.html
Fixes FD-2393. [skip changelog]
=> [TfL] Consistent site name.

templates/web/cheshireeast/contact/_footer.html, templates/web/fixmystreet-uk-councils/about/privacy.html, web/js/contact.js
Fixes FD-2000. [skip changelog]
=> [Cheshire East] Tweaks to abuse form

web/cobrands/bathnes/assets.js
=> [BathNES] Add litter to Curo categories.

perllib/FixMyStreet/App/Form/Waste/AboutYou.pm, perllib/FixMyStreet/App/Form/Waste/Billing.pm, templates/web/base/govuk/fields.html
Fixes https://github.com/mysociety/societyworks/issues/3133 [skip changelog]
=> Waste error links

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/SCP.pm, t/Mock/MapIt.pm, t/app/controller/waste_sutton_garden.t, templates/web/base/waste/cc.html, templates/web/sutton/waste/cc_form.html, templates/web/sutton/waste/pay.html, templates/web/sutton/waste/services.html
Add credit card processing for sutton waste integration.
Also includes staff payment.
Fixes https://github.com/mysociety/societyworks/issues/3230
Fixes https://github.com/mysociety/societyworks/issues/3144
=> [Sutton] Waste credit card integration

.cypress/cypress/integration/tfl.js, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/Hackney.pm, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, perllib/FixMyStreet/DB/Result/Problem.pm
Fixes https://github.com/mysociety/societyworks/issues/3202
Fixes https://github.com/mysociety/societyworks/issues/2703
=> [Hackney] Update to working server.

perllib/FixMyStreet/Cobrand/TfL.pm, web/cobrands/merton/assets.js
Connects https://github.com/mysociety/societyworks/issues/3070 [skip changelog]
=> [Merton] Add street light asset layer.

bin/buckinghamshire/add-parish-categories, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t, templates/web/buckinghamshire/report/new/_category_extras_header.html, web/cobrands/buckinghamshire/assets.js
For https://mysocietysupport.freshdesk.com/a/tickets/2429
=> [Buckinghamshire] Use speed limit layer to route all parish categories

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, t/cobrand/highwaysengland.t, templates/email/highwaysengland/submit.html, templates/email/highwaysengland/submit.txt, templates/web/base/report/form/user.html, templates/web/base/report/form/user_loggedout_by_email.html, templates/web/base/report/form/user_loggedout_by_email_password.html, templates/web/base/report/inspect/information.html, templates/web/base/report/new/duplicate_suggestions.html, templates/web/bromley/report/form/user_loggedout_by_email_password.html, templates/web/hackney/report/form/user.html, templates/web/highwaysengland/auth/form_extra.html, templates/web/highwaysengland/report/form/private_details.html, templates/web/highwaysengland/report/form/user.html, templates/web/highwaysengland/report/new/duplicates_message.html, templates/web/highwaysengland/tokens/confirm_problem.html, templates/web/westminster/report/form/user.html, web/js/duplicates.js
Fixes https://github.com/mysociety/societyworks/issues/2291 [skip changelog]
=> [National Highways] Users can give contact details

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/header.html, web/cobrands/sass/_waste.scss
=> [Bulky] Add ‘Location details’ page to booking wizard

perllib/FixMyStreet/Cobrand/Northamptonshire.pm, t/cobrand/northamptonshire.t
Can be reversed should it be fixed. [skip changelog]
=> [Northamptonshire] Do not send updates on old reports.

perllib/FixMyStreet/App/Form/Waste/Request/SLWP.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_4471550.json, t/app/controller/waste_4499005.json, t/app/controller/waste_sutton_r.t
Fixes https://3.basecamp.com/4020879/buckets/26876928/todos/5424996481
Fixes https://3.basecamp.com/4020879/buckets/26876928/todos/5428174934
Fixes https://3.basecamp.com/4020879/buckets/26876928/todos/5428181549
=> [Sutton] bag fixes

perllib/FixMyStreet/Roles/Bottomline.pm, perllib/FixMyStreet/Roles/DDProcessor.pm
Sets property_id should be only real change.
But hopefully a bit easier to follow.
=> [Waste] DD more refactoring

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/CobrandPay360.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/Integrations/Pay360.pm, t/app/controller/waste.t, templates/web/base/waste/_garden_status_messages.html, templates/web/base/waste/bin_days.html, templates/web/base/waste/bin_days_sidebar.html, templates/web/bromley/waste/services.html
Fixes https://github.com/mysociety/societyworks/issues/3238 [skip changelog]
=> [Bromley] Try to look up existing DD subscription.

templates/email/highwaysengland/site-name.txt, templates/web/highwaysengland/tokens/confirm_problem.html
Fixes https://github.com/mysociety/societyworks/issues/3271
=> [National Highways] Change site-name and text on problem confirmation

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Reporting.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_sutton_garden.t, t/app/controller/waste_sutton_r.t, templates/web/sutton/waste/services.html
=> [Sutton] Cancellation by staff only.

web/cobrands/northamptonshire/assets.js
Fixes https://mysocietysupport.freshdesk.com/a/tickets/2520 (allows both old and new so they can put it live their end whenever). [skip changelog]
=> [Northamptonshire] New traffic signal categories.

templates/web/bathnes/around/_postcode_form_post.html, web/cobrands/bathnes/layout.scss
Improved hierarchy of the markup for Bathness message on home page.
Change markup from `<h4>` -> `<p>`
Let me know if there is any feedback
=> [Bathness] Simplified markup for postcode message

perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/FixMyStreet/Roles/DDProcessor.pm, perllib/Integrations/Bottomline.pm, t/app/controller/waste_kingston.t, t/cobrand/bromley.t, t/cobrand/kingston.t, t/integrations/bottomline.t, templates/web/kingston/waste/dd_form.html
=> [Kingston] waste small fixes

perllib/FixMyStreet/Cobrand/TfL.pm, t/cobrand/tfl.t, templates/email/tfl/submit.html, templates/email/tfl/submit.txt
=> [TfL] Remove contact information from report submission emails

perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Template.pm, t/app/controller/admin/emergencymessage.t, templates/web/bathnes/around/_postcode_form_post.html, templates/web/bathnes/report/new/form_after_heading.html, templates/web/bristol/report/new/form_after_heading.html, templates/web/bromley/report/new/form_after_heading.html, templates/web/buckinghamshire/report/new/form_after_heading.html, templates/web/cheshireeast/report/new/form_after_heading.html, templates/web/hart/report/new/form_after_heading.html
[Bucks, Bath] Remove hard-coded site-wide messaging.
Fixes https://github.com/mysociety/societyworks/issues/3327
=> [fixmystreet.com] Show relevant emergency message.

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/CheshireEast.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/Hackney.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/Merton.pm, perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Cobrand/Westminster.pm
For part of https://github.com/mysociety/societyworks/issues/3319 [skip changelog]
Take the opportunity to streamline how the function works.
=> [Brent] Anonymous reporting

perllib/FixMyStreet/Cobrand/Brent.pm
* Adds privacy url
* OS maps option
* Zoom
* Disambiguate location
=> [Brent] Configuration

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, templates/web/base/govuk/fields.html
Closes https://github.com/mysociety/societyworks/issues/3310.
=> [Bulky Goods] Location page improvements

templates/web/peterborough/waste/_more_services_sidebar.html
Closes https://github.com/mysociety/societyworks/issues/3311.
=> [Bulky Goods] Add link to Household Recycling Centre to bin days page

web/cobrands/camden/_mixins.scss, web/cobrands/camden/base.scss
Fixes: https://mysociety.slack.com/archives/C03DWPYHS4S/p1668679976155599
Let me know if there is any feedback
=> [Camden] Added fix for inputs

perllib/FixMyStreet/Cobrand/Brent.pm, templates/web/brent/around/intro.html
* Add intro.html
* Add postcode text
* Disallow reopening of reports
For https://github.com/mysociety/societyworks/issues/3319
=> [Brent] Cobrand configuration

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/bin_days_bulky.html
Closes https://github.com/mysociety/societyworks/issues/3309.
In addition to the deep link, this PR implements a check for existing pending bulky collections and redirects the user accordingly.
=> [Bulky Goods] Deep link to bulky workflow after selecting address

perllib/FixMyStreet/Cobrand/Shropshire.pm
* Add photo uploads to Confirm
Servers branch: shropshire-confirm-photo-upload-live
For FD-2403
=> [Shropshire] Enable Open311 photo upload

t/cobrand/tfl.t, templates/web/tfl/report/_item_heading.html, web/cobrands/tfl/base.scss
=> [TfL] Include report ID in report list alongside map

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/forms/waste/bulky.t, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html
For https://github.com/mysociety/societyworks/issues/3314
=> [Bulky Goods] Configurable maximum number of items.

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/app/controller/waste_peterborough.t, templates/web/base/waste/bulky/cannot_book.html
For https://github.com/mysociety/societyworks/issues/2908 (assuming question wording as currently is is okay)
=> [Bulky Goods] Must be a resident to book online.

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/forms/waste/bulky.t, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, web/js/waste.js
Still needs a 'nice admin' but can do that separately along with the max-items-per-collcetion field as well.
So fixes most of https://github.com/mysociety/societyworks/issues/2916 (bar per-item maximum I think).
=> [Bulky goods] Per-item pricing

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Waste/UPRN.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/Integrations/Bartec.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/_bulky_waste_message.html, templates/web/peterborough/waste/_more_services_sidebar.html, templates/web/peterborough/waste/bin_days_bulky.html
For https://github.com/mysociety/societyworks/issues/3302.
For https://github.com/mysociety/societyworks/issues/3303 (sort of).
For https://github.com/mysociety/societyworks/issues/2911 (last bit, staff needing to provide email/phone).
=> [Peterborough] Bulky error updates

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_peterborough.t, templates/web/base/waste/bulky/confirmation.html, templates/web/peterborough/email_sent.html, web/cobrands/sass/_waste.scss
Designs from #4122 [skip changelog]
=> [Peterborough] Bulky confirmation email/page

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/forms/waste/bulky.t, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, templates/web/base/waste/garden/subscribe_confirm.html, templates/web/base/waste/pay_error.html, templates/web/kingston/waste/garden/subscribe_confirm.html, templates/web/peterborough/waste/pay_error.html, templates/web/sutton/waste/garden/subscribe_confirm.html, templates/web/sutton/waste/pay_error.html, web/js/waste.js
For https://github.com/mysociety/societyworks/issues/3282
For https://github.com/mysociety/societyworks/issues/2912
For https://github.com/mysociety/societyworks/issues/3313
=> [Peterborough] Allow payment to be taken for collection bookings

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, t/app/controller/waste_peterborough.t, templates/web/base/admin/waste/edit.html
Fixes https://github.com/mysociety/societyworks/issues/3368 [skip changelog]
=> [Bulky Goods] Nicer admin for overall config.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t
[skip changelog] For https://github.com/mysociety/societyworks/issues/3367
=> [Peterborough] Check if had a free collection.

perllib/FixMyStreet/App/Controller/Photo.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Claims.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Wizard.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/base/govuk/fields.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, templates/web/peterborough/waste/index.html, web/cobrands/sass/_waste.scss
Fixes https://github.com/mysociety/societyworks/issues/3371 [skip changelog]
Hopefully all makes sense, few bits were missing.
=> [Bulky Goods] Upload images without JS

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/base/waste/bulky/summary.html, templates/web/peterborough/waste/bin_days_bulky.html
For https://github.com/mysociety/societyworks/issues/3373
(will sort out photo storage in separate PR)
=> [Bulky Goods] Add page for viewing existing booking

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/base/waste/bulky/summary.html
=> [Bulky Goods] Store/display photos on collection summary

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/cobrand/peterborough/bulky-goods/available-slots.t
For https://github.com/mysociety/societyworks/issues/3381 [skip changelog]
=> [Peterborough] Next day booking only before 3pm.

CHANGELOG.md, templates/web/base/common_scripts.html, web/js/fancybox.js
Closes https://github.com/mysociety/fixmystreet/issues/3856
https://user-images.githubusercontent.com/9289297/204593266-8f6c6c80-5bb1-414a-adb8-7d283e68aff3.mov
=> Stop the map from moving when navigating images with arrow keys.

perllib/FixMyStreet/Cobrand/Southwark.pm
=> [Southwark] Add cobrand

perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_sutton_r.t
Request to suppress time of bin collection on collection day
https://mysocietysupport.freshdesk.com/a/tickets/2577
=> [Sutton] Prevent time of bin collection showing on collection day

perllib/FixMyStreet/Cobrand/Brent.pm
Setting for using Brent's Azure single sign-on
=> [Brent] Add social_auth_enabled for single sign on

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky/Cancel.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Roles/SCP.pm, perllib/Integrations/Bartec.pm, t/app/controller/waste_peterborough.t, t/cobrand/peterborough/bulky-goods/unit.t, templates/email/default/waste/bulky-refund-request.txt, templates/web/base/waste/bulky/booking_cancellation.html, templates/web/peterborough/waste/bin_days_bulky.html
Closes https://github.com/mysociety/societyworks/issues/2915.
=> Peterborough Bulky Goods cancellations

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
From https://3.basecamp.com/4020879/buckets/28996137/todos/5602478388#__recording_5625502350 [skip changelog]
=> [Brent] Move UnitID on gullies to text.

t/app/controller/waste_peterborough.t, templates/web/base/waste/bulky/items.html
=> [Bulky Goods] Hide ‘maximum numbers’ message unless there are max values

web/cobrands/buckinghamshire/assets.js
Fixes https://github.com/mysociety/societyworks/issues/3417
=> [Buckinghamshire] Update gritting link

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
Brent do not have any river piers in their area
=> [Brent] Remove TfL River pier category

docs/sites.md
=> Added Croatian Popravi.to site

t/app/controller/waste_peterborough.t, templates/web/base/govuk/fields.html, templates/web/peterborough/waste/_bulky_not_signed_user.html, templates/web/peterborough/waste/bin_days_bulky.html
- Wire up 'sign in' button on bin days page for viewing existing bulky booking
- Ensure item message is displayed even if item name has an `&` in it
=> [Bulky Goods] Couple of small fixes

templates/web/camden/before_wrapper.html, templates/web/camden/tracking_code.html
They've asked for this to be available on staging for testing purposes, so I've configured it to appear on staging as well.
Fixes https://github.com/mysociety/societyworks/issues/3306
=> [Camden] Add Google Tag Manager

web/cobrands/camden/base.scss
Replaces https://github.com/mysociety/fixmystreet/pull/4233
=> [Camden] Input fixes

web/cobrands/fixmystreet-uk-councils/assets.js
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/2714
=> [Cheshire East] Update to WFS service.

templates/web/brent/auth/general.html, templates/web/brent/report/form/user.html
Client has requested that we should follow the style and wording that Westminster is using for signing in with the single sign on
=> [Brent] Change login to match Westminster

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/forms/waste/bulky.t
=> [Bulky goods] Fix message unicode encoding.

perllib/FixMyStreet/Cobrand/TfL.pm, templates/web/camden/auth/general.html, templates/web/camden/footer_extra_js.html, templates/web/camden/report/form/user.html, web/cobrands/camden/base.scss
- Adds the config for TfL's red routes etc
- Makes the staff login button less prominent
Fixes https://github.com/mysociety/societyworks/issues/3459
Fixes https://github.com/mysociety/societyworks/issues/3460
Fixes https://github.com/mysociety/societyworks/issues/3461
=> [Camden] Various small fixes

perllib/FixMyStreet/App/Form/Claims.pm, t/app/controller/claims.t
For https://mysocietysupport.freshdesk.com/a/tickets/2657
=> [Buckinghamshire] Ensure report ID for claims is always 8 digits

perllib/FixMyStreet/Cobrand/Bristol.pm, t/cobrand/bristol.t, templates/web/bristol/report/new/roadworks_text.html
Fixes https://mysocietysupport.freshdesk.com/a/tickets/2588 [skip changelog]
=> [Bristol] Auto-close idle roadworks reports.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Request.pm, perllib/FixMyStreet/App/Form/Waste/Request/Brent.pm, perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t, templates/web/brent/waste/summary_request.html
Adds Brent container request form as copy of Bromley and cobrand methods required for new containers.
https://github.com/mysociety/societyworks/issues/3405
=> [Brent] Adds request new container feature

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t
=> [Buckinghamshire] Only show phone number field to staff

templates/web/peterborough/waste/_more_services_sidebar.html
Peterborough supplier currently out of stock for food bags
https://mysocietysupport.freshdesk.com/a/tickets/2691
Previously done in https://github.com/mysociety/fixmystreet/pull/3996 but request for message alerting public they're out of stock in this request.
=> [Peterborough] Request to suspend food bags

bin/fixmystreet.com/generate_council_location
Add some documentation to the `bin/fixmystreet.com/generate_council_location` script.
Also print out usage if no arguments are provided.
=> Document the bin/fixmystreet.com/generate_council_location script

perllib/FixMyStreet/Cobrand/Hart.pm, t/app/controller/report_new.t, templates/web/hart/about/faq-en-gb.html, templates/web/hart/around/intro.html, templates/web/hart/footer_extra.html, templates/web/hart/index-steps.html
A number of text changes requested to finalise the new look.
Cookies and Disclaimer are broken links - not sure if the intention is to change that at our end or their end?
The list of changes requested is available in the document on https://mysocietysupport.freshdesk.com/a/tickets/2272
=> [Hart] Text changes to footer, faq and front page

perllib/FixMyStreet/App/Form/Claims.pm, t/app/controller/claims.t, templates/web/base/report/new/subcategories.html
Fixes https://github.com/mysociety/societyworks/issues/3060 some more; by setting autocomplete on the subcategory which I think is a simpler and better fix than page hide (which seemed to work most, but not all, of the time and I couldn't work out why). [skip changelog]
=> Set autocomplete=off on subcategories.

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/cobrand/peterborough/bulky-goods/unit.t, templates/web/base/admin/waste/edit.html
- JSON editor for WasteWorks config only available to superusers
- Items list is automatically sorted on name column when form is submitted
- Daily slots is now configurable from admin instead of being hardcoded to 40
=> [Bulky Goods] Admin UI improvements

templates/web/brent/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html
Request to update text for prompting user to
select point in a park.
https://3.basecamp.com/4020879/buckets/28996137/todos/5846228698
=> [Brent] Change park prompt text

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_garden.t, templates/email/brent/other-reported-garden.html, templates/email/brent/other-reported-garden.txt
From the technical specification add half price garden bin subscription in Oct/Nov/Dec
Adds cobrand messaging changes to the emails sent out.
=> [Brent] Add garden subscription cost

perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/Integrations/Echo.pm, t/app/controller/waste_brent_garden.t, templates/email/brent/_garden_data.html, templates/email/brent/other-reported-garden.html, templates/email/brent/other-reported-garden.txt, templates/email/brent/other-reported-waste.html, templates/email/brent/other-reported-waste.txt, templates/email/brent/other-reported.html, templates/email/brent/other-reported.txt, templates/web/brent/waste/garden/subscribe_details_bin_desc.html, templates/web/brent/waste/garden/subscribe_existing_bin_desc.html, templates/web/brent/waste/garden/subscribe_intro.html
Sets up Brent Green Garden Waste service
=> [Brent] Add garden waste subscriptions

templates/email/default/waste/csc_payment_failed.html, templates/email/default/waste/csc_payment_failed.txt
For https://3.basecamp.com/4020879/buckets/26662378/todos/5857896103.
=> Bulky Goods: Use custom message for failed payment email

templates/web/borsetshire/main_nav_items.html
=> [Borsetshire] Remove waste navigation link

perllib/FixMyStreet/Cobrand/Southwark.pm, t/Mock/MapIt.pm, t/cobrand/southwark.t
Fixes https://3.basecamp.com/4020879/buckets/29836651/todos/5756696845 as part of https://github.com/mysociety/societyworks/issues/3396.
=> Southwark: Filter TfL categories

perllib/FixMyStreet/Roles/ParallelAPI.pm
[skip changelog] Echo was down for a bit yesterday, leading to empty temp files being created. The code would fail to load in the file and then return no data, so either give a 404 (non-Peterborough) or get stuck for ever (Peterborough).
=> ParallelAPI copes better with e.g. empty temp file.

web/cobrands/fixmystreet/fixmystreet.js
=> Try and work out category group from filter.

perllib/FixMyStreet/App/Controller/Auth.pm, perllib/FixMyStreet/App/Controller/Auth/Social.pm, t/app/controller/auth_social.t
=> [OIDC] Include id_token_hint in logout redirect.

perllib/FixMyStreet/Reporting.pm, t/app/controller/dashboard.t
Raised in https://3.basecamp.com/4020879/buckets/28996137/todos/5921122970
=> [FMS] Fix issue with role id breaking csv report creation

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_kingston.t, templates/web/base/waste/bin_days_sidebar.html, templates/web/bromley/waste/services.html, templates/web/kingston/waste/_bin_days_no_collections.html, templates/web/kingston/waste/services.html, templates/web/sutton/waste/_bin_days_no_collections.html, templates/web/sutton/waste/services.html
=> [Waste] Add flags to disable garden subs/modify.

templates/web/fixmystreet.com/report/update/after_update.html
=> [fms.com][Shropshire] Show inline tips on update form if report was for Shropshire

perllib/FixMyStreet/Cobrand/Peterborough.pm
This is a temporary workaround until Bartec is updated to display extended data on job sheet
=> [Peterborough] Put all bulky booking information in report title

web/cobrands/highwaysengland/layout.scss
=> [National Highways] Make inspector form a bit wider.

t/app/controller/waste.t, t/app/controller/waste_peterborough.t, templates/web/base/waste/confirmation.html, templates/web/peterborough/waste/confirmation.html, web/cobrands/sutton/_colours.scss
=> [Waste] Ensure confirmation page always has button to get to property page

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/peterborough/other-reported-bulky.html, templates/email/peterborough/other-reported-bulky.txt, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html
- https://3.basecamp.com/4020879/buckets/26662378/todos/5866421148
- https://3.basecamp.com/4020879/buckets/26662378/todos/5866759841
- https://3.basecamp.com/4020879/buckets/26662378/todos/5870284301
Part of https://github.com/mysociety/societyworks/issues/3543.
=> [Bulky Goods] Miscellaneous post-soft-launch wording changes

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/cobrand/peterborough/bulky-goods/unit.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/summary.html
For https://3.basecamp.com/4020879/buckets/26662378/todos/5851788706.
Part of https://github.com/mysociety/societyworks/issues/3543.
=> [Bulky Goods] Updates and improvements to handling of cancellation and collection/refund cutoff times

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/Integrations/Paye.pm
First half, if staff redirecting to PAYE link as provided by its API [skip changelog]
(Don't know what we get back yet)
=> [Brent] Add paye.net integration.

perllib/FixMyStreet/App/Form/Waste/Request/Kingston.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kingston_r.t, templates/email/kingston/other-reported-garden.html, templates/email/kingston/other-reported-garden.txt, templates/email/sutton/other-reported-garden.html, templates/email/sutton/other-reported-garden.txt, templates/web/base/waste/garden/amended.html, templates/web/base/waste/garden/cancel_confirmation.html
[skip changelog] For FD-2698. First commit has no changes, only documenting.
=> [Kingston] Add green bin option if they have boxes

perllib/FixMyStreet/App/Controller/Develop.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/Mock/Tilma.pm, t/app/controller/claims.t, t/cobrand/bucks.t, templates/email/buckinghamshire/_council_reference.html, templates/email/buckinghamshire/_council_reference.txt, templates/email/buckinghamshire/alert-update.txt, templates/email/buckinghamshire/other-reported-claim.html, templates/email/buckinghamshire/other-reported-claim.txt, templates/web/base/admin/config_page_cobrand.html, templates/web/base/admin/config_page_cobrand_one.html, templates/web/base/admin/config_page_value.html, templates/web/base/develop/asset_layers.html, templates/web/base/develop/index.html, web/cobrands/fixmystreet-uk-councils/assets.js
=> [Buckinghamshire] Alloy configuration

CHANGELOG.md, perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/Open311/GetServiceRequests.pm
for https://github.com/mysociety/societyworks/issues/3514
=> [Northumberland] Set-up Alloy integration.

perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Purchase.pm, t/app/controller/waste_brent_garden.t
Change text on button for Brent payment by adding config override for button text
https://3.basecamp.com/4020879/buckets/28996137/todos/5838639014#__recording_5996609233
=> [Brent][FMS] Add config for changing text on submit ggw payment

t/app/controller/waste_kingston_r.t, templates/web/base/waste/confirmation.html
Change to text on navigation button requested by council
https://mysocietysupport.freshdesk.com/a/tickets/2747
=> [Kingston and Sutton] Change text for returning to bin page

templates/email/fixmystreet.com/_submit_footer.html, templates/email/fixmystreet.com/submit.txt
Fixes:  https://github.com/mysociety/societyworks/issues/3572
This PR:
- Removed FMS Pro section
- Expanded FAQ section.
Preview:
Let me know if there is any feedback.
=> [FMS][Emails] Edited mail content for councils

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, t/app/controller/waste_peterborough.t, templates/web/base/admin/waste/edit.html, templates/web/peterborough/waste/_more_services_sidebar.html
=> [Peterborough] Allow food bag ordering to be controlled via admin page

t/app/controller/waste_peterborough.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt
As per https://3.basecamp.com/4020879/buckets/26662378/todos/5961885813.
=> [Bulky Goods] Remove item list from reminder emails

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm, perllib/FixMyStreet/Cobrand/CheshireEast.pm, perllib/FixMyStreet/Cobrand/IsleOfWight.pm, perllib/FixMyStreet/Cobrand/Northamptonshire.pm, perllib/FixMyStreet/Cobrand/Warwickshire.pm, perllib/FixMyStreet/Cobrand/Westminster.pm
=> Add some basic POD documentation to some cobrand files

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Queue/Item/Report.pm, perllib/Open311/UpdatesBase.pm, t/cobrand/bromley_waste.t
=> [Bromley] Cope with earlier received updates

perllib/FixMyStreet/Cobrand/Northumberland.pm
Request to increase default map zoom referencing Bucks, so have set to Bucks zoom
https://github.com/mysociety/societyworks/issues/3636
=> [Northumberland] Increase default map zoom later

perllib/FixMyStreet/Cobrand/Brent.pm
Fixes https://github.com/mysociety/societyworks/issues/3645
=> [Brent] Change default map zoom to 5

web/cobrands/tfl/assets.js
Follows on from https://github.com/mysociety/fixmystreet/pull/4382
=> [TfL] Change category names in asset layers code

perllib/FixMyStreet/App/Controller/Report/Update.pm, perllib/FixMyStreet/Cobrand/Default.pm, templates/web/base/report/form/user.html, templates/web/camden/report/form/user.html, templates/web/hackney/report/form/user.html, templates/web/highwaysengland/report/form/user.html
=> No anonymous updating.

perllib/FixMyStreet/Cobrand/Brent.pm
=> [Brent] Treat allocated task as in progress.

perllib/FixMyStreet/Cobrand/Peterborough.pm
=> [Bulky Goods] Don’t send reminder emails for cancelled bookings

templates/email/default/_email_settings.html, templates/email/fixmystreet.com/submit.html
=> Add ID to submit email report table.

perllib/FixMyStreet/Cobrand/Hackney.pm, t/cobrand/hackney.t
Added a few docs in same commit, sorry, only functional change is the new `category_change_force_resend` function.
=> [Hackney] Resend report upon email category change.

web/cobrands/fixmystreet/assets.js
Add a note about how to look up the current resolution, which can then be used for setting the max_resolution.
=> Update asset layer max_resolution documentation

perllib/FixMyStreet/Cobrand/Northumberland.pm
Set cut_off_date to go-live date.
Part of https://github.com/mysociety/societyworks/issues/3589
=> [Northumberland] Set cut off date

perllib/FixMyStreet/Roles/DDProcessor.pm, t/Mock/MapIt.pm, t/cobrand/bromley_waste.t, t/cobrand/kingston.t
For https://github.com/mysociety/societyworks/issues/3664
=> [Waste] Update areas when renewing subscription

perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm
Otherwise the daemon still has to go through and discount all the email ones. [skip changelog]
=> Mark all archive updates as processed.

CHANGELOG.md, web/cobrands/fixmystreet/fixmystreet.js
This should fix #4423 (does here, anyway).
=> Disable context menu on the map

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Renew.pm, perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_garden.t, templates/web/base/waste/garden/_bin_quantities.html, templates/web/base/waste/garden/_discount_allowed_field.html, templates/web/base/waste/garden/_renew_discount.html, templates/web/base/waste/garden/_sack_quantity.html, templates/web/base/waste/garden/modify.html, templates/web/base/waste/garden/renew.html, templates/web/base/waste/garden/sacks/renew.html, templates/web/base/waste/garden/sacks/subscribe_details.html, templates/web/brent/waste/services.html, web/js/waste.js
Add a cobrand hook to Waste so Brent can change
the category to an Amend garden waste category
and set extra data fields on that based on the
changes made when modifying a garden waste subscription
Branch with same name on mysociety server too.
=> [Brent][WW] Add amend green garden waste

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/cobrand/brent.t, templates/web/base/waste/bin_days_sidebar.html
[skip changelog] For https://mysocietysupport.freshdesk.com/a/tickets/2920
=> [Brent] Code to show correct PDF calendar.

perllib/FixMyStreet/App/Controller/Offline.pm, templates/web/base/offline/drafts.html, templates/web/base/offline/fallback.html, web/cobrands/fixmystreet/offline_report.js, web/cobrands/sass/_base.scss, web/js/offline_draft.js
Thought the individual commits might be easier to review, but the whole lot can probably be squashed down to one commit before merging.
Fixes #4410
=> [Offline] Multiple drafts

templates/web/northumberland/footer_extra_js.html
These were missed during setup.
Fixes https://github.com/mysociety/societyworks/issues/3691
=> [Northumberland] Add JS for highways and roadworks

CHANGELOG.md, templates/web/base/alert/_list.html, web/cobrands/fixmystreet/fixmystreet.js
Fixes https://github.com/mysociety/societyworks/issues/3690
=> Fix RSS feed subscription from alert page button.

t/cobrand/brent.t, templates/web/brent/waste/services.html
Add a general enquiry form for WasteWorks
https://3.basecamp.com/4020879/buckets/28996137/todos/5943751764
Config in society servers 3575-brent-general-enquiry-event-for-staff
=> [Brent][WW] Add general enquiry form

perllib/FixMyStreet/Cobrand/Northumberland.pm, t/cobrand/northumberland.t
=> [Northumberland] Show name of publicly anonymous reporters in staff CSV exports.

docs/_includes/ww-admin-tasks-content.md
Edited the links to the resident's experience section to be consistent in style (also actually added a link in, because there wasn't one before!)
=> Minor copy edits

perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/Camden.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/camden.t, templates/web/camden/report/new/close_bike.html
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/3457
=> [Camden] Auto close e-bike reports.

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t, templates/web/base/waste/bin_days_sidebar.html
Request to add downloadable ggw calendars.
Config in same branch on mysociety servers
https://mysocietysupport.freshdesk.com/a/tickets/3028
=> [Brent] Add green garden waste pdf dowloads

templates/web/base/admin/triage/_inspect.html
=> [Buckinghamshire] Show current destination in triage form.

perllib/FixMyStreet/App/Form/Wizard.pm, perllib/FixMyStreet/Cobrand/Base.pm, perllib/FixMyStreet/DB/ResultSet/Body.pm, perllib/FixMyStreet/DB/Schema.pm, t/app/controller/waste_brent_garden.t
Tests all pass, so hopefully I've weakened the right end of these, but is hard to know [skip changelog]
=> Weaken some circular references

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/Camden.pm, perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm, perllib/FixMyStreet/Cobrand/CheshireEast.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/Hounslow.pm, perllib/FixMyStreet/Cobrand/IsleOfWight.pm, perllib/FixMyStreet/Cobrand/Lincolnshire.pm, perllib/FixMyStreet/Cobrand/Westminster.pm, t/app/controller/report_new.t, t/cobrand/camden.t, templates/web/base/report/new/_form_labels.html, templates/web/base/report/new/form_title.html, templates/web/bathnes/report/new/_form_labels.html, templates/web/brent/report/new/_form_labels.html, templates/web/buckinghamshire/report/new/_form_labels.html, templates/web/camden/report/new/_form_labels.html, templates/web/centralbedfordshire/report/new/_form_labels.html, templates/web/cheshireeast/report/new/_form_labels.html, templates/web/highwaysengland/report/new/_form_labels.html, templates/web/hounslow/report/new/_form_labels.html, templates/web/isleofwight/report/new/_form_labels.html, templates/web/lincolnshire/report/new/_form_labels.html, templates/web/westminster/report/new/_form_labels.html, web/cobrands/fixmystreet/fixmystreet.js
fixes: https://github.com/mysociety/societyworks/issues/3497
=> Make cobrand text overrides for new report fields apply on fixmystreet.com.

templates/web/bristol/around/intro.html
As part of adding docks and liferings Bristol want to update the intro text to reflect the expanded scope.
Part of https://github.com/mysociety/societyworks/issues/3649
This is to be merged/deployed at the same time as the rest of the changes discussed in the above issue, which is scheduled to be this Wednesday, 14th June.
=> [Bristol] Update intro text

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Echo.pm, t/cobrand/sutton.t
Push notifications for Sutton will be being posted to the Kingston domain, so make sure we can still locate the relevant report. Fixes https://github.com/mysociety/societyworks/issues/3728 [skip changelog]
=> [Sutton] Acknowledge push notifications

templates/web/highwaysengland/about/web-app.html
Fixes https://github.com/mysociety/societyworks/issues/3734
=> [National Highways] Add PWA instructions

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, t/cobrand/peterborough/bulky-goods/unit.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/peterborough/other-reported-bulky.html, templates/email/peterborough/other-reported-bulky.txt, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html, templates/web/peterborough/waste/bin_days_bulky.html
Fixes https://github.com/mysociety/societyworks/issues/3543.
Contains changes from
- https://github.com/mysociety/fixmystreet/pull/4323
- https://github.com/mysociety/fixmystreet/pull/4317
- https://github.com/mysociety/fixmystreet/pull/4305
- https://github.com/mysociety/fixmystreet/pull/4380
=> [P'bro] Post-soft launch fixes

perllib/FixMyStreet/Cobrand/Peterborough.pm
=> [P'bro] Add some POD to Cobrand/Peterborough.pm

templates/web/fixmystreet.com/static/unresponsive.html
I have updated the copy and added some extra information to this page. I'm not sure I've done all of the code properly, particularly the bullet point lists and spacing.
=> Update unresponsive council.html

perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/Gloucestershire.pm, perllib/FixMyStreet/Cobrand/UK.pm, t/cobrand/gloucestershire.t, templates/web/fixmystreet-uk-councils/admin/bodies/_updates_disallowed_hint.html, templates/web/gloucestershire/footer_extra_js.html, templates/web/gloucestershire/report/_updates_disallowed_message.html
Closes https://github.com/mysociety/societyworks/issues/3648.
Related commits also in `mysociety-servers` -> `glos-confirm-integration`: 2168f5434, ceb3b75df
=> [Glos] FMS config

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_peterborough.t, templates/email/default/waste/bulky-refund-request.txt
For https://github.com/mysociety/societyworks/issues/3543
=> [Waste] Include PAYE.net code in bulky refund emails

perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/cobrand/bathnes.t, t/cobrand/fixmystreet.t
Thought this might be worth trying to see if it makes the mobile experience a bit better. 
For FD-2979
=> [FMS.com & BANES] Zoom further in when using geolocation on /around

perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/northumberland.t
[skip changelog] Fixes FD-3130
=> [Northumberland] Include staff email/role in CSV export.

templates/web/base/maps/_map_instructions.html, web/cobrands/fixmystreet/assets.js, web/cobrands/sass/_base.scss, web/js/map-OpenLayers.js
Fixes https://github.com/mysociety/societyworks/issues/3637
=> Fix overlapping UI on mobile ‘select road’ map screen

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
Bexley have provided new logic for considering out of hours priority notifications.
This adds some extra questions and the logic to select p1 or p1 & ooh.
Also updates dropdown content on some questions and changes text regarding price and time scale for dead animal collection
Matching branch on my society-servers
https://github.com/mysociety/societyworks/issues/3679
=> [Bexley] Update p1/out of hours categories and logic

templates/web/gloucestershire/header_extra.html, templates/web/gloucestershire/tracking_code.html
For https://3.basecamp.com/4020879/buckets/32187059/todos/6001244893
=> [Glos] Add staging tracking code

conf/packages.docker
@davea Thanks for your help today.
I have added the line to packages.docker.
I'll ask you for some help adding info to the PR if neccesary.
=> Added libreadline-dev packages.docker

templates/web/base/report/_item.html
For https://github.com/mysociety/societyworks/issues/3790
=> Remove shortlist stars from front page

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Queue/Item/Report.pm, t/Mock/MapIt.pm, t/cobrand/centralbedfordshire.t, templates/web/base/js/translation_strings.html, templates/web/base/report/new/after_photo.html, templates/web/centralbedfordshire/footer_extra_js.html, templates/web/fixmystreet-uk-councils/footer_extra_js_base.html, templates/web/fixmystreet-uk-councils/report/new/after_photo.html, templates/web/fixmystreet-uk-councils/report/new/inline-tips.html, templates/web/fixmystreet.com/footer_extra_js.html, templates/web/fixmystreet.com/report/new/inline-tips.html, web/cobrands/centralbedfordshire/flytipping.js, web/cobrands/fixmystreet-uk-councils/council_category_hide_element_rules.js, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js, web/cobrands/fixmystreet/fixmystreet.js
Closes https://github.com/mysociety/societyworks/issues/3792
Closes https://github.com/mysociety/societyworks/issues/3800
Closes https://github.com/mysociety/societyworks/issues/3801
Closes https://github.com/mysociety/societyworks/issues/3802
=> [Central Beds] Address Jadu integration customer feedback.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/app/controller/claims.t, templates/email/buckinghamshire/submit.html, templates/email/buckinghamshire/submit.txt
Request to only send claims to Evo.
Removes sending to Open311 and expectation in tests of open311 response
https://mysocietysupport.freshdesk.com/a/tickets/3221
=> [Bucks] Remove claims from going into open311

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
Related: https://github.com/mysociety/open311-adapter/pull/291
=> [Central Beds] Indicate whether reported by staff for Jadu reports.

perllib/Open311.pm, t/sendreport/open311_send.t
Multivaluelist params are arrayrefs like media urls, so also need flattening.
=> Fix open311 file uploads when sending multivaluelist attributes.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/app/controller/waste_peterborough.t, templates/web/peterborough/waste/services.html
[skip changelog] Fixes FD-3234
=> [Peterborough] Change cut off time to 4pm.

perllib/FixMyStreet/Cobrand/Shropshire.pm, t/sendreport/open311.t
[skip changelog] For FD-2689
open311 change at https://github.com/mysociety/open311-adapter/pull/282
=> [Shropshire] Include contributed_by info in sent data.

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_sutton_garden.t
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/3820
=> [Waste] Show success if pay complete visited again

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Report/Update.pm, perllib/FixMyStreet/App/Controller/Tokens.pm, perllib/FixMyStreet/DB/Result/Token.pm, t/app/controller/report_new.t, t/app/controller/report_new_update.t
Fixes https://github.com/mysociety/fixmystreet/issues/4543
=> Make confirm links login within 30s of first use.

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/Northumberland.pm, t/Mock/MapIt.pm, t/cobrand/fixmystreet.t, t/cobrand/northumberland.t, templates/web/base/report/new/category.html, templates/web/base/report/new/subcategories.html, web/cobrands/highways/assets.js
Fixes FD-3216.
Fixes https://github.com/mysociety/societyworks/issues/3837
=> [Northumberland] Allow staff only group on NH roads

perllib/Open311.pm, t/cobrand/brent.t
https://github.com/mysociety/societyworks/issues/3835
=> [Brent] Change title label in Open311 service req description for ATAK reports.

templates/web/peterborough/waste/services.html
=> [Peterborough] Update text for no access bin reports

perllib/FixMyStreet/App/Form/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Billing.pm, t/app/controller/waste_kingston.t, t/app/controller/waste_sutton_garden.t
FD-3118 and FD-3269 [skip changelog]
=> [SLWP] Text change, and email mandatory

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
https://github.com/mysociety/societyworks/issues/3856
=> [Central Beds] Send staff reporter name for Jadu reports.

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
https://github.com/mysociety/societyworks/issues/3805
=> [Brent] Move ATAK reports to investigating after open311 send.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
=> [Bromley] Fallback if title missing on update, but still send.

bin/import_categories, perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/Gloucestershire.pm, t/app/controller/report_new.t, t/cobrand/gloucestershire.t, templates/web/base/report/new/_form_labels.html, web/cobrands/fixmystreet-uk-councils/assets.js
For https://github.com/mysociety/societyworks/issues/3791, https://github.com/mysociety/societyworks/issues/3860.
=> Glos confirm integration post testing fixes

templates/web/base/report/_main_sent_info.html, templates/web/oxfordshire/report/_main_after.html
=> Treat send_state of skipped as not sent.

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t, templates/web/base/waste/bin_days.html, templates/web/peterborough/waste/_announcement.html, templates/web/peterborough/waste/_more_services_sidebar.html, templates/web/peterborough/waste/_service_navigation_bar.html
Closes https://github.com/mysociety/societyworks/issues/3844.
Kingston and Sutton have different property types that are eligible for bulky waste collection: https://docs.google.com/spreadsheets/d/14grAtRpKKb2ji_KbKZpmNQADpgFNANW_So4BK0uWobc/edit#gid=1790878445.
This PR also refactors the eligibility checks across bulky waste code to make them easier to follow.
=> [K&S Bulky] Eligibility check for properties

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/app/controller/waste_peterborough.t, t/app/controller/waste_peterborough_bulky.t, templates/web/base/admin/waste/edit.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html
Adds dropdown option (staff/users/don't show) to show location page in bulky waste form - wasteworks_config 'show_location_page'
Adds boolean option to show extra location field for each item in bulky waste form - wasteworks_config  'show_individual_location_notes'
Links photos and notes to Echo fields using extra fields
For ticket:
https://github.com/mysociety/societyworks/issues/3845
=> [WW][Kingston][Sutton] K&S bulky waste - optional booking information

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough.t, t/app/controller/waste_peterborough_bulky.t, templates/web/base/admin/waste/edit.html, templates/web/base/waste/bulky/items.html, web/js/waste.js
Wasn't sure what tests you might have done already, but hopefully easy to include this in them when ready. Feel free to incorporate however. https://github.com/mysociety/societyworks/issues/3841 [skip changelog]
=> [Bulky] Allow two bands of collection payment.

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
=> [Bexley] Update street cleaning P1 handling.

perllib/FixMyStreet/Cobrand/Gloucestershire.pm, t/open311/getservicerequests.t
Closes https://github.com/mysociety/societyworks/issues/3859.
=> [Glos] Prevent fetching of reports from Confirm for private categories 

.cypress/cypress/integration/brent.js, data/test-asset-layers.yml, templates/web/brent/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html
=> [Brent] Update road message, and move to config.

perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t
For https://github.com/mysociety/societyworks/issues/3884
=> [SLWP] Store SLA details

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t
[skip changelog] For https://github.com/mysociety/societyworks/issues/3760
=> [SLWP] Send to echo before payment

perllib/FixMyStreet/Cobrand/Brent.pm
https://github.com/mysociety/societyworks/issues/3898
=> [Brent] [ATAK] Send attributes to construct description open311-adapter side.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/FixMyStreet/Roles/SCP.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_sutton_garden.t, templates/web/base/waste/bulky/choose_date.html
The payment half of https://github.com/mysociety/societyworks/issues/3760
=> [SLWP] Payment references

perllib/FixMyStreet/App/Controller/JS.pm, perllib/FixMyStreet/App/View/Web.pm, perllib/FixMyStreet/Template/JS.pm, t/app/controller/waste.t, t/app/controller/waste_kingston.t, t/app/controller/waste_sutton_garden.t, templates/web/base/common_header_tags.html, templates/web/base/common_scripts.html, templates/web/base/js/translation_strings.html, templates/web/base/report/form/user.html, templates/web/fixmystreet-uk-councils/footer_extra_js_base.html, templates/web/fixmystreet.com/footer_extra_js.html, templates/web/highwaysengland/footer_extra_js.html, templates/web/thamesmead/footer_extra_js.html, web/cobrands/fixmystreet/fixmystreet.js
Check for a per-cobrand static asset layer file, and a language-based translation file.
This means we will be able to pre-compile the asset layer and translation JavaScript.
=> Factor out asset layer and translation JavaScript compilation code

perllib/FixMyStreet/App/Form/Waste/SmallItems.pm, t/app/controller/waste_brent_small_items.t, templates/web/base/waste/bulky/items.html
Adds count of how many small WEEE items have been selected  and how many different 'types' of item have been selected.
Adds errors if more that 4 small WEEE or more than 3 types.
Adds text to clarify the limits allowed.
Adds tests for above.
https://github.com/mysociety/societyworks/issues/3869#issuecomment-1700920860
=> [Brent][WW] Small items making a booking #3869

perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm
[skip changelog] Just generalising this so others can access the admin if flag set.
=> [UK] wasteworks_config permission for any cobrand.

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_brent_small_items.t, templates/email/brent/other-reported.html, templates/email/brent/other-reported.txt, templates/email/default/waste/_bulky_data.html, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/default/waste/other-reported-bulky.html, templates/email/default/waste/other-reported-bulky.txt
Changes templates to adapt for Brent and to add small items in relevant places instead of bulky waste
Adds tests
https://github.com/mysociety/societyworks/issues/3871
=> [Brent][WW] Small items collection - Email notifications

templates/web/base/waste/bulky/_bin_days_list.html
Request to change text for K&S to 'View existing bookings"
https://3.basecamp.com/4020879/buckets/33314444/todos/6529430589
=> [SLWP] Change sign in text to "View existing bookings"

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, templates/web/base/waste/bulky/about_you_preamble.html
Adds explanation for collection of text on about you page
https://3.basecamp.com/4020879/buckets/33314444/todos/6529451251
=> [SLWP] Add text on the about you page

perllib/FixMyStreet/App/Controller/Waste.pm, t/app/controller/waste_kands_bulky.t, templates/email/default/waste/bulky-reminder.txt, templates/email/default/waste/other-reported-bulky.txt
Fixes both parts of https://3.basecamp.com/4020879/buckets/33314444/todos/6535996192
=> [SLWP] Email tweaks for bulky

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm
Adds purpose of notes field under note label and makes label more direct
https://3.basecamp.com/4020879/buckets/33314444/todos/6529606114
=> [SLWP] Add more detail to notes field

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough_bulky.t
=> [SLWP] Make location field mandatory.

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
=> [Brent] Include location_name field in CSV export

.cypress/cypress/integration/merton.js, bin/fixmystreet.com/fixture, perllib/FixMyStreet/Cobrand/Merton.pm, t/cobrand/merton.t, templates/web/base/report/form/user.html, templates/web/camden/report/form/user.html, templates/web/hackney/report/form/user.html, templates/web/westminster/report/form/user.html
=> [Merton] Remove anonymous reports override.

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_bromley_bulky.t, templates/web/base/admin/waste/bulky_items.html
https://github.com/mysociety/societyworks/issues/3911
=> [Bromley] [Waste] Per-item pricing depending on property type.

perllib/FixMyStreet/App/Model/PhotoSet.pm, perllib/FixMyStreet/ImageMagick.pm
=> [Brent] Convert uploaded photos to JPEGs.

perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Cobrand/Westminster.pm, t/cobrand/bucks.t, t/cobrand/westminster.t, templates/web/base/tokens/confirm_problem.html
=> [Westminster] Clearer confirmation message when passing report to TfL

perllib/FixMyStreet/Roles/CobrandEcho.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/FixMyStreet/Script/Alerts.pm, perllib/FixMyStreet/TestMech.pm, perllib/Open311.pm, t/cobrand/kingston.t, t/cobrand/sutton.t, templates/email/default/_email_comment_list.html, templates/email/default/_email_comment_list.txt, templates/email/default/waste/_bulky_email_comment_end.html, templates/email/default/waste/_bulky_email_comment_end.txt, templates/email/default/waste/_bulky_list.html, templates/email/default/waste/_bulky_list.txt, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/default/waste/bulky_payment_echo_update_failed.txt, templates/email/default/waste/other-reported-bulky.html, templates/email/default/waste/other-reported-bulky.txt
Fetching completion photo for an udpate, and improving the update email sent out thereby.
=> [SLWP] Completion photo/email improvements

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, templates/web/base/admin/waste/edit.html
=> [Bulky waste] Increase max items to 200.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste_bromley_bulky.t, templates/web/base/waste/bulky/summary.html
https://github.com/mysociety/societyworks/issues/3891
=> [Bromley] [Waste] Bulky payments.

perllib/FixMyStreet/Roles/ParallelAPI.pm, t/app/controller/waste.t, templates/web/base/waste/async_loading.html, templates/web/base/waste/bin_days.html, templates/web/base/waste/form.html, templates/web/base/waste/missing.html
For https://github.com/mysociety/societyworks/issues/3922, also FD-3409.
=> [Waste] Ensure async loading works when visiting sub-page directly

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
Uses domestic waste service and blue bag service to calculate pdf to use.
Configuration in mysociety_servers under same branch.
=> [Brent] Brent recycling sacks pdfs

templates/web/sutton/header_site.html
For https://mysocietysupport.freshdesk.com/a/tickets/3413.
=> [Sutton] Change title in site header

templates/web/sutton/waste/_more_services_sidebar.html
For https://mysocietysupport.freshdesk.com/a/tickets/3414
=> [Sutton] Add link to recycling centre booking form

perllib/FixMyStreet/Cobrand/Brent.pm
=> [Brent] Allow requesting of recycling sacks.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste_bromley_bulky.t
Test for Trade or Domestic Service_Ids when running through bin services for address. If Domestic or Trade found, bulky waste is allowed as long as bulky waste is also enabled.
https://github.com/mysociety/societyworks/issues/3892
=> [Bromley] Only Trade or Domestic properties are allowed bulky waste

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Peterborough.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/app/controller/my.t, t/app/controller/waste_peterborough_bulky.t, templates/email/peterborough/other-reported.html, templates/email/peterborough/other-reported.txt, templates/email/peterborough/waste/other-reported-bulky-cancel.html, templates/email/peterborough/waste/other-reported-bulky-cancel.txt, templates/web/base/reports/_status_filter_options.html
I saw the small other two while fixing the main two.
Fixes https://github.com/mysociety/fixmystreet/issues/4558
Fixes https://github.com/mysociety/fixmystreet/issues/4469
Fixes https://github.com/mysociety/societyworks/issues/3930
Fixes https://github.com/mysociety/societyworks/issues/3929
=> [Peterborough] bulky emails and couple assorted

t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough_bulky.t, templates/web/base/waste/bulky/intro.html, web/cobrands/sass/_base.scss
Changes for https://3.basecamp.com/4020879/buckets/33314444/todos/6618280655
=> [SLWP] Amend intro text for pricing and cancellation

t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough_bulky.t, templates/web/base/waste/bulky/choose_date.html
Add advice on times for collection of bulky goods booking
https://3.basecamp.com/4020879/buckets/33314444/todos/6618280655
=> [SLWP] Add explanatory text on date picker page

perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough_bulky.t, templates/web/base/waste/bulky/location.html
Added advice about collections to location page
https://3.basecamp.com/4020879/buckets/33314444/todos/6618280655
=> [SLWP] Add explanatory text on Location page

perllib/FixMyStreet/App/Form/Waste/SmallItems.pm, perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_small_items.t, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html
Fixes all items on https://3.basecamp.com/4020879/buckets/33769634/todolists/6623008745
=> [Brent] small small text changes

t/app/controller/waste_kands_bulky.t, templates/web/base/waste/index.html
https://3.basecamp.com/4020879/buckets/33314444/todos/6627663646
=> [SLWP] Add reference to bulky waste to index page

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_bromley_bulky.t, t/app/controller/waste_peterborough.t, templates/web/base/admin/waste/edit.html, templates/web/base/waste/bulky/items.html, web/js/waste.js
https://github.com/mysociety/societyworks/issues/3932
=> [Waste] [Bromley]  Enable a minimum cost for bulky per-item charging.

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/Integrations/Echo.pm, t/app/controller/waste_brent_garden.t, t/app/controller/waste_brent_small_items.t, templates/web/brent/waste/services.html
Fixes https://mysocietysupport.freshdesk.com/a/tickets/3427
Fixes https://mysocietysupport.freshdesk.com/a/tickets/3428
Change asked for https://3.basecamp.com/4020879/buckets/33769634/todos/6526315977#__recording_6636845817
Add logging I suggest at https://3.basecamp.com/4020879/buckets/33769634/todos/6526315977#__recording_6636816644
And a test warning I noticed along the way.
=> [Brent] Small item changes + other waste issues

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
Add explicit FMS id for Bexley in notification email that a report has been made
https://mysocietysupport.freshdesk.com/a/tickets/3381
=> [Bexley] Add FMS id/street name area to submit email

web/cobrands/gloucestershire/assets.js, web/cobrands/oxfordshire/assets.js
Arguably these two files should be factored together somehow, but I didn't think it worth it as we'll be getting rid of the Gloucestershire one soon anyway.
For https://3.basecamp.com/4020879/buckets/32187059/todos/6618416579
=> [Glos, Oxfordshire] Stop job/defect popup disappearing immediately on mobile

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste_bromley_bulky.t
https://github.com/mysociety/societyworks/issues/3908
=> [Bromley] [Waste] Enable reporting missed bulky collections.

.cypress/cypress/integration/highwaysengland.js, bin/fixmystreet.com/fixture, web/cobrands/highwaysengland/assets.js
Fixes https://mysocietysupport.freshdesk.com/a/tickets/3445
=> [National Highways] Litter is now a group.

perllib/FixMyStreet/Cobrand/Gloucestershire.pm
For https://github.com/mysociety/societyworks/issues/3915.
=> Gloucestershire post-go-live fixes

perllib/FixMyStreet/App/Form/Page/Bulky.pm, perllib/FixMyStreet/App/Form/Waste/Bulky.pm, t/app/controller/waste_kands_bulky.t, templates/web/base/waste/bulky/confirmation.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/location.html
Changes from https://3.basecamp.com/4020879/buckets/33314444/todos/6641263357 and (https://3.basecamp.com/4020879/buckets/33314444/todos/6618688024 & https://3.basecamp.com/4020879/buckets/33314444/todos/6618280655)
=> [SLWP] Kands further text improvements

perllib/FixMyStreet/App/Controller/Admin/Triage.pm, perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm, perllib/Open311/UpdatesBase.pm, t/app/controller/waste_kands_bulky.t
Changes comments made to the comment user of the council rather than the user taking the create/cancel action
https://3.basecamp.com/4020879/buckets/33314444/todos/6619156888
=> [SLWP] Make comments for bulky create/cancel from council

t/app/controller/waste_bromley_bulky.t, templates/web/base/waste/bulky/summary.html
Bromley not offering amending bulky collection so don't have line in summary saying how much more can be added
https://3.basecamp.com/4020879/buckets/33906758/todos/6657459835
=> [Bromley] Don't show amend numbers

templates/email/default/waste/other-reported-bulky.html
Remove duplicate of terms and conditions and also booking date
https://3.basecamp.com/4020879/buckets/33906758/todos/6657359025
=> [Bromley] Duplicate of terms and conditions

perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/northumberland.t
https://mysocietysupport.freshdesk.com/a/tickets/3384
=> [Northumberland] Add shortlisted to stats summary

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/app/controller/waste_brent_small_items.t, t/cobrand/brent.t
Couple of pre-go-live tweaks from testing [skip changelog]
=> [Brent] Small item missed collection tweaks

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, t/app/controller/waste_kands_bulky.t
Adds the option to accept cheque payments and put in the cheque reference number avoiding the credit card payment flow.
https://github.com/mysociety/societyworks/issues/3952
=> [SLWP] Adds cheque payment for K&S

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_peterborough_bulky.t
Fixes https://github.com/mysociety/societyworks/issues/3914.
Was originally https://github.com/mysociety/fixmystreet/pull/4680 but changes to the underlying kands-bulky-setup branch produced a lot of conflicts when I attempted to rebase.
=> Bulky phone bugs

perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/app/controller/report_new.t, templates/web/base/report/new/extra_name.html
Request to add PC/PCSO on Bromley titles. 
https://mysocietysupport.freshdesk.com/a/tickets/3379
=> [Bromley] Add PC/PCSO to titles on reports

perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_brent_small_items.t
=> [Waste] No bulky reminder if no email to send to.

perllib/FixMyStreet/Cobrand/Northumberland.pm
=> [Northumberland] Update pin colours

perllib/FixMyStreet/Roles/CobrandEcho.pm
=> [Waste] Clear slots before reserving anew.

perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_sutton_r.t
=> [SLWP] Rename some container types

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste_bromley_bulky.t
=> [Waste] [Bromley] Don't cancel bookings without payment if staff created.

perllib/FixMyStreet/Roles/SCP.pm, t/app/controller/waste_bromley_bulky.t
=> [Waste] Configure separate bulky SCP customer ref.

perllib/FixMyStreet/Roles/Extra.pm, perllib/FixMyStreet/Roles/SCP.pm, perllib/Open311/UpdatesBase.pm
This seemed the smallest change that might work [skip changelog]
=> [Open311] Lock report row whilst processing update.

CHANGELOG.md, web/js/map-OpenLayers.js
https://groups.google.com/a/mysociety.org/g/fixmystreet/c/QD3u2V3q3hA/m/qo4NtgQoAgAJ
=> Keep postcode search bounds

templates/web/base/report/new/form_report.html, templates/web/oxfordshire/report/new/_category_extra_top.html, templates/web/oxfordshire/report/new/form_after_heading.html
https://mysocietysupport.freshdesk.com/a/tickets/3542
=> [Oxfordshire] Don't show video on all report pages

perllib/FixMyStreet/Cobrand/FixMyStreet.pm, perllib/FixMyStreet/Cobrand/Gloucestershire.pm, t/cobrand/gloucestershire.t
https://mysocietysupport.freshdesk.com/a/tickets/3551
=> [Gloucestershire] Request for user to not be able to reopen reports

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/DB/Result/Comment.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, perllib/FixMyStreet/TestMech.pm, t/app/controller/waste_kands_bulky.t
[skip changelog] Plus bit of tidying
=> [Waste] Make sure next day is available when possible

perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/Reporting.pm, t/cobrand/oxfordshire.t
Fixes issue with exact end date matching, and bad dates being supplied to the query.
=> Dashboard date range fix

t/app/controller/waste_brent_small_items.t, t/app/controller/waste_bromley_bulky.t, templates/web/base/waste/bulky/_cancel_details.html, templates/web/base/waste/bulky/cancel_intro.html, templates/web/bromley/waste/bulky/cancel_intro.html
Requested by K&S for theirs, but I think given you could have multiple collections, this is a nice thing to have everywhere. [skip changelog]
=> [Waste] Add collection details to cancellation page.

perllib/FixMyStreet/App/Controller/My.pm, templates/web/base/report/_item.html, templates/web/base/report/_item_small.html
=> Improve performance of shortlist bit more

perllib/FixMyStreet/Cobrand/TfL.pm, t/cobrand/tfl.t
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/4008
=> [TfL] Fix bike companies appearing on red routes.

perllib/FixMyStreet/DateRange.pm
=> Change DateRange methods to attributes.

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Around.pm, perllib/FixMyStreet/App/Controller/Report.pm, t/app/controller/around.t, templates/web/base/admin/config_page_value.html, web/js/duplicates.js
Closes https://github.com/mysociety/societyworks/issues/3889.
=> [FMS] Add support for custom duplicate report radius per category

perllib/FixMyStreet/Cobrand/Merton.pm, t/cobrand/merton.t
=> [Merton] Hide TfL River Piers categories

templates/email/default/waste/csc_payment_failed.html, templates/email/default/waste/csc_payment_failed.txt
=> [WasteWorks] Update phone numbers on payment failed emails

CHANGELOG.md, t/app/model/alert_type.t, templates/email/default/_email_report_list.html
And move the date up to have this metadata above the title. Looking something like
=> Include reference in report list emails.

perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/Reporting.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/northumberland.t
=> [Northumberland] Add response time to CSV export

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, t/app/controller/waste_bromley_bulky.t
[skip changelog] [FD-2623](https://mysocietysupport.freshdesk.com/a/tickets/3623)
=> [Bromley] [Waste] Fix bookings marked payment failed not being cancelled.

perllib/FixMyStreet/App/Form/Field/Checkbox.pm, perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/GardenTandC.pm, perllib/FixMyStreet/App/Form/Waste/SmallItems.pm, t/app/controller/waste_brent_garden.t
And add a Checkbox subclass to make that (and a couple of other places) easier to handle.
Fixes https://mysocietysupport.freshdesk.com/a/tickets/2882 [skip changelog]
=> [Brent] Change text for T&C tickbox

perllib/FixMyStreet/App/Controller/Waste/Echo.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_sutton_r.t
=> [SLWP] Separate out two admins.

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, t/cobrand/highwaysengland.t
=> [National Highways] Include road name in CSV.

t/app/controller/report_display.t, templates/web/fixmystreet-uk-councils/report/banner.html, templates/web/fixmystreet.com/report/banner.html
Matches base template again [skip changelog]
Started from FD-3622
=> [UK] Show state in banner for in progress states.

perllib/FixMyStreet/App/Controller/Admin/Reports.pm, t/app/controller/admin/report_edit.t, templates/web/base/admin/reports/_edit_main.html
If a report is marked as not sent can choose whether to set it as processed or skipped.
https://github.com/mysociety/fixmystreet/issues/3908
=> [FMS] Add a dropdown to the admin to change send_status

t/cobrand/zurich.t
=> [Zürich] Ensure tests pass in early January

perllib/FixMyStreet/DB/ResultSet/Nearby.pm
The easiest way to do this, given all the other query parameter construction going on, seems to be fetch the finished query and replace the table lookup with the materialized CTE of the data, then look up the full rows after to save having to work out how to construct them ourselves. 
I haven't found anywhere where this makes it slower, but I guess conceivably there could be.
It's much quicker without the category filter - having category appears to make pg do a nested loop for every matching problem from nearby and problem from parameters, but without it it does nearby then primary key lookups (same as forcing it to materialize).
Current:
```
bci=# explain analyze
select *
FROM problem_find_nearby( 51.57353, -0.256399, 1) me
JOIN problem
ON problem.id = me.problem_id …
```
=> Materialize the nearby DB query for performance.

perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/bexley.t
=> [Bexley] Include user email in dashboard CSV export

perllib/FixMyStreet/Cobrand/CyclingUK.pm, t/cobrand/cyclinguk.t
=> [Cycling UK] Fix error on /contact form

templates/email/brent/other-reported-garden.html, templates/email/brent/other-reported-garden.txt
[skip changelog] [FD-3746](https://mysocietysupport.freshdesk.com/a/tickets/3746)
=> [Brent] [Waste] Update garden subscription year in email text.

bin/process-inactive-reports, perllib/FixMyStreet/Script/Inactive.pm, t/script/inactive.t, templates/email/default/waste/csc_payment_failed.html, templates/email/default/waste/csc_payment_failed.txt
=> Add category/days/state options to inactive reports script

t/Mock/Tilma.pm, t/app/controller/auth_social.t
Add mySociety::Locale to Mock::Tilma to make sure it's loaded.
Use Mock::Tilma in test
=> Fms add tilma mock to auth social

templates/web/base/waste/bulky/_bin_days_list.html
Make sure buttons aren't buttressing up against lists, and spaced out, fixing some strange nested `div`s inside `dl`. [skip changelog]
Best viewed with whitespace ignored: https://github.com/mysociety/fixmystreet/pull/4819/files?w=1
Before
After
=> [Waste] Improve layout in bulky bin day section.

perllib/Open311/GetServiceRequests.pm
For https://mysocietysupport.freshdesk.com/a/tickets/3742
=> Fetch reports with wards

perllib/FixMyStreet/App/Form/Claims.pm, perllib/FixMyStreet/App/Form/Field/FileIdUpload.pm, t/app/controller/claims.t
=> [Claims] Check non-zero size of uploaded files.

perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days.html
Done as part of https://github.com/mysociety/societyworks/issues/4093.
- Filter out services based on SiteServiceValidFrom/-To
- Prettily display next collection dates
=> BEX005 Bexley WW: Service filters & date munging

perllib/FixMyStreet/App/Controller/Admin.pm
Just a couple of little things to make /admin front page nicer.
=> Admin summary tweaks

t/app/controller/waste_brent_garden.t, templates/email/brent/_garden_data.html, templates/email/brent/other-reported-garden.html, templates/email/brent/other-reported-garden.txt
[skip changelog] [FD-3746](https://mysocietysupport.freshdesk.com/a/tickets/3746)
=> [Brent] Auto update garden sub renewal end year.

templates/web/bexley/footer_extra.html, templates/web/bexley/main_nav_items.html, web/cobrands/bexley/base.scss
Add WasteWorks navigation and stylesheet, along with the "Powered by SocietyWorks" footer.
Fixes https://github.com/mysociety/societyworks/issues/4118
=> [Bexley] WasteWorks branding and styles

perllib/Integrations/Whitespace.pm
=> [Whitespace] Use force_arrayref function.

templates/web/base/offline/drafts.html
Fixes: https://github.com/mysociety/societyworks/issues/4111
Preview:
=> Increased spacing between buttons draft list page

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Around.pm, templates/web/base/around/postcode_form.html, web/cobrands/fixmystreet/offline_report.js, web/cobrands/sass/_base.scss, web/cobrands/sass/_layout.scss, web/js/offline_draft.js
https://github.com/mysociety/fixmystreet/issues/4437
https://github.com/mysociety/fixmystreet/assets/9289297/a4368928-8a27-4a8e-924b-cd40fbd77557
=> Fix restoring a draft without a location.

templates/web/base/waste/missing.html
=> [Brent] Update WasteWorks missing address page

web/cobrands/fixmystreet-uk-councils/assets.js
[skip changelog] [FD-3731](https://mysocietysupport.freshdesk.com/a/tickets/3731)
=> [Bucks] Display last cleaned date for drains in sidebar.

perllib/FixMyStreet/Cobrand/Gloucestershire.pm
https://mysocietysupport.freshdesk.com/a/tickets/3745
=> [Gloucestershire] Update location detail

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t
Enable users to download a .ics file containing their bin collection timetable for the year.
Closes https://github.com/mysociety/societyworks/issues/4097.
=> [Bexley][WW] Pull collections timetable into iCal/.ics file

t/cobrand/bexley.t, templates/web/bexley/report/new/councils_extra_text.html, templates/web/bexley/report/updates-sidebar-notes.html
Request to remove text warning about calls
https://mysocietysupport.freshdesk.com/a/tickets/3838
=> [Bexley] Remove warnings about personal data

templates/web/kingston/main_nav_items.html, templates/web/sutton/main_nav_items.html
https://mysocietysupport.freshdesk.com/a/tickets/3862
=> [SLWP] Update Kingston and Sutton help links

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Report/SLWP.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kands_bulky.t, templates/web/base/waste/bulky/_bin_days_list.html, templates/web/kingston/waste/_service_missed.html, templates/web/sutton/waste/_service_missed.html
=> [SLWP] Add some info to bulky missed collections

t/cobrand/gloucestershire.t, templates/web/base/report/_updates_disallowed_message.html, templates/web/base/report/display.html, templates/web/bristol/report/_updates_disallowed_message.html, templates/web/bromley/report/_updates_disallowed_message.html, templates/web/camden/report/_updates_disallowed_message.html, templates/web/fixmystreet-uk-councils/report/_updates_disallowed_message.html, templates/web/fixmystreet.com/report/_updates_disallowed_message.html
It is possible updates could still come in through integrations, or staff leaving an update, or similar. [skip changelog]
For FD-3756 (and fixes https://github.com/mysociety/societyworks/issues/3944 but that was removed back in November anyway).
=> Clarify closed to updates is from the public.

perllib/FixMyStreet/Cobrand/Northumberland.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, templates/web/cyclinguk/main_nav_items.html, web/cobrands/fixmystreet-uk-councils/assets.js
=> [SLWP] Add new container types

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste.t
=> [Bromley] Hide frequency line from bin day output.

perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kingston.t
[skip changelog] For https://github.com/mysociety/societyworks/issues/4163
=> [Kingston] Different garden renewal cost

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/CobrandEcho.pm, t/app/controller/waste_kingston.t, t/app/controller/waste_sutton_garden.t, templates/web/bromley/waste/garden/subscribe_intro.html, templates/web/kingston/waste/garden/subscribe_intro.html, templates/web/sutton/waste/garden/subscribe_intro.html
=> [Waste] Improve price display on garden intro page.

perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/CobrandBulkyWaste.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_sutton_garden.t
=> [K&S] No reminder if no payment, and encode parameters

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days.html
- Show "Being collected today" when a collection is due today
- Add a "where are your bins located" question to the missed collection form
Part of https://github.com/mysociety/societyworks/issues/4051
=> [Bexley WasteWorks] Missed collections enhancements

bin/bexley/make-bexley-ww-postcode-db, perllib/BexleyAddresses.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t
Closes https://github.com/mysociety/societyworks/issues/4149.
- Includes script for generating SQLite tables from LLPG CSV
- Changes necessitated switching from using Whitespace-specific
AccountSiteID to UPRN
- Check for whether a property has children no longer needed, as
we no longer fetch any parent properties
=> [Bexley][WW] Implement postcode lookup using LLPG data

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/CobrandSLWP.pm
=> [Waste] Let new bin costs use an array.

perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/services_extra.html
- Rename 'Green Wheelie Bin' to 'Rubbish collection' ([Basecamp](https://3.basecamp.com/4020879/buckets/35109031/todos/7182118005))
- Add a couple of "Any issues with your collection service?" links to a Bexley form (https://github.com/mysociety/societyworks/issues/4190)
- Add GGW promo to eligible properties (https://github.com/mysociety/societyworks/issues/4191)
For https://github.com/mysociety/societyworks/issues/4206
=> [Bexley][WW] Various tweaks based on feedback

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/bin_days.html, templates/web/base/waste/bin_days_sidebar.html, templates/web/base/waste/header.html, templates/web/bexley/header_logo.html, templates/web/bexley/waste/_announcement.html, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/services_extra.html, web/cobrands/sass/_waste.scss
Done as part of https://github.com/mysociety/societyworks/issues/4206 .
- Open external links in new tab - https://3.basecamp.com/4020879/buckets/35109031/todos/7249357961
- Display what goes in each container - https://3.basecamp.com/4020879/buckets/35109031/todos/7181913727
- Implement dropdowns for bin location field - https://3.basecamp.com/4020879/buckets/35109031/todos/7181976929 (fixes https://github.com/mysociety/societyworks/issues/4247)
- Amend red tag messaging - https://3.basecamp.com/4020879/buckets/35109031/todos/7255049101
=> Bexley WW Misc fixes pt. 2

templates/web/base/report/new/form_report.html, templates/web/fixmystreet-uk-councils/report/new/category_filter.html, templates/web/fixmystreet.com/report/new/category_filter.html
Fixes https://github.com/mysociety/societyworks/issues/4172
=> [UK] Add category filter to UK council cobrands.

perllib/FixMyStreet/Roles/CobrandSLWP.pm, t/app/controller/waste_kingston_r.t, t/app/controller/waste_sutton_r.t
[skip changelog] https://mysocietysupport.freshdesk.com/a/tickets/4030
=> [Waste] [Sutton] Rename containers.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/cobrand/bromley.t
Commenter name and email to be used to populate the title, name and email for new Event creation
https://github.com/mysociety/societyworks/issues/4232
=> [Bromley] Echo open investigate report text change

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/base/waste/summary_report.html
Fixes for the following small requests:
Also added text for Clinical Waste.
=> Bexley WW Misc fixes pt. 3

t/app/controller/waste_bexley.t, templates/web/bexley/waste/services_extra.html
Part of https://github.com/mysociety/societyworks/issues/4206 .
Fixes https://3.basecamp.com/4020879/buckets/35109031/todos/7167910998.
=> [Bexley][WW] Block garden waste promo for properties with sacks

templates/web/buckinghamshire/footer_extra_js.html, templates/web/buckinghamshire/front/post-steps.html, templates/web/buckinghamshire/front/pre-recent.html, templates/web/buckinghamshire/front/pre-steps.html, web/cobrands/buckinghamshire/layout.scss
=> [Buckinghamshire] Remove winter maintainence video

t/cobrand/bucks.t, templates/web/fixmystreet-uk-councils/about/privacy.html
https://mysocietysupport.freshdesk.com/a/tickets/4114
=> [Bucks] Add Bucks link to privacy page

perllib/FixMyStreet/Cobrand/Merton.pm, t/app/controller/waste_merton.t
=> [Merton] Correctly store second external_id

templates/web/surrey/footer_extra.html, web/cobrands/surrey/_variables.scss, web/cobrands/surrey/base.scss, web/cobrands/surrey/layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/4276
=> [Surrey] Front-end feedback

bin/fixmystreet.com/waste-reconcile-dd, perllib/FixMyStreet/Roles/DDProcessor.pm, t/cobrand/bromley_waste.t
Sometimes we get a renewal through but there's no matching service in the backend. Add an option to push it through with the given quantity. [skip changelog]
=> [Bromley] Add DD option to renew when no service.

perllib/FixMyStreet/Script/Merton/SendWaste.pm, t/app/controller/waste_merton.t
For https://github.com/mysociety/societyworks/issues/4277
=> [Merton] Pass Echo event ID to Crimson when sending reports

web/cobrands/fixmystreet-uk-councils/assets.js
Rights of way has to be excluded from the not on a road stopper or reports can't be made.
Map and server side in .com and society-servers with same branch name
https://mysocietysupport.freshdesk.com/a/tickets/3760
=> [CBeds] Stop road layer triggering for PROW

bin/fixmystreet.com/fetch-waste, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Whitespace.pm, t/app/controller/waste_bexley.t
Closes https://github.com/mysociety/societyworks/issues/4262.
=> [Bexley][WW] Fetch updates for missed collection reports

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Field/Notice.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Script/Merton/SendWaste.pm, t/app/controller/waste_merton.t, t/app/controller/waste_merton_garden.t, templates/web/base/govuk/fields.html, templates/web/base/waste/services.html
[skip changelog] closes https://github.com/mysociety/societyworks/issues/4284
=> [Merton] Add staff-only address change form for garden subscriptions. 

perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/FixMyStreet.pm, t/Mock/MapIt.pm, t/cobrand/bromley.t
Allow bus stops to be reported in Lewisham based on asset feature_id
https://github.com/mysociety/societyworks/issues/4104
=> [Bromley] Allow reporting on 3 assets outside Bromley area

t/app/controller/waste_bromley_bulky.t, templates/web/bromley/waste/enquiry-problem.html, templates/web/bromley/waste/services.html
=> [Bromley][Waste] Move general enquiry form

t/app/controller/waste_bexley.t, templates/web/bexley/waste/_service_missed.html
For https://3.basecamp.com/4020879/buckets/35109031/todos/7411178677#__recording_7465299420
=> [Bexley] Change "missed collections can only be reported..." text

templates/web/camden/report/new/roads_message.html, templates/web/fixmystreet.com/report/new/roads_message.html
=> [Camden] Sign post user elsewhere for housing repairs

templates/web/surrey/before_wrapper.html, templates/web/surrey/tracking_code.html
https://github.com/mysociety/societyworks/issues/4307
Some discussion on things I'm not clear on as this basically replicates Merton:
https://mysociety.slack.com/archives/C06M1A7QXPZ/p1716476520990489
https://mysociety.slack.com/archives/C01TK8P1K8T/p1716538448735839?thread_ts=1716481887.898449&cid=C01TK8P1K8T
=> [Surrey] Adds google tag

perllib/FixMyStreet/Cobrand/Surrey.pm, templates/web/surrey/around/_report_banner.html, templates/web/surrey/before_wrapper.html, templates/web/surrey/tracking_code.html
Surrey FMS: click map wording
https://github.com/mysociety/societyworks/issues/4304
Contact and privacy information
https://github.com/mysociety/societyworks/issues/4305
This is also on servers in `surrey-config` branch
point FMS to tellus.surreycc.gov.uk
https://github.com/mysociety/societyworks/issues/4299
In `surrey-config` 
=> [Surrey] Extra configuration

perllib/FixMyStreet/Cobrand/TfL.pm, t/cobrand/tfl.t
=> [TfL] Allow through TfL as a name if reporting as staff.

perllib/FixMyStreet/Cobrand/Northamptonshire.pm
=> [Northants] Skip sending updates on reports pulled from Alloy.

t/cobrand/brent.t
Deletes report created in one test that is interfering with another test.
=> [Brent] Fixes intermittent test failure

perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston_r.t
=> [Kingston] Fix cost when request has collection.

templates/web/base/around/_on_map_empty.html, templates/web/base/around/tabbed_lists.html
Part of TFL Accessibility audit.
This commit helps screen reader to notify the user once the map results have been updated triggering a change in the number of results.
=> Added aria-live search results in around page

perllib/FixMyStreet/Cobrand/NottinghamshirePolice.pm
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/4387
=> [Notts Police] Move to UK parent class.

perllib/FixMyStreet/Cobrand/NottinghamshirePolice.pm, t/Mock/MapIt.pm, t/cobrand/nottinghamshirepolice.t, templates/email/nottinghamshirepolice/submit.html, templates/email/nottinghamshirepolice/submit.txt, templates/web/base/report/inspect/information.html, templates/web/nottinghamshirepolice/report/inspect/extra_details.html, templates/web/nottinghamshirepolice/report/inspect/public_update.html
=> [Notts Police] Council referral functionality

templates/web/base/waste/services.html
https://mysocietysupport.freshdesk.com/a/tickets/4187
=> [Brent] [Waste] Add garden subscription notice.

perllib/FixMyStreet/Cobrand/TfL.pm
Beginning of pod documentation for TfL Cobrand
=> [TfL] Start pod documentation

perllib/FixMyStreet/App/Form/Waste/Request/Brent.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/Integrations/Echo.pm, t/cobrand/brent.t, templates/web/brent/waste/refuse_extra_container.html
For https://github.com/mysociety/societyworks/issues/4173 [skip changelog]
=> [Brent] Extra container request workflow

templates/web/base/waste/services.html
=> [Brent] Update garden waste extra service text

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
For https://mysocietysupport.freshdesk.com/a/tickets/4308
(Also the last commit on master above this wasn't properly reviewed, as urgent bug fix, but if you had a quick look at that too, thanks.)
=> [Brent] Improve message in referral email.

templates/web/shropshire/report/new/roads_message.html
=> [Shropshire] Tweak not-a-road message.

CHANGELOG.md, perllib/FixMyStreet/DB/Result/User.pm, t/app/controller/report_inspect.t, t/script/inactive.t, templates/web/base/report/inspect/_assignment-options.html
Fixes https://github.com/mysociety/fixmystreet/issues/4855
Also skip blank names in assignment dropdown - last bit of https://github.com/mysociety/fixmystreet/issues/3873
=> Some assignment fixes

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/web/bexley/waste/_service_missed.html
Fixes https://github.com/mysociety/societyworks/issues/4345.
=> [Bexley][WW] Display data for missed collections on bin days page

templates/web/bexley/waste/_bin_days_no_collections.html
closes https://github.com/mysociety/societyworks/issues/4400
Screenshot:
Wireframe spec:
=> [Bexley] Update text for no known waste collections.

perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Cobrand/Hart.pm, perllib/FixMyStreet/Cobrand/Rutland.pm
=> [BathNES] Document cobrand.

t/cobrand/nottinghamshirepolice.t, templates/web/nottinghamshirepolice/contact/_footer.html, templates/web/nottinghamshirepolice/report/_council_sent_info.html
A few little tweaks for things that came up in training.
=> [Notts Police] Training fixes

templates/email/brent/_council_reference.html, templates/email/brent/_council_reference.txt, templates/email/brent/_council_reference_alert_update.html, templates/email/brent/_council_reference_alert_update.txt, templates/email/brent/alert-update.html, templates/email/brent/alert-update.txt, templates/email/brent/other-reported.html, templates/email/brent/other-reported.txt
https://mysocietysupport.freshdesk.com/a/tickets/4272
=> [Brent] Add reference and date to notification emails

web/cobrands/fixmystreet/fixmystreet.js
https://github.com/mysociety/fixmystreet/issues/5047
=> [FMS] Prevent category select error message showing before cats loaded

perllib/FixMyStreet/Cobrand/NorthNorthants.pm, perllib/FixMyStreet/Cobrand/WestNorthants.pm
Fixes https://github.com/mysociety/societyworks/issues/4428 [skip changelog]
=> [Northants] Remove non-area geocoder results.

web/cobrands/fixmystreet/fixmystreet.js, web/cobrands/sass/_multiselect.scss
This lets you toggle all the categories in a group on and off at once.
=> Add toggling via category filter legends.

t/app/controller/waste_bexley.t, templates/web/bexley/waste/_service_missed.html
Fixes https://github.com/mysociety/societyworks/issues/4444
Fixes https://github.com/mysociety/societyworks/issues/4450
=> [Bexley][WW] Couple of minor text changes

db/fixture.sql, perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Choice.pm, perllib/Open311.pm, t/app/controller/waste_bromley_bulky.t, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_merton_bulky.t, t/app/controller/waste_peterborough_bulky.t, t/app/model/problem.t, t/app/model/state.t, t/open311.t, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/intro_amend.html, templates/web/merton/footer_extra.html
5 of the 6 changes requested at https://3.basecamp.com/4020879/buckets/36310026/todolists/7082041259 (except the last).
=> [Merton] Various text tweaks

bin/send-reports
=> Allow send-reports with a specific ID

templates/web/nottinghamshirepolice/footer_extra.html
Fixes https://github.com/mysociety/societyworks/issues/4457.
=> [Notts Police] Update FOI link

docs/_includes/admin-tasks-content.md, templates/web/base/admin/templates/edit.html, templates/web/base/waste/_service_missed_open.html
Text changes from following tickets
https://github.com/mysociety/societyworks/issues/4447
https://github.com/mysociety/societyworks/issues/4458
=> [FMS][WW] Text changes for clarity

templates/web/bromley/tracking_code.html
https://mysocietysupport.freshdesk.com/a/tickets/4405
=> [Bromley] Fix cookie expiry configuration.

perllib/BexleyAddresses.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
=> [Bexley] Add POD documentation to Bexley-related packages

perllib/FixMyStreet/Roles/Cobrand/Adelante.pm, perllib/Integrations/Adelante.pm, t/app/controller/waste_merton_garden.t, templates/web/base/waste/pay_error.html
=> [Adelante] Deal with timeout in payment query.

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Develop.pm, t/app/controller/develop.t, templates/web/base/develop/email_list.html
Closes https://github.com/mysociety/societyworks/issues/4459.
=> Add plain text preview links to /_dev/email

templates/email/default/other-reported.html, templates/email/default/other-reported.txt, templates/email/default/other-updated.html, templates/email/default/other-updated.txt
Text changed in template as doesn't fit with site-name variable https://mysocietysupport.freshdesk.com/a/tickets/4280
=> [NorthNorthants] Email wording change

templates/email/bexley/alert-update.txt
=> [Bexley] Use correct subject line for update emails

perllib/FixMyStreet/Script/Merton/SendWaste.pm
=> [Merton] Set up locale in payment checking.

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Merton.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/Cobrand/BulkyWaste.pm, t/app/controller/waste_merton.t, t/app/controller/waste_merton_bulky.t, templates/web/base/waste/bulky/summary.html
Fixes FD-4472 [skip changelog]
=> [Merton] Remove length limit on waste report data fields.

templates/web/base/around/_report_banner.html, templates/web/base/report/new/fill_in_details_form.html, templates/web/bromley/around/_report_banner.html, templates/web/cyclinguk/around/_report_banner.html, templates/web/greenwich/around/_report_banner.html, templates/web/oxfordshire/around/_report_banner.html, templates/web/shropshire/around/_report_banner.html, templates/web/thamesmead/around/_report_banner.html, web/cobrands/sass/_layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/4483
This new copy for 'Can't use the map...' should provide more context to users with visual impairments.
Current copy:'Can’t use the map? [Skip this step.](https://fixmystreet.cheshireeast.gov.uk/report/new?latitude=53.145324&skipped=1&pc=CW11+1HZ&longitude=-2.370437)' 
Changed to 'Can’t use the map to start a report?
[Skip this step →](https://cheshireeast.fixmystreet.localhost:3000/report/new?pc=&longitude=-1.89801&latitude=52.47766&skipped=1)'
**Preview: `fill_in_details_form.html`**
**Preview for cobrands that are overriding `_report_banner.html`**
Commit: [6c8739d](https://github.com/mysociety/fixmystreet/pull/5109/commits/6c8739dc8177bf222970130a97fdec0548e54fa1)
After we happy with the PR, I'll squash the commits. Currently …
=> Improved copy for 'Can't use the map...'

templates/web/base/auth/general.html, web/cobrands/fixmystreet/fixmystreet.js
Fixes https://github.com/mysociety/societyworks/issues/4484.
=> [Surrey] Display 'password required'-type msg if empty pword

CHANGELOG.md, templates/web/base/admin/config_page.html, templates/web/base/admin/config_page_cobrand.html, templates/web/base/admin/config_page_value.html
Tiny tweaks I noticed in passing
=> [Admin] Config page display tweaks

CHANGELOG.md, templates/web/base/admin/list_updates.html, templates/web/base/admin/problem_row.html, templates/web/base/admin/reports/_edit_main.html, templates/web/base/admin/update_edit.html, templates/web/kingston/admin/problem_row.html, templates/web/sutton/admin/problem_row.html
Fixes https://mysocietysupport.freshdesk.com/a/tickets/4060 as first bit.
Others are just things I noticed while being around there.
=> [Admin] problem/update display tweaks

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Users.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, perllib/FixMyStreet/Script/Inactive.pm, t/script/inactive.t, templates/web/base/admin/reports/_edit_main.html, templates/web/base/admin/users/form.html, templates/web/base/admin/users/index.html
Fixes https://github.com/mysociety/societyworks/issues/4433 in first commit.
Rest was either me clicking around, or wondering why the user page was so slow to load in production.
=> [Admin] Minor user section improvements

t/app/controller/waste_merton.t, t/app/controller/waste_merton_bulky.t, templates/web/merton/waste/_service_missed_open.html
=> [Merton][WW] Change existing missed collection report message

templates/web/hart/around/intro.html, templates/web/hart/index-steps.html, web/cobrands/hart/hart.scss
Some changes to the homepage requested by Harts in FD-4500.
=> [Hart] Homepage updates

perllib/FixMyStreet/Cobrand/Hart.pm, templates/web/hart/footer_extra.html
https://mysocietysupport.freshdesk.com/a/tickets/4524
=> [Hart] User own privacy url

templates/web/surrey/footer_extra.html, templates/web/surrey/footer_extra_js.html
For https://github.com/mysociety/societyworks/issues/4420
=> [Surrey] Add HappyOrNot

perllib/FixMyStreet/Cobrand/Surrey.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/Open311/GetServiceRequests.pm, t/cobrand/surrey.t, templates/email/surrey/_council_reference.html, templates/email/surrey/_council_reference.txt, templates/email/surrey/_council_reference_alert_update.html, templates/email/surrey/_council_reference_alert_update.txt, templates/web/base/report/_council_sent_info.html, templates/web/surrey/footer_extra.html, templates/web/surrey/footer_extra_js.html, templates/web/surrey/report/_updates_disallowed_message.html, templates/web/surrey/tokens/_confirm_problem_council_id.html
This is primarily changes required to support the Boomi integration, though some smaller changes as a result of feedback have also made their way in.
For https://github.com/mysociety/societyworks/issues/4351
=> [Surrey] Open311 changes for Boomi integration

perllib/FixMyStreet/Cobrand/Surrey.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/Open311/GetServiceRequests.pm, t/cobrand/surrey.t, templates/email/surrey/_council_reference.html, templates/email/surrey/_council_reference.txt, templates/email/surrey/_council_reference_alert_update.html, templates/email/surrey/_council_reference_alert_update.txt, templates/web/base/report/_council_sent_info.html, templates/web/surrey/around/_report_banner.html, templates/web/surrey/around/intro.html, templates/web/surrey/before_wrapper.html, templates/web/surrey/footer_extra.html, templates/web/surrey/footer_extra_js.html, templates/web/surrey/report/_updates_disallowed_message.html, templates/web/surrey/tokens/_confirm_problem_council_id.html, templates/web/surrey/tracking_code.html, web/cobrands/surrey/base.scss
- https://github.com/mysociety/societyworks/issues/4300
- https://github.com/mysociety/societyworks/issues/4303
=> [Surrey] Cobrand config

perllib/FixMyStreet/Cobrand/UKCouncils.pm, t/cobrand/surrey.t
=> Ensure cut_off_date is respected if is_two_tier is set

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_garden.t
Matches similar code already present in SLWP.pm. FD-4565 [skip changelog]
=> [Brent] Check presence of garden service unit.

templates/web/base/waste/bin_days.html
[skip changelog] [FD-4559](https://mysocietysupport.freshdesk.com/a/tickets/4559)
=> [Brent] [Waste] Only display collection window on bin page if domestic.

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/App/Controller/Root.pm, t/app/controller/report_new_mobile.t, t/app/controller/report_new_pwa.t
closes https://github.com/mysociety/societyworks/issues/4052
=> Detect if a report was made via PWA.

templates/web/northnorthants/before_wrapper.html, templates/web/northnorthants/header_extra.html, templates/web/northnorthants/tracking_code.html, templates/web/westnorthants/before_wrapper.html, templates/web/westnorthants/tracking_code.html, web/cobrands/northnorthants/_cookies.scss, web/cobrands/northnorthants/base.scss
Add cookie banner from https://github.com/FutureNorthants/CookieBanner
https://mysocietysupport.freshdesk.com/a/tickets/4512
=> Northnorthants add cookie analytics

bin/update-schema, db/downgrade_0088---0087.sql, db/schema.sql, db/schema_0088-add-index-on-problem-created.sql
=> Add index on problem.created.

perllib/FixMyStreet/Cobrand/BathNES.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/DB/Result/Contact.pm, t/cobrand/bathnes.t, templates/web/base/admin/report-category.html
[skip changelog] [FD-4530](https://mysocietysupport.freshdesk.com/a/tickets/4530)
=> [BANES] Prevent staff from assigning a report to a disabled category.

perllib/FixMyStreet/Cobrand/Surrey.pm, t/cobrand/surrey.t, templates/web/base/js/translation_strings.html, templates/web/surrey/footer_extra_js.html, web/cobrands/fixmystreet-uk-councils/council_validation_rules.js, web/cobrands/surrey/js.js
Fixes https://github.com/mysociety/societyworks/issues/4565
=> [Surrey] Disallow email addresses in problem title/detail

t/cobrand/camden.t
Test broken by rebase adding an extra category.
=> [Camden] Fixes broken test

perllib/Open311/GetServiceRequests.pm
=> Fix typo in Open311 GetServiceRequests error output

t/cobrand/peterborough.t, templates/web/fixmystreet.com/report/new/flytipping_text.html, templates/web/peterborough/report/new/flytipping_text.html
=> [Peterborough] Update flytipping messaging

perllib/FixMyStreet/Cobrand/Oxfordshire.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/oxfordshire.t
=> [Oxfordshire] Include staff role in CSV export

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_container_requests.t, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/_services_request.html, templates/web/bexley/waste/services.html
For https://github.com/mysociety/societyworks/issues/4570.
Displays links on bin days for requesting delivery and removal of waste containers.
Also implements a rough version of the first page of the request form.
=> [Bexley][WW] Display links for new container & removal requests

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Request.pm, perllib/FixMyStreet/App/Form/Waste/Request/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_container_requests.t, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/_services_request.html
NOTE: Currently on top of https://github.com/mysociety/fixmystreet/pull/5217 .
For https://github.com/mysociety/societyworks/issues/4575.
=> [Bexley][WW] Implement form for requesting new/replacement containers

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t, templates/email/bexley/waste/_email_data.html, templates/email/bexley/waste/_report_details.txt, templates/email/bexley/waste/_sidebar_content.html, templates/email/bexley/waste/other-reported.html, templates/email/bexley/waste/other-reported.txt, templates/email/bexley/waste/submit.html, templates/email/bexley/waste/submit.txt, templates/email/highwaysengland/submit.txt, templates/web/base/waste/summary_enquiry.html, templates/web/bexley/waste/_bin_days_no_collections.html, templates/web/bexley/waste/_more_services_sidebar.html
Fixes https://github.com/mysociety/societyworks/issues/4585
=> [Bexley] Add communal/no service container request form.

perllib/FixMyStreet/App/Controller/Waste/Whitespace.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
https://github.com/mysociety/societyworks/issues/4095
=> [Bexley] Handle incoming pushed waste updates

perllib/FixMyStreet/Cobrand/BathNES.pm
=> [BANES] Add geocoder override for a particular road

perllib/FixMyStreet/Cobrand/WestNorthants.pm, perllib/FixMyStreet/Roles/Cobrand/Northants.pm
=> [North Northants] Staff can’t bypass stoppers any more

templates/email/bexley/alert-update.html, templates/email/bexley/alert-update.txt, templates/email/bexley/waste/_email_data.html, templates/email/bexley/waste/_report_details.txt, templates/email/bexley/waste/_sidebar_content.html, templates/email/bexley/waste/other-reported.html, templates/email/bexley/waste/other-reported.txt
For https://github.com/mysociety/societyworks/issues/4577.
=> [Bexley][WW] Container request email templates

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_container_requests.t, templates/web/bexley/waste/container_removal_intro.html
https://github.com/mysociety/societyworks/issues/4587
=> [Bexley][WW] Adds message about what containers not collected

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_container_requests.t, templates/web/bexley/waste/_services_request.html
Once removals is on the main branch, I'll rebase the whole 'spot open' to be after it, that's seems cleanest.
=> squash! [Bexley] Spot open container requests.

perllib/FixMyStreet/App/Form/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, perllib/FixMyStreet/Roles/Cobrand/BulkyWaste.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, perllib/FixMyStreet/WorkingDays.pm, t/app/controller/waste_peterborough_bulky.t, t/cobrand/peterborough/bulky-goods/unit.t, templates/email/default/waste/bulky-reminder.html, templates/email/default/waste/bulky-reminder.txt, templates/email/default/waste/other-reported-bulky.html, templates/email/default/waste/other-reported-bulky.txt, templates/email/peterborough/waste/_bulky_extra_text.html, templates/email/peterborough/waste/_bulky_extra_text.txt, templates/web/base/waste/bulky/cannot_book.html, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/intro_amend.html, templates/web/base/waste/bulky/summary.html, templates/web/peterborough/waste/bulky/intro.html, templates/web/peterborough/waste/bulky/intro_amend.html
Fixes https://github.com/mysociety/societyworks/issues/4588 [skip changelog]
=> [Peterborough][Bulky] Add working days to calculations

.cypress/cypress/integration/peterborough.js, bin/fixmystreet.com/fixture, data/test-asset-layers.yml, templates/web/fixmystreet.com/report/new/graffiti_text.html, templates/web/fixmystreet.com/report/new/roads_message.html, templates/web/peterborough/report/new/graffiti_text.html, templates/web/peterborough/report/new/roads_message.html, web/cobrands/fixmystreet-uk-councils/assets.js
=> [Peterborough] Different wording for graffiti on non-Pboro land

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/DB/Result/Problem.pm, t/app/controller/waste_brent_small_items.t, t/app/controller/waste_bromley_bulky.t, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_merton_bulky.t, t/app/controller/waste_peterborough_bulky.t
=> [Bulky] Mark cancelled reports as cancelled.

perllib/FixMyStreet/App/Controller/Admin/Waste.pm, perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, t/app/controller/waste_peterborough_bulky.t, templates/web/base/admin/waste/bulky_items.html, web/cobrands/sass/_admin.scss
- Shrinks sidebar
- Removes per-item price field if feature not enabled
- Uses entire page width for container
For FD-4697
=> [Waste] Bulky items list editing improvements

perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, t/app/controller/waste_sutton_r.t, templates/web/sutton/waste/_announcement.html
[skip changelog] For https://mysocietysupport.freshdesk.com/a/tickets/4781
=> [Sutton] Add message for evening collections.

perllib/FixMyStreet/Cobrand/Bromley.pm, t/app/controller/waste_bromley_bulky.t
=> [Bromley] Do not overwrite other fields in payment fallback.

t/app/controller/waste_bexley.t, templates/email/bexley/waste/_submit_request_enquiry.html, templates/email/bexley/waste/submit.html
Fixes https://3.basecamp.com/4020879/buckets/35109031/todos/8027838324 and https://3.basecamp.com/4020879/buckets/35109031/todos/8028744101
=> fixup! [Bexley] Add communal/no service container request form.

cpanfile, cpanfile.snapshot
=> Upgrade XML::LibXML.

perllib/FixMyStreet/Cobrand/Surrey.pm, t/cobrand/surrey.t
=> [Surrey] Add External ID to CSV export

perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, t/app/controller/waste_kands_bulky.t, t/app/controller/waste_sutton_r.t, templates/web/base/waste/bin_days.html
https://mysocietysupport.freshdesk.com/a/tickets/4787
=> [Sutton] Change bin container text

perllib/FixMyStreet/Cobrand/Surrey.pm, t/app/controller/contact.t
=> [Surrey] Disable reCAPTCHA

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley.t
=> [Bexley] Remove spotting of non-UPRN cab logs.

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, t/cobrand/bucks.t
The server no longer accepts GET requests with a filter. [skip changelog] Fixes FD-4779
=> [Buckinghamshire] Fix WFS lookups to use POST.

CHANGELOG.md, perllib/FixMyStreet/App/Controller/Admin/Reports.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
=> Improve speed of admin update email search

web/cobrands/fixmystreet-uk-councils/assets.js, web/cobrands/merton/base.scss
Feedback on https://mysocietysupport.freshdesk.com/a/tickets/4728
Companion branch with same name on servers
=> [Merton] Make recycling points more obvious

perllib/FixMyStreet/Cobrand/Brent.pm, t/app/controller/waste_brent_garden.t, templates/web/brent/waste/garden/subscribe_intro.html
[skip changelog] For https://github.com/mysociety/societyworks/issues/4647
=> [Brent] Remove half-price end of 2024.

perllib/FixMyStreet/App/Form/Waste/Request/Merton/Larger.pm, t/app/controller/waste.t, t/app/controller/waste_kingston_r.t, templates/web/base/waste/summary_request.html
=> [Kingston] Show removals on request summary page.

perllib/FixMyStreet/Cobrand/Peterborough/Bulky.pm, t/app/controller/waste_peterborough_bulky.t
If we are coming back after failed payment or similar, make sure we're still within the time limit. [skip changelog]
=> [Peterborough] Check cutoff time in bulky slots.

templates/web/brent/waste/refuse_call_us.html
For https://mysocietysupport.freshdesk.com/a/tickets/4939.
=> [Brent][Waste] Update bin pricing text from 1st Jan 25.

perllib/FixMyStreet/Cobrand/Bromley.pm
For https://mysocietysupport.freshdesk.com/a/tickets/4940.
=> [Bromley] Allow image sending on all Echo categories

templates/web/brent/waste/refuse_call_us.html
- Add paragraph explaining the Council's legal authority to charge for general waste bins, with link to Section 46 of the Environmental Protection Act 1990.
- Text tweak in the bin costs list
For FD-4939
=> [Brent] Add link to bin charging legislation

.cypress/cypress/integration/peterborough.js, web/cobrands/fixmystreet-uk-councils/roadworks.js, web/js/map-OpenLayers.js
For https://github.com/mysociety/societyworks/issues/4728
=> [Street Manager] Only update layer when pin placed.

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP.pm
Shouldn't be any changes bar the addition of constants [skip changelog]
=> [Waste] Use constants for more Echo IDs.

t/cobrand/brent.t, templates/web/brent/waste/refuse_call_us.html
https://mysocietysupport.freshdesk.com/a/tickets/5028
=> [Brent] [Waste] General waste bin signposting text changes.

perllib/FixMyStreet/Cobrand/Hylte.pm
=> [Hylte] Remove two redundant overrides

perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, t/app/controller/waste_kands_bulky.t
Asked for at https://3.basecamp.com/4020879/buckets/40355775/todos/8248864814#__recording_8252677936
=> [Sutton] Only allow bulky if service unit present.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/App/Form/Claims.pm, perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, perllib/FixMyStreet/App/Form/Waste/SmallItems.pm, perllib/FixMyStreet/App/Form/Wizard.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP.pm, t/app/controller/waste_kingston_r.t
=> [Kingston/Sutton] Few refactor tweaks

perllib/FixMyStreet/Cobrand/Bristol.pm
Role and sub necessary for sending updates
=> [Bristol] Adds Open311Multi role

perllib/FixMyStreet/Cobrand/Bristol.pm, t/cobrand/bristol.t
=> [Bristol] Send email for witnessed flytipping.

perllib/FixMyStreet/Cobrand/Northumberland.pm
Restrict searches to the UK
https://github.com/mysociety/societyworks/issues/4500
=> [Northumberland] Add defaults to geolocation

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/AccessPaySuiteBankDetails.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Cobrand/Default.pm, perllib/FixMyStreet/Roles/Cobrand/AccessPaySuite.pm, perllib/Integrations/AccessPaySuite.pm, t/app/controller/waste_bexley_garden.t, templates/web/base/waste/bank_details.html, web/cobrands/fixmystreet/fixmystreet.js
- Add support for internal Direct Debit processing in Bexley
- Implement new direct_debit_internal method in Waste controller
- Add direct_debit_collection_method method to Default and Bexley cobrands
- Update garden subscription form to handle internal Direct Debit flow
- Add bank details form validation and formatting
- Add tests for Direct Debit submission process
Part of https://github.com/mysociety/societyworks/issues/4612
See `0a4474f5a` in servers repo for development/staging config.
=> [Bexley] Internal Direct Debit collection method for GGW

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/WasteWorks/Costs.pm, t/app/controller/waste_bexley_garden.t, t/wasteworks/costs.t, templates/web/base/waste/garden/_bin_quantities.html, templates/web/base/waste/garden/subscribe_details.html, templates/web/base/waste/garden/subscribe_details_bin_desc.html, templates/web/base/waste/header.html, web/cobrands/bexley/waste.js, web/js/waste.js
https://github.com/mysociety/societyworks/issues/4788
Servers branch is `bexley-ggw-first-bin-discount-staging`.
https://github.com/user-attachments/assets/61a51b2a-60fa-4cb4-8e05-2668ceb45654
=> [Bexley][WW] Discount cost of the first GGW bin if payment method is DD.

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t
Ensures reports are confirmed after DD is set up so they get sent to Agile
=> [Bexley] GGW - Confirm DD reports

perllib/FixMyStreet/App/Form/Waste/Request/Peterborough.pm, t/app/controller/waste_peterborough.t
This form is staff only. FD-5110 [skip changelog]
=> [Peterborough] Move request extra details box.

perllib/FixMyStreet/DB/Result/Contact.pm, perllib/FixMyStreet/SendReport/Email.pm, perllib/FixMyStreet/SendReport/Email/Highways.pm, perllib/FixMyStreet/SendReport/Zurich.pm, t/cobrand/bristol.t, t/cobrand/highwaysengland.t, templates/email/buckinghamshire/submit.html, templates/email/buckinghamshire/submit.txt, templates/email/default/cy/submit.html, templates/email/default/cy/submit.txt, templates/email/default/submit.html, templates/email/default/submit.txt, templates/email/fixmystreet.com/cy/submit.html, templates/email/fixmystreet.com/cy/submit.txt, templates/email/fixmystreet.com/submit.html, templates/email/fixmystreet.com/submit.txt, templates/email/highwaysengland/submit.html, templates/email/highwaysengland/submit.txt, templates/email/nottinghamshirepolice/submit.html, templates/email/nottinghamshirepolice/submit.txt
Removes some duplicate output from NH emails, uses better output for extra questions for Bristol flytipping (and anywhere else extra data is included in emails).
=> Improvements to extra data in submit email

t/cobrand/bristol.t, templates/email/buckinghamshire/submit.html, templates/email/buckinghamshire/submit.txt, templates/email/default/cy/submit.html, templates/email/default/cy/submit.txt, templates/email/default/submit.html, templates/email/default/submit.txt, templates/email/fixmystreet.com/cy/submit.html, templates/email/fixmystreet.com/cy/submit.txt, templates/email/fixmystreet.com/submit.html, templates/email/fixmystreet.com/submit.txt, templates/email/highwaysengland/submit.html, templates/email/highwaysengland/submit.txt, templates/email/nottinghamshirepolice/submit.html, templates/email/nottinghamshirepolice/submit.txt
The IF check in the template was skipping fields with a value of "0". [skip changelog]
=> Fix for value labels in email where value is 0.

perllib/FixMyStreet/Cobrand/CyclingUK.pm, t/cobrand/cyclinguk.t
[skip changelog] For https://mysocietysupport.freshdesk.com/a/tickets/5149
=> [CyclingUK] Follow .com questionnaire policy.

perllib/FixMyStreet/App/Form/Waste/Garden/Cancel/Bexley.pm, perllib/FixMyStreet/App/Form/Waste/GardenTandC.pm, templates/email/default/waste/other-reported-garden.html, templates/email/default/waste/other-reported-garden.txt, templates/web/base/waste/garden/subscribe_details_bin_desc.html, templates/web/base/waste/garden/subscribe_existing_bin_desc.html, templates/web/bexley/waste/garden/cancel.html, templates/web/bexley/waste/garden/subscribe_intro.html
For https://github.com/mysociety/societyworks/issues/4562, for https://github.com/mysociety/societyworks/issues/4676.
=> [Bexley] GGW various text fixes

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, t/app/controller/waste_bexley_garden.t, templates/email/default/waste/_garden_data.html, templates/web/bexley/waste/_more_services_sidebar.html, templates/web/bexley/waste/services_extra.html
For https://github.com/mysociety/societyworks/issues/4789
=> [Bexley][WW] Refactor GGW eligibility; ensure communal properties can't sign up

perllib/FixMyStreet/Roles/Cobrand/AccessPaySuite.pm, t/app/controller/waste_bexley_garden.t
For https://3.basecamp.com/4020879/buckets/40373795/todos/8370902383.
=> [Bexley][WW] Make sure DD date falls on 28th of month

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/App/Form/Waste/AccessPaySuiteBankDetails.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew/Bexley.pm, perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t
For https://3.basecamp.com/4020879/buckets/40373795/todos/8354919506
=> [Bexley][WW] Add DD bank details page for GGW renewals

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t, templates/web/base/waste/_services_garden_current.html
=> [Bexley] Treat a RENEWALDUE contract as renewed.

perllib/FixMyStreet/Roles/Cobrand/AccessPaySuite.pm, t/app/controller/waste_bexley_garden.t
=> Fixup! [Bexley][WW] Make sure DD date falls on 28th of month

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, t/app/controller/waste_bexley_garden.t
For https://3.basecamp.com/4020879/buckets/40373795/todos/8387841662
=> [Bexley][WW] Show pending DD amount on GGW subscriptions

perllib/FixMyStreet/App/Form/Waste/Request/Kingston.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, t/app/controller/waste_kingston_r.t, templates/web/kingston/waste/request/intro.html
[skip changelog] https://github.com/mysociety/societyworks/issues/4784
=> [Kingston] Container pricing work.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, t/app/controller/waste_sutton_r.t, templates/email/default/waste/other-reported.html, templates/email/default/waste/other-reported.txt, templates/web/base/waste/services.html, templates/web/base/waste/summary_enquiry.html, templates/web/sutton/waste/enquiry-problem.html
[skip changelog] https://github.com/mysociety/societyworks/issues/4727
=> [Sutton] Report problem functionality

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Roles/Cobrand/AccessPaySuite.pm, t/app/controller/waste_bexley_garden.t
=> [Bexley][WW] Implement check for existing GGW direct debit

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Kingston.pm, perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP2.pm, perllib/FixMyStreet/Roles/Cobrand/Waste.pm, t/app/controller/waste_kingston.t, t/app/controller/waste_sutton_garden.t
Fixes https://github.com/mysociety/societyworks/issues/4826 [skip changelog]
=> [SLWP] Make a container removal event if decrease in garden bins

t/cobrand/surrey.t, templates/web/surrey/_email_sent_confirmation_text.html
=> [Surrey] Update confirmation page wording

CHANGELOG.md, bin/export-import-data
Adds send_method to the data exported and imported for categories.
https://github.com/mysociety/societyworks/issues/4818
=> [FMS] export-import-data script include send_method

templates/email/default/waste/other-reported.html, templates/email/default/waste/other-reported.txt, templates/email/kingston/alert-update.html, templates/email/kingston/alert-update.txt
Fixes https://mysocietysupport.freshdesk.com/a/tickets/5247 [skip changelog]
=> [Kingston] Remove track link during switchover.

perllib/FixMyStreet/Cobrand/Bristol.pm
=> [Bristol] Update pin colours

perllib/FixMyStreet/App/Controller/Admin/Triage.pm, perllib/FixMyStreet/App/Controller/Reports.pm, t/app/controller/admin/triage.t
=> Include private reports in triage list

perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, t/app/controller/waste_bexley_garden.t
Fixes https://3.basecamp.com/4020879/buckets/40373795/todos/8421052820
=> [Bexley] Fix DD renewal summary cost display

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/Cobrand/Bexley/Waste.pm, perllib/Integrations/Agile.pm, t/app/controller/waste_bexley_container_requests.t, t/app/controller/waste_bexley_garden.t
=> [Bexley] If no Agile, but Whitespace, remove Whitespace.

perllib/FixMyStreet/Cobrand/Merton/Waste.pm, perllib/FixMyStreet/Script/Merton/SendWaste.pm, t/app/controller/waste_merton.t
=> [Merton] Don’t retry if no Echo ID returned.

perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Renew.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/FixMyStreet/Roles/Cobrand/Waste.pm, t/app/controller/waste_brent_garden.t, t/app/controller/waste_kingston.t, t/app/controller/waste_merton_garden.t, t/app/controller/waste_sutton_garden.t, templates/web/base/waste/garden/_payment_field.html
Fixes https://github.com/mysociety/societyworks/issues/4852 [skip changelog]
Fixes https://3.basecamp.com/4020879/buckets/40355775/todos/8274014948
=> [Merton] Changes for garden payments, remove payment method if unneeded

perllib/FixMyStreet/App/Form/Waste/Garden/EmailRenewalReminders.pm
=> [Brent] Change reminder to opt-out rather than opt-in

perllib/FixMyStreet/Cobrand/Bristol.pm, t/cobrand/bristol.t
Fixes https://mysocietysupport.freshdesk.com/a/tickets/5281
=> [Bristol] Check parks layer for flytipping reports.

.cypress/cypress/integration/oxfordshire.js, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, t/cobrand/oxfordshire.t, templates/web/oxfordshire/report/inspect/_raise_defect.html
https://github.com/mysociety/societyworks/issues/4847 [skip changelog]
=> [Oxfordshire] Add more fields to defect form.

perllib/FixMyStreet/Cobrand/Bristol.pm, t/cobrand/bristol.t
[skip changelog] Follow on in FD-5281, so all get the side email
=> [Bristol] Send flytipping witness email for parks.

bin/access-paysuite-callback-url
Think this is the crucial line for running this script.
Also removed some of the guidance as was related to further development of the script that hasn't happened yet.
=> fixup! [PaySuite][Bexley] Adds script to add webhook and call

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm
Fixes https://github.com/mysociety/societyworks/issues/4882
=> [Bexley][WW] Handle '400' errors from Agile

perllib/FixMyStreet/Cobrand/Bexley/Garden.pm, perllib/FixMyStreet/SendReport/Email.pm, t/app/controller/waste_bexley_garden.t
For https://github.com/mysociety/societyworks/issues/4824.
=> [Bexley][WW] Tidy tests & code to remove warnings

perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/DB/Result/Problem.pm, perllib/Open311.pm, t/cobrand/bromley.t
For https://github.com/mysociety/societyworks/issues/4812 & FD-5114.
=> [Bromley] Upload static map image to Echo when sending reports

perllib/FixMyStreet/App/Form/Waste/GardenTandC.pm
For https://mysocietysupport.freshdesk.com/a/tickets/5339.
=> [Brent][GGW] Add text to T&Cs.

perllib/FixMyStreet/Cobrand/Brent.pm
The name needed updating after it was changed in https://github.com/mysociety/societyworks/issues/4398.
For https://mysocietysupport.freshdesk.com/a/tickets/5353.
Verified on staging.
=> [Brent] Fix lookups verge categories.

templates/web/peterborough/waste/_service_missed.html
https://mysocietysupport.freshdesk.com/a/tickets/5273
=> [Peterborough][WW] Update wording when can't report missed collection.

perllib/FixMyStreet/App/Form/Waste/Garden.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm, t/app/controller/waste_kingston.t, t/app/controller/waste_merton_garden.t
The correct amount was being charged, but the summary page was listing an admin fee for sacks when there shouldn't be one. [skip changelog] Fixes the bug part of FD-5366
=> [Waste] Fix summary cost display of admin fee.

perllib/Integrations/AccessPaySuite.pm
For https://3.basecamp.com/4020879/buckets/40373795/todos/8408739630#__recording_8475079927
=> [Bexley][WW] Pass empty data hashref for AccessPaySuite contract archive

templates/web/hart/around/intro.html
=> [Hart] Update homepage text

web/cobrands/fixmystreet-uk-councils/assets.js
https://mysocietysupport.freshdesk.com/a/tickets/4882
Servers branch: `bristol-gullies-message`.
=> [Bristol] Show message for cyclically cleansed gullies.

perllib/FixMyStreet/Cobrand/Aberdeenshire.pm
For https://github.com/mysociety/societyworks/issues/4734
=> [Aberdeenshire] Enable OIDC login

perllib/FixMyStreet/App/Controller/Report.pm, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, t/app/controller/report_inspect.t, t/cobrand/oxfordshire.t, templates/web/oxfordshire/report/inspect/_extra_details_field.html, templates/web/oxfordshire/report/inspect/_raise_defect.html
=> [Oxfordshire] Rename traffic management field.

perllib/FixMyStreet/Cobrand/Peterborough.pm, t/cobrand/peterborough.t
[skip changelog] Fixes FD-5438
=> [Peterborough] Fix closure update for graffiti categories.

perllib/FixMyStreet/Cobrand/Bristol.pm, t/cobrand/bristol.t
https://mysocietysupport.freshdesk.com/a/tickets/5241
=> [Bristol] Add Flytipping size to csv export

perllib/FixMyStreet/App/Controller/Root.pm, templates/web/base/around/postcode_form.html, templates/web/base/index.html, templates/web/northnorthants/front/front-main-message.html, web/cobrands/northnorthants/base.scss, web/cobrands/northnorthants/layout.scss
Fixes: https://github.com/mysociety/societyworks/issues/4883
=> [NorthNorthants] Added one.network message

perllib/FixMyStreet/Template/JS.pm
closes https://github.com/mysociety/societyworks/issues/4807
=> [Glos][Gloucestershire] Include each other's asset layers.

perllib/FixMyStreet/Cobrand/Bexley.pm, t/cobrand/bexley.t
Fixes FD-5474 [skip changelog]
=> [Bexley] Include UPRN and payment method in CSV.

perllib/FixMyStreet/Cobrand/Gloucester.pm, t/Mock/MapIt.pm, t/cobrand/gloucester.t
Closes https://github.com/mysociety/societyworks/issues/4952.
=> [Glos City] Send an email for Open311 categories where activity witnessed

perllib/FixMyStreet/App/Controller/Report/New.pm, perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/Bromley.pm, perllib/FixMyStreet/Roles/Cobrand/DDProcessor.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, t/app/controller/waste_bromley_bulky.t, t/app/controller/waste_kingston_r.t, t/app/controller/waste_merton.t, t/app/controller/waste_sutton_r.t, t/cobrand/bristol.t, t/cobrand/bromley_waste.t, templates/web/fixmystreet-uk-councils/about/waste-calendar.html
Fixes all of FD-5462 FD-5509 FD-5511 FD-5512
=> Small client support things

perllib/FixMyStreet/Roles/Syslog.pm
Syslog has a global ident, which we use to send to different outputs, so we call openlog on each log to make sure the ident is the correct one. We are not using `ndelay`, so only one connection should be made, at the first log. [skip changelog]
=> Force syslog to use current ident.

perllib/FixMyStreet/Cobrand/Gloucester.pm
Closes https://github.com/mysociety/societyworks/issues/4932.
=> [Glos City] Set zoom level to 3

templates/web/fixmystreet.com/about/understanding-report-data.html
A new page to link to from various places explaining what FixMyStreet data can and can't tell you in a bid to discourage use of FMS data in clickbait comparison articles [skip changelog]
=> Create new page about understanding report data.html

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
Prevent caching across page reloads
https://github.com/mysociety/societyworks/issues/4987
=> [Bexley] Adds clear_cached_lookups_property

perllib/FixMyStreet/App/Form/Waste/Garden/Sacks/Choice.pm, t/app/controller/waste_bexley.t, t/cobrand/sutton.t, templates/web/base/admin/reports/_edit_waste.html, templates/web/base/waste/garden/subscribe_existing_bin_desc.html, templates/web/base/waste/index.html, templates/web/sutton/waste/garden/renew_bin_desc.html
Fixes FD-5558, FD-5557, FD-5549 [skip changelog]
=> [Sutton] Small bin things

perllib/FixMyStreet/Cobrand/IsleOfWight.pm, perllib/FixMyStreet/Cobrand/Oxfordshire.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, perllib/FixMyStreet/DB/Result/Problem.pm
For https://3.basecamp.com/4020879/buckets/39821225/card_tables/cards/8725550561 and https://3.basecamp.com/4020879/buckets/39821225/card_tables/cards/8730621495
=> [Aberdeenshire] front end text tweaks

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
=> [Bexley] Use correct key when clearing cache.

CHANGELOG.md, bin/update-schema, conf/general.yml-example, db/downgrade_0090---0089.sql, db/downgrade_0091---0090.sql, db/schema.sql, db/schema_0091-add-abuse-columns.sql, perllib/FixMyStreet/App/Controller/Admin.pm, perllib/FixMyStreet/DB/Result/Abuse.pm, perllib/FixMyStreet/DB/ResultSet/Abuse.pm, perllib/FixMyStreet/Email.pm, perllib/FixMyStreet/Roles/DB/Abuser.pm, perllib/FixMyStreet/Script/Alerts.pm, t/app/model/abuse.t
For https://github.com/mysociety/societyworks/issues/4947
=> Add way to check domains against usercheck

perllib/BexleyAddresses.pm, perllib/FixMyStreet/App/Form/Waste/Garden/Bexley.pm, t/app/controller/waste_bexley.t, t/app/controller/waste_bexley_garden.t
And a tweak for display, didn't end up using, but think this more pedantically accurate
=> [Bexley] Prefill DD address form

templates/web/aberdeenshire/tracking_code.html
Not working.
For https://github.com/mysociety/societyworks/issues/4954.
=> WIP [Aberdeenshire] cookies analytics

web/cobrands/highwaysengland/assets.js, web/cobrands/tfl/js.js
=> [TfL, NH] Adjust raster layers for BNG projection.

perllib/FixMyStreet/Cobrand/Bristol.pm, t/cobrand/bristol.t
Fixes https://github.com/mysociety/societyworks/issues/4970 [skip changelog]
=> [Bristol] Treat Long Ashton P&R site as Bristol.

perllib/FixMyStreet/Cobrand/Aberdeenshire.pm, t/Mock/MapIt.pm, t/cobrand/aberdeenshire.t, templates/web/aberdeenshire/about/faq-en-gb.html, templates/web/aberdeenshire/around/intro.html
- [Include Confirm ID in CSV export](https://3.basecamp.com/4020879/buckets/39821225/card_tables/cards/8773704929)
- [Update front page text](https://3.basecamp.com/4020879/buckets/39821225/card_tables/cards/8726588685)
- [Don't show state change in update emails](https://3.basecamp.com/4020879/buckets/39821225/card_tables/cards/8767689203)
- [Update FAQ](https://3.basecamp.com/4020879/buckets/39821225/card_tables/cards/8730562339)
=> [Aberdeenshire] Some post-go-live fixes

perllib/FixMyStreet/Cobrand/Gloucester.pm
For https://3.basecamp.com/4020879/buckets/38208405/todos/8798164676.
=> [Glos City] Add custom pin colours

perllib/FixMyStreet/Cobrand/Gloucester.pm, t/cobrand/gloucester.t
=> [Glos City] Remove unused open311_post_send

perllib/FixMyStreet/Cobrand/Shropshire.pm, perllib/FixMyStreet/Script/CSVExport.pm, t/cobrand/shropshire.t
https://mysocietysupport.freshdesk.com/a/tickets/5658
=> [Shropshire] Add subscribers to csv export

perllib/FixMyStreet/Cobrand/Gloucester.pm, templates/web/aberdeenshire/report/new/after_photo.html, templates/web/base/tokens/confirm_problem.html, templates/web/gloucester/report/new/after_photo.html
For https://3.basecamp.com/4020879/buckets/38208405/todos/8758827925
and https://3.basecamp.com/4020879/buckets/38208405/todos/8822257240
=> [Gloucester] Text tweaks

templates/email/bristol/_council_reference.html, templates/email/bristol/_council_reference.txt
https://mysocietysupport.freshdesk.com/a/tickets/5417
=> [Bristol] Add FMS reference to emails

perllib/FixMyStreet/Cobrand/Aberdeenshire.pm, perllib/Open311/UpdatesBase.pm, t/cobrand/aberdeenshire.t, t/open311/getservicerequestupdates.t
For https://github.com/mysociety/societyworks/issues/5043
Depends on open311-adapter running https://github.com/mysociety/open311-adapter/pull/429
=> [Aberdeenshire] Pass category changes both ways between Confirm/FMS

perllib/FixMyStreet/App/Form/Waste.pm, t/app/controller/waste_peterborough_bulky.t
=> [Peterborough] Mandatory phone number for bulky.

perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, perllib/FixMyStreet/Cobrand/Bexley/Bulky.pm, t/app/controller/waste_bexley_bulky.t, web/js/waste.js
For
https://3.basecamp.com/4020879/buckets/42017522/card_tables/cards/8906892575
https://3.basecamp.com/4020879/buckets/42017522/card_tables/cards/8906983221
https://3.basecamp.com/4020879/buckets/42017522/card_tables/cards/8911434262
=> [Bexley][Bulky] Item & date page changes

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm
=> [Echo] Skip event lookups for calendar.

perllib/FixMyStreet/App/Controller/Waste.pm, perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Roles/Cobrand/KingstonSutton.pm, perllib/FixMyStreet/Roles/Cobrand/SLWP2.pm, perllib/Integrations/Echo/Events.pm, t/app/controller/waste_sutton_small_items.t, templates/web/base/waste/summary_report.html
Fixes https://github.com/mysociety/societyworks/issues/4925 .
=> [Sutton] Missed collections for small items

.cypress/cypress/integration/buckinghamshire.js, .cypress/cypress/integration/highways.js, .cypress/cypress/integration/highwaysengland.js, .cypress/cypress/integration/hounslow.js, .cypress/cypress/integration/northamptonshire.js, .cypress/cypress/integration/regressions.js, .cypress/cypress/integration/tfl.js, templates/web/base/reports/_bulk-assign.html, web/cobrands/highwaysengland/_colours.scss, web/cobrands/sass/_layout.scss, web/cobrands/sass/_report_list.scss, web/cobrands/zurich/_colours.scss
Fixes: https://github.com/mysociety/societyworks/issues/3784
Replaces: https://github.com/mysociety/fixmystreet/pull/4566/
https://github.com/user-attachments/assets/d9e14f46-c752-49ef-a5b9-d44a6a58c25e
https://github.com/user-attachments/assets/f89eb283-21f9-4a5d-b900-f06572528a45
https://github.com/user-attachments/assets/c0b074b3-393f-486a-bfc7-33841ab96773
https://github.com/user-attachments/assets/8863268d-c8b0-46d3-a949-e6bbaba9810f
https://github.com/user-attachments/assets/fd934dae-6e05-45ef-8d82-a472cc50e41f
=> Improve tablet breakpoints on map page

templates/web/zurich/about/faq-de-ch.html
=> [Zürich] Update email address on FAQ page

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm, t/app/controller/admin/bodies.t, t/app/controller/sample.txt, templates/web/base/admin/bodies/form.html
Closes https://github.com/mysociety/societyworks/issues/5089.
=> Allow an image upload for a body

perllib/FixMyStreet/Cobrand/Brent.pm, perllib/FixMyStreet/Cobrand/Bristol.pm, perllib/FixMyStreet/Cobrand/Buckinghamshire.pm, perllib/FixMyStreet/Cobrand/Camden.pm, perllib/FixMyStreet/Cobrand/Hackney.pm, perllib/FixMyStreet/Cobrand/HighwaysEngland.pm, perllib/FixMyStreet/Cobrand/Southwark.pm, perllib/FixMyStreet/Cobrand/TfL.pm, perllib/FixMyStreet/Cobrand/Thamesmead.pm, perllib/FixMyStreet/Cobrand/UKCouncils.pm, perllib/FixMyStreet/Roles/Cobrand/OpenUSRN.pm, t/Mock/Tilma.pm, t/cobrand/bucks.t, t/cobrand/fixmystreet.t, t/cobrand/hackney.t, t/cobrand/merton.t, t/cobrand/northumberland.t, web/cobrands/fixmystreet-uk-councils/assets.js
For https://github.com/mysociety/societyworks/issues/4985
For https://github.com/mysociety/societyworks/issues/5012
=> [Bucks] Asset layer code

perllib/Open311/GetServiceRequests.pm
=> [Confirm] Skip $updated date check for Confirm defects

perllib/FixMyStreet/Cobrand/Lincolnshire.pm, t/cobrand/lincolnshire.t
https://mysocietysupport.freshdesk.com/a/tickets/5960
=> [FMS][Lincs] Add user id to csv export

perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm, perllib/FixMyStreet/Cobrand/Bexley/Bulky.pm, perllib/FixMyStreet/Roles/Cobrand/BulkyWaste.pm, t/app/controller/waste_bexley_bulky.t, templates/web/base/waste/bulky/intro.html, templates/web/base/waste/bulky/items.html, templates/web/base/waste/bulky/summary.html
=> [Bexley] More notices for Saturday collections.

perllib/FixMyStreet/Cobrand/Sutton.pm, perllib/Integrations/Whitespace/Booking.pm, t/app/controller/waste_bexley_bulky.t, templates/web/base/waste/bin_days.html
=> [Waste] Sutton small item tweaks, Bexley slot fix

templates/web/base/waste/garden/subscribe_confirm.html, templates/web/kingston/waste/garden/subscribe_confirm.html, templates/web/sutton/waste/garden/subscribe_confirm.html
Spotted by Bexley in [this Basecamp todo](https://3.basecamp.com/4020879/buckets/40373795/todos/8525903050).
=> [WW] Fix typo on garden waste amend confirmation page

perllib/FixMyStreet/Cobrand/Bexley/Waste.pm
Given this appears to be slow at present. I don't think this has any issues in terms of stale caches, but not sure if I'm missing something. Perhaps they'll fix the slowness and it won't be needed, but guess it shouldn't hurt. [skip changelog]
=> [Bexley] Cache GetSiteWorksheets call in session.

perllib/FixMyStreet/App/Controller/Waste/Bulky.pm, perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm, perllib/FixMyStreet/Cobrand/Rutland.pm, perllib/FixMyStreet/Roles/Cobrand/Echo.pm, templates/web/base/waste/bin_days.html, templates/web/sutton/waste/small_items/intro.html, templates/web/sutton/waste/small_items/intro_amend.html
Hopefully all self-explanatory
=> A variety of things, sorry

perllib/FixMyStreet/App/Controller/Around.pm, t/app/controller/around.t
Around filter show categories with same display name when in different categories.
https://mysocietysupport.freshdesk.com/a/tickets/5885
=> [Brent][FMS] Allow duplicate display names in different categories

perllib/FixMyStreet/Cobrand/Brent.pm, t/cobrand/brent.t
For https://mysocietysupport.freshdesk.com/a/tickets/6091
=> [Brent] Auto re-send when category changed from Atak to Echo.
