perllib/FixMyStreet/Cobrand/EastSussex.pm

[EastSussex] disable questionnaires

---

web/js/map-OpenLayers.js

This updates map-OpenLayer.js for the current norwegian translation, so show/hide pins and show/hide old will work with Norwegian language.

Fixed show/hide pins and show/hide old for norwegian cobrand.

---

templates/web/fixmystreet.com/static/posters.html

Add tracking of download clicks for the goodies page

---

perllib/FixMyStreet/Geocode.pm
perllib/FixMyStreet/Geocode/Bing.pm
perllib/FixMyStreet/Geocode/FixaMinGata.pm
perllib/FixMyStreet/Geocode/Google.pm
perllib/FixMyStreet/Geocode/OSM.pm
perllib/FixMyStreet/Geocode/Zurich.pm

Refactor geoloction caching code into one function.
Fixes #684

Expire cached geolocations after a week.

---

.travis.yml
.travis/after_script
.travis/install
cpanfile
cpanfile.snapshot
perllib/FixMyStreet/App/Controller/Photo.pm

Speed up travis (and try to remove as much sudo as possible), by:
* Put Locale::gettext in cpanfile.
* Installing boto via pip, only when needed.
* Not installing GMP and not warning if it's not present
* Not minding if jhead isn't present.

Travis bits

---

templates/web/stevenage/header.html
templates/web/stevenage/tracking_code.html

[Stevenage] tracking code

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Harrogate.pm
templates/web/harrogate/report/new/after_category.html
web/cobrands/harrogate/base.scss

see https://github.com/mysociety/FixMyStreet-Commercial/issues/703

Harrogate: link NYCC incidents to appropriate form on council website

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Tokens.pm
perllib/FixMyStreet/Cobrand/Harrogate.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Roles/Extra.pm
perllib/FixMyStreet/SendReport/Open311.pm
perllib/Open311.pm
perllib/Open311/PopulateServiceList.pm
t/app/controller/report_new.t
t/app/controller/report_new_open311.t
t/app/controller/token.t
t/app/model/extra.t
t/cobrand/bromley.t
t/cobrand/zurich.t
t/open311/populate-service-list.t

A number of Zurich changes in https://github.com/mysociety/FixMyStreet-Commercial/issues/672 build on this, so would be useful to review first.
See #1018

Roles::Extra to give an API to {extra} field #1018

---

perllib/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Smidsy.pm
templates/web/smidsy/faq/faq-en-gb.html
templates/web/smidsy/front/stats.html
web/cobrands/smidsy/base.scss
web/cobrands/smidsy/layout.scss

This is the design half of the ticket.
Before this can be merged, @osfameron will need to do the magic of actually piping the correct statistic through to the frontend, instead of it using the hard-coded "1234".

Show Stats19 on Collideoscope homepage

---

perllib/FixMyStreet/DB/Result/Problem.pm
templates/web/base/report/_council_sent_info.html
templates/web/base/report/_main.html
templates/web/oxfordshire/report/_council_sent_info.html
templates/web/oxfordshire/report/_main.html
web/cobrands/oxfordshire/base.scss
web/cobrands/oxfordshire/layout.scss
web/cobrands/sass/_base.scss

Mostly for Oxfordshire cobrand, but I've included a minor improvement for everyone else.
/cc @davea

Improve display of council-specific information on individual report page

---

bin/zurich/overdue-alert

Hopefully this is a very simple fix, just making a PR so that someone can
double-check I've not done anything silly.
Closes #1107

[Zurich] Fix path to setenv.pl in bin/zurich/overdue-alert

---

perllib/FixMyStreet/Cobrand/Smidsy.pm
t/cobrand/smidsy.t
templates/web/smidsy/report/new/fill_in_details_form.html
web/cobrands/smidsy/base.scss

This adds a required field asking the user whether the emergency services
attended the incident being reported.
See mysociety/FixMyStreet-Commercial#695

Add emergency services question to report form

---

perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t
templates/web/zurich/header.html

Admin CR4 https://github.com/mysociety/FixMyStreet-Commercial/issues/673
seems like admin_pages should be able to generate the menu, but
this change also needs template change.

[Zurich] all admin users can see stats (issues/commercial/673)

---

templates/web/zurich/report/new/fill_in_details_form.html

https://github.com/mysociety/FixMyStreet-Commercial/issues/666

[Zurich] text tweak (hint for "Photos" label) (issues/commercial/666)

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
templates/email/zurich/problem-confirm.txt

https://github.com/mysociety/FixMyStreet-Commercial/issues/669

Zurich: Issues/commercial/669 remove unnecessary confirmation email

---

perllib/FixMyStreet/Map/Zurich.pm
web/js/map-wmts-zurich.js

- Refactor map tile size into a constant
- Update map tiles to use new Zurich WMTS server
- Restore correct top-left corner values for Zurich map

[Zurich] use new larger tiles (issues/commercial/668)

---

templates/web/base/maps/openlayers.html
templates/web/zurich/admin/report_edit.html
templates/web/zurich/header.html
web/cobrands/sass/_base.scss
web/cobrands/zurich/base.scss
web/cobrands/zurich/layout.scss

- limit #site-logo changes to print media only
see #1036 for previous discussion (I couldn't see way of repointing the PR to zurich-2015-dev-candidate branch, so closed and opened this one)

[Zurich] improve report print styles (issues/commercial/677)

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/moderate.t
t/app/controller/photo.t
t/app/controller/report_import.t
t/app/model/photoset.t
t/cobrand/zurich.t
templates/web/base/report/photo.html
templates/web/zurich/admin/problem_row.html
templates/web/zurich/admin/report_edit.html
templates/web/zurich/report/new/fill_in_details_form.html

Work on https://github.com/mysociety/FixMyStreet-Commercial/issues/664 for multiple images.

Zurich: Issues/commercial/664 multiple photos

---

bin/update-schema
db/downgrade_0034---0033.sql
db/schema.sql
db/schema_0034-time-spent.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/AdminLog.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/questionnaire.t
t/cobrand/zurich.t
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html
web/cobrands/zurich/base.scss

[Zurich] (676) Time spent recording

---

templates/web/base/reports/body.html
templates/web/fixmystreet.com/reports/_body_gone.html

Factor out template to correct cobrand.

[fixmystreet.com] Add deleted NI councils.

---

web/cobrands/warwickshire/base.scss

Closes https://github.com/mysociety/FixMyStreet-Commercial/issues/597

[Warwickshire] Increase footer font size to 16px.

---

perllib/FixMyStreet/Cobrand/Bromley.pm

[Bromley] Add more disambiguation rules for geocoder

---

web/cobrands/barnet/_colours.scss
web/cobrands/barnet/base.scss
web/cobrands/bromley/_colours.scss
web/cobrands/bromley/base.scss
web/cobrands/fixamingata/_colours.scss
web/cobrands/fixamingata/base.scss
web/cobrands/harrogate/_colours.scss
web/cobrands/harrogate/base.scss
web/cobrands/sass/_base.scss
web/cobrands/trinidadtobago/_colours.scss
web/cobrands/trinidadtobago/base.scss

No need to override if it's set right from the start.

Use variable for menu image.

---

web/cobrands/eastsussex/base.scss
web/cobrands/eastsussex/layout.scss

Fixes https://github.com/mysociety/FixMyStreet-Commercial/issues/659 and a
related issue I noticed at the same time where the currently selected item in
the menu had different styling and so was smaller and out of line.

[East Sussex] Fix menu overlapping intro, and highlighted item looking rubbish

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/DB/ResultSet/AlertType.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/DB/ResultSet/Questionnaire.pm
perllib/FixMyStreet/Email.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/Utils/Email.pm

DMARC workaround

---

conf/general.yml-example
perllib/FixMyStreet/Geocode/Google.pm

Upgrade Google geocoder to version 3 of the API.

---

templates/web/base/admin/index.html
templates/web/base/admin/list_updates.html
templates/web/base/admin/problem_row.html
templates/web/base/admin/report_blocks.html
templates/web/base/admin/report_edit.html

Translate state column in admin index and lists.

---

t/MapIt.pm
t/app/controller/around.t
t/app/controller/report_import.t

SW1A 1AA has moved, who'd have thought.

Mock MapIt postcode call to fix broken tests.

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t
templates/web/zurich/admin/header.html
templates/web/zurich/admin/problem_row.html
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html
templates/web/zurich/admin/response_templates_select.html
templates/web/zurich/report/updates.html

Changes/improvements to admin workflow for problem closure after discussion with client.

[Zurich] Further improvements to admin workflow (672/690)

---

perllib/FixMyStreet.pm
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/Map.pm
perllib/FixMyStreet/Map/Zurich.pm
t/app/controller/report_display.t
t/app/controller/report_import.t
t/cobrand/zurich.t
templates/web/base/maps/noscript_map.html
templates/web/base/maps/openlayers.html
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html
templates/web/zurich/maps/noscript_map.html
web/cobrands/sass/_base.scss
web/cobrands/zurich/base.scss
web/cobrands/zurich/layout.scss

Work for mysociety/FixMyStreet-Commercial#677 that improves the print styles for admin report pages.

[Zurich] Admin report printing improvements

---

perllib/Catalyst/Plugin/Session/State/Cookie.pm

Unlikely to crop up, but this fixes #1077.

Prevent potential recursion in session cookie.

---

templates/web/fixmystreet-uk-councils/static/privacy.html
templates/web/fixmystreet.com/contact/address.html
templates/web/fixmystreet.com/static/privacy.html

Add physical address and more opt out instructions

---

web/down.default.html

Bring down page up to date, and work via proxy.

---

web/cobrands/fixmystreet.com/layout.scss

Add missing background-size to retina image.

---

locale/FixMyStreet.po
locale/de_CH.UTF-8/LC_MESSAGES/FixMyStreet.po
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
t/app/controller/report_display.t
t/cobrand/zurich.t
templates/web/base/auth/general.html
templates/web/base/report/new/category_extras.html
templates/web/fixmystreet/auth/general.html
templates/web/zurich/admin/list_updates.html
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html
templates/web/zurich/admin/response_templates_select.html
templates/web/zurich/admin/stats.html
templates/web/zurich/admin/template_edit.html
templates/web/zurich/auth/general.html
templates/web/zurich/footer.html
web/cobrands/zurich/base.scss
web/cobrands/zurich/layout.scss

This PR is a fairly random collection of little bug fixes and UI improvements made to the Zürich admin.
Each commit encapsulates a single fix or change.

[Zurich] Lots of little admin improvements

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t
templates/email/default/problem-confirm-not-sending.txt

Send altered confirmation email if not being sent.

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Status.pm
perllib/FixMyStreet/DB/ResultSet/Comment.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/DB/ResultSet/Questionnaire.pm
templates/web/base/admin/index.html
templates/web/base/status/index.html

Fixes #1251.
Would be good to do #1174 as part of this too, but no point in that holding up this which is fine alone.

JSON status page

---

CONTRIBUTING.md
README.md
bin/site-specific-install.sh

Include new contributing document.

Version 1.7.

---

cpanfile
cpanfile.snapshot
t/app/01app.t
templates/web/base/admin/index.html
templates/web/base/front/stats.html
templates/web/base/status/index.html
templates/web/base/status/stats.html
templates/web/emptyhomes/front/stats.html

And front page number localisation.

Prettify admin/status numbers

---

README.md
notes/cobranding.txt
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/SeeSomething.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/DB/ResultSet/Comment.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/admin.t
t/cobrand/bromley.t
t/cobrand/fixamingata.t
t/cobrand/fixmybarangay.t
t/cobrand/restriction.t
t/cobrand/two_tier.t

Fixes #1289, and makes it more consistent in general.

Allow more general filtering of Nearby

---

templates/web/base/report/update.html
web/cobrands/sass/_layout.scss

Pad internal update links so they are in view.

---

perllib/Open311/GetServiceRequestUpdates.pm
t/Mock/Facebook.pm
t/Mock/MapIt.pm
t/Mock/Nominatim.pm
t/Mock/Static.pm
t/app/controller/alert.t
t/app/controller/around.t
t/app/controller/auth_social.t
t/app/controller/report_import.t
t/cobrand/fixamingata.t
t/open311/getservicerequestupdates.t

Spot media_url in Open311 GetServiceRequestUpdate.

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_mobile.t

Thanks to @jonkri for spotting.

If app user logged in, perform alert signup.

---

perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/Open311/GetServiceRequestUpdates.pm

Only load images from disk when needed.

---

perllib/FixMyStreet/DB/Result/User.pm
t/app/model/user.t
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/report/new/form_user_loggedout_by_email.html
templates/web/base/report/update/form_name.html
templates/web/base/user/_anonymity.html
templates/web/eastsussex/report/new/after_name.html
templates/web/eastsussex/report/update-form.html

If a user is logged in, use their last report/update to set the default anonymity state.

Remember user's last anonymous state.

---

perllib/FixMyStreet/TestMech.pm
templates/web/base/report/_item.html
templates/web/fixmystreet-uk-councils/report/_item-with-pin.html
templates/web/greenwich/reports/_list-entry.html
templates/web/oxfordshire/reports/_list-entry.html
templates/web/zerotb/report/_item.html
templates/web/zurich/report/_item.html
web/cobrands/angus/layout.scss
web/cobrands/fixamingata/layout.scss
web/cobrands/fixmystreet.com/layout.scss
web/cobrands/sass/_base.scss
web/js/fixmystreet.js

This stops the front page header nesting skipping a level.
Needs checking if this affects any cobrands. Fixes #1348.

Switch list item heading from h4 to h3.

---

perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/EmptyHomes.pm
perllib/FixMyStreet/Cobrand/UK.pm
t/app/controller/reports.t
templates/web/base/admin/body.html

Cope with a '/' in body name in body slug.

---

perllib/Catalyst/Plugin/Session/State/Cookie.pm
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Open311.pm
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Controller/Rss.pm
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/Open311.pm
t/app/controller/auth_social.t
t/app/controller/photo.t
t/app/controller/report_new.t
t/app/model/photoset.t
t/open311.t
t/open311/getservicerequestupdates.t
templates/web/base/around/_error_multiple.html
templates/web/base/questionnaire/index.html
templates/web/base/report/new/form_report.html
templates/web/base/report/update/form_update.html
templates/web/bromley/report/display.html
templates/web/bromley/report/new/fill_in_details_form.html
templates/web/eastsussex/report/update-form.html
templates/web/emptyhomes/report/new/fill_in_details_form.html
templates/web/seesomething/report/new/fill_in_details_form.html
templates/web/zurich/report/new/fill_in_details_form.html
web/cobrands/fixmystreet/fixmystreet.js

Allow PNGs to be uploaded.

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

Even when we ask for a specific range of dates, we sometimes get given
more in the response.

Skip fetched updates if they're out of date range.

---

perllib/FixMyStreet/App/Controller/Admin.pm

Allow change of email in admin to existing entry.

---

customising/integration.md
glossary.md
running/bodies_and_contacts.md

I didn't understand what this meant the first time, so now the
terminology is documented.

add glossary entry for "devolved"

---

conf/general.yml-example
perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/App/Controller/Rss.pm
perllib/FixMyStreet/Gaze.pm
perllib/FixMyStreet/Map.pm
perllib/FixMyStreet/Map/Google.pm
perllib/FixMyStreet/Map/OSM.pm
perllib/FixMyStreet/Script/Alerts.pm
t/app/load_general_config.t
t/fixmystreet.t

Fallback if request to Gaze fails.

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Status.pm
templates/web/base/admin/index.html
templates/web/base/admin/stats.html
templates/web/base/admin/stats_by_state.html
templates/web/base/admin/stats_fix_rate.html
templates/web/base/status/stats.html

Move most index page statistics to their own pages.

Add search boxes to admin index page, move stats.

---

templates/web/fixmystreet.com/about/faq-en-gb.html

Update wording about changing email/password

---

templates/web/smidsy/footer_extra.html

Part of https://github.com/mysociety/standard-footer/issues/9

UTM params for mysociety.org links in Collideoscope footer

---

templates/web/fixmystreet.com/footer_extra.html

Tweak the recently added UTM tag in the footer, to match our new standard: https://wiki.mysociety.org/wiki/Google_Analytics#Custom_Campaigns

Standardise footer UTM tracking with other sites

---

_includes/footer.html

Part of https://github.com/mysociety/standard-footer/issues/9

UTM params for mysociety.org links in fixmystreet.org footer

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Council.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/admin.t
templates/web/base/admin/report_edit.html

Allow editing of category on admin report edit

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Map.pm
t/map/tilma/original.t

Sorry for not doing this sooner (though would have missed /my then anyway!).

Refactor map pin/feature functions.

---

conf/general.yml-example
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/Geocode.pm
perllib/FixMyStreet/Geocode/Zurich.pm

If they are absolute already, do nothing.
Switch a couple of uses to Path::Tiny as well.

Make UPLOAD_DIR/GEO_CACHE relative to project root

---

README.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/View/Web.pm
templates/web/base/my/my.html
templates/web/base/questionnaire/index.html
templates/web/base/report/_main.html
templates/web/base/report/update.html
templates/web/zurich/report/_main.html
templates/web/zurich/report/updates.html

Convert single newlines, use double quotes, use add_links as a filter.

Some improvements to text display

---

web/cobrands/fixmystreet/fixmystreet.js

Couple of small things spotted during use; fixing the back link, stopping possible infinite loop and making the try again button a bit better.

JS History tweaks

---

bin/update-schema
db/downgrade_0042---0041.sql
db/downgrade_0043---0042.sql
db/schema.sql
db/schema_0042-planned_reports.sql
db/schema_0043-add-user-area-field.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/DB/Result/AdminLog.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/DB/Result/UserPlannedReport.pm
perllib/FixMyStreet/TestMech.pm
t/Mock/MapIt.pm
t/app/controller/admin.t
t/app/controller/admin_permissions.t
t/app/controller/my.t
t/app/controller/my_planned.t
t/app/model/user_planned_report.t
templates/web/base/admin/user-form.html
templates/web/base/around/lookup_by_ref.html
templates/web/base/my/planned.html
templates/web/base/report/_main.html
templates/web/oxfordshire/header.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/fixmystreet-admin.js

See mysociety/fixmystreetforcouncils#37.

Allow user to have an area assigned in admin

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/Roles/Extra.pm
t/app/model/extra.t
templates/web/base/admin/category_edit.html

Allow get_extra_metadata to return all the data with no argument.

Improve display of category extra data in admin.

---

perllib/FixMyStreet/App/Controller/Admin.pm

Fixes (the first part of) #1138.

Don't reject email when editing Open311 contacts

---

templates/web/base/report/new/after_photo.html

As discussed in https://github.com/mysociety/fixmystreetforcouncils/issues/6#issuecomment-246621617 – this wording might be marginally clearer.

Clearer wording for photo advice

---

bin/zurich/overdue-alert
templates/web/zurich/admin/report_edit.html
web/cobrands/zurich/js.js

A couple of little bugs Zurich emailed about.

[Zurich] Fixes to image zooming and overdue alert emails

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Reports.pm
templates/web/base/my/my.html
templates/web/base/my/planned.html
templates/web/base/pagination.html
templates/web/base/reports/body.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/map-OpenLayers.js

Fixed:
Todo:
~~Add a "clear" to the categories filter when something is selected, to clear the filter~~ Will leave for later.

/reports and /my page fixes

---

perllib/FixMyStreet/DB/Result/Problem.pm
web/cobrands/fixmystreet/fixmystreet.js

And fix an issue where removed shortlisted users were shown on report page.

Make sure inspect form shown if report pulled in.

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Map.pm
templates/web/base/reports/_list-filters.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/cobrands/sass/_multiselect.scss
web/cobrands/sass/_report_list.scss
web/js/map-OpenLayers.js

Needs a bit of design to fit in with the multiple ones, I think, but is up and running okay.

Add sort order option to list pages.

---

perllib/FixMyStreet/Map/Bing.pm
perllib/FixMyStreet/Map/Bristol.pm
perllib/FixMyStreet/Map/Bromley.pm
perllib/FixMyStreet/Map/GoogleOL.pm
perllib/FixMyStreet/Map/OSM.pm
perllib/FixMyStreet/Map/OSM/CycleMap.pm
perllib/FixMyStreet/Map/OSM/MapQuest.pm
perllib/FixMyStreet/Map/OSM/StreetView.pm
perllib/FixMyStreet/Map/WMTSBase.pm
perllib/FixMyStreet/Map/Zurich.pm
templates/web/base/maps/openlayers.html
templates/web/bromley/maps/bromley.html
web/cobrands/bromley/map.js
web/js/map-fms.js

The change to remove inline JavaScript stopped the Bromley-specific
tiles from working. Put them back with an extra JavaScript file.

[Bromley] Fix map tiles.

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/fixmystreet.js

Should fix the bootstrapping issue, mysociety/fixmystreetforcouncils#120, the navigation in new tab for non-Android, mysociety/fixmystreetforcouncils#121, and scrolling to inspect form mysociety/fixmystreetforcouncils#122

Few small fixes

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm

Should fix #1584, a comment in #1574, and a warning I noticed in testing.

Some tiny fixes

---

web/cobrands/fixmystreet/fixmystreet.js

For mysociety/fixmystreetforcouncils#140

Hide 'Show my name publicly' when reporting on behalf of another user

---

templates/web/fixmystreet-uk-councils/report/new/after_photo.html

For mysociety/fixmystreetforcouncils#141

Reword photo advice

---

web/cobrands/fixmystreet/offline.js

Offline tweaks

---

perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/admin.t
t/app/controller/report_as_other.t
t/app/controller/report_display.t

For mysociety/fixmystreetforcouncils#136

Show user details for council report

---

perllib/FixMyStreet/App/Controller/Report.pm

Assume that if they inspect and save a report, they want
to go back to their shortlist.

Redirect to shortlist if user has shortlist perms.

---

perllib/FixMyStreet/App/Controller/My.pm
t/app/controller/my_planned.t
templates/web/base/my/planned.html

For mysociety/fixmystreetforcouncils#146
This adds the JSON response to the controller action, and wraps the problem list in a `js-reports-list` container, so the list can be updated.

Fix Shortlist filtering

---

perllib/FixMyStreet/Cobrand/Default.pm

Call base_url_with_lang in base_url_for_report

---

perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/SendReport/Open311.pm

This joins easting, northing and an external ID field.

Add a 'closest_address' hidden Open311 attribute.

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/ExorDefects.pm
perllib/FixMyStreet/Script/Reports.pm

It's a relatively minor change that I don't **think** has any knock-on effects, but figured I'd PR it for a second opinion just to be safe 😃 
For mysociety/fixmystreetforcouncils#168

Send open reports regardless of current state

---

bin/generate_cobrand_po
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/model/problem.t
templates/web/base/report/banner.html
templates/web/fixmystreet.com/report/banner.html

There is no link between these three commits.
Fixes #1616. Fixes #1640.

Fix a script, and inspecting superuser, add a helper

---

perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/moderate.t
templates/web/base/report/_main.html
templates/web/base/report/update.html

Use name at time of moderation, including superusers.

---

perllib/FixMyStreet/Email.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/Utils/Email.pm
t/app/model/problem.t
t/cobrand/zurich.t
t/cobrand/zurich_attachments.txt
t/utils/email.t

Change the from line in email if its domain matches the to

---

perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/TestMech.pm
t/Mock/MapIt.pm
t/app/controller/admin.t
t/app/controller/admin_permissions.t
t/app/controller/alert.t
t/app/controller/alert_new.t
t/app/controller/around.t
t/app/controller/auth.t
t/app/controller/auth_social.t
t/app/controller/dashboard.t
t/app/controller/index.t
t/app/controller/photo.t
t/app/controller/report_as_other.t
t/app/controller/report_import.t
t/app/controller/report_inspect.t
t/app/controller/report_new.t
t/app/controller/report_new_mobile.t
t/app/controller/report_new_open311.t
t/app/controller/reports.t
t/app/controller/rss.t
t/app/model/alert_type.t
t/app/model/user.t
t/cobrand/fixamingata.t
t/cobrand/form_extras.t

This lets all tests run offline, plus a few other minor fixes.

Offline tests

---

templates/web/fixmystreet.com/about/faq-en-gb.html
templates/web/fixmystreet.com/contact/who.html
templates/web/fixmystreet.com/questionnaire/completed-open.html
templates/web/fixmystreet.com/static/unresponsive.html

Specifies Google Analytics tracking parameters for links to WTT.

[fixmystreet.com] Add URL parameters to links to WriteToThem

---

perllib/FixMyStreet/Cobrand/Bristol.pm

Fixes https://github.com/mysociety/FixMyStreet-Commercial/issues/828

Use OSM geocoder for Bristol

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/report_inspect.t
t/app/model/user.t

Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/130

Subscribe inspectors to alerts after updating an issue

---

.travis.yml
t/app/controller/report_new.t
t/app/controller/reports.t
t/app/model/problem.t
t/cobrand/get_body_sender.t
t/cobrand/oxfordshire.t
t/open311/getupdates.t

This should fix @zarino's issues running the tests somewhere where Swedish wasn't installed and when there was no internet.

Testing times

---

perllib/FixMyStreet/App/Controller/Report/Update.pm
t/app/controller/report_inspect.t
t/app/controller/report_updates.t
templates/web/base/report/_state_select_field.html
templates/web/base/report/update/form_update.html
templates/web/oxfordshire/report/inspect/state_groups_select.html

Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/191

Tidy up state dropdowns, and use instruct permission in Oxfordshire

---

templates/web/angus/footer.html
templates/web/angus/post_header_extra.html
templates/web/base/main_nav.html
templates/web/bristol/footer.html
templates/web/bromley/footer.html
templates/web/eastherts/footer.html
templates/web/greenwich/footer.html
templates/web/greenwich/header_logo.html
templates/web/hart/footer.html
templates/web/oxfordshire/footer.html
templates/web/oxfordshire/header.html
templates/web/stevenage/footer.html
templates/web/warwickshire/header.html
web/cobrands/angus/base.scss
web/cobrands/fiksgatami/base.scss
web/cobrands/fiksgatami/layout.scss
web/cobrands/fixamingata/layout.scss
web/cobrands/fixmystreet.com/layout.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

This is part 1 of #1718, split off to get merged first.

Simplify header/nav markup and CSS (part 1)

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/ResultSet/DefectType.pm
perllib/FixMyStreet/DB/ResultSet/ResponsePriority.pm
perllib/FixMyStreet/Roles/ContactExtra.pm
t/app/model/defecttype.t
t/app/model/responsepriority.t
templates/web/base/report/_inspect.html
templates/web/oxfordshire/footer_extra_js.html
web/cobrands/fixmystreet/staff.js
web/cobrands/oxfordshire/js.js

Fixes mysociety/fixmystreetforcouncils#185

Change defect type when category is changed

---

perllib/FixMyStreet/Cobrand/UKCouncils.pm

Fixes mysociety/fixmystreet-commercial#859

[UK Councils] Show all pins only on two-tiers

---

bin/fixmystreet.com/fixture
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Factories.pm
perllib/FixMyStreet/DB/ResultSet/ResponseTemplate.pm
perllib/FixMyStreet/Roles/ContactExtra.pm
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/staff.js

This should fix mysociety/fixmystreetforcouncils#193

Update template list when category or state are changed

---

bin/update-all-reports
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/Script/UpdateAllReports.pm

This is in support of mysociety/fixmystreet-international#50.
This was the simplest way I could see to add this feature, and given the incoming new dashboards I didn't want to go too deep into the problem as it'll likely be redundant soon.

Generate stats for body areas in all-reports.json

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/Email/Sender.pm
t/email/sender.t

And email sending failure in contact form.
Fixes #1758

Spot bad SMTP_TYPE config

---

customising/boundaries.md
customising/config.md
glossary.md
updating/ami.md
updating/index.md

* Switch all mentions of UK MapIt to https.
* Fix -/_ typo in AMI upgrade instructions.
* Document new script/update script.

Fix small doc errors and update upgrade instructions

---

perllib/FixMyStreet/Integrations/ExorRDI.pm
t/cobrand/oxfordshire.t

The "M" line needs an "I" after the activity code if the activity code
is only one character.
Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/213

[Oxfordshire] Put I when single char activity code

---

perllib/FixMyStreet/App/Controller/About.pm

Cache template paths in About.pm with lang_code

---

templates/web/base/js/translation_strings.html
web/js/map-OpenLayers.js
web/js/map-google.js

Use standard JS translation for show/hide pins.

---

bin/install-as-user
bin/update-schema

Allow update-schema to run on empty database.

---

CHANGELOG.md
templates/web/base/report/_item.html

Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/208

Output current shortlist holder in list tooltips.

---

perllib/FixMyStreet/App/Controller/Auth.pm
templates/web/base/auth/general.html
templates/web/borsetshire/around/postcode_form.html
templates/web/borsetshire/auth/_general_top.html
templates/web/borsetshire/footer_extra_js.html
web/cobrands/borsetshire/js.js

@zarino wondered why his dev site didn't match live. Turned out live's master had two commits not in our master?!
Also add a fix so if you submit `/auth` when logged in, it will switch account as you'd expect.

[Borsetshire] Live things on demo site

---

locale/sv_SE.UTF-8/LC_MESSAGES/FixMyStreet.po

This pull request adds the lastest (2.1) translation, as "downloaded for use" from Transifex.
Thank you.

[FixaMinGata] Add updated translation

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Reports.pm
t/app/controller/reports.t
templates/web/base/reports/_list-filters.html

Not just New/Fixed/Closed but the Investigating etc
Fixes mysociety/fixmystreetforcouncils#187
Fixes #1790

allow body users to filter on all problem categories

---

t/app/controller/admin_defecttypes.t

tests for the defect types admin interface

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report.pm
templates/web/base/around/tabbed_lists.html
templates/web/base/front/recent.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js
web/js/map-OpenLayers.js
web/js/map-google.js

The page currently fetches the pins again client-side (as we don't know the extent of the map at the server point). I realise this isn't ideal, but should speed up the normal case quite a bit.
Also fixes #1808.

Don't fetch pins serverside with JS on

---

perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/App/Model/DB.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Schema.pm
templates/web/base/report/_item.html

Another couple of /reports speedups

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html

Fixes mysociety/fixmystreetforcouncils#204

Redirect to original URL after inspecting

---

CHANGELOG.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/App/View/Web.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Test.pm
perllib/Open311/GetServiceRequestUpdates.pm
t/Mock/MapItZurich.pm
t/app/controller/admin_reportextrafields.t
t/app/model/alert_type.t
t/app/model/problem.t
t/app/script/archive_old_enquiries.t
t/app/sendreport/email.t
t/app/sendreport/inspection_required.t
t/cobrand/closest.t
t/cobrand/get_body_sender.t
t/map/tilma/original.t
templates/web/base/admin/_translations.html
templates/web/base/admin/problem_row.html
templates/web/base/admin/state_groups_select.html
templates/web/base/report/_item.html
templates/web/base/report/_state_select_field.html
templates/web/base/report/inspect/state_groups_select.html
templates/web/oxfordshire/report/inspect/state_groups_select.html

Some preparatory things that have fallen out of the report state move, rebased to all come first.
Fixes #1824.

Move report states to database part 1

---

.gitignore
CHANGELOG.md
conf/general.yml-example
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Root.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Roles/Extra.pm
t/app/controller/auth.t
t/app/controller/root.t
t/app/model/extra.t
templates/web/base/auth/token.html
templates/web/base/maps/openlayers.html

This PR is a collection of small improvements to FMS that came about as part of the Ground Control site.

[Ground Control] Platform improvements

---

app.psgi
cpanfile
cpanfile.snapshot
perllib/Plack/Middleware/Debug/FixMyStreet/Template.pm

Use a small subclass of https://github.com/mysociety/Plack-Middleware-Debug-Template to have better display of our template path names. [skip changelog]

Add template debug panel.

---

CHANGELOG.md
db/downgrade_0055---0054.sql
db/schema.sql
db/schema_0055-add-default-to-reponsepriority.sql
perllib/FixMyStreet/App/Controller/Admin/ResponsePriorities.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/ResponsePriority.pm
t/app/controller/admin.t
t/app/controller/report_inspect.t
templates/web/base/admin/responsepriorities/edit.html
templates/web/base/admin/responsepriorities/list.html
templates/web/base/report/_inspect.html

Add and use default response priorities.
Fixes mysociety/fixmystreetforcouncils#224

default response priorities

---

perllib/FixMyStreet/Integrations/ExorRDI.pm
t/cobrand/oxfordshire.t

[Oxfordshire] Use local time for rdi_processed, not UTC

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Phone.pm
perllib/FixMyStreet/App/Controller/Auth/Profile.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/SMS.pm
t/app/controller/auth_phone.t

We have no way of knowing whether a +1 geographic number is fixed
line or mobile, so accept them all as potentially mobile.

Accept +1 geographic numbers as possibly mobile.

---

perllib/FixMyStreet/Script/Alerts.pm
t/app/controller/alert_new.t

If there was a normal email alert, and then an alert for an update with
no text (so no email should be sent), it would still try to send the
blank email, and then die because no e.g. $data{cobrand} set.
This moves the skip-blank-update check higher up, above any email
sending code. [skip changelog]

Fix issue sending alerts around no-text update.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/app/controller/admin.t
t/app/controller/moderate.t
t/app/controller/report_updates.t
templates/web/base/report/update.html
templates/web/base/report/updates.html

Create a comment with blank text when the report state is updated in admin

---

conf/general.yml-example
perllib/FixMyStreet/App/Controller/Auth/Phone.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/SMS.pm
t/Mock/Twilio.pm
t/app/controller/auth_phone.t
templates/web/base/auth/_username_error.html
templates/web/base/auth/change_phone.html
templates/web/base/auth/general.html

Spot any sync errors when sending the text and inform the user, and add the option of using a Twilio Messaging Service. [skip changelog]

Some text messaging tweaks

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin.t
templates/web/base/admin/report_blocks.html
templates/web/base/admin/user-form.html
templates/web/base/admin/users.html

Add an unban button to the user edit page when a user is in the abuse
table.
Fixes #1881

allow admin to unban a user

---

bin/oxfordshire/send-rdi-emails
templates/email/oxfordshire/rdi.txt

Fixes mysociety/fixmystreetforcouncils#251

[Oxfordshire] Clearly mark RDI emails if sent from staging

---

templates/web/borsetshire/around/postcode_form.html
web/cobrands/borsetshire/base.scss
web/cobrands/borsetshire/layout.scss

Fixes mysociety/fixmystreet-commercial#927. [skip changelog]

[Borsetshire] Homepage login hint banner

---

templates/email/fixmystreet.com/_submit_footer.html
templates/email/fixmystreet.com/submit.html
templates/email/fixmystreet.com/submit.txt

Fixes mysociety/fixmystreet-commercial#925.

[fixmystreet.com] Prominent FMS Pro promo in email to council

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/DB/Result/Problem.pm

Use proper dates in CSV export, not nice human strings. Should fix https://github.com/mysociety/fixmystreetforcouncils/issues/264 . Also fixes a couple of other small issues along the way.

CSV export issues

---

bin/fixmystreet.com/fixture
perllib/FixMyStreet/DB/Factories.pm
templates/web/base/auth/general.html
templates/web/borsetshire/auth/_general_top.html
templates/web/borsetshire/front/footer-marketing.html
web/cobrands/borsetshire/base.scss
web/cobrands/borsetshire/js.js
web/cobrands/borsetshire/layout.scss

Barring design work needed (and it is needed, not least an `!important`?!), this
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/946
and fixes https://github.com/mysociety/fixmystreet-commercial/issues/944

Small demo changes

---

.gitignore
CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/around.t
t/app/controller/report_new.t
templates/web/base/around/_error_multiple.html
templates/web/base/header.html

WIP: Changes in core to support Yo Denuncio

---

CHANGELOG.md
bin/update-all-reports
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Angus.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/ResultSet/Body.pm
templates/web/base/dashboard/index.html

Create some new helper methods, make sure they're used everywhere, and prefetch translations/ignore bodies that won't work on the dashboard.

Fix some small body list issues

---

CHANGELOG.md
web/js/map-OpenLayers.js

My strategy cannot calculate bounds

---

CHANGELOG.md
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/model/problem.t
t/app/sendreport/inspection_required.t
t/cobrand/bromley.t
t/cobrand/fixamingata.t
t/cobrand/zurich.t
t/sendreport/open311.t

Fix error sending `requires_inspection` reports.

---

templates/web/base/open311/index.html
templates/web/borsetshire/front/footer-marketing.html
templates/web/borsetshire/header_site.html
templates/web/bromley/front/footer-marketing.html
templates/web/eastherts/footer.html
templates/web/fixmystreet.com/about/council-dashboard.html
templates/web/fixmystreet.com/about/faq-en-gb.html
templates/web/fixmystreet.com/contact/blurb.html
templates/web/fixmystreet.com/footer_extra.html
templates/web/fixmystreet.com/front/footer-marketing.html
templates/web/fixmystreet.com/report/_report_meta_info.html
templates/web/greenwich/front/footer-marketing.html
templates/web/hart/footer.html
templates/web/oxfordshire/footer.html
templates/web/stevenage/footer.html
web/cobrands/borsetshire/_council-header.scss
web/cobrands/borsetshire/_mysoc-header.scss
web/cobrands/borsetshire/base.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/944

Borsetshire Pro changes

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Profile.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/Test.pm
t/app/controller/auth_profile.t
templates/web/base/auth/change_password.html

Ask for current password on change.

---

CHANGELOG.md
cpanfile
cpanfile.snapshot
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Phone.pm
perllib/FixMyStreet/App/Controller/Auth/Profile.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/Borsetshire.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/auth.t
t/app/controller/auth_profile.t
templates/web/base/auth/change_password.html
templates/web/base/auth/general.html
templates/web/base/js/translation_strings.html
templates/web/base/report/new/form_user_loggedout_by_email.html
templates/web/base/report/update/form_user_loggedout_by_email.html
templates/web/bromley/report/new/form_user.html
templates/web/bromley/report/update-form.html
templates/web/fixamingata/report/new/form_user_loggedout.html
templates/web/zurich/auth/general.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/validation_rules.js

Minimal length and comparison against common password list.

Add password checking on setting.

---

CHANGELOG.md
perllib/Catalyst/Plugin/FixMyStreet/Session/StoreSessions.pm
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin/users.t
t/app/controller/report_new.t
templates/web/base/admin/user-form.html

Admin ability to remove user account details.

---

.travis.yml
CHANGELOG.md
cpanfile
cpanfile.snapshot
perllib/Catalyst/Authentication/Credential/2FA.pm
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Profile.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/auth.t
t/app/controller/auth_profile.t
t/app/controller/report_new.t
templates/web/base/auth/2faform.html
templates/web/base/auth/generate_token.html
templates/web/base/my/my.html

Add two-factor authentication for superusers.

---

CHANGELOG.md
web/cobrands/fixmystreet/assets.js
web/js/map-OpenLayers.js

- Displays the loading spinner whilst asset layers are being loaded
- Slight refactor of spinner code to keep track of multiple things loading simultaneously

Display map loading spinner for asset layers

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Geocode/Google.pm
perllib/FixMyStreet/Script/Reports.pm
t/Mock/GoogleGeocoder.pm
t/geocode/google.t
templates/web/base/report/_inspect.html
templates/web/base/report/new/category_extras_fields.html

A few smaller things that have shaken out of the BANES work and that didn't seem to fit elsewhere.

Some small fixes/tweaks

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/report_inspect.t
t/app/controller/report_new.t
templates/web/base/report/_inspect.html
templates/web/base/report/new/form_user_loggedin.html

Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/276

Allow inspectors to change non_public status

---

CHANGELOG.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Develop.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/controller/develop.t
templates/email/default/alert-update.html
templates/email/default/alert-update.txt
templates/email/default/submit.html
templates/email/default/submit.txt
templates/email/fiksgatami/nn/submit.txt
templates/email/fiksgatami/submit.txt
templates/email/fixamingata/submit.html
templates/email/fixamingata/submit.txt
templates/email/fixmystreet.com/submit.html
templates/email/fixmystreet.com/submit.txt
templates/email/zurich/submit-external-personal.txt
templates/email/zurich/submit-external-wish.txt
templates/email/zurich/submit-external.txt
templates/email/zurich/submit-feedback-pending.txt
templates/email/zurich/submit-in-progress.txt
templates/email/zurich/submit.txt
templates/web/base/develop/email_list.html

This adds `/_dev/email` when run in development, that lets you easily preview any HTML email as it would look, including inline images.
TODO: note in docs

Development email previewer

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/admin/report_edit.t
t/cobrand/zurich.t
web/cobrands/zurich/base.scss
web/cobrands/zurich/layout.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1007
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/975
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/976
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/981

[Zurich] Fix couple of bugs + general admin edit bug

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Dashboard.pm

This makes it clearer what is being shown.

Show default start date on dashboard.

---

bin/oxfordshire/archive-old-enquiries
perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm
t/app/script/archive_old_enquiries.t
templates/email/warwickshire/archive.txt

Add an update with each report closure.

[Warwickshire] Add archive script data.

---

web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js
web/js/map-OpenLayers.js

JS event handling

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/report_new_open311.t
templates/web/base/admin/list_updates.html
templates/web/base/admin/problem_row.html
templates/web/base/report/new/category_extras_fields.html
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss

A few more improvements that have shaken out of the BANES work.

Little report extra & permissions improvements

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Open311.pm
t/app/controller/open311.t

This fixes #2023 by removing the comma, though I would like to replicate this.

Truncate dates in Open311 output to the second.

---

templates/web/base/around/display_location.html
templates/web/fixmystreet.com/around/_report_banner.html
templates/web/fixmystreet.com/header_extra.html
web/cobrands/fixmystreet.com/base.scss

Part of #2016. [skip changelog]

[UK] A/B test "big green banner" position

---

perllib/FixMyStreet/App/Controller/Admin/Stats.pm
t/app/controller/admin/stats.t
templates/web/base/admin/stats/index.html
templates/web/fixmystreet.com/admin/stats/refused.html

[fixmystreet.com] Add admin page to list refused.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Open311.pm

Add CORS header to Open311 output.

---

CHANGELOG.md
cpanfile
cpanfile.snapshot
perllib/FixMyStreet/TestAppProve.pm

Upgrade Test::PostgreSQL, which fixes a bug delaying the end
of test running, and introduces a nicer setup mechanism.

Fix issue with test database removal.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Council.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_new_open311.t
templates/web/base/admin/category-checkboxes.html
templates/web/base/report/_item.html
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/report/new/form_user_loggedout_by_email.html
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/staff.js

A collection of little improvements that have shaken out of the Buckinghamshire cobrand.

Small improvements from Buckinghamshire work

---

web/cobrands/bathnes/staff.js

Fixes mysociety/fixmystreetforcouncils#305

[BANES] remove fill from LLPG layer labels

---

CHANGELOG.md
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/Memcached.pm

Also stop caching lat/lon specific alert photo lists, and improve
Memcached code.

Check recent reports for any hidden since cached.

---

perllib/FixMyStreet/App/Controller/FakeMapit.pm
t/app/controller/fakemapit.t

Provide API key to MapIt proxy if present.

---

CHANGELOG.md
perllib/Open311.pm

[Open311] Pretty print all request parameters.

---

setenv.pl

Abort if a script is run in an old deploy.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Reports.pm
templates/web/base/reports/_ward-list.html
templates/web/fixmystreet.com/reports/cobrand_stats.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss

Fixes mysociety/fixmystreetforcouncils#231

Add UI for selecting multiple wards from /reports/ body page

---

templates/web/fixmystreet.com/about/privacy.html

A couple of tweaks to the privacy policy. [skip changelog]

Privacy fixes

---

CHANGELOG.md
web/cobrands/sass/_admin.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_dashboard.scss
web/cobrands/sass/_dropzone.scss
web/cobrands/sass/_layout.scss
web/cobrands/sass/_multiselect.scss
web/cobrands/sass/_report_list.scss

Main issues fixed are overlapping text on contact form/dashboard graph/multiselect tickboxes, the new hide pin button/geolocation spinner being wrong side, loading indicator not working, and broken 'segmented-control' (borders wrong side of end ones).

Fix issues with RTL display/hardcoded directions.

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
templates/email/bathnes/other-updated.txt
templates/email/bromley/_problem-confirm_extra.html
templates/email/bromley/_problem-confirm_extra.txt
templates/email/buckinghamshire/other-reported.txt
templates/email/default/alert-confirm.txt
templates/email/default/change_email.txt
templates/email/default/login.txt
templates/email/default/other-reported.txt
templates/email/default/other-updated.txt
templates/email/default/partial.txt
templates/email/default/problem-confirm-not-sending.txt
templates/email/default/problem-confirm.txt
templates/email/default/problem-moderated.txt
templates/email/default/update-confirm.txt
templates/email/fixamingata/alert-confirm.txt
templates/email/fixamingata/change_email.txt
templates/email/fixamingata/login.txt
templates/email/fixamingata/other-reported.txt
templates/email/fixamingata/other-updated.txt
templates/email/fixamingata/partial.txt
templates/email/fixamingata/problem-confirm-not-sending.txt
templates/email/fixamingata/problem-confirm.txt
templates/email/fixamingata/problem-moderated.txt
templates/email/fixamingata/update-confirm.txt
templates/email/fixmystreet.com/other-reported.txt

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1037

[Bromley] Email text and default to unticking show name box

---

CHANGELOG.md
perllib/Open311/PopulateServiceList.pm
web/cobrands/fixmystreet/assets.js

The non-Bromley parts of #2044 pulled out for inclusion.

Some asset improvements, from Bromley work

---

templates/web/bathnes/report/new/councils_text_private.html
templates/web/fixmystreet-uk-councils/about/privacy.html

Some wording from BANES.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1057

[UK] Tweaks to council privacy policy.

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Geocode.pm
perllib/FixMyStreet/Geocode/OSM.pm
t/Mock/Nominatim.pm
t/app/controller/alert.t
t/cobrand/bromley.t
t/cobrand/fixamingata.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1064

[Bromley] Improve geocoding

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/SendReport/Email.pm
t/cobrand/bucks.t
templates/web/base/admin/contact-form.html
templates/web/fixmystreet.com/reports/summary.html
web/cobrands/fixmystreet/admin.js

And a few related odds and sods. I think using body handler hook in SendReport makes sense, but that always confuses me.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1060

[Bucks] Support extra recipient for road flytipping

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
web/cobrands/fixmystreet/staff.js

Fixes #2171. Fixes #2172. Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1082

Fix some inspection issues

---

templates/web/buckinghamshire/report/new/inline-tips.html

For mysociety/fixmystreet-commercial#1065

[Bucks] add one issue per report text to tips

---

CHANGELOG.md
t/app/controller/around.t
templates/web/base/reports/_list-filters.html

Show all fixed issues when staff uses map filter.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1085

Allow any user who sees private checkbox to use it

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm

For mysociety/keepitinthecommunity#47

Add cobrand hook for custom searching on disambiguation page

---

locale/de_CH.UTF-8/LC_MESSAGES/FixMyStreet.po

Hi
I've amended the translation for the e-mail confirmation.
Best,
Tobias

Amended Translation

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Contact.pm
t/app/controller/contact.t
templates/email/default/contact.html
templates/email/default/contact.txt

Include user agent in contact form emails.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/moderate.t
templates/web/base/report/_inspect.html
templates/web/base/report/_main.html
templates/web/base/report/display.html
templates/web/base/report/update.html

This does some tidying of the moderation code, and adds a hook so that a cobrand can e.g. let users edit their own reports on the site.

 Allow cobrand to add extra ability to moderate

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/Update.pm
t/app/controller/report_updates.t
templates/web/base/report/display.html
templates/web/base/report/update-form.html

For mysociety/collideoscope#20.

Add cobrand hook for disallowing updates on problems

---

bin/fixmystreet.com/defra_stats

[UK] utility script to generate stats for Defra

---

CHANGELOG.md
templates/web/base/my/my.html

Say “Set password”, not Change, if none set.

---

templates/email/lincolnshire/contact.html
templates/email/lincolnshire/contact.txt

For mysociety/fixmystreet-freshdesk#16.

[Lincolnshire] Remove UA string from contact emails

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/pull_request_template.md

Add issue/PR templates

---

CHANGELOG.md
bin/fixmystreet.com/fixture
conf/general.yml-example
cpanfile
cpanfile.snapshot
docs/customising/config.md
docs/install/manual-install.md
perllib/FixMyStreet.pm
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/PhotoStorage.pm
perllib/FixMyStreet/PhotoStorage/FileSystem.pm
perllib/FixMyStreet/PhotoStorage/S3.pm
t/app/controller/photo.t
t/app/model/photoset.t
t/cobrand/zurich.t
t/open311.t
t/photostorage/s3.t
t/sendreport/open311.t

- Refactors on-disk photo storage code into `FixMyStreet::PhotoStorage::FileSystem` module
- Adds new `FixMyStreet::PhotoStorage::S3` module that stores report/update photos in an S3 bucket
Fixes mysociety/fixmystreet-commercial#1182.

S3 photo storage support

---

conf/general.yml-docker

Hopefully this is pretty straightforward! I'll test on a new build, but thought I'd just raise a PR to check it looks right.

[Docker] Update example config to support S3 file storage

---

.cypress/cypress/integration/responsive.js

checks what is shown/hidden at various screen sizes [skip changelog]
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1190

basic front end tests for responsive design

---

templates/web/base/report/new/form_report.html
templates/web/base/report/new/form_user.html
templates/web/fixmystreet.com/footer_extra_js.html
templates/web/oxfordshire/footer_extra_js.html
web/cobrands/oxfordshire/assets.js
web/cobrands/oxfordshire/base.scss

Adds some div wrappers round the non category bit of the form so we can
then hide easily.

[Oxfordshire] display message if user selects PROW category

---

.cypress/cypress.json
.cypress/cypress/integration/bathnes.js
.cypress/cypress/integration/regressions.js
.cypress/cypress/integration/responsive.js
.cypress/cypress/integration/simple_spec.js
bin/browser-tests

WIP options for cobrand front end testing

---

docs/install/ami.md
docs/install/database.md
docs/install/troubleshooting.md
docs/updating/ami.md
docs/updating/index.md

Updates relating to the new AMI build process, hopefully the balance is right between what we discuss in the FMS docs and what we discuss in the Public Builds repo - see that repo's [docs branch](https://github.com/mysociety/public-builds/tree/docs) for corresponding additions there.

[Docs] Updated docs with more detail on AMI builds

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/app/controller/dashboard.t
t/cobrand/bathnes.t
templates/web/base/dashboard/index.html
web/cobrands/sass/_dashboard.scss

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/12

Add update export to dashboard

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/Cobrand/BathNES.pm

Speed up dashboard CSV export.

---

.cypress/cypress/integration/category_tests.js
CHANGELOG.md
bin/browser-tests
bin/fixmystreet.com/fixture
perllib/FixMyStreet/Cobrand/Borsetshire.pm
perllib/FixMyStreet/DB/Factories.pm
t/Mock/MapIt.pm
web/cobrands/fixmystreet/fixmystreet.js

Also fixes #2276 issue with sub categories on `/report/new`
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1187

front end category tests

---

CHANGELOG.md
bin/send-comments
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/Lewisham.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Script/Questionnaires.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/Open311.pm
perllib/Open311/GetServiceRequestUpdates.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/app/controller/admin.t
t/open311.t
t/open311/getservicerequestupdates.t
t/open311/post-service-request-updates.t

Move send-comments to package and related

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/Update.pm
templates/web/base/report/update/form_update.html
templates/web/bromley/report/update/form_update.html

Allow superusers access to update staff dropdowns.

---

Vagrantfile

- When using the official box, just run `script/update` at startup as
the latest release (0.0.3) has everything fully pre-installed;
- When using the official box, always run the provisioner that checks
and bind mounts the local pre-built Perl modules when starting as
these would previously have been missing after a `halt` and `up`;
- When using any other box, just run the full install process.
[skip ci]

[Vagrant] Improve provisioning for mySociety base box

---

docs/install/ami.md

[Docs] Updated with AMI for release v2.4.2

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Moderate.pm
t/app/controller/moderate.t

Allow moderation to edit category.

---

bin/switch-site
web/js/map-OpenLayers.js

Fixes https://github.com/mysociety/keepitinthecommunity/issues/117 [skip changelog]

[KiitC] Fix issue updating lat/lon fields

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/moderate.t
templates/web/base/report/_main.html
templates/web/base/report/update.html
web/cobrands/fixmystreet/staff.js
web/cobrands/sass/_base.scss

Specifically connected to https://github.com/mysociety/keepitinthecommunity/issues/126 but applies more generally.

Fix moderation without JavaScript.

---

templates/web/buckinghamshire/before_wrapper.html
templates/web/buckinghamshire/footer.html
templates/web/buckinghamshire/header_extra.html
templates/web/buckinghamshire/tracking_code.html
templates/web/lincolnshire/before_wrapper.html

[Buckinghamshire] New tracking code.

---

templates/web/buckinghamshire/report/new/roads_message.html
templates/web/fixmystreet.com/report/new/roads_message.html
web/cobrands/buckinghamshire/assets.js

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/37

[Buckinghamshire] Nicer not-our-road messages.

---

web/cobrands/fixmystreet/fixmystreet.js

Hopefully fixes #1649 issue with using filters first. [skip changelog]

Make sure map state stored if filters used first.

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm

For mysociety/fixmystreet-commercial#997

[WIP] Ground Control pothole changes

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/app/controller/contact.t
templates/web/base/contact/index.html
templates/web/bathnes/contact/index.html
templates/web/buckinghamshire/contact/who.html
templates/web/fixmystreet.com/contact/who.html
web/cobrands/sass/_base.scss
web/js/contact.js

TODO:
Fixes #1072.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/41

[Bucks] [fixmystreet.com] Add topic question to reporting contact form

---

docs/install/ami.md

Updated AMI ID in documentation to reflect v2.5.

[Docs] Updated with AMI for release v2.5

---

locale/sv_SE.UTF-8/LC_MESSAGES/FixMyStreet.po

These are the latest Swedish translations made by Jon Kristensen for v2.5.
Live at fixamingata.se now.

Swedish translations for v2.5

---

web/cobrands/fixmystreet/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1042 [skip changelog]

Stop double green pin on hover-end

---

locale/sv_SE.UTF-8/LC_MESSAGES/FixMyStreet.po
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t
templates/web/base/report/display.html
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/report/update-form-wrapper.html
templates/web/base/reports/_list-filters.html

A few minor things to enable easier updating of the cobrand. I guess override search and the body default could qualify for changelog, but both seem like they wouldn't really have much use. [skip changelog]

[KiitC] Changes needed for asset display updates

---

CHANGELOG.md
bin/update-schema
db/downgrade_0066---0065.sql
db/schema.sql
db/schema_0066-user-area-ids.sql
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/admin/permissions.t
t/app/controller/admin/users.t
t/app/controller/dashboard.t
templates/web/base/admin/user-form.html
templates/web/base/dashboard/index.html
web/cobrands/fixmystreet/admin.js

Update database to store an array of IDs rather than only one; consequential changes to the admin and the dashboard to allow selection. Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1270.

Allow user to be associated with multiple areas.

---

web/cobrands/bristol/assets.js
web/cobrands/fixmystreet/assets.js

BCC have moved their lighting assets to a new WFS URL.
Fixes mysociety/fixmystreet-freshdesk#18.

[Bristol] Use new WFS server for street lighting categories

---

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
t/app/controller/admin.t

Fix admin index body dropdown redirect.

---

perllib/FixMyStreet/App/Controller/Admin/ExorDefects.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/JSON.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/DateRange.pm

This simplifies the places where a date range is used; it also makes Dashboard date parsing more flexible. [skip changelog]

Add DateRange class.

---

web/cobrands/bathnes/js.js
web/cobrands/fixmystreet-uk-councils/roadworks.js
web/cobrands/lincolnshire/roadworks.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1303

[UK Councils] Factor roadworks calls, and fix BANES pin issue

---

perllib/FixMyStreet/App/Controller/Dashboard.pm

Stream dashboard CSV output.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/SendReport/Open311.pm
perllib/Open311.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/app/sendreport/open311.t
t/open311.t
t/open311/post-service-request-updates.t

Not particularly happy about it passing body and cobrand down all through, but can't really see how else to do it?

[Open311] Use cobrand hook for extra update params

---

templates/web/fixmystreet.com/about/faq-en-gb.html

Fixes mysociety/fixmystreet.com#1

[fixmystreet.com] update FAQ now we send reports to Highways England

---

web/cobrands/buckinghamshire/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1326

[Buckinghamshire] Message on Rights of Way category.

---

templates/web/base/report/_item_expandable.html
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/category_wrapper.html
templates/web/base/report/new/form_report.html
web/cobrands/bathnes/js.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet-uk-councils/roadworks.js
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/oxfordshire/assets.js
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss
web/js/duplicates.js

Connects https://github.com/mysociety/fixmystreet-commercial/issues/1304

Duplicate report feedback

---

web/cobrands/northamptonshire/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1296

[Northamptonshire] Hide form on emergency categories

---

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/App/Controller/Admin/Users.pm
perllib/FixMyStreet/App/Controller/Council.pm
perllib/FixMyStreet/App/Controller/Open311.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/App/Controller/Rss.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/Factories.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/MapIt.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/Open311/GetServiceRequests.pm
t/Mock/MapIt.pm
t/app/controller/around.t
t/app/sendreport/email.t

Keep SW&T sending to separate addresses when we create shared body. [skip changelog]

[UK] 2019 structural changes

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/report_as_other.t

Fix superusers creating anonymous reports.

---

CHANGELOG.md
perllib/Open311.pm

This means GET errors will give better output.

[Open311] Factor GET/POST calls together.

---

web/cobrands/fixmystreet/assets.js
web/cobrands/northamptonshire/assets.js

Fixes mysociety/fixmystreet-commercial#1343

[Northamptonshire] add streetlight category message

---

cpanfile
perllib/FixMyStreet/Map/WMTSBase.pm
perllib/FixMyStreet/Roles/PhotoSet.pm
perllib/Utils.pm

These changes should have no negative consequences for the code or its behaviour, but make it simpler or clearer.

Miscellaneous Minor Improvements

---

CHANGELOG.md
templates/web/base/admin/category-checkboxes.html
templates/web/base/admin/responsepriorities/edit.html
templates/web/base/admin/template_edit.html
templates/web/base/admin/users/form.html
templates/web/bromley/admin/category-checkboxes.html
web/cobrands/sass/_admin.scss
web/cobrands/sass/_base.scss

As discussed with @dracos earlier today. Minor tidying for the user admin form.

Neater admin forms

---

docs/install/ami.md

Adds new AMI details to documentation.

[Docs] Updated with AMI for release v2.6

---

templates/web/fixmystreet.com/report/new/roads_message.html
templates/web/northamptonshire/report/new/roads_message.html
web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/northamptonshire/assets.js
web/cobrands/oxfordshire/assets.js

The first commit I think is safe and could be taken alone; am working on second commit more/testing needed, but hopefully along the right lines, I think it could sort itself out better but I tried for now to keep the business code as similar as possible, maybe. [skip changelog]

Message controller

---

.cypress/cypress.json
.cypress/cypress/fixtures/trees.json
.cypress/cypress/fixtures/trees_none.json
.cypress/cypress/integration/bathnes.js
.cypress/cypress/integration/northamptonshire.js
bin/browser-tests
bin/fixmystreet.com/fixture
t/Mock/MapIt.pm
t/cobrand/northamptonshire.t
web/cobrands/fixmystreet-uk-councils/alloy.js
web/cobrands/fixmystreet/assets.js
web/cobrands/northamptonshire/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1323
NB: the cobrand specific client side tests need to be run manually at the moment:
./bin/browser-tests run --cobrand northamptonshire --area_id 2234 --coords '52.236251,0.892052'

Various small post NCC go live fixes

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
t/cobrand/bucks.t

For https://github.com/mysociety/fixmystreet-freshdesk/issues/58

[Buckinghamshire] Include Car parking category.

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/cobrand/hounslow.t
templates/email/hounslow/_council_reference.html
templates/email/hounslow/_council_reference.txt
templates/email/hounslow/_council_reference_alert_update.html
templates/email/hounslow/_council_reference_alert_update.txt
templates/web/base/reports/body.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1402
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1404

[Hounslow] Hide a TfL category, fix some names

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/Result/Body.pm
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/reports/_rss.html

[Hounslow] Couple more council references (RSS related).

---

web/cobrands/northamptonshire/assets.js

fixes mysociety/fixmystreet-freshdesk#60

[Northamptonshire] add midblock asset layer to traffic signals

---

perllib/FixMyStreet/DB/Result/Problem.pm
t/cobrand/hounslow.t
templates/web/hounslow/report/_council_sent_info.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1416

[Hounslow] Show external ID on /report to staff.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t

[Bexley] Also send email for lighting reports.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t

[Bexley] P1 email on dangerous reports.

---

perllib/FixMyStreet/Cobrand/Rutland.pm
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js

[Rutland] limit report summaries to 254 characters

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Root.pm
t/app/controller/report_display.t
templates/web/base/errors/generic.html

Improve 403/private report error messages.

---

templates/web/isleofwight/footer_extra_js.html
web/cobrands/isleofwight/js.js

Fixes mysociety/fixmystreet-commercial#1399

[IsleOfWight] roadworks.org integration

---

templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1427

[Zurich] Remove some parts of admin report view.

---

templates/web/base/common_header_tags.html
templates/web/base/header/title.html
templates/web/zurich/header.html
templates/web/zurich/header/title.html
templates/web/zurich/header_opengraph.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1432

[Zurich] Add new meta title/description.

---

perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1426

[Zurich] Use Beantwortet on external banner.

---

templates/web/zurich/about/faq-de-ch.html

[skip changelog] No reason it couldn't be done early, I thought.

[Zurich] Update FAQ text with new category.

---

perllib/FixMyStreet.pm
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/ResultSet/Alert.pm
perllib/FixMyStreet/DB/ResultSet/Comment.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Script/Questionnaires.pm
perllib/FixMyStreet/Script/UpdateAllReports.pm
t/app/01app.t
t/cobrand/form_extras.t

Turn on quote_names

---

templates/web/isleofwight/footer_extra_js.html

[IsleOfWight] only include javascript on relevant pages

---

perllib/FixMyStreet/Cobrand/Zurich.pm

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1431

[Zurich] Sort categories in admin alphabetically.

---

perllib/FixMyStreet/SendReport/Email.pm
perllib/FixMyStreet/SendReport/Zurich.pm
perllib/FixMyStreet/TestMech.pm
t/cobrand/zurich.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1424

[Zurich] Set envelope for external body emails.

---

perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/Geocode/Zurich.pm
t/cobrand/zurich.t
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1428

[Zurich] Include administrative district in admin.

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

Fixes https://github.com/mysociety/fixmystreet/issues/2541
Fixes https://github.com/mysociety/fixmystreet/issues/2542

Keyboard improvements

---

templates/web/base/contact/enquiry/index.html
templates/web/base/contact/index.html

Localisation for 'optional' in contact forms.

---

perllib/FixMyStreet/Cobrand/Northamptonshire.pm

[Northamptonshire] turn on sending comments over Open311

---

perllib/FixMyStreet/App/Controller/Admin/Users.pm
templates/web/base/admin/users/import.html

Allow password hash setting in user import.

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm

[Oxfordshire] turn on multi photo sending over open311

---

templates/web/bathnes/before_wrapper.html
templates/web/bathnes/tracking_code.html

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/76

[BANES] Add GTM code.

---

web/cobrands/bristol/assets.js

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/72

[Bristol] Switch street lights to other WFS server

---

perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/cobrand/hounslow.t

[UK] Allow multiple admin user domains.

---

locale/de_CH.UTF-8/LC_MESSAGES/FixMyStreet.po

- [no ] Whether this PR should include changes to any documentation, or the FAQ;
- [ general commit] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [no new functionality ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [no ] Are the changes tested for accessibility?
- [no ] Have you updated the changelog? If this is not necessary, put square brackets around this: [skip changelog]
Thanks …

added translations for ZWN

---

templates/web/isleofwight/report/new/_form_labels.html

[IsleOfWight] update report form labels

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm
t/cobrand/isleofwight.t

[IsleOfWight] include FMS prefix on updates sent over open311

---

.cypress/cypress/fixtures/iow_roadworks.json
.cypress/cypress/integration/isleofwight.js
bin/fixmystreet.com/fixture
perllib/FixMyStreet/Cobrand/IsleOfWight.pm
t/cobrand/isleofwight.t
templates/email/isleofwight/problem-confirm.html
templates/email/isleofwight/problem-confirm.txt
templates/email/isleofwight/signature.txt
web/cobrands/isleofwight/js.js

Extra tests for Island Roads

---

templates/web/westminster/footer_extra_js.html
templates/web/westminster/report/new/roads_message.html
web/cobrands/fixmystreet/assets.js
web/cobrands/westminster/assets.js

Will fix https://github.com/mysociety/fixmystreet-commercial/issues/1444

[Westminster] Asset handling

---

perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t
templates/web/zurich/admin/index-dm.html
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/report_edit.html
web/cobrands/zurich/layout.scss
web/js/map-wmts-base.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1467.
One new thing (email on report admin), two fixes to change requests (banner colour, admin sort), two bugfixes (status message overlapping, strategy firing too often).

Zurich post feedback fixes

---

perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/app/controller/auth_social.t
t/cobrand/westminster.t
templates/web/base/report/display_tools.html
templates/web/base/report/update-form.html
web/cobrands/westminster/base.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1469
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1468

[Westminster] No updates

---

.cypress/cypress/integration/isleofwight.js
bin/fixmystreet.com/fixture
perllib/FixMyStreet/App/Controller/Report/New.pm
t/cobrand/isleofwight.t
templates/web/base/report/new/category_extras.html

[IsleOfWhite] make sure category_extras uses correct name

---

t/app/controller/auth_social.t
t/cobrand/westminster.t
templates/web/base/report/new/form_report.html
templates/web/westminster/auth/general.html
templates/web/westminster/report/form/user.html
web/cobrands/sass/_base.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1475

[Westminster] Remove confirm by email

---

t/app/controller/auth_social.t

Adds a test for viewing existing reports when signing in with social auth.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1373

[Westminster] Add test for viewing existing reports

---

perllib/FixMyStreet/Cobrand/Westminster.pm
t/cobrand/westminster.t

Allows Westminster staff + superusers to leave updates on reports.

[Westminster] Allow staff to leave updates

---

perllib/FixMyStreet/App/Controller/Auth/Social.pm

Fixes an issue where the report content was lost if the OIDC password-reset flow was followed if logging in at the same time as making a report.

Preserve partial report if resetting password during OIDC login

---

perllib/FixMyStreet/Cobrand/Northamptonshire.pm
t/cobrand/northamptonshire.t

[Northamptonshire] do not send comments on defects

---

perllib/FixMyStreet/Cobrand/Rutland.pm

Fixes mysociety/fixmystreet-commercial#1495

[Rutland] update default map status to be open

---

templates/web/base/around/postcode_form.html
web/js/geolocation.js

Maintain filter_category/group if locate me used.

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/cobrand/westminster.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1497 [skip changelog]

[Westminster] Do not create any reporter alerts.

---

perllib/FixMyStreet/DB/Result/Problem.pm
t/cobrand/isleofwight.t

Fixes mysociety/fixmystreet-commercial#1522

[IsleOfWight] display external id as ref no

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
t/cobrand/bucks.t

[Buckinghamshire] Update email addresses.

---

templates/web/bristol/footer_extra_js.html
web/cobrands/bristol/js.js
web/cobrands/fixmystreet-uk-councils/roadworks.js

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/79

[Bristol] Add roadworks.

---

web/cobrands/bexley/js.js
web/cobrands/fixmystreet/assets.js

Had to do some geometry; I did not need my new artwork.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1446 [skip changelog]

[Bexley] Add TfL support.

---

bin/site-specific-install.sh

Fixes test suite failures in new Vagrant environments.
See also: #2487

Add Swedish locale instead of Norwegian

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/DB/Result/User.pm
t/cobrand/isleofwight.t
templates/web/isleofwight/tokens/_confirm_problem_council_id.html

Island roads training bugfixes

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/cobrand/westminster.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1497

[Westminster] No email alerts on .com reports.

---

perllib/FixMyStreet/Cobrand/Northamptonshire.pm

[Northamptonshire] Always update report with Open311 state change.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Geocode.pm
perllib/FixMyStreet/Geocode/Bexley.pm
perllib/FixMyStreet/Geocode/Bing.pm
perllib/FixMyStreet/Geocode/Google.pm
perllib/FixMyStreet/Geocode/OSM.pm
perllib/FixMyStreet/Geocode/Zurich.pm
perllib/FixMyStreet/Map/Bexley.pm
t/cobrand/bexley.t
t/geocode/google.t
t/map/tests.t
web/js/map-bexley.js

This adds the new map tile layer when zoomed in, and a new geocoder that looks up in the street asset layer in preference to OSM (those results still shown underneath for the mo). [skip changelog]

[Bexley] New map tiles and geocoder

---

web/cobrands/isleofwight/assets.js

[IsleOfWight] decrease spot asset snap threshold to 5m

---

bin/fixmystreet.com/island_roads_setup_messages
web/cobrands/isleofwight/layout.scss

Make it a bit more obvious that something has been selected.

[IsleOfWight] highlight asset details when selected

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/Roles/Extra.pm
t/app/controller/admin/bodies.t
t/app/model/extra.t
templates/web/base/admin/bodies/contact-form.html
web/cobrands/fixmystreet/admin.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss

One part of #2469 (the top-level part, and disable-form field top-level).

Improve top-level part of admin category form

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm

[IsleOfWight] hide reports created before go live

---

web/cobrands/isleofwight/assets.js

Change the tilma url based on whether we are using the live or staging
site.

[IsleOfWight] use appropriate asset server on staging/live

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm

Mostly to handle the lack of assets in the mobile app

[IsleOfWight] lookup site_code if missing from report

---

templates/web/base/reports/_rss.html
templates/web/isleofwight/report/_council_sent_info.html

Remove reference to council from ref no on report page and rss link on all reports page

[IsleOfWight] update reference number text

---

web/cobrands/fixmystreet/fixmystreet.js

Allow ctrl-/cmd-clicking ‘Report another problem here’ button

---

templates/email/isleofwight/archive.html
templates/email/isleofwight/archive.txt

[IsleOfWight] report archive template

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1634

[Bexley] No P1 email on lighting, allow multiple.

---

.cypress/cypress/integration/duplicates.js
.cypress/cypress/integration/regressions.js
templates/web/base/common_scripts.html
web/js/duplicates.js

[skip changelog] (covered by last time I thought I'd fixed it)

Fix a couple of staff duplicate issues

---

bin/fixmystreet.com/one-off-status-update

Update the script for updating all statuses rather than just the
investigating ones

[Northamptonshire] updated report status backfill script

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/SendReport/Open311.pm
web/cobrands/bexley/js.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1585
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1571
Maybe should rewrite the hooks to take a hash of parameters rather than stick on more arguments...

[Bexley] Add trees layer, provide Confirm fields

---

bin/fixmystreet.com/one-off-status-update

Fix a couple of issues discovered in testing where the Response to
customer wasn't being detected in the database;

[Northamptonshire] small tweaks to backfill script

---

perllib/FixMyStreet/Cobrand/CheshireEast.pm
t/cobrand/cheshireeast.t
templates/email/cheshireeast/_council_reference.html
templates/email/cheshireeast/_council_reference.txt
templates/email/cheshireeast/_council_reference_alert_update.html
templates/email/cheshireeast/_council_reference_alert_update.txt
templates/web/cheshireeast/about/faq-en-gb.html
templates/web/cheshireeast/alert/_list_rss_local.html
templates/web/cheshireeast/around/intro.html
templates/web/cheshireeast/footer_extra_js.html
templates/web/cheshireeast/report/_council_sent_info.html
templates/web/cheshireeast/report/new/roads_message.html
templates/web/cheshireeast/tokens/confirm_problem.html
templates/web/fixmystreet.com/footer_extra_js.html
web/cobrands/cheshireeast/assets.js
web/cobrands/cheshireeast/base.scss
web/cobrands/cheshireeast/layout.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1623
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1622
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1640

Cheshire east changes

---

bin/fixmystreet.com/add_emergency_message
bin/northamptonshire/update-emergency-message
perllib/FixMyStreet/Roles/Extra.pm
t/app/model/extra.t

To avoid having to do it all by hand

[Northamptonshire] script to update emergency message

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/TfL.pm

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1639
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1602

[TfL] Disable questionnaire

---

web/cobrands/buckinghamshire/assets.js

[Buckinghamshire] Allow reporting on "9" roads.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Profile.pm
perllib/FixMyStreet/App/Controller/Root.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/auth.t
templates/web/base/auth/create.html

Allows a cobrand to enforce a password expiry.

Password expiry

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

For https://github.com/mysociety/fixmystreet-commercial/issues/1600

[TfL] Allow case-insensitive ref lookup.

---

perllib/FixMyStreet/Cobrand/TfL.pm

[TfL] Passwords expire after one year.

---

cpanfile
cpanfile.snapshot
perllib/Catalyst/Authentication/Credential/2FA.pm
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/TfL.pm
t/app/controller/auth.t
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1606
[skip changelog] Matching IP addresses given in server config.

[TfL] Mandate 2FA for non-internal-IP staff users.

---

perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t
templates/email/default/alert-update.html
templates/email/default/alert-update.txt

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1629

[TfL] Send email to shortlisted user upon update.

---

bin/tfl/import_categories
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Cobrand/UK.pm
t/cobrand/tfl.t
templates/web/base/report/_item.html
templates/web/tfl/report/_item_extra_class.html
templates/web/tfl/report/_item_heading.html
web/cobrands/tfl/base.scss

Connects https://github.com/mysociety/fixmystreet-commercial/issues/1603

[TfL] Mark reports as safety critical & highlight as such in UI

---

templates/web/fixmystreet.com/report/update/form_state_checkbox.html

Connects https://github.com/mysociety/fixmystreet-commercial/issues/1639

[TfL] Disable form state checkbox on .com.

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

This adds an admin log entry for category changing, and then uses the latest of those to include reassigned by/at in the TfL CSV export file.
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1613

[TfL] Include reassigned by/at in CSV export

---

templates/web/tfl/footer_extra.html
templates/web/tfl/header_site.html
templates/web/tfl/report/new/after_photo.html
templates/web/tfl/report/new/inline-tips.html
web/cobrands/tfl/_colours.scss
web/cobrands/tfl/base.scss

Feedback from TFL acceptance testing addressed in here

Tfl final design tweaks

---

templates/web/base/report/_inspect.html

This seemed like a suspiciously simple solution, so I'm sure I have missed something.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1676

Include extra field values in other categories on inspect form.

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1683

[TfL] Remove action scheduled and for triage states.

---

perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/Mock/MapIt.pm
t/cobrand/greenwich.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1680

[UK] Fix Greenwich RSS feed.

---

perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/cobrand/tfl.t
templates/email/tfl/update-confirm-donotsend.txt
templates/web/base/report/new/form_public_councils_text.html
templates/web/base/report/new/form_report.html
templates/web/tfl/about/faq-en-gb.html
templates/web/tfl/contact/_heading.html
templates/web/tfl/email_sent.html
templates/web/tfl/footer.html
templates/web/tfl/footer_extra.html
templates/web/tfl/footer_extra_js.html
templates/web/tfl/index-steps.html
templates/web/tfl/report/form/private_details.html
templates/web/tfl/report/new/councils_text_all.html
templates/web/tfl/report/new/councils_text_private.html
templates/web/tfl/report/new/form_public_councils_text.html
templates/web/tfl/report/updates-sidebar-notes.html
templates/web/tfl/tokens/confirm_problem.html
web/cobrands/tfl/js.js

Fixes all of https://github.com/mysociety/fixmystreet-commercial/issues/1679 except for https://github.com/mysociety/fixmystreet-commercial/issues/1680 which is a bug.
By the end it was heavy going so my final commit is separate because I know I probably should have done it a different way but hey.

[Tfl] Content changes

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/moderate.t

Fixes both parts of https://github.com/mysociety/fixmystreet/issues/2696.

Fix deletion of cached photos on moderation

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/cobrand/councils.t

[UK] Updates only by reporter on open reports conf

---

templates/web/tfl/report/new/roads_message.html
web/cobrands/tfl/js.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1674

[TfL] Link through to .com with correct co-ordinates.

---

templates/web/tfl/about/faq-en-gb.html
templates/web/tfl/footer_extra_js.html
templates/web/tfl/header_extra.html
templates/web/tfl/tracking_code.html

For https://github.com/mysociety/fixmystreet-commercial/issues/1688 and https://github.com/mysociety/fixmystreet-commercial/issues/1673.

[TfL] Add cookies banner and analytics JS

---

conf/packages
cpanfile
cpanfile.snapshot
perllib/Catalyst/Authentication/Credential/2FA.pm
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Profile.pm
perllib/FixMyStreet/Auth/GoogleAuth.pm
t/app/controller/report_new.t
templates/web/base/auth/2fa/form-add.html

Switch to internal QR code generator.

---

templates/web/bathnes/report/new/roads_message.html
web/cobrands/bathnes/assets.js

Banes road nearby

---

web/cobrands/tfl/assets.js

- No longer fetches roadworks in the past
- Displays promoter/resposibility info

[TfL] Roadworks tweaks

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

If a category is selected.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1695

[TfL] Include category extra fields in CSV export.

---

perllib/FixMyStreet/Cobrand/FixaMinGata.pm
templates/email/fixamingata/submit.txt
templates/web/fixamingata/about/accessibility.html
templates/web/fixamingata/about/council.html
templates/web/fixamingata/about/faq-sv.html
web/cobrands/fixamingata/js.js

Misc. FixaMinGata-specific configurations from the last couple of months.

FixaMinGata cobrand changes

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/FixMyStreet/Roles/ConfirmValidation.pm
t/Mock/MapIt.pm
t/app/controller/report_new.t
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js

Fixes mysociety/fixmystreet-freshdesk#102

[Peterborough] add title length restriction

---

t/cobrand/tfl.t
templates/email/tfl/submit.html
templates/email/tfl/submit.txt

For https://github.com/mysociety/fixmystreet-commercial/issues/1693

[TfL] Include bus stop/traffic signal ID in email

---

web/cobrands/tfl/js.js

Add validator for input[type=time] and helpful error for invalid dates

---

bin/handlemail
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Email.pm
perllib/FixMyStreet/SendReport/Email.pm
t/cobrand/tfl.t
templates/email/tfl/reply-autoresponse
templates/web/base/admin/config_page.html

For https://github.com/mysociety/fixmystreet-commercial/issues/1689

Enable custom do-not-reply address & bounce messages for cobrands

---

perllib/FixMyStreet/SendReport/Email.pm
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1717

[UK] Fix email logo display on submit email.

---

perllib/FixMyStreet/Cobrand/Bexley.pm

[Bexley] Send email for all flooding reports.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t
web/cobrands/bexley/js.js

Similar to what confirm/symology do, but with a different value. [skip changelog]

[Bexley] Include UPRN in Uniform submission.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t

[Bexley] Send Uniform reports by email

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/app/controller/report_new.t
t/cobrand/bexley.t

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/92

[Bexley] Out-of-hours email.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t

[Bexley] Email on missing covers and road defects.

---

templates/web/fixmystreet.com/header/css.html

[fixmystreet.com] Mark front page critical CSS string as safe

---

perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t
templates/web/base/admin/reports/edit.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1721

[Bexley] Resend report on most category changes

---

perllib/FixMyStreet/Cobrand/CheshireEast.pm
perllib/FixMyStreet/Map/CheshireEast.pm
perllib/FixMyStreet/Map/OSM.pm
t/map/cheshireeast.t
t/map/tests.t
templates/web/cheshireeast/report/new/_form_labels.html
templates/web/cheshireeast/report/new/roads_message.html
web/cobrands/cheshireeast/assets.js
web/js/map-OpenLayers.js
web/js/map-cheshireeast.js
web/js/map-wmts-bristol.js
web/js/map-wmts-buckinghamshire.js
web/js/map-wmts-hounslow.js
web/js/map-wmts-isleofwight.js
web/js/map-wmts-zurich.js

[Cheshire East] Use own map tiles.

---

perllib/FixMyStreet/Cobrand/TfL.pm
templates/web/base/around/_postcode_form_examples.html
templates/web/base/around/postcode_form.html
templates/web/oxfordshire/around/_postcode_submit_button.html
templates/web/oxfordshire/around/postcode_form.html
templates/web/tfl/around/_postcode_form_examples.html

[TfL] Front page text change

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_as_other.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1287
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1484

Allow report as another user with only name.

---

perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1725

[TfL] Hide certain categories from admin forms

---

t/app/controller/report_display.t
templates/web/fixmystreet-uk-councils/report/banner.html

In theory these are never unknown so do not display this in report
banner.

[UK] do not show unknown banner on fms pro sites

---

templates/web/rbkc/header_extra.html
web/cobrands/rbkc/_colours.scss
web/cobrands/rbkc/base.scss
web/cobrands/rbkc/layout.scss

Rbkc cobrand design

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1742

[TfL] Include non-open reports in duplicate suggestions.

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
t/app/controller/dashboard.t
templates/web/base/dashboard/index.html

Connects #2702. [skip changelog]

Include category groups in dashboard filter.

---

templates/web/bathnes/footer_extra_js.html
templates/web/bromley/footer_extra_js.html
templates/web/buckinghamshire/footer_extra_js.html
templates/web/cheshireeast/footer_extra_js.html
templates/web/hounslow/footer_extra_js.html
templates/web/lincolnshire/footer_extra_js.html
templates/web/peterborough/footer_extra_js.html
templates/web/rutland/footer_extra_js.html
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js

For https://github.com/mysociety/fixmystreet-freshdesk/issues/107

[Peterborough] Ensure 50 char title limit is restricted to Peterborough reports

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/ImageMagick.pm
perllib/FixMyStreet/Roles/PhotoSet.pm
t/app/controller/report_display.t
templates/web/base/header_opengraph_image.html
templates/web/fixamingata/header_opengraph_image.html

Per-report OpenGraph images

---

perllib/FixMyStreet/Template.pm

Allow img elements in scrubbed fields.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
templates/web/base/admin/bodies/body.html
templates/web/base/admin/council_contacts.txt
templates/web/zurich/admin/bodies/body.html
web/cobrands/sass/_admin.scss

List categories in body admin by group.

---

CHANGELOG.md
templates/web/base/js/translation_strings.html
templates/web/base/report/update-form.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/tfl/js.js

Fixes #2345 [skip changelog]
Probably enough, but feel free to do something else, this (or around line 26 of report/display.html) would be the correct place.

After login during update, separate form/report.

---

CHANGELOG.md
templates/web/base/js/translation_strings.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/tfl/js.js

Fixes https://github.com/mysociety/fixmystreet/issues/2358

Use nicer default photo upload message.

---

templates/web/isleofwight/report/new/councils_extra_text.html

For https://github.com/mysociety/fixmystreet-freshdesk/issues/123

[Isle of Wight] Add extra advisory text above report form.

---

web/cobrands/bathnes/assets.js

[BANES] Limit categories to adopted highways layer

---

t/app/controller/around.t
templates/web/base/reports/_list-filters.html

Fix filter_group selection if category group is a list.

---

docs/install/ami.md

[Docs] Updated with AMI for release v3.0

---

perllib/FixMyStreet/App/Controller/Location.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Map/UKCouncilWMTS.pm
t/cobrand/cheshireeast.t

A number of warnfixes in tests.

---

.gitignore

These symlinks are generated when using the [sort-my-sign](https://github.com/mysociety/sort-my-sign) repo's `bin/create-cobrand-symlinks` script.

Ignore Transport Focus files

---

web/cobrands/lincolnshire/assets.js

To reduce the number of reports that are arriving without a site code

[Lincolnshire] increase NSG layer nearest radius

---

t/cobrand/isleofwight.t
templates/web/isleofwight/report/_item_heading.html

[IsleOfWight] use category for front page report title

---

templates/web/tfl/front/pre-steps.html

[TfL] add Covid-19 front page message

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/CheshireEast.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/Rutland.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
perllib/FixMyStreet/Roles/ConfirmOpen311.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport/Open311.pm
t/app/sendreport/open311.t

Fixes https://github.com/mysociety/fixmystreet/issues/2788

[Open311] Allow save/drop of row changes during send.

---

CHANGELOG.md
bin/export-import-data

This covers response templates, roles, and staff users.
Needs tests.
Fixes https://github.com/mysociety/fixmystreet/issues/2905

Add script to export/import body data.

---

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
t/Mock/MapIt.pm
t/cobrand/highwaysengland.t
templates/email/highwaysengland/submit.html
templates/email/highwaysengland/submit.txt
templates/web/highwaysengland/report/new/inline-tips.html

This is slightly abusing the tips template but seemed better than adding another template.
Fixes mysociety/fixmystreet-commercial/issues/1833

[HE] add a how did you hear about us question

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

As it has switched to using category groups, the special subcategory code needs updating to update the correct variable. [skip changelog]

[Bromley] Fix heatmap category filter.

---

templates/web/tfl/front/pre-steps.html

Request from client to update the text on the homepage.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1851

[TfL] Update homepage message

---

web/cobrands/eastsussex/assets.js

Also update list of categories for asset display

[EastSussex] display information about selected assets

---

perllib/FixMyStreet/DB/Result/Problem.pm

[EastSussex] display council reference number on report

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
t/cobrand/peterborough.t

[Peterborough] Include Skanska ref in description.

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/cobrand/oxfordshire.t

For https://github.com/mysociety/fixmystreet-commercial/issues/1876

[Oxfordshire] Include external problem reference in CSV export

---

perllib/FixMyStreet/DB/ResultSet/Problem.pm

Makes sure cached recent reports are displayed in order.

---

web/cobrands/tfl/assets.js

For https://github.com/mysociety/fixmystreet-commercial/issues/1848

[TfL] Add shelter_id asset attribute mapping

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/cobrand/oxfordshire.t

The Exor reference was missed from the previous commit.
For https://github.com/mysociety/fixmystreet-commercial/issues/1876

[Oxfordshire] Include Exor problem reference in CSV export

---

docs/_layouts/pro.html
docs/pro-manual/admin-tasks.md
docs/pro-manual/deep-linking.md
docs/pro-manual/staff-user-accounts.md

Fixes https://github.com/mysociety/fixmystreet/issues/2978

[Docs] Add deep linking page to Pro manual.

---

t/cobrand/oxfordshire.t
t/open311/getservicerequestupdates.t

The database could return rows in differing orders.

Fix unpredictable tests.

---

templates/web/peterborough/front/pre-steps.html
web/cobrands/peterborough/base.scss

For https://github.com/mysociety/fixmystreet-commercial/issues/1880

[Peterborough] Add COVID-19 banner

---

CHANGELOG.md
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/around.t

Looks like might have been broken since 0796a2b6821e75e22ec6eacd3950ef916b16303d

Fix sorting by most commented on /around map view.

---

perllib/FixMyStreet/Cobrand/TfL.pm
web/cobrands/tfl/assets.js

TLRN-only.
For https://github.com/mysociety/fixmystreet-commercial/issues/1883

[TfL] Add new pavement overcrowding category

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
t/app/controller/admin/report_edit.t

Include name, email and body rather than just user id.

display user detail for contributed_by in report_edit

---

bin/export-import-data

For https://github.com/mysociety/fixmystreet-commercial/issues/1856

Add contact handling to export-import-data script

---

web/cobrands/bexley/assets.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/cheshireeast/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/hounslow/assets.js
web/cobrands/isleofwight/assets.js
web/cobrands/peterborough/assets.js

For https://github.com/mysociety/fixmystreet-commercial/issues/1856 (and the street lighting history can be found at https://mysocietysupport.freshdesk.com/a/tickets/363 ). [skip changelog]
Took the opportunity to factor similar labelled-select code together.

[Peterborough] Add street lights asset layer.

---

templates/web/hart/around/intro.html

For https://github.com/mysociety/fixmystreet-commercial/issues/1875

[Hart] Update front page suggested report types

---

templates/web/base/hercules/bin_days.html
templates/web/base/hercules/confirmation.html
templates/web/base/hercules/summary_report.html
templates/web/base/hercules/summary_request.html
web/cobrands/bromley/_fonts.scss
web/cobrands/bromley/base.scss
web/cobrands/sass/_hercules.scss

Front-end design work on Bromley Waste. WIP but at a good place to merge and deploy to staging while we work out what to do next

Bromley waste design

---

docs/_includes/footer.html
docs/_layouts/pro.html
templates/web/fixmystreet.com/footer_extra.html
templates/web/hounslow/about/mapterms.html
templates/web/isleofwight/about/mapterms.html

Updates the references to mySociety Ltd / UKCOD to their new company names, in the fixmystreet.com and fixmystreet.org footers.

[fixmystreet.com] Update company details in footer

---

templates/web/tfl/front/pre-steps.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1899

[TfL] Update COVID-19 homepage messaging

---

templates/web/base/hercules/bin_days.html
templates/web/base/hercules/govuk/fields.html
templates/web/base/hercules/index.html
templates/web/base/hercules/summary_enquiry.html
templates/web/base/hercules/summary_request.html
web/cobrands/bromley/base.scss
web/cobrands/sass/_hercules.scss

Bromley waste frontend tweaks

---

perllib/FixMyStreet/Cobrand/TfL.pm
web/cobrands/tfl/assets.js

[TfL] Add new Streetspace category, TLRN-only.

---

perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Bristol.pm
perllib/FixMyStreet/Cobrand/UK.pm

[Bath,Bristol] No need for special hidden overrides.

---

bin/import_categories
perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/Open311/PopulateServiceList.pm
templates/web/hackney/footer_extra_js.html
web/cobrands/hackney/assets.js

[Hackney] Add asset layers & improve category import script

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Auth/Social.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/OIDC/Lite/Client/WebServer/AuthCodeFlow.pm
t/Mock/OpenIDConnect.pm
t/app/controller/auth_social.t
templates/web/hackney/auth/general.html
templates/web/hackney/report/form/user.html
web/cobrands/hackney/base.scss

- Updates Auth::Social to be more compatible with G Suite OpenID Connect
- Adds ability to limit OIDC logins to a matching domain
- Adds a "Hackney staff sign-in" link to auth forms on Hackney cobrand

[Hackney] G Suite staff login function

---

web/cobrands/bexley/_colours.scss
web/cobrands/bexley/layout.scss

[Bexley] Redesign.

---

perllib/FixMyStreet/App/Controller/Hercules.pm
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/WorkingDays.pm
t/app/controller/hercules.t
t/cobrand/bexley.t
templates/web/bromley/hercules/services.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1893

[Bromley] Report missed bin only within two working days of collection.

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/FixMyStreet/Map/OSM.pm

Includes a commit from the Hackney PR (changed as per my comment there) [skip changelog]

[Peterborough] Change zoom level

---

.cypress/cypress/integration/peterborough.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/cheshireeast/assets.js
web/cobrands/eastsussex/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/hounslow/assets.js
web/cobrands/peterborough/assets.js

And also a small refactor of that message display code so that the specific cobrand lines aren't needed (I think).

[Bucks] Spot lights ending with "A"

---

conf/systemd.example
perllib/FixMyStreet/DB/Result/Contact.pm

Couple of tiny system things

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Queue/Item/Report.pm
t/app/controller/hercules.t
templates/email/bromley/confirm_report_sent.html
templates/email/bromley/confirm_report_sent.txt
templates/web/base/hercules/confirmation.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1902
Also improves confirmation page, missed that before.

[Bromley] Send sent confirmation email for waste reports.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Memcached.pm
t/cobrand/bromley.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1904 [skip changelog]

[Bromley] Restrict waste lookups per day.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/hercules.t

Hopefully all these small PRs like this are straightforward, rather than annoying :)

[Bromley] waste updates only on open reports

---

cpanfile
cpanfile.snapshot
perllib/Data/ICal/Entry/Event7986.pm
perllib/Data/ICal/RFC7986.pm
perllib/FixMyStreet/App/Controller/Hercules.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/hercules.t
templates/web/base/hercules/bin_days.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1900 [skip changelog]

[Bromley] ICal support

---

perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/cobrand/hounslow.t
templates/web/hounslow/front/stats.html

Change front page stat to include closed+fixed [skip changelog]

[Hounslow] Closed as well as fixed on front page.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/cobrand/bromley.t
templates/web/bromley/hercules/enquiry-problem.html

Guess could be part of #3081 but is separate (and includes 2-day behaviour from previous for missed collections) [skip changelog]

[Bromley] Treat gate/spill/not returned same as missed

---

templates/web/eastherts/about/faq-en-gb.html

Inevitably, missed one reference with first PR...

Change UKCOD to mySociety

---

perllib/FixMyStreet/App/Controller/Hercules.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/hercules.t
t/cobrand/bromley.t
templates/web/bromley/hercules/enquiry-problem.html
templates/web/bromley/hercules/services.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1909 [skip changelog]

[Bromley] Disallow opening if existing missed/request report

---

templates/web/base/dashboard/heatmap-list.html
templates/web/base/dashboard/heatmap.html

Internationalization of the heatmap page.

---

perllib/FixMyStreet/Cobrand/Bristol.pm
t/cobrand/bristol.t

For https://github.com/mysociety/fixmystreet-commercial/issues/1934

[Bristol] Ensure categories edited via the admin are visible on cobrand

---

.cypress/cypress/fixtures/iow_roadworks.json
.cypress/cypress/integration/bathnes.js
.cypress/cypress/integration/isleofwight.js
templates/web/bathnes/footer_extra_js.html
templates/web/bexley/footer_extra_js.html
templates/web/bristol/footer_extra_js.html
templates/web/bromley/footer_extra_js.html
templates/web/buckinghamshire/footer_extra_js.html
templates/web/cheshireeast/footer_extra_js.html
templates/web/fixmystreet-uk-councils/footer_extra_js_base.html
templates/web/hounslow/footer_extra_js.html
templates/web/isleofwight/footer_extra_js.html
templates/web/lincolnshire/footer_extra_js.html
templates/web/northamptonshire/footer_extra_js.html
templates/web/oxfordshire/footer_extra_js.html
templates/web/peterborough/footer_extra_js.html
templates/web/westminster/footer_extra_js.html
web/cobrands/bathnes/js.js
web/cobrands/fixmystreet-uk-councils/roadworks.js
web/cobrands/sass/_base.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1783 [skip changelog]

[UK] Show data from StreetManager.

---

perllib/FixMyStreet/Map/Bing.pm
perllib/FixMyStreet/Map/FMS.pm
t/map/bing.t
t/map/fms.t
templates/web/base/js/translation_strings.html
web/js/map-bing-ol.js

Some fixes falling out after #3041 [skip changelog]

Aerial tile fixes

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/cobrand/bromley.t
templates/web/base/waste/bin_days.html
templates/web/base/waste/summary_report.html

And disallow reporting missed collection if it's day of collection and not yet marked completed.

[Bromley] Completion date display

---

templates/web/highwaysengland/report/new/inline-tips.html

[HighwaysEngland] add notice about offensive language

---

templates/web/highwaysengland/report/new/inline-tips.html

[HighwaysEngland] change where heard from options

---

CHANGELOG.md
perllib/FixMyStreet/Map/Bing.pm
perllib/FixMyStreet/Map/OSM.pm
templates/web/base/maps/_sub_links.html
templates/web/base/maps/bing.html
templates/web/base/maps/fms.html
templates/web/base/maps/google-ol.html
templates/web/base/maps/openlayers.html
templates/web/base/maps/osm.html
templates/web/zurich/maps/zurich.html
web/js/map-OpenStreetMap.js
web/js/map-bing-ol.js

Add the ability for OSM maps to have Bing aerial tiles too.
Also fix an issue (unlikely to occur) whereby if you went to an aerial=1 URL with JS on, it loaded the non-aerial tiles.

Aerial tiles for OSM

---

CHANGELOG.md
bin/update-schema
conf/general.yml-example
db/downgrade_0073---0072.sql
db/schema.sql
db/schema_0073-add-full-text-search-index.sql
perllib/DBIx/Class/Helper/ResultSet/Me.pm
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/App/Controller/Admin/Users.pm
perllib/FixMyStreet/DB/ResultSet/Comment.pm
perllib/FixMyStreet/DB/ResultSet/Contact.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Roles/FullTextSearch.pm

Adds a full text search index to both problems and updates, and updates the admin search to use that index.
If DB_FULL_TEXT_SEARCH_CONFIG is set prior to the database schema change, that value will be used, otherwise it will default to english.

Full text search index

---

web/cobrands/northamptonshire/assets.js

[Northamptonshire] add in V2 PRoW and Traffic Light assets

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/cobrand/oxfordshire.t
templates/email/oxfordshire/submit.html
templates/email/oxfordshire/submit.txt
templates/web/fixmystreet.com/footer_extra_js.html
templates/web/oxfordshire/footer_extra_js.html
templates/web/oxfordshire/report/new/roads_message.html
web/cobrands/fixmystreet/assets.js
web/cobrands/oxfordshire/assets.js
web/cobrands/oxfordshire/base.scss

Mostly reviewed already, bar the NSG maintainable parts of https://github.com/mysociety/fixmystreet/commit/1c67be74451f473b7ffcd27604c0713c097f52c8, the config changes due to using a different layer there also, and some simplification to use shared functions in a few places.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1078 [skip changelog]

[Oxfordshire] Asset layers

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/app/controller/report_inspect.t
t/cobrand/oxfordshire.t
templates/web/oxfordshire/report/inspect/_raise_defect.html

Extra questions to provide information required by the API.
For https://github.com/mysociety/fixmystreet-commercial/issues/1846 [skip changelog]
Outstanding issues listed on that ticket.

[Oxfordshire] Extra questions for raising defect.

---

perllib/FixMyStreet/Reporting.pm

CSV export fix for e.g. spaces in category names.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t
templates/web/bromley/admin/category-checkboxes.html

Couple of fixes from some testing [skip changelog]

[Bromley] admin templates fix

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Reporting.pm
t/cobrand/bucks.t

Off-road flytipping reports were not being categorised on .com like they were on the Buckinghamshire cobrand. [skip changelog]

 [Buckinghamshire] Fix off-road reports on .com.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t
t/cobrand/bromley.t
templates/web/base/waste/bin_days.html
templates/web/bromley/report/_updates_disallowed_message.html

A fix for the script not looking at all reports when fetching updates, better message on closed waste reports, create the alert for reports so users get updates(!), and show the last collection resolution string. [skip changelog]

[Bromley] Some small waste fixes

---

templates/web/fixamingata/about/accessibility.html
templates/web/fixamingata/about/council.html
templates/web/fixamingata/about/faq-sv.html
templates/web/fixamingata/about/privacy.html
templates/web/fixamingata/footer_extra.html
web/cobrands/fixamingata/_colours.scss
web/cobrands/fixamingata/base.scss
web/cobrands/fixamingata/layout.scss

Here are the changes to the FixaMinGata cobrand we've done since March.

Latest changes to the FixaMinGata cobrand

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/cobrand/bromley.t
templates/web/base/waste/bin_days.html
templates/web/bromley/waste/enquiry-problem.html
web/cobrands/bromley/base.scss

7b29f3e for https://3.basecamp.com/4020879/buckets/16062166/todos/2941906765
d3745c4 for https://3.basecamp.com/4020879/buckets/16062166/todos/2942227397
c501fe2 and 12df555 for https://3.basecamp.com/4020879/buckets/16062166/uploads/2945618773

[Bromley] Waste tweaks

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
templates/web/oxfordshire/report/_council_sent_info.html
web/cobrands/oxfordshire/assets.js
web/cobrands/oxfordshire/base.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1960
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1958
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1957
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1963

Oxfordshire asset tweaks

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Contact/Enquiry.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/WorkingDays.pm
t/cobrand/bexley.t
t/workingdays.t
templates/web/base/admin/extra-metadata-item.html
templates/web/base/report/new/category_extras_fields.html

Hopefully no actual changes, just some small tidyings from the Bromley waste branch, and factoring out some functions so they can be used later (e.g. working day calculator, and non-map report creation).

Non map refactoring bits

---

docs/_includes/admin-tasks-content.md

This wasn't covered in the docs already and has been asked a couple of times.

[Docs] Add instructions for automatic export of dashboard CSV

---

templates/web/northamptonshire/front/pre-steps.html

Covers switch from Alloy V1 to V2

[Northamptonshire] add message about upgrade to front page

---

.cypress/cypress/integration/northamptonshire.js
templates/web/fixmystreet.com/footer_extra_js.html
templates/web/northamptonshire/footer_extra_js.html

Temporary measure while Alloy is down for upgrade

[Northamptonshire] turn off assets

---

perllib/FixMyStreet/App/Controller/Noise.pm
perllib/FixMyStreet/App/Form/Noise.pm
t/app/controller/noise.t
templates/web/base/noise/confirmation.html
templates/web/base/noise/govuk/fields.html
templates/web/base/noise/index.html
templates/web/base/report/display.html
web/cobrands/fixmystreet/fixmystreet.js

A variety of small fixes and improvements from testing.

[Noise] Various fixes

---

perllib/FixMyStreet/App/Form/Noise.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
t/Mock/Hackney.pm
t/app/controller/noise.t
templates/web/base/noise/summary.html

[Noise] Add working address lookup.

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Page/Simple.pm
perllib/FixMyStreet/App/Form/Page/Waste.pm
perllib/FixMyStreet/App/Form/Waste.pm
perllib/FixMyStreet/App/Form/Waste/AboutYou.pm
perllib/FixMyStreet/App/Form/Waste/Enquiry.pm
perllib/FixMyStreet/App/Form/Waste/Report.pm
perllib/FixMyStreet/App/Form/Waste/Request.pm
perllib/FixMyStreet/App/Form/Wizard.pm
templates/web/base/waste/index.html
templates/web/base/waste/summary.html

This takes the current form wizard commit from the noise branch (where I had originally taken the code from this branch and then adapted it lots) and refactors it back into this branch as I think it's nicer. Each form gets its own package, the meta saved-data/process stuff is all self contained within the Wizard package, and so the controller is much smaller (as the first page of each form has dynamic fields, there's still a bit of code for that first Page, but hopefully that is clear). It's possible it might change further, but this seemed an okay point to cross it back.

[Bromley] Update wizard stuff with updates from parallel branch

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm
templates/web/isleofwight/footer_extra_js.html
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js

[IslandRoads] use standard confirm validation

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/ResultSet/DefectType.pm
perllib/FixMyStreet/DB/ResultSet/ResponsePriority.pm
perllib/FixMyStreet/DB/ResultSet/ResponseTemplate.pm
perllib/FixMyStreet/Roles/ContactExtra.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/report_inspect.t
t/app/model/responsepriority.t
templates/web/base/report/inspect/extra_details.html

Fixes https://github.com/mysociety/fixmystreet/issues/3195

Do not display deleted priorities in inspect form.

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm

[Central Beds] Include extra params for Symology when POSTing Open311 updates

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
t/cobrand/peterborough.t

For https://mysocietysupport.freshdesk.com/a/tickets/735

[Peterborough] Add USRN, nearest address to CSV.

---

perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_inspect.t
t/cobrand/oxfordshire.t
templates/web/base/report/_inspect.html
templates/web/base/report/_item.html
templates/web/base/report/inspect/extra_details.html
templates/web/oxfordshire/report/inspect/_extra_details_field.html
templates/web/oxfordshire/report/inspect/_inspected.html
templates/web/oxfordshire/report/inspect/_raise_defect.html

After feedback, we construct the extra details string from various other bits being asked, with a JS preview.
Traffic management only applies to Oxfordshire, so put it in there until otherwise.
Couple of other minor UI improvements.

Oxfordshire defect feedback

---

bin/tfl/auto-close-reports
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Reporting.pm
perllib/FixMyStreet/Script/TfL/AutoClose.pm
t/cobrand/tfl.t
t/script/tfl/autoclose.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1955

[TfL] auto close reports

---

perllib/FixMyStreet/Template.pm
perllib/FixMyStreet/TestAppProve.pm
t/app/controller/alert_new.t
t/cobrand/hackney.t

Issue in the new staff HTML thing in emails if extra happens to have Unicode in it anywhere.
And some other small fixes.

Fix unicode issue &c

---

docs/_layouts/pro-print.html

[UK] Pro user guide, link to online version from print version

---

perllib/FixMyStreet/Geocode/Bing.pm
perllib/FixMyStreet/SendReport/Email/Highways.pm
t/Mock/Bing.pm
t/app/sendreport/email/highways.t
t/geocode/bing.t
templates/web/highwaysengland/report/new/roads_message.html
web/cobrands/highwaysengland/assets.js
web/cobrands/highwaysengland/base.scss

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1986 [skip changelog]

[Highways England] Expand nationwide

---

bin/fixmystreet.com/bromley-echo
perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t
t/cobrand/bromley.t
templates/web/base/waste/bin_days.html
templates/web/base/waste/enquiry.html
templates/web/bromley/report/_updates_disallowed_message.html
templates/web/bromley/waste/services.html

Speeds it up from >20s to hopefully no more than 8ish.

Bromley parallelizing

---

web/cobrands/lincolnshire/assets.js

For https://github.com/mysociety/fixmystreet-commercial/issues/2011

[Lincolnshire] Add bus stops asset layer

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t

For https://github.com/mysociety/fixmystreet-commercial/issues/2056

[Zürich] Send admin emails, if any, when report is confirmed

---

perllib/FixMyStreet/Cobrand/Hackney.pm
t/cobrand/hackney.t

- Nearest address
- Nearest postcode
- Metadata fields
For https://github.com/mysociety/fixmystreet-commercial/issues/2054

[Hackney] Include extra columns in dashboard CSV export

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

Small tweaks to the geocoder config to make it Central Beds-specific.

[Central Beds] Geocoder tweaks

---

t/app/controller/noise.t
templates/web/base/noise/confirmation.html
templates/web/base/noise/start.html

Few small updates to text
For https://github.com/mysociety/fixmystreet-commercial/issues/2016

[Noise] Update confirmation and start page text

---

perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/HighwaysEngland.pm
t/app/controller/noise.t

[skip changelog] Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2066

[Hackney] Different noise report destinations.

---

.cypress/cypress/fixtures/peterborough_roadworks.json
.cypress/cypress/integration/peterborough.js
bin/fixmystreet.com/fixture
templates/web/peterborough/footer_extra_js.html
web/cobrands/peterborough/js.js

[Peterborough] only display roadworks for some categories

---

perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm
t/app/script/archive_old_enquiries.t

Also fix the bad tests that said it worked

fix alert/no alert queries for archiving a list of reports

---

perllib/FixMyStreet/Cobrand/CheshireEast.pm
t/cobrand/cheshireeast.t

For https://github.com/mysociety/fixmystreet-commercial/issues/2068

[Cheshire East] Show staff user details in Open311 description for contributed_by reports

---

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
t/cobrand/highwaysengland.t

For https://github.com/mysociety/fixmystreet-commercial/issues/2078

[Highways England] Add custom columns to CSV export

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

[Central Beds] Add server-side road lookup.

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/cobrand/bromley.t

[Bromley] Fix bug showing title field

---

docs/customising/boundaries.md

Fix Nominatim OSM url

---

templates/email/bathnes/_email_color_overrides.html
templates/email/bathnes/_email_top.html
templates/email/fixmystreet.com/_submit_footer.html
templates/email/fixmystreet.com/submit.txt

[BANES] Fix RSS, and [UK] Only show footer on .com reports

---

perllib/FixMyStreet/App/Controller/Noise.pm
perllib/FixMyStreet/App/Form/Noise.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
t/Mock/Hackney.pm
t/app/controller/noise.t
templates/web/base/noise/confirmation.html
templates/web/base/noise/summary.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2123
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2124

[Hackney] noise tweaks

---

perllib/FixMyStreet/App/Controller/Auth/Social.pm

To track down a bug that’s occurring with Azure B2C login
For https://github.com/mysociety/fixmystreet-commercial/issues/2126

Increase logging of OIDC token errors

---

web/cobrands/centralbedfordshire/assets.js

[skip changelog] Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2105 (tilma has a proxy added)

[Central Beds] Trees

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

For https://github.com/mysociety/fixmystreet-commercial/issues/2136

[Central Beds] Include report external id (CRNo) in dashboard CSV export

---

web/cobrands/hackney/assets.js

The server we were using is gone. [skip changelog]
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2143

[Hackney] Move to new asset layer server.

---

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/waste.t
t/cobrand/bexley.t
t/cobrand/bromley.t
t/cobrand/highwaysengland.t
t/cobrand/tfl.t
templates/web/base/report/new/subcategories.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2174

[Highways England] Fix display of "Highways England" category

---

.cypress/cypress/integration/tfl.js
templates/web/tfl/report/new/councils_text_all.html

Add the text requested in https://github.com/mysociety/fixmystreet-commercial/issues/2155 to TfL's new report page.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2155
---

[TfL] Add phone number to report your problem page

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/Mock/MapIt.pm
t/cobrand/tfl.t
templates/web/tfl/admin/bodies/_category_field.html

[TfL] Prevent renaming of hard-coded categories.

---

perllib/FixMyStreet/App/Controller/Noise.pm
t/app/controller/noise.t

[Noise] Reopen closed report on a new occurrence.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2223
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2226
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2227

[Bromley] Fix a few small issues

---

perllib/FixMyStreet/Cobrand/UK.pm

[UK] Fix display of maps on osm.fixmystreet.com.

---

templates/web/bristol/footer_extra.html
templates/web/bromley/footer_extra.html
templates/web/greenwich/front/footer-marketing.html
templates/web/northamptonshire/footer_extra.html

Updates the year in the relevant cobrands.
Hi @struan 
does this look ok?

Update copyright in cobrand footers to update year automatically

---

templates/web/fixmystreet.com/report/new/roads_message.html
templates/web/oxfordshire/report/new/roads_message.html
web/cobrands/oxfordshire/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2104

[Oxfordshire] Add bridges asset layer.

---

.github/workflows/cypress.yml

[Cypress] Pin code coverage version.

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Noise.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/FixMyStreet/Email.pm
t/app/controller/noise.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2255

[Hackney] noise missing field in email/ subject change for noise reports

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[skip changelog] Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1904

[Bromley] Staff bypass waste restriction.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Billing.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
perllib/FixMyStreet/App/Form/Wizard.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
perllib/Integrations/Pay360.pm
perllib/Integrations/SCP.pm
t/app/controller/waste.t
t/cobrand/bromley.t
t/integrations/pay360.t
t/integrations/scp.t
templates/web/base/waste/bin_days.html
templates/web/base/waste/dd.html
templates/web/base/waste/dd_complete.html
templates/web/base/waste/garden/cancel.html
templates/web/base/waste/garden/dd_renewal_error.html
templates/web/base/waste/garden/modify.html
templates/web/base/waste/garden/modify_summary.html
templates/web/base/waste/garden/property_page.html
templates/web/base/waste/garden/renew.html
templates/web/base/waste/garden/renew_summary.html
templates/web/base/waste/garden/subscribe_summary.html
templates/web/base/waste/summary.html
templates/web/bromley/waste/services.html

Bromley waste phase2 payments

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
t/app/controller/waste.t
templates/web/base/waste/garden/modify.html
templates/web/base/waste/garden/subscribe_details.html
web/js/waste.js

Add some javascript to make the payments costs update as you change the
number of bins when creating or modifying a subscription.

[Bromley] update subscription costs as values change

---

templates/email/buckinghamshire/alert-update.txt

For https://github.com/mysociety/fixmystreet-commercial/issues/2246

[Bucks] Update alert email subject

---

perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t

For https://github.com/mysociety/fixmystreet-commercial/issues/2248

[Zürich] Mark internal reports as such in CSV export

---

perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_new.t

Promote categories alone in a group to top-level.

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/app/controller/waste.t

[Bromley] canceling a subscription requires an end date

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t
templates/web/base/waste/garden/renew.html
web/js/waste.js

plus add in JS to auto-update costs

[Bromley] style garden waste renewal pages

---

perllib/FixMyStreet/Cobrand/TfL.pm

[Bromley] Include graffiti category on red routes.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/Integrations/SCP.pm

[Bromeley] pass email address to SCP to avoid rekeying

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/app/controller/waste.t

[Bromley] set client reference for GGW events

---

web/cobrands/cheshireeast/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2050

[CheshireEast] allow cleaning reports to be made anywhere

---

perllib/FixMyStreet/Cobrand/CheshireEast.pm
t/cobrand/cheshireeast.t

[CheshireEast] send address string over open311

---

perllib/FixMyStreet/App/Controller/Waste.pm
templates/web/base/waste/dd.html
templates/web/base/waste/dd_cancelled.html
templates/web/base/waste/dd_complete.html
templates/web/base/waste/dd_form.html

[Bromley] improve direct debit confirm and cancellation pages

---

templates/web/fixmystreet.com/before_wrapper.html
templates/web/hackney/header_logo.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2283 [skip changelog]
Also fixes Hackney logo link.

Developer advert

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/app/controller/waste.t
templates/web/base/waste/garden/subscribe_confirm.html

[Bromley] fix bin days link on card payment confirmation

---

t/app/controller/waste.t

Remove a load of duplication and be more explicit about setting data
where we are relying on it

[Bromley] tidy up echo api mocking in tests

---

templates/web/zurich/footer.html
templates/web/zurich/main_nav_items.html
web/cobrands/zurich/layout.scss

Moving of top menu made it display incorrectly [skip changelog]

[Zurich] Fix navigation display.

---

perllib/FixMyStreet/App/Form/Waste/Garden.pm
t/app/controller/waste.t

If no bins then should be zero so explicitly set it to that

[Bromley] correctly set initial cost for garden waste

---

perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/alert_new.t
t/cobrand/hackney.t
t/sendreport/failures.t

Fix text updates to non mobiles

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/app/controller/waste.t

[Bromley] change containter instruction field name

---

CHANGELOG.md
bin/one-off-update-staff-report-contributed-by
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/app/controller/report_as_other.t
t/cobrand/bathnes.t
t/cobrand/bucks.t

And [Bucks/BANES] if we come across a non pre-fetched contributed_by, look it up.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2278

Always record contributed_by for staff users

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/Open311/PopulateServiceList.pm
t/cobrand/peterborough.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2218
And fixes an issue with consistent sort ordering, happened to be noticed on Peterborough whilst doing this.

[Peterborough] Include extra data in CSV export

---

.cypress/cypress/fixtures/westminster-street-entertainment.json
.cypress/cypress/integration/westminster.js
bin/fixmystreet.com/fixture
web/cobrands/westminster/assets.js

These changes were present in https://github.com/mysociety/fixmystreet/pull/3363 until the final force-push when they were lost.

[Westminster] Fetch UPRN for street pitches.

---

templates/web/base/report/new/after_photo.html
templates/web/bromley/report/new/after_photo.html
templates/web/fixmystreet-uk-councils/report/new/after_photo.html
templates/web/hounslow/report/new/after_photo.html
templates/web/tfl/report/new/after_photo.html

Add statement to new report form about photos leading to fixes

---

perllib/FixMyStreet/App/Controller/Admin/EmergencyMessage.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/admin/emergencymessage.t
templates/web/base/admin/emergencymessage/edit.html
templates/web/base/admin/emergencymessage/index.html
templates/web/base/admin/report_blocks.html
templates/web/base/front/pre-steps.html
templates/web/base/index.html
templates/web/base/waste/header.html
templates/web/bromley/front/pre-steps.html
web/cobrands/bromley/_colours.scss
web/cobrands/bromley/layout.scss

Places the message on every page, assuming e.g. if you had the bin day page bookmarked, you'd want to see it, etc. Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2224 [skip changelog]

[Bromley] Emergency waste message

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm

Factored out from other PRs. Already checked, but I changed it to cache inside call_api given both calls were doing the same thing. Hoping to put this live now rather than wait.

[Bromley] cache bin service lookups for speed

---

.cypress/cypress/integration/westminster.js
bin/fixmystreet.com/fixture
web/cobrands/westminster/assets.js
web/cobrands/westminster/js.js

Westminster have renamed this category at their end, so update the code to match.

[Westminster] Rename Street Entertainment category

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Request.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t
t/cobrand/bromley.t
templates/web/bromley/waste/services.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2228

[Bromley] Add garden waste container request.

---

bin/zurich/overdue-alert
perllib/FixMyStreet/Cobrand/Zurich.pm

Should stop cron errors about ‘Undefined subroutine
&FixMyStreet::Cobrand::Zurich::is_public_holiday’

[Zürich] Fix overdue_alerts script

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

Test failures I think are unrelated, investigating

[Bromley] Add role to CSV

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/Integrations/SCP.pm
t/app/controller/waste.t

Bromley waste phase2 small fixes

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t

last payment type and payment reference.

[Bromley] add some extra garden waste subscription fields

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t

So that a URL like https://recyclingservices.bromley.gov.uk/property/10070014436 continues to work.

[Bromley] Add property UPRN redirect.

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/Mock/MapIt.pm
templates/web/bromley/navigation/_report.html

[Bromley] Hide report link on waste reports.

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

For https://github.com/mysociety/fixmystreet-commercial/issues/2231

[Central Beds] Send problem title/detail/URL as separate Open311 attributes

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t
t/cobrand/bromley.t
templates/email/bromley/site-name.txt

[Bromley] Improve max-per-day waste lookup.

---

bin/fixmystreet.com/bromley-reconcile-dd
perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Pay360.pm
t/app/controller/waste.t
t/cobrand/bromley.t
t/integrations/pay360.t
templates/web/base/waste/bin_days.html
templates/web/base/waste/garden/cancel_confirmation.html
templates/web/bromley/waste/services.html

Fill in some missing code, plus be a bit more helpful about pending cancellations, and subscriptions

Garden Waste Cancellation improvments

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste.pm
t/app/controller/waste.t

Small fixes to changes made for phase 1.

Bromley waste phase2 phase1 fixes

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/Integrations/SCP.pm

[Bromley] include address details for SCP query

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t

[Bromley] Set correct Source for staff, handle future better

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t
templates/web/base/waste/garden/csc_code.html
templates/web/base/waste/garden/renew.html
templates/web/base/waste/garden/staff_no_dd.html
templates/web/base/waste/garden/subscribe_details.html

Bromley waste phase2 csc workflow

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t
templates/email/default/waste/direct_debit_in_progress.html
templates/email/default/waste/direct_debit_in_progress.txt
templates/web/base/waste/garden/csc_code.html
templates/web/base/waste/garden/renew.html
templates/web/base/waste/garden/staff_no_dd.html
templates/web/base/waste/garden/subscribe_details.html
templates/web/bromley/waste/services.html

Bromley waste phase2 bugfixes

---

perllib/FixMyStreet/Cobrand/Bromley.pm

This way, it will still be set for a future-dated schedule, but not set if a scheduled fails to have next/last instances. [skip changelog]

[Bromley] Set description when setting next/last.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t
t/cobrand/bromley.t

Bromley waste phase2 bugfixes 2

---

t/app/controller/waste.t

[Bromley] add start dates to test data

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
t/app/controller/waste.t
templates/web/base/waste/garden/subscribe_details.html

Bromley waste phase2 csc bugfixes

---

perllib/FixMyStreet/Cobrand/Bromley.pm

[Bromley] A unit can have multiple service tasks.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t
templates/web/base/waste/bin_days.html
templates/web/bromley/waste/services.html

Don't skip recently expired garden waste subs from the bin days list so
they can be renewed if people are a bit forgetful.

[Bromley] improve handling of expired subscriptions

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[Bromley] Nicer message if rate limit hit.

---

perllib/FixMyStreet/SendReport/Zurich.pm
templates/email/zurich/submit-external-wish.txt
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/reports/edit.html

From freshdesk #1166, just a link update. [skip changelog]

[Zurich] Update internal map link.

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
t/cobrand/peterborough.t

[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/2390

[Peterborough] External code, display state in CSV

---

templates/web/zurich/bikeable_banner.html
templates/web/zurich/header.html
web/cobrands/zurich/_bikeable_banner.scss
web/cobrands/zurich/base.scss

For https://github.com/mysociety/societyworks/issues/2351

[Zürich] Add Bikeable.ch banner to front page

---

perllib/FixMyStreet/App/Form/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t
templates/web/base/waste/garden/modify.html

Bromley waste phase2 csc emails

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/Integrations/Bartec.pm
templates/web/base/waste/_address_display.html
templates/web/base/waste/bin_days.html
templates/web/base/waste/summary.html
templates/web/peterborough/waste/_address_display.html
templates/web/peterborough/waste/_change_answers_top.html
templates/web/peterborough/waste/_more_services_extra.html
templates/web/peterborough/waste/confirmation.html
templates/web/peterborough/waste/header.html
templates/web/peterborough/waste/index.html
templates/web/peterborough/waste/missing.html
web/cobrands/peterborough/waste.js

This PR builds on top of #3306 with tweaks and changes request by the client ahead of go-live. I've broken the code into two PRs like this to (hopefully) make it a bit simpler to review.

[Peterborough] WasteWorks feedback changes

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/app/controller/waste.t
templates/email/default/waste/csc_payment_failed.html
templates/email/default/waste/csc_payment_failed.txt
templates/web/base/waste/garden/csc_code.html
templates/web/base/waste/garden/csc_payment_failed.html

[Bromley] waste payment failed option for CSC staff

---

perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t

[Bromley] allow user to reset name when renewing

---

templates/email/highwaysengland/submit.txt

For https://github.com/mysociety/societyworks/issues/2397

[Highways England] Update problem report email subject line

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Location.pm
t/app/controller/around.t

For all the amateur radio users of FixMyStreet, of course.

Add Maidenhead Locator System support

---

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
t/cobrand/highwaysengland.t

[Highways England] Add fallback road name lookup.

---

perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t

[Bromley] handle user details defaults better

---

docs/pro-manual/index.md

I have updated the copy on the pro-manual page of fixmystreet.com. 

Update pro-manual page copy

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

Fixes https://github.com/mysociety/societyworks/issues/2412
And fixes issue with stuck updates.

[Bromley] Few edge case bugs

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/app/controller/waste.t

Show expired garden waste subs on the bin list page

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t
templates/web/base/waste/bin_days.html
templates/web/bromley/waste/services.html

Adds garden_disabled feature to disable it entirely, or garden_waste_staff_only to restrict to staff. Only in terms of what is displayed to the user. [skip changelog]

[Bromley] waste phase2 staff only

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t
templates/web/base/waste/garden/subscribe_details.html
web/js/waste.js

This means they can reduce the number of bins, and it makes it a bit
more explicit how many bins they want, rather than having to do sums.

[Bromley] explicitly ask how many bins a customer wants

---

templates/email/default/waste/direct_debit_in_progress.html
templates/web/base/waste/garden/cancel_confirmation.html
templates/web/base/waste/garden/renew.html

[Bromley] waste phase2 more small fixes

---

perllib/FixMyStreet/App/Controller/Waste.pm
t/app/controller/waste.t

[Bromley] don't set up alerts for anonymous garden subs

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
perllib/FixMyStreet/Reporting.pm
t/cobrand/highwaysengland.t

[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/2380

[Highways England] Include updates in report CSV output

---

templates/web/base/waste/bin_days.html
templates/web/bromley/waste/services.html
web/cobrands/sass/_waste.scss

Use gov.uk UI design to make due and over due renewal subscriptions stand out more - closes #2405

[Bromley] Improve design of bin calendar page for Garden Waste renewals

---

templates/web/base/waste/garden/renew.html
web/js/waste.js

[Bromley] fix js updating of price on renew screen

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
t/app/controller/waste.t
templates/web/base/waste/garden/renew.html

This is largely to get round the problem of occasional inaccurate data
by asking and hence hopefully not having incorrect container requests.

[Bromley] ask for current container count on garden renewal page

---

web/cobrands/fixmystreet/assets.js
web/cobrands/tfl/assets.js

This adds bus stations, displays their names in the sidebar when selected (and therefore another commit fixes an issue I discovered with that display not working correctly). [skip changelog] Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2052

[TfL] Bus stations

---

perllib/FixMyStreet/Cobrand/Bromley.pm

[Bromley] add to possible CSC role names

---

perllib/FixMyStreet/Map/OS/API.pm
perllib/FixMyStreet/Map/OS/Base.pm
templates/web/base/maps/openlayers.html
web/cobrands/fixmystreet/map.js
web/js/map-fms.js

So we can specify some extra data if requested [skip changelog]

Add licence option to OS Maps output.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t

store the max end date and not the last end date as Echo doesn't always
list them in date order

[Bromley] don't assume waste service tasks are in date order

---

t/cobrand/cheshireeast.t
templates/web/cheshireeast/front/pre-steps.html
templates/web/cheshireeast/report/new/form_after_heading.html
templates/web/cheshireeast/tokens/confirm_problem.html
templates/web/fixmystreet.com/report/new/_form_labels.html
web/cobrands/cheshireeast/assets.js

Remove various highways notices while there are no highways categories.
Also update the daytime emergency phone number.
Fixes mysociety/societyworks#2424

[CheshireEast] update highways notices and phone number

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t

Renewal notices get sent out 6 weeks in advance.

[Bromley] extend renewal window out to 7 weeks

---

perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t

[Bromley] increase maximum garden bins to 6

---

web/cobrands/bromley/assets.js

Bromley have requested that we remove the trees asset layer for the time being.
Fixes https://github.com/mysociety/societyworks/issues/2426

[Bromley] Remove trees asset layer

---

perllib/FixMyStreet/App/Form/Claims.pm
t/app/controller/claims.t
templates/web/base/claims/confirmation.html

Fixes https://github.com/mysociety/societyworks/issues/2444

[Buckinghamshire] Red claim tweaks.

---

perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/SendReport/Email.pm
t/cobrand/tfl.t

[TfL] Different From for Countdown report emails.

---

perllib/FixMyStreet/App/Controller/Form.pm
t/app/controller/claims.t

[Buckinghamshire] Remove extra CSRF check.

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
t/cobrand/hackney.t

For https://mysocietysupport.freshdesk.com/a/tickets/1122

[Hackney] Email all updates to address that received report

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

Bromley small dd reconcilliation tweaks

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[Bromley] don't error if there's not extensible data

---

perllib/FixMyStreet/Cobrand/Bromley.pm

Otherwise it doesn't set the time which upsets other things

[Bromley] use confirm method when updating canceled subs

---

templates/web/zurich/about/faq-de-ch.html

[Zurich] update FAQ text

---

templates/web/bathnes/around/_postcode_form_post.html

Fixes mysociety/societyworks#2420

[BathNES] add parking issues text to front page

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

Also correct the title of the report.

[Bromley] add sub end date when cancelling DD subs

---

templates/web/cheshireeast/around/intro.html

[CheshireEast] update front page text

---

perllib/FixMyStreet/DB/Result/Body.pm

Add Environment Agency cobrand file

Fix for odour help text

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm

Various small DD reconciliation fixes.

Bromley dd small fixes 2

---

perllib/FixMyStreet/Cobrand/UKCouncils.pm

skip environment agency in bodies restriction

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[Bromley] duplicate reports as unconfirmed so ->confirm works

---

perllib/FixMyStreet/Cobrand/Peterborough.pm

We don't want any margin on this as the front end has no margin, and
having the front end say one thing and the back end do another is
not ideal.

[Peterborough] update the server side private land buffers

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[Bromley] Make sure auto-reports are non-public.

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/CheshireEast.pm
perllib/FixMyStreet/Cobrand/EastSussex.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/SendReport.pm
perllib/FixMyStreet/SendReport/Email/SingleBodyOnly.pm
perllib/FixMyStreet/SendReport/Open311.pm
t/cobrand/bromley.t

[skip changelog] For https://github.com/mysociety/societyworks/issues/2159

[Bromley] Spot duplicate at sending

---

perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Roles/Open311Alloy.pm
t/sendreport/open311.t

Factor out shared code, then add direct photo upload (rather than URL fetching). [skip changelog]

[Hackney] [Northants] Direct photo upload

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
t/cobrand/peterborough.t

Fixes https://github.com/mysociety/societyworks/issues/2562
and another thing.

Peterborough flytipping fixes

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/2553

[Bromley] Show waste categories in admin pages.

---

CHANGELOG.md
perllib/FixMyStreet/Script/Inactive.pm
t/script/inactive.t

Just had such an email. They are not deleted, so do not email them either.

Do not email inactive body comment users.

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm

Bucks Council would like to have the same pins as Oxfordshire County Council. 
for https://mysocietysupport.freshdesk.com/a/tickets/1452

[Buckinghamshire] Give Bucks same pins as Oxfordshire CC

---

templates/web/cheshireeast/front/pre-steps.html
templates/web/fixmystreet.com/report/new/_form_labels.html
web/cobrands/cheshireeast/assets.js

For https://mysocietysupport.freshdesk.com/a/tickets/1485

[Cheshire East] Reenable unadopted highways message

---

perllib/FixMyStreet/Queue/Item/Report.pm

Always log any SendReport errors.

---

web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/assets.js

https://github.com/mysociety/community/issues/111
* Uses Kaarbontech wps feed to map gullies
* Uses information in the feed to create a user message about gully cleaning status

[Bucks] Integrate Kaarbontech feed with drains

---

perllib/FixMyStreet/Cobrand/Bromley.pm

Fixes https://github.com/mysociety/societyworks/issues/2559 [skip changelog]
Didn't have to change any tests, dunno if that was good or bad thing!

[Bromley] Remove unneeded cancellation code.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

This only moves some cobrand specific code out so that it applies to all users.
[skip changelog] Fixes https://github.com/mysociety/societyworks/issues/2182

[Waste] Move bin day check to controller.

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t

[Bromley] Treat open garden sub event as pending.

---

t/app/controller/waste_peterborough.t
templates/web/base/waste/_summary_intro.html
templates/web/base/waste/summary.html
templates/web/peterborough/waste/_summary_intro.html
templates/web/peterborough/waste/index.html
templates/web/peterborough/waste/services.html

[skip changelog] Text tweaks and one feature asked for at https://3.basecamp.com/4020879/buckets/19439943/todos/4190174005 and https://3.basecamp.com/4020879/buckets/19439943/todos/4185940077 (already on staging, client approved)

[Peterborough] Waste text tweaks

---

perllib/FixMyStreet/App/Form/Waste/Garden.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
templates/web/base/waste/garden/_bin_quantities.html

For https://mysocietysupport.freshdesk.com/a/tickets/1504

[Waste] Clarify garden bin collection/emptying wording

---

perllib/FixMyStreet/Cobrand/Merton.pm
templates/email/merton/_email_color_overrides.html
templates/web/base/auth/change_password.html
templates/web/merton/around/intro.html
templates/web/merton/footer_extra.html
web/cobrands/merton/_colours.scss
web/cobrands/merton/base.scss
web/cobrands/merton/layout.scss

Latest updates to Merton cobrand CSS. (All done, really.)

[Merton] CSS feedback changes

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/Cobrand/Peterborough.pm
t/app/controller/waste.t
t/app/controller/waste_peterborough.t
t/cobrand/peterborough.t
templates/web/base/govuk/fields.html
templates/web/base/waste/bin_days.html
templates/web/peterborough/about/faq-en-gb.html
templates/web/peterborough/waste/confirmation.html
templates/web/peterborough/waste/enquiry-problem.html
templates/web/peterborough/waste/services.html
templates/web/peterborough/waste/summary_report.html

A few bits and pieces that needed improving/tidying ahead of the initial public launch.

[Peterborough] WasteWorks phase 1 pre-launch fixes

---

perllib/FixMyStreet/Cobrand/Shropshire.pm
templates/web/shropshire/footer_extra_js.html
web/cobrands/shropshire/assets.js

* Adds asset file and trigger footer
* Adds no_questionnaire setting
* Adds site_config setting

[Shropshire] Assets information

---

perllib/FixMyStreet/Cobrand/Shropshire.pm

Request to increase the zoom level of the map after a search.
https://3.basecamp.com/4020879/buckets/24097582/todos/4315055393
Fixes mysociety/societyworks#2696

[Shropshire] Set zoom level of map to 6

---

templates/web/fixmystreet.com/report/new/roads_message.html
templates/web/shropshire/report/new/roads_message.html
web/cobrands/shropshire/assets.js

If a report is made on a private road will give a private road message
If a report is made not on a public road will give a not Shropshire Council message
https://github.com/mysociety/societyworks/issues/2663

[Shropshire] Add road layer found/not-found messages

---

web/cobrands/shropshire/assets.js

For LAMP, PLMP, ILUM.
New layers have different keys so switching those out.

[Shropshire] Change asset layers to wfs downloaded versions

---

.cypress/cypress/integration/oxfordshire.js
templates/web/oxfordshire/footer_extra_js.html
templates/web/oxfordshire/report/inspect/_raise_defect.html
web/cobrands/oxfordshire/js.js

New defect category, types and detail added, along with a
requirement for more complex behaviour to correctly match
each detail with the correct type and category.
Fixes mysociety/societyworks/issues/2482
and https://mysocietysupport.freshdesk.com/a/tickets/1275V

[Oxfordshire] New Defect Types

---

templates/web/fixmystreet.com/footer_extra_js.html

Needed otherwise .com won't show any Shropshire assets/roads.

[fixmystreet.com] Include Shropshire’s assets.js on map pages

---

perllib/FixMyStreet/Cobrand/TfL.pm
web/cobrands/tfl/assets.js

fixes https://mysocietysupport.freshdesk.com/a/tickets/1613

[TfL] Added new tlrn cat.: 'Graffiti / Flyposting - Political or Anti-Vaccination'

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Modify.pm
perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t
t/cobrand/bromley.t
templates/web/base/admin/reports/edit.html

Fixes https://github.com/mysociety/societyworks/issues/2702
Fixes https://github.com/mysociety/societyworks/issues/2738
Fixes https://github.com/mysociety/societyworks/issues/2558 (also checks renew for get_original_sub, I don't thnik this should have any side effects, the tests then failed correctly because they were finding results of previous tests...)

Minor Bromley waste fixes

---

perllib/FixMyStreet/Cobrand/Zurich.pm

Resolve https://mysocietysupport.freshdesk.com/a/tickets/1621 [skip changelog]

[Zurich] Update app text to match web output.

---

templates/web/fixmystreet-uk-councils/about/privacy.html

Amends standard privacy policy for council with Shropshire changes
https://github.com/mysociety/societyworks/issues/2665

[Shropshire] Council privacy policy for Shropshire

---

perllib/FixMyStreet/App/Controller/Develop.pm
perllib/FixMyStreet/Email.pm
t/app/controller/waste_peterborough.t
t/cobrand/bathnes.t
t/cobrand/bromley.t
t/script/process_updates_file.t

Fixes https://github.com/mysociety/societyworks/issues/2741
[skip changelog] as nothing core uses attachments that wouldn't be working anyway.

Fix email sending with empty attachments array

---

web/cobrands/buckinghamshire/assets.js

Fixes https://github.com/mysociety/societyworks/issues/2607 [skip changelog]

[Buckinghamshire] Request less drains data.

---

templates/web/shropshire/header_extra.html
web/cobrands/shropshire/assets.js

Fixes https://github.com/mysociety/societyworks/issues/2758 [skip changelog]

[Shropshire] parish and part-time lights

---

perllib/FixMyStreet/Cobrand/Merton.pm

This change was requested by Merton on their UAT Trello board.

[Merton] Switch to OSM geocoder

---

perllib/FixMyStreet/Cobrand/Merton.pm
templates/web/fixmystreet-uk-councils/about/privacy.html

- Use our privacy policy, rather than linking to Merton's
- Add a block of text at the start with contact information
- Change the "Contact us" links to their data protection email
Changes requested here: https://github.com/mysociety/societyworks/issues/2629#issuecomment-984664766

[Merton] Privacy policy updates

---

templates/web/tfl/tracking_code.html

TfL have been in touch and asked us to update their Cookiebot code to this new version.
Fixes https://github.com/mysociety/societyworks/issues/2778

[TfL] Update Cookiebot script tag

---

perllib/FixMyStreet/Cobrand/Default.pm
t/cobrand/fixmystreet.t

Fix link deactivation for privacy policy link on privacy policy page.
