bin/send-comments
bin/zurich-overdue-alert
conf/general.yml-example
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/App/Model/EmailSend.pm
perllib/FixMyStreet/DB/ResultSet/AlertType.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/DB/ResultSet/Questionnaire.pm
perllib/FixMyStreet/EmailSend/ContactEmail.pm
perllib/FixMyStreet/EmailSend/DoNotReply.pm
perllib/FixMyStreet/SendReport.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/FixMyStreet/SendReport/EmptyHomes.pm
perllib/FixMyStreet/SendReport/NI.pm
perllib/FixMyStreet/SendReport/Zurich.pm
t/app/model/problem.t
t/app/sendreport/email.t

This means that e.g. SMTP authentication is used when set up by all
emails, not just non-cron ones. Fixes #988.

Use same handling for cron and non-cron email.

---

perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Council.pm
perllib/FixMyStreet/App/Controller/Location.pm
perllib/FixMyStreet/App/Controller/Questionnaire.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Geocode.pm
perllib/FixMyStreet/Geocode/Bing.pm
perllib/FixMyStreet/Geocode/FixaMinGata.pm
perllib/FixMyStreet/Geocode/Google.pm
perllib/FixMyStreet/Geocode/OSM.pm
perllib/FixMyStreet/Geocode/Zurich.pm
t/MapIt.pm
t/cobrand/fixamingata.t
templates/web/base/around/display_location.html
templates/web/base/report/display.html
templates/web/base/report/new/fill_in_details.html
templates/web/bromley/report/display.html
templates/web/fixmystreet/report/display.html
templates/web/seesomething/around/display_location.html
templates/web/zerotb/report/display.html

This includes MapIt postcode lookups, geocoding, query parameters, tile
clicks. This way, we no longer need any "short" versions anywhere, and
the JSON response always uses a decimal point regardless of locale.
Fixes https://github.com/mysociety/fixmystreet-mobile/issues/190

Make sure all co-ordinates are stringified.

---

conf/general.yml-example
perllib/FixMyStreet/Cobrand/BellaVistaEnAccion.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/FiksGataMi.pm
perllib/FixMyStreet/Cobrand/FixMindelo.pm
perllib/FixMyStreet/Cobrand/FixaMinGata.pm
perllib/FixMyStreet/Cobrand/ZeroTB.pm
perllib/FixMyStreet/Cobrand/Zurich.pm

Instead, add it if not present at the negotiation stage. Even if not negotiated, we currently need it to be present for the in_gb_locale() calls to work.

Remove need to have to specify en-gb in LANGUAGES.

---

perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm

This PR:
* Allows cobrands to specify their own `order_by` clause for the `/reports/[body]` page
* Makes the Oxfordshire cobrand order reports by descending order of creation date
Closes mysociety/FixMyStreet-Commercial#681

Order 'all reports' page by confirmation date

---

templates/web/fixmystreet.com/around/postcode_form.html
templates/web/fixmystreet.com/header_extra.html
web/cobrands/eastsussex/report-form.js
web/cobrands/fixmystreet/base.scss
web/cobrands/fixmystreet/layout.scss

The latest suggestion from #785.
**Hypothesis:** Conversions can be increased by giving the reporting process a more clearly defined call to action.
**Method:** For 50% of users, replace the homepage location search box with a large button to “Report a problem”, and a smaller link to “view problems”. Clicking either of these elements does the same thing: fade the elements out, and the existing form in. Once it’s faded in, we auto-focus the form input to save a click, meaning the total number of clicks for the interaction is the same as the existing behaviour.
All set up in Google Analytics, and the experiment is already running. So just needs a code review (and no doubt commit squash) from @dracos, and then we can deploy!
/cc @TomSteinberg @wrightmartin

AB test clicking a button on FMS.com homepage

---

conf/general.yml-example
perllib/FixMyStreet/App.pm

Rather than hardcoding domain names, add a SECURE_PROXY_SSL_HEADER variable that provides a trusted HTTP header and value that can be used to determine if we're behind a HTTPS proxy.

Use config variable for setting proxy trust.

---

perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
templates/web/oxfordshire/report/_council_sent_info.html

* Adds a new `problem_response_days` to the `Default` cobrand that subclasses can override to provide an expected response time based on a problem's category.
* OCC-provided response time figures are implemented in the `Oxfordshire` cobrand.
* The response time is displayed at the top of the report when viewed in the Oxfordshire cobrand.
Fixes mysociety/FixMyStreet-Commercial#680.

Add expected response time to report page

---

perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm

* Adds a new `reports_ordering` sub to the `Default` cobrand that's used to control ordering of reports in `Reports.load_and_group_problems`.
* Orders reports by confirmed date in the `Oxfordshire` cobrand.
Fixes mysociety/FixMyStreet-Commercial#681.

Allow cobrands to specify report ordering on 'all reports' page

---

perllib/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Smidsy.pm
templates/web/smidsy/around/tabbed_lists.html
web/cobrands/smidsy/base.scss
web/cobrands/smidsy/layout.scss

This is the markup and styling for a checkbox that lets the user show or hide Stats19 data in the Collideoscope cobrand.
@osfameron needs to add the backend logic that makes the checkbox work.
@BenJam needs to decide, with our partners, whether "Stats19 reports" is the right wording to use. Maybe "reports from the Department for Transport" might be clearer?

Stats19 checkbox on Collideoscope /around page

---

templates/web/base/report/update.html
templates/web/fixmystreet/report/update.html
web/cobrands/sass/_base.scss

Fixes #424.
Primary improvement is that images no longer shrink into oblivion when they're next to a very wordy update:
Using a float rather than table-cell styling also means we no longer have to work around IE7 table display support.
Works for short updates with images too:

Simplify .update-img layout

---

bin/setup-contacts
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
templates/web/zurich/report/new/fill_in_details_form.html

https://github.com/mysociety/FixMyStreet-Commercial/issues/663
Note that FMS::Cobrand::EastSussex and FMS::Cobrand::Harrogate still have temporary routines that generate contacts extra as arrays.  This shouldn't be an issue as 3b7adb471 will transparently upgrade them (and they most probably won't be rerun in any case.)
But TODO: refactor those cobrands to use setup-contacts script provided, for neatness.

Zurich: Issues/commercial/663 zurich fields and categories

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Admin.pm

This PR:
- Fixes a bug in `App::get_param_list` that would cause a non-empty list to be returned if the param was missing from the request
- Fixes a bug meaning only the first of the selected areas would be associated with the body when updating or creating it.

Fix multiple body areas

---

templates/web/base/reports/index.html
web/cobrands/sass/_base.scss
web/cobrands/sass/_fixedthead.scss
web/js/jquery.fixedthead.js

Fixes #50.
Works in browsers all the way back to IE8. Degrades relatively gracefully in IE6–7 (position fixed doesn't work, so the table header row is just duplicated in place).
On all browsers, there’s a slight jump in cell widths when the floated header kicks in—possibly something to do with the percentage widths on the original table cells?—but I think we can live with it.

Fix “All Reports” table headers to top of window on scroll

---

templates/web/base/admin/header.html
web/cobrands/sass/_admin.scss
web/js/fixmystreet-admin.js

As per @dracos and @davewhiteland's comments on https://github.com/mysociety/fixmystreet/pull/1160
this removes the show-admin-notes css and makes admin notes and errors display
all the time.
Closes #1161
This will need to be backported to Zurich to close https://github.com/mysociety/FixMyStreet-Commercial/issues/706 too.

Drop .show-admin-notes class and associated code

---

perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin.t
templates/web/base/admin/bodies.html
templates/web/base/admin/body-form.html
templates/web/base/admin/body.html
templates/web/base/admin/category_edit.html
templates/web/base/admin/report_edit.html
templates/web/base/admin/user-form.html
templates/web/base/admin/users.html
web/js/fixmystreet-admin.js

This PR allows a body's external URL to be edited in the admin (no ticket). While it's there, it adds a mark as sent button (fixes #601); adds a link to a body's comment_user_id (fixes #580); adds mapit links to body/report pages (fixes #638); shows category extra data (fixes #517, fixes #920); lists report bodies more nicely on a report page, with links (no ticket); stars users who have moderate permission (fixes #990), and tweaks the display of body form a bit.

Add some admin things

---

web/cobrands/eastsussex/base.scss
web/cobrands/eastsussex/layout.scss

This is a bit of a hacky way to fix it, because the cobrand html/css is a bit
non-standard, but it does the trick I think.
Closes https://github.com/mysociety/FixMyStreet-Commercial/issues/542

[East Sussex] Stop the header scrolling off the screen on the map page

---

perllib/FixMyStreet/App/Controller/Rss.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/DB/ResultSet/AlertType.pm
t/app/controller/rss.t

If a cobrand has a body restriction, then a report without any body
won't be shown on it, so we need to make sure links to the report (in
email alerts and RSS) are to the base URL, not the cobrand.

Use base URL in cobrand alert for no-body report.

---

perllib/FixMyStreet/Cobrand/EastSussex.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/Stevenage.pm

Overrides `contact_email` in the East Sussex and Greenwich cobrands so that emails from the
`/contact` page get sent to the council, rather than us.
~~This is hopefully very simple, I'm just making it a PR so that someone can
tell me if I've misunderstood all the implications of doing this (I have 4
more cobrands to update this on soon).~~
Fixes https://github.com/mysociety/FixMyStreet-Commercial/issues/619, https://github.com/mysociety/FixMyStreet-Commercial/issues/726

[East Sussex, Greenwich] Add contact email addresses

---

templates/web/base/maps/openlayers.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_layout.scss

Hide the map with aria-hidden, as all report links are duplicated in the main content. Fix skip map link on mobile (it was disappearing). Place delegate handler on body to prevent e.g. VoiceOver announcing everything underneath .container as clickable. Remove header report button rather than hide off-screen, as is a duplicate link to the previous.

Improve accessibility of map pages.

---

perllib/FixMyStreet/App/Controller/Auth.pm

If a sign-in button explicitly clicked, use it.

---

perllib/FixMyStreet/App/Controller/Questionnaire.pm
t/app/controller/questionnaire.t

Treat an update left during a questionnaire the same as one left on a
report page, ie. pass it through cleanup_text. This will also make sure
updates left that are wholly whitespace are errored, or replaced with
the default text.

Process update left as part of questionnaire.

---

perllib/FixMyStreet/App/Controller/Reports.pm
t/app/controller/reports.t

Adds `is_deleted` to the ORM query that pulls out the list of categories for
the filters on the new combined reports page that Greenwich/Oxfordshire/Bromley
use. I've included a basic test too.
Closes #1239

Exclude deleted categories from the all reports page filters

---

web/cobrands/greenwich/base.scss
web/cobrands/sass/_base.scss

The use of the background shorthand was causing cobrands which override this
to have unexpected styling issues because it only set a colour, not the other
background properties.
This commit makes it more specific by just using background-color.
Fixes #1238

Don't set whole background style in issue-list css

---

templates/web/hart/footer.html
web/cobrands/eastsussex/layout.scss
web/cobrands/hart/hart.scss
web/cobrands/sass/_layout.scss
web/cobrands/stevenage/layout.scss

The changes in 99610f1 missed out adding a class to the footer menu,
and a few subsequent changes to the CSS.

[Hart] Fix missing menu class, tidy remaining.

---

perllib/Catalyst/Engine.pm
perllib/Catalyst/Log.pm
perllib/FixMyStreet/App/View/Web.pm

Upgrade Catalyst::Engine and Catalyst::Log to 5.90030 so that errors are logged via psgi.errors rather than printed to the (perhaps nulled) stderr. Fixes #404.
Also prevent Catalyst::View::TT from logging errors twice.

Fix lack of error logging in certain scenarios.

---

bin/install_perl_modules
bin/make_css

If the CDPATH environment variable is set (so cd can look in multiple
places), cd prints out the resulting directory when used. This confuses
a command sequence used in a couple of places doing (cd && pwd) to get
a directory path. Make sure we ignore any output from cd.

Fix non-working scripts when CDPATH is set.

---

cpanfile.snapshot

Module::Pluggable is marked as deprecated in Perl 5.18, to be removed
from core in a later version. cpanminus, which is called from carton,
ignores core modules that have been deprecated - running a deployment
install under 5.18 therefore caused a warning to be shown saying that
it could not find Module::Pluggable as no version was included in the
snapshot.

Add Module::Pluggable to cpanfile snapshot.

---

templates/web/base/maps/google-ol.html
web/js/map-google-ol.js

A repeat of cc6a278; Google have now dropped version 3.20 of their Maps API, which we were using. Version 3.21 is the oldest available version, and only appears to work if you start off in hybrid view.
According to https://developers.google.com/maps/documentation/javascript/versions, in three months 3.21 will be dropped; 3.22 does not currently work with our OpenLayers code at all. Looking at http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/google-v3.html the maps do still appear if you first switch to the Satellite layer. So investigation will be needed to find out why that happens and if it can be worked around.

Default the Google map view to hybrid

---

templates/web/base/alert/index.html
templates/web/base/alert/list.html
web/cobrands/sass/_base.scss

Fixes #1168 (sidebar overlapping footer) by avoiding the sidebar entirely.
Photos are presented in a single row, with wrapping disabled. Grey background makes them recede a little, in an effort to make them less distracting.
I'm not convinced of the value of the photos without any anchoring text (lots of shots of potholes doesn't really serve as a glamorous advertisement for the alerts service) but in lieu of a major rethink for the alerts pages, this is a quick fix that avoids the footer overlap problem and reduces the number of pages using one of those smartypants fixed sidebars by two, which can only be a good thing.

Move alert page "recent photos" out of sidebar

---

templates/web/fixmystreet.com/front/international_banner.html
templates/web/fixmystreet.com/report/new/unresponsive_body.html
web/cobrands/fixmystreet.com/base.scss
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/cobrands/warwickshire/layout.scss

If the country banner was displayed, it would overlap e.g. the mobile header. Fix this and tidy up CSS at same time.

Tidy up banner CSS and fix overlap bug

---

web/cobrands/fixmystreet.com/_colours.scss
web/cobrands/sass/_base.scss
web/js/map-OpenLayers.js

Fixes #1094.
Hovering over map pins highlights the relevant item from the
sidebar beside the map. And hovering a sidebar item highlights
the relevant map pin.
Clicking a map pin takes you directly to the relevant report
page, just like clicking an item in the sidebar.
This means the OpenLayers popup "balloon" no longer appears on
clicking a pin, and has been removed entirely.
To make customisation of the list item hover colour easier,
it has been abstracted out into a SCSS variable that cobrand
authors should override (as the fixmystreet.com cobrand does)
or leave at its default light grey colour.

Clearer relationship between map pins and list items

---

templates/web/base/questionnaire/index.html
templates/web/base/report/new/form_report.html
templates/web/base/report/update/form_update.html
templates/web/bromley/report/display.html
templates/web/bromley/report/new/fill_in_details_form.html
templates/web/eastsussex/report/update-form.html
templates/web/zurich/report/new/fill_in_details_form.html
web/cobrands/fixmystreet/fixmystreet.js

The uploaded_files solution in cbdfcad6, to show already uploaded files
stored in upload_fileid, worked if you submitted the form to the server
and had it returned, but did not show remembered photos if you used the
browser's Back button to return to the form from another page.
Instead, always read the data from upload_fileid, which works whichever
way you have come to the page. Fixes #1332.

Show remembered uploaded photos when Back used.

---

bin/handlemail
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/ResultSet/Secret.pm
perllib/FixMyStreet/Email.pm
perllib/FixMyStreet/EmailSend.pm
perllib/FixMyStreet/EmailSend/ContactEmail.pm
perllib/FixMyStreet/EmailSend/DoNotReply.pm
perllib/FixMyStreet/EmailSend/Variable.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/SendReport/Email.pm
t/email.t

Auto unsubscribe alert bounces, forward on report bounces and alert replies to support, and send through to report creator non-bounce replies to their report (for systems that ignore both the From and Reply-To headers).

Better handle replies to bounce addresses.

---

templates/web/base/report/photo.html
web/cobrands/sass/_base.scss

Displaying the images smaller makes the lines of text easier to read, and makes display of multiple images much better. People can still click the images to see them full size.
Fixes #1325.
Before:
After:

Smaller image display for reports and updates

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/EmptyHomes.pm
perllib/FixMyStreet/Cobrand/UK.pm
t/cobrand/form_extras.t
t/cobrand/form_extras/templates/report/new/after_photo.html

Taking the idea from #1291 (thanks), but adding optional required attribute, and storing the results in the extra metadata hash rather than the extra fields list.

Add cobrand-specific custom reporting fields

---

.gitignore
.travis.yml
.travis/after_script
.travis/install
.travis/utils.py
cpanfile
cpanfile.snapshot
perllib/FixMyStreet/App/Controller/Rss.pm
perllib/FixMyStreet/TestMech.pm
perllib/Open311/Endpoint.pm
t/Mock/MapItZurich.pm
t/app/helpers/send_email.t
t/app/helpers/send_email_sample_mime.txt
t/cobrand/zurich.t
t/cobrand/zurich_attachments.txt
t/open311/endpoint.t
t/open311/endpoint/Endpoint1.pm
t/open311/getupdates.t

The following modules had bugs that have been fixed for working in recent perls:
* List::MoreUtils
* Guard
* PadWalker
* aliased
* URI
* Convert::NLS_DATE_FORMAT
The CGI module was removed from core in 5.20, so also include it in the snapshot (I don't think it's actually used, but is a dependency).

Updates to cpanfile to work with perl 5.20/5.22.

---

bin/handlemail
cpanfile
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/Email.pm
t/app/01app.t
t/app/controller/questionnaire.t
t/app/helpers/send_email.t
t/app/helpers/send_email_sample.txt
t/app/helpers/send_email_sample_mime.txt
t/app/model/alert_type.t
t/cobrand/fixamingata.t
t/cobrand/zurich.t
t/cobrand/zurich_attachments.txt
t/i18n.t

The code was using Email::Simple for headers, then creating an on-the-wire email with nice encoded handling, then using Email::MIME if there were attachments. Switch to only using Email::MIME (slightly less nice encoded handling, but whatevs). A step to using same template handling for all email templates.

Refactor email

---

bin/zurich/update_report_descriptions.sql

Zurich would like to update the detail text of a whole bunch of reports on the site. They've provided a CSV file with the report ID and the new detail text for the reports in question.
This script applies the new details to the database from the file 'report_updates.txt'.

SQL script to bulk-update reports from CSV

---

perllib/FixMyStreet/SendReport/Angus.pm
perllib/FixMyStreet/SendReport/EastHants.pm
perllib/FixMyStreet/SendReport/Open311.pm

This should stop the "read timeout" emails.
And also store the actual server error in the database for easier debugging.

Quieten Open311 errors

---

perllib/FixMyStreet/App/Controller/Report.pm
templates/web/base/report/_main.html
templates/web/oxfordshire/report/_main.html
web/cobrands/sass/_base.scss
web/js/moderate.js

Part of mysociety/fixmystreet-commercial#731
Moderation UI is now better laid out into logical chunks.
There was one bug I couldn't work out, that @davea or @stevenday will need to fix:
And a potential improvement that will make reverting better – again, something for @davea or @stevenday:

Tidy up in-place moderation UI

---

templates/web/stevenage/footer.html
templates/web/stevenage/header.html
templates/web/stevenage/header_logo.html
web/cobrands/stevenage/_colours.scss
web/cobrands/stevenage/_council_header.scss
web/cobrands/stevenage/_council_header_responsive.scss
web/cobrands/stevenage/base.scss
web/cobrands/stevenage/layout.scss

Fixes https://github.com/mysociety/FixMyStreet-Commercial/issues/774.
Small screen:
Small screen, landscape:
Tablet, portrait (768px):
Tablet, landscape (1024px):
Large screen:
Here’s a visual diff between the live stevenage.gov.uk header, and the version from this pull request:
Visual diff highlights the pixels that are different between the two versions – so, aside from small type rendering differences, the most notable changes are a slight shuffling of the main menu nav items (we distribute them with roughly equal space around each one, whereas the Stevenage site gives each one an identical fixed width) and a removal of the secondary links next to the search box.

Responsive header for Stevenage cobrand

---

perllib/FixMyStreet/App/Controller/Report/New.pm
templates/web/base/reports/_list-filters.html

It was being treated as a new report and showing errors, rather than
showing you the same page with updated filters. Fixes #1422.

Redirect correctly if filter used sans JavaScript.

---

web/cobrands/bristol/layout.scss
web/cobrands/eastsussex/layout.scss
web/cobrands/fixmystreet.com/posters.scss
web/cobrands/harrogate/layout.scss
web/cobrands/hart/layout.scss
web/cobrands/oxfordshire/layout.scss
web/cobrands/sass/_layout.scss
web/cobrands/sass/_mixins.scss
web/cobrands/stevenage/layout.scss
web/cobrands/zurich/layout.scss

Fixes #1419.
The main change was removing `box-shadow` from `.content` and `.content aside` in `sass/_layout.scss`. All the rest is just removing all the places that cobrands overrode these shadows with their own `box-shadow: none`.

Remove default box-shadow from .content and aside

---

templates/web/fixmystreet-uk-councils/contact/blurb.html

The default wording says messages do not go to a council, which is not true for
UK council cobrands.

[UK Councils] Clarify who receives messages from the contact form.

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Bristol.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Hart.pm

This adds a new Cobrand::Default::categories_restriction method that can be used
to limit what categories are available when making a new report on a per-cobrand
basis.
This is used by Cobrand::Bristol to only show Open311 categories when making a
new report on fixmystreet.bristol.gov.uk but allowing all categories on FMS.com.
Also removes the Hart::hidden_categories and uses the new categories_restriction
method to achieve the same thing.

[Bristol] Only show Open311 categories on Bristol cobrand

---

perllib/FixMyStreet/App.pm
templates/email/default/_email_bottom.html
templates/email/default/_email_comment_list.html
templates/email/default/_email_settings.html
templates/email/default/_email_sidebar.html
templates/email/default/_email_top.html
templates/email/default/alert-problem-area.html
templates/email/default/alert-problem-council.html
templates/email/default/alert-problem-nearby.html
templates/email/default/alert-problem-ward.html
templates/email/default/alert-problem.html
templates/email/default/alert-update.html
templates/email/default/contact.html
templates/email/default/problem-confirm-not-sending.html
templates/email/default/problem-confirm.html
templates/email/default/problem-moderated.html
templates/email/default/questionnaire.html
templates/email/default/submit.html
templates/email/default/update-confirm.html
templates/email/fixmystreet.com/submit.html

* White body background for HTML emails (avoids illegible replies in Outlook)
* Tweak contact HTML footer.
* Log email sending failure from site
* Try and remove all end line spaces from emails
* Factor out sidebar to template
Fixes #1469.

HTML email fixes

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/report_as_other.t
templates/email/default/other-reported.html
templates/email/default/other-reported.txt
templates/email/default/other-updated.html
templates/email/default/other-updated.txt
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/report/update/form_name.html
web/cobrands/fixmystreet/fixmystreet.js

Part of mysociety/fixmystreetforcouncils#10 and mysociety/fixmystreetforcouncils#11.
Todo:

Let council users submit reports/updates as another user, or as the council

---

web/cobrands/fixmystreet/fixmystreet.js

Problems nearby should load the /around page from those pages, rather
than act like "Back to all reports" but changing to an incorrect URL.

Fix "Problems nearby" link on /my and /reports.

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/app/controller/admin.t
t/app/controller/admin_permissions.t
t/app/controller/moderate.t
templates/web/base/admin/stats.html
templates/web/base/admin/user-form.html

- Adds `report_edit` and `user_edit` permissions which are required to edit reports or users via the admin
- Cobrand admin doesn't allow editing of users from other cobrands
- Setting a user's `from_body` is a simple 'staff' tickbox for non-superusers, which sets `from_body` to the same as the logged-in user.
- Individual permissions can be granted/revoked via the user edit form, if the logged-in user has the `user_manage_permissions` permission.
For mysociety/fixmystreetforcouncils#35

Add permissions restrictions/management to admin

---

bin/update-schema
db/downgrade_0042---0041.sql
db/schema.sql
db/schema_0042-planned_reports.sql
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/DB/Result/AdminLog.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/DB/Result/UserPlannedReport.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/my.t
t/app/controller/my_planned.t
t/app/model/user_planned_report.t
templates/web/base/around/lookup_by_ref.html
templates/web/base/my/planned.html
templates/web/base/report/_main.html
templates/web/oxfordshire/header.html
web/cobrands/fixmystreet/fixmystreet.js

Searches the `id` and `external_id` fields.
This takes you directly to the report if only a single report matches, otherwise
a disambiguation page is shown.
For mysociety/fixmystreetforcouncils#16

Allow searching for reports with ref: prefix in postcode field

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Location.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
templates/web/base/js/translation_strings.html
templates/web/base/report/_inspect.html
templates/web/base/report/_main.html
templates/web/base/report/display.html
templates/web/base/report/inspect.html
templates/web/fixmystreet-uk-councils/maps/fms.html
templates/web/fixmystreet.com/maps/fms.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/oxfordshire/_oxon.scss
web/cobrands/oxfordshire/layout.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss
web/cobrands/sass/_mixins.scss
web/js/map-OpenLayers.js
web/js/map-wmts-zurich.js

As part of the FixMyStreet for Councils work, this PR adds a new page that allows a council inspector to view and manage a problem by adding detailed notes, setting its priority etc.
This is still a work-in-progress, but I'm opening this PR to allow us to keep track of the page changes.
See mysociety/fixmystreetforcouncils#22, mysociety/fixmystreetforcouncils#39.

Add 'inspect report' page

---

bin/update-schema
db/downgrade_0044---0043.sql
db/schema.sql
db/schema_0044-contact_response_templates.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/DB/Result/ContactResponseTemplate.pm
perllib/FixMyStreet/DB/Result/ResponseTemplate.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/admin.t
t/app/controller/admin_permissions.t
templates/web/base/admin/response_templates_select.html
templates/web/base/admin/template_edit.html
templates/web/base/admin/templates.html
templates/web/base/admin/templates_index.html
templates/web/base/admin/user-form.html
templates/web/base/admin/users.html
templates/web/base/report/update/form_update.html
templates/web/oxfordshire/header.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/oxfordshire/layout.scss

This extends the Zürich response template admin functionality to all cobrands, and adds:
- Templates have an 'auto-response' flag, for automatically adding an update when a problem is left (future functionality)
- Templates can be assigned to individual categories in addition to bodies
- Managing templates requires the `template_edit` permission.
For mysociety/fixmystreetforcouncils#31

Response template management

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/DB/Result/Problem.pm
templates/web/base/report/_council_sent_info.html
templates/web/oxfordshire/report/_main_sent_info.html

This introduces a new `is_council_with_case_management` flag for Cobrands, that,
when active, considers any report that's been confirmed as having been received
by the Council in question.
See mysociety/fixmystreetforcouncils#65

[Oxfordshire] Display confirmed reports as received by the Council

---

templates/web/base/report/new/form_report.html

Part of mysociety/fixmystreetforcouncils#41.
Form labels now describe what the user should do, and placeholders
give a supporting example of what their input should look like.
Placeholder text in the "Summary" box now suggests that people
include a location in their summary. Likewise with a timescale in
the "Description" box.
Placeholders use potholes as an example, since potholes are the most
common complaint on FMS. Maybe eventually we might want to change the
placeholder text based on the category the user selects…

Improve "Summary" and "Description" form guidance

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/sendreport/inspection_required.t
t/cobrand/get_body_sender.t
templates/web/base/admin/body.html
templates/web/base/admin/category_edit.html
templates/web/base/report/_inspect.html

- Adds an 'inspection required' boolean field to categories, managed via the admin
- Skips sending reports that haven't been inspected if their category requires it
- Adds button to inspect view allowing report to be marked as inspected
For mysociety/fixmystreetforcouncils#50

Add ability for reports to be inspected before being sent

---

bin/update-schema
db/downgrade_0045---0044.sql
db/schema.sql
db/schema_0045-response-priorities.sql
perllib/FixMyStreet/App/Controller/Admin/ResponsePriorities.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/DB/Result/ContactResponsePriority.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/ResponsePriority.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/admin.t
templates/web/base/admin/responsepriorities/edit.html
templates/web/base/admin/responsepriorities/index.html
templates/web/base/admin/responsepriorities/list.html
templates/web/base/report/_inspect.html

This PR upgrades the hard-coded `Oxfordshire::problem_response_priorities` method into a fully-fledged `ResponsePriority` model which can be managed via the admin. Priorities are assigned to bodies and categories, and Problems can optionally have a priority set.
For mysociety/fixmystreetforcouncils#66

Response priority management in admin

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Council.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
templates/web/base/report/_main.html

This is a cut-down version of the full inspect screen. There is a "manage" button if the user has either the edit category or edit priority permissions.
Not sure I like bits of this code-wise, e.g. hardcoded superuser for all permissions, but the alternative was more `can_*` variables in the template. Perhaps that would be simpler anyway, or 'inspect or edit these bits' could be given a single name ("manage" best I can think of) and wrapped in a function.
Anyway, does the job for the two perms given, plus allows pin moving, as that seemed related enough to either?

Add manage screen for editing priority/category.

---

perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
templates/web/base/report/inspect.html

This adds an update field to the bottom of the inspect form, allowing the
inspector to provide an update to be added to the report as it's sent.
See mysociety/fixmystreetforcouncils#64

Require inspector to provide update when instructing report

---

perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/my_planned.t
templates/web/base/my/planned.html
templates/web/base/questionnaire/index.html
templates/web/base/report/_main.html
templates/web/fixmystreet.com/report/new/extra_name.html
templates/web/oxfordshire/header.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss

Fixes #89.
Adds a new segmented control, containing the admin actions the current user is permitted to perform (currently any number of the 3 actions: moderation, inspection, and shortlisting).
Tested in IE8-10, and modern browsers. And screenreaders.

Organize report admin actions into single control

---

perllib/FixMyStreet/App/View/Email.pm
perllib/FixMyStreet/App/View/Web.pm
perllib/FixMyStreet/Email.pm
perllib/FixMyStreet/Template.pm

Reduce some duplicated code, and as a side effect gives HTML emails our
internal html_para filter, allowing single line returns in contact form
submissions.

Use shared Template base for all templates.

---

perllib/FixMyStreet/App/Controller/Admin/ResponsePriorities.pm
templates/web/base/admin/navigation.html
templates/web/base/admin/responsepriorities/index.html
templates/web/base/admin/responsepriorities/list.html
templates/web/base/admin/templates.html
templates/web/base/admin/templates_index.html

- Superusers couldn't view response priorities due to invalid `$c->forward` call
- Navigation to other areas of admin was broken on response priority admin pages
Decided to do this as a PR instead of straight on to master as I wasn't sure that my `uri_for` fix was the best way to do it.

Some minor admin fixes

---

bin/update-schema
db/downgrade_0046---0045.sql
db/schema.sql
db/schema_0046-user-add-extra.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/controller/report_inspect.t
t/app/sendreport/inspection_required.t
templates/web/base/admin/category_edit.html
templates/web/base/admin/user-form.html
templates/web/base/report/display_tools.html
web/js/fixmystreet-admin.js

This PR adds the ability for users to gain reputation if they make high-quality reports, and lose it if their reports are duplicates/otherwise rejected or removed from the site.
The purpose of reputation is to allow reports to be sent immediately without any need for inspection/instruction for those categories that require inspection. It operates in a similar way to the 'trusted' flag.
- User's reputation is stored in the newly-added `extra` column.
- Categories requiring inspection can have a reputation threshold set, below which reports must still be inspected before being sent.
- When a report is inspected and sent on to be fixed the user gains a reputation point.
- ~~When a report is rejected (e.g. has its state set to hidden/duplicate/not responsible) at the inspection stage the …

Add user reputation for automatic report sending

---

templates/web/fixmystreet.com/about/privacy.html

Update the privacy policy for fixmystreet.com to allow us to switch on demographic tracking in Google Analytics. This is a direct lift of the [policy from TheyWorkForYou](https://www.theyworkforyou.com/privacy/), which we're already confident allows this sort of thing. As part of this it removes the table of Google cookies, adds a bit on opt-out tools, and retains the Google statement.

[fixmystreet.com] Update privacy policy to allow Google Analytics demographics

---

templates/web/oxfordshire/footer.html

Addresses the bug raised in https://github.com/mysociety/fixmystreetforcouncils/issues/36#issuecomment-251901875
Shortlist link now appears in the footer menu on mobiles:

[Oxfordshire] Link to Shortlist in mobile footer nav menu

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Map.pm
perllib/FixMyStreet/TestAppProve.pm
t/app/controller/reports.t
templates/web/base/common_footer_tags.html
templates/web/base/reports/_list-filters.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/cobrands/sass/_multiselect.scss
web/cobrands/sass/_report_list.scss
web/js/jquery.multi-select.js
web/js/map-OpenLayers.js

To fix https://github.com/mysociety/fixmystreetforcouncils/issues/95
- https://github.com/mysociety/jquery-multi-select/pull/5
~~We should probably re-think the logic of the options here – for instance, should “all reports” be a fourth option in the status select box, or should the box just default to having its three options (“unfixed reports”, “closed reports”, “fixed reports”) ticked?~~

Allow multiple selections in report-list-filter UI

---

bin/update-schema
db/downgrade_0047---0046.sql
db/schema.sql
db/schema_0047-response-priorities-add-description.sql
perllib/FixMyStreet/App/Controller/Admin/ResponsePriorities.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/ResponsePriority.pm
t/app/controller/admin.t
templates/web/base/admin/category-checkboxes.html
templates/web/base/admin/responsepriorities/edit.html
templates/web/base/admin/responsepriorities/list.html
templates/web/base/admin/template_edit.html
web/js/fixmystreet-admin.js

- Adds an internal 'description' field to response priorities in the admin
- Description is shown on the response priorities list table
- Adds 'select all/select none' UI atop categories checklist (also for response templates)
- Matches behaviour introduced in #1555 - empty category list means priority applies to all categories
For mysociety/fixmystreetforcouncils#66.

Add ‘description’ field to response priorities

---

perllib/FixMyStreet/DB/Result/Problem.pm
t/app/model/problem.t

Instead of returning all templates for the problem's body, return those
for the problem's category (or with no category).
Fixes mysociety/fixmystreetforcouncils#100

Fix list of response templates for a problem.

---

perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
templates/web/base/report/_main.html
templates/web/base/report/inspect.html

This saves an inspector having to click a button to see the form.

Have report page show inspect form by default

---

perllib/FixMyStreet/App/Controller/FakeMapit.pm
web/js/map-OpenLayers.js

This makes it easier to use the map, as the land outside the area is shaded, rather than the area itself.
It also makes zoom-to-extent/area_format work for bodies with multiple areas.

Invert display of areas on body pages.

---

templates/web/base/reports/_list-filters.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_multiselect.scss
web/js/jquery.multi-select.js

Adds the features from https://github.com/mysociety/jquery-multi-select/pull/7 to FixMyStreet.
Fixes mysociety/fixmystreetforcouncils#115, and gives us a nice user-friendly "presets" interface we could add into #1563 too.
Looks like this in the Oxfordshire cobrand:

Add simple way to return to "everything" in list filters

---

README.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/admin.t
t/app/controller/report_inspect.t

Changing the category of a report (via the inspect/manage page or via the admin) might also mean the responsible body for that report has changed.
This PR adds functionality causing the report to be sent again if the body changes.
For mysociety/fixmystreetforcouncils#44.

Resend report if changing category also changes body

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/index.t
templates/web/base/admin/user-form.html
templates/web/base/around/postcode_form.html
templates/web/base/footer.html
templates/web/oxfordshire/footer.html
templates/web/oxfordshire/header.html
web/js/fixmystreet-admin.js

- Users can be assigned to one or more of their parent body's categories
- The 'all reports' link is prefiltered with the user's categories, if they have any, on the Oxfordshire cobrand
Left to do:
For mysociety/fixmystreetforcouncils#69

Assign users to categories

---

README.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/View/Web.pm
templates/web/base/report/update.html

And add ability for admin users to italic updates, to be used by this.
Fixes #1544.

Leave a public update when admin changes category.

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_display.t
t/app/controller/report_inspect.t
t/app/controller/report_updates.t
t/app/model/problem.t
templates/web/base/report/_inspect.html
templates/web/base/report/_item.html
templates/web/base/report/display.html
templates/web/base/report/duplicate-no-updates.html
templates/web/base/report/updates.html
templates/web/bromley/report/display.html
templates/web/bromley/report/update-form.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_report_list_pins.scss
web/js/map-OpenLayers.js
web/js/map-google.js

This PR adds functionality for inspectors to be able to mark a report as a duplicate as another and prevents users leaving updates on reports marked as duplicates.
For mysociety/fixmystreetforcouncils#18

WIP: UI for handling duplicate reports

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/DB/ResultSet/ResponsePriority.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/fixmystreet.js

Different categories may have a different list of priorities, so store them all and update as the category changes.

Update priorities in inspect form on category change.

---

perllib/FixMyStreet/DB/Result/User.pm
templates/web/base/admin/report_blocks.html
templates/web/base/report/_item.html
web/cobrands/fixmystreet.com/base.scss
web/cobrands/oxfordshire/base.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_mixins.scss

Fixes mysociety/fixmystreetforcouncils#21.
Todo:
Currently looks like:

WIP: Improved print view for lists of reports

---

db/schema.sql
db/schema_0048-response-templates-add-state.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/ResponseTemplate.pm
templates/web/base/admin/report_edit.html
templates/web/base/admin/response_templates_select.html
templates/web/base/admin/state_groups_select.html
templates/web/base/admin/template_edit.html
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/fixmystreet.js

This allows response templates to be associated with a problem state in the admin, and changing a report's state when inspecting/managing a report will automatically prefill the update field with the appropriate response template for the new state, if one exists.
For mysociety/fixmystreetforcouncils#75

Add 'state' to response templates

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Response.pm

This is to work around
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8572187/
The horror of this bug is at least matched by the elegance of the workaround :)

In Edge 14, do all HTTP redirects in HTML instead.

---

perllib/FixMyStreet/App/Controller/Auth.pm

This should prevent an issue where e.g. a phone autocorrects oxfordshire.gov.uk to Oxfordshire.
It looks like there are 19 accounts that may need merging.

Lowercase email when signing in.

---

templates/web/base/admin/response_templates_select.html
web/cobrands/zurich/js.js

Using a `div` inside a `p` isn't valid, so the DOM was being restructured by the
browser causing the 'save with public update' toggle on the inspect form to not
work.
Fixes mysociety/fixmystreetforcouncils#153

Use span instead of div to wrap response template

---

perllib/FixMyStreet/App/Controller/Reports.pm
t/app/controller/reports.t
templates/web/base/reports/_list-filters.html

For mysociety/fixmystreetforcouncils#112
This allows inspectors to access any report listing page (such as /reports, or when #1613 is merged, /my/areas) and filter by if a problem is shortlisted or not.
The only issue I can see so far is that users will be able to click 'shortlisted' and 'unshortlisted', which may give an unexpected result (at the moment, it will default to shortlisted), but as people can click on 'unfixed' and 'fixed' at the moment too, that might be something to file for further improvements.

Filter by shortlisted problems

---

bin/oxfordshire/archive-old-enquiries
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm
perllib/Utils.pm
t/app/model/problem.t
t/app/script/archive_old_enquiries.t
t/utils.t
templates/email/oxfordshire/archive.html
templates/email/oxfordshire/archive.txt
templates/web/base/report/update/form_update.html

For mysociety/fixmystreetforcouncils#51
This will mark all reports with the last update in 2015 as closed, and email the users with information on what problems have been closed, and the option to reopen them. Anything still open with a last update of 2014 or earlier gets closed with no email.
This could do with a code review, but would also be good to test against a corpus of real data before pointing it at live.

Close 'old' enquiries

---

bin/update-schema
db/schema.sql
db/schema_0049-response-priorities-add-external_id.sql
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/ExorDefects.pm
perllib/FixMyStreet/App/Controller/Admin/ResponsePriorities.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Base.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/ResponsePriority.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport/Email.pm
t/app/controller/report_inspect.t
t/cobrand/oxfordshire.t
templates/web/base/admin/exordefects/index.html
templates/web/base/admin/responsepriorities/edit.html
templates/web/base/admin/user-form.html
templates/web/base/report/_inspect.html
templates/web/oxfordshire/admin/user-form-extra-fields.html
web/cobrands/fixmystreet/offline.js
web/js/fixmystreet-admin.js

This PR adds a new 'Download Exor RDI' link to the admin on the Oxfordshire cobrand.
The purpose of this feature is to quickly import inspected problems into Exor as defects, using an obscure CSV format.
See mysociety/fixmystreetforcouncils#127 for a detailed discussion of this feature.
To support this feature, some other changes have been made to the inspection workflow:
- When a report is inspected a new `inspected` AdminLog entry is created.
- A report is marked as inspected if somebody with the `report_inspect` permission changes its state.
- In the Oxfordshire cobrand, the admin user edit form includes an 'initials' field, which is required for Exor to link the inspection records to the appropriate users internally.

[Oxfordshire] Exor RDI inspection file download

---

bin/oxfordshire/open311_service_request_update.cgi
bin/oxfordshire/open311_services.pm

The timestamps returned from the database are in server-local time, not UTC.
Because FMS expects timestamps in Open311 responses to be UTC, the timestamps
of updates from OCC appear one hour ahead when DST is in effect.
This commit converts the timestamps to UTC before outputting them.
Fixes mysociety/FixMyStreet-Commercial#499

[Oxfordshire] Open311 update timestamps should be in UTC

---

perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/App/View/Web.pm

Two small things that do a lot of statting.
1. The versioning code wasn't remembering when it had found that a file did not exist, so was checking for them each time.
2. The list code was checking the photo ID given in the database existed on disk – this shouldn't ever not be the case, and if it was, all that would happen would be a broken image when the full photo code looks for it (this is only for e.g. lists of reports).

Reduce disc stats

---

templates/email/default/submit-example.txt
templates/email/fixmystreet.com/_submit_footer.html
templates/email/fixmystreet.com/submit.txt
templates/web/base/open311/index.html
templates/web/bromley/front/footer-marketing.html
templates/web/fixmystreet.com/about/council.html
templates/web/fixmystreet.com/footer_extra.html
templates/web/fixmystreet.com/front/footer-marketing.html
templates/web/fixmystreet.com/reports/_extras.html
templates/web/greenwich/front/footer-marketing.html
templates/web/hart/footer.html
templates/web/oxfordshire/footer.html
templates/web/stevenage/footer.html
web/cobrands/fixmystreet.com/fmsforcouncils.scss

* Tweak wording to make it clearer that the form is unsuitable for residents wanting to report street problems.
* Record HTTP Referer when form is submitted, so we can see which pages are leading people to the FMS4C page.
* Tidy up capitalisation elsewhere in headings on the page.
* Replace links to `/council` with `/about/council` to avoid an unnecessary redirect (thanks @davea!) and remove the `www.fixmystreet.com` prefix inside the fixmystreet.com cobrand templates.
Fixes #1553.

Clarify purpose of FMS4C contact form

---

bin/open311-populate-service-list
perllib/FixMyStreet/Cobrand.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/Cobrand/WestBerkshire.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/SendReport/Open311.pm
t/app/sendreport/open311.t

Avoid doing cobrand-specific logic within SendReport::Open311.
Instead:
```
- inflate a cobrand from the row's cobrand
(complex cases such as UK may then defer to other cobrands
depending on bodies_str)
- add a 'call_cobrand_hook' method to Cobrand::Base which
calls a cobrand method *if* it is defined.
- the hooks defined are:
open311_config:   set extra fields and $revert
open311_pre_send: set endpoints and munge data
open311_zero_result_on_fail: temporary behaviour required for
West Berks
- create two dummy cobrands (West Berks and Cambridgeshire)
to be able to dispatch these hooks to consistently.
```
These are tested in the new t/app/sendreport/open311.t, which does
not send any actual reports, but just checks that all the data is
munged into the expected format.  (tests under …

Refactor SendReport::Open311 to cobrand hooks

---

web/cobrands/fixmystreet/fixmystreet.js

IE11 caches this Ajax call, not calling out to the server at all if it
is made again (e.g. after an update has been made). Fixes #1638.

Make sure report Ajax call is not cached by IE11.

---

templates/web/base/reports/_list-filters.html
web/cobrands/fixmystreet/fixmystreet.js

A cobrand may have a blank default that isn't everything, so the
"All reports" option must specify all the possible options.

Specify options in 'all' status filter.

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Model/PhotoSet.pm

If we're chugging through a list of reports, this save on a lot of
pointless statting of the upload directory which we know is there.

Do upload_dir check on start up, not each report.

---

bin/update-schema
db/schema.sql
db/schema_0050-add-defect-type-table.sql
perllib/FixMyStreet/App/Controller/Admin/DefectTypes.pm
perllib/FixMyStreet/App/Controller/Admin/ExorDefects.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/DB/Result/ContactDefectType.pm
perllib/FixMyStreet/DB/Result/DefectType.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/ResultSet/DefectType.pm
perllib/FixMyStreet/TestMech.pm
t/app/model/defecttype.t
templates/web/base/admin/category-multiselect.html
templates/web/base/admin/defecttypes/edit.html
templates/web/base/admin/defecttypes/index.html
templates/web/base/admin/defecttypes/list.html
templates/web/base/defect_type/format.html
templates/web/base/report/_inspect.html
templates/web/oxfordshire/admin/defecttypes/extra_fields.html
templates/web/oxfordshire/defect_type/format.html
web/cobrands/fixmystreet/admin.js
web/cobrands/fixmystreet/fixmystreet.js

For https://github.com/mysociety/fixmystreetforcouncils/issues/160

Customisable defect types

---

cpanfile
cpanfile.snapshot
t/Mock/Facebook.pm

0.09 was communicating with v2.2 of the Facebook API which was switched off
on 25th March 2017, so Facebook logins were no longer working.
Mock::Facebook was updated to correctly return JSON from /oauth/access_token,
to match the behaviour expected since v2.3 of the FB API.
Fixes #1681

Upgrade Net::Facebook::Oauth2 to 0.10

---

perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin.t

The report-sending code has allowed multiple emails for a long time, but the
admin wouldn't allow you to enter multiple emails for each contact.
Fixes mysociety/FixMyStreet-Commercial#835

Allow comma-separated contact emails in the admin

---

perllib/FixMyStreet/Cobrand/Default.pm

The check assumed that if a body was devolved, either the contact
or the body would have a send method. Instead, use a contact send
method if devolved and it exists, a body send method if it exists
or the fallback if neither. Fixes #1374.

Don't error when devolved body, blank send methods

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t
templates/web/base/report/new/category.html
templates/web/base/report/new/category_wrapper.html
templates/web/base/report/new/form_user_loggedin.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js

For mysociety/fixmystreetforcouncils#150
This makes it somewhat easier for inspectors who might be reporting a new problem to open a new report and add the inspection details by autocompleting a bunch of stuff for them, and redirecting to the inspection page once the report has been made. The flow now looks like this:
And like this on mobile:
It doesn't quite address everything in mysociety/fixmystreetforcouncils#150, but goes a long way to reducing the friction.

Simplify open and inspect procedure for inspectors

---

templates/web/base/report/_inspect.html
templates/web/base/report/duplicate-no-updates.html
templates/web/base/report/update-form.html
templates/web/bromley/report/update-form.html
web/cobrands/fixmystreet/staff.js
web/cobrands/oxfordshire/base.scss
web/cobrands/oxfordshire/layout.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

Attempt at fixing mysociety/fixmystreetforcouncils#157.
* Inspect form now has background color on narrow devices
* Inspect form has heading on narrow devices
* When an inspect form is present, the "Provide an update" form is hidden behind a button press
Also includes a quick fix to the `#key-tools` styling, while I was in the vicinity.

Better differentiation for Inspector form on report page

---

web/cobrands/oxfordshire/layout.scss
web/cobrands/sass/_layout.scss

Fixes mysociety/fixmystreetforcouncils#190.
The green "inspector" column is narrower now for _all_ users. And for screens smaller than 1280px, the _main_ column also gets narrower, to make sure the map is still usable.

Larger map for inspectors using 1024px displays

---

perllib/FixMyStreet/Cobrand/UK.pm
t/Mock/Bing.pm
t/Mock/MapIt.pm
t/cobrand/closest.t

If the longitude was very close to 0, it was being sent as e.g. 1e-6
in the request to MapIt. Mock out the Bing query so that this can be
tested (the closest.t tests were previously always being skipped).
Fixes #1695

[UK] Stop nearest request with scientific notation

---

web/js/map-OpenLayers.js
web/js/map-wmts-bristol.js
web/js/map-wmts-zurich.js

The Git JS linting hook didn't used to run on files with `OpenLayers` in the filename, but we've changed this now vendor scripts are in their own subdirectory (#1705). This means that our own map-OpenLayers.js file wasn't being linted before, but now it is. This PR just fixes the issues that the linter's picked up.

Fix linting errors

---

perllib/FixMyStreet/App/Controller/Report/Update.pm
templates/web/base/report/inspect/state_groups_select.html
templates/web/bromley/report/update-form.html

The Bromley update form needed to be updated to use the new <select> template.
This also fixes a situation where staff users (on all cobrands) wouldn't be able
to leave updates on problems with state 'fixed - user'.

[Bromley] Restore staff update function

---

web/cobrands/borsetshire/_council-header.scss
web/cobrands/borsetshire/base.scss

Borsetshire `#site-header` is a bit funky because it has an extra "fake" menu on desktop on all pages except `.mappage`.
Adding padding to `#site-header .container` is a much simpler way to vertically centre the logo and the fake menu on desktop, and the logo and mobile header controls on narrow screens, without _also_ messing up the `.mappage` header height calculations.
I also took the opportunity to replace a few magic numbers in the borsetshire `layout.scss` with numbers calculated from `$mappage-header-height`.

[Borsetshire] Fix incorrect map page header height

---

perllib/FixMyStreet/App/Controller/Admin.pm

Instead of checking if the list of bodies has changed at all, mark the
report for resending if there is a body in the new list not present in
the old.

Don't resend if category change subsets body.

---

glossary.md

Spotted a rude `</dl>` showing up at the end of [the glossary](http://fixmystreet.org/glossary/) (and there was a `</p>` higher up too, which turned out to be the real culprit) — I believe* this fixes it.
* Locally, Jekyll rendered the offending page cleanly, so I didn't manage to reproduce the error locally before modifying the markdown.

fix imbalanced paragraph tags in glossary

---

.travis.yml
script/bootstrap
script/console
script/server
script/setup
script/test
script/update

This adds the following scripts that do the following:
`bootstrap`: updates submodules, installs Perl modules.
`console`: Turns on virtualenv (this needs to be run as `. script/console`)
`server`: Starts app server.
`setup`: Runs `update`.
`test`: Runs test suite.
`update`: Runs `bootstrap`, updates DB schema, compiles CSS, compiles `.mo` files.

Add scripts to rule them all.

---

templates/web/base/reports/body.html
web/cobrands/sass/_base.scss

Float all labels left to fix 189 - this currently breaks e.g. Show X about Y. Is there a way to fix it without having to check all the labels.
Use a `<br>` to fix 188, but does this make the gap too big, is there a nicer way?

WIP fix blank spaces being clickable.

---

perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
templates/web/oxfordshire/report/inspect/state_groups_select.html
web/cobrands/fixmystreet/staff.js
web/cobrands/sass/_base.scss

Revert the behaviour from 36baff2d, so that everyone can use the 'action scheduled' state, and instead if someone with report_instruct permission has the state set to 'action scheduled', add an extra mandatory question asking whether they want to raise a defect or not.

[Oxfordshire] Separate defect creation from state.

---

cpanfile
cpanfile.snapshot
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Root.pm
t/app/controller/about.t
t/app/controller/report_display.t
t/app/controller/templates/about/homepage.html
templates/web/base/main_nav_items.html

If you have a templates/web/COBRAND/about/homepage.html file, then that page will be used as the front page of your site, and the normal front page will instead be available at `/report`. Fixes #1745

Allow static home page template override.

---

templates/web/base/report/_inspect.html

If the reporter of a problem left their phone number, it will be shown
at the top of the inspector form as a 'tel:' link
Fixes mysociety/fixmystreetforcouncils#200

Show reporter's phone number on inspector form

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/report_inspect.t

If a report’s category is changed to one with a different send_method to the original category, the report needs to be resent.
Fixes mysociety/fixmystreetforcouncils#209

Resend report if changing to category with different send_method

---

perllib/FixMyStreet/App/Controller/Moderate.pm
t/app/controller/moderate.t

Replacing deleted text with [...] when moderating reports and comments
leads to very odd looking reports when correcting minor typos so just
leave the text as deleted.
Fixes #1774

do not replace deleted text with [...] when moderating

---

perllib/FixMyStreet/App/Controller/Contact.pm
t/app/controller/contact.t
templates/web/fixmystreet.com/about/council.html
web/cobrands/fixmystreet.com/fmsforcouncils.scss
web/cobrands/fixmystreet.com/js.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/857
* Form is shown by default.
* If JavaScript is available, form is hidden behind another button, to save space.
* Submitting the form sends contact details to the enquiries email address, and automatically forwards the user on to the Demo site.

Form on FMS Pro page for requesting access to demo

---

customising/boundaries.md
customising/config.md
customising/language/index.md
glossary.md
updating/ami.md
updating/index.md

Adds expanded documentation for using http://$lang.fixmystreet.com/ style URLs as well as basic details of adding a language switcher.
Also documents `base_url_with_lang` for adding language specific URLs to emails.
Fixes #1571.
Fixes #1619.

[DOCS] Expanded documentation for multi language support.

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

As we only get `open`/`closed` back from Oxfordshire, don't switch back to 'open' if we receive an open and we're already in an open state.

[Oxfordshire] Open311 update, no open state switch

---

sites.md

Simple change. ZeroTB and Bellavista En Ación moved down to the bottom of the page, under an "Honourable mentions" heading. Broken links removed.

Move dead sites into their own section

---

templates/email/default/_email_sidebar.html
templates/email/default/problem-confirm-not-sending.html
templates/email/default/problem-confirm.html
templates/email/default/questionnaire.html
templates/email/fixamingata/problem-confirm-not-sending.html
templates/email/fixamingata/problem-confirm.html
templates/email/fixamingata/questionnaire.html

Emails that contain a report’s title, description, and location in the ”sidebar” will now have a map that takes you to the report’s web page when clicked.
Fixes #1596. Thanks to @MyfanwyNixon for the suggestion!

Make map image in HTML emails clickable

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js

A variety of issues caused mostly when a report is pulled in via JavaScript (still?!):
* Action scheduled behaviour not correct. Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/195
* Errors in console from JS validator
* Update form toggle broken
* Map size incorrect (so e.g. panTo centring not centre).

Variety of brokenness to quickly fix

---

CHANGELOG.md
templates/web/base/pagination.html

Even if no next/previous page, the number of items can be useful.
Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/202

Always show pagination figures.

---

locale/nb_NO.UTF-8/LC_MESSAGES/FixMyStreet.po
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Location.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/ResultSet/Body.pm
perllib/FixMyStreet/Roles/Translatable.pm
t/roles/translatable.t

This should remember a translation looked up for the remainder of the request, plus add a way to look up all translations when fetching all bodies at once.

Improve new translation lookup performance

---

templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/staff.js
web/cobrands/sass/_base.scss

The chosen "original" report is now much more visually distinct from the other options, with a white background and a thick border in the site’s primary colour. Here’s how it looks in the Oxfordshire cobrand:
Looks the same on mobile too.
Fixes mysociety/fixmystreetforcouncils#211

Clearer styling for chosen report, when closing report as duplicate

---

CHANGELOG.md
bin/one-off-update-duplicates
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_inspect.t
t/app/model/problem.t

This avoids the need to search the whole table to find a report's
duplicates. And is easier than constructing an index or upgrading
PostgreSQL.

Store duplicate reverse lookups upon dupe setting.

---

CHANGELOG.md
bin/make_css
bin/update-schema
db/downgrade_0053---0052.sql
db/schema.sql
db/schema_0053-add-report-extra-fields-table.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/ReportExtraFields.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/Result/ReportExtraFields.pm
perllib/FixMyStreet/DB/ResultSet/ReportExtraFields.pm
t/app/controller/admin_reportextrafields.t
templates/web/base/admin/category_edit.html
templates/web/base/admin/contact-form.html
templates/web/base/admin/extra-metadata-form.html
templates/web/base/admin/reportextrafields/edit.html
templates/web/base/admin/reportextrafields/index.html
templates/web/base/report/_inspect.html
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/category_extras_fields.html
templates/web/base/report/new/category_wrapper.html
web/cobrands/fixmystreet/admin.js
web/cobrands/sass/_admin.scss
web/cobrands/sass/_base.scss

This PR adds a new feature that allows management via the admin of extra fields on the new report form. These fields can be managed on a per-category basis (i.e. the same as Open311 metadata fields), or site-wide (with restrictions via cobrand/language).
New site-wide fields can be added:
Which then appear on the report form:
Multiple sets of fields can be active, and limited to cobrand/language:
Metadata can be managed per-category, too:
Fixes #1743

Site-wide extra fields on report form

---

templates/web/fixmystreet.com/about/faq-en-gb.html
templates/web/fixmystreet.com/contact/who.html
templates/web/fixmystreet.com/footer_extra.html
templates/web/fixmystreet.com/next_steps.html
templates/web/fixmystreet.com/questionnaire/completed-open.html
templates/web/fixmystreet.com/static/unresponsive.html

@dracos correctly noted that some unencoded ampersands slipped into #1810 because I just copied the `utm` link template from the footer donation link, which didn’t have encoded ampersands either.
So, this fixes all of the unencoded ampersands in `href` attributes everywhere in the `.html` templates (which turns out to only be in the `fixmystreet.com` cobrand).

[fixmystreet.com] Encode ampersands in link hrefs

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/app/controller/report_inspect.t
t/app/controller/report_updates.t

Create a comment entry for all updates to reports regardless of whether
there is any text part. Also adds an entry to extra if a defect was
raised and includes that in the update.

show all report updates, even if no public text

---

.travis.yml

Older perl versions can leak the locale decimal point character, leading to invalid JSON being written by Devel::Cover.
The changes to coverage can be seen at: https://codecov.io/gh/mysociety/fixmystreet/compare/6e22df6dd8fbf1504bcedd6a3e77201cf438525d...f0f863865a270d9a508e8c3c273a31764555e60f/changes
The main desired change due to this is the questionnaire controller (which finished with a Norway test), which rises 50% in coverage to 87%.

[Travis] Run code coverage on 5.24.

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

Dropzone version 5 changed how createThumbnailFromUrl was called,
so the upgrade in 30dd9d8 broke this.

Fix redisplay of uploaded photo thumbnails.

---

perllib/FixMyStreet/Script/Alerts.pm
t/app/controller/alert_new.t

If a staff user changed a problem’s state and an empty update was generated,
it was possible for alert emails to be sent with missing URLs because the
empty string in the update text was falsy and Alert.pm took the wrong path.
This fixes the problem by changing the test to defined() and includes a
regression test.

Fix missing URLs in alert emails

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Model/DB.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/DB/Schema.pm
t/app/sendreport/inspection_required.t

Spotted on the Ground Control cobrand, where the inspector form only shows the category field and not the state field.
(NB: it looks like this functionality is [tested in `report_inspect.t`](https://github.com/mysociety/fixmystreet/blob/0c4b5041d807899ab708db4c5dd15203d23df257/t/app/controller/report_inspect.t#L231) so I'm not sure why this wasn't noticed sooner, unless I'm reading the test wrong.)

Fix a crash if changing report category without state field present

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/dashboard.t

This adds a Ward, Easting and Northing columns to the CSV export from the council dashboard.
Fixes mysociety/fixmystreetforcouncils#220.
Fixes mysociety/fixmystreetforcouncils#221.

Extra fields for Council dashboard CSV export

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/UK.pm
t/app/controller/alert.t
templates/web/base/alert/_list.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

Fixes mysociety/fixmystreet-commercial#866.
Alert options on the /alert/list page are now in an order that is easier to parse, with a slightly clearer message for users in two-tier locations, and a more prominent email subscription CTA.
Minimal changes to styling. No changes to the form behaviour.
@jukesie, do you want some Google Analytics event tracking so we know how many people actually sign up for email alerts?

Simpler alerts signup page

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Dashboard.pm
t/app/controller/dashboard.t

And update the tests to avoid a random failure caused by inconsistent
ordering.

sort body dashboard CSV export by report confirmed time

---

CHANGELOG.md
t/Mock/MapIt.pm
t/cobrand/oxfordshire.t
templates/email/default/problem-confirm.html
templates/email/default/problem-confirm.txt
templates/email/oxfordshire/_problem-confirm_extra.html
templates/email/oxfordshire/_problem-confirm_extra.txt
templates/web/base/email_sent.html
templates/web/oxfordshire/_email_sent_extra.html
templates/web/oxfordshire/_response_time.html
templates/web/oxfordshire/report/_council_sent_info.html
templates/web/oxfordshire/tokens/_extras_confirm.html

This adds some extra templates to enable adding cobrand messages to
* Confirmation email sent page.
* The confirm problem email.
* Problem confirmed page.
It also display the expected response time message in those locations for the Oxfordshire cobrand.
Fixes mysociety/fixmystreetforcouncils#219

Enable including extra text at all problem confirmation stages

---

bin/oxfordshire/send-rdi-emails
perllib/FixMyStreet/App/Controller/Admin/ExorDefects.pm
perllib/FixMyStreet/Integrations/ExorRDI.pm
t/cobrand/oxfordshire.t
templates/web/base/report/_inspect.html
templates/web/oxfordshire/report/_inspect_extra_info.html

The timestamp of when a problem was included in an RDI is shown on the problem’s
report_edit page in the Oxfordshire cobrand admin.
If a report hasn't been inspected yet:
If it's been inspected and instructed but not yet sent:
And once it's been sent in an RDI:
Fixes mysociety/fixmystreetforcouncils#223.

[Oxfordshire] Log when problems are sent in RDI

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/DefectTypes.pm
perllib/FixMyStreet/App/Controller/Admin/ExorDefects.pm
perllib/FixMyStreet/App/Controller/Admin/ReportExtraFields.pm
perllib/FixMyStreet/App/Controller/Admin/ResponsePriorities.pm
perllib/FixMyStreet/App/Controller/Admin/States.pm
perllib/FixMyStreet/App/Controller/My.pm
t/cobrand/zurich.t

Simplify chaining of body/category admin URLs so that all categories are treated the same, with `/` or without, and the template will then always have its CSRF token. Fixes #1836
(Also fixes awkward bug I stumbled across when the first page after restart is admin as it was when testing above fix.)
[skip changelog] - main bug introduced by body/category translation, stumbled bug introduced by superuser fix (nothing on user model used schema before).

Fix issue editing category with '/' in it.

---

CHANGELOG.md
templates/web/base/report/new/form_user_loggedin.html

They're logged in, it's only showing them as a confirmatory check, so it
should not be editable. I'm afraid I don't understand my commit that did
this last year, so there may be some edge case I've now forgotten :-/

Disable email field for logged in people using JS.

---

perllib/FixMyStreet/DB/ResultSet/State.pm

This can fail if the tests are being run in parallel.

Revert using memcached cache in testing.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/AreaStats.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/TestMech.pm
t/Mock/MapIt.pm
t/app/controller/area_stats.t
templates/web/base/admin/areastats/area.html
templates/web/base/admin/areastats/index.html

Admin page to show some simple summary stats for an area.
If the user has been assigned to an area then they will see the stats
for that area. Superusers can pick which are they want to view.
For mysociety/fixmystreetforcouncils#2

basic area stats pages

---

CHANGELOG.md
templates/web/base/main_nav.html
templates/web/base/main_nav_items.html

Because we move to report pages using ajax and pushstate rather than links the shortlist menu item remains inactive because the page doesn't reload. Fix this by making the Shortlist menu item a link all the time.
Fixes mysociety/fixmystreetforcouncils#233

make sure shortlist menu item is link on report pages

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/staff.js
web/cobrands/sass/_base.scss

Add an optional maximum length, configured in the cobrand, for the detailed information field in the inspector panel.
Fixes mysociety/fixmystreetforcouncils#228

Maximum length for inspector detailed information 

---

perllib/FixMyStreet/DB/Result/Problem.pm

For temp URLs there was not already a query string, and
so "?" needs to be used rather than "&" when appending.

Fix bug in cookie passthrough query parameter.

---

CHANGELOG.md
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html

If we've stored the nearest address then display that at the top of the
inspector panel.
Fixes mysociety/fixmystreetforcouncils#230

show nearest address for report in inspector panel

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Rss.pm
perllib/FixMyStreet/SendReport/EastHants.pm
t/app/controller/rss.t

By default encode_entities uses named entities, which don't exist
by default in XML. It seemed nicer to switch to only escaping the
minimum rather than switching to numeric entities.
Fixes #1859

In RSS, only escape the necessary five/ctrl chars.

---

perllib/FixMyStreet/App/Controller/Admin/AreaStats.pm
t/app/controller/area_stats.t
templates/web/base/admin/areastats/area.html

Doing this calculation in code turns out to be much too slow.
As part of this also fix an issue where if a report changed state last
month but had a further comment this month that was counted as being
a state change this month.
Also tweak the 'last month' start date to be midnight so the stats don't
change throughout the day.

move area stats page problems by status calc into database

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html

This changes the admin code that updates problem categories to do two things:
* Only update the problem category if the updates are valid
* Only create a single comment for the changes rather than one for the category change and another for other changes.
For #1857

Fix category updating issues with inspect form

---

CHANGELOG.md
perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/DB/ResultSet/State.pm
perllib/FixMyStreet/Script/Alerts.pm
t/app/controller/alert_new.t

This both ignores blank updates for email alerts and also includes useful text in the update if the status of the problem was changed.
For #1857

Avoid blank updates in alert emails

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Reports.pm
t/Mock/MapIt.pm
t/app/controller/reports.t
templates/web/base/reports/body.html

URLs have to be manually constructed, but specifying multiple ward names
separated by "|" will show all those wards and their reports on the map.
Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/231

Allow ward page to show multiple wards.

---

CHANGELOG.md
templates/web/base/maps/openlayers.html
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

A full modal made it hard to perform multiple zooms/pans, making
the site slower to use than necessary. Tell the user the site is
updating, but let them interact with the map at the same time.

Stop loading spinner covering map.

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

Any map bar the already-full-screen /around map could benefit from
the expand map option, especially the list of your reports.

Add expand map toggle to more mobile maps.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm

Do not try and redirect to a report that won't be viewable on the cobrand being used.

Redirect inspectors correctly on creation.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t

It was possible to mark a report as a duplicate in the inspector panel
without providing an id of the duplicate. This prevents that.
Fixes mysociety/fixmystreetforcouncils#236

make sure duplicate id provided when marking as duplicate

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Reports.pm
templates/web/base/reports/_list-filters.html
templates/web/base/reports/_status_filter_options.html
templates/web/oxfordshire/reports/_status_filter_options.html
web/cobrands/fixmystreet/fixmystreet.js

Partly to restore a more meaningful default message to the Oxfordshire cobrand for the default status of the report status filter, also to make the all option work better for body users.
https://github.com/mysociety/fixmystreetforcouncils/issues/227

improve report status filter default message

---

CHANGELOG.md
bin/update-all-reports
perllib/FixMyStreet/App/Controller/About.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/Script/UpdateAllReports.pm
t/app/controller/reports.t
t/cobrand/fixmystreet.t
templates/web/base/reports/index.html
templates/web/fixmystreet.com/about/council-dashboard.html
web/cobrands/fixmystreet.com/fmsforcouncils.scss

Firstly this updates `update-all-reports` to allow it to output the same data used for `/reports` restricted to a particular body, or output for each body. Then it updates the front end to display this data (with ward selection rather than body selection; whoops, guess it shouldn't show it if the area has no children). Then lastly, for .com it restricts those pages to logged in users whose domain matches a council one, and provides a customised login page at `/about/council-dashboard` which if an email is entered for a relevant body, acts like normal and sends confirmation email, or if not, sends us an email for manual checking (probably by adding the domain if possible and sending them a confirmation email? Perhaps list shouldn't be in version control.)
This final form could be …

Add per-body reports summary pages

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/My.pm
t/app/controller/my_planned.t
templates/web/base/report/_item.html

If a user is trying to remove a problem from their shortlist we should
always allow it regardless of the state of the problem. Previously if a
problem wasn't displayed on the site then it could not be removed from
the shortlist which was an issue with council cobrands and reports that
had changed body.
Fixes mysociety/fixmystreetforcouncils#243

always allow problems to be removed from shortlist

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Location.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Map.pm
t/app/controller/around.t
t/app/controller/report_new.t
t/app/controller/report_new_text.t
t/cobrand/oxfordshire.t
t/map/tilma/original.t
templates/web/base/around/display_location.html
templates/web/base/around/on_map_list_items.html
templates/web/base/around/tabbed_lists.html
templates/web/base/maps/google.html
templates/web/base/maps/openlayers.html
templates/web/base/pagination.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/map.js
web/cobrands/sass/_base.scss
web/js/map-OpenLayers.js
web/js/map-google.js

This factors this code to use the same code `/reports` and `/my` are using, and removes the show old pins code. For #525.
Also adds heading for #1577 (as those nearby ones are excluded from the pagination, which is a bit odd I grant you, but didn't seem odd enough to try and work something out).

Add pagination to around page

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t
templates/web/base/report/_item.html

This functionality isn't needed here, and causes an issue with the main form submitting due to a form inside a form.
Fixes https://github.com/mysociety/fixmystreetforcouncils/issues/248

Remove shortlist form from inspect duplicate list.

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
templates/web/base/report/new/category.html
templates/web/base/report/new/category_wrapper.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js

Add a `prefill_report_fields_for_inspectors` config to cobrands,
defaulted to 0, to control the automatic pre-population of report
fields.
Also add default of 1 for UKCouncil cobrand.
Fixed #1854

cobrand option to control prefilling of report fields for inspectors

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/cobrand/councils.t
templates/web/base/auth/general.html
templates/web/base/report/new/form_user_loggedout.html
templates/web/base/report/update/form_user_loggedout.html

We want to enable FB login on fixmystreet.com, but not the various UK council cobrands also active on that instance. This PR allows individual cobrands to opt-out of social login, and does so for our council cobrands.
For #1890.

[fixmystreet.com] Disable social login on council cobrands

---

CHANGELOG.md
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

Prevent long numbers on homepage from overflowing their container and looking messy. Fixes #1722.
Updating the size in three media queries is a bit fragile. But it’s much simpler than any other more "automatic" alternative I could think of (eg: flexbox). Looks good with the huge numbers on the UK site, and still looks ok on sites with fewer reports.
I also took the opportunity to simplify the overpowered `…#front_stats div big` selector down one notch, to `…#front_stats big`, while I was in the area.

Prevent homepage stats text overflow

---

perllib/FixMyStreet/Geocode.pm
perllib/FixMyStreet/Geocode/OSM.pm
t/Mock/Nominatim.pm
t/cobrand/fixamingata.t

It turns out that HTTP::Message (as used by LWP::Simple::get) only decodes text/* and 'XML', not application/json, as used by all the geocoders. Work around this, hopefully in a future-proof way.
Fixes #1905.
[skip changelog] (as was introduced as an aside recently)

Fix geocoder encoding issue

---

CHANGELOG.md
templates/web/base/report/display.html
templates/web/base/report/duplicate-no-updates.html
templates/web/base/report/update-form.html
templates/web/bromley/report/update-form.html
web/cobrands/fixmystreet/staff.js

This prevents the form scroll going to the wrong place when the
form was being hidden later on.
Fixes #1863

Hide update form for inspectors in HTML.

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

On mobile, if you e.g. selected one report and then another, you'd get
another "Expand map" appearing. Check that one is needed before adding
it, and also make sure the handler is only attached once to prevent it
conflicting with itself (and so cancelling itself out).

Prevent multiple 'Expand map' links appearing.

---

CHANGELOG.md
conf/general.yml-example
perllib/FixMyStreet/App/Controller/Offline.pm
web/cobrands/fixmystreet/fixmystreet.js

This checks that the user has a from_body *and* the planned_reports
permission when considering whether to default to 'yourself' or the
council in the 'report as' field.
Fixes #1913.

Fix UI bug stopping superusers making reports

---

CHANGELOG.md
web/js/geolocation.js

Modern browsers disable geolocation on non-HTTPS pages, but
sadly still report it as available with the `navigator.geolocation`
object. This commit adds a check for HTTPS and hides the link
if it won’t work.

Hide geolocation link if not on HTTPS

---

CHANGELOG.md
perllib/FixMyStreet/Map.pm
web/js/front.js

When viewing /around without the `js=1` parameter in a Spanish locale
the incorrect decimal separator was being passed to the DB query,
causing a crash.
Fixes mysociety/fixmystreet-commercial#942

Ensure calculated lat/lon are sent to DB in correct format

---

CHANGELOG.md
templates/web/base/around/_error_multiple.html
templates/web/base/around/postcode_form.html

The intro header takes up a lot of vertical screen space, which on small devices means that the suggestion links end up beneath the fold. This can make it seem as though nothing has happened at all when you enter a search term on the front page, e.g.:
iOS | Android
----|--------
This PR improves things by removing the intro header if there are location suggestions, and also shifts the second sentence of the help text to the bottom of the list where it's more likely to be read:
The same change applies to larger screens too:
I'm opening this PR for discussion. Is this change a good idea? Can the problem be solved better? What's the next steps?

Remove intro text when showing location disambiguations

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/cobrand/fixmystreet.t
templates/web/base/reports/index.html
web/cobrands/sass/_dashboard.scss

Display a list of the email addresses used to contact the council on the
council dashboard. Does not display emails if the council has an
integration, rejects FMS reports or is currently turned off.
Fixes mysociety/fixmystreet-commercial#941

display council contacts on council dashboard

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

The popstate event for a filter change assumed that the list was already
being displayed, but it was not if you were going back from a report.
The reports_list function to display the list page is idempotent (though
this commit makes it more so), so can happily be called whether the list
page is currently displayed or not.
Fixes #1920

Fix back bug, from report after using list filters

---

perllib/Open311/PopulateServiceList.pm

For EHDC we need to leave the 'Other' category alone or reports made in this category will be sent only to Hertfordshire County Council.

[East Herts] Preserve 'Other' category in PopulateServiceList

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/TestMech.pm
perllib/Open311/GetServiceRequestUpdates.pm
t/app/controller/admin.t
t/open311/getservicerequestupdates.t
templates/web/base/admin/template_edit.html
templates/web/base/admin/templates.html
templates/web/zurich/admin/templates.html

If an Open311 service request update with an empty description field is received and there is a matching ResponseTemplate for the problem's category & state (and it's marked as auto-response) then the text from that ResponseTemplate will be used for the created update.
This PR adds that functionality, as well as improving the admin UI for managing response templates and marking them as auto-responses.
Fixes mysociety/fixmystreetforcouncils#263

Use auto-response ResponseTemplates for text when fetching Open311 updates

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t
templates/web/base/report/new/category.html
web/cobrands/fixmystreet/fixmystreet.js

This PR adds support for the Open311 `group` field for services. Practically this means:
- The `group` field is populated on `Contact`s by `PopulateServiceList`
- New UI for categories/subcategories based on group when making reports
- Cobrand hook (`use_category_groups`) to enable UI 
For mysociety/fixmystreetforcouncils#40

Open311 category group support

---

t/Mock/Nominatim.pm

This was causing an error in "Test ajax decimal points" in fixamingata.t
due to "importance" being encoded with a comma decimal separator.

Ensure Mock::Nominatim JSON is encoded in en-gb locale

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport/Angus.pm
perllib/FixMyStreet/SendReport/Open311.pm
templates/web/fixmystreet.com/report/updates-sidebar-notes.html

This fixes an issue whereby if you changed a problem from a category that was send method A at the time the problem was made but is now send method B, to send method B, it wasn't being resent. It also stores all send methods used rather than just a couple, and adds a script to spot reports not sent via RDI.

Small send method fixes

---

perllib/FixMyStreet/Map/Bristol.pm
t/map/tests.t
templates/web/base/common_footer_tags.html
templates/web/base/common_scripts.html
templates/web/bristol/footer_extra_js.html
templates/web/bromley/footer_extra_js.html
templates/web/zurich/footer.html
templates/web/zurich/footer_extra_js.html
web/cobrands/borsetshire/js.js
web/cobrands/fixmystreet-uk-councils/js.js
web/cobrands/oxfordshire/js.js

A few front pages giving a jQuery missing error because they're either loading JS they don't need to or not loading jQuery when they do need to:
* Bromley uses jQuery for its A-Z on all pages;
* only load Bristol map JavaScript on map pages (same as Angus);
* fix Zurich load order; and
* improve jQuery check in other JavaScript.

[UK] Make sure jQuery is loaded where it is needed

---

CHANGELOG.md
web/cobrands/sass/_dashboard.scss
web/js/dashboard.js

Fixes part of mysociety/fixmystreet-commercial#965.
Previously, filter items were capped at 25% of the parent width. If you had more than 4 of items, there was a chance enough would extend to the 25% maximum that you’d get items wrapping onto multiple lines:
This pull request fixes that for modern browsers, using flexbox. Items take up a maximum of 25% width, as before, except now, if the total of all items exceeds 100% of the parent, the width of each item is reduced until they all fit. Flexbox does it all automatically for us:
We’ll need to be careful that we don’t abuse this by cramming too many items into these filter forms. But for now, this is the most sensible fix.

Force dashboard filters onto a single line

---

templates/web/fixmystreet.com/about/faq-en-gb.html

They've changed from using an 0845 number to 0345, which is a Good Thing as it will cost people less to call.

Update Ordnance Survey phone number

---

CHANGELOG.md
cpanfile
cpanfile.snapshot
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Engine.pm
perllib/FixMyStreet/App/Response.pm
t/app/engine.t

This prevents FixMyStreet cookies from being sent from third-party `<img>`s and the like, in supporting browsers.

Include "SameSite=Lax" with all set cookies.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
t/app/controller/around.t
web/cobrands/fixmystreet/fixmystreet.js

One server-side (not selecting the category correctly when provided in URL), one client-side (all select multiples using the same settings, that of the first on the page).
Fixes #1950. Fixes #1951.

Fix two around filter issues

---

CHANGELOG.md
web/js/map-OpenLayers.js

This also fixes an inconsistency between what you can see on the map and the
list of reports underneath.
Fixes #1958

Zoom out as much as necessary, even on mobile.

---

CHANGELOG.md
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport.pm

It’s a little annoying to have to fiddle with the database between runs
of send-reports when debugging a stuck/failing report or working on a
new Open311 integration. This commit disables skipping of reports when
the --debug flag is used.

Never skip sending reports with --debug flag

---

CHANGELOG.md
templates/web/base/around/on_map_list_items.html

The map and sidebar are empty on /around when the page loads, and JS is used
to pull in the relevant reports and populate the page. The previous message
indicated that there were no reports at all, but in fact they were being loaded
asynchronously. This commit shows a more helpful message whilst the pins are
being loaded.

Show loading message on /around page load

---

CHANGELOG.md
t/utils.t

Make sure that the prettify_dt tests use the same timezone as FMS
otherwise the test can fail if now in the local timezone is actually
yesterday/tomorrow in the FMS timezone.
Fixes #1984
This does point to underlying issues with `prettify_dt` but given that FMS doesn't really handle multiple timezones I suspect that `prettify_dt` getting passed a date in a different timezone is probably a sign of something else wrong.

prevent timezone related util test failure

---

web/cobrands/angus/js.js
web/cobrands/bristol/js.js
web/cobrands/fixmystreet/assets.js
web/vendor/OpenLayers.Projection.OrdnanceSurvey.js

This PR makes the asset layers code easier to work with if you want to load features from a quirky WFS endpoint, or show a layer independent of the category field, or provide your own styles for features.

Make asset layers more awesome

---

perllib/FixMyStreet/Cobrand/Bristol.pm
perllib/Open311.pm

Bristol's Open311 endpoint isn't fully compliant with [the spec](http://wiki.open311.org/GeoReport_v2/#post-service-request) as it rejects service requests that have no email parameter. This is causing stuck reports since [email addresses aren't always required on fixmystreet.com](https://github.com/mysociety/fixmystreet/pull/1978) any more.

[Bristol] Always include an email address for Open311 reports

---

web/cobrands/fixmystreet.com/js.js

We’re interested in seeing whether people are mistakenly clicking the (inert) "Click map to report a problem" banner on the `/around` page. This will record a Google Analytics event if and when they do.
I’ve included tracking in the code for both fixmystreet.com and all UK councils … but, on second thoughts, I’m wondering whether we _even need it_ in the UK council cobrands, because they won’t be set up to send Google Analytics events anywhere we can see them. Thoughts, @dracos?
Fixes mysociety/fixmystreet-commercial#963.

[UK] Track clicks on ".big-green-button"

---

CHANGELOG.md
templates/web/base/report/_inspect.html
templates/web/base/report/new/category_extras_fields.html
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/js/map-OpenLayers.js

- Display asset layers beneath existing markers on the map
- Fill report `usrn` field from highways asset layer independently of e.g. street lights/grit bins
- Fix bug that would delete values of hidden report extra fields when inspector form saved
- Show hidden report extra fields on inspector form

More asset/inspector form improvements

---

CHANGELOG.md
web/cobrands/oxfordshire/base.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

The tiny buttons could prove hard to trigger, especially on touchscreen devices, and with large screens now more commonplace, there’s no reason not to give them a few more pixels.
One of a number of enhancements suggested in #1462.

Increase size of sub map links

---

CHANGELOG.md
templates/email/default/_email_bottom.html
templates/email/default/_email_settings.html
templates/email/default/_email_top.html
templates/email/fixamingata/_email_bottom.html

Fixes #1928.
(Might look a bit weird on the white Github ticket background, but looks much better on a phone!)

Edge-to-edge email content on narrow screens

---

perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t

The code for moving a report to the intermediary state was running
even if the report was in a closed state and had not been changed.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/974. [skip changelog]

[Zurich] Do not reopen closed reports by mistake.

---

.cypress/cypress/integration/regressions.js
CHANGELOG.md
bin/fixmystreet.com/fixture
templates/web/base/around/_updates.html
templates/web/base/report/display_tools.html
web/cobrands/fixmystreet/fixmystreet.js

I don't think this check could ever have worked, because items are invisible
if their parent is set to `display: none`, so it would hide the links bar if
it was already hidden, and show it if it was already shown.
Use a js- class for the movement of the feed item into the sub map links.

Fix check for visible sub map links.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/controller/report_as_other.t

Store if the report/update was created by someone using the contributed-as
dropdown, and use that information to perhaps not send report-sent emails.

Store contributed-as data.

---

.cypress/cypress/integration/simple_spec.js
templates/web/fixmystreet.com/around/postcode_form.html
web/cobrands/fixmystreet.com/base.scss
web/cobrands/fixmystreet.com/layout.scss

Present "report" vs "browse" choice at time of postcode entry, so we can track intent, as part of a temporary experiment into what people expect to see on the fixmystreet.com/around page.
Google Analytics will be able detect which button was pressed by looking for the `intent=report` or `intent=report` query string param in the resulting pageview location.
We supply a *third* submit button, immediately before the other two, and hidden from visual users and assistive devices, to prevent either of the "intent" submit values being sent when the user submits the form via the Return/Enter key.
Part of #2021. [skip changelog]

[UK] Dual submit buttons on homepage postcode form

---

.cypress/cypress/integration/simple_spec.js
CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

Data collected by #2001 has shown that some people are clicking the big green "Click map to report a problem" banner on fixmystreet.com/around. We assume the same is true for other cobrands.
As suggested in #2016, this commit adds a click handler to that banner element, which will begin a new report at the centre of the screen. It might not be the exact right location, but the pin can be repositioned from the `/report/new` form, and beginning a report is better than just soaking up the click and doing nothing.

Clicking "big green banner" on /around begins a report

---

web/cobrands/fixmystreet/fixmystreet.js

#2032 included a bug that left the "big green banner" visible when you clicked to start a new report or view an existing report.
This fixes that bug.

[UK] Correctly show and hide experimental .big-green-banner

---

CHANGELOG.md
templates/web/base/around/postcode_form.html
templates/web/borsetshire/around/postcode_form.html
templates/web/fixmystreet.com/around/postcode_form.html

Will give some feedback to people who click one of the submit buttons without first entering a location to search for.

Make homepage #pc input required

---

perllib/FixMyStreet/SendReport/Open311.pm
t/cobrand/bromley.t

If the map was not clicked and we don't have a postcode we should still
send the easting and northing extra attributes if send_notpinpointed is
set.

send easting/northing over open311 if send_notpinpointed and no map/postcode

---

.cypress/cypress/integration/regressions.js
CHANGELOG.md
web/cobrands/sass/_base.scss
web/js/map-OpenLayers.js

Fix race condition making a new report: If you started a new report by clicking the map before the server had responded with the map list pins, when they did arrive they would replace the new report pin. Fixes #1434 (better way this time too, I think).
The "coerce pin ID to integer" behaviour to fix a previous issue was coercing undefined to NaN, which then caused other problems with the new report pin, such as fading out when hovered, and being the wrong size (well, it used to be bigger and now it is again, though dunno if people are now used to smaller). Fixes #2038.
Also improve the cursor handling, showing the grab/ grabbing cursors where available.

Fix issues with new report pin, improve cursor.

---

CHANGELOG.md
perllib/FixMyStreet.pm

fixmystreet.com went down early Sunday morning because the database server had
been upgraded in the past year and was now set to UTC and not local time. This
confused the codebase when it encountered timestamps that could not exist, all
between 1-2am UTC.
Ideally, timestamps in the database should be 'with time zone' or be stored in
UTC, but for now let us set the time zone to the local one upon connection.

Set database session timezone on connection.

---

templates/email/default/_email_bottom.html
templates/email/default/_email_top.html

dcc5926 simplified the HTML email layout and styling, but introduced a
bug in Mac and iOS Mail (both of which use Safari to render emails)
where the central "column" of the layout would expand beyond its 620px
maximum width if your window/screen was big enough to let it.
As far as I can tell, this is a bug in Safari – it treats empty table
cells as if they aren’t there, meaning, in our layout, they no longer
"pushed" against the sides of the central column, allowing it to expand
to the full width of the parent (the window).
Adding a non-transparent background-color to the cells forces Safari to
handle them correctly, so we set a background-color that matches the
body background, to effectively make the cells invisible, while still
giving them enough "layout" to trick Safari into rendering …

Fix Mac / iOS mail full-width email layout bug

---

.cypress/.gitignore

The Cypress docs suggest putting machine-specific config into a
`cypress.env.json` file at the same location as `cypress.json`.
(For example, if you want to disable video recording of test sessions
on your machine, but not everyone else’s.) Since this file will be
machine-specific, we don’t want it tracked in Git.

Gitignore cypress.env.json

---

CHANGELOG.md
bin/update-schema
db/downgrade_0058---0058.sql
db/schema.sql
db/schema_0059-response-templates-external_status_code.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/ResponseTemplate.pm
perllib/Open311/GetServiceRequestUpdates.pm
t/app/controller/admin/templates.t
t/open311/getservicerequestupdates.t
templates/web/base/admin/report_edit.html
templates/web/base/admin/template_edit.html
templates/web/base/admin/templates.html
templates/web/base/admin/update_edit.html

Fixes mysociety/fixmystreetforcouncils#297. As mentioned in that ticket, Confirm has a more fine-grained status code system than FMS which we want to use to trigger response templates/emails to users.
This PR:
- Fetches the `external_status_code` attribute from Open311 service request updates
- Allows response templates to be associated with an external status code instead of an FMS state
- Triggers response templates by `external_status_code` when fetching updates.

Allow response templates to be triggered by Confirm status code.

---

CHANGELOG.md
bin/update-schema
db/downgrade_0059---0058.sql
db/schema.sql
db/schema_0059-add-convert_latlong.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/Open311/GetServiceRequests.pm
t/Mock/MapIt.pm
t/app/controller/report_inspect.t
t/open311/getservicerequests.t
templates/web/base/admin/open311-form-fields.html

If the backend we are pulling reports from cannot provide Lat/Long then accept Easting and Northing and convert to Lat/Long in FixMyStreet.
This is here to avoid it being in the Open311 adapter and leave that to be as much of a pass through system as possible.
Fixes #2028

optionally convert incoming open311 problem locations from EPSG:27700

---

perllib/FixMyStreet/App/Controller/Report.pm
t/app/controller/report_inspect.t

Comments added offline by an inspector set the time in JavaScript using
a UTC epoch. We need to add the FMS timezone to this so it's in the
timezone the database expects for timestamps otherwise it's incorrect
when we fetch it back out

fix timezone problems with offline inspector comments

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/Cobrand/Default.pm
templates/web/base/admin/user_import.html

This is intended to be an internal tool for quickly creating staff
users in bulk. As such, it's hidden at `/admin/user_import` and is only
available to superusers.

User import admin page

---

CHANGELOG.md
templates/web/base/around/display_location.html
templates/web/base/maps/google-ol.html
templates/web/base/reports/body.html
templates/web/zurich/maps/zurich.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

**To do**
* Check tests
Fixes #2018 by making the `#sub_map_links` bigger.
But the greater win here is that we’re using fewer ID selectors in our CSS, and both `#sub_map_links` and `#mob_sub_map_links` now share the same styling – both of which are good for maintainability.
<table>
<thead>
<tr><th>Before</th><th>After</th></tr>
</thead>
<tr><td><img src="https://user-images.githubusercontent.com/739624/38257732-b312e526-3758-11e8-87c0-566983513f8d.png" width="300" height="533" alt=""></td><td>
<tr><td><img src="https://user-images.githubusercontent.com/739624/38257900-1aa5f5e8-3759-11e8-9165-e28961351786.png" width="300" height="533" alt=""></td><td><img src="https://user-images.githubusercontent.com/739624/38257869-0d32661c-3759-11e8-9af6-479afa7f77a9.png" width="300" height="533" …

Standardise styling for #sub_map_links and #mob_sub_map_links

---

templates/web/fixmystreet.com/header_extra.html

#2032 introduced a bug on FMS.com only, where, if you were chosen to be in the "button over map" experiment group, the button would be incorrectly shown _even_ on mobile, because of a CSS selector specificity issue.
Fixes #2060.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tr>
<td>
</td>
<td>
</tr>
</table>

Prevent green banner (#2032) appearing over mobile map

---

CHANGELOG.md
templates/web/base/maps/osm.html
web/cobrands/bathnes/js.js
web/cobrands/fixmystreet/assets.js
web/js/map-OpenStreetMap.js

Allow asset layers to add their own attribution string to the map.
Fixes mysociety/fixmystreetforcouncils#304

asset layer map attribution

---

CHANGELOG.md
t/app/controller/report_inspect.t
templates/web/base/report/_inspect.html

I find myself wanting to view the current report in the admin all the time -
this PR adds a link to the top of the inspector column that goes right there.
Only visible for superusers and staff users with permission to actually view the
admin.

Add link to edit current report in admin

---

CHANGELOG.md
bin/update-schema
db/downgrade_0061---0060.sql
db/schema.sql
db/schema_0061-add-extra-body.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/Open311/GetServiceRequests.pm
t/app/controller/admin/bodies.t
t/open311/getservicerequests.t
templates/web/base/admin/open311-form-fields.html
web/cobrands/sass/_admin.scss

This adds an option to not set start and end dates when fetching problems over Open311. This is either if you always want to fetch all of them or if the API doesn't have a date options and you want to suppress the warnings about problems outside the default date range.

Open311 fetch all reports

---

CHANGELOG.md
perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

Previously, an update's problem_state was set via an Open311 update if:
* the update timestamp was equal or greater to the report's last update;
* the new state was visible, and not equal to the report's current state;
* the update wouldn't change the report from a fixed state to another fixed state;
* (Oxfordshire) the update wouldn't change the report from any open state to Open.
It would also set the report's state to match if the report was currently visible.
This mostly worked, but could lead to issues if e.g. the report started life in
a non-confirmed state (e.g. we pulled it in already fixed from an external
source), as then the update did not record its state and the update display got
confused as to the state history. However it did mean there wasn't confusion if
a later update …

[Open311] Generally store update state.

---

templates/web/fixmystreet.com/about/faq-en-gb.html

Since https://github.com/mysociety/fixmystreet/pull/1554 it has been possible for a user to hide their name on their reports and updates, rather than having to contact support. This PR updates the FAQ to mention that.

Add info on anonymisation feature

---

perllib/FixMyStreet/App.pm
perllib/Memcached.pm

The namespace was only being set in the web loop, so cron scripts
were accessing different memcached keys. In particular, the state
list would be shared between instances on the same host.

Always set memcached namespace.

---

CHANGELOG.md
Vagrantfile

The precise box's default libssl cannot connect to github; yes, you can update/upgrade first off to get it usable, but precise is in extended-support anyway now, and bionic is out soon, so I think moving to xenial for vagrant makes sense. FMS should already be supporting xenial, so this should be fine (just running it from scratch now).

Update Vagrantfile to use Xenial.

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
web/cobrands/fixmystreet/assets.js

If the user visits /report/new directly and doesn't change the pin
location, then the assets:selected/maps:update_pin events are never
fired and fixmystreet.usrn.select is never called. This results in a
report whose location was never looked up against the USRN layer,
which can cause issues for Open311 endpoints that require a USRN
value.
Also increases the USRN lookup radius for reports made via the app/national
site.

Ensure USRN asset lookup JS is run on /report/new

---

CHANGELOG.md
web/cobrands/fixmystreet/admin.js
web/cobrands/sass/_admin.scss

If JavaScript is enabled hide the deleted contacts from the list on the
body page. Display as normal if no JavaScript.
Fixes #1962

hide deleted contacts by default

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

Response templates won't be triggered unless the problem state or
external status code is changed.
Fixes #2075 

Don’t trigger response templates unless problem state changes

---

.gitignore
CHANGELOG.md
perllib/CronFns.pm
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Script/UpdateAllReports.pm
t/Mock/MapIt.pm
t/app/controller/report_new.t
t/app/controller/reports.t
t/cobrand/form_extras.t
templates/web/base/around/index.html
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/councils_text_all.html
templates/web/base/report/new/form_report.html
templates/web/base/report/new/form_title.html
templates/web/base/report/update/form_state_checkbox.html
templates/web/base/report/update/form_update.html
templates/web/fixamingata/report/new/top_message_none.html

These are the hooks needed for the refactor of the `smidsy-candidate` branch (still there if that's useful) on to current master:
* table dashboard - to have its own columns on `/reports`
* bodies list - to filter the list of bodies on `/reports`
* new reports - to change the title/category before submission based on extra data submitted
* `aroundpage` class
* One new template
* Adding 'validation' of report_form_extras
I didn't need the contact changes (master now handles extra values), email changes (master is fine) will do batched reporting in the cobrand, and various other bits are now done differently.
The cobrand specific files are not in core any longer, but at https://github.com/mysociety/collideoscope/pull/4
Will probably need looking at …

Collideoscope refactor

---

CHANGELOG.md
bin/send-comments

Previously send-comments errors would only be printed the first time
they occurred so there was no visibility of ongoing errors. This brings
send-comments in line with send-reports by emitting errors if the script
is called with --verbose.
Fixes #2091

[Open311] warn about send-comments errors if verbose flag set

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin/report_edit.t
templates/web/base/admin/report_edit.html

Instead of just a Yes/No display a formatted list of values in extra.
Has special handling for known fields otherwise just prints them out
dumbly.
Fixes #1809

display the contents of report's extra field in admin

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm

If a new user registers during the report/update process
and their password starts or ends with whitespace or has
consecutive whitespace chars then those would be stripped
and the entered password wouldn’t work for subsequent logins.

Don’t strip whitespace from user passwords during registration

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

If no text, photo, or state change, hide the update from display.
Question: hide, or not insert them? Not inserting means it'll process them again next time, but presumably with same outcome? So might be better.
Todo: test.

[Open311] Hide fetched update if no data to show.

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Map.pm
t/app/controller/around.t

So that you can build functionality to add extra limitations on to the map pins displayed. Useful for Collideoscope initially to filter out (or in) reports from the Department of Transport's Stats19 Data.

Allow cobrands to supply arbitrary extra query params for map pins

---

templates/web/base/report/update.html
web/cobrands/sass/_layout.scss

The internal link for updates to enable #update_n anchor links to work
has some padding/margin CSS to make sure the place scrolled to doesn't
obscure any of the update. This is partly based on the page header and
does not interact well with the header for the Bromley cobrand
preventing the user from clicking on the update moderation checkboxes.
By overriding the margin/padding for Bromley the anchor link still works
and the checkboxes also work
Fixes mysociety/fixmystreet-commercial#1027

[Bromley] fix inability to click hide update checkbox

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
t/app/controller/admin/report_edit.t
t/app/controller/report_new.t
templates/web/base/admin/report-category.html
templates/web/base/report/_inspect.html
templates/web/base/report/new/category.html
templates/web/base/reports/_list-filters.html
templates/web/zurich/admin/report_edit.html
templates/web/zurich/admin/stats/index.html

This displays a category's extra `help_text` if present in list filters and when reporting.
It also takes the opportunity to just pass around Contact objects rather than map them to smaller hashes.

Extra help text for categories

---

CHANGELOG.md
web/cobrands/sass/_layout.scss

Avoid empty space either side of "key tools" drawer when open

---

CHANGELOG.md
perllib/FixMyStreet/DB/ResultSet/DefectType.pm
perllib/FixMyStreet/DB/ResultSet/ResponsePriority.pm
perllib/FixMyStreet/DB/ResultSet/ResponseTemplate.pm
t/app/model/defecttype.t
t/app/model/responsepriority.t
t/app/model/responsetemplate.t
templates/web/base/report/_inspect.html
web/cobrands/fixmystreet/staff.js

This fixes a bug whereby a double quote in an item would not be JSON-escaped
due to being HTML-escaped first, meaning it would not parse as JSON on the
client.

Escape data attributes in template.

---

templates/web/base/about/privacy.html
templates/web/fixamingata/about/privacy.html
templates/web/fixmystreet-uk-councils/about/privacy.html
templates/web/fixmystreet.com/about/privacy.html
web/cobrands/fixmystreet.com/_colours.scss
web/cobrands/sass/_base.scss

While doing https://github.com/mysociety/collideoscope/issues/3 I noticed that the cookie tables we put into our Privacy Policy pages weren’t getting styled up. The narrow, 10px gutters, and lack of gridlines, made it hard to see where cells begin and end.
Meanwhile, it rang a bell that, recently, the old `.nicetable` style got [reintroduced in KIITC](https://github.com/mysociety/fixmystreet-commercial/commit/1eed07d2392b37b17201c748a8207757347582a6) to display the list of authorities and their assets.
I figured, why not reintroduce a simpler version of the old `.nicetable`, for those times you need to make tables legible; and then use it in all the Privacy Policies, and also on the KIITC `/reports` page.
This PR does the first two of those three things, and …

Reintroduce “nicetable” class for simple table styling

---

web/cobrands/sass/_base.scss

There was a CSS specificity bug in #2137 that meant table heads would change colour on hover, which wasn’t intended. This fixes that!

Fix CSS specificity bug with new nicetable hover styles

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
t/cobrand/bathnes.t

- Adds a cobrand hook for customising the dashboard CSV output
- Adds a new `Extra columns in CSV export` permission to the BANES cobrand
- Dashboard CSV exports by users with the new permission include some extra information for each report:
- User Email
- User Phone
- Reported As
- Staff User
- Attribute Data
- Site Used
Fixes mysociety/fixmystreet-commercial#1056.

Add extra columns to BANES dashboard CSV export

---

templates/web/zurich/admin/contact-form.html
web/cobrands/fixmystreet/admin.js

Editing a contact with extra fields would cause those fields to be
deleted because they weren't included in the POST request when saving.
This change ensures they're present in the DOM, but hidden by default.

[Zurich] Don't delete extra fields when editing contact

---

CHANGELOG.md
web/js/map-OpenLayers.js

Going back to /around from /report/new can trigger loadend (and the
spinner hiding function) twice (if the strategy activation starts a
read), with triggerRead aborting that read and triggering the event
itself. This means the spinner is not displayed, as the count falls
below 0. We could pin the count above 0, but instead let’s log each
layer ID while ‘active’ and switch off when they’re all gone.

Improve handling of loading spinner display.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Map/Bromley.pm
perllib/Open311/PopulateServiceList.pm
t/cobrand/bromley.t
t/open311/populate-service-list.t
web/cobrands/bromley/map.js
web/cobrands/fixmystreet/assets.js

This PR does asset-related things for Bromley Council, see https://github.com/mysociety/fixmystreet-commercial/issues/1005
It adds bins, street lights, trees, TfL red routes, and rights of way layers. The first three are point layers that can be selected, the red routes are used in certain categories to explain/divert to TfL (unless asset selected), and rights of way are displayed and ID taken through. In order to have multiple 'road' type layers, the USRN/road code is refactored into its own Layer class, which shouldn't affect anything but needs some testing.

[Bromley] Asset layers and related

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Contact.pm
t/app/controller/contact.t
templates/web/base/contact/index.html

We get quite a few emails to support that are about a specific problem
but fail to include a link to that problem. This adds some text to the
contact form to ask people to do so.

add reminder to include link to report on contact form

---

CHANGELOG.md
templates/web/base/main_nav.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/map-OpenLayers.js

On a mobile device that implements pointer events, there are two events that
can happen on an /around page – touching the map starts a new report (or goes
back to the map if already on a report page); touching a pin pulls in that
report’s page. The map touch, which uses an OpenLayers.Handler.Click, operates
by default on click, whereas the pin touch, which uses an
OpenLayers.Handler.Feature, operates on touchstart. You end up either starting
a new report, and then it tries to pull in an undefined pin ID report and
errors, or the pin report loads and then you instantly go back to the map page.
The first touchstart event disables click events on the handlers, which fixes
this issue (and hence why the problem does not arise if you drag the map
first). So we disable the click handlers as soon …

Fix pointer event issue selecting pin on map.

---

perllib/Open311/PopulateServiceList.pm

If we assume that any body with can_be_devolved set is probably a mix of
Open311/email, we can ignore any email address contacts for such a body.

Don’t delete email contacts on devolved bodies.

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/oxfordshire/open311_services.t

Times in the Oxfordshire DB use local time so we need to convert our UTC
strings before using them in queries.
Fixes mysociety/fixmystreet-commercial#1062

[Oxfordshire] convert UTC string to local time

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/Contact.pm
t/app/controller/admin/reportextrafields.t
templates/web/base/admin/contact-form.html
templates/web/base/admin/extra-metadata-form.html

Display fields that are automatically filled in the contact editing form
otherwise the data is lost. Also include the automated field in the
form.
Fixes #2136

include automated field when editing contacts

---

CHANGELOG.md
templates/web/fixmystreet.com/about/faq-en-gb.html
templates/web/greenwich/about/faq-en-gb.html
templates/web/hart/about/faq-en-gb.html
templates/web/stevenage/about/faq-en-gb.html
templates/web/stevenage/footer.html
templates/web/stevenage/front/footer-marketing.html
web/cobrands/bromley/layout.scss
web/cobrands/fixamingata/layout.scss
web/cobrands/greenwich/layout.scss
web/cobrands/rutland/layout.scss
web/cobrands/sass/_layout.scss

Fixes #2107. The offending CSS from the issue is now the much more obvious `#footer-mobileapps a`, and the worst bit in the section is now `.content footer .tablewrapper h4` which is fair enough as it is because `.tablewrapper` and `footer` are both used elsewhere, and I didn't want this to be a big hunt of fixing the classes at the mo!

Reduce complexity of footer CSS a bit

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t

This allows the mobile app to explicitly detect when a body is
unresponsive and display the category_extra text.
For mysociety/fixmystreet-mobile#266

send unresponsive details back with category extras

---

CHANGELOG.md
perllib/Open311.pm
t/open311/getservicerequestupdates.t

The Open311 specification has two values for a report's status:
- open: it has been reported.
- closed: it has been resolved.
FixMyStreet previously mapped 'closed' to 'fixed - council', but this
has been causing issues with Open311 endpoints that want to mark a FMS
report as closed but not fixed. The mySociety Open311 additions
introduce extended statuses, some of which represent a 'closed' state
e.g. duplicate, no_further_action, but there are times when a report
should simply be closed without any indication why - for example, if
open311-adapter is being used to integrate with a council system which
has a closed state not represented by the extended statuses. Marking a
report as 'closed' on a council system and displaying that as 'fixed'
on the FixMyStreet front end is not an ideal …

Map Open311 CLOSED status to closed state if extended statuses enabled.

---

CHANGELOG.md
t/script/inactive.t
templates/web/base/report/display.html

To do:
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/875

Show message on reports closed to updates.

---

CHANGELOG.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/User.pm
templates/web/base/around/postcode_form.html
templates/web/base/main_nav_items.html
templates/web/borsetshire/around/postcode_form.html
web/js/map-OpenLayers.js

Categories could contain commas, so splitting on comma is not good enough.
Let’s escape the fields as if it’s a line in CSV. Fixes #2166.

Use CSV escaping for categories in URLs.

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/FiksGataMi.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/TestMech.pm
t/Mock/MapIt.pm
t/app/controller/alert.t
t/app/controller/alert_new.t
t/app/model/alert_type.t
t/cobrand/fiksgatami.t

Hitherto when creating a body or ward alert on a UK site, the MapIt area ID has been stored instead of the body ID. This is okay for www.fixmystreet.com which for historical reasons does have body IDs that match MapIt area IDs, but other UK-based sites may well not. The alert lookup looks for body ID, meaning those alerts will not work. Save the body ID instead, plus fix some tests that were making the same assumption.

[UK] Fix issue when body ID not equal to MapIt ID.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/Map.pm
t/app/controller/around.t
t/map/tilma/original.t
templates/web/base/around/on_map_list_items.html
templates/web/base/pagination.html
templates/web/base/reports/_list-filters.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/map-OpenLayers.js

Hides reports older than 6 months on the around page by default.
Fixes #2098

Hide old reports by default

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Questionnaire.pm
t/app/controller/questionnaire.t

Users who double click links were seeing an error when visiting the
questionnaire page. This change gives a grace period of two minutes
for revisiting the questionnaire page.
Fixes #2123.

Allow questionnaire pages to be revisited within 2 minutes

---

templates/web/fixmystreet.com/reports/summary.html

Fixes mysociety/fixmystreet-commercial#1087. I think it also fixes #2103?

Make non-pro dashboard CSV download limit clearer

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t
templates/web/base/maps/openlayers.html
web/cobrands/bathnes/js.js
web/cobrands/buckinghamshire/js.js
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/map.js
web/js/map-OpenLayers.js

Associate layers with a body and only show them if the body covers the area displayed on the map. This is to allow us to use asset layers on the national site and only display the appropriate layers for an area.
This adds a body property to layers which specifies the body associated with the layer, a bodies property to the fixmystreet object to specify which bodies are associated with the area shown on the map, and the associated code to only display that layer if the two match.
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1086

Body specific asset layers

---

CHANGELOG.md
perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

A move between fixed states (presumably fixed-user to fixed-council) should
not count as a state change for the purposes of generating comment text from
templates.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1123

[Open311] No update text on fixed state move.

---

CHANGELOG.md
templates/web/base/js/translation_strings.html
templates/web/base/main_nav_items.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_layout.scss
web/js/map-OpenLayers.js

Fixes #2016 and is a partway solution to #2012.
Rather than always saying "Report a problem" and always just linking back to the homepage postcode search form, the `.report-a-problem-btn` in the nav bar now behaves differently, based on what else is on the page.
The general idea is that, if you’re looking at an individual problem already, then the button will say "Report _another_ problem here" and will automatically begin creating a new report at the same coordinates. Otherwise, if you’re zoomed a sensible distance into a map, then the button will say "Report a problem _here_" and will begin a report at the centre of the visible map. And finally, if neither of those cases are true, it’ll just do what it always did, and take you to the homepage.
When clicking the button, if it’s possible …

"New report near here" button in nav bar

---

CHANGELOG.md
templates/web/base/tokens/confirm_problem.html
web/cobrands/sass/_base.scss

Part of #2012.
Should make it much quicker to report multiple problems in the same location, one after the other.
Uses the same new `loc('Report another problem here')` string that was introduced in #2195.

"Report another problem here" button on confirmation page

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/FixMyStreet/SendReport/Open311.pm
t/Mock/MapIt.pm
t/cobrand/bucks.t
web/cobrands/buckinghamshire/assets.js

Allow flytipping reporting on cobrand and .com, with road reports going to Bucks Confirm and email, and non-road reports going to district and Bucks emails. [skip changelog]
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1118

[Buckinghamshire] Update flytipping handling.

---

web/cobrands/bathnes/assets.js
web/cobrands/bristol/assets.js
web/cobrands/bromley/assets.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/assets.js

Bristol - different maps on Bristol/.com, different resolutions. Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1126
Showing the assets more zoomed out - there is the possibility of e.g. going to a Bucks location on .com, clicking map on-road at zoomed out level (say most zoomed in 1:25k), selecting category and it saying you're not on a road and not letting you. Easiest solution is showing them at zoom level 2 also (was previously 3), but perhaps need to show some at all zoom levels? Probably quite an edge case.

Fix Bristol assets on .com, and show assets more zoomed out

---

perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Map/FMS.pm
templates/web/base/maps/pin.html
templates/web/oxfordshire/footer_extra_js.html
web/cobrands/fixmystreet/map.js
web/js/map-OpenLayers.js
web/js/map-fms.js

* New OS map doesn't work at zoom level 11 any more.
* 27700 library not loaded for Oxfordshire, so inspectors not getting easting/northing when pin dragged.
* Set up fully whether pins are draggable or not, which should fix inspector issue dragging/unable to click pins that shouldn't be draggable. Theoetically this means the DragFeatureFMS control could be loaded at all times, and it shouldn't affect any non-draggable pins, but I have not done that here.

Few small breakages to fix

---

templates/web/fixmystreet.com/about/house-rules.html

We’ve recently come across a case of a FixMyStreet user making reports and comments under the name of other nearby residents, often then going on to fabricate potentially defamatory conversations between these sockpuppet accounts.
This is clearly not how we expect people to use FixMyStreet, and it brings no benefit to the community, or the councils receiving the reports. If users feel the need to contribute without disclosing their name, they can do so anonymously.

New House Rule forbidding impersonation

---

CHANGELOG.md
templates/web/base/report/new/form_report.html

Previously, if you didn’t want a hint to appear under the main "details" textarea on the new report form, you had to override the entire `form_report.html` template, or leave the hint element in the markup but hide it with CSS.
Now, you can set `form_detail_placeholder` to a falsey value, and the template won’t output the hint element at all. It also amends the `aria-describedby` attribute on the textarea so it doesn’t end up referencing a hint element that doesn’t exist.
I needed this for https://github.com/mysociety/collideoscope/pull/28, because the existing `[% DEFAULT form_detail_placeholder = … %]` block gave me no easy way to prevent the hint being shown.
When no custom `form_detail_placeholder` is defined in the cobrand, eg:
```
[% form_detail_label = loc('Can you describe what …
```

Make it easier to prevent a form_detail_placeholder being printed

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t
t/app/controller/report_new_open311.t
templates/web/base/js/translation_strings.html
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js

Add `by_category` output to the `/report/new/ajax` call, containing all the data (or at least, the needed subset, e.g. not returning `councils_text` if same as general one) that `/report/new/category_extras` returns for one category. Then alter the JS to use that data immediately when needed. Fixes #1201.
The `/category_extras` is kept (mobile app currently using it) but no longer outputs councils_text (unused), or category_extra/json if no output (code copes fine); it still has to output `unresponsive` as app code specifically checks for empty string.
One issue I came across was when switching from Flytipping to Graffiti in Bucks, it not switching off the single_body_only for Bucks. This was because in old-way, `road_found` fired for Graffiti (thus removing single_body_only) at the …

Remove need for category_extras ajax call.

---

CHANGELOG.md
web/cobrands/sass/_base.scss

Fixes https://github.com/mysociety/collideoscope/issues/44
(Note the "HOME" button and "RIGHT PLACE?" title stacked _behind_ the black overlay)
("HOME" button is no longer obscured by the black overlay, so can be pressed)

Make sure Home clickable with Try again overlay.

---

web/cobrands/buckinghamshire/assets.js

Sending to Bucks reports made on non-Bucks roads was only disabled if
Bucks was the only body concerned; flytipping is a concern of both
tiers, but reports on non-Bucks roads should still not be sent to Bucks.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1150

[Buckinghamshire] Do not report on non-Bucks roads

---

web/cobrands/bromley/assets.js

This displays street lights and bins for too many things, but there's no way to filter spot assets apart from category at present.

[Bromley] Update asset for category changes.

---

web/cobrands/bromley/assets.js
web/cobrands/fixmystreet/assets.js

This moves `check_layer_relevant` from a global function to on the layer class, which means then it is easily subclassable to provide more nuanced behaviour. I think. Will test in the morning! [skip changelog]

[Bromley] Asset display fixes

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_import.t
templates/web/base/report/new/report_import.html

if a web parameter is passed to /import then display the email
confirmation sent page rather than a SUCCESS message. Enables this page
to be used for creating partial reports from a web page.
For mysociety/collideoscope#17

allow web based use of report import

---

web/js/dashboard.js

We needed this for Collideoscope, where we’re displaying small bar charts on the Statistics page, and the default bar height of 30px was much too small when the chart was reduced in size.

.js-make-bar-chart now accepts custom chart/bar dimensions

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin/permissions.t

If an admin with the user_edit permission but not user_assign_body
edited a user with from_body set, the from_body field was lost.

Don't lose from_body if edited by non-superuser.

---

CHANGELOG.md
conf/general.yml-example
perllib/Memcached.pm

Previously we assumed that any memcache instance would be running on the local loopback interface. This commit makes this configurable with a `FMS_MEMCACHED_HOST` option. If left unset, this will default to `127.0.0.1`.

Add configuration option for memcached host

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/DefectTypes.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/ResultSet/Body.pm
t/app/controller/admin/defecttypes.t
templates/web/base/admin/bodies.html
templates/web/base/admin/defecttypes/index.html
templates/web/base/dashboard/index.html
templates/web/base/reports/index.html

Use a HashRefInflator wherever `all_sorted` is used, with consequential changes to deal with it now not being an object (e.g. add some `with_*` functions for manual fetching of extra data).

Speed up fetching lists of bodies.

---

CHANGELOG.md
conf/nginx.conf.example
conf/sysvinit.example
script/server

This allows `script/server` to take arguments, switches the example sysvinit script to use it rather than the FastCGI daemon, and the example nginx config to proxy rather than use FastCGI.

Switch to direct app server, not FastCGI.

---

CHANGELOG.md
Vagrantfile

This sets the default box to be `mysociety/fixmystreet` and provides
an optional argument, `--base-box`, that can be used to override this.
When using the `mysociety/fixmystreet` box, the Perl modules are
prebuilt in `/usr/share/fixmystreet/local` and are bind-mounted into
`/home/vagrant/fixmystreet/local`. This ensures that these are
compatible with the guest machine and speeds up an initial launch.
The `mysociety/fixmystreet` box is also based on Debian Stretch so is
a closer match to our current production environment.

Vagrant: Use the mysociety/fixmystreet box by default

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/app/controller/admin/defecttypes.t
t/app/controller/admin/permissions.t
t/app/controller/my_planned.t

Adds a message about the system being off line and also turns off the inspector tool.

Pre OCC WDM go live

---

Dockerfile
conf/packages
conf/packages.docker
conf/packages.generic

This is required to build `XML::LibXML`, a dependency of `Net::Amazon::S3`. Without this, the Docker and Vagrant builds fail.

[Dependencies] Add libxml2-dev to packages files

---

Dockerfile

Rather than pulling across the preinit file from master, use the
version in the copy of FixMyStreet on the image - this will then
match the release actually being built.

[Docker] Copy the preinit file from the local working copy at build

---

CHANGELOG.md
templates/email/default/partial.html

Fixes #2263.
Here’s what it should look like:
@dracos Do I need to add a test somewhere that checks the "partial" email is now multipart text+html? Or is that generic enough that it’s covered by other tests like `send_email.t`?

HTML template for the "partial" report confirmation email

---

conf/sysvinit.example

The install script calls a service restart at build, this failed if the stop action in the init script doesn't check for the existence of the `PIDFILE` first, so check.

Add check for PIDFILE to init script stop action

---

Vagrantfile

When using the mySociety Vagrant box, ensure that the `local/` directory is present before attempting to bind mount the pre-built Perl modules.
Without this directory present the bind mount will fail and the Perl modules will all be built again unnecessarily.

[Vagrant] Ensure `local` directory is present

---

CHANGELOG.md
bin/run-tests
cpanfile
cpanfile.snapshot
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/develop.t
t/app/controller/root.t
t/cobrand/zurich.t
t/i18n.t
t/open311/getservicerequestupdates.t
t/photostorage/s3.t
templates/web/base/pagination.html

* Stop red warning being output by S3 bucket creation failure test
* Make sure 'num_old_reports' is always a number on /around pages
* Stop 'category_extra' being generated when unnecessary
* Prevent warning printed in getservicerequestupdates.t
* Prevent info lines from being output in develop.t

Deal with a variety of low-level test warnings.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/cobrand/oxfordshire.t

Allow cobrands to do their own search from the front page if the string matches `lookup_by_ref_regexp'.
Add in a custom search for OCC if the search matches a customer_reference.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1200

OCC reference search

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Dashboard.pm
t/app/controller/dashboard.t

This allows a cobrand to e.g., as the test does, allow public access to dashboard CSV export for a body, but not otherwise.

Add cobrand hook for dashboard viewing.

---

CHANGELOG.md
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/ResultSet/Body.pm
t/app/controller/report_display.t
t/app/controller/reports.t
templates/web/base/admin/body.html

`body.url` could still be in use by old-school `/reports` table index pages (though they were dropped in 2.1, so a cobrand would have to have overridden it since then) and the update to speed up body lists in #2248 broke it. This puts it back in minimal form.
I've removed the Norwegian note as they must have something different, the current code wouldn't be working for them either.

Have body.url work in hashref lookup.

---

perllib/Open311/GetServiceRequestUpdates.pm

The //= meant that once `$open311` was populated we reused it each time
which mean we were passing the original config in to each body.

do not reuse original open311 object in fetch comments loop

---

CHANGELOG.md
perllib/FixMyStreet/Map/OSM.pm
t/app/controller/around.t

call ZOOM_LEVELS and MIN_ZOOM_LEVELS using self so that we can override
them in a subclass.

allow map zoom constants to be overridden

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin/report_edit.t
templates/web/base/admin/report_edit.html

Add a count of currently active alerts on new updates for a report to
the admin page.
Fixes #669

display alert count on admin report page

---

CHANGELOG.md
docs/customising/cobrand-module.md
perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/contact.t
templates/web/bromley/footer_extra.html

Remove links to the contact form for Bromley cobrand.
Also add a cobrand option to limit the contact form to abuse reports only and turn that on for Bromley.
Fixes mysociety/fixmystreet-commercial#1198

[Bromley] disable contact form

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin/users.t
templates/web/base/admin/user-alerts.html
templates/web/base/admin/user_edit.html

Include a list of alerts the user is subscribed to at the bottom of the
user_edit page in the admin. Also allows disabling, enabling and deleting of alerts.
Fixes #676 

list user's alerts on user edit page in admin

---

.cypress/cypress/integration/around_filters.js
CHANGELOG.md
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/moderate.t
t/app/controller/photo.t
t/app/controller/report_interest_count.t
templates/web/base/report/_support.html
templates/web/base/report/display_tools.html
web/cobrands/fixmystreet/fixmystreet.js

Lets a cobrand provide a standard photo upload form (as on new report/update) in the report display so moderation can add/remove photos to a report, not just show/hide.

Allow moderation to potentially change photos.

---

CHANGELOG.md
perllib/FixMyStreet/Script/Questionnaires.pm
t/app/controller/questionnaire.t

Stops questionnaires being sent for reports closed/fixed via Open311.
Not sure if we want this behaviour for situations where a report has been closed/fixed by an admin/council staff user too?
Connects to https://github.com/mysociety/fixmystreet-freshdesk/issues/24.

Disable questionnaires when closing/fixing reports via Open311

---

bin/fixmystreet.com/backfill-open311-comments
perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

Allows creating scripts that fetch comments for a single body, e.g for
batch updating or because they require special setup.

allow comment fetching to be limited by body name

---

.cypress/cypress/integration/category_tests.js
CHANGELOG.md
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t
web/cobrands/fixmystreet/fixmystreet.js

- Fixes a bug that meant items in top-level category dropdown were out of order if there was a mix of grouped and ungrouped categories
- There are existing Open311 contacts (Bristol, Greenwich) in the DB which have unhelpful groups applied, presumably because they weren't intended to be seen publicly.
- This PR inspects the cobrand's `enable_category_groups` value when populating Open311 categories and only sets the contact's `group` metadata if the handling cobrand has groups enabled.
Connects to mysociety/fixmystreet-commercial#1148.

[FixMyStreet.com] Enable category groups

---

perllib/FixMyStreet/DB/Result/Comment.pm

This adds a cobrand configuration option for always showing the
body user's name in updates.
Fixes #1860
This is for FixaMinGata, but I'm delivering just the generic change now and will open a separate PR for the FixaMinGata cobrand, since I'm not sure of the approval process for delivering to a cobrand (I'm new with FixaMinGata :-) )

Add configuration option to show staff user name as well as body name

---

perllib/FixMyStreet/Cobrand/FixaMinGata.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/cobrand/fixamingata.t
templates/web/fixamingata/footer_extra_js.html
web/cobrands/fixamingata/js.js

A couple of customizations for FixaMinGata:
1. Show staff user names in updates
2. Don't scroll reports on load
This is my first delivery to the FixaMinGata cobrand. Let me know if you need some kind of approval from someone at FixaMinGata/Sambruk in some way.

[FixaMinGata] cobrand customizations

---

CHANGELOG.md
Vagrantfile
docs/install/manual-install.md
script/setup

This adds support in `script/setup` for generating a local `general.yml` if it doesn't already exist and is run as the `vagrant` user. This is called from the `Vagrantfile` when using the FixMyStreet Vagrant box.
In addition, the addition of `:3000` to `BASE_URL` is only applied when not using the FixMyStreet box as this will be supplied in by the `setup` script in that case. This should also only be applied when not already present to prevent it being added repeatedly.

[Vagrant] Check and generate config file if necessary

---

perllib/FixMyStreet/Map/BathNES.pm
web/cobrands/bathnes/base.scss
web/cobrands/bathnes/js.js
web/cobrands/fixmystreet-uk-councils/roadworks.js

Add roadworks.org layer to Bathnes cobrand.
Also introduces ability to filter on which roadworks messages are shown.
Fixes mysociety/fixmystreet-freshdesk#17

Bathnes roadworks

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/Open311/PostServiceRequestUpdates.pm

Deal with possible multiple send_method_useds.

---

CHANGELOG.md
perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t

- Group wasn’t being set correctly by open311-populate-service-list as cobrand attribute
not being updated for each body.
- Extra metadata was being persisted to the DB every time even if nothing had changed,
causing lots of duplicate entries in contacts_history.

Fix Open311 category group bugs

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/admin/users.t
t/app/controller/around.t
t/app/controller/report_inspect.t
t/app/controller/report_new.t
t/app/controller/reports.t
templates/web/base/report/new/form_user_loggedin.html

Allows user's to see the inspector panel to mark reports as Private, and
also to view those non-public reports. Useful for call centre staff who
want to record private reports but don't need to other permissions.
Fixes mysociety/fixmystreet-commercial#1213

add report_mark_private permission

---

CHANGELOG.md
docs/customising/config.md
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Model/PhotoSet.pm
perllib/FixMyStreet/ImageMagick.pm
perllib/FixMyStreet/PhotoStorage/FileSystem.pm
t/app/controller/photo.t

This enforces server-side the current client-side restriction on maximum photo size, plus also allows an instance to state that we can symlink full size photos from the photo cache rather than copy them there. Plus makes the ImageMagick wrapper a lot neater :) Also fixes #2134

Photo storage updates

---

CHANGELOG.md
bin/update-schema
db/downgrade_0063---0062.sql
db/schema.sql
db/schema_0063-add-extra-to-moderation.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm
t/app/controller/moderate.t
web/cobrands/fixmystreet/staff.js

Some new things are allowed to be moderated (category, location, extra) but these weren't being stored in original data.
Question: should this be bigger and store a history of changes rather than just the original?

Store remaining original moderation data

---

.cypress/cypress/fixtures/highways.xml
.cypress/cypress/integration/highways.js
bin/browser-tests
perllib/FixMyStreet/SendReport.pm
perllib/FixMyStreet/SendReport/Email/Highways.pm
perllib/FixMyStreet/SendReport/Email/SingleBodyOnly.pm
t/app/controller/report_new.t
t/app/sendreport/email/highways.t
templates/web/bristol/footer_extra_js.html
templates/web/buckinghamshire/report/new/form_heading.html
templates/web/fixmystreet-uk-councils/footer_extra_js.html
templates/web/fixmystreet.com/footer_extra_js.html
templates/web/oxfordshire/footer_extra_js.html
web/cobrands/bristol/base.scss
web/cobrands/buckinghamshire/assets.js
web/cobrands/buckinghamshire/base.scss
web/cobrands/fixmystreet/assets.js
web/cobrands/highways/assets.js
web/cobrands/sass/_base.scss
web/js/map-fms.js

Includes an option to send to the council instead for e.g. reports on
underpasses or bridges.
Fixes #736
Also demonstrates how mysociety/fixmystreet-commercial#1191 can be done

send reports on highways agency roads to highways agency

---

.cypress/cypress/integration/staff.js
CHANGELOG.md
bin/fixmystreet.com/fixture
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/app/controller/admin/users.t
t/app/controller/report_as_other.t
t/app/controller/report_new.t
templates/web/base/report/new/category.html
templates/web/base/report/new/category_wrapper.html
templates/web/base/report/new/form_user_loggedin.html
web/cobrands/fixmystreet/staff.js

This adds `report_prefill` and `default_to_body` permissions for staff which split out some of the report_inspect behaviours into separate permissions.
Staff with the `report_prefill`/ permission will have the report title and detail auto populated with some default text.
Staff with the `default_to_body` permission will, assuming they also have the `can_contribute_as_body` permission, default to reporting new reports and updates as the body rather than themselves.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1218
Connects https://github.com/mysociety/fixmystreet-freshdesk/issues/23

more granular staff permissions

---

CHANGELOG.md
perllib/Open311/GetServiceRequests.pm

This should reduce the incidence of the ‘Problem id X for Y has an
invalid time, not creating’ cron errors we’ve been seeing.
See also mysociety/open311-adapter#26.

[Open311] Improve handling of created/updated datetimes of fetched reports

---

bin/handlemail
bin/handlemail-support

The EmailUtil library expects "\n" line endings, otherwise it gets confused. It also doesn't handle a different SMTP port, and so on. Fixes #2332.

Use standard email sending for handlemail.

---

CHANGELOG.md
bin/update-schema
db/downgrade_0064---0063.sql
db/downgrade_0065---0064.sql
db/schema.sql
db/schema_0064-allow-multiple-moderations.sql
db/schema_0065-add-moderation-admin-log.sql
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/ImageMagick.pm
perllib/FixMyStreet/Roles/Moderation.pm
t/app/controller/admin/search.t
t/app/controller/moderate.t
templates/email/default/problem-moderated.html
templates/email/default/problem-moderated.txt
templates/web/base/admin/list_updates.html
templates/web/base/admin/report_edit.html
templates/web/base/admin/update_edit.html

This allows moderation_original_data to store all moderation changes, and shows them on admin report /update page.
Fixes https://github.com/mysociety/keepitinthecommunity/issues/121

Store all moderation history

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js
web/js/map-OpenLayers.js

Clicking a pin twice on /around zooms in, and this PR ensures the back button and 'back to all reports' link zooms the map back to where you were initially.
Fixes #1649.

Restore zoom level when navigating back to /around from /report

---

bin/handlemail
docs/_layouts/page.html
docs/customising/handlemail.md

Fixes #2331. Fixes #2332. Fixes #2336.
I also added an option for specifying a separate destination for the bounces we'd like to have a look at. The default is still that the CONTACT_EMAIL address handles these, but it can be overridden (we want it to go to a separate mailbox for FixaMinGata). It could have been a new config parameter I suppose but I didn't want to clutter the config file for this. Let me know if you don't like it and I'll remove it or change it.

Adds cobrand support for handlemail.

---

web/js/map-OpenLayers.js

This handles not drawing a pin for a report with no location.
In KiitC cobrand, still need to add:
Connects https://github.com/mysociety/keepitinthecommunity/issues/96 [skip changelog]

don't draw a pin for a problem with no location

---

web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/assets.js

Adds new assets to Bucks integration as well as making the message when you select an asset a bit more specific based on the type of asset.
Fixes mysociety/fixmystreet-freshdesk#36

bucks additional assets

---

perllib/Open311/GetServiceRequestUpdates.pm

If we fail to match an update to a problem on the staging server then
print a warning so we can diagnose issues.

[Open311] warn on staging if fail to match updates

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Questionnaire.pm
t/app/controller/report_updates.t
templates/web/base/report/updates.html

Should fix #2357 (cc @joesiltberg).

Show reopening/fixed questionnaire responses lacking updates.

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/Open311/GetServiceRequests.pm
t/cobrand/bucks.t
t/open311/getservicerequests.t

Also adds some basic filtering of incoming report descriptions to remove emails and phone numbers.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/42

[Buckinghamshire] set incoming Bucks reports to non public

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/around.t
t/app/controller/reports.t
templates/web/base/reports/_list-filters.html

This adds an option on the reports screen to display only private reports.

add private only report filter

---

.cypress/cypress/integration/category_tests.js
bin/fixmystreet.com/fixture

Dropped Kerbs and Skips in a Licensing group.
Fixes mysociety/fixmystreet-commercial#1241

add extra categories to demo site

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm

Two separate small issues could combine to still show an already moderated photo on the front page:
1. The moderation was not clearing out the web cache of photos being moderated;
2. The code fetching the front page recent reports list from memcached checked they had not been hidden since they were cached, but wasn't checking whether they still had a photo (ie. moderated but report still present).

More clearing/checking of cached photos

---

bin/fixmystreet.com/fixture
templates/web/base/report/new/category_extras_fields.html

This also sneaks in the ability to set the type of extra field inputs so we can use the nice build in date picker for these fields.

Add start and end date extra fields to licensing categories for demo

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Roles/Abuser.pm
perllib/FixMyStreet/Script/Reports.pm

As perlsyn says, "NOTE: The behaviour of a `my`, `state`, or `our` modified with a statement modifier conditional or loop construct (for example, `my $x if ...`) is undefined. The value of the `my` variable may be `undef`, any previously assigned value, or possibly anything else."
Noticed because a call to `/ajax/closest` was returning the previous call's result (as `$j` was being "remembered" between function calls).

Remove any use of `my $x if $foo`.

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
t/app/controller/report_new.t
templates/web/oxfordshire/footer_extra_js.html
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js

Add in validation to check names, email and phone numbers don't exceed
maximum lengths permitted by HIAMS.
Fixes mysociety/fixmystreet-commercial#1244

[Oxfordshire] length checking for names, emails and phone Nos

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm
t/app/controller/moderate.t
templates/web/base/admin/report_edit.html
templates/web/base/report/update.html
templates/web/base/report/update/moderation.html
templates/web/base/report/update/moderation_diff.html
templates/web/base/report/update/moderation_meta.html

This adds moderation history, currently only shown on admin report edit page, to the front end report page if the user has moderation permission, interleaved with any normal updates/questionnaires to the report.

Moderation in front end updates

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Moderate.pm
t/app/controller/moderate.t

If a state is passed in (on a cobrand), update problem state and add a comment to record this (as state changes are updates not moderations).

Allow state editing via moderation.

---

bin/fixmystreet.com/buckinghamshire-flytipping
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/Warwickshire.pm
perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm
perllib/Open311/PopulateServiceList.pm
t/cobrand/bucks.t
t/cobrand/warwickshire.t
t/open311/populate-service-list.t
web/cobrands/buckinghamshire/assets.js

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/45
* Tidies up test file to not hard-code IDs, new test is at bottom.
* JS for showing/hiding extra question.
* Perl to get extra question into DB, not being pulled from Open311.
* Server side code to work out what to do if both bodies still given (question made mandatory in most cases, but not if district only).
* Script to auto close >3 weeks old district flytipping

[Buckinghamshire] Question for on-road flytipping.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Roles/Moderation.pm
t/app/controller/moderate.t
templates/web/base/report/_main.html
templates/web/base/report/update.html
web/cobrands/fixmystreet/staff.js

Two commits - the first stops the redirect on any error in moderation, doesn't commit changes to the db until the end, and tidies up the related code a bit; the second then adds a new error if it looks like the report has been edited since you started, reshowing the form (hopefully with all your changes still present, bit worried about that bit) and a link to the latest history (hooray that it's already being shown, made that easy at least).

Spot moderation conflicts

---

templates/web/fixmystreet-uk-councils/footer_extra_js.html
templates/web/oxfordshire/footer_extra_js.html

And load main assets script so highways script does not error. [skip changelog]
In mysociety/fixmystreet@0e8c7453c highways/assets.js was added to council footer JS, which assumes fixmystreet/assets.js is loaded which it isn't on all cobrands. I assume easiest fix is to also include fixmystreet/assets.js in line before highways/assets.js and have that load on all pages (and wrap it al in a `IF mappage` statement) but wanted someone to check/confirm that :)

[UK Councils] Only load map JavaScript on map pages.

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/BathNES.pm
templates/web/base/admin/extra-metadata-form.html
templates/web/base/common_header_tags.html
templates/web/base/common_scripts.html
web/cobrands/fixmystreet/admin.js

Also the automated setting was being dropped in the same scenario, as both selects had the wrong ID number. Fixes #2369.

Stop keys/values in category extra data "List" field lost when saving 

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
templates/web/base/report/new/category_extras_fields.html

Template Toolkit treats keys starting with ‘_’ as private and does not expose them. It is possible for an Open311 server to return fields starting with an underscore, and we want to use those in the template.

Allow Open311 codes starting with ‘_’ to function.

---

CHANGELOG.md
conf/general.yml-docker
conf/general.yml-example
docs/customising/config.md
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm

Add a configuration variable to use for the front page stats/ recent list, plus the max-age of `/reports`. Fixes #2375.

Make front page cache time configurable.

---

CHANGELOG.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t
templates/web/fixmystreet.com/report/new/unresponsive_body.html

Similarly to 1f69e28c, we were previously only checking the first matching entry, which led to confusing behaviour in places. Include consequential amendments for e.g. one body being unresponsive, the other not.

[fixmystreet.com] Improve two-tier unresponsive.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t
templates/web/bromley/admin/category-checkboxes.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1271

[Bromley] Store service_sub_code as subcategory.

---

CHANGELOG.md
web/js/map-OpenLayers.js

The behaviour should be the same whether “Show older” or “Show older reports” is clicked, but only the latter was updating the URL. Fixes #2397.

Add parameter to URL when “Show older” clicked.

---

CHANGELOG.md
t/app/controller/alert_new.t
templates/web/base/report/display_tools.html

The “Get updates” flow on a report page, if logged in, was showing an input label but no input field (because one is not needed), but then on submission asking for your email address. Add missing name on submit button to fix this.

Don't ask for email on alert signup if logged in.

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/Cobrand/FixaMinGata.pm
perllib/FixMyStreet/DB/Result/Body.pm
perllib/FixMyStreet/Script/UpdateAllReports.pm

This adds an optional threshold so that a body with very few fixed reports don't end up in the top 5 list under /reports.
I haven't tested the change in App/Controller/Dashboard.pm, am I supposed to be able to see the responsiveness somewhere under /dashboard? Or should I look somewhere else?
Fixes #1957

[FixaMinGata] Adds a cobrand hook (threshold for responsiveness top 5 list)

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/dashboard.t
t/cobrand/bathnes.t
t/cobrand/bucks.t
t/cobrand/fixmystreet.t

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/49

[Buckinghamshire] Add contributed_by to CSV export

---

perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
t/cobrand/bromley.t
templates/web/bromley/about/heatmap-list.html
templates/web/bromley/about/heatmap.html
templates/web/bromley/footer_extra_js.html
web/cobrands/bromley/HeatmapLayer.js
web/cobrands/bromley/_colours.scss
web/cobrands/bromley/base.scss
web/cobrands/bromley/js.js
web/cobrands/sass/_base.scss
web/js/map-OpenLayers.js

* Toggleable heatmap
* Ward and date filters
* Access to Bromley special subcategories (Open311 attribute)
* Will default to user's wards/categories
* Sidebar latest/oldest
* Client-side pin loading by default, like /around
TODO:
[skip changelog] Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1267

[Bromley] Heatmap

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/app/controller/report_new.t
t/cobrand/bromley.t
templates/web/base/maps/pin.html
templates/web/base/report/_item.html
templates/web/base/report/_item_expandable.html
templates/web/base/tokens/confirm_problem.html
templates/web/zurich/tokens/confirm_problem.html

On some UK council cobrands, some reports listed might not have been sent
to that council, so links to those must go to the national site. However,
using absolute URLs for all these reports means that sometimes you change
domain when you don't need to (eg. if you’re on osm.fixmystreet.com or an
aliased version of the site), which can cause confusion. State when we’re
happy to use a relative link (ie. web-facing report links, not emails, or
share links) and do that when we can.
Fixes #1995. Connects https://github.com/mysociety/fixmystreet-commercial/issues/1277

Use relative report links where possible.

---

CHANGELOG.md
templates/web/base/admin/users/form.html
templates/web/base/questionnaire/creator_fixed.html
web/cobrands/sass/_base.scss
web/cobrands/zurich/base.scss

Reduce the space between checkbox and label, so the text isn't lost if the page is zoomed in. Fixes #2411.
Replace the creator_fixed question with segmented control to match the full questionnaire, and the admin verified checkboxes with inline-text as they need no padding. Having done that, all uses of .inline are now on their own lines, so no post-padding is needed any longer, but we’ll leave some in case of future use.

Improve inline checkbox spacing.

---

web/js/duplicates.js

The form may be brought in via JS, so we have to add an event to something that will always be there (or alternatively set up when pulled in, which was the old pre-duplicates.js behaviour). [skip changelog]

Listen for all inspector form duplicate events.

---

CHANGELOG.md
perllib/FixMyStreet/DB/RABXColumn.pm
t/open311/populate-service-list.t

Without doing this, a call to e.g. `$contact->set_extra_fields(@meta)` in PopulateServiceList.pm, with an unchanged meta that contains some Unicode values, can write to the database (and cause an unneeded row in the history table), because the column from the database is UTF-8 decoded, whilst the new text is UTF-8 encoded.
It looks like an attempt was made in filter_from_storage to fix this issue, but the column comparison for marking a column as dirty takes place without this being called.

Make sure raw RABX column is utf8-encoded.

---

CHANGELOG.md
perllib/FixMyStreet/DB/RABXColumn.pm
perllib/FixMyStreet/DB/Result/Contact.pm
t/open311/populate-service-list.t

Otherwise any such fields are lost upon a manual edit.

Show all Open311 extra fields in edit admin.

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm

Remove the config that stopped us sending easting/northing if the user
had not clicked the map.

[Oxfordshire] always send easting/northing over open311

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

If an update has a fixmystreet_id field then use the contents of that in
preference to the external_id field to match an update to a problem.
This handles the case where a report in a third party system passes
through different types (eg inspection and defect), resulting in the
external id changing. In this case it is sometimes possible to include
the fixmystreet id in each type and hence use that to match things up at
the fixmystreet side.

[open311] optionally use fixmystreet_id to match update to problem

---

perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
t/cobrand/bucks.t

Bucks want drainage reports sent via email as well as Confirm.
Includes a slight refactor of `Buckinghamshire::open311_post_send` to allow multiple categories to be sent via email once they've been sent to Confirm.
Fixes mysociety/fixmystreet-commercial#1306

[Buckinghamshire] Send drainage reports via email as well as Open311

---

web/cobrands/oxfordshire/assets.js

This makes sure that we re-enable the report form if you select a non
OCC category after selecting PRoW, and also enables correct hiding and
displaying of the message.

[Oxfordshire] correctly display PRoW message

---

perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm

Previously if no reports were closed with an email this meant that the
lang setup never ran and you got an error when _ was called in
close_problems. So, we call the lang setup in close_problems too.

make sure the archive report script sets up lang etc

---

CHANGELOG.md
templates/web/base/report/new/category.html
web/cobrands/fixmystreet/fixmystreet.js

* Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1307 (Allow things to reset if "Pick a category" picked. This is most noticable with category groups, where changing the parent would leave visible any asset/attribute questions.)
* If you had one filter category selected, clicked the map (category auto pre-selected), changed the category, and clicked the map again, it would re-select the filter category, not the changed category.
* Previously, when update_pin was called, category change events were fired: 1. if category wasn't blank, 2. if category groups were enabled, and 3. if category groups were enabled, a group was selected, and a category was not.
* If the site only has the one category, it was being preselected but the extra attribute questions were not being …

A tidy up of some category change bugs

---

perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Lincolnshire.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/controller/report_as_other.t
t/app/model/problem.t
t/cobrand/bucks.t
templates/email/buckinghamshire/other-reported.html
templates/email/buckinghamshire/other-reported.txt
templates/email/default/other-reported.html
templates/email/default/other-reported.txt
templates/email/fixamingata/other-reported.html
templates/email/fixamingata/other-reported.txt
templates/email/fixmystreet.com/_council_reference.html
templates/email/fixmystreet.com/_council_reference.txt
templates/email/fixmystreet.com/confirm_report_sent.html
templates/email/fixmystreet.com/confirm_report_sent.txt

And fix bug where two-tier message not appearing in confirm sent email.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1273 [skip changelog]

[BANES,Bucks,Lincs] Include reference in .com confirm sent email

---

templates/web/fixmystreet.com/report/new/roads_message.html
templates/web/northamptonshire/report/new/roads_message.html
web/cobrands/northamptonshire/assets.js

Prevent users from making report unless they have selected an asset from the map.

[Northamptonshire] prevent report submission without asset selection

---

docs/community/index.md
docs/how-it-works.md
docs/index.md
docs/install/index.md
docs/overview.md
docs/running/admin_manual.md

Removes the mySociety international email address from the documentation, making the Google Group the main focus for email-based interaction.

[fixmystreet.org] docs update

---

web/cobrands/northamptonshire/assets.js

Ncc layer issues

---

web/cobrands/fixmystreet/assets.js

Layers that are always visible mean that we can end up with a count of 1
which means we don't re-display the pin

ignore always_visible layers in layer visibility change

---

web/cobrands/fixmystreet-uk-councils/alloy.js
web/cobrands/northamptonshire/assets.js

The tile URL includes a parameter for the client number which we were
not using so configure this based on live or staging.

[Northamptonshire] use the correct layer environment for assets

---

perllib/FixMyStreet/Cobrand/Northamptonshire.pm
t/Mock/MapIt.pm
t/app/controller/report_new.t
templates/web/base/js/translation_strings.html
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js
web/cobrands/fixmystreet/fixmystreet.js

Prevent people from using very long titles.
Fixes mysociety/fixmystreet-commercial#1344

[Northamptonshire] restrict title to 120 characters

---

perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

If an update has a fixmystreet id in it check that it looks like an
integer and if not issue a warning and skip the update.

[Open311] handle bad FixMyStreet id in updates

---

web/cobrands/fixmystreet-uk-councils/alloy.js

Call newRequest directly rather than with an event to avoid resetting
all the layers that have been used and hence removing all the features.
Fixes mysociety/fixmystreet-commercial#1354

[Northamptonshire] only clear current layer on reload

---

web/cobrands/fixmystreet-uk-councils/roadworks.js
web/cobrands/lincolnshire/assets.js
web/cobrands/lincolnshire/roadworks.js

Also displays the structures asset layer for the correct categories.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/48

[Lincolnshire] Show roadworks.org responsible party

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
t/app/controller/admin/templates.t
templates/web/base/admin/template_edit.html
templates/web/zurich/admin/template_edit.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1364

Prevent creation of two templates with same title.

---

templates/web/base/admin/report_edit.html
web/cobrands/sass/_admin.scss

Rather than having to go into the database to see any error details
display it in the admin. The error only shows the first few lines by
default and expands on hover.

show open311 failure details in admin report edit page

---

web/cobrands/buckinghamshire/assets.js

Allows assets to display when zoomed in.
Remove very zoomed out views as not useful.

[Buckinghamshire] fix zoom level issues

---

templates/web/base/report/new/category_wrapper.html
web/cobrands/bexley/js.js
web/cobrands/fixmystreet/assets.js

This changes which categories display which assets, and shows the asset ID on the pin/sidebar.

Bexley changes

---

.cypress/cypress/integration/regressions.js
CHANGELOG.md
bin/fixmystreet.com/fixture
perllib/FixMyStreet/DB/Factories.pm
web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/fixmystreet.js

A few bits weren't being correctly hidden, as the code didn't account for someone going directly from a report page to a reporting page via the Report another problem here button.
Also Bucks spot fix, and spotted Unicode issue with fixture.

Fix bug going between report/new pages client side.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/Open311/GetServiceRequests.pm
perllib/Open311/PopulateServiceList.pm
t/app/controller/around.t
t/open311/getservicerequests.t
t/open311/populate-service-list.t
templates/email/default/login.html

A few small things that have come from the Hounslow cobrand work.
- Support `<keywords>private</keywords>` in Open311 service definitions to mark that contact as non_public
- Ensure non_public reports aren't included in results when searching by ref from front page
- Ensure reports fetched via Open311 are marked private if the category they're in is also marked private. NB this situation shouldn't arise through normal use, it's just a belt-and-braces check that we don't expose things that shouldn't be public.

Small improvements from Hounslow branch

---

.travis.yml
perllib/FixMyStreet/TestMech.pm
t/app/01app.t
t/app/controller/about.t
t/app/model/alert_type.t
t/app/model/state.t
t/i18n.t
t/open311/getupdates.t

[skip changelog] A few i18n tests have been failing locally for a while, and I've been unable to track down the exact cause. For the sake of having green tests again I've added `skip`s around the failing tests.
```bash
$ perl -V
Summary of my perl5 (revision 5 version 28 subversion 1) configuration:
Platform:
osname=darwin
osvers=18.2.0
archname=darwin-thread-multi-2level
uname='darwin mojave.local 18.2.0 darwin kernel version 18.2.0: mon nov 12 20:24:46 pst 2018; root:xnu-4903.231.4~2release_x86_64 x86_64 '
config_args='-des -Dprefix=/usr/local/Cellar/perl/5.28.1 -Dprivlib=/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1 -Dsitelib=/usr/local/Cellar/perl/5.28.1/lib/perl5/site_perl/5.28.1 -Dotherlibdirs=/usr/local/lib/perl5/site_perl/5.28.1 -Dperlpath=/usr/local/opt/perl/bin/perl …
```

Skip tests causing locale-related failures on macOS

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new.t

Not all cobrands have a council_name method.

make sure council_name exists before trying to call it

---

perllib/FixMyStreet/Cobrand/Hounslow.pm
t/cobrand/hounslow.t

Hounslow has requested that any report made on FixMyStreet before their cobrand launched should not be visible at all on the cobrand.

[Hounslow] Hide all reports made before go-live entirely

---

perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Borsetshire.pm
perllib/FixMyStreet/Cobrand/Bristol.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/EastHerts.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/Cobrand/Hart.pm
perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/Cobrand/Lincolnshire.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/Rutland.pm
perllib/FixMyStreet/Cobrand/Stevenage.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/Cobrand/Warwickshire.pm
t/cobrand/bexley.t

This moves four options from code to config, which would make it easier to change any of them in future (for these, perhaps unlikely, but still). This change would necessitate the following being done in the server config:
```
contact_name:
bromley: 'Bromley Council (do not reply)'
hart: 'Hart District Council (do not reply)'
warwickshire: 'Warwickshire County Council (do not reply)'
contact_email:
[...]
example_places:
bathnes: [  'BA1 1JQ', "Lansdown Grove" ]
bexley: [ 'DA6 7AT', "Chieveley Road" ]
borsetshire: [ 'BS36 2NS', 'Coalpit Heath' ]
bristol: [ 'BS1 5TR', "Broad Quay" ]
bromley: [ 'BR1 3UH', 'Glebe Rd, Bromley' ]
buckinghamshire: [ 'HP19 7QF', "Walton Road" ]
eastherts: [ 'SG14 2AP', "Mangrove Road" ]
greenwich: [ 'SE18 6HQ', "Woolwich Road" ]
hart: [ 'GU51 …
```

[UK] Put some things in config

---

perllib/Open311.pm
t/app/controller/contact_enquiry.t

This was previously done automatically, but isn’t when you do file uploads.
Looks like Open311 file uploading isn't tested at all, so don't have a regression test, will add some testing later today.

[Open311] Make sure Open311 parameters are encoded

---

web/cobrands/northamptonshire/assets.js

Not all assets on the right of way are recorded so give the option to
select a point on the right of way network instead of a point asset.
Fixes mysociety/fixmystreet-freshdesk#61

[Northamptonshire] display right of way network for categories

---

CHANGELOG.md
bin/browser-tests
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Borsetshire.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Lincolnshire.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/Open311/PopulateServiceList.pm
t/app/controller/admin/bodies.t
t/app/controller/report_new.t
t/open311/populate-service-list.t
templates/web/base/admin/bodies/contact-form.html
web/cobrands/fixmystreet/admin.js

The group metadata of a contact can now be a comma separated list of
groups under which to display the category
For #2475

display category under multiple groups

---

web/cobrands/bristol/assets.js

Add a message to various categories on the national site asking people
to use a separate Bristol site to make reports.

[Bristol] redirect national site categories

---

CHANGELOG.md
bin/browser-tests

Noticed this week that it’s not been possible to run the cypress browser tests when you have FMS running an a Vagrant VM (and the tests running outside on the host) since the FMS Vagrant config was changed to use an FMS-specific box.
@dracos and I changed a couple of things to get it working again. I think this was all of it?

Fix frontend testing when done with vagrant

---

templates/web/bromley/before_wrapper.html
templates/web/bromley/report/new/top_message.html
web/cobrands/bromley/base.scss

Adds a temporary banner to Bromley for the upcoming maintenance window.
For https://github.com/mysociety/fixmystreet-freshdesk/issues/65

[Bromley] Add temporary maintenance banner

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

Be able to personalise the email so admins can add the reporter's name to the email .
Include the email template that is stored in FixMyStreet as well as the update that is pulled from the council integration.

 [Open311] Allow desc in email template with tokens.

---

CHANGELOG.md
perllib/FixMyStreet/SendReport.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/FixMyStreet/SendReport/Email/SingleBodyOnly.pm
perllib/FixMyStreet/SendReport/Open311.pm
perllib/FixMyStreet/SendReport/Zurich.pm
t/app/sendreport/email/highways.t
t/app/sendreport/email/tfl.t
t/sendreport/open311.t

It is possible that the category of a report no longer exists and in
that case the Open311 send process was falling over. This checks that
we've found a contact and if not sets the error and skips the report.

better error if category for report does not exist

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/app/controller/contact_enquiry.t
t/cobrand/bexley.t
web/cobrands/bexley/js.js

This makes the server-side check behave as the client-side, doing nearest-point-on-line checks rather than only nearest point *of* line checks.

[UK] Improve server-side nearest road lookup

---

CHANGELOG.md
templates/email/default/_email_comment_list.html
templates/email/default/_email_report_list.html

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/66

Maintain formatting in email report/update lists.

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm
t/cobrand/isleofwight.t
templates/web/base/report/update-form-wrapper.html
templates/web/base/report/update-form.html
templates/web/isleofwight/report/_updates_disallowed_message.html

Shut down comments on reports that have been closed.
Only allow the original reporter to comment on reports.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1409
Fixes mysociety/fixmystreet-commercial#1412
Fixes mysociety/fixmystreet-commercial#1414

Island roads comments changes

---

CHANGELOG.md
web/cobrands/bathnes/base.scss
web/cobrands/bexley/_colours.scss
web/cobrands/bexley/base.scss
web/cobrands/bristol/_colours.scss
web/cobrands/bristol/base.scss
web/cobrands/bromley/_colours.scss
web/cobrands/bromley/base.scss
web/cobrands/buckinghamshire/_colours.scss
web/cobrands/buckinghamshire/base.scss
web/cobrands/hart/_colours.scss
web/cobrands/hart/base.scss
web/cobrands/lincolnshire/_colours.scss
web/cobrands/lincolnshire/base.scss
web/cobrands/northamptonshire/_colours.scss
web/cobrands/northamptonshire/base.scss
web/cobrands/oxfordshire/_colours.scss
web/cobrands/oxfordshire/base.scss
web/cobrands/sass/_base.scss
web/cobrands/sass/_dropzone.scss
web/cobrands/zurich/_colours.scss
web/cobrands/zurich/_zurich.scss

Spotted by @dracos.
I took the opportunity to turn the default link colour / decoration styles into variables, so they’re easier for cobrands to customise without having to redefine their own `a, a:hover, a:active…` rules.
I’ve upgraded every cobrand I could find using its own overrides (via a search for lines beginning with `a,` or `a {` in `.scss` files) to instead now use the defaults or their own variables. I’m sure I‘ll have missed some though.

Darker default link colour

---

web/cobrands/buckinghamshire/assets.js

The server renames asset_no to feature_id, so that can be used instead, no need for extra code.
Depends upon https://github.com/mysociety/fixmystreet.com/pull/3 being done at the same time.

[Bucks] Remove unneeded alt streetlight code.

---

.cypress/cypress/integration/hounslow.js
CHANGELOG.md
bin/browser-tests
bin/fixmystreet.com/fixture
perllib/FixMyStreet/App/Controller/Report/New.pm
t/Mock/MapIt.pm
t/app/controller/report_new.t
templates/web/base/report/new/councils_text_all.html
templates/web/base/report/new/form_report.html
templates/web/hounslow/report/new/councils_text_all.html
templates/web/oxfordshire/report/new/councils_text_all.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/hounslow/js.js
web/cobrands/sass/_base.scss

This makes it clearer that all details for a report made in a private category will not be shown publicly.
Fixes mysociety/fixmystreet-commercial#1405

Update UI text when selecting a private category

---

templates/email/default/problem-confirm.html
templates/email/default/problem-confirm.txt
templates/email/hounslow/problem-confirm.html
templates/email/hounslow/problem-confirm.txt

Another instance of the borough council being mentioned where it shouldn't be. Also fixes some misleading text indicating that a private report would be published when in reality it wouldn't.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/71

[Hounslow] Use ‘Hounslow Highways’ in report confirmation emails

---

CHANGELOG.md
bin/update-schema
cpanfile
cpanfile.snapshot
db/downgrade_0068---0067.sql
db/schema.sql
db/schema_0068-oidc_login.sql
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Social.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/OIDC/Lite/Client/IDTokenResponseParser.pm
perllib/OIDC/Lite/Client/WebServer/Azure.pm
t/Mock/OpenIDConnect.pm
t/app/controller/auth_social.t
t/app/model/user.t
t/cobrand/westminster.t
templates/web/base/auth/general.html
templates/web/base/report/form/user.html
templates/web/westminster/auth/general.html
templates/web/westminster/report/form/user.html
web/cobrands/fixmystreet/fixmystreet.js

Extends social login functionality to authenticate against an (MS Active Directory B2C-specific) OpenID Connect identity provider.

[Westminster] Add OpenID Connect single sign-on support

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/DB/ResultSet/Contact.pm
t/cobrand/bexley.t

I thought about doing it in all cobrands with category groups, but B&NES fetch their CSV file programmatically, so I don't know if they'd handle that or not. (Also they have the option of multiple groups for one category, so might not make sense for them.) So this inserts it just after Category in the export, for Bexley only. I don't know if any others do manual exports; alternatively we could add it to all that have groups and don't have multiple-groups-per-category, meh.

[Bexley] Include subcategory in dashboard export.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/Contact.pm
t/app/controller/report_new_open311.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1456

Do not store display-only extra fields on reports.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Open311.pm
perllib/FixMyStreet/App/Controller/Open311/Updates.pm
perllib/Open311/GetServiceRequestUpdates.pm
t/app/controller/open311.t
t/app/controller/open311_updates.t
t/open311/getservicerequestupdates.t

This adds a counterpoint to GetServiceRequestUpdates call, allowing Open311 endpoints to POST updates to FixMyStreet, rather than having them fetched from the endpoint.
It tries to reuse GetServiceRequestUpdates code, which was first refactored to split out a giant loop into functions. In the end, ignoring boilerplate and fetching parameters etc, the actual new code boils down to: find problem, check comment doesn't already exist, process update, format output.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1396

Receive updates over Open311

---

perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/cobrand/isleofwight.t

The area name does not match the council name so it redirects to the
national site, so check for the all_reports_single_body and use that as
the matching instead.

[IsleOfWight] fix all reports link

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Social.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
perllib/Open311.pm
t/Mock/OpenIDConnect.pm
t/app/controller/auth_social.t
t/open311.t

A few improvements around Westminster single sign-on:
- Store user's MyWestminster CRM ID in user extra and include it as the `account_id` param when posting reports over Open311
- Log out of MyWestminster when logging out of FMS by redirecting to the appropriate URI

[Westminster] SSO logout support & send CRM ID with Open311 reports

---

CHANGELOG.md
perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

If an update with a blank external_status_code is fetched then unset it
otherwise we will always a detect a change in the external_status_code
which might mean phantom updates.

unset the external_status_code if blank

---

CHANGELOG.md
t/app/controller/index.t
templates/web/base/around/_error_multiple.html
templates/web/base/around/display_location.html
templates/web/base/around/postcode_form.html
templates/web/base/reports/_list-filters.html
templates/web/oxfordshire/around/postcode_form.html
web/cobrands/fixmystreet/fixmystreet.js

Adds `filter_group` and `filter_category` parameters to the front page URL which are carried through to filter the map on `/around` and pre-fill the appropriate fields on the new report form.

Enable pre-filling of report form group/category from front page

---

CHANGELOG.md
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_new.t
templates/web/base/js/translation_strings.html
templates/web/base/report/new/form_title.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/validation_rules.js

Some browsers seem to be autocompleting title with the user's email
address so try turning this off to see if it helps.

set autocomplete to off for report title

---

templates/web/base/admin/users/index.html

The error was due to CSRF token not being included in the page when filtering by role, but this approach is consistent with existing behaviour when searching.
Fixes mysociety/fixmystreet-commercial#1485

Disable ‘add user’ form on admin user search when role selected

---

perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/cobrand/westminster.t

Adds server-side USRN lookup for Westminster reports made via the app (or any which don't already have a USRN for whatever reason).
For https://github.com/mysociety/fixmystreet-commercial/issues/1471

[Westminster] USRN lookup

---

perllib/FixMyStreet/App/Controller/Admin/Users.pm
t/app/controller/admin/users.t

Certain edits to a user (e.g. unsetting `from_body`, editing email address) might result in that user not being visible in the current cobrand any more. This PR fixes a 404 error by redirecting back to the user list after such an edit, instead of to the user profile page.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1486.

Redirect correctly after editing user to remove them from cobrand

---

.cypress/cypress/integration/regressions.js
.cypress/cypress/integration/simple_spec.js
.cypress/cypress/integration/staff.js
CHANGELOG.md
bin/browser-tests
perllib/FixMyStreet/App/Controller/Test.pm
t/Mock/MapIt.pm
t/app/controller/report_import.t
t/app/controller/report_new_open311.t
templates/web/base/report/new/duplicate_suggestions.html
web/cobrands/fixmystreet/fixmystreet.js
web/js/duplicates.js

Hide category extras when duplicate suggestions shown; conversely hide duplicate suggestions when signing in during reporting. Also retain extra data when signing in during reporting.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1481
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1482
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1483

Fix some reporting interaction bugs

---

CHANGELOG.md
web/cobrands/bexley/js.js
web/cobrands/bromley/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js
web/js/duplicates.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1480

Have duplicate suggestion and assets coexist better

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/auth_social.t
templates/web/base/report/new/category.html

If you come to /report/new with a part-filled report (say you've gone
via an OAuth flow), then the stash needs to get the category from the
report, not a query parameter, and report_meta needs initializing, as
that is what the template uses to fill in existing attribute answers.
Hopefully really fixes https://github.com/mysociety/fixmystreet-commercial/issues/1482 this time.

Make sure existing attribute answers set up.

---

templates/web/base/report/new/login_success_form.html
templates/web/base/report/new/oauth_email_form.html

If the user has logged in as part of making the report, it's easy to overlook the ‘Submit’ button in the middle of the form when scrolling. This PR adds a second ‘Submit’ button right at the bottom of the page.

Include ‘submit’ button at very bottom of report form when signing in during report

---

perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/cobrand/bucks.t
t/cobrand/westminster.t
web/cobrands/westminster/assets.js

Makes it easier to handle more than one call to `lookup_site_code` for a single report, and looks up the UPRN for reports that have that field in their report extras but not a value. Also restores the frontend UPRN lookup for bins, after the field was renamed.
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1471

[Westminster] UPRN lookup

---

perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/App/Controller/Auth/Social.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
perllib/FixMyStreet/SendReport/Open311.pm
perllib/Open311.pm
t/app/controller/auth_social.t
templates/web/base/my/my.html
web/cobrands/westminster/assets.js
web/cobrands/westminster/base.scss

- Replace ‘gully’ with ‘drain’ in asset UI ([Basecamp](https://3.basecamp.com/4020879/buckets/12002933/todos/1972169811))
- ~Upload all photos over Open311~ ([Basecamp](https://3.basecamp.com/4020879/buckets/12002933/messages/1969231294)) (supporting code is included in this PR, but not enabled for the Westminster cobrand)
- Hide 'change password' & 'change email' links on `/my` ([Basecamp](https://3.basecamp.com/4020879/buckets/12002933/messages/1945441618#__recording_1978717754))
- Remove TfL categories ([Basecamp](https://3.basecamp.com/4020879/buckets/12002933/todos/1978021687))
- Show 3 months on `/around` by default ([Basecamp](https://3.basecamp.com/4020879/buckets/12002933/messages/1939205134#__recording_1974850946))

[Westminster] Some small changes

---

CHANGELOG.md
t/app/controller/report_display.t
templates/web/base/main_nav_items.html
templates/web/bexley/main_nav_items.html
templates/web/hounslow/main_nav_items.html

Adds a check to the template that generates the 'report another problem here' link to stop that link being generated if the report is `non_public`.

Don’t reveal private report lat/lon in ‘report another’ link

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_open311.t
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/councils_text_all.html
templates/web/hounslow/report/new/councils_text_all.html
templates/web/isleofwight/report/new/councils_text_all.html

#2574 broke non-JS display of the body name (added testing line to show that) because `display_names` did not exist in that case. The template only needs one variable, so tried to tidy this up a bit, and then did the same to councils_text_all which meant the Hounslow/IsleOfWight override templates for them can be removed.

Fix category_extras using correct cobrand name

---

perllib/FixMyStreet/App/Controller/Auth.pm

https://github.com/mysociety/fixmystreet-mobile/pull/275 should fix it in the app, but I thought we should do something for those who don't upgrade, perhaps?

Always return a name string if login successful.

---

web/cobrands/bristol/assets.js

[Bristol] add flooding assets

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/App/Controller/Develop.pm
perllib/FixMyStreet/DB/Result/User.pm
t/app/controller/contact.t
templates/email/default/_email_settings.html
templates/email/default/contact.html
templates/email/default/contact.txt

It’s common for people to send contact form messages about their most recent report (usually they’ve included personal details and want them removed) but without actually linking to the report, or using the well hidden "Unsuitable?" link on the report page.
So the person handling the support email for that site has to go manually searching for the user’s profile, or their most recent report, in the admin interface.
After doing this for what seemed like the thousandth time this morning, I figured it’s time to get FMS to do the hard work for me, generating links to the user’s profile page, list of reports, and latest report, if a matching user (and report) is found in the database:
It also improves the `/_dev/email/contact` email preview endpoint, to show some dummy content, just like the …

Contact email admin improvements

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_anon.t

There was a small bug where the 'default_to_body' permission would
override the 'report anonymously' button when staff users were adding
reports to the site. The result of this was that the name of the
anonymous user record would be shown. No harm done, as that user's name
would likely be set to "Anonymous user" in config, but it resulted in
reports pages showing the slightly odd wording along the lines of:
> Reported in the Bin bags category by Anonymous user at 14:57 today
This commit ensures the contributing_as_body flag is mutually exclusive
with the 'report_anonymously' request parameter.

Make sure anonymous reports are marked anon irrespective of permissions

---

templates/web/base/alert/index.html
templates/web/base/around/postcode_form.html
templates/web/fixmystreet.com/about/faq-en-gb.html
templates/web/oxfordshire/around/postcode_form.html

For https://github.com/mysociety/fixmystreet-commercial/issues/1496

Change ‘locate me automatically’ to ‘use my location’

---

CHANGELOG.md
bin/fixmystreet.com/fixture
bin/fixmystreet.com/one-off-move-js-messages-to-db
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/admin/reportextrafields.t
t/app/controller/report_new_open311.t
templates/web/base/admin/extra-metadata-form.html
templates/web/fixmystreet.com/footer_extra_js.html
templates/web/oxfordshire/footer_extra_js.html
web/cobrands/bexley/js.js
web/cobrands/bristol/assets.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/admin.js
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/northamptonshire/assets.js
web/cobrands/oxfordshire/assets.js

This replaces the cobrand-JS-specific way of adding messages that disable the report form with a new 'disable form' tickbox in the admin.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1515

Add 'disable_form' flag to category extras

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/cobrand/councils.t
t/cobrand/westminster.t
templates/web/base/report/_updates_disallowed_message.html

A cobrand feature flag can be used to only allow updates on open
reports, by the original reporter, to staff only, or to no-one.

[UK Councils] Config specifying of update closure.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
t/app/controller/admin/bodies.t

If a body was set to Open311, and a contact set to Email, it was
impossible to unset the contact's send method and set an Open311
code, because it would always demaned a valid email address.

Allow contact send method to be unset always.

---

perllib/FixMyStreet/App/Controller/Report/New.pm
web/cobrands/fixmystreet/assets.js
web/cobrands/westminster/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1543
I realise with this fix the stopper code is run more times than seems necessary (e.g. on a map pin click, checkFeature is called immediately, then when category data comes back, that will lead to a category change event firing, so it'll get called again, plus the stopper code runs in its own right on category change anyway) but given we don't know when/where data will be available, that seems safest, if a bit hmm. The stopper code doesn't do very much, at least.
Also due to the above, picking the roads category on Westminster will show the disabled bit before the TfL data comes back at which point the form comes back. I couldn't think of an easy fix except somehow telling the stopper code that it should wait for layer …

Asset code ordering issues

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_new_open311.t
t/app/model/problem.t
templates/web/base/report/form/user_loggedout_by_email.html
templates/web/base/report/form/user_loggedout_email.html
templates/web/base/report/form/user_loggedout_password.html
templates/web/base/report/new/category_extras_fields.html
templates/web/base/report/new/category_wrapper.html
templates/web/base/report/new/form_report.html
templates/web/base/report/new/form_title.html
templates/web/base/report/new/form_user.html
templates/web/bromley/report/form/user_loggedout_email.html

This improves the reporting journey to only ask for category, and then category extra questions if appropriate, first, so that if the choice would lead to the form being disabled, this can be shown immediately.

 Improve user flow when JavaScript is not available

---

perllib/FixMyStreet/Map/UKCouncilWMTS.pm
t/cobrand/bristol.t

If the coordinates are (0,0) then return that straight back as trying to
reproject causes Geography::NationalGrid::GB to fall over as 0 lat is
outside UK
Fixes #2617 [skip changelog]

do not reproject uk wmts map if no coordinates

---

perllib/FixMyStreet/App/Controller/Contact.pm
t/cobrand/bathnes.t

The request cobrand is set on the schema during the app's `setup_request()`, which is called by the root `auto` action. So anything in a controller's `begin` action (such as user permission for rejecting reports) will access an incorrect cobrand (if one has already been set).

Make sure determine_contact_type called later.

---

perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/SendReport/Open311.pm

Switches to using `open311_pre_send` for the Hounslow enquiries inbox, in order to ensure any Confirm unavailability doesn't stop new report emails being delivered.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/84

[Hounslow] Send report to inbox before Open311 send, not after

---

perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/SendReport/Open311.pm
t/sendreport/open311.t

Adjusts the mechanism introduced in 5bf5c08a3a25c91866ce478f01fc6c4ad9d25eb6 to send the enquiries inbox email after the first Open311 send attempt, not before. This ensures if the Open311 send was successful the enquiry ID will be included, and if it fails the email isn't delayed.

[Hounslow] Send report to inbox after first Open311 send attempt

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm

This gives much better results for e.g Hight Street and also handle Rd
versus Road better.

[IsleOfWight] swap to use OSM geocoder

---

perllib/FixMyStreet/App/Controller/Report/New.pm

When an open311 category has multiple groups it puts them in the groups
element using CSV escaping. This means that group names can sometimes
feature double quotes. If we send these to the front end then putting
them into the optgroup name attribute breaks the HTML as if the group
name is in the database as `"group name"` you end up with
<optgroup name="" group="" name="">
instead of
<optgroup name="group name">
Hence, stripping the double quotes.

strip quote from contact group names

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/Open311.pm
perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t
templates/web/base/admin/bodies/contact-form.html

Companion to https://github.com/mysociety/open311-adapter/pull/59 to read in `groups` when given, rather than parse a single entry as CSV (which doesn't then need to be used anywhere, I think).
This means we can drop all the enable multiple groups stuff to deal with comma edge cases, and let anyone have multiple groups if they should want to without worrying about it.

[Open311] Spot new <groups> parameter rather than use CSV.

---

perllib/FixMyStreet/Cobrand/Hounslow.pm
templates/web/hounslow/footer_extra_js.html
web/cobrands/fixmystreet-uk-councils/council_validation_rules.js

This was missed from the initial cobrand.

[Hounslow] Use Confirm validation rules for reports

---

bin/fixmystreet.com/island_roads_setup_messages

One off script that adds an question to each Triage category to ask if
the problem is urgent or not. Sets urgent answer to block form
submission.

[IsleOfWight] script to add emergency categories

---

templates/web/base/admin/index.html
web/cobrands/sass/_admin.scss
web/cobrands/sass/_base.scss

Fixes a bug that was introduced by 6ac0633d87da551f25c3d7d4cf2c902acf2a9e51, I think.
[skip changelog] because this is just fixing a bug in a feature that’s still in the "unreleased" section.

Restore single-line layout for admin index search inputs

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm
t/cobrand/isleofwight.t

Use a generic report description for fetched reports rather than the one
fetched over open311

[IsleOfWight] ignore description on fetched reports

---

perllib/FixMyStreet/App/Controller/Admin/Triage.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/app/controller/admin/triage.t
t/cobrand/isleofwight.t

This is only used for audit purposes on FixMyStreet and not required in
Confirm.
[ship changelog]

[IsleOfWight] do not send comment recording triage action

---

templates/web/westminster/footer_extra_js.html
web/cobrands/westminster/roadworks.js

Fixes: mysociety/fixmystreet-commercial#1566

[Westminster] Add roadworks.org layer

---

bin/fixmystreet.com/one-off-status-update

This is a one off script to update the status of NCC reports affected
by a bug in the NCC update process. It relies on a csv file containing
a mapping of report id to Alloy status and uses this to update the
FixMyStreet status.

[Northamptonshire] script to update NCC statuses

---

perllib/FixMyStreet/DB/Result/Contact.pm
perllib/Open311/PopulateServiceList.pm

It arises that `<group></group>` now passes to the code as a one-element
list containing undef, which compared differently to what was stored -
the code assumed lists would contain things. A new changelog entry was
created each time. Hopefully resolve this once and for all by treating
groups more formally and making sure we always have lists to compare.

Stop empty Open311 group causing duplicate history

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/app/controller/around.t

Two unrelated commits, one to fix a bug where it flashes a message it doesn't need to, the second to not bother generating map data if we're not going to be displaying a map.

Fix missing body message flash, and only call gaze once

---

perllib/FixMyStreet/TestMech.pm
t/Mock/OpenIDConnect.pm
t/app/controller/admin/update_edit.t
t/app/controller/admin/users.t
t/app/controller/alert_new.t
t/app/controller/auth_profile.t
t/app/controller/auth_social.t
t/app/controller/contact.t
t/app/controller/contact_enquiry.t
t/app/controller/moderate.t
t/app/controller/report_as_other.t
t/app/controller/report_new.t
t/app/controller/report_new_mobile.t
t/app/controller/report_updates.t
t/app/model/session.t
t/app/model/user.t
t/cobrand/bathnes.t
t/script/inactive.t

We are getting occasional (though seems to be increasing) deadlocks in the test suite on Travis, always in the admin/bodies.t or permissions.t files, whereby the creation of a superuser account is deadlocked against another test process somehow. I have tried but cannot see any place where a deadlock could occur - all user creation happens in the same order in all the test files - but it is definitely happening. Rather than try and get the output of the server query log and find out what the other statement is, it seemed easier to change our test user creation functions to create per-test-file email addresses. I thought this might also speed up the test suite as no test file will block waiting for the same email address to become available when another test file using it finishes, but it …

Per-test file email addresses.

---

web/cobrands/fixmystreet/assets.js

Without this, with the default template, it would find "an item" instead of "a road".  I think looking only inside the chosen ID is the right thing to do, but not 100% sure.

Limit asset string finding to chosen ID.

---

web/cobrands/bristol/assets.js

An upgrade to Bristol’s server means this will need to be requested.

[Bristol] Explicitly request shape information.

---

perllib/FixMyStreet/App/Controller/Contact.pm
perllib/FixMyStreet/App/Controller/Photo.pm
perllib/FixMyStreet/App/Controller/Questionnaire.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/cobrand/westminster.t

Ensures that comments left on Westminster reports on fixmystreet.com don't show up on the Westminster cobrand.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1509

[Westminster] Hide fixmystreet.com updates on Westminster cobrand

---

web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/js/duplicates.js

On mobile the asset selection process is a bit fiddly, and the duplicate suggestion UI makes this harder than it needs to be.
This PR adds three small changes to improve things a bit:
1.  Stops the duplicates code from removing the asset markers from the map if you happen to miss the asset when tapping:
Old | New
--- | ---
2. The duplicates are now dismissed when returning to the map to select the asset marker:
(Although I'm not super happy with this solution, as the user may actually want to go to the map to see the locations of the duplicate markers... So open to removing/rethinking this change.)
3. The "You can pick a _thing_ from the map" message is a button on mobile that takes you to the map:

Improve asset selection/duplicate suggestion interactions on mobile

---

templates/web/fixmystreet.com/reports/cobrand_stats.html

Trying to access the summary dashboard without permission already redirects the user to a login page, so this change makes it easier for logged-in council staff and super users to access the dashboard without having to see the login form.

[fixmystreet.com] Make summary dashboard easier to access if logged in

---

web/cobrands/fixmystreet/admin.js

`sortable()` returns `undefined` if no elements match, so on admin pages
that weren't the contact editing page a `TypeError` was being thrown by
the `[0]` line which resulted in the debug toolbar not being shown.

Restore debug toolbar on non-contact admin pages

---

web/cobrands/fixmystreet/assets.js

This fixes a bug where if a category group is picked for which assets are shown (e.g. Drains on Westminster) then an asset selected/auto-selected, then a subcategory picked, the asset's ID is not written to the hidden field. This is because it is only being done on asset selection, at which point the hidden field does not exist.
Also remove a needless event listen where every asset selection would cause checkFeature to run twice. I think.

Subcategory asset pick

---

perllib/FixMyStreet/DB/ResultSet/State.pm
t/cobrand/isleofwight.t

Use Island Roads in place of council in not responsible message.
Fixes mysociety/fixmystreet-freshdesk#93

[IsleOfWight] do not mention council in not responsible

---

.cypress/cypress/integration/buckinghamshire.js
bin/fixmystreet.com/fixture
web/cobrands/bexley/js.js
web/cobrands/fixmystreet/assets.js

Bexley's Confirm server needs the `NSG_REF` attribute from the Streets layer to appear in the `site_code` field.
We already had a `usrn` configuration for Bexley's assets, so this change includes a modification to the code that handles the `usrn` mapping to allow it to accept an array of configuration objects as well as just a single object.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1638

[Bexley] Map NSG_REF as site_code for Confirm

---

perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/Cobrand/Lincolnshire.pm
perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/FixMyStreet/Roles/ConfirmOpen311.pm
perllib/FixMyStreet/Roles/ConfirmValidation.pm
t/app/controller/auth_profile.t
t/cobrand/fixmystreet.t
t/cobrand/isleofwight.t
t/cobrand/westminster.t

This can then be used by in-progress Peterborough, Cheshire East, Bexley, to automatically catch the three photos thing (Bexley might be trickier due to multi-integration but hey).

[UK] Factor out Confirm open311_config to role.

---

web/cobrands/bristol/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/lincolnshire/assets.js

If GET-based WFS is being used, no server-side filtering takes place, so we need a client side filter to perform the same job. But if normal POST WFS is being used, the server-side filtering has already been performed, so no need to do it again (in fact, no need to return the data necessary to do such filtering either).
Making this change to save bandwidth on Bristol and Lincolnshire and Cheshire East in progress.
Corresponding PR at https://github.com/mysociety/fixmystreet.com/pull/6 to reduce Lincs output.

Only add filter strategy if HTTP WFS being used.

---

perllib/FixMyStreet/App/Controller/Report/New.pm

The mobile app is looking at the old extra.datatype_description location
rather than the new disable_form location for per-question disabling (it
does look there for all-category disabling). So we need to make sure the
JSON includes the message in the place where it will be looking.
Note if an extra data question has two answers that disable the form and
they have different messaging, the app will only take one of them.
[skip changelog] (new feature included there already)

[Mobile] Make sure disable message findable by app

---

perllib/FixMyStreet/App/Controller/Admin/Triage.pm
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/DB/Result/Contact.pm
perllib/FixMyStreet/DB/ResultSet/Contact.pm
t/cobrand/bathnes.t
templates/web/base/report/new/category_extras.html

Remove the extra questions heading visually, it's duplicating what's just above (plus wasn't showing the display name); make sure categories sorted in display order; and save a bit of bandwidth on the disable form call. [skip changelog]

Some small rename-category fallout

---

perllib/FixMyStreet/Cobrand/Peterborough.pm

As requested by @LouiseMySociety in Slack:
> …the Peterborough co-brand is still set to send questionnaires out. I think they wanted that disabling

[Peterborough] Disable questionnaires

---

web/cobrands/borsetshire/base.scss

The extra header was causing layout issues on the mobile map page at the point when you confirm a new report’s location.

[Borsetshire] Hide mySociety header on map pages

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Roles/ContactExtra.pm
t/app/controller/admin/templates.t
t/app/model/defecttype.t
t/app/model/responsepriority.t
t/app/model/responsetemplate.t
templates/web/base/report/_inspect.html
templates/web/base/report/inspect/_extra_details_field.html
templates/web/base/report/inspect/extra_details.html
templates/web/tfl/report/inspect/extra_details.html

- Removes priority and traffic management fields & admin permissions
- Ensures only TfL response templates are visible, not all London cobrands

[TfL] Inspector form tweaks

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

Borrowed the LBO commit from the current inspectors PR (with added mock), and includes stuff for safety critical that is only currently in tfl-cobrand, even though this is branched off tfl-reviewed, so should work fine if those are merged together.
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1613

[TfL] Add CSV export columns

---

perllib/FixMyStreet/App/Controller/Auth.pm
t/app/controller/auth.t

Just after fixing it, 3d593bc68 broke it again, because it took anyone
who must have 2FA switched on to the must-have-2FA sign up flow, even
if they already had 2FA set up. [skip changelog]

Fix password reset on 2FA accounts again.

---

perllib/FixMyStreet/Cobrand/UK.pm
t/cobrand/tfl.t
templates/email/tfl/submit.html
templates/email/tfl/submit.txt

Also fixes an issue where `tfl` cobrand not active when sending report emails.
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1603

[TfL] Highlight safety critical reports in email subject line

---

docs/customising/templates.md

The logo_width and logo_height are set in `_email_color_overrides.html`, not `_email_setting_overrides.html`, so update the documentation to reflect that.

[Docs] Fix name of template for email logo settings

---

CHANGELOG.md
perllib/FixMyStreet/SendReport/Email.pm
t/app/model/problem.t

If email SendReport is used, this stores the email address(es) sent to on the report as a record. This could be worked out (in normal cases) from looking at the category details at the time the report was sent, but in complicated cases and ones that might change frequently, there doesn't seem any harm in freezing it at the point of sending. This could in future be displayed in admin, CSV export, etc.

Store email addresses report sent to on the report.

---

perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Script/Alerts.pm
t/app/controller/alert_new.t

Connects mysociety/fixmystreet-commercial#1613.
Records the first time a fixed/closed update is sent to the reporter in an email.
The delivered-to will come from #2730 when merged.

[TfL] Delivered to and closure-email-at in CSV export

---

perllib/FixMyStreet/Cobrand/TfL.pm

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1678
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1675
Probably fixes much else using base_url_for_report (links in emails, confirming an already confirmed report email link, etc).

[TfL] Fix base url.

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t

- Enable anonymous reporting with single button-click
- ~Create unique user record for each anonymous report~
~The second point is probably not the right way of doing this, per discussion on the ticket. Opening the PR as-is though, to get this off the `tfl-cobrand` branch.~
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1594

[TfL] Enable anonymous reports

---

templates/web/tfl/report/new/roads_message.html
web/cobrands/fixmystreet-uk-councils/roadworks.js
web/cobrands/fixmystreet/assets.js
web/cobrands/tfl/assets.js

- Ensures reports can only be made on red routes in specific categories.
- Ensures a marker must be selected for bus stops/traffic lights layers
- Only shows roadworks.org markers that are on red routes
Connects https://github.com/mysociety/fixmystreet-commercial/issues/1588

[TfL] Red route asset handling

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Rss.pm
t/app/controller/rss.t
templates/email/default/_email_settings.html
templates/email/default/_email_sidebar.html
templates/email/default/_email_top.html
templates/email/default/xsl.xsl

Fixes https://github.com/mysociety/fixmystreet/issues/2736 - uses the email templates to give cobrand specific branding if present in the emails, and also gives nice consistency between RSS and email alerts, which conceptually are doing the same thing anyway.
Before:
After:

Add cobrand-specific XSL to RSS feeds.

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
t/app/controller/report_new_open311.t

If a user belongs to a body override the disabled form check upon
submission as mostly staff users can submit in those categories.
Fixes mysociety/fixmystreet-freshdesk#98

allow staff to submit in disabled categories

---

templates/email/tfl/other-reported.html
templates/email/tfl/other-reported.txt
templates/email/tfl/problem-confirm.html
templates/email/tfl/problem-confirm.txt

Seemed easier to copy the templates then fiddle with getting report.body to return something different.

[TfL] Make sure emails use "Transport for London".

---

templates/email/tfl/_email_color_overrides.html
templates/email/tfl/_email_setting_overrides.html

Fixes the header/footer text contrast issue mentioned by @dracos in https://github.com/mysociety/fixmystreet-commercial/issues/1670.
Background `#EFF6FD` is taken from their website (eg the hover colour on [the download links here](https://tfl.gov.uk/info-for/suppliers-and-contractors/design-standards?intcmp=5837)) and text colour `#414B56` is one of their core brand colours. Contrast ratio is 8.14:1.
While I was there, I also fixed some awkward stretching and extra vertical space in the header.

Tfl improve email contrast

---

web/cobrands/tfl/base.scss

This is a bit of a catch-all fix and I haven't been able to test it exhaustively. If we spot any links appearing underlined we can add them to the list in the stylesheet I guess

Make all links consistently underlined

---

bin/tfl/import_categories
perllib/FixMyStreet/App/Controller/Report/New.pm
templates/web/bromley/footer_extra_js.html
templates/web/fixmystreet-uk-councils/report/new/roads_message.html
templates/web/greenwich/footer_extra_js.html
templates/web/hounslow/footer_extra_js.html
templates/web/westminster/footer_extra_js.html
web/cobrands/bexley/js.js
web/cobrands/bromley/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/northamptonshire/assets.js
web/cobrands/tfl/assets.js
web/cobrands/westminster/assets.js

This PR sets up the UK site and London cobrands so that clicking on a TfL red route will show all TfL categories and any council street cleaning category/group, and clicking elsewhere in Greater London will show all council categories and TfL any-location categories (bus stops, traffic lights). It centralises all TfL handling in one JS file which should handle all the above.
Category groups need to be activated on all London cobrands for this to function correctly.
The only loss I have thought of is Bromley's "Blocked drain" in Street cleaning will no longer go to TfL (they don't have such a category for that to work; we could drop it if Bromley do not want to receive them).
To fix the issue of Other being a stopper category for TfL, but we don't want that on non-red route on non-tfl …

[TfL] Red route handling for .com/cobrands

---

CHANGELOG.md
conf/general.yml-example
docs/customising/config.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/UK.pm
t/app/01app.t
t/cobrand/councils.t

This allows you to output a working Content-Security-Policy header, with optional third-party domains, by setting a new CONTENT_SECURITY_POLICY configuration option.
In the UK, uses a cobrand feature to allow per-cobrand CSP setting.

Add configuration for setting CSP header.

---

perllib/FixMyStreet/Cobrand/Peterborough.pm

They've requested that these be added to the cobrand.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1667

[Peterborough] Include email categories on cobrand

---

perllib/FixMyStreet/Script/Alerts.pm
t/cobrand/oxfordshire.t

This was passing the cobrand object so the checks in State::display that
were relying on the moniker were not working.

pass cobrand name to state display from alert script

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/cobrand/isleofwight.t
templates/web/fixmystreet-uk-councils/report/_updates_disallowed_message.html
templates/web/fixmystreet.com/report/_updates_disallowed_message.html
templates/web/isleofwight/report/_updates_disallowed_message.html

This means you don't have to make a new template each time a council adds a disallowed option. [skip changelog]

[UK] Updates disallowed template work out message.

---

perllib/DBIx/Class/FixMyStreet/EncodedColumn.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/TestMech.pm
t/cobrand/tfl.t
templates/web/base/report/_item.html
templates/web/fixmystreet.com/report/_item_photo_title.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1687
I considered having the cobrand bits in the cobrand file, but for password stuff it seemed clearer to have them present there as an exception, maybe?

[TfL] Privacy policy changes

---

t/cobrand/cheshireeast.t
templates/web/cheshireeast/report/new/form_after_heading.html
templates/web/cheshireeast/tokens/confirm_problem.html
web/cobrands/sass/_base.scss

Also gives change_location a bottom margin as I needed it here, needed it on TfL for their top message, and would improve the Bucks message too. [skip changelog]
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1686

[Cheshire East] Emergency message on report form

---

perllib/FixMyStreet/App/Controller/Admin/Templates.pm
perllib/FixMyStreet/App/Controller/Admin/Users.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/admin/templates.t
templates/web/base/admin/category-checkboxes.html

Adds category groups to the user and template editing forms in the admin:
For https://github.com/mysociety/fixmystreet/issues/2702

Group categories on map filters & admin

---

templates/web/peterborough/header_extra.html

Forgot to actually reference the favicon.ico file in the original PR, oops!
Follows on from https://github.com/mysociety/fixmystreet/pull/2785.
Part of https://github.com/mysociety/fixmystreet-freshdesk/issues/103

[Peterborough] Add link tag referencing custom favicon.ico

---

perllib/FixMyStreet/Script/Reports.pm
t/cobrand/tfl.t

We're using the sent-to cobrand's template, so we should use its base URL. And a bug on TfL for the reference in the report sent email. [skip changelog]
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1720

[TfL]/[UK] Couple of issues with submission process

---

perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/DB/ResultSet/State.pm
t/cobrand/isleofwight.t
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1704
The issue remains in email alerts, but there we don't have easy access to the body names, so is harder to fix there, and has always been present, so this should at least fix the issue for TfL cobrand/.com web.

[TfL] Display of not responsible state

---

CHANGELOG.md
bin/update-schema
db/downgrade_0069---0068.sql
db/downgrade_0070---0069.sql
db/fixture.sql
db/schema_0070-alert-type-site-name.sql
perllib/FixMyStreet/App/Controller/Rss.pm
t/cobrand/tfl.t
templates/email/default/xsl.xsl

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1708
"No schema update found" is because it's looking for a change to schema.sql but I changed fixture.sql.

Do not hard code site name in database fixture

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
t/Mock/MapIt.pm
t/Mock/Tilma.pm
t/app/controller/admin/templates.t
t/cobrand/hounslow.t
t/cobrand/tfl.t
web/cobrands/tfl/assets.js

The app can't distinguish between reports being made on red routes or not, so this PR makes the determination server side and returns the appropriate categories in the `/report/new/ajax` call. This fixes the app and also updates the website to use the same method.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1716

[TfL] Server-side red route lookup

---

perllib/FixMyStreet/Cobrand/Greenwich.pm

The recent TfL launch has meant a bunch of extra categories appearing on the Greenwich site which aren't wanted.

[Greenwich] Don’t show TfL categories on cobrand

---

perllib/FixMyStreet/Cobrand/Greenwich.pm

Companion to #2800 that does the same for `/around`.

[Greenwich] Hide TfL categories on /around filter

---

perllib/FixMyStreet/Geocode/OSM.pm

Saves a HTTP->HTTPS redirect when doing street name lookup from front page.

Switch OSM geocoder URLs to HTTPS

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_as_other.t
t/app/controller/report_new_anon.t

Stored ‘contributed_by’ when staff users make anonymous reports via button

---

web/cobrands/eastherts/layout.scss

A simple one. The `position: relative` on East Herts’ new `.container` elements was making the `position: absolute / position: fixed` sidebar unclickable, because it has a `z-index: -1` by default (so that it stacks _underneath_ the default footer).
This _does_ mean that the East Herts sidebar can now overlap on top of the footer, but it’s a very short footer (unlike FMS.com) so this will only be an issue on extremely short windows.

[East Herts] Fix z-index stacking bug in Help page sidebar

---

t/cobrand/bucks.t
templates/email/buckinghamshire/other-reported.html
templates/email/buckinghamshire/other-reported.txt

Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/104

[Buckinghamshire] Remove ‘not responsible’ message from emails for district reports

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Users.pm
t/app/controller/admin/users.t
t/app/controller/report_inspect.t
templates/web/base/navigation/_all_reports.html

In the rare situation that a user has no from_body set but does have categories set in their extra metadata, the 'All reports' link would point to /my/inspector_redirect but this URL would 404 if the user did not have a from_body. This PR updates the template to use the same logic when generating the 'all reports' link, so users without from_body will never be sent to /my/inspector_redirect.
Also clears any categories from the user record when its from_body is unset.
Fixes #2815.

Fix 'all reports' link for users with categories but no from_body

---

perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_open311.t
templates/web/base/report/new/category_extras.html

For categories that use the extra metadata fields to just show a notice
message to the user, the ‘help the council fix the problem by providing
extra information’ text was a bit out of place. This commit hides it
unless there are actual UI elements also included in the markup.
Fixes #2811.

Hide ‘provide extra information’ preamble when no visible fields are present

---

CHANGELOG.md
conf/general.yml-docker
conf/general.yml-example
docs/customising/config.md
t/cobrand/staging.t
templates/web/base/debug_header.html

Allows you to hide the banner introduced in 1f43fc9.
Useful when you’re making front-end changes—especially on small screens—and don’t want the banner getting in the way.
I can see why the banner’s useful, but it’s just been annoying me ever since it arrived last month ;-)
I’ve added a new test in `t/cobrand/staging.t` – not sure whether that’s the best place! Couldn’t find any other front-end tests for staging/development options. Maybe this is the first one?
The new flag is documented on the `/customising/config` docs page, alongside the other STAGING_FLAGS.
Changlelog updated.

STAGING_FLAGS option to hide the staging site banner

---

perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t

- Fixes an ambiguous column name when attempting to download CSV stats for a specific month
- Fixes front page double escaping of postcode text. That appears to be the only place it was happening.

[Zürich] Fix admin CSV exports and front page double-escaped text

---

perllib/FixMyStreet/Cobrand/TfL.pm

- Adds disambiguation to try and get results that are actually within London.
- OSM includes more of the address in each result to help the user identify where each identically-named road actually is within London.

[TfL] Switch to OSM geocoder; add ‘London’ to disambiguation

---

bin/process-inactive-reports
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/Script/Inactive.pm
t/cobrand/tfl.t
t/script/inactive.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1608
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1669
Fixes https://github.com/mysociety/fixmystreet/issues/2376
Will be run as `process-inactive-reports --delete 36 --cobrand tfl` and `process-inactive-reports --delete 84 --cobrand tfl` with the code picking the right ones to delete based upon the time period.

[TfL] Remove old reports after specified time periods

---

perllib/FixMyStreet/Template/Variable.pm
t/template.t

Perl may pass swapped operands to ensure the first one is always an object that implements the relevant operator.

Cope with swapped operands in template operators

---

web/cobrands/bathnes/assets.js
web/cobrands/bexley/js.js
web/cobrands/bristol/assets.js
web/cobrands/bromley/assets.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/cheshireeast/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/highways/assets.js
web/cobrands/hounslow/assets.js
web/cobrands/isleofwight/assets.js
web/cobrands/lincolnshire/assets.js
web/cobrands/peterborough/js.js
web/cobrands/tfl/assets.js
web/cobrands/westminster/assets.js

Rather than setting a min_resolution on all of the cobrands just set a
default in web/cobrands/fixmystreet/assets.js. This means that assets
will appear at all zoom levels, which seems like what we want to happen
most of the time.
Fixes https://github.com/mysociety/fixmystreet/issues/2835

Fix assets disappearing at maximum zoom

---

CHANGELOG.md
perllib/Open311/GetServiceRequestUpdates.pm
t/open311/getservicerequestupdates.t

To avoid issues with autogenerated updates in the bodies back-end
happening quicker that the back-end returns the external_id to us ignore
the check for comment being earlier than the last update if it's the
first comment.

[open311] always update problem state if no comments

---

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm

Some contacts (e.g. TfL) don’t have a valid email address but aren’t Open311
categories - the email destination is managed via the borough_email_addresses
feature. This prevents any changes to the contact being made via the admin
due to the email validation error message.
This commit updates the logic to only check that the email address is valid
if it’s been changed from the existing value (which may be blank if a it’s a
new contact).
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/108

Skip admin contact email validation check if address hasn’t changed

---

web/cobrands/fixmystreet/density-map.js
web/cobrands/sass/_base.scss

This helps distinguish between the heatmap and underlying features.
Old | New
--- | ---

Reduce saturation of basemap when heatmap is active

---

templates/web/base/report/display_tools.html

It is possible for a report to be closed to public updates, but it still
could receive updates (eg updates only from problem reporter, or updates
only by staff), so we should still allow people to sign up.

Allow update signup even if updates disallowed.

---

perllib/FixMyStreet/App.pm
perllib/FixMyStreet/Cobrand/TfL.pm
t/cobrand/tfl.t
templates/email/tfl/signature.txt

It was using the branding/URL of the site the update was left on.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1741 [skip changelog]

[TfL] Always use TfL branding on shortlist email.

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/TestMech.pm
t/Mock/MapIt.pm
t/Mock/OpenIDConnect.pm
templates/web/base/report/new/category.html
templates/web/base/report/new/category_wrapper.html
templates/web/base/report/new/form_report.html
templates/web/base/reports/_list-filters-sort.html
templates/web/base/reports/_list-filters.html

Tweaks needed in core for the Sort My Sign project:
* Labels template included earlier so we can override the category label;
* Allow running of its own tests;
* Factor out the list filter sort section to its own template;
* Let the heatmap be viewable when not logged in (if cobrand allows it).

Sort My Sign

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm

If we wait until after to filter the contacts and the constructed
options, then we can end up in the situation where e.g. we've filtered
out all the TfL contacts but the category option is still the TfL one
(with its associated group).
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1740

[UK] Filter contacts before constructing options.

---

bin/fixmystreet.com/add_emergency_message

There was a typo in the error message and the related conditional which meant it was checking for `$opts->questions` (which doesn't exist) rather than `$opts->question`, which prevented the script from being used to add a question.
Related to https://github.com/mysociety/fixmystreet/pull/2699, where the bug was originally introduced.

Fix bug in add_emergency_message script

---

perllib/Open311/PopulateServiceList.pm

[Open311] Don’t use full path to open311-populate-service-list in editor column

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

When going back to the initial state with popstate, a change event was
being triggered on every single option of the filter selects. This led
to a lot of change events running on the category/status multi-selects
which then needlessly repeated the same activities over and over. This
locked up the browser for seconds in locations with many categories.
Performance chart before:
After:

Only trigger one change event on initial popstate.

---

.cypress/cypress/integration/peterborough.js
bin/browser-tests
bin/fixmystreet.com/fixture
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_open311.t
web/cobrands/fixmystreet/fixmystreet.js

This changes the existing logic to account for the fact that multiple questions might have the disable form checkbox ticked for one of their options. Previously it only worked for one question which disabled the form.
At the moment this just displays one of the messages at a time, with the first one taking priority. So if you have a "Is this an emergency" question and a "Is this on private land" question which both disable the
form, and the user has selected "Yes" to both, then only the message for the first question is displayed. This can potentially be improved in the future, but seemed out of scope for this change.
Fixes https://github.com/mysociety/fixmystreet/issues/2853
Original PR which added the disable for option for question: https://github.com/mysociety/fixmystreet/pull/2599

Allow multiple question to disable the new report form

---

templates/web/northamptonshire/index-steps.html

This is as requested on https://mysocietysupport.freshdesk.com/a/tickets/389 but perhaps there is a better solution to this, thoughts?

[Northamptonshire] Customise homepage index steps

---

CHANGELOG.md
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

For #2013. I've left the zoom control there for now, easy to remove also if desired.

Remove pan control from mobile widths.

---

CHANGELOG.md
templates/web/base/js/translation_strings.html
templates/web/base/report/display_tools.html
templates/web/base/report/update-form.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/cobrands/tfl/js.js

A bit of #2013 and/or #2494.
It stops the updates link on a mobile-width report page moving to be part of the map, and keeps it where it would be at larger widths. And stops capitalising those key tools links.

Tweak to report updates link

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Problem.pm
templates/web/base/report/_item_expandable.html
web/cobrands/sass/_base.scss
web/js/duplicates.js

When making a new report on mobile devices the main map has scrolled off the top of the page when the duplicate suggestions are shown. This PR adds an inline image for each one that gives a bit more context about where the suggested report:
Fixes #2668.

Display inline map for duplicate suggestions on mobile

---

bin/fixmystreet.com/add_emergency_message
perllib/FixMyStreet/Cobrand/Peterborough.pm
t/cobrand/peterborough.t
web/cobrands/fixmystreet/assets.js
web/cobrands/peterborough/js.js

Changes for the ezytreev integration. Mostly adding and removing fields in the open311_config around hook. Also adding the javascript to display the tree layers on the map when the "Trees" category i selected.
Part of [Peterborough Phase 2 - EzyTreev](https://github.com/mysociety/fixmystreet-commercial/milestone/37).
Related open311-adapter PRs: https://github.com/mysociety/open311-adapter/pull/85 and https://github.com/mysociety/open311-adapter/pull/87

[Peterborough] Changes for ezytreev integration

---

perllib/FixMyStreet/App/Controller/Admin.pm

Historically, the FixMyStreet admin was accessed via HTTP Basic Auth and
a secure proxy, so the auth user was used for logging purposes. Nowadays
all admin use is by FixMyStreet user, and any Basic Auth is used for the
purpose of hiding staging sites from bots. This configuration means that
on those staging sites, all admin is logged by the one staging user, not
the actual user, so let's swap that round.

Default logging to logged in user.

---

.cypress/cypress/integration/regressions.js
.cypress/cypress/integration/responsive.js
CHANGELOG.md
perllib/FixMyStreet/Template.pm
templates/web/base/js/translation_strings.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss
web/js/map-OpenLayers.js
web/js/map-google.js
web/js/map-wmts-zurich.js

This PR renames "Try again" when you first click map to "Nearby reports". You don't need to click "try again" in order to... try again, you can click the map again or drag the pin, clicking try again is actually more annoying because it takes you back to around loading nearby pins and starting the whole thing again which you might well not want. Update the heading to explain you can reposition before hitting OK.
Going back up from the form to the map and clicking "Try again" doesn't go back to around either, but only resets the map to allow repositioning of the pin again. You can go back to nearby reports from there if you desire.
This PR also restricts lat/lon in URL to 6dp, and stops history state being pushed on each map drag/click (assuming those are only corrections to the first). …

Improve mobile try again interface

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/cobrand/tfl.t

Will need a feature adding to match current behaviour of:
```
send_questionnaire:
fixmystreet:
TfL: 0
```
[skip changelog] Connects with https://github.com/mysociety/fixmystreet-freshdesk/issues/111

[UK] Use feature flag for send_questionnaire.

---

.travis.yml

Cypress 4 has been released, it requires node 8, travis has 6 by default, seemed easier to pin cypress than upgrade node? [skip changelog]

[Travis] Pin cypress to version 3.

---

perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Template.pm
web/cobrands/tfl/assets.js

On the TfL cobrand, this treats the 'Flytipping (TfL)' category
the same as the existing 'General Litter' and redirects users to
fixmystreet.com.
On fixmystreet.com, borough flytipping categories are included in
those available on red routes.
This PR also includes a commit to allow the `class` attribute on `a` elements in HTML-scrubbed inputs, which is required for the "form disabled" message of the to-be-disabled TfL flytipping category.
For mysociety/fixmystreet-freshdesk#120

[TfL] Include borough flytipping categories on red routes

---

conf/packages.docker
conf/packages.generic

I tried installing the latest master on Debian Buster and ran into this missing dependency.

Add libpng-dev to package lists (generic and for Docker)

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Template/SafeString.pm
t/cobrand/zurich.t

Attempting to load the `/report/ajax/<id>` URL for a problem that had a public response and wasn't in the ‘external’ state was causing a crash because the call to `FixMyStreet::App::View::Web::add_links` in `updates_as_hashref` was returning a `FixMyStreet::Template::SafeString` that the JSON module didn't know how to serialise.
This commit adds a `TO_JSON` method to `SafeString`, and ensures the output
of `/report/ajax/<id>` is JSON-encoded with `convert_blessed` turned on so the
`TO_JSON` method is called.

[Zürich] Fix crash on certain /report/ajax/<id> URLs

---

t/app/controller/report_new_open311.t
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/councils_text.html
templates/web/base/report/new/councils_text_all.html
templates/web/base/report/new/councils_text_private.html
templates/web/oxfordshire/report/new/councils_text_all.html
templates/web/tfl/report/new/councils_text_all.html
web/cobrands/fixmystreet/fixmystreet.js

The `IF category_extras.$category.size` condition in category_extras.html was using an escaped string for `$category`, meaning the lookup would always fail for categories that had an ampersand in their name. The result of this was an empty `<div id="category_meta">`, and no extra fields shown to the user. This caused issues when one or more of the fields were required, as they were always empty and the error message wasn't being rendered and shown to the user. This meant the user would see their report form over and over again when submitting instead of useful feedback.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/126

Fix category extra AJAX call for categories with ampersands

---

web/cobrands/peterborough/js.js

We always want a tree code for tree reports, so add the code needed to make the asset selection step mandatory.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/1780

[Peterborough] Force tree asset selection

---

perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Script/Reports.pm
t/app/controller/report_new_anon.t
templates/web/base/report/form/user.html
templates/web/westminster/report/form/user_loggedout.html
web/cobrands/fixmystreet/fixmystreet.js

This passes in the category to `allow_anonymous_reports` function so it can change its answer on a per-category basis should it wish to. It also passes the result to the client JS so it can show/hide the button as appropriate. In a cobrand where it is always allowed for all categories, this does mean it's adding `"allow_anonymous": true` to every category of the output, but with gzip that shouldn't make much difference.
Also fixes a bug where the report anonymously button wasn't being shown in non-JS scenario.

Allow anonymous reporting on per-category basis

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Tokens.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/app/controller/report_display.t
t/app/controller/report_non_public.t
templates/email/buckinghamshire/other-reported.html
templates/email/buckinghamshire/other-reported.txt
templates/email/default/other-reported.html
templates/email/default/other-reported.txt
templates/email/fixamingata/other-reported.html
templates/email/fixamingata/other-reported.txt
templates/email/hounslow/other-reported.html
templates/email/hounslow/other-reported.txt
templates/email/tfl/other-reported.html
templates/email/tfl/other-reported.txt
templates/web/base/report/display_tools.html
templates/web/base/report/update-form-wrapper.html

If a report is made using "Report as other" and marked as private, the email that gets sent to the user telling them this should explain that it's a private report. We also make the link in that email work (even if not logged in) but don't log them in, in case they forward the email on (could change that easily enough). Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/125

Include explanation of private reports in other-reported email

---

web/cobrands/peterborough/assets.js

Follows on from https://github.com/mysociety/fixmystreet/pull/2885.
This fixes a bug where the new tree plantings group was requiring a tree group to be selected, which isn't the desired behaviour.
The bug was caused by the group layer not having the same `relevant` function as the points layers. This adds the shared bits into a shared config that the assets both use.

[Peterborough] Ensure trees and tree groups share the same config

---

.cypress/cypress/fixtures/tfl-bus-stops.xml
.cypress/cypress/fixtures/tfl-tlrn.xml
.cypress/cypress/integration/tfl.js
bin/browser-tests
bin/fixmystreet.com/fixture
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/Mock/MapIt.pm
t/cobrand/tfl.t

After this change, you can safely add the TfL body to other councils (namely the ones surrounding London that include TfL bus stops); clicking in those councils on other cobrands will have no change, as the TfL body will be fully ignored on a non-London council, but on the TfL cobrand it will allow it for e.g. the selection of bus stops outside London.
It removes the body rather than just all its categories to prevent a "We do not have details of the other body covering this area" message appearing.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/116 [skip changelog]

[TfL] Bus stops outside London

---

CHANGELOG.md
perllib/FixMyStreet/DB/Result/Comment.pm
t/app/controller/admin/users.t

If a user had no confirmed updates, but did have e.g. an unconfirmed update that had mark_fixed set, you would get an error when trying to hide the user's reports/updates.
Fixes #2898.

Fix error hiding user's updates with no confirmed.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Location.pm
perllib/FixMyStreet/Geocode/Bexley.pm
perllib/FixMyStreet/Geocode/Bing.pm
perllib/FixMyStreet/Geocode/Google.pm
perllib/FixMyStreet/Geocode/OSM.pm
perllib/FixMyStreet/Geocode/Zurich.pm

If a SQLite file exists at `../data/analytics.sqlite` with a table named `location_searches_with_no_results`, then a row will be created for each `/around` search that returns no results.
Assuming a search for "heath field close" on fixmystreet.com, that returned no results, it would log:
| datetime | cobrand | geocoder | url | user_input |
| --- | --- | --- | --- | --- |
| 2020-02-25 14:57:48 | fixmystreet | OSM | https://nominatim.openstreetmap.org/search?countrycodes=gb&format=json&q=heath+field+close | heath field close |
Part of mysociety/fixmystreet-commercial#1663.
@dracos I attempted to make the whole thing "optional" by wrapping it in a `try catch` block – not sure whether that’s a good idea or not?
Also, do you think it’s worth adding tests for this? Maybe not worth testing the …

Optional server-side tracking for unsuccessful location searches

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/ManifestTheme.pm
perllib/FixMyStreet/App/Controller/Offline.pm
perllib/FixMyStreet/App/Controller/Root.pm
perllib/FixMyStreet/App/Form/ManifestTheme.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/DB/Result/AdminLog.pm
perllib/FixMyStreet/PhotoStorage.pm
perllib/Memcached.pm
t/app/controller/admin/manifesttheme.t
t/app/controller/offline.t
templates/web/base/admin/manifesttheme/form.html
templates/web/base/admin/manifesttheme/index.html
templates/web/base/common_header_tags.html
templates/web/fixmystreet.com/header_extra.html
web/cobrands/fixmystreet/admin.js
web/cobrands/sass/_admin.scss

Adds admin UI for superusers to manage the `ManifestTheme` model for each cobrand. Allows the names/icon/colours to be customised.
Installing | Icon
---------- | ----
- Colour picker UI in form
- Live preview of app/home screen UI alongside form fields
Fixes #2792.

Add cobrand-specific manifest customisation

---

.cypress/cypress/integration/buckinghamshire.js
templates/web/buckinghamshire/report/form/user_name.html

Since we require the user to enter their full name Buckinghamshire have asked us to change the text to "Full name" to make it clearer that the full name is required to complete the form.
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/122
There is the wider issue of doing this for all cobrands that have the validation for full name on them, but that will be done separately, as part of https://github.com/mysociety/fixmystreet/pull/2868.

[Buckinghamshire] Change "Name" to "Full name" on forms

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm

If you submit the non-JS image map from an around page with a particular
category selected, that is sent to the server in filter_category and
should be checked to see if we can pre-fill the category dropdown on new
report.

Also check filter_category for category choice.

---

CHANGELOG.md
Vagrantfile
bin/install_packages
script/bootstrap

This adds a script, `bin/install_packages`, that will install packages
listed in versions of `conf/packages*` and calls it from the bootstrap
script in a way appropriate to the environment it is being run under.
This should ensure that, for example, changes to dependencies will be
applied to Vagrant machines in-between tagged releases.

Ensure that Vagrant box packages are kept updated

---

perllib/FixMyStreet/Map/MasterMap.pm
t/map/mastermap.t
templates/web/base/maps/openlayers.html
web/cobrands/bexley/assets.js
web/cobrands/fixmystreet/map.js
web/cobrands/isleofwight/assets.js
web/cobrands/northamptonshire/assets.js
web/cobrands/peterborough/assets.js
web/js/map-mastermap.js

This passes a flag from server to client rather than rely upon hostnames.
It switches existing (IoW/Northants) to use this var, and adds Peterborough assets/MasterMap to things that use it.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1785 [skip changelog]

Use staging sites on staging hosts

---

web/cobrands/bromley/_colours.scss
web/cobrands/bromley/base.scss
web/cobrands/sass/_mixins.scss

The shortlist "star" icons were losing their styling, because Bromley’s default button styling was more specific.
Bromley’s existing styles only affected "primary" buttons anyway (ie: elements with `.btn-primary` rather than just regular `.btn`) so buttons at the bottom of the first stage of the reporting form, for example, were still showing the default FMS white/grey gradient. I’ve not added any `.btn` styling in this pull request, so that’s not changed.
Fixes mysociety/fixmystreet-commercial#1659.

[Bromley] Fix shortlist button styling for inspectors

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm

Make it a bit easier to see if any reports have been sitting unsent for
some time

order unsent reports in admin summary by confirmed

---

CHANGELOG.md
Dockerfile
docker-compose.yml
script/bootstrap

This adds a `sudo` rule to the Docker image to ensure the application user can install packages.
It also adds support for skipping this if desired by setting `SKIP_PACKAGES_INSTALL` in the Docker Compose environment and, when building, enables `--build-arg VERSION_OVERRIDE=<foo>` to build arbitrary git commits instead of the most recent tagged release.
Fixes #2914

Allow Docker app user to install packages

---

perllib/FixMyStreet/Cobrand/UK.pm

Email from Norwich: "The Highways Agency Agreement covering Norwich is coming to an end this month. As of 1st March all new highways enquiries for the Norwich City Council district will need to be directed to Norfolk County Council."

[UK] Norwich/Norfolk highways agreement now ended.

---

perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/app/controller/admin/users.t

[UK Councils] Superusers cannot be edited by staff

---

CHANGELOG.md
bin/make-junctions-database
docs/customising/geocoder.md
perllib/FixMyStreet/Cobrand/UK.pm
perllib/HighwaysEngland.pm
t/app/controller/around.t

This is taken from the [sort-my-sign repo](https://github.com/mysociety/sort-my-sign). It allows the user to search for motorways names and junction numbers, e.g. "M60, Junction 2", and then geocodes that using a SQLite database created from Highways England markerpost locations.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1797

Add Highways England junction lookup

---

templates/web/fixmystreet.com/before_wrapper.html
web/cobrands/fixmystreet.com/_survey-banner.scss
web/cobrands/fixmystreet.com/base.scss

Big purple survey banner, which is hidden by default, and shown on 40% of pageloads, by JavaScript.
CTA button opens the surveygizmo survey in a new window/tab.
Banner can be hidden using the cross in the top right corner.
If the user clicks either the main CTA button, or the close button, a cookie is set that prevents the banner ever showing again.
Works on both the static pages, and the map pages. Here’s how it looks:
Fixes #2928.

[fixmystreet.com] Survey banner

---

perllib/FixMyStreet/Map/Bristol.pm

As requested by the client, this updates the URL for Bristol's map tiles.
Part of https://github.com/mysociety/fixmystreet-freshdesk/issues/138

[Bristol] Update URL for map tiles

---

templates/email/bexley/_problem-confirm_footer.html
templates/email/default/problem-confirm.html
templates/web/bexley/email_sent.html
templates/web/bexley/front/pre-steps.html
templates/web/bexley/tokens/_extras_confirm.html

This adds a COVID-19 informational banner to the following places:
- The homepage
- Problem confirm email
- Page when you create a problem as an unregistered user
- Page when you create a problem as a registered user
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/139
---
---
---
---

[Bexley] Add COVID-19 messages

---

perllib/FixMyStreet/Script/Inactive.pm

Without the brackets the user's name was interpreted as a separate
recipient.
Fixes #2935

Fixes the To header when sending emails about inactive accounts.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/DB/ResultSet/Contact.pm
perllib/FixMyStreet/SendReport.pm
t/app/controller/report_new_staff.t

Staff-only categories were added previously, but only in terms of them being there when making a new report. Turns out you couldn't *send* those reports, whoops, or e.g. set up admin templates for them or anything.

Staff only cats in admin 

---

CHANGELOG.md
bin/send-reports-failure-summary
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/CheshireEast.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/Rutland.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
perllib/FixMyStreet/Queue/Item/Report.pm
perllib/FixMyStreet/Roles/ConfirmOpen311.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport.pm
perllib/FixMyStreet/SendReport/Email.pm
perllib/FixMyStreet/SendReport/Open311.pm
t/app/sendreport/email.t
t/app/sendreport/open311.t
t/cobrand/bexley.t

This refactors send reports to not be one monolithic function, and moves the per-row processing to its own package for future use elsewhere. It also takes the 'verbose' end summary of failures out to its own script.

Refactor send reports

---

.cypress/cypress/integration/buckinghamshire.js
bin/fixmystreet.com/buckinghamshire-flytipping
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Roles/BoroughEmails.pm
t/cobrand/bucks.t
web/cobrands/buckinghamshire/assets.js

- Sends district categories to old district email addresses using the `borough_email_addresses` cobrand feature from TfL
- Updates cobrand JS to allow reports in specific ex-district categories to be made off the road assets
- Uses the answer to the 'road placement' question on the Flytipping category to recategorise into a new ex-district category which is sent via email.
To test, add something like the following to your `COBRAND_FEATURES` setting:
```
borough_email_addresses:
buckinghamshire:
districts:
- email: district-a@example.org
areas:
- 2255
- email: district-b@example.org
areas:
- 2256
- email: district-c@example.org
areas:
- 2257
- email: district-d@example.org
areas:
- 2258
```
and then create a new devolved `Flytipping (off-road)` category which sends email to `districts`, as …

[Buckinghamshire] Handle ex-district categories correctly

---

web/js/duplicates.js

Without this check, it is possible for calls to overlap and end up with
a situation whereby both the duplicate list and the form are hidden.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1796

Only one duplicate call in progress at once.

---

bin/fixmystreet.com/buckinghamshire-flytipping

The ex-districts are not associated with areas any more, and the Bucks
body will be associated with a different area ID once the generation is
updated. The names are fixed, so use them instead.

[Buckinghamshire] Fix flytipping closure script.

---

CHANGELOG.md
bin/fetch
bin/fetch-comments
bin/fetch-comments-24hs
bin/fetch-reports
bin/fetch-reports-24hs
bin/open311-update-reports
conf/crontab-example
conf/general.yml-example
cpanfile
cpanfile.snapshot
perllib/FixMyStreet.pm
perllib/Open311/GetServiceRequestUpdates.pm
perllib/Open311/GetServiceRequests.pm
t/open311/getservicerequests.t
t/open311/getservicerequestupdates.t

This PR combines fetch-comments and fetch-reports into one fetch script, and allows command line selection of start/end times.
It also (March 2020) parallelizes the fetching of comments - first commit providing a config number of workers to run in parallel, the second making a min/max with a timeout so you can start with lower and add more if backends are slow.

Improve fetch scripts

---

docs/running/index.md

Removes documentation about restricting access to /admin

---

bin/send-reports
perllib/FixMyStreet/Queue/Item/Report.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/FixMyStreet/SendReport.pm
perllib/FixMyStreet/SendReport/Noop.pm
t/cobrand/zurich.t
t/cobrand/zurich_attachments.txt

This PR does two things - firstly tidies up the command parameters so verbose/debug are clear as to what they're doing, they've always confused me. Then it moves the code-based "should we skip this report" behaviour to the DB query, so that the sending daemon can then use the same query and not look at reports it will then go on to skip, iyswim. [skip changelog]
So #2924 will need rewriting on top of this, but that's easier if it's merged and agreed a good thing to do!

Sending reports tidying

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/cobrand/bexley.t

Bexley wish to send Confirm reports to a different P1 email address than other reports, and want to treat any Oil spillage report as a P1.
This goes alongside /data/servers commit 92332bdb for the Open311 part.

[Bexley] P1 updates

---

perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Bristol.pm
perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/Cobrand/Lincolnshire.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Cobrand/TfL.pm

Without allowing through the Highways England body, clicking on a
Highways England road in these cobrands would leave no categories
to be selected.

[UK] Show Highways England categories on cobrands.

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/Mock/Tilma.pm
web/cobrands/tfl/assets.js

Two small things:
* Increase stroke opacity of red routes - in Firefox/Edge on Windows, having a translucent stroke causes a large slowdown in page painting - see animation when I drag the red route into view:
* Restrict HE categories to HE roads - The checks added in 285e183 missed the TfL cobrand, and so the Highways England categories are currently appearing everywhere.

[TfL] Couple of bug fixes

---

templates/web/fixmystreet-uk-councils/report/form/user_name.html

Requested by the folks at Bucks. I figure it makes sense to change it across the board though [for all UK councils that include the checking code.]
It’s annoying that we even have to mandate a "full name" (who says everyone’s "full name" has a space in it!?) but it’s a requirement of most councils’ case management systems.
At least this way, users get an up-front hint that they need to enter a full name (ie: with at least two words) before they submit the form and the validation runs.

[UK] Make it clearer that full name is required.

---

perllib/FixMyStreet/Cobrand/Peterborough.pm
t/cobrand/peterborough.t

Ignore (for Open311-sending purposes) any questions whose code starts
"PCC-", so that it is easier to use the admin to add extra questions,
and move the removal of the extra questions to a more normal location
so answers are not lost when extra fields is reset post-send.
For freshdesk 544 and 545.

[Peterborough] Improve extra question handling.

---

perllib/FixMyStreet/Cobrand/Bristol.pm

Category groups were turned on for Bristol due to Highways England using groups, turns out all Bristol categories are in a "Highways" group which we should remove because it wasn't used/displayed previously. [skip changelog]

[Bristol] Remove Open311 groups.

---

script/bootstrap

When working locally it’s not convenient to always run `install_packages` as part of `./script/update`, so this commit allows you to define the `SKIP_PACKAGES_INSTALL` environment variable to stop that.

Respect SKIP_PACKAGES_INSTALL when not in Docker too

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/Open311/PopulateServiceList.pm
t/app/controller/admin/bodies.t
t/open311/populate-service-list.t
templates/web/base/admin/bodies/contact-form.html

Adds a new tickbox to the contact editing form that protects the category
and group names from being changed by Open311.
For mysociety/fixmystreet-commercial#1776

Add contact flag to protect category/group names from Open311 changes

---

CHANGELOG.md
web/cobrands/fixmystreet/fixmystreet.js

If the same category is in multiple groups, upon moving the pin and fetching new categories from the server it would then pick the last instance of that category in the list. Instead of using val(), pick the correct entry in the previously selected optgroup. Fixes #2962.

Maintain category group on pin move.

---

CHANGELOG.md
t/app/controller/report_new_staff.t
templates/web/base/report/new/form_user_loggedin.html
web/cobrands/fixmystreet/fixmystreet.js

If a category is marked private, new reports are always marked private regardless of the setting of the private checkbox shown to relevant staff when making a new report. So tick/disable this box in that situation to prevent any confusion. Fixes #2961

Disable staff private tickbox if category private.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
templates/web/base/report/new/report_import.html

If the web param is used, show an error web page rather than the normal
plain text output. Also do the normal remember/show uploaded photos
feature, and hide the inputs better if unneeded.
Fixes #2233.

Error page when submitting /import with web param.

---

CHANGELOG.md
bin/send-daemon
conf/general.yml-example
conf/send-daemon.service.example
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Queue/Item/Report.pm
perllib/FixMyStreet/Script/Reports.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/cobrand/northamptonshire.t

This PR adds a daemon using Parallel::ForkManager. Then it does a noddy thing for updates, only locking per body, not per update, which seemed easier given the current code, but discussion there welcome too. The daemon will spin up some number of children each of which will just repeatedly look for reports(/updates) to send.
Todo:

Sending dæmon

---

CHANGELOG.md
perllib/DBIx/Class/SQLMaker/Pg/ServerCursor.pm
perllib/DBIx/Class/Storage/DBI/Pg/ServerCursor.pm
perllib/DBIx/Class/Storage/DBI/PgServerCursor.pm
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/DB/Schema.pm

When investigating the slowness of update export, it turns out the main culprit was the prefetch of user by the BANES specific code, rather than a join and adding the one column needed. (The user's extra column is very slow to fetch, perhaps need something to go through and clear out bad session IDs.). Also spotted a few other prefetches that could be joins around the place.
However by the time I'd realised that I had also implemented using server side cursors for the export, which should also help speed up as it won't have to load all the results into memory first as normal. It also perhaps means we can switch e.g. the alerts code or update-all-reports code from being raw SQL/cursor to using objects (assuming that was a reason it was written like that).

Speed up dashboard export

---

CHANGELOG.md
cpanfile
cpanfile.snapshot

Update Getopt::Long::Descriptive to stop warning.

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_update.t

Upon report confirmation, we look to see if there is an auto-response response template in the database for the Open (confirmed) state. If there is, we add that immediately to the new report as its first update (as if it had just come in via Open311).
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1832

Allow a template to be an initial update on reports

---

CHANGELOG.md
web/cobrands/sass/_layout.scss

Not sure why this margin was even here. Appears to have been present since the original FMS redesign in 2012.
It certainly isn’t required, and actually causes weird off-centre alignment, which is especially noticeable on cobrands with a narrower homepage search box form.

Remove unnecessary margin-right on #postcodeForm

---

bin/fixmystreet.com/fixture

The TfL `council_area_id` sub uses the `$_[0]` argument to call other cobrand methods, but that argument wasn't being passed in correctly in the `bin/fixmystreet.com/fixture` script.
Fixes #3018

Pass class argument to council_area_id in fixture script

---

bin/fixmystreet.com/banes-close-reports
perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm

B&NES have sent us a spreadsheet with a list of reports along with their
IDs that they want marking as "No further action" along with a specific
update.
This script takes a comma-separated list of report IDs and closes those
reports, leaving the appropriate comment text.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1867

[BANES] Add script to close redundant reports

---

perllib/FixMyStreet/Cobrand/EastSussex.pm
t/cobrand/eastsussex.t

Fix issue sending notices. Store the original detail so we can reset back to it easily. (Also use a function not also used by update sending, in case that's used in future and it would break.) [skip changelog]

[East Sussex] FIx issue sending notices, tidy up detail reset.

---

perllib/FixMyStreet/Cobrand/Bristol.pm

Not sure how we've managed to go this long without this. PRd despite being a small change because I couldn't remember if there was a good reason it wasn't there.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1882

[Bristol] Add admin_user_domain

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Default.pm
perllib/FixMyStreet/Cobrand/EastSussex.pm
perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/FixMyStreet/DB/Result/Problem.pm
perllib/FixMyStreet/DB/ResultSet/Nearby.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
t/app/controller/admin/bodies.t
t/app/controller/report_updates.t
t/roles/translatable.t
templates/web/base/admin/bodies/contact-form.html
templates/web/isleofwight/report/_item_heading.html

Add a tickbox to the category admin, and do not allow updates on reports made in those selected categories.
Fixes #2991.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1871
Before that, it also moves the "category_row" functionality to a database relationship, so that it could use that in its feature, and also fix the issue I had spotted that e.g. admin report list was doing a db lookup once per row. Sadly, due to quite a few shared-column names this was trickier than it looked (and some places it's aliased differently, and there appears to be an issue whereby if you try and save an update whose associated problem is an object on which the contact has been looked up, it fails, I gave up tracking that one down :-/ ). But hopefully is okay now, at least all the places the …

Interface for disabling updates for certain categories

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/DB/ResultSet/Contact.pm
t/cobrand/bexley.t
t/cobrand/tfl.t

Fixes https://github.com/mysociety/fixmystreet/issues/2994
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1874
First commit is shared with #3011 and #3012 to allow the group lookup to be done as part of the normal DB call.

Include category group in CSV export

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/admin/bodies.t
t/app/controller/report_updates.t
templates/web/base/admin/bodies/contact-form.html
templates/web/base/report/update/form_state_checkbox.html
templates/web/fixmystreet.com/report/update/form_state_checkbox.html

Fixes #2992. Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1872.
Does need a doc update but I will do that at same time as #2991 doc given it'll be same screenshot, same place. In fact, might as well wait for #2989 to only do the screenshot once!
Includes same first commit as mentioned in #3011

Add way to disallow report reopening on reports in a category

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/DB/Result/Contact.pm
t/app/controller/admin/bodies.t
templates/web/base/admin/bodies/_category_field.html
templates/web/base/admin/bodies/contact-form.html
web/cobrands/fixmystreet/staff.js

If you rename an Open311 category, it will only get reinstated/deleted
by the Open311 populate script shortly after, and can cause issues due
to the problem category renaming that occurs. Fixes #2957.

Disable category rename on Open311 categories.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/admin/bodies.t
t/app/controller/report_new_anon.t
templates/web/base/admin/bodies/contact-form.html

Add an interface to enable a category to accept anonymous reports, plus
the code to handle permitting this.
It's only available on single body cobrand sites in the default
configuration.

admin interface for per category anonymous reporting

---

web/js/map-fms.js

Display the current year, rather than hard-coding a year, in the map copyright notices.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1879

Make year in map copyright notices dynamic

---

.cypress/cypress/integration/peterborough.js
bin/fixmystreet.com/fixture
web/cobrands/fixmystreet/assets.js

Resetting using the class could cause an incorrect "you can pick an
$item from the map" message to be display when asset_groups were being
used. This was happening when the unselect event was firing after the
category change event and then updating the new message using the
message from the unselected layer.
Fixes mysociety/fixmystreet-commercial#1888

reset asset select message by id when asset unselected

---

bin/send-failure-summary
conf/crontab-example
perllib/Open311/PostServiceRequestUpdates.pm
t/open311/post-service-request-updates.t

This will include details of failed updates along with reports.
We may want to change the name of the script to reflect this, `send-failure-summary`, perhaps.

Include updates in failure summary report

---

CHANGELOG.md
bin/update-schema

`pg_constraint.consrc` has [been removed in Postgres 12](https://www.postgresql.org/docs/12/release-12.html), and this is the recommended replacement.

Fix update-schema constraint check on Postgres 12

---

CHANGELOG.md
bin/import_categories
bin/tfl/import_categories
perllib/FixMyStreet/App/Controller/Admin/Templates.pm
perllib/FixMyStreet/App/Controller/Admin/Triage.pm
perllib/FixMyStreet/App/Controller/Admin/Users.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/JSON.pm
perllib/FixMyStreet/App/Controller/My.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Hounslow.pm
perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/DB/Result/Contact.pm
t/app/controller/report_new.t
templates/web/base/reports/_list-filters.html

Start off making sure everything is using `->groups` consistently, why not, then add a tiny bit to reporting so that if two bodies have a contact with the same name but in different groups, one set of groups isn't lost (spotted with Highways England but could theoretically happen elsewhere).
Hopefully fixes https://github.com/mysociety/fixmystreet-commercial/issues/1854.

Fix for multiple categories with same name in different group set

---

perllib/FixMyStreet/SendReport/Email.pm
t/Mock/MapIt.pm
t/app/sendreport/email.t

No longer required since we have a single email address for the council now.

[UK] Remove Somerset West and Taunton special destination handling

---

CHANGELOG.md
perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t

What I'll be doing on Bromley will have a devolved Open311 contact, and this script keeps deleting it as it only spots email addresses.

[Open311] Do not remove any devolved contacts.

---

CHANGELOG.md
perllib/FixMyStreet/App.pm
perllib/FixMyStreet/App/Controller/Auth.pm
perllib/FixMyStreet/Cobrand/UK.pm
perllib/FixMyStreet/Gaze.pm
t/app/controller/alert.t
templates/web/base/alert/_list.html
templates/web/base/alert/updates.html
templates/web/base/report/display_tools.html
templates/web/base/report/form/user_loggedout_by_email.html
templates/web/fixmystreet.com/auth/form_extra.html

This shows a recaptcha to logged out users from non-UK IP addresses on alert and report/update forms. For https://github.com/mysociety/sysadmin/issues/1302.

 [fixmystreet.com] Add option for recaptcha.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/Update.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/Script/Inactive.pm
t/app/controller/alert_new.t
templates/web/fixmystreet.com/about/privacy.html

If a user is sent email alerts they've signed up for, but otherwise doesn't log in to the site, we probably don't want to delete their account as 'inactive'. We could/would send them the "about to be deleted" warning email, but that could be confusing because their account isn't "inactive", as dur, they're getting email alerts. (If an email alert bounces, they'll be unsubscribed and then not get emails and account will get deleted as normal.) So when an alert is sent, take that as activity on the user's account and update the last active time.
Also update .com privacy page to say that is what we are doing. Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1661

Mark user as active when sent an email alert

---

perllib/FixMyStreet/Cobrand/IsleOfWight.pm
perllib/FixMyStreet/Cobrand/Lincolnshire.pm
perllib/FixMyStreet/Cobrand/Peterborough.pm

For https://github.com/mysociety/fixmystreet-commercial/issues/1778
Already reviewed at #2903. [skip changelog]

[UK Councils] Enable private photo uploading on cobrands whose backend supports it

---

perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/FixMyStreet/Geocode/OSM.pm
t/app/controller/admin/report_edit.t
templates/web/base/admin/reports/edit.html
web/cobrands/hackney/assets.js

- Allow more cobrand control over geocoder parameters
- Some Hackney-specific geocoder tweaks
- Work around an issue with Hackney WFS server returning features outside of the BBOX param
- Show array contents instead of `ARRAY(0x5587da81ffb0)` in report admin extra data

[Hackney] A few bug fixes that have shaken out of testing

---

templates/email/default/submit-example.txt
templates/web/bromley/about/faq-en-gb.html
templates/web/eastherts/about/faq-en-gb.html
templates/web/fixmystreet.com/contact/address.html
templates/web/greenwich/about/faq-en-gb.html
templates/web/hart/about/faq-en-gb.html
templates/web/stevenage/about/faq-en-gb.html

UKCOD is now formally known as mySociety, this PR hopefully sweeps up all the existing mentions of the old name.
Sidenote: some of these cobrands (and they are the older ones) are using very old FAQ text and should maybe be prompted to review/update?

Change company name

---

perllib/FixMyStreet/Cobrand/Hounslow.pm

Requested in ticket 659 on Freshdesk.

[Hounslow] Allow two email categories to be shown.

---

cpanfile
cpanfile.snapshot

LWP::UserAgent (used by MapIt and Open311 integrations) uses this
cert bundle by default to verify peers.
Fixes #3088

Upgrades the Mozilla::CA module to 20200520.

---

CHANGELOG.md
perllib/FixMyStreet/Geocode/Bing.pm
t/Mock/Bing.pm
t/geocode/bing.t

Add a couple of parameters to hopefully improve results, and make sure the returned locality is included in the summary address.
Sometimes (I think with results with less information?), Bing is including no information beyond the country in the result string. Make sure the locality is included if not already present. Also ignore our server IP, and ask for 10 results (default was changed to 5 at some point).
Helps with this example query, at least, and I don't think it could harm any other.
Before:
After:

Improve Bing geocoder results.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/cobrand/bromley.t
t/open311/post-service-request-updates.t
templates/web/bromley/report/update/form_state_checkbox.html

First fixup is to stop the bromley tests requesting gov.uk bank holiday live, whoops. Second is because if one entry in a list is returned to SOAP, it's auto-promoted to the single entry directly, which we don't want, we want to always loop.
Then the other two are to only change the Bromley endpoint for the main endpoint, so waste updates will be posted correctly to the right endpoint, and hide the fixed checkbox because users can leave updates but can't do that.

[Bromley] waste update tweaks

---

bin/fixmystreet.com/bromley-fetch-waste
perllib/FixMyStreet/App/Controller/Hercules.pm
perllib/FixMyStreet/App/Controller/Open311/Updates.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/cobrand/bromley.t

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1898. [skip changelog]
As we already had an Echo integration present here, seemed easier to use it directly rather than go via open311-adapter requesting all the IDs. Also given I was here anyway and it didn't seem to take much longer, wrote the push-notification way of doing it should we use that method.
Wondered about having a F::C::Bromley;:Waste package for all this maybe, what do you think?

[Bromley] Code for fetching updates

---

conf/general.yml-docker

Letting the code pick a default MAPIT_URL means it picks port 8000,
which will not work with the current Docker container setup.
Fixes https://github.com/mysociety/fixmystreet/issues/3090

[Docker] Specify MAPIT_URL.

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/FixMyStreet/Email.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/SendReport/Email.pm
t/app/controller/auth_social.t
t/cobrand/hackney.t
t/email.t

Adds cobrand hook for setting domain of VERP emails, enables this for Hackney using a cobrand feature.

[Hackney] Custom domain for email envelope

---

perllib/FixMyStreet/Cobrand/TfL.pm
t/Mock/MapIt.pm
t/Mock/Tilma.pm
t/cobrand/tfl.t

Because Hackney doesn't have any matching categories for TfL red routes
skip sending the body, otherwise you get a "no contact details" message
when you click on a red route in Hackney

[Hackney] skip hackney categories for TfL red routes

---

CHANGELOG.md
web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/assets.js

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1920
And default as I found another type of street light not covered when I did https://github.com/mysociety/fixmystreet/pull/3070

Fix duplicate asset selection message

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Users.pm

Sort the table when showing search results, and show users without name at the bottom, rather than at the top.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1925

Better sort admin user table.

---

CHANGELOG.md
perllib/FixMyStreet/DB/Result/ModerationOriginalData.pm

Fixes https://github.com/mysociety/fixmystreet/issues/2837

Improve moderation diff display in few small ways

---

CHANGELOG.md
conf/general.yml-example
perllib/FixMyStreet/App/Controller/Auth.pm
t/app/controller/auth.t

If switched on, sends first five letters of the SHA1 hash of the entered
password to HIBP's API, which then returns all matching hashes in their
database of breached passwords. If we find a match, tell the user they
need to pick a different password.
Questions to answer - leave it like this, or if the count is very low, allow it to go through anyway? (Read the count section of https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/ for background)
Future work - could on login check password against this and alert the user to change it if present?

Add option to check password on Have I Been Pwned.

---

web/cobrands/peterborough/base.scss
web/cobrands/tfl/_colours.scss
web/cobrands/tfl/base.scss

In Peterborough's case, having them repeated meant they took precedence over the sub map links overrides. TfL's just didn't seem needed.

[Peterborough,TfL] Remove unneeded CSS.

---

perllib/FixMyStreet/Map/Bing.pm
perllib/FixMyStreet/Map/Bromley.pm
perllib/FixMyStreet/Map/FMS.pm
templates/web/base/maps/_sub_links.html
templates/web/base/maps/bing.html
templates/web/base/maps/google-ol.html
web/cobrands/bromley/map.js
web/js/map-OpenLayers.js
web/js/map-bing-ol.js
web/js/map-fms.js
web/js/map-mastermap.js

Adds a button to the map controls on FMS.com that toggles between the roads and aerial views:

[fms.com] add toggle between aerial and roads maps

---

CHANGELOG.md
bin/fixmystreet.com/banes-close-reports
bin/fixmystreet.com/buckinghamshire-flytipping
bin/one-off-update-staff
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/App/Controller/Admin/Triage.pm
perllib/FixMyStreet/App/Controller/Moderate.pm
perllib/FixMyStreet/App/Controller/Questionnaire.pm
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/DB/Result/Comment.pm
perllib/FixMyStreet/Script/ArchiveOldEnquiries.pm
perllib/Open311/UpdatesBase.pm
t/app/controller/admin/report_edit.t
t/app/controller/admin/update_edit.t
t/app/controller/report_updates.t
t/app/model/comment.t
t/open311.t

Given the user, we can infer the name if not provided, and the extra
data if a staff user. We can also provide defaults for various other
fields. Always have superuser take precedence over from_body.

Centralise update creation to include fields.

---

t/app/controller/admin/bodies.t
t/cobrand/isleofwight.t
templates/web/base/admin/bodies/contact-form.html
templates/web/fixmystreet-uk-councils/admin/bodies/_updates_disallowed_hint.html
templates/web/fixmystreet.com/report/_updates_disallowed_message.html

And fix bug in .com showing of original reporter only message I just spotted.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1886 [skip changelog]

[UK] Show message if site-wide update disallowed.

---

CHANGELOG.md
Vagrantfile
bin/docker.preinit
bin/install_packages
bin/site-specific-install.sh
docker-compose.yml
docs/install/manual-install.md
docs/updating/ami.md
docs/updating/index.md
script/bootstrap

Your site user may not have access to sudo, and your admin user may cause permission issues if used to do the git checkout, or the Perl module installation. Document the separate script to install system packages instead.
Fixes #2930. I think it causes too much confusion to have it run sudo-level commands, when it's a user-level script. I realise this was introduced because a new Perl module needed a new library package, I've added some documentation about updating.
I've left in the Docker fms user being able to run bin/install_packages, don't see why not, and have changed the preinit to run this as well. I'm not sure if that's everything.

Do not have bootstrap run sudo commands.

---

perllib/FixMyStreet/DB/Result/Comment.pm
t/app/controller/report_updates.t

The changes in 67823bc78 create the necessary metadata at the creation
of a Comment object, but if the user is not included at that point but
later (as is done by the normal public update flow), then it would not
be created. Wrap the user accessor so we can make sure it is set.

Spot user set on update not at object creation.

---

CHANGELOG.md
t/app/controller/around.t
t/app/controller/report_inspect.t
t/cobrand/hackney.t
templates/web/base/admin/report-category.html
templates/web/base/admin/triage/_list-filters.html
templates/web/base/report/_inspect.html
templates/web/base/report/_item.html
templates/web/base/report/new/_category_select.html
templates/web/base/report/new/category.html
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/reports/_list-filters.html
web/cobrands/fixmystreet/fixmystreet.js

Fixes #3110. And while fixing, spotted a variety of places where category lookup on a hash would fail.

Allow deep linking with both category+group, and fix various template lookups

---

t/app/controller/contact_enquiry.t
templates/web/base/contact/enquiry/index.html

This is largely to resolve an issue with the TfL other category
appearing in the contact form even though it is disabled, and hence has
no contact details.

[Hounslow] skip disabled contacts in enquiry form

---

web/cobrands/fixmystreet/fixmystreet.js

The recaptcha used by fixmystreet.com uses a textarea, so this makes sure it is copied and sent.

Include textarea in alert email form copy.

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/cobrand/oxfordshire.t
templates/email/oxfordshire/submit.html
templates/email/oxfordshire/submit.txt
templates/web/oxfordshire/footer_extra_js.html
templates/web/oxfordshire/report/new/roads_message.html
web/cobrands/fixmystreet/assets.js
web/cobrands/oxfordshire/assets.js
web/cobrands/oxfordshire/base.scss

This adds asset layers to the map for OCC for:
- drains
- grit bins
- streetlights
- traffic lights
- trees
It also adds a roads layer for access to the USRN.
It includes the asset id and USRN in the description sent over Open311.

[Oxfordshire] display asset layers on map

---

.cypress/cypress/integration/oxfordshire.js
bin/browser-tests
bin/fixmystreet.com/fixture
perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/Open311/PostServiceRequestUpdates.pm
t/app/controller/report_inspect.t
t/cobrand/oxfordshire.t
templates/email/oxfordshire/submit.html
templates/email/oxfordshire/submit.txt
templates/web/base/report/_inspect.html
templates/web/oxfordshire/footer_extra_js.html
templates/web/oxfordshire/report/inspect/_inspected.html
templates/web/oxfordshire/report/inspect/_raise_defect.html
templates/web/oxfordshire/report/new/roads_message.html
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/staff.js
web/cobrands/oxfordshire/assets.js
web/cobrands/oxfordshire/base.scss

In the past Oxfordshire had a way for inspectors to "instruct a defect", which generated a CSV which got emailed to Oxfordshire with a list of defects.
They now want to bring this functionality back, but instead of emailing a CSV they want it to call an API.
As a first step towards that goal, this adds back some of the instruct defect functionality that was removed in 68e18ff.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/1846

[Oxfordshire] Add instruct defect functionality back in

---

bin/zurich/overdue-alert
perllib/FixMyStreet/Cobrand/Zurich.pm
t/cobrand/zurich.t
templates/web/base/admin/users/_form_details.html
templates/web/base/admin/users/form.html
templates/web/zurich/admin/_index_table.html
templates/web/zurich/admin/index-dm.html
templates/web/zurich/admin/index-sdm.html
templates/web/zurich/admin/problem_row.html
templates/web/zurich/admin/report_edit-sdm.html
templates/web/zurich/admin/reports/edit.html
templates/web/zurich/admin/reports/index.html
templates/web/zurich/admin/users/form.html
templates/web/zurich/header.html
web/cobrands/sass/_admin.scss
web/cobrands/sass/_base.scss

Adds the bits of functionality required. Starts off doing some refactoring that makes no actual changes to some templates and code (oh, and one small bug fix). Then sets up marking users/reports as internal, and the various bits.
This is a replacement PR for https://github.com/mysociety/fixmystreet/pull/2855 where almost all this was already reviewed - only bits to be reviewed are https://github.com/mysociety/fixmystreet/commit/fde6fcf77f3dffc9d9abef8a8711ad980e55ce17, https://github.com/mysociety/fixmystreet/commit/2025cbf1175f469178db7ab72e9bba6115fe20d7, and the base https://github.com/mysociety/fixmystreet/commit/99996e1c8f96e6eaf6b2f2643937c75e5627b47f.
Fixes mysociety/fixmystreet-commercial#1698
Fixes mysociety/fixmystreet-commercial#1699
Fixes mysociety/fixmystreet-commercial#1700 …

[Zurich] Internal reports

---

perllib/FixMyStreet/App/Controller/Contact.pm
t/app/controller/contact.t

Tiny change I just noticed when I wondered why someone didn't have the links added [skip changelog]

Lowercase contact email when looking for user.

---

perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/UKCouncils.pm
t/cobrand/oxfordshire.t

Part of https://github.com/mysociety/fixmystreet-commercial/issues/1847
This deals with the USRN aspect of the data to be sent for a defect, but not the various item type codes.

[Oxfordshire] Send raise_defect flag to open311 for inspected reports

---

perllib/FixMyStreet/App/Controller/Dashboard.pm
t/app/controller/dashboard.t

If category groups are enabled, the CSV export includes a subcategory,
but it was only fetching a valid groups value if the row's contact was
found. [skip changelog]

Do not error in export if report has bad category.

---

perllib/Open311/GetServiceRequests.pm
t/open311/getservicerequests.t

At the moment if you fetch a report in a staff category it will still be
created but will be in the Other category. Given that some staff
categories are marked as private this can allow reports that should be
private to be put in a public category.

[Open311] use staff categories when fetching reports

---

bin/update-schema
db/downgrade_0074---0073.sql
db/schema.sql
db/schema_0074-add-users-full-text-search-index.sql
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/App/Controller/Admin/Users.pm
perllib/FixMyStreet/DB/ResultSet/Comment.pm
perllib/FixMyStreet/DB/ResultSet/Problem.pm
perllib/FixMyStreet/DB/ResultSet/User.pm
perllib/FixMyStreet/Roles/FullTextSearch.pm
t/app/controller/admin/users.t

One "bug" fix - forcing postgresql to use the index in situations where it does not want to.
And then adding full text search to the user admin search as well. Plus side - is quicker. Down side - can no longer search for part of name/phone/email only whole words. Perhaps alternative solution would be to search whole fields first (for exact match) and only do ilike search if no results to that. Or just say is okay as is. Review the first bug commit regardless please :)

Full text admin user search

---

docs/_layouts/pro.html

The Pro manual at `/pro-manual` uses a separate jekyll layout that mimics the output of the WordPress site at societyworks.org.
Our copy had fallen out of date. This commit:
* Updates the Google Fonts requested (was Rubik, now Lato and Lora).
* Updates the header nav menu content to match the live site.
* Replaces fixmystreet.com/pro URLs with societyworks.org URLs.
* Updates the footer legal text to match the live site.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/1949

[fixmystreet.org] Update "pro" layout to latest SocietyWorks content

---

CHANGELOG.md
bin/csv-export
perllib/Catalyst/Authentication/Credential/AccessToken.pm
perllib/FixMyStreet/App/Controller/Dashboard.pm
perllib/FixMyStreet/App/Controller/Reports.pm
perllib/FixMyStreet/Cobrand/BathNES.pm
perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/TfL.pm
perllib/FixMyStreet/Cobrand/Zurich.pm
perllib/FixMyStreet/Reporting.pm
t/app/controller/dashboard.t
templates/web/base/dashboard/index.html
templates/web/base/dashboard/status.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1926
From the command line, can call with export=2 instead of 1 to get the 202 flow, otherwise is as before.

Offline CSV generation

---

docs/_layouts/pro.html
docs/_sass/fixmystreet-pro.scss

Matches the corresponding change on the societyworks.org site:
https://github.com/mysociety/orgsites/issues/1156

[Docs] Remove mySociety header from FMS Pro manual

---

CHANGELOG.md
templates/web/base/admin/report-category.html
templates/web/base/report/inspect/information.html
web/cobrands/bexley/assets.js
web/cobrands/buckinghamshire/assets.js
web/cobrands/cheshireeast/assets.js
web/cobrands/fixmystreet/assets.js
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/fixmystreet/staff.js
web/cobrands/hounslow/assets.js
web/cobrands/isleofwight/assets.js
web/cobrands/peterborough/assets.js
web/cobrands/sass/_base.scss
web/js/map-OpenLayers.js

Couple of these commits have questions I'm not sure of the answer to. The first does fix a bug in that if you currently go to e.g. https://www.fixmystreet.com/report/new?longitude=-0.604850&latitude=51.710853&category=Street+light+dim you'll see the selection of other assets is a bit weird - a click doesn't change asset, it deselects then snap-to-nearest kicks in so it sort of works but the next click then gets confused, and so on. With this change, all the asset layers are underneath so it's better. I'm not sure if it affects anything else, though.
The second made my code a bit simpler, I wasn't sure why the update was restricted to only the inspector form. I realise the around page may have a hidden form with fields in that would match and be updated also, but if you ever then made a …

Allow inspectors to change asset of report

---

web/cobrands/fixmystreet/assets.js

Of course, only noticed this immediately after merge/deploy.  [skip changelog]
If you click the change asset button on a report page that was loaded inline from a map list page, you want to see assets around the report and not the centre of the map.

Zoom in to asset if selected when changing asset.

---

CHANGELOG.md
web/cobrands/fixmystreet/assets.js

To see these issues on live, go to https://report.peterborough.gov.uk/report/new?longitude=-0.247059&latitude=52.556479 - click middle of St Margarets Road then select Street Lighting, then Trees, then Street Lighting, then Trees. You'll see there are now two green pins (fixed by 80d47db and 919cb2b) and it says "You can pick a light from the map" (fixed by 4b659c6).
Then click a different tree asset (up to the left there are plenty) and change category to Street lighting, you'll see there are now two selected assets (fixed by 2f7ce01).
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1888

Fix number of asset changing confusions

---

perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
t/Mock/MapIt.pm
t/cobrand/hackney.t

This adds a cobrand hook to validate the email address provided when editing a contact
in the admin.

[Hackney] Allow editing & addition of contacts with special destination addresses

---

perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/App/Controller/My.pm
t/app/controller/around.t

Two rows would be returned because the district and county `Other` contacts have different `extra` fields, so this adds a `WHERE` for the Oxfordshire cobrand to only fetch the county contact.
This probably isn't the best way to fix the problem.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1964

[Oxfordshire] Hide duplicate ‘Other’ category from map filters

---

templates/web/centralbedfordshire/footer_extra_js.html
templates/web/centralbedfordshire/report/new/roads_message.html
templates/web/fixmystreet.com/footer_extra_js.html
web/cobrands/centralbedfordshire/assets.js

Adds an invisible highways layer which is used to check ownership of roads and prevents reports that aren't on CBC-responsible roads.

[Central Beds] Add highways layer and prevent reports made off CBC roads

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_open311.t

Provide a stopper per disable message, rather than per question
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1997

fix using multiple disable messages on category questions

---

.cypress/cypress/integration/duplicates.js
CHANGELOG.md
perllib/FixMyStreet/App/Controller/Test.pm
templates/web/borsetshire/footer_extra_js.html
web/cobrands/fixmystreet/fixmystreet.js

The stopper checking code is triggered using the category_change event
which, by default also calls the duplicate check code. This meant that
when an extra question dropdown with an associated stopper was updated
the duplicate check re-ran and the duplicate reports panel was re-shown.
The invocation of category_change on the extra questions now includes
the skip_duplicates parameter to avoid this.
Fixes mysociety/fixmystreet-commercial#2007

do not trigger duplicate check with stopper check

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/View/Web.pm
perllib/FixMyStreet/Script/Alerts.pm
perllib/FixMyStreet/Template.pm
perllib/FixMyStreet/TestMech.pm
t/app/controller/alert_new.t
t/app/controller/my.t
t/app/controller/questionnaire.t
t/app/controller/report_updates.t
templates/email/default/_email_comment_list.html
templates/email/default/_email_comment_list.txt
templates/email/fixamingata/_email_comment_list.html
templates/web/base/admin/users/log.html
templates/web/base/my/my.html
templates/web/base/questionnaire/index.html
templates/web/base/report/update.html

Response templates can now include HTML which is sanitized and rendered when shown on the front end and in update emails. This also extends to updates left by staff/superusers.
Not 100% happy with the approach but at this point would be good to have a second pair of eyes before I dig any further into the rabbit hole.
For https://github.com/mysociety/fixmystreet-commercial/issues/1928

Allow HTML in response templates and updates from staff

---

.cypress/cypress/integration/simple_spec.js
.travis.yml
CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Test.pm
t/app/controller/report_new.t
templates/web/base/report/form/submit.html
templates/web/base/report/form/user_loggedout_by_email.html
templates/web/base/report/new/form_report.html
templates/web/base/report/new/form_user_loggedin.html
templates/web/base/report/new/login_success_form.html
templates/web/base/report/new/oauth_email_form.html
templates/web/base/report/update/form_user_loggedin.html
templates/web/zurich/report/new/fill_in_details_form.html
web/cobrands/fixmystreet/fixmystreet.js

Have two submit buttons, one of which displays at <48em, one of which displays at >=48em. Record desktop/mobile with report depending on which button is clicked.
If neither button is clicked, e.g. if they submit the form by hitting return (although spec says button should be clicked then? whatever), have a bit of fallback JS that sets the form field in the browser resize function.
If no-JS and no form button clicked, carry on storing nothing as now.

Record whether report made on desktop or mobile.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
t/app/controller/admin/bodies.t

If a category’s send method is Open311, only strip spaces from the
ends of the code. We are aware of active Open311 servers that have
codes with spaces in the middle.
Fixes #3167.

Don’t strip all spaces from Open311 categories.

---

perllib/FixMyStreet/App/Controller/Admin/Templates.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Integrations/Echo.pm
t/cobrand/bromley.t
templates/web/base/admin/templates/_external.html
templates/web/base/admin/templates/edit.html
templates/web/bromley/admin/templates/_external.html

Have the response template external status code be a combination
of resolution code, task type ID, and task state. [skip changelog]

[Bromley] Nuanced template resolution codes.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Admin/Bodies.pm
t/app/controller/admin/bodies.t

Show all category history even if category renamed

---

perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/FixMyStreet/Cobrand/EastSussex.pm
perllib/FixMyStreet/Cobrand/Greenwich.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
perllib/FixMyStreet/Cobrand/Northamptonshire.pm
perllib/FixMyStreet/Cobrand/Oxfordshire.pm
perllib/FixMyStreet/Cobrand/Peterborough.pm
perllib/FixMyStreet/Cobrand/Rutland.pm
perllib/FixMyStreet/Cobrand/Westminster.pm
perllib/FixMyStreet/Roles/ConfirmOpen311.pm
perllib/FixMyStreet/SendReport/Open311.pm

If a report had an existing, but empty, extra field that was looked up
on the server when being sent by Open311, the looked up information
would be added as an additional extra field, rather than replacing the
blank one. [skip changelog]

[UK] Prevent duplicate extra fields when blank.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_update.t

A report's confirmation timestamp uses current_timestamp, and so
includes microseconds. An initial update text, to fit in with the
Open311 handling of updates, uses a DateTime object, which does not.
This means if a report is created when logged in, the initial update
can have a timestamp earlier than the report, and so is not alerted on.

Fix email alert on initial update template.

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Offline.pm
t/app/controller/offline.t

As the contents vary if the user is logged in and depending on their
permissions we should not be caching the service worker. This sets the
Vary header to 'Cookie' to avoid this.

avoid caching the service worker for logged in users

---

docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/Cobrand/Bexley.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/cobrand/bexley.t
templates/web/base/report/_update_state.html

Always show body name on normal staff updates even if marked anonymous, give Bexley a different message, and tidy up the docs related to this area.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2002
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2003
~~Improvements to staff leaving report/updates, and display of body name. A staff user's update is always displayed as posted by the body user, but when making the update, the staff user is shown their own user's name and given the option of showing/not showing, which does not correspond with what then happens. So show the body name as the name that will be displayed so that's clear, always show a body name on a staff update (that isn't contribute as another user/anonymous user), and related change for …

Changes to updates left by staff

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

Adds a new Central Beds-specific `COBRAND_FEATURE` that maps between MapIt area codes and CBC's three highways teams areas.

[Central Beds] Include Symology area code param for Open311 reports

---

perllib/FixMyStreet/App/Controller/Noise.pm
perllib/FixMyStreet/App/Form/Noise.pm
t/app/controller/noise.t
templates/web/base/noise/summary.html

Add an extra question to the when screen to check if there's a pattern
to when the noise occurs, and only then ask about when, otherwise ask
for more information about when. To avoid people filling in all the day
and time boxes if there's no pattern.
For mysociety/fixmystreet-commercial#2015

[Noise] check if the noise follows a pattern

---

perllib/FixMyStreet/Cobrand/CheshireEast.pm

For https://github.com/mysociety/fixmystreet-commercial/issues/2028

[Cheshire East] Don’t show description of fetched reports

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
t/cobrand/centralbedfordshire.t
t/cobrand/hounslow.t
templates/web/fixmystreet-uk-councils/report/update/form_state_checkbox.html

Removes the "this problem has been fixed" tickbox from the update form. Factors out the same behaviour for TfL and Hounslow into a cobrand feature, and adds tests for it.
For https://github.com/mysociety/fixmystreet-commercial/issues/2017
For https://github.com/mysociety/fixmystreet-commercial/issues/2018

[Central Beds] Don't allow users to change report status

---

web/cobrands/centralbedfordshire/assets.js
web/cobrands/centralbedfordshire/base.scss

Adds street lighting and gullies asset layers. Also fixes an issue where the header prevented the "continue" button being shown on mobile when making a report.

[Central Beds] Add asset layers & fix mobile header

---

.cypress/cypress.json
.cypress/cypress/integration/borsetshire.js
.cypress/cypress/integration/duplicates.js
templates/web/borsetshire/auth/_general_top.html
web/cobrands/borsetshire/js.js

Three hopeful fixes, for three different things that sometimes but not always fail on Travis. [skip changelog]
The first fix, while a nice thing to do anyway, did not help, for some reason, looking at the video, on Travis the Inspector part of the test is submitting the form ok, must be logging in okay, redirecting to /my/planned, but that then thinks not logged in and redirects back to /auth?r=my/planned (can't see how else you end up at that URL instead anyway). Some cookie issue with the hostnames, or something? I dunno. I've added another commit to use links to log out and back in instead of using cy.visit(), shouldn't make any difference but will see. As intermittent, it passing first time doesn't mean it is fixed :-/ Cypress has many open cookie issues, e.g. …

Some hopeful Cypress Travis fixes

---

perllib/FixMyStreet/App/Controller/Noise.pm
perllib/FixMyStreet/App/Form/Noise.pm
t/app/controller/noise.t
templates/web/base/noise/summary.html

Instead of having a separate flow for known/unknown location have a
location search box and then show a list of addresses if they enter a
Hackney postcode, or the map page if we can't get a list of addresses.
For https://github.com/mysociety/fixmystreet-commercial/issues/2013

[Noise] ask directly for location rather than if know it

---

.github/workflows/coverage.yml
.github/workflows/cypress.yml
.github/workflows/default.yml

This pins the Ubuntu version on GitHub Actions, and adds coverage to the Cypress tests, posting to codecov same as the Perl tests, which is nice (even though it drops overall coverage to begin with!). [skip changelog]

Cypress coverage

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_new_open311.t

The code for deciding whether there were extra questions to answer
would always run, even if all the extra questions had been answered.

Fix non-JS form when all extra questions answered.

---

CHANGELOG.md
templates/web/base/report/_inspect.html

As extra questions can include limited HTML now, including `<p>`,
wrapping them in a `<p>` can lead to display issues.

Use div for inspector form wrapped extra questions

---

templates/web/fixmystreet-uk-councils/about/privacy.html

A couple of tweaks to the UK councils privacy policy wording for the Central Beds cobrand.
For https://github.com/mysociety/fixmystreet-commercial/issues/1991

[Central Beds] Privacy policy wording

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/Mock/MapIt.pm
t/cobrand/bexley.t

For some categories Bexley staff use a different URL from the public in
the notices. This allows the public URL in the notice to be replaced.

[Bexley] replace notice urls with staff specific ones

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
perllib/FixMyStreet/DB/Result/Problem.pm
t/cobrand/centralbedfordshire.t
templates/email/centralbedfordshire/_council_reference.html
templates/email/centralbedfordshire/_council_reference.txt
templates/email/centralbedfordshire/confirm_report_sent.html
templates/email/centralbedfordshire/confirm_report_sent.txt

A few things not picked up in testing:
- Show external Symology ID on report page
- Send email to user with Symology ID after report is sent
- Hide reports made before the cobrand launched.

[Central Beds] Post go-live tweaks

---

perllib/FixMyStreet/Cobrand/Hackney.pm

Reusing sent_to can cause an issue if a non-
split email report is marked for resending.

[Hackney] Use different variable for split sending

---

CHANGELOG.md
docs/running/admin_manual.md
perllib/FixMyStreet/App/Controller/Admin/EmergencyMessage.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/admin/emergencymessage.t
t/app/controller/admin/users.t
templates/web/base/admin/emergencymessage/edit.html
templates/web/base/admin/emergencymessage/index.html
templates/web/base/front/emergency-message.html
templates/web/base/front/pre-steps.html
web/cobrands/sass/_base.scss
web/cobrands/sass/_layout.scss

Add an `emergency_message` field to the Body's extra metadata which when set will display an emergency banner on the homepage.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/2023
This is just a first pass at this as I'm not sure if this is the best approach. Feedback very welcome!
Some thoughts:
- Is extra metadata on the Body the best place to store this?
- Does having a whole page in the admin for this seem excessive? I guess at least it's clear?
- I've added a separate permission for this as it seemed like something that not everyone should be able to do. Not sure if that's excessively cautious?
- Design could probably do with some work, I just copied the styles we're using on the [Bexley homepage](https://fix.bexley.gov.uk/) for their emergency banner.

Allow setting a custom emergency message on homepage

---

CHANGELOG.md
docs/_includes/admin-tasks-content.md
perllib/FixMyStreet/App/Controller/Admin.pm
perllib/FixMyStreet/App/Controller/Admin/Reports.pm
perllib/FixMyStreet/App/Controller/Admin/Users.pm
perllib/FixMyStreet/Cobrand/Default.pm
t/app/controller/admin/report_edit.t
t/app/controller/admin/update_edit.t
t/app/controller/admin/users.t
t/app/controller/auth.t
t/app/controller/auth_phone.t
t/app/controller/auth_profile.t
t/app/controller/report_new.t
t/app/controller/report_new_text.t
templates/web/base/admin/flagged.html
templates/web/base/admin/header.html
templates/web/base/admin/report_blocks.html
templates/web/base/admin/reports/edit.html
templates/web/base/admin/update_edit.html
templates/web/base/admin/users/_form_details.html
templates/web/base/admin/users/form.html
templates/web/zurich/admin/header.html

This moves the ban/flag buttons to the user edit admin, which seems a better place for them; and adds a link to the user admin from a report/update admin page. And tries to clarify that changing the name/user on a report/update changes it for that report/update, it isn't changing the user. And a fix to overflowing category dropdown when there are very long categories on report admin page.
Some of this has been done with inline styling that should be done properly, however that may be, help appreciated there :)

User edit admin link

---

templates/web/buckinghamshire/front/pre-steps.html
web/cobrands/buckinghamshire/base.scss
web/cobrands/buckinghamshire/layout.scss

This migrates the Buckinghamshire emergency banner over to the new system that allows them to update the content of the banner.
I've already added the text from the banner in the admin, so this should work when it's put live.
Should fix https://github.com/mysociety/fixmystreet-commercial/issues/2071

[Buckinghamshire] Migrate emergency banner to new system

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

Unlike others this is just a simple category lookup in the `open311_email` config to find a destination email address.

[Central Beds] Use open311_email cobrand feature to email certain Open311 reports

---

perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
t/cobrand/highwaysengland.t
templates/web/highwaysengland/about/_sidebar.html
templates/web/highwaysengland/about/faq-en-gb.html
templates/web/highwaysengland/about/privacy.html

- Remove links from help pages to /contact
- Switch on abuse_reports_only
- Respect contact_email cobrand feature instead of global CONTACT_EMAIL

[Highways England] Disable contact form & point links to HE site

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Open311.pm
t/app/controller/open311.t
templates/web/base/open311/index.html

Stop the JSON output using arrays where not needed (was fixed for requests back in 2017, looks like, but this was missed), and also include JSON links on the index page.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2106

Open311 JSON fixes

---

web/cobrands/fixmystreet/fixmystreet.js

If you e.g. look somewhere in Bristol on desktop, pick Bridges, click Continue, then click Back, the "Pick a bridge" message has now moved to the bottom of the page. We only want the message to look like that on mobile, it shouldn't have changed on desktop.

Fix class adding going Back on desktop reporting.

---

web/cobrands/sass/_layout.scss

Removes the z-index values from the sticky-sidebar and aside.
This doesn’t appear to affect anything else...
For #3287

Fix clicking of /about sidebar on desktop

---

perllib/FixMyStreet/Cobrand/FixMyStreet.pm
perllib/FixMyStreet/Cobrand/Hackney.pm
t/app/controller/noise.t

I guess we should add a new state or flag for contacts that hides them from normal flow which could then work for waste etc as well, but just for now to stop any more staff-made reports.

[Hackney] Hide noise category from normal flow.

---

perllib/FixMyStreet/DB/Result/Body.pm
t/cobrand/fixmystreet.t

Recently launched cobrands for councils who previously refused FMS reports
would see a misleadingly high figure in the ‘how responsive is ...’ section
on the councillor dashboard.
This commit respects the cobrand’s cut_off_date figure when calculating
these stats, meaning reports made before the cobrand launched are ignored.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2151

[fixmystreet.com] Respect cobrand’s cut_off_date on responsiveness stats

---

perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t

Fixes an issue preventing reports being made in categories whose group had trailing whitespace.

[Open311] Trim leading/trailing whitespace from service groups

---

perllib/Open311/PopulateServiceList.pm
t/open311/populate-service-list.t

Stores a flag in the contact’s extra indicating whether it should only appear on the waste workflow, and not the main report flow.
This will be used by the Peterborough cobrand as part of the waste product.

[Open311] Add support for waste_only service keyword

---

CHANGELOG.md
perllib/FixMyStreet/Script/Reports.pm
t/sendreport/failures.t

Also have a list of ids and order output so it's consistent to make
it a bit easier to scan.

add reports failed count to sendreports output

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Around.pm
perllib/FixMyStreet/Map.pm
t/map/tilma/original.t
web/cobrands/hackney/assets.js

And tiny unrelated Hackney thing. But mostly fixing the double Gaze call.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2063

Fix double Gaze call

---

CHANGELOG.md
bin/export-import-data

Makes it easier to compare. [skip changelog]

Sort output in export script.

---

.cypress/cypress/fixtures/banes-caro-group-housing-layer.json
.cypress/cypress/integration/bathnes.js
bin/fixmystreet.com/fixture
t/Mock/MapIt.pm
templates/web/bathnes/report/new/roads_message.html
templates/web/fixmystreet.com/report/new/roads_message.html
web/cobrands/bathnes/assets.js
web/cobrands/fixmystreet/assets.js

Adds a new asset layer containing housing association information. When a pin is dropped onto one of these housing association areas and it's in the category whitelist a warning message will be shown telling the user to email the housing association instead.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/2051

Banes housing layer restriction

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/Cobrand/Default.pm
templates/web/base/report/new/category_extras.html
templates/web/base/report/new/councils_text_all.html

The call was doing repeated loops of contacts to look up bodies and
hint texts, repeated database calls to check anonymous allowed, and
making lists of body names it did not need to in templates.

Pre-lookup some data for /report/new/ajax call.

---

perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/App/Controller/Develop.pm
t/app/controller/alert_new.t
templates/email/default/alert-subscribed.html
templates/email/default/alert-subscribed.txt

This adds a new email that is sent when someone is subscribed to email alerts by a member of staff. Councils sometimes use this when someone phones to report a problem and they enter it into the system.
The email that is sent contains an unsubscribe link so that users can stop receiving updates if they wish.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2049

Send email when staff member subscribes user to alerts

---

.gitattributes

Minor commit that makes GitHub's linguist language detection correctly identify all the .pm and .t files as Perl rather than Raku.
Added as a nicety, mainly as trying to identify why ./script/test has failing tests in my vagrant vm, but this commit when tested via CI on github actions all tests pass.

Make GitHub detect the Perl correctly.

---

perllib/FixMyStreet/App/Controller/Report.pm
perllib/FixMyStreet/Script/TfL/AutoClose.pm
t/app/controller/report_inspect.t
t/script/tfl/autoclose.t

- Don't skip reports that have comments with empty `problem_state` value
- Ensure `problem_state` is always set when leaving comments via the inspector form
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2208

[TfL] Ensure all relevant ‘action scheduled’ reports are auto-closed

---

perllib/FixMyStreet/App/Controller/Open311.pm
t/app/controller/open311.t
templates/web/base/open311/index.html

Makes the open311 documentation at https://www.zueriwieneu.ch/open311 more Zurich-specific.
Fixes https://github.com/mysociety/fixmystreet/issues/3288
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2150

[Zurich] Open311 docs changes

---

perllib/FixMyStreet/Cobrand/Bexley.pm
t/Mock/MapIt.pm
t/cobrand/bexley.t
templates/web/base/report/new/form_user_loggedin.html
templates/web/bexley/report/form/private_comments.html

This allows staff to add private comments to a report when creating it.
Your user will need to have the `contribute_as_body` permission in order to see this box.
open311-adapter changes are in https://github.com/mysociety/open311-adapter/pull/156
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1850
---

[Bexley] Add private comments field to report form

---

perllib/FixMyStreet/Cobrand/CentralBedfordshire.pm
t/cobrand/centralbedfordshire.t

Sometimes the nearest feature has a NULL `streetref1` property but there is an overlapping feature that correctly has a `streetref1` value a very small distance away. To avoid choosing the feature with an empty `streetref1` we reject those features, forcing selection of the nearest feature that has a valid value.
For https://github.com/mysociety/fixmystreet-commercial/issues/2231

[Central Beds] Ignore invalid features when doing server-side NSGRef lookup

---

CHANGELOG.md
bin/update-schema
db/downgrade_0075---0074.sql
db/schema.sql
db/schema_0075-add-alert-parameter3.sql
perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/DB/Result/Alert.pm
perllib/FixMyStreet/Script/Alerts.pm
t/app/controller/alert.t
t/app/controller/alert_new.t
t/cobrand/fiksgatami.t
templates/web/base/alert/_list.html
templates/web/base/alert/_list_rss_local.html
templates/web/cheshireeast/alert/_list_rss_local.html
web/cobrands/fixmystreet/fixmystreet.js
web/cobrands/sass/_base.scss

Allow email alert radius to be specified.

---

CHANGELOG.md
web/js/map-OpenLayers.js

Wasn't sure if there was a reason we didn't do this when we did around/reports back in https://github.com/mysociety/fixmystreet/pull/2301 but a user has asked if they can have a "home location" when viewing their previous reports and this would be the easiest way of doing so, I think.

Update URL on /my when map moves.

---

perllib/FixMyStreet.pm

Avoids the odd warning in tests

check if staging flags are defined

---

perllib/FixMyStreet/App/Controller/Report.pm
templates/web/base/maps/_compass.html
templates/web/base/maps/openlayers.html

Removes the HTML compass from report pages because there isn't really any point in panning the map (I guess you might want to zoom in/out, which could maintain if wanted, but easier to drop both), and fixes the road map toggle button if at an aerial=1 URL.

Map control updates

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Alert.pm
perllib/FixMyStreet/App/Controller/Tokens.pm
perllib/FixMyStreet/DB/Result/User.pm
perllib/FixMyStreet/Script/Alerts.pm
t/app/controller/alert_new.t
templates/web/base/alert/_list.html
templates/web/base/alert/_updates.html
templates/web/base/alert/updates.html
templates/web/base/report/display_tools.html
templates/web/base/tokens/confirm_alert.html

Improves the text on update alert signup for phone-only users (stops referring to email alerts), and fixes an issue whereby a phone-only user could sign up for a local alert but wouldn't ever get anything, so instead ask for email and do a merge, like the verify email step would do, if that makes sense. [skip changelog]

Email alert text updates

---

perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste/Garden.pm
t/app/controller/waste.t

Apart from cancellation all subscription actions use the same event code
in Echo so don't have different categories for each one

[Bromley] use a single category for subscriptions

---

perllib/FixMyStreet/Cobrand/Greenwich.pm

Greenwich now have a new open311 endpoint which returns useful groups, so stop blanking out groups when fetching contacts for Greenwich.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/2058

[Greenwich] Re-enable open311 groups

---

perllib/FixMyStreet/Cobrand/Bromley.pm
t/app/controller/waste.t

When a service task is cancelled and then later renewed you end up with
multiple service task schedules which we need to handle by using the one
with the latest end date for the current schedule

[Bromley] handle service tasks with multiple schedules

---

CHANGELOG.md
perllib/FixMyStreet/App/Controller/Report/New.pm
t/app/controller/report_as_other.t

This is similar to reporting as anonymous, in that it uses the staff user account, except you could have provided a different name. (Also see previous commit de8084885daffd3f4203cc46cfa3edf4d0a1dc0d)

No questionnaires if reported as other, no details

---

CHANGELOG.md
perllib/FixMyStreet/Cobrand/HighwaysEngland.pm
perllib/FixMyStreet/Reporting.pm
t/app/controller/dashboard.t
t/cobrand/bathnes.t
t/cobrand/bucks.t
t/cobrand/highwaysengland.t
t/cobrand/oxfordshire.t

Since we started recording mobile/desktop website use in service, Site Used now contains that, rather than the cobrand used. Rename Site Used to Device Type (and only show service column), and add a new Site Used column that always contains the cobrand used. (This was already done for the Highways England cobrand.)

CSV export, improve Site Used and add Device Type.

---

perllib/FixMyStreet/Cobrand/FixaMinGata.pm
perllib/FixMyStreet/DB/Result/Comment.pm
t/cobrand/fixamingata.t

Some background:
For FixaMinGata we've shown the names of staff users in their updates. This has been a wish from some of our municipalities, although some have disagreed (leading some staff users to change their names to just first name or something anonymous).
We've started using the functionality now where a staff user can create update "as body" rather than "as myself", I was hoping this would solve the problem by giving the user the choice of who's shown as the source of the comment.
I had assumed when creating an update "as body", only the body name was shown, but because of our override in our cobrand's `always_view_body_contribute_details` , both body name and staff user name was shown regardless of how the update was made.
However removing our override instead leads to only the …

Let the cobrand function always_view_body_contribute_details take contributed_as into account

---

perllib/FixMyStreet/App/Controller/Admin/Triage.pm
t/app/controller/admin/triage.t

Prevent the user from unsetting the category when triaging a report.

do not allow blank category on triage

---

web/cobrands/cheshireeast/assets.js

Cheshire East have been in touch to say that the change in https://github.com/mysociety/fixmystreet/pull/3232 to allow reports in cleaning categories to be made anywhere isn't working.
After a bit of investigation it turns out that the original code was written and reviewed before the change that introduced the `selectedCategory` helper function, but was merged into master without being re-reviewed (my bad).
So this changes the code to use the new helper function so it works as expected.
Follows on from the original PR that introduced this change: https://github.com/mysociety/fixmystreet/pull/3232
Related to https://github.com/mysociety/fixmystreet-commercial/issues/2239

[CheshireEast] Use new selectedCategory method in JS

---

.cypress/cypress/fixtures/westminster-street-entertainment.json
.cypress/cypress/integration/westminster.js
bin/fixmystreet.com/fixture
t/Mock/MapIt.pm
templates/web/westminster/footer_extra_js.html
web/cobrands/westminster/assets.js
web/cobrands/westminster/js.js

Adds an asset layer for street entertainment pitches. When a pitch is selected the name and terms and conditions are displayed.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2222
https://user-images.githubusercontent.com/22996/113185311-363cf100-924e-11eb-99b3-263fa246ca89.mov

[Westminster] Street Entertainment custom text

---

perllib/FixMyStreet/Cobrand/Bromley.pm
perllib/Open311/UpdatesBase.pm
t/cobrand/bromley.t
templates/web/base/waste/bin_days.html

Fix admin template setting by making sure blank external status is actually blank; show more task states than just in progress (e.g. delayed should be shown), and prefer templates over description (don't want to just blank out description as don't know if templates will be created for all states, though I guess they probably will be). [skip changelog]

[Bromley] Some waste fixes 

---

perllib/FixMyStreet/App/Controller/Noise.pm
perllib/FixMyStreet/App/Controller/Report/New.pm
perllib/FixMyStreet/App/Controller/Waste.pm
perllib/FixMyStreet/App/Form/Waste.pm
perllib/FixMyStreet/App/Form/Waste/AboutYou.pm
perllib/FixMyStreet/App/Form/Waste/Report.pm
perllib/FixMyStreet/App/Form/Waste/Request.pm
t/app/controller/waste.t
templates/web/base/waste/confirmation.html

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2272 [skip changelog]
The first four commits set things up for multiple reports being created/confirmed in one go and having a different confirmation template, then we make sure email given, and the final commit switches to using the normal confirmation flow.
The way it works is the first report (which is the 'key' one with the confirmation token associated with it etc) also stores the subsequent report IDs in its metadata, then when it's confirmed it looks up and confirms its grouped reports.

[Waste] Verify email address

---

web/cobrands/buckinghamshire/assets.js
web/cobrands/fixmystreet/assets.js

plus a small tweak to enable multiple asset item placeholders in message string.
[skip changlog]

[Buckinghamshire] make it clear only bucks streelights are displayed
